/-
# Linglib

A Lean 4 library for formal linguistics, covering semantics, pragmatics,
and their interfaces. See README.md for documentation links.
-/

-- Core
import Linglib.Core.Basic
import Linglib.Core.Pronouns
import Linglib.Core.Kleene
import Linglib.Core.Empirical
import Linglib.Core.Proposition
import Linglib.Core.UD
import Linglib.Core.Duality
import Linglib.Core.Quantification
import Linglib.Core.HornScale
import Linglib.Core.Intension
import Linglib.Core.ModalLogic
import Linglib.Core.Conjectures
import Linglib.Core.CommonGround
import Linglib.Core.Parse
import Linglib.Core.Presupposition
import Linglib.Core.ProductOfExperts
import Linglib.Core.Partition
import Linglib.Core.PolarityPartition
import Linglib.Core.QUD
import Linglib.Core.Interfaces.BindingSemantics
import Linglib.Core.Interfaces.CoreferenceTheory
import Linglib.Core.Interfaces.ImplicatureTheory
import Linglib.Core.Interfaces.ScopeTheory
import Linglib.Core.Interfaces.CombinationSchema
import Linglib.Core.Interfaces.FelicityCondition
import Linglib.Core.Interfaces.SemanticStructure
import Linglib.Core.Causation
import Linglib.Core.RootDimensions
import Linglib.Core.Verbs
import Linglib.Core.NaturalLogic
import Linglib.Core.DecisionTheory
import Linglib.Core.Evidence
import Linglib.Core.ProcessingModel
import Linglib.Core.Alternatives
import Linglib.Core.Time
import Linglib.Core.Reichenbach
import Linglib.Core.Context
import Linglib.Core.InformationStructure
import Linglib.Core.Prosody
import Linglib.Core.Definiteness
import Linglib.Core.NounCategorization
import Linglib.Core.Roundness
import Linglib.Core.Mereology
import Linglib.Core.Continuation
import Linglib.Core.PersonCategory
import Linglib.Core.Morphology.MorphRule
import Linglib.Core.Morphology.Degree
import Linglib.Core.Morphology.Number
import Linglib.Core.Morphology.ScaleFromParadigm
import Linglib.Core.Morphology.StemToLex
import Linglib.Core.Morphology.Tense
import Linglib.Core.Morphology.Aspect
import Linglib.Core.DiscourseRole

-- Fragments
import Linglib.Fragments.Dutch.Nouns
import Linglib.Fragments.Dutch.Particles
import Linglib.Fragments.English.Determiners
import Linglib.Fragments.English.FunctionWords
import Linglib.Fragments.English.MeasurePhrases
import Linglib.Fragments.English.NumeralModifiers
import Linglib.Fragments.English.Lexicon
import Linglib.Fragments.English.Modifiers.Adjectives
import Linglib.Fragments.English.Nouns
import Linglib.Fragments.English.PolarityItems
import Linglib.Fragments.English.Predicates
import Linglib.Fragments.English.Predicates.Adjectival
import Linglib.Fragments.English.Predicates.Verbal
import Linglib.Fragments.English.Pronouns
import Linglib.Fragments.English.Scales
import Linglib.Fragments.English.Tense
import Linglib.Fragments.English.TemporalExpressions
import Linglib.Fragments.Bulgarian.Evidentials
import Linglib.Fragments.Czech.Determiners
import Linglib.Fragments.Czech.Particles
import Linglib.Fragments.Farsi.Determiners
import Linglib.Fragments.German.PolarityMarking
import Linglib.Fragments.German.Predicates
import Linglib.Fragments.German.Predicates.Modal
import Linglib.Fragments.Georgian.Coordination
import Linglib.Fragments.HindiUrdu.Particles
import Linglib.Fragments.Hungarian.Coordination
import Linglib.Fragments.French.Nouns
import Linglib.Fragments.French.Predicates
import Linglib.Fragments.Irish.Coordination
import Linglib.Fragments.Latin.Coordination
import Linglib.Fragments.Japanese.Determiners
import Linglib.Fragments.Japanese.Classifiers
import Linglib.Fragments.Japanese.Nouns
import Linglib.Fragments.Korean.Evidentials
import Linglib.Fragments.Korean.Predicates
import Linglib.Fragments.Japanese.Particles
import Linglib.Fragments.Japanese.Predicates
import Linglib.Fragments.Mandarin.Determiners
import Linglib.Fragments.Mandarin.Classifiers
import Linglib.Fragments.Mandarin.Nouns
import Linglib.Fragments.Mandarin.Particles
import Linglib.Fragments.Mandarin.Predicates
import Linglib.Fragments.Turkish.Predicates
import Linglib.Fragments.Basque.Pronouns
import Linglib.Fragments.Magahi.Pronouns
import Linglib.Fragments.Korean.Pronouns
import Linglib.Fragments.Japanese.Pronouns
import Linglib.Fragments.Tamil.Pronouns
import Linglib.Fragments.Galician.Pronouns
import Linglib.Fragments.Hindi.Pronouns
import Linglib.Fragments.Maithili.Pronouns
import Linglib.Fragments.Punjabi.Pronouns
import Linglib.Fragments.Tagalog.TemporalConnectives
import Linglib.Fragments.Spanish.Clitics
import Linglib.Fragments.Spanish.Predicates
import Linglib.Fragments.Spanish.PersonFeatures

-- Phenomena
import Linglib.Phenomena.SpalekMcNally.Data
import Linglib.Phenomena.AlstottAravind2026.Data
import Linglib.Phenomena.TurcoBraunDimroth2014.Data
import Linglib.Phenomena.TemporalConnectives.ExamplesBridge
import Linglib.Phenomena.AdditiveParticles.Data
import Linglib.Phenomena.AdditiveParticles.Studies.Thomas2026
import Linglib.Phenomena.Agreement.Basic
import Linglib.Phenomena.Agreement.Case
import Linglib.Phenomena.Agreement.DetNoun
import Linglib.Phenomena.Attitudes.IntensionalExamplesBridge
import Linglib.Phenomena.Anaphora.BathroomSentences
import Linglib.Phenomena.Anaphora.Bridging
import Linglib.Phenomena.Anaphora.Coreference
import Linglib.Phenomena.Anaphora.CrossSentential
import Linglib.Phenomena.Anaphora.DonkeyAnaphora
import Linglib.Phenomena.Anaphora.ModalSubordination
import Linglib.Phenomena.Anaphora.PronounTypology
import Linglib.Phenomena.Anaphora.Studies.ParasiticAttitudes
import Linglib.Phenomena.ArgumentStructure.DativeAlternation
import Linglib.Phenomena.ArgumentStructure.Passive
import Linglib.Phenomena.ArgumentStructure.Subcategorization
import Linglib.Phenomena.ArgumentativeFraming.Data
import Linglib.Phenomena.ActualityInferences.Data
import Linglib.Phenomena.Aspect.DiagnosticsBridge
import Linglib.Phenomena.AuxiliaryVerbs.Diagnostics
import Linglib.Phenomena.AuxiliaryVerbs.NegativeAuxiliaries
import Linglib.Phenomena.AuxiliaryVerbs.Selection
import Linglib.Phenomena.AuxiliaryVerbs.SelectionBridge
import Linglib.Phenomena.AuxiliaryVerbs.Typology
import Linglib.Phenomena.Charlow2021.Data
import Linglib.Phenomena.Charlow2021.CumulativeReadingsBridge
import Linglib.Phenomena.Cumming2026.Bridge
import Linglib.Phenomena.Lakoff1970.Data
import Linglib.Phenomena.Lakoff1970.Bridge
import Linglib.Phenomena.Conditionals.Data
import Linglib.Phenomena.Conditionals.LeftNested
import Linglib.Phenomena.Conditionals.Studies.GrusdtLassiterFranke2022
import Linglib.Phenomena.Conditionals.Studies.RamotowskaEtAl2025
import Linglib.Phenomena.Conditionals.Studies.SubordinateFuture
import Linglib.Phenomena.Complementation.Bridge
import Linglib.Phenomena.Complementation.Typology
import Linglib.Phenomena.Constructions.Studies.FillmoreKayOConnor1988
import Linglib.Phenomena.Constructions.Studies.GoldbergShirtz2025
import Linglib.Phenomena.Constructions.Studies.KayFillmore1999
import Linglib.Phenomena.Constructions.Resultatives.Data
import Linglib.Phenomena.ChangeOfState.Typology
import Linglib.Phenomena.Causatives.Data
import Linglib.Phenomena.Causatives.Typology
import Linglib.Phenomena.Causatives.ThickThinBridge
import Linglib.Phenomena.Causatives.StructuralCausationBridge
import Linglib.Phenomena.MunozPerez2026.Data
import Linglib.Phenomena.MunozPerez2026.Bridge
import Linglib.Phenomena.Coordination.Data
import Linglib.Phenomena.Coordination.Studies.BillEtAl2025
import Linglib.Phenomena.Coordination.Studies.BillEtAl2025Bridge
import Linglib.Phenomena.Coordination.Typology
import Linglib.Phenomena.DependencyLength.FutrellEtAl2020
import Linglib.Phenomena.Ellipsis.FragmentAnswers
import Linglib.Phenomena.Ellipsis.Gapping
import Linglib.Phenomena.Ellipsis.Sluicing
import Linglib.Phenomena.Entailment.Basic
import Linglib.Phenomena.Entailment.Monotonicity
import Linglib.Phenomena.FillerGap.Basic
import Linglib.Phenomena.FillerGap.CrossSerial
import Linglib.Phenomena.FillerGap.LongDistance
import Linglib.Phenomena.Focus.Basic
import Linglib.Phenomena.Focus.PolarityStress
import Linglib.Phenomena.Focus.ProsodicExhaustivity
import Linglib.Phenomena.Generics.BareNames
import Linglib.Phenomena.Generics.BarePlurals
import Linglib.Phenomena.Generics.Data
import Linglib.Phenomena.Generics.KindReference
import Linglib.Phenomena.Gradability.Adjectives
import Linglib.Phenomena.Gradability.Basic
import Linglib.Phenomena.Gradability.ComparisonClass
import Linglib.Phenomena.Gradability.Evaluativity
import Linglib.Phenomena.Gradability.Studies.KursatDegen2021
import Linglib.Phenomena.Gradability.Studies.KursatDegen2021Bridge
import Linglib.Phenomena.Gradability.IntensifiersBridge
import Linglib.Phenomena.Gradability.Vagueness
import Linglib.Phenomena.Humor.Studies.KaoEtAl2016
import Linglib.Phenomena.Imperatives.Studies.SumersEtAl2023
import Linglib.Phenomena.Imprecision.Basic
import Linglib.Phenomena.Imprecision.FormMeaning
import Linglib.Phenomena.Imprecision.InferencePreservation
import Linglib.Phenomena.Imprecision.Numerals
import Linglib.Phenomena.NumberUse.WoodinEtAl2024
import Linglib.Phenomena.Imprecision.Studies.EgreEtAl2023
import Linglib.Phenomena.Imprecision.Projection
import Linglib.Phenomena.Islands.Data
import Linglib.Phenomena.Islands.MannerOfSpeaking
import Linglib.Phenomena.Metaphor.Studies.KaoBergenGoodman2014
import Linglib.Phenomena.NumeralModification.ClausWalch2024
import Linglib.Phenomena.NumeralSemantics.Snyder2026Bridge
import Linglib.Phenomena.NumeralModification.Embedding
import Linglib.Phenomena.MeasurePhrases.BaleSchwarz2026Bridge
import Linglib.Phenomena.MeasurePhrases.Scontras2014Bridge
import Linglib.Phenomena.ConditionalModality.Data
import Linglib.Phenomena.ConditionalModality.Bridge
import Linglib.Phenomena.Modality.Basic
import Linglib.Phenomena.Modality.EpistemicEvidentiality
import Linglib.Phenomena.Modality.FreeChoice
import Linglib.Phenomena.Modality.PracticalReasoning
import Linglib.Phenomena.Modality.InformationalBackgrounds
import Linglib.Phenomena.Modality.DegreeCollapse
import Linglib.Phenomena.Modality.GermanModalsBridge
import Linglib.Phenomena.Modality.Studies.FreeChoiceFarsi
import Linglib.Phenomena.Modality.Studies.Khoo2015
import Linglib.Phenomena.Modality.Studies.Khoo2015Bridge
import Linglib.Phenomena.Modality.TypologyBridge
import Linglib.Phenomena.Negation.Basic
import Linglib.Phenomena.Negation.ExpletiveNegationBridge
import Linglib.Phenomena.NonProjectivity.Data
import Linglib.Phenomena.Negation.DoubleNegation
import Linglib.Phenomena.Negation.CzechThreeWayNeg
import Linglib.Phenomena.Negation.CzechThreeWayNeg.TypologyBridge
import Linglib.Phenomena.Negation.FlexibleNegation
import Linglib.Phenomena.Morphology.Composition
import Linglib.Phenomena.Morphology.DegreeComposition
import Linglib.Phenomena.Morphology.ZwickyPullum1983Bridge
import Linglib.Phenomena.StankovaSimik2024.Data
import Linglib.Phenomena.Plurals.Basic
import Linglib.Phenomena.Plurals.Homogeneity
import Linglib.Phenomena.Plurals.NonMaximality
import Linglib.Phenomena.Plurals.Studies.HaslingerEtAl2025Bridge
import Linglib.Phenomena.Plurals.Studies.QingEtAl2025
import Linglib.Phenomena.Polarity.Basic
import Linglib.Phenomena.Polarity.DisjunctionIgnorance
import Linglib.Phenomena.Polarity.Exceptives
import Linglib.Phenomena.Polarity.NPIs
import Linglib.Phenomena.Polarity.Studies.Schwab2022
import Linglib.Phenomena.Polarity.VonFintel1999
import Linglib.Phenomena.Honorifics.Data
import Linglib.Phenomena.Politeness.Studies.MachinoEtAl2025
import Linglib.Phenomena.Politeness.Studies.MachinoEtAl2025Bridge
import Linglib.Phenomena.Politeness.Studies.YoonEtAl2020
import Linglib.Phenomena.Presupposition.Basic
import Linglib.Phenomena.Presupposition.Diagnostics
import Linglib.Phenomena.Presupposition.ProjectiveContent
import Linglib.Phenomena.Presupposition.Studies.DegenTonhauser2021
import Linglib.Phenomena.Presupposition.Studies.HeKaiserIskarous2025
import Linglib.Phenomena.Presupposition.Studies.LoGuercio2025
import Linglib.Phenomena.Presupposition.Studies.ScontrasTonhauser2025
import Linglib.Phenomena.Presupposition.Studies.Wang2025
import Linglib.Phenomena.Presupposition.Studies.Yagi2025
import Linglib.Phenomena.OutlookMarkers.Kubota2026
import Linglib.Phenomena.Agreement.NounCategorization
import Linglib.Phenomena.Agreement.NounCategorizationBridge
import Linglib.Phenomena.Agreement.PersonMarkingTypology
import Linglib.Phenomena.Quantification.Basic
import Linglib.Phenomena.Quantification.Data
import Linglib.Phenomena.Quantification.ExamplesBridge
import Linglib.Phenomena.Quantification.Typology
import Linglib.Phenomena.Quantification.Bridge
import Linglib.Phenomena.Quantification.Studies.FrankeBergen2020
import Linglib.Phenomena.Quantification.Studies.ScontrasPearl2021
import Linglib.Phenomena.Questions.Basic
import Linglib.Phenomena.Questions.Typology
import Linglib.Phenomena.Questions.Embedding
import Linglib.Phenomena.Questions.Coordination
import Linglib.Phenomena.Questions.Exhaustivity
import Linglib.Phenomena.Questions.FocusAnswer
import Linglib.Phenomena.Questions.MentionSome
import Linglib.Phenomena.Questions.MultipleWh
import Linglib.Phenomena.Questions.NandaoQs
import Linglib.Phenomena.Questions.NandaoQsBridge
import Linglib.Phenomena.Questions.NegativeQuestions
import Linglib.Phenomena.Questions.PolarAnswers
import Linglib.Phenomena.Questions.PragmaticAnswerhood
import Linglib.Phenomena.Questions.ScopeReadings
import Linglib.Phenomena.Questions.SlavicPQStrategies
import Linglib.Phenomena.Questions.Studies.HawkinsEtAl2025
import Linglib.Phenomena.Questions.WhComplement
import Linglib.Phenomena.Reference.DirectReference
import Linglib.Phenomena.Reference.Studies.FrankGoodman2012
import Linglib.Phenomena.Reference.Studies.HawkinsGweonGoodman2021
import Linglib.Phenomena.ScalarImplicatures.Basic
import Linglib.Phenomena.ScalarImplicatures.Studies.CremersWilcoxSpector2023
import Linglib.Phenomena.ScalarImplicatures.Studies.GeurtsPouscoulous2009
import Linglib.Phenomena.ScalarImplicatures.Studies.GoodmanStuhlmuller2013
import Linglib.Phenomena.ScalarImplicatures.Studies.Ronai2024
import Linglib.Phenomena.ScalarImplicatures.Studies.VanTielEtAl2016
import Linglib.Phenomena.ScalarImplicatures.Studies.VanTielEtAl2021
import Linglib.Phenomena.SequenceOfTense.Data
import Linglib.Phenomena.SequenceOfTense.Bridge
import Linglib.Phenomena.WordOrder.Basic
import Linglib.Phenomena.WordOrder.SubjectAuxInversion
import Linglib.Phenomena.WordOrder.Typology
import Linglib.Phenomena.WordOrder.VerbPosition
import Linglib.Phenomena.WordOrder.Gradience
import Linglib.Phenomena.WordOrder.HahnDegenFutrell2021
import Linglib.Phenomena.TemporalAdverbials.Rouillard2026Bridge
import Linglib.Phenomena.WeakEvidenceEffect.Data

-- Theories: CCG
import Linglib.Theories.CCG.Core.Basic
import Linglib.Theories.CCG.Core.Combinators
import Linglib.Theories.CCG.Core.FromFragments
import Linglib.Theories.CCG.Bridge.Interface
import Linglib.Theories.CCG.Bridge.Homomorphism
import Linglib.Theories.CCG.Bridge.Derivation
import Linglib.Theories.CCG.Phenomena.Agreement
import Linglib.Theories.CCG.Phenomena.Coordination
import Linglib.Theories.CCG.Phenomena.CrossSerial
import Linglib.Theories.CCG.Phenomena.Derivations
import Linglib.Theories.CCG.Phenomena.Gapping
import Linglib.Theories.CCG.Phenomena.TruthConditions
import Linglib.Theories.CCG.Formal.Equivalence
import Linglib.Theories.CCG.Formal.FormalLanguageTheory
import Linglib.Theories.CCG.Formal.GenerativeCapacity
import Linglib.Theories.CCG.Phenomena.Scope
import Linglib.Theories.CCG.Phenomena.Intonation

-- Comparisons (cross-theory)
import Linglib.Comparisons.CommandRelations
import Linglib.Comparisons.FreeChoice.Aloni2022
import Linglib.Comparisons.FreeChoice.Compare
import Linglib.Comparisons.GenericSemantics
import Linglib.Comparisons.Implicature
import Linglib.Comparisons.KindReference
import Linglib.Comparisons.PolarQuestions
import Linglib.Comparisons.PresuppositionProjection
import Linglib.Comparisons.RelevanceTheories
import Linglib.Comparisons.RSAandPDS
import Linglib.Comparisons.RSAExhExpressivity
import Linglib.Comparisons.RSANeoGricean
import Linglib.Comparisons.SauerlandRSA
import Linglib.Comparisons.ScalarImplicature
import Linglib.Comparisons.Islands
import Linglib.Comparisons.ScopeFreezing
import Linglib.Comparisons.SDSandRSA
import Linglib.Comparisons.Mueller2013
import Linglib.Comparisons.NumeralSalience
import Linglib.Comparisons.ThresholdSemantics
import Linglib.Comparisons.ResultativeArgLicensing
import Linglib.Comparisons.VaguenessTheories
import Linglib.Comparisons.CausativeAlternation
import Linglib.Comparisons.BeforeAfter
import Linglib.Comparisons.CumulativeReadings
import Linglib.Comparisons.TenseModalEvidentiality

-- Theories: Dependency Grammar
import Linglib.Theories.DependencyGrammar.Core.Basic
import Linglib.Theories.DependencyGrammar.Core.LexicalRules
import Linglib.Theories.DependencyGrammar.Core.Nominal
import Linglib.Theories.DependencyGrammar.Formal.HeadCriteria
import Linglib.Theories.DependencyGrammar.Formal.DependencyLength
import Linglib.Theories.DependencyGrammar.Formal.HarmonicOrder
import Linglib.Theories.DependencyGrammar.Formal.Catena
import Linglib.Theories.DependencyGrammar.Formal.EnhancedDependencies
import Linglib.Theories.DependencyGrammar.Formal.VPDivergence
import Linglib.Theories.DependencyGrammar.Formal.NonProjective
import Linglib.Theories.DependencyGrammar.Formal.Government
import Linglib.Theories.DependencyGrammar.Formal.Ellipsis
import Linglib.Theories.DependencyGrammar.Formal.Discontinuity
import Linglib.Theories.DependencyGrammar.Formal.Islands
import Linglib.Theories.DependencyGrammar.Formal.CoordinationParallelism
import Linglib.Theories.DependencyGrammar.Formal.MemorySurprisal.Basic
import Linglib.Theories.DependencyGrammar.Formal.MemorySurprisal.FedzechkinaEtAl2017
import Linglib.Theories.DependencyGrammar.Formal.MemorySurprisal.CrossLinguistic
import Linglib.Theories.DependencyGrammar.Formal.MemorySurprisal.MorphemeOrder
import Linglib.Theories.DependencyGrammar.Phenomena.Coordination
import Linglib.Theories.DependencyGrammar.Phenomena.Coreference
import Linglib.Theories.DependencyGrammar.Phenomena.CRDC
import Linglib.Theories.DependencyGrammar.Phenomena.Inversion
import Linglib.Theories.DependencyGrammar.Phenomena.LongDistance

-- Theories: Dynamic Semantics
-- Theories: Dynamic Semantics — Core
import Linglib.Theories.DynamicSemantics.Core.Basic
import Linglib.Theories.DynamicSemantics.Core.CCP
import Linglib.Theories.DynamicSemantics.Core.DiscourseRef
import Linglib.Theories.DynamicSemantics.Core.DynamicTy2
import Linglib.Theories.DynamicSemantics.Core.Translation
import Linglib.Theories.DynamicSemantics.Core.Update
-- Theories: Dynamic Semantics — Effects
import Linglib.Theories.DynamicSemantics.Effects.State.Basic
import Linglib.Theories.DynamicSemantics.Effects.State.DPL
import Linglib.Theories.DynamicSemantics.Effects.State.DPLBridge
import Linglib.Theories.DynamicSemantics.Effects.State.DRT
import Linglib.Theories.DynamicSemantics.Effects.Nondeterminism.Basic
import Linglib.Theories.DynamicSemantics.Effects.Nondeterminism.Charlow2019
import Linglib.Theories.DynamicSemantics.Effects.Nondeterminism.PointwiseUpdate
import Linglib.Theories.DynamicSemantics.Effects.Continuation.Basic
import Linglib.Theories.DynamicSemantics.Effects.Bilateral.Basic
import Linglib.Theories.DynamicSemantics.Effects.Bilateral.FreeChoice
import Linglib.Theories.DynamicSemantics.Effects.Probability.Basic
import Linglib.Theories.DynamicSemantics.Effects.Epistemic.Basic
-- Theories: Dynamic Semantics — Systems
import Linglib.Theories.DynamicSemantics.Systems.BUS.Basic
import Linglib.Theories.DynamicSemantics.Systems.BUS.DynamicTy2
import Linglib.Theories.DynamicSemantics.Systems.CDRT.Basic
import Linglib.Theories.DynamicSemantics.Systems.CDRT.DynamicTy2
import Linglib.Theories.DynamicSemantics.Systems.DynamicGQ.Basic
import Linglib.Theories.DynamicSemantics.Systems.DynamicGQ.UpdateTheoretic
import Linglib.Theories.DynamicSemantics.Systems.DynamicGQ.HigherOrder
import Linglib.Theories.DynamicSemantics.Systems.DynamicGQ.SubtypePolymorphism
import Linglib.Theories.DynamicSemantics.Systems.DynamicGQ.PostSuppositional
import Linglib.Theories.DynamicSemantics.Systems.IntensionalCDRT.Basic
import Linglib.Theories.DynamicSemantics.Systems.IntensionalCDRT.Connectives
import Linglib.Theories.DynamicSemantics.Systems.IntensionalCDRT.MendesDerivations
import Linglib.Theories.DynamicSemantics.Systems.IntensionalCDRT.ModalDonkeyAnaphora
import Linglib.Theories.DynamicSemantics.Systems.IntensionalCDRT.PresuppositionWeakening
import Linglib.Theories.DynamicSemantics.Systems.IntensionalCDRT.Situations
import Linglib.Theories.DynamicSemantics.Systems.IntensionalCDRT.Update
import Linglib.Theories.DynamicSemantics.Systems.PLA.Basic
import Linglib.Theories.DynamicSemantics.Systems.PLA.Belief
import Linglib.Theories.DynamicSemantics.Systems.PLA.DeepTheorems
import Linglib.Theories.DynamicSemantics.Systems.PLA.DynamicTy2
import Linglib.Theories.DynamicSemantics.Systems.PLA.Epistemic
import Linglib.Theories.DynamicSemantics.Systems.PLA.Quantifiers
import Linglib.Theories.DynamicSemantics.Systems.PLA.Semantics
import Linglib.Theories.DynamicSemantics.Systems.PLA.Update
-- Theories: Dynamic Semantics — Comparisons & top-level
import Linglib.Theories.DynamicSemantics.Comparisons.PLA_BUS
import Linglib.Theories.DynamicSemantics.State
import Linglib.Theories.DynamicSemantics.TeamSemantics
-- Theories: TTR (Type Theory with Records)
import Linglib.Theories.TTR.Core
import Linglib.Theories.TTR.Discourse
import Linglib.Theories.TTR.Modality
import Linglib.Theories.TTR.Quantification
import Linglib.Theories.TTR.Underspecification

-- Theories: Construction Grammar
import Linglib.Theories.ConstructionGrammar.Basic
import Linglib.Theories.ConstructionGrammar.Studies.FillmoreKayOConnor1988
import Linglib.Theories.ConstructionGrammar.Studies.GoldbergShirtz2025
import Linglib.Theories.ConstructionGrammar.ArgumentStructure
import Linglib.Theories.ConstructionGrammar.Studies.KayFillmore1999
import Linglib.Theories.ConstructionGrammar.Studies.GoldbergJackendoff2004

-- Theories: HPSG
import Linglib.Theories.HPSG.Core.Basic
import Linglib.Theories.HPSG.Core.FromFragments
import Linglib.Theories.HPSG.Core.HeadFiller
import Linglib.Theories.HPSG.Core.LexicalRules
import Linglib.Theories.HPSG.Phenomena.Coreference
import Linglib.Theories.HPSG.Phenomena.Inversion

-- Theories: Information Structure (now in Focus/)
import Linglib.Theories.TruthConditional.Sentence.Focus.KratzerSelkirk2020

-- Theories: Minimalism
import Linglib.Theories.Minimalism.Core.Agree
import Linglib.Theories.Minimalism.Formal.Amalgamation
import Linglib.Theories.Minimalism.Formal.Constraints.HMC
import Linglib.Theories.Minimalism.Phenomena.Coreference
import Linglib.Theories.Minimalism.Phenomena.Derivations
import Linglib.Theories.Minimalism.Core.FromFragments
import Linglib.Theories.Minimalism.Formal.HeadMovement.Basic
import Linglib.Theories.Minimalism.Phenomena.HeadMovement.BulgarianLHM
import Linglib.Theories.Minimalism.Phenomena.HeadMovement.GermanicV2
import Linglib.Theories.Minimalism.Phenomena.Allocutivity
import Linglib.Theories.Minimalism.Phenomena.Inversion
import Linglib.Theories.Minimalism.Phenomena.SpeechActs
import Linglib.Theories.Minimalism.Core.Labeling
import Linglib.Theories.Minimalism.Core.Phase
import Linglib.Theories.Minimalism.Formal.MergeUnification
import Linglib.Theories.Minimalism.Phenomena.Scope
import Linglib.Theories.Minimalism.Bridge.Interface
import Linglib.Theories.Minimalism.Bridge.CombinationSchemata
import Linglib.Theories.Minimalism.Bridge.RelativeClauses
import Linglib.Theories.Minimalism.Core.Structure
import Linglib.Theories.Minimalism.Core.Basic
import Linglib.Theories.Minimalism.Core.Voice
import Linglib.Theories.Minimalism.Core.Applicative
import Linglib.Theories.Minimalism.Bridge.EventStructureBridge
import Linglib.Theories.Minimalism.Morphology.Fission
import Linglib.Theories.Morphology.Diagnostics.CliticVsAffix
import Linglib.Theories.Minimalism.Phenomena.VoiceAppl
import Linglib.Theories.Minimalism.Formal.MCB2023.FreeMagmaEquiv
import Linglib.Theories.Minimalism.Formal.MCB2023.Accessible
import Linglib.Theories.Minimalism.Formal.MCB2023.BinaryOptimality
import Linglib.Theories.Minimalism.Formal.MCB2023.Coproduct
import Linglib.Theories.Minimalism.Formal.Workspace
import Linglib.Theories.Minimalism.Formal.XBar

-- Theories: TruthConditional (extensional)
import Linglib.Theories.TruthConditional.Adjective.Comparative
import Linglib.Theories.TruthConditional.Adjective.Intensification
import Linglib.Theories.TruthConditional.Adjective.Theory
import Linglib.Theories.TruthConditional.Anaphora
import Linglib.Theories.TruthConditional.Basic
import Linglib.Theories.TruthConditional.Composition
import Linglib.Theories.TruthConditional.Conjunction
import Linglib.Theories.TruthConditional.Core.Derivation
import Linglib.Theories.TruthConditional.Core.Lexicon
import Linglib.Theories.TruthConditional.Core.Polarity
import Linglib.Theories.TruthConditional.Core.Time
import Linglib.Theories.TruthConditional.Derivation.Scope
import Linglib.Theories.TruthConditional.Derivation.TruthConditions
import Linglib.Theories.TruthConditional.Determiner.Demonstrative.AhnZhu2025
import Linglib.Theories.TruthConditional.Measurement.Basic
import Linglib.Theories.TruthConditional.Numeral.Embedding
import Linglib.Theories.TruthConditional.Numeral.Polysemy
import Linglib.Theories.TruthConditional.Numeral.Precision
import Linglib.Theories.TruthConditional.Numeral.Semantics
import Linglib.Theories.TruthConditional.Determiner.Definite
import Linglib.Theories.TruthConditional.Determiner.Quantifier

import Linglib.Theories.TruthConditional.Expressives.Basic
import Linglib.Theories.TruthConditional.Expressives.OutlookMarker
import Linglib.Theories.TruthConditional.Frames.Basic
import Linglib.Theories.TruthConditional.Graded.BayesianSemantics
import Linglib.Theories.TruthConditional.Graded.GradedProposition
import Linglib.Theories.TruthConditional.Interface.SemanticBackend
import Linglib.Theories.TruthConditional.Interface.SyntaxInterface
import Linglib.Theories.TruthConditional.Modification
import Linglib.Theories.TruthConditional.Noun.GradableNouns
import Linglib.Theories.TruthConditional.Noun.Kind.Carlson1977
import Linglib.Theories.TruthConditional.Noun.Kind.Chierchia1998
import Linglib.Theories.TruthConditional.Noun.Kind.Dayal2004
import Linglib.Theories.TruthConditional.Noun.Kind.Generics
import Linglib.Theories.TruthConditional.Noun.Kind.Krifka2004
import Linglib.Theories.TruthConditional.Noun.Relational.Barker2011
import Linglib.Theories.TruthConditional.Noun.TypeShifting
import Linglib.Theories.TruthConditional.Particle.Additive
import Linglib.Theories.TruthConditional.Plural.Distributivity
import Linglib.Theories.TruthConditional.PTQ
import Linglib.Theories.TruthConditional.Sentence.Entailment.AntiAdditivity
import Linglib.Theories.TruthConditional.Sentence.Entailment.Basic
import Linglib.Theories.TruthConditional.Sentence.Entailment.Monotonicity
import Linglib.Theories.TruthConditional.Sentence.Entailment.NegationTests
import Linglib.Theories.TruthConditional.Sentence.Entailment.PolarityBuilder
import Linglib.Theories.TruthConditional.Sentence.Entailment.PresuppositionPolarity
import Linglib.Theories.TruthConditional.Sentence.Entailment.ScaleInteraction
import Linglib.Theories.TruthConditional.Sentence.Entailment.StrawsonEntailment
import Linglib.Theories.TruthConditional.Sentence.Focus.BackgroundedIslands
import Linglib.Theories.TruthConditional.Sentence.Focus.DomainWidening
import Linglib.Theories.TruthConditional.Sentence.Focus.Interpretation
import Linglib.Theories.TruthConditional.Sentence.Focus.Particles
import Linglib.Theories.TruthConditional.Sentence.Presupposition.BeliefEmbedding
import Linglib.Theories.TruthConditional.Sentence.Presupposition.LocalContext
import Linglib.Theories.TruthConditional.Sentence.Presupposition.OntologicalPreconditions
import Linglib.Theories.TruthConditional.Sentence.Presupposition.TonhauserDerivation
import Linglib.Theories.TruthConditional.Sentence.Tense.Basic
import Linglib.Theories.TruthConditional.Sentence.Tense.TenseAspectComposition
import Linglib.Theories.TruthConditional.Sentence.Tense.TemporalAdverbials
import Linglib.Theories.TruthConditional.Sentence.Tense.Evidential
import Linglib.Theories.TruthConditional.Sentence.Tense.Perspective
import Linglib.Theories.TruthConditional.Sentence.Tense.TemporalConnectives
import Linglib.Theories.TruthConditional.Sentence.Tense.PerfectPolysemy
import Linglib.Theories.TruthConditional.Sentence.Tense.SequenceOfTense
import Linglib.Theories.TruthConditional.Variables
import Linglib.Theories.TruthConditional.Verb.Aspect
import Linglib.Theories.TruthConditional.Verb.ChangeOfState.Theory
import Linglib.Theories.TruthConditional.Verb.Habituals
import Linglib.Theories.TruthConditional.Verb.SelectionalPreferences
import Linglib.Theories.TruthConditional.Verb.ViewpointAspect

-- Theories: EventSemantics (neo-Davidsonian)
import Linglib.Theories.EventSemantics.Basic
import Linglib.Theories.EventSemantics.ThematicRoles
import Linglib.Theories.EventSemantics.ThematicRolesGrounding
import Linglib.Theories.EventSemantics.Mereology
import Linglib.Theories.EventSemantics.StratifiedReference
import Linglib.Theories.EventSemantics.Krifka1989
import Linglib.Theories.EventSemantics.Krifka1998
import Linglib.Theories.EventSemantics.Agentivity
import Linglib.Theories.EventSemantics.ProtoRoles
import Linglib.Theories.EventSemantics.EventStructure
import Linglib.Theories.EventSemantics.RootTypology
import Linglib.Theories.EventSemantics.TemporalDecomposition

-- Theories: IntensionalSemantics (possible-worlds semantics)
import Linglib.Theories.IntensionalSemantics.Basic
import Linglib.Theories.IntensionalSemantics.Attitude.BuilderProperties
import Linglib.Theories.IntensionalSemantics.Attitude.CDistributivity
import Linglib.Theories.IntensionalSemantics.Attitude.ContrafactiveGap
import Linglib.Theories.IntensionalSemantics.Attitude.Doxastic
import Linglib.Theories.IntensionalSemantics.Attitude.Intensional
import Linglib.Theories.IntensionalSemantics.Attitude.Parasitic
import Linglib.Theories.IntensionalSemantics.Attitude.Preferential
import Linglib.Theories.IntensionalSemantics.Attitude.SituationDependent
import Linglib.Theories.IntensionalSemantics.Causative.Basic
import Linglib.Theories.IntensionalSemantics.Causative.Builder
import Linglib.Theories.IntensionalSemantics.Causative.CoerciveImplication
import Linglib.Theories.IntensionalSemantics.Causative.Examples
import Linglib.Theories.IntensionalSemantics.Causative.GradedCausation
import Linglib.Theories.IntensionalSemantics.Causative.Integration
import Linglib.Theories.IntensionalSemantics.Causative.Necessity
import Linglib.Theories.IntensionalSemantics.Causative.Sufficiency
import Linglib.Theories.IntensionalSemantics.Causative.Implicative
import Linglib.Theories.IntensionalSemantics.Causative.ProductionDependence
import Linglib.Theories.IntensionalSemantics.Causative.Resultatives
import Linglib.Theories.IntensionalSemantics.Conditional.Assertability
import Linglib.Theories.IntensionalSemantics.Conditional.Basic
import Linglib.Theories.IntensionalSemantics.Conditional.ConditionalType
import Linglib.Theories.IntensionalSemantics.Conditional.Counterfactual
import Linglib.Theories.IntensionalSemantics.Conditional.LeftNested
import Linglib.Theories.IntensionalSemantics.Modal.Basic
import Linglib.Theories.IntensionalSemantics.Modal.Compare
import Linglib.Theories.IntensionalSemantics.Modal.Disjunction
import Linglib.Theories.IntensionalSemantics.Modal.BiasedPQ
import Linglib.Theories.IntensionalSemantics.Modal.Kratzer
import Linglib.Theories.IntensionalSemantics.Modal.PhillipsBrown
import Linglib.Theories.IntensionalSemantics.Modal.ProbabilityOrdering
import Linglib.Theories.IntensionalSemantics.Modal.SatisfactionOrdering
import Linglib.Theories.IntensionalSemantics.Modal.Ability
import Linglib.Theories.IntensionalSemantics.Modal.Simple
import Linglib.Theories.IntensionalSemantics.Modal.Typology
import Linglib.Theories.IntensionalSemantics.Mood.Basic
import Linglib.Theories.IntensionalSemantics.Reference.Basic
import Linglib.Theories.IntensionalSemantics.Reference.Kaplan
import Linglib.Theories.IntensionalSemantics.Reference.Donnellan
import Linglib.Theories.IntensionalSemantics.Reference.Almog2014
import Linglib.Theories.IntensionalSemantics.Reference.Demonstratives
import Linglib.Theories.IntensionalSemantics.Reference.KaplanLD
import Linglib.Theories.IntensionalSemantics.Reference.Monsters
import Linglib.Theories.IntensionalSemantics.Reference.Kripke
import Linglib.Theories.IntensionalSemantics.SituationSemantics.Elbourne

-- Theories: QuestionSemantics
import Linglib.Theories.QuestionSemantics.Answerhood
import Linglib.Theories.QuestionSemantics.Basic
import Linglib.Theories.QuestionSemantics.Coordination
import Linglib.Theories.QuestionSemantics.DecisionTheory
import Linglib.Theories.QuestionSemantics.EconomyOddness
import Linglib.Theories.QuestionSemantics.EntropyNPIs
import Linglib.Theories.QuestionSemantics.GSVanRooyBridge
import Linglib.Theories.QuestionSemantics.Hamblin
import Linglib.Theories.QuestionSemantics.Inquisitive
import Linglib.Theories.QuestionSemantics.LeftPeriphery
import Linglib.Theories.QuestionSemantics.LiftedTypes
import Linglib.Theories.QuestionSemantics.MentionSome
import Linglib.Theories.QuestionSemantics.Partition
import Linglib.Theories.QuestionSemantics.Polarity
import Linglib.Theories.QuestionSemantics.PragmaticAnswerhood
import Linglib.Theories.QuestionSemantics.ProbabilisticAnswerhood
import Linglib.Theories.QuestionSemantics.ScopeReadings
import Linglib.Theories.QuestionSemantics.SignalingGames
import Linglib.Theories.QuestionSemantics.DegreeQuestion
import Linglib.Theories.QuestionSemantics.VerumFocus

-- Theories: NeoGricean
import Linglib.Theories.NeoGricean.Analyticity
import Linglib.Theories.NeoGricean.ConventionalImplicatures
import Linglib.Theories.NeoGricean.Core.AlternativeGeneration
import Linglib.Theories.NeoGricean.Core.Alternatives
import Linglib.Theories.NeoGricean.Core.Basic
import Linglib.Theories.NeoGricean.Core.Competence
import Linglib.Theories.NeoGricean.Core.Markedness
import Linglib.Theories.NeoGricean.Evaluativity
import Linglib.Theories.NeoGricean.Exhaustivity.Basic
import Linglib.Theories.NeoGricean.Exhaustivity.Chierchia2004
import Linglib.Theories.NeoGricean.Exhaustivity.Chierchia2013
import Linglib.Theories.NeoGricean.Exhaustivity.EFCI
import Linglib.Theories.NeoGricean.Exhaustivity.EFCIClosure
import Linglib.Theories.NeoGricean.Exhaustivity.Interface
import Linglib.Theories.NeoGricean.Implementations.BarLevFox2020
import Linglib.Theories.NeoGricean.Implementations.FoxSpector2018
import Linglib.Theories.NeoGricean.Implementations.MontagueExhaustivity
import Linglib.Theories.NeoGricean.Implementations.Spector2007
import Linglib.Theories.NeoGricean.NegationScope
import Linglib.Theories.NeoGricean.Presuppositions
import Linglib.Theories.NeoGricean.ScalarImplicatures.Basic
import Linglib.Theories.NeoGricean.Constraints.NumericalExpressions
import Linglib.Theories.NeoGricean.Constraints.Wang2025
import Linglib.Theories.NeoGricean.ScalarImplicatures.Operations

-- Theories: RSA
import Linglib.Theories.RSA.Core.Basic
import Linglib.Theories.RSA.Core.BasicQ
import Linglib.Theories.RSA.Core.ChainComparison
import Linglib.Theories.RSA.Core.CombinedUtility
import Linglib.Theories.RSA.Core.CompositionalRSA
import Linglib.Theories.RSA.Core.Convergence
import Linglib.Theories.RSA.Core.Discourse
import Linglib.Theories.RSA.Core.DiscourseIntegration
import Linglib.Theories.RSA.Core.Eval
import Linglib.Theories.RSA.Core.Intensional
import Linglib.Theories.RSA.Core.Model
import Linglib.Theories.RSA.Core.Noise
import Linglib.Theories.RSA.Core.Distribution
import Linglib.Theories.RSA.Core.RationalPower
import Linglib.Theories.RSA.Core.Softmax.Basic
import Linglib.Theories.RSA.Core.Softmax.Limits
import Linglib.Theories.RSA.Core.Softmax.MaxEntropy
import Linglib.Theories.RSA.Implementations.DegenEtAl2020
import Linglib.Theories.RSA.Domains.Degrees
import Linglib.Theories.RSA.Domains.LexicalAmbiguity
import Linglib.Theories.RSA.Domains.Quantities
import Linglib.Theories.RSA.Domains.QUD
import Linglib.Theories.RSA.Domains.ReferenceGames
import Linglib.Theories.RSA.Domains.Scope
import Linglib.Theories.RSA.Extensions.ArgumentativeStrength
import Linglib.Theories.RSA.Extensions.NoncooperativeCommunication
import Linglib.Theories.RSA.Extensions.InformationTheory.Basic
import Linglib.Theories.RSA.Extensions.InformationTheory.PhaseTransition
import Linglib.Theories.RSA.Extensions.InformationTheory.RateDistortion
import Linglib.Theories.RSA.Extensions.InformationTheory.UtilityDynamics
import Linglib.Theories.RSA.Extensions.InformationTheory.UtilityNonMonotonicity
import Linglib.Theories.RSA.Extensions.LexicalUncertainty.Basic
import Linglib.Theories.RSA.Extensions.LexicalUncertainty.Compositional
import Linglib.Theories.RSA.Implementations.Alsop2024
import Linglib.Theories.RSA.Implementations.BarnettEtAl2022
import Linglib.Theories.RSA.Implementations.BellerGerstenberg2025
import Linglib.Theories.RSA.Implementations.BergenGoodman2015
import Linglib.Theories.RSA.Implementations.CausalCorrelation
import Linglib.Theories.RSA.Implementations.ChampollionAlsopGrosu2019
import Linglib.Theories.RSA.Implementations.CremersWilcoxSpector2023
import Linglib.Theories.RSA.Implementations.CumminsFranke2021
import Linglib.Theories.RSA.Implementations.EgreEtAl2023
import Linglib.Theories.RSA.Implementations.Franke2011
import Linglib.Theories.RSA.Implementations.FrankeBergen2020
import Linglib.Theories.RSA.Implementations.FrankGoodman2012
import Linglib.Theories.RSA.Implementations.GoodmanStuhlmuller2013
import Linglib.Theories.RSA.Implementations.GrusdtLassiterFranke2022
import Linglib.Theories.RSA.Implementations.HardingGerstenbergIcard2025
import Linglib.Theories.RSA.Implementations.HawkinsEtAl2025
import Linglib.Theories.RSA.Implementations.HawkinsGweonGoodman2021
import Linglib.Theories.RSA.Implementations.HeKaiserIskarous2025
import Linglib.Theories.RSA.Implementations.KaoEtAl2014_Hyperbole
import Linglib.Theories.RSA.Implementations.KaoEtAl2014_Metaphor
import Linglib.Theories.RSA.Implementations.LassiterGoodman2017
import Linglib.Theories.RSA.Implementations.Nouwen2024
import Linglib.Theories.RSA.Implementations.PottsEtAl2016
import Linglib.Theories.RSA.Implementations.QingEtAl2016
import Linglib.Theories.RSA.Implementations.ScontrasPearl2021
import Linglib.Theories.RSA.Implementations.ScontrasTonhauser2025
import Linglib.Theories.RSA.Implementations.ScopeFreezing
import Linglib.Theories.RSA.Implementations.SumersEtAl2023
import Linglib.Theories.RSA.Implementations.TesslerFranke2020
import Linglib.Theories.RSA.Implementations.TesslerGoodman2019
import Linglib.Theories.RSA.Implementations.TesslerGoodman2022
import Linglib.Theories.RSA.Implementations.VanTielEtAl2021
import Linglib.Theories.RSA.Implementations.WaldonDegen2021
import Linglib.Theories.RSA.Implementations.Warstadt2022
import Linglib.Theories.RSA.Implementations.YoonEtAl2020
import Linglib.Theories.RSA.Questions.Basic
import Linglib.Theories.RSA.Questions.PolarQuestions
import Linglib.Theories.RSA.Questions.ResponseSelection
import Linglib.Theories.RSA.ScalarImplicatures.Basic
import Linglib.Theories.RSA.ScalarImplicatures.Embedded.Attitudes
import Linglib.Theories.RSA.ScalarImplicatures.Embedded.Basic
import Linglib.Theories.RSA.ScalarImplicatures.Embedded.Conditionals
import Linglib.Theories.RSA.ScalarImplicatures.Embedded.Questions
import Linglib.Theories.RSA.ScalarImplicatures.Hurford

-- Theories: SDS
import Linglib.Theories.SDS.Core
import Linglib.Theories.SDS.Examples
import Linglib.Theories.SDS.Humor
import Linglib.Theories.SDS.Marginalization
import Linglib.Theories.SDS.MeasureTheory
import Linglib.Theories.SDS.ThresholdInstances

