/-
# Linglib

A Lean 4 library for formal linguistics, covering semantics, pragmatics,
and their interfaces. See README.md for documentation links.
-/

-- Core
import Linglib.Core.Basic
import Linglib.Core.Kleene
import Linglib.Core.Empirical
import Linglib.Core.Proposition
import Linglib.Core.UPOS
import Linglib.Core.UDFeatures
import Linglib.Core.DepRel
import Linglib.Core.Duality
import Linglib.Core.Scales
import Linglib.Core.Intension
import Linglib.Core.ModalLogic
import Linglib.Core.Conjectures
import Linglib.Core.CommonGround
import Linglib.Core.Parse
import Linglib.Core.Presupposition
import Linglib.Core.ProductOfExperts
import Linglib.Core.QUD
import Linglib.Core.Interfaces.BindingSemantics
import Linglib.Core.Interfaces.CoreferenceTheory
import Linglib.Core.Interfaces.ImplicatureTheory
import Linglib.Core.Interfaces.ScopeTheory
import Linglib.Core.Interfaces.SemanticStructure

-- Fragments
import Linglib.Fragments.Dutch.Nouns
import Linglib.Fragments.English.Determiners
import Linglib.Fragments.English.FunctionWords
import Linglib.Fragments.English.NumeralModifiers
import Linglib.Fragments.English.Lexicon
import Linglib.Fragments.English.Modifiers.Adjectives
import Linglib.Fragments.English.Nouns
import Linglib.Fragments.English.PolarityItems
import Linglib.Fragments.English.Predicates
import Linglib.Fragments.English.Predicates.Adjectival
import Linglib.Fragments.English.Predicates.Verbal
import Linglib.Fragments.English.Pronouns
import Linglib.Fragments.English.Scales
import Linglib.Fragments.Farsi.Determiners
import Linglib.Fragments.Georgian.Coordination
import Linglib.Fragments.HindiUrdu.Particles
import Linglib.Fragments.Hungarian.Coordination
import Linglib.Fragments.French.Nouns
import Linglib.Fragments.Irish.Coordination
import Linglib.Fragments.Latin.Coordination
import Linglib.Fragments.Japanese.Nouns
import Linglib.Fragments.Japanese.Particles
import Linglib.Fragments.Japanese.Predicates
import Linglib.Fragments.Mandarin.Nouns
import Linglib.Fragments.Mandarin.Predicates
import Linglib.Fragments.Turkish.Predicates

-- Phenomena
import Linglib.Phenomena.AdditiveParticles.Data
import Linglib.Phenomena.AdditiveParticles.Studies.Thomas2026
import Linglib.Phenomena.Agreement.Basic
import Linglib.Phenomena.Agreement.Case
import Linglib.Phenomena.Agreement.DetNoun
import Linglib.Phenomena.Attitudes.IntensionalExamples
import Linglib.Phenomena.Anaphora.BathroomSentences
import Linglib.Phenomena.Anaphora.Bridging
import Linglib.Phenomena.Anaphora.Coreference
import Linglib.Phenomena.Anaphora.CrossSentential
import Linglib.Phenomena.Anaphora.DonkeyAnaphora
import Linglib.Phenomena.Anaphora.ModalSubordination
import Linglib.Phenomena.Anaphora.Studies.ParasiticAttitudes
import Linglib.Phenomena.ArgumentStructure.DativeAlternation
import Linglib.Phenomena.ArgumentStructure.Passive
import Linglib.Phenomena.ArgumentStructure.Subcategorization
import Linglib.Phenomena.Aspect.Diagnostics
import Linglib.Phenomena.Conditionals.Data
import Linglib.Phenomena.Conditionals.LeftNested
import Linglib.Phenomena.Conditionals.Studies.GrusdtLassiterFranke2022
import Linglib.Phenomena.Conditionals.Studies.RamotowskaEtAl2025
import Linglib.Phenomena.Conditionals.Studies.SubordinateFuture
import Linglib.Phenomena.Complementation.Bridge
import Linglib.Phenomena.Complementation.Typology
import Linglib.Phenomena.Constructions.Studies.FillmoreKayOConnor1988
import Linglib.Phenomena.Constructions.Studies.GoldbergShirtz2025
import Linglib.Phenomena.Coordination.Data
import Linglib.Phenomena.Coordination.Studies.BillEtAl2025
import Linglib.Phenomena.Coordination.Typology
import Linglib.Phenomena.Ellipsis.FragmentAnswers
import Linglib.Phenomena.Ellipsis.Gapping
import Linglib.Phenomena.Ellipsis.Sluicing
import Linglib.Phenomena.Entailment.Basic
import Linglib.Phenomena.Entailment.Monotonicity
import Linglib.Phenomena.FillerGap.Basic
import Linglib.Phenomena.FillerGap.CrossSerial
import Linglib.Phenomena.FillerGap.LongDistance
import Linglib.Phenomena.Focus.Basic
import Linglib.Phenomena.Focus.PolarityStress
import Linglib.Phenomena.Focus.ProsodicExhaustivity
import Linglib.Phenomena.Generics.BareNames
import Linglib.Phenomena.Generics.BarePlurals
import Linglib.Phenomena.Generics.Data
import Linglib.Phenomena.Generics.KindReference
import Linglib.Phenomena.Gradability.Adjectives
import Linglib.Phenomena.Gradability.Basic
import Linglib.Phenomena.Gradability.ComparisonClass
import Linglib.Phenomena.Gradability.Evaluativity
import Linglib.Phenomena.Gradability.Studies.KursatDegen2021
import Linglib.Phenomena.Gradability.Vagueness
import Linglib.Phenomena.Humor.Studies.KaoEtAl2016
import Linglib.Phenomena.Imperatives.Studies.SumersEtAl2023
import Linglib.Phenomena.Imprecision.Basic
import Linglib.Phenomena.Imprecision.FormMeaning
import Linglib.Phenomena.Imprecision.InferencePreservation
import Linglib.Phenomena.Imprecision.Numerals
import Linglib.Phenomena.Imprecision.Studies.EgreEtAl2023
import Linglib.Phenomena.Imprecision.Projection
import Linglib.Phenomena.Islands.Data
import Linglib.Phenomena.Metaphor.Studies.KaoBergenGoodman2014
import Linglib.Phenomena.Modality.Basic
import Linglib.Phenomena.Modality.FreeChoice
import Linglib.Phenomena.Modality.Studies.FreeChoiceFarsi
import Linglib.Phenomena.Negation.Basic
import Linglib.Phenomena.Negation.DoubleNegation
import Linglib.Phenomena.Negation.FlexibleNegation
import Linglib.Phenomena.Plurals.Basic
import Linglib.Phenomena.Plurals.Homogeneity
import Linglib.Phenomena.Plurals.NonMaximality
import Linglib.Phenomena.Plurals.Studies.HaslingerEtAl2025
import Linglib.Phenomena.Plurals.Studies.QingEtAl2025
import Linglib.Phenomena.Polarity.Basic
import Linglib.Phenomena.Polarity.DisjunctionIgnorance
import Linglib.Phenomena.Polarity.Exceptives
import Linglib.Phenomena.Polarity.NPIs
import Linglib.Phenomena.Politeness.Studies.YoonEtAl2020
import Linglib.Phenomena.Presupposition.Basic
import Linglib.Phenomena.Presupposition.Diagnostics
import Linglib.Phenomena.Presupposition.ProjectiveContent
import Linglib.Phenomena.Presupposition.Studies.DegenTonhauser2021
import Linglib.Phenomena.Presupposition.Studies.HeKaiserIskarous2025
import Linglib.Phenomena.Presupposition.Studies.LoGuercio2025
import Linglib.Phenomena.Presupposition.Studies.ScontrasTonhauser2025
import Linglib.Phenomena.Presupposition.Studies.Yagi2025
import Linglib.Phenomena.Quantification.Basic
import Linglib.Phenomena.Quantification.Numerals
import Linglib.Phenomena.Quantification.ScopeFreezing
import Linglib.Phenomena.Quantification.ScopeWordOrder
import Linglib.Phenomena.Quantification.Studies.FrankeBergen2020
import Linglib.Phenomena.Quantification.Studies.ScontrasPearl2021
import Linglib.Phenomena.Questions.Basic
import Linglib.Phenomena.Questions.Typology
import Linglib.Phenomena.Questions.Embedding
import Linglib.Phenomena.Questions.Coordination
import Linglib.Phenomena.Questions.Exhaustivity
import Linglib.Phenomena.Questions.FocusAnswer
import Linglib.Phenomena.Questions.MentionSome
import Linglib.Phenomena.Questions.MultipleWh
import Linglib.Phenomena.Questions.NegativeQuestions
import Linglib.Phenomena.Questions.PolarAnswers
import Linglib.Phenomena.Questions.PragmaticAnswerhood
import Linglib.Phenomena.Questions.ScopeReadings
import Linglib.Phenomena.Questions.Studies.HawkinsEtAl2025
import Linglib.Phenomena.Questions.WhComplement
import Linglib.Phenomena.Reference.Studies.FrankGoodman2012
import Linglib.Phenomena.Reference.Studies.HawkinsGweonGoodman2021
import Linglib.Phenomena.ScalarImplicatures.Basic
import Linglib.Phenomena.ScalarImplicatures.Studies.CremersWilcoxSpector2023
import Linglib.Phenomena.ScalarImplicatures.Studies.GeurtsPouscoulous2009
import Linglib.Phenomena.ScalarImplicatures.Studies.GoodmanStuhlmuller2013
import Linglib.Phenomena.ScalarImplicatures.Studies.Ronai2024
import Linglib.Phenomena.ScalarImplicatures.Studies.VanTielEtAl2016
import Linglib.Phenomena.ScalarImplicatures.Studies.VanTielEtAl2021
import Linglib.Phenomena.WordOrder.Basic
import Linglib.Phenomena.WordOrder.SubjectAuxInversion
import Linglib.Phenomena.WordOrder.VerbPosition

-- Theories: CCG
import Linglib.Theories.CCG.Core.Basic
import Linglib.Theories.CCG.Core.Combinators
import Linglib.Theories.CCG.Core.FromFragments
import Linglib.Theories.CCG.Bridge.Interface
import Linglib.Theories.CCG.Bridge.Homomorphism
import Linglib.Theories.CCG.Bridge.Derivation
import Linglib.Theories.CCG.Phenomena.Agreement
import Linglib.Theories.CCG.Phenomena.Coordination
import Linglib.Theories.CCG.Phenomena.CrossSerial
import Linglib.Theories.CCG.Phenomena.Derivations
import Linglib.Theories.CCG.Phenomena.Gapping
import Linglib.Theories.CCG.Phenomena.TruthConditions
import Linglib.Theories.CCG.Formal.Equivalence
import Linglib.Theories.CCG.Formal.FormalLanguageTheory
import Linglib.Theories.CCG.Formal.GenerativeCapacity
import Linglib.Theories.CCG.Phenomena.Scope
import Linglib.Theories.CCG.Phenomena.Intonation

-- Comparisons (cross-theory)
import Linglib.Comparisons.CommandRelations
import Linglib.Comparisons.FreeChoice.Aloni2022
import Linglib.Comparisons.FreeChoice.Compare
import Linglib.Comparisons.GenericSemantics
import Linglib.Comparisons.Implicature
import Linglib.Comparisons.KindReference
import Linglib.Comparisons.PolarQuestions
import Linglib.Comparisons.PresuppositionProjection
import Linglib.Comparisons.RelevanceTheories
import Linglib.Comparisons.RSAandPDS
import Linglib.Comparisons.RSAExhExpressivity
import Linglib.Comparisons.RSANeoGricean
import Linglib.Comparisons.SauerlandRSA
import Linglib.Comparisons.ScalarImplicature
import Linglib.Comparisons.ScopeFreezing
import Linglib.Comparisons.SDSandRSA
import Linglib.Comparisons.ThresholdSemantics

-- Theories: Dependency Grammar
import Linglib.Theories.DependencyGrammar.Basic
import Linglib.Theories.DependencyGrammar.Coordination
import Linglib.Theories.DependencyGrammar.Coreference
import Linglib.Theories.DependencyGrammar.CRDC
import Linglib.Theories.DependencyGrammar.Inversion
import Linglib.Theories.DependencyGrammar.LexicalRules
import Linglib.Theories.DependencyGrammar.LongDistance

-- Theories: Dynamic Semantics
import Linglib.Theories.DynamicSemantics.BilateralUpdate.Basic
import Linglib.Theories.DynamicSemantics.BilateralUpdate.FreeChoice
import Linglib.Theories.DynamicSemantics.BUS.Basic
import Linglib.Theories.DynamicSemantics.BUS.DynamicTy2
import Linglib.Theories.DynamicSemantics.BUS.FreeChoice
import Linglib.Theories.DynamicSemantics.Charlow2019
import Linglib.Theories.DynamicSemantics.CDRT.Basic
import Linglib.Theories.DynamicSemantics.CDRT.DynamicTy2
import Linglib.Theories.DynamicSemantics.Comparisons.PLA_BUS
import Linglib.Theories.DynamicSemantics.Core.Basic
import Linglib.Theories.DynamicSemantics.Core.Bilateral
import Linglib.Theories.DynamicSemantics.Core.CCP
import Linglib.Theories.DynamicSemantics.Core.DiscourseRef
import Linglib.Theories.DynamicSemantics.Core.DynamicTy2
import Linglib.Theories.DynamicSemantics.Core.Translation
import Linglib.Theories.DynamicSemantics.Core.Update
import Linglib.Theories.DynamicSemantics.DPL.Basic
import Linglib.Theories.DynamicSemantics.DPL.DynamicTy2
import Linglib.Theories.DynamicSemantics.DRT.Basic
import Linglib.Theories.DynamicSemantics.FileChangeSemantics.Basic
import Linglib.Theories.DynamicSemantics.IntensionalCDRT.Basic
import Linglib.Theories.DynamicSemantics.IntensionalCDRT.Connectives
import Linglib.Theories.DynamicSemantics.IntensionalCDRT.MendesDerivations
import Linglib.Theories.DynamicSemantics.IntensionalCDRT.ModalDonkeyAnaphora
import Linglib.Theories.DynamicSemantics.IntensionalCDRT.PresuppositionWeakening
import Linglib.Theories.DynamicSemantics.IntensionalCDRT.Situations
import Linglib.Theories.DynamicSemantics.IntensionalCDRT.Update
import Linglib.Theories.DynamicSemantics.PLA.Basic
import Linglib.Theories.DynamicSemantics.PLA.Belief
import Linglib.Theories.DynamicSemantics.PLA.DeepTheorems
import Linglib.Theories.DynamicSemantics.PLA.DynamicTy2
import Linglib.Theories.DynamicSemantics.PLA.Epistemic
import Linglib.Theories.DynamicSemantics.PLA.Quantifiers
import Linglib.Theories.DynamicSemantics.PLA.Semantics
import Linglib.Theories.DynamicSemantics.PLA.Update
import Linglib.Theories.DynamicSemantics.Probabilistic
import Linglib.Theories.DynamicSemantics.State
import Linglib.Theories.DynamicSemantics.TeamSemantics
import Linglib.Theories.DynamicSemantics.UpdateSemantics.Basic

-- Theories: Construction Grammar
import Linglib.Theories.ConstructionGrammar.Basic
import Linglib.Theories.ConstructionGrammar.Studies.FillmoreKayOConnor1988
import Linglib.Theories.ConstructionGrammar.Studies.GoldbergShirtz2025

-- Theories: HPSG
import Linglib.Theories.HPSG.Basic
import Linglib.Theories.HPSG.Coreference
import Linglib.Theories.HPSG.Features
import Linglib.Theories.HPSG.Inversion

-- Theories: Minimalism
import Linglib.Theories.Minimalism.Core.Agree
import Linglib.Theories.Minimalism.Formal.Amalgamation
import Linglib.Theories.Minimalism.Core.Basic
import Linglib.Theories.Minimalism.Formal.Constraints.HMC
import Linglib.Theories.Minimalism.Core.Containment
import Linglib.Theories.Minimalism.Phenomena.Coreference
import Linglib.Theories.Minimalism.Phenomena.Derivations
import Linglib.Theories.Minimalism.Core.FromFragments
import Linglib.Theories.Minimalism.Formal.HeadMovement.Basic
import Linglib.Theories.Minimalism.Phenomena.HeadMovement.BulgarianLHM
import Linglib.Theories.Minimalism.Phenomena.HeadMovement.GermanicV2
import Linglib.Theories.Minimalism.Phenomena.Inversion
import Linglib.Theories.Minimalism.Core.Labeling
import Linglib.Theories.Minimalism.Formal.MergeUnification
import Linglib.Theories.Minimalism.Phenomena.Scope
import Linglib.Theories.Minimalism.Bridge.Interface
import Linglib.Theories.Minimalism.Bridge.RelativeClauses
import Linglib.Theories.Minimalism.Core.Structure
import Linglib.Theories.Minimalism.Core.SyntacticObjects
import Linglib.Theories.Minimalism.Formal.Workspace
import Linglib.Theories.Minimalism.Formal.XBar

-- Theories: TruthConditional (extensional)
import Linglib.Theories.TruthConditional.Adjective.Theory
import Linglib.Theories.TruthConditional.Anaphora
import Linglib.Theories.TruthConditional.Basic
import Linglib.Theories.TruthConditional.Composition
import Linglib.Theories.TruthConditional.Conjunction
import Linglib.Theories.TruthConditional.Core.Derivation
import Linglib.Theories.TruthConditional.Core.Lexicon
import Linglib.Theories.TruthConditional.Core.Polarity
import Linglib.Theories.TruthConditional.Core.Time
import Linglib.Theories.TruthConditional.Derivation.Scope
import Linglib.Theories.TruthConditional.Derivation.TruthConditions
import Linglib.Theories.TruthConditional.Determiner.Demonstrative.AhnZhu2025
import Linglib.Theories.TruthConditional.Determiner.Numeral.Bilateral
import Linglib.Theories.TruthConditional.Determiner.Numeral.Compare
import Linglib.Theories.TruthConditional.Determiner.Numeral.LowerBound
import Linglib.Theories.TruthConditional.Determiner.Numeral.Theory
import Linglib.Theories.TruthConditional.Determiner.Quantifier
import Linglib.Theories.TruthConditional.Domain.Degree
import Linglib.Theories.TruthConditional.Expressives.Basic
import Linglib.Theories.TruthConditional.Frames.Basic
import Linglib.Theories.TruthConditional.Graded.BayesianSemantics
import Linglib.Theories.TruthConditional.Graded.GradedProposition
import Linglib.Theories.TruthConditional.Interface.SemanticBackend
import Linglib.Theories.TruthConditional.Interface.SyntaxInterface
import Linglib.Theories.TruthConditional.Modification
import Linglib.Theories.TruthConditional.Noun.GradableNouns
import Linglib.Theories.TruthConditional.Noun.Kind.Carlson1977
import Linglib.Theories.TruthConditional.Noun.Kind.Chierchia1998
import Linglib.Theories.TruthConditional.Noun.Kind.Dayal2004
import Linglib.Theories.TruthConditional.Noun.Kind.Generics
import Linglib.Theories.TruthConditional.Noun.Kind.Krifka2004
import Linglib.Theories.TruthConditional.Noun.Relational.Barker2011
import Linglib.Theories.TruthConditional.Noun.TypeShifting
import Linglib.Theories.TruthConditional.Particle.Additive
import Linglib.Theories.TruthConditional.Plural.Distributivity
import Linglib.Theories.TruthConditional.PTQ
import Linglib.Theories.TruthConditional.Sentence.Entailment.AntiAdditivity
import Linglib.Theories.TruthConditional.Sentence.Entailment.Basic
import Linglib.Theories.TruthConditional.Sentence.Entailment.Monotonicity
import Linglib.Theories.TruthConditional.Sentence.Entailment.NegationTests
import Linglib.Theories.TruthConditional.Sentence.Entailment.PresuppositionPolarity
import Linglib.Theories.TruthConditional.Sentence.Entailment.ScaleInteraction
import Linglib.Theories.TruthConditional.Sentence.Focus.DomainWidening
import Linglib.Theories.TruthConditional.Sentence.Focus.InformationStructure
import Linglib.Theories.TruthConditional.Sentence.Focus.Interpretation
import Linglib.Theories.TruthConditional.Sentence.Focus.Particles
import Linglib.Theories.TruthConditional.Sentence.Presupposition.BeliefEmbedding
import Linglib.Theories.TruthConditional.Sentence.Presupposition.LocalContext
import Linglib.Theories.TruthConditional.Sentence.Presupposition.OntologicalPreconditions
import Linglib.Theories.TruthConditional.Sentence.Presupposition.TonhauserDerivation
import Linglib.Theories.TruthConditional.Sentence.Tense.Basic
import Linglib.Theories.TruthConditional.Variables
import Linglib.Theories.TruthConditional.Verb.Aspect
import Linglib.Theories.TruthConditional.Verb.ChangeOfState.Theory
import Linglib.Theories.TruthConditional.Verb.Habituals
import Linglib.Theories.TruthConditional.Verb.SelectionalPreferences

-- Theories: IntensionalSemantics (possible-worlds semantics)
import Linglib.Theories.IntensionalSemantics.Basic
import Linglib.Theories.IntensionalSemantics.Attitude.BuilderProperties
import Linglib.Theories.IntensionalSemantics.Attitude.CDistributivity
import Linglib.Theories.IntensionalSemantics.Attitude.ContrafactiveGap
import Linglib.Theories.IntensionalSemantics.Attitude.Doxastic
import Linglib.Theories.IntensionalSemantics.Attitude.Intensional
import Linglib.Theories.IntensionalSemantics.Attitude.Parasitic
import Linglib.Theories.IntensionalSemantics.Attitude.Preferential
import Linglib.Theories.IntensionalSemantics.Causative.Basic
import Linglib.Theories.IntensionalSemantics.Causative.CoerciveImplication
import Linglib.Theories.IntensionalSemantics.Causative.Examples
import Linglib.Theories.IntensionalSemantics.Causative.Integration
import Linglib.Theories.IntensionalSemantics.Causative.Necessity
import Linglib.Theories.IntensionalSemantics.Causative.Sufficiency
import Linglib.Theories.IntensionalSemantics.Conditional.Assertability
import Linglib.Theories.IntensionalSemantics.Conditional.Basic
import Linglib.Theories.IntensionalSemantics.Conditional.CausalBayesNet
import Linglib.Theories.IntensionalSemantics.Conditional.CausalModel
import Linglib.Theories.IntensionalSemantics.Conditional.ConditionalType
import Linglib.Theories.IntensionalSemantics.Conditional.Counterfactual
import Linglib.Theories.IntensionalSemantics.Conditional.LeftNested
import Linglib.Theories.IntensionalSemantics.Modal.Basic
import Linglib.Theories.IntensionalSemantics.Modal.Compare
import Linglib.Theories.IntensionalSemantics.Modal.Disjunction
import Linglib.Theories.IntensionalSemantics.Modal.Kratzer
import Linglib.Theories.IntensionalSemantics.Modal.PhillipsBrown
import Linglib.Theories.IntensionalSemantics.Modal.SatisfactionOrdering
import Linglib.Theories.IntensionalSemantics.Modal.Simple
import Linglib.Theories.IntensionalSemantics.Mood.Basic

-- Theories: QuestionSemantics
import Linglib.Theories.QuestionSemantics.Answerhood
import Linglib.Theories.QuestionSemantics.Basic
import Linglib.Theories.QuestionSemantics.Coordination
import Linglib.Theories.QuestionSemantics.DecisionTheory
import Linglib.Theories.QuestionSemantics.EntropyNPIs
import Linglib.Theories.QuestionSemantics.GSVanRooyBridge
import Linglib.Theories.QuestionSemantics.Hamblin
import Linglib.Theories.QuestionSemantics.Inquisitive
import Linglib.Theories.QuestionSemantics.LeftPeriphery
import Linglib.Theories.QuestionSemantics.LiftedTypes
import Linglib.Theories.QuestionSemantics.MentionSome
import Linglib.Theories.QuestionSemantics.Partition
import Linglib.Theories.QuestionSemantics.Polarity
import Linglib.Theories.QuestionSemantics.PragmaticAnswerhood
import Linglib.Theories.QuestionSemantics.ProbabilisticAnswerhood
import Linglib.Theories.QuestionSemantics.ScopeReadings
import Linglib.Theories.QuestionSemantics.SignalingGames
import Linglib.Theories.QuestionSemantics.VerumFocus

-- Theories: NeoGricean
import Linglib.Theories.NeoGricean.Analyticity
import Linglib.Theories.NeoGricean.ConventionalImplicatures
import Linglib.Theories.NeoGricean.Core.AlternativeGeneration
import Linglib.Theories.NeoGricean.Core.Alternatives
import Linglib.Theories.NeoGricean.Core.Basic
import Linglib.Theories.NeoGricean.Core.Competence
import Linglib.Theories.NeoGricean.Core.Markedness
import Linglib.Theories.NeoGricean.Evaluativity
import Linglib.Theories.NeoGricean.Exhaustivity.Basic
import Linglib.Theories.NeoGricean.Exhaustivity.EFCI
import Linglib.Theories.NeoGricean.Exhaustivity.EFCIClosure
import Linglib.Theories.NeoGricean.Exhaustivity.Interface
import Linglib.Theories.NeoGricean.Implementations.BarLevFox2020
import Linglib.Theories.NeoGricean.Implementations.FoxSpector2018
import Linglib.Theories.NeoGricean.Implementations.MontagueExhaustivity
import Linglib.Theories.NeoGricean.Implementations.Spector2007
import Linglib.Theories.NeoGricean.NegationScope
import Linglib.Theories.NeoGricean.Presuppositions
import Linglib.Theories.NeoGricean.ScalarImplicatures.Basic
import Linglib.Theories.NeoGricean.ScalarImplicatures.Operations

-- Theories: RSA
import Linglib.Theories.RSA.Core.Basic
import Linglib.Theories.RSA.Core.BasicQ
import Linglib.Theories.RSA.Core.ChainComparison
import Linglib.Theories.RSA.Core.CombinedUtility
import Linglib.Theories.RSA.Core.CompositionalRSA
import Linglib.Theories.RSA.Core.Convergence
import Linglib.Theories.RSA.Core.Discourse
import Linglib.Theories.RSA.Core.DiscourseIntegration
import Linglib.Theories.RSA.Core.Eval
import Linglib.Theories.RSA.Core.Intensional
import Linglib.Theories.RSA.Core.Model
import Linglib.Theories.RSA.Core.Noise
import Linglib.Theories.RSA.Core.Distribution
import Linglib.Theories.RSA.Core.RationalPower
import Linglib.Theories.RSA.Core.Softmax.Basic
import Linglib.Theories.RSA.Core.Softmax.Limits
import Linglib.Theories.RSA.Core.Softmax.MaxEntropy
import Linglib.Theories.RSA.Implementations.DegenEtAl2020
import Linglib.Theories.RSA.Domains.Degrees
import Linglib.Theories.RSA.Domains.LexicalAmbiguity
import Linglib.Theories.RSA.Domains.Quantities
import Linglib.Theories.RSA.Domains.QUD
import Linglib.Theories.RSA.Domains.ReferenceGames
import Linglib.Theories.RSA.Domains.Scope
import Linglib.Theories.RSA.Extensions.InformationTheory.Basic
import Linglib.Theories.RSA.Extensions.InformationTheory.PhaseTransition
import Linglib.Theories.RSA.Extensions.InformationTheory.RateDistortion
import Linglib.Theories.RSA.Extensions.InformationTheory.UtilityDynamics
import Linglib.Theories.RSA.Extensions.InformationTheory.UtilityNonMonotonicity
import Linglib.Theories.RSA.Extensions.LexicalUncertainty.Basic
import Linglib.Theories.RSA.Extensions.LexicalUncertainty.Compositional
import Linglib.Theories.RSA.Implementations.Alsop2024
import Linglib.Theories.RSA.Implementations.BellerGerstenberg2025
import Linglib.Theories.RSA.Implementations.BergenGoodman2015
import Linglib.Theories.RSA.Implementations.CausalCorrelation
import Linglib.Theories.RSA.Implementations.ChampollionAlsopGrosu2019
import Linglib.Theories.RSA.Implementations.CremersWilcoxSpector2023
import Linglib.Theories.RSA.Implementations.EgreEtAl2023
import Linglib.Theories.RSA.Implementations.Franke2011
import Linglib.Theories.RSA.Implementations.FrankeBergen2020
import Linglib.Theories.RSA.Implementations.FrankGoodman2012
import Linglib.Theories.RSA.Implementations.GoodmanStuhlmuller2013
import Linglib.Theories.RSA.Implementations.GrusdtLassiterFranke2022
import Linglib.Theories.RSA.Implementations.HawkinsEtAl2025
import Linglib.Theories.RSA.Implementations.HawkinsGweonGoodman2021
import Linglib.Theories.RSA.Implementations.HeKaiserIskarous2025
import Linglib.Theories.RSA.Implementations.KaoEtAl2014_Hyperbole
import Linglib.Theories.RSA.Implementations.KaoEtAl2014_Metaphor
import Linglib.Theories.RSA.Implementations.LassiterGoodman2017
import Linglib.Theories.RSA.Implementations.PottsEtAl2016
import Linglib.Theories.RSA.Implementations.QingEtAl2016
import Linglib.Theories.RSA.Implementations.ScontrasPearl2021
import Linglib.Theories.RSA.Implementations.ScontrasTonhauser2025
import Linglib.Theories.RSA.Implementations.ScopeFreezing
import Linglib.Theories.RSA.Implementations.SumersEtAl2023
import Linglib.Theories.RSA.Implementations.TesslerFranke2020
import Linglib.Theories.RSA.Implementations.TesslerGoodman2019
import Linglib.Theories.RSA.Implementations.TesslerGoodman2022
import Linglib.Theories.RSA.Implementations.VanTielEtAl2021
import Linglib.Theories.RSA.Implementations.WaldonDegen2021
import Linglib.Theories.RSA.Implementations.Warstadt2022
import Linglib.Theories.RSA.Implementations.YoonEtAl2020
import Linglib.Theories.RSA.Questions.Basic
import Linglib.Theories.RSA.Questions.PolarQuestions
import Linglib.Theories.RSA.Questions.ResponseSelection
import Linglib.Theories.RSA.ScalarImplicatures.Basic
import Linglib.Theories.RSA.ScalarImplicatures.Embedded.Attitudes
import Linglib.Theories.RSA.ScalarImplicatures.Embedded.Basic
import Linglib.Theories.RSA.ScalarImplicatures.Embedded.Conditionals
import Linglib.Theories.RSA.ScalarImplicatures.Embedded.Questions
import Linglib.Theories.RSA.ScalarImplicatures.Hurford

-- Theories: SDS
import Linglib.Theories.SDS.Core
import Linglib.Theories.SDS.Examples
import Linglib.Theories.SDS.Humor
import Linglib.Theories.SDS.Marginalization
import Linglib.Theories.SDS.MeasureTheory
import Linglib.Theories.SDS.ThresholdInstances

