/-
# Linglib

A Lean 4 library for formal linguistics, covering semantics, pragmatics,
and their interfaces. See README.md for documentation links.
-/

-- Core
import Linglib.Core.Situation
import Linglib.Core.Basic
import Linglib.Core.Pronouns
import Linglib.Core.Kleene
import Linglib.Core.Empirical
import Linglib.Core.Proposition
import Linglib.Core.UD
import Linglib.Core.Duality
import Linglib.Core.Quantification
import Linglib.Core.SquareOfOpposition
import Linglib.Core.HornScale
import Linglib.Core.Intension
import Linglib.Core.ModalLogic
import Linglib.Core.Register
import Linglib.Core.SocialMeaning
import Linglib.Core.Conjectures
import Linglib.Core.CommonGround
import Linglib.Core.Parse
import Linglib.Core.Presupposition
import Linglib.Core.ProductOfExperts
import Linglib.Core.Partition
import Linglib.Core.PolarityPartition
import Linglib.Core.QUD
import Linglib.Core.Interface
import Linglib.Core.Causation
import Linglib.Core.RootDimensions
import Linglib.Theories.Semantics.Lexical.Verb.VerbEntry
import Linglib.Core.NaturalLogic
import Linglib.Core.DecisionTheory
import Linglib.Core.RationalAction
import Linglib.Core.UtilityTheory
import Linglib.Core.Evidence
import Linglib.Core.ProcessingModel
import Linglib.Core.Alternatives
import Linglib.Core.Time
import Linglib.Core.AtomicDistributivity
import Linglib.Core.Reichenbach
import Linglib.Core.Tense
import Linglib.Core.Context
import Linglib.Core.InformationStructure
import Linglib.Core.Prosody
import Linglib.Core.Definiteness
import Linglib.Core.NounCategorization
import Linglib.Core.Roundness
import Linglib.Core.Mereology
import Linglib.Core.MereoDim
import Linglib.Core.ContentIndividual
import Linglib.Core.BToM
import Linglib.Core.Path
import Linglib.Core.Continuation
import Linglib.Core.PersonCategory
import Linglib.Core.MorphRule
import Linglib.Core.InformationTheory
import Linglib.Theories.Morphology.Core.Circumfix
import Linglib.Theories.Morphology.Core.Exponence
import Linglib.Theories.Morphology.Core.ScaleFromParadigm
import Linglib.Theories.Interfaces.MorphologySemantics.StemToLex
import Linglib.Core.DiscourseRole
import Linglib.Core.Interval.QInterval
import Linglib.Core.Interval.PadeExp
import Linglib.Core.Interval.RpowInterval
import Linglib.Core.Interval.LogInterval
import Linglib.Tactics.NonnegOfForall
import Linglib.Tactics.RSADecide
import Linglib.Tactics.RSAPredict
import Linglib.Tactics.OntSort

-- Fragments
import Linglib.Fragments.Dutch.Nouns
import Linglib.Fragments.Dutch.Particles
import Linglib.Fragments.English.Determiners
import Linglib.Fragments.English.FunctionWords
import Linglib.Fragments.English.MeasurePhrases
import Linglib.Fragments.English.NumeralModifiers
import Linglib.Fragments.English.Lexicon
import Linglib.Fragments.English.Modifiers.Adjectives
import Linglib.Fragments.English.Nouns
import Linglib.Fragments.English.PolarityItems
import Linglib.Fragments.English.Predicates
import Linglib.Fragments.English.Predicates.Adjectival
import Linglib.Fragments.English.Predicates.Verbal
import Linglib.Fragments.English.Pronouns
import Linglib.Fragments.English.Scales
import Linglib.Fragments.English.Tense
import Linglib.Fragments.English.TemporalDeictic
import Linglib.Fragments.English.TemporalExpressions
import Linglib.Fragments.Bulgarian.Evidentials
import Linglib.Fragments.Czech.Determiners
import Linglib.Fragments.Czech.Particles
import Linglib.Fragments.Farsi.Determiners
import Linglib.Fragments.German.TemporalDeictic
import Linglib.Fragments.German.PolarityMarking
import Linglib.Fragments.German.Predicates
import Linglib.Fragments.German.Predicates.Modal
import Linglib.Fragments.Georgian.Coordination
import Linglib.Fragments.Greek.TemporalDeictic
import Linglib.Fragments.Hebrew.TemporalDeictic
import Linglib.Fragments.HindiUrdu.Particles
import Linglib.Fragments.Hungarian.Coordination
import Linglib.Fragments.French.Nouns
import Linglib.Fragments.French.Predicates
import Linglib.Fragments.Irish.Coordination
import Linglib.Fragments.Latin.Coordination
import Linglib.Fragments.Japanese.Determiners
import Linglib.Fragments.Japanese.Classifiers
import Linglib.Fragments.Japanese.Nouns
import Linglib.Fragments.Korean.Evidentials
import Linglib.Fragments.Korean.Predicates
import Linglib.Fragments.Japanese.TemporalDeictic
import Linglib.Fragments.Japanese.Particles
import Linglib.Fragments.Japanese.Predicates
import Linglib.Fragments.Mandarin.Determiners
import Linglib.Fragments.Mandarin.Classifiers
import Linglib.Fragments.Mandarin.Nouns
import Linglib.Fragments.Mandarin.Particles
import Linglib.Fragments.Mandarin.TemporalDeictic
import Linglib.Fragments.Mandarin.AspectComparison
import Linglib.Fragments.Mandarin.Predicates
import Linglib.Fragments.Turkish.Predicates
import Linglib.Fragments.Turkish.QuestionParticles
import Linglib.Fragments.Basque.Pronouns
import Linglib.Fragments.Magahi.Pronouns
import Linglib.Fragments.Korean.Pronouns
import Linglib.Fragments.Japanese.Pronouns
import Linglib.Fragments.Tamil.Pronouns
import Linglib.Fragments.Galician.Pronouns
import Linglib.Fragments.Hindi.Pronouns
import Linglib.Fragments.Maithili.Pronouns
import Linglib.Fragments.Punjabi.Pronouns
import Linglib.Fragments.Russian.TemporalDeictic
import Linglib.Fragments.Tagalog.TemporalConnectives
import Linglib.Fragments.Spanish.Clitics
import Linglib.Fragments.Spanish.Predicates
import Linglib.Fragments.Spanish.PersonFeatures

-- Phenomena
import Linglib.Phenomena.Causatives.Studies.SpalekMcNally.Data
import Linglib.Phenomena.TenseAspect.Studies.AlstottAravind2026.Data
import Linglib.Phenomena.Focus.AdditiveParticles.Studies.TurcoBraunDimroth2014.Data
import Linglib.Phenomena.TenseAspect.TemporalConnectivesBridge
import Linglib.Phenomena.Focus.AdditiveParticles.Data
import Linglib.Phenomena.Focus.AdditiveParticles.Studies.Thomas2026
import Linglib.Phenomena.Agreement.Basic
import Linglib.Phenomena.Agreement.DetNoun
import Linglib.Phenomena.Case.Data
import Linglib.Phenomena.Case.Typology
import Linglib.Phenomena.Copulas.Typology
import Linglib.Phenomena.Complementation.Attitudes.IntensionalExamplesBridge
import Linglib.Phenomena.Complementation.Attitudes.IntentionalIdentity.Data
import Linglib.Phenomena.Complementation.Attitudes.IntentionalIdentity.Bridge
import Linglib.Phenomena.Anaphora.BathroomSentences
import Linglib.Phenomena.Anaphora.Bridging
import Linglib.Phenomena.Anaphora.DG_CRDCBridge
import Linglib.Phenomena.Anaphora.DG_CoreferenceBridge
import Linglib.Phenomena.Anaphora.DG_NominalBridge
import Linglib.Phenomena.Anaphora.HPSGBridge
import Linglib.Phenomena.Anaphora.MinimalismBridge
import Linglib.Phenomena.Anaphora.TypeTheoreticBridge
import Linglib.Phenomena.Anaphora.Coreference
import Linglib.Phenomena.Anaphora.CrossSentential
import Linglib.Phenomena.Anaphora.DonkeyAnaphora
import Linglib.Phenomena.Anaphora.ModalSubordination
import Linglib.Phenomena.Anaphora.Typology
import Linglib.Phenomena.Anaphora.Studies.ParasiticAttitudes
import Linglib.Phenomena.Alignment.Typology
import Linglib.Phenomena.ArgumentStructure.DativeAlternation
import Linglib.Phenomena.ArgumentStructure.Passive
import Linglib.Phenomena.ArgumentStructure.Subcategorization
import Linglib.Phenomena.ArgumentStructure.Compare
import Linglib.Phenomena.ScalarImplicatures.ArgumentativeFraming
import Linglib.Phenomena.Modality.ActualityInferencesBridge
import Linglib.Phenomena.TenseAspect.CrossDomainBridge
import Linglib.Phenomena.TenseAspect.DiagnosticsBridge
import Linglib.Phenomena.AuxiliaryVerbs.Diagnostics
import Linglib.Phenomena.AuxiliaryVerbs.NegativeAuxiliaries
import Linglib.Phenomena.AuxiliaryVerbs.Selection
import Linglib.Phenomena.AuxiliaryVerbs.SelectionBridge
import Linglib.Phenomena.AuxiliaryVerbs.Typology
import Linglib.Phenomena.Plurals.Studies.Charlow2021.Data
import Linglib.Phenomena.Plurals.Studies.Charlow2021.CumulativeReadingsBridge
import Linglib.Phenomena.TenseAspect.Studies.Cumming2026.Bridge
import Linglib.Phenomena.TenseAspect.Studies.Lakoff1970.Data
import Linglib.Phenomena.TenseAspect.Studies.Lakoff1970.Bridge
import Linglib.Phenomena.Conditionals.Data
import Linglib.Phenomena.Conditionals.LeftNested
import Linglib.Phenomena.Conditionals.Studies.GrusdtLassiterFranke2022
import Linglib.Phenomena.Conditionals.Studies.RamotowskaEtAl2025
import Linglib.Phenomena.Conditionals.Studies.SubordinateFuture
import Linglib.Phenomena.Conditionals.Studies.EvcenBaleBarner2026.Data
import Linglib.Phenomena.Conditionals.Studies.EvcenBaleBarner2026.Bridge
import Linglib.Phenomena.Complementation.Attitudes.ConjunctionDistribution.Data
import Linglib.Phenomena.Complementation.Bridge
import Linglib.Phenomena.Complementation.Typology
import Linglib.Phenomena.Complementation.Studies.Cacchioli2025.SelectionBridge
import Linglib.Phenomena.Complementation.Studies.Cacchioli2025.Data
import Linglib.Phenomena.Complementation.Studies.Cacchioli2025.Bridge
import Linglib.Fragments.Tigrinya.ClausePrefixes
import Linglib.Phenomena.Constructions.Studies.FillmoreKayOConnor1988
import Linglib.Phenomena.Constructions.Studies.GoldbergShirtz2025
import Linglib.Phenomena.Constructions.Studies.KayFillmore1999
import Linglib.Phenomena.Constructions.Studies.OsborneGross2012.Data
import Linglib.Phenomena.Constructions.Resultatives.Data
import Linglib.Phenomena.Causatives.Studies.BeaversEtAl2021
import Linglib.Phenomena.Causatives.Data
import Linglib.Phenomena.Causatives.Typology
import Linglib.Phenomena.Causatives.ThickThinBridge
import Linglib.Phenomena.Causatives.StructuralCausationBridge
import Linglib.Phenomena.Causatives.Studies.MunozPerez2026.Data
import Linglib.Phenomena.Causatives.Studies.MunozPerez2026.Bridge
import Linglib.Phenomena.Causatives.Compare
import Linglib.Phenomena.Coordination.Data
import Linglib.Phenomena.Coordination.Studies.BillEtAl2025
import Linglib.Phenomena.Coordination.Studies.BillEtAl2025Bridge
import Linglib.Phenomena.Coordination.Typology
import Linglib.Phenomena.Coordination.Conjectures
import Linglib.Phenomena.WordOrder.Studies.FutrellEtAl2020
import Linglib.Phenomena.Ellipsis.FragmentAnswers
import Linglib.Phenomena.Ellipsis.Gapping
import Linglib.Phenomena.Ellipsis.Sluicing
import Linglib.Phenomena.Ellipsis.VPEllipsis
import Linglib.Phenomena.Ellipsis.Studies.AnandHardtMcCloskey2021.Data
import Linglib.Phenomena.Ellipsis.Studies.AnandHardtMcCloskey2021.Bridge
import Linglib.Phenomena.Entailment.Basic
import Linglib.Phenomena.Entailment.Monotonicity
import Linglib.Phenomena.FillerGap.Basic
import Linglib.Phenomena.FillerGap.CrossSerial
import Linglib.Phenomena.FillerGap.LongDistance
import Linglib.Phenomena.FillerGap.Typology
import Linglib.Phenomena.Focus.Basic
import Linglib.Phenomena.Focus.PolarityStress
import Linglib.Phenomena.Focus.ProsodicExhaustivity
import Linglib.Phenomena.Generics.BareNames
import Linglib.Phenomena.Generics.BarePlurals
import Linglib.Phenomena.Generics.Data
import Linglib.Phenomena.Generics.KindReference
import Linglib.Phenomena.Generics.Compare
import Linglib.Phenomena.Gender.Typology
import Linglib.Phenomena.Gradability.Adjectives
import Linglib.Phenomena.Gradability.Data
import Linglib.Phenomena.Gradability.ComparisonClass
import Linglib.Phenomena.Gradability.EvaluativityBridge
import Linglib.Phenomena.Gradability.Studies.KursatDegen2021
import Linglib.Phenomena.Gradability.Studies.KursatDegen2021Bridge
import Linglib.Phenomena.Gradability.IntensifiersBridge
import Linglib.Phenomena.Gradability.Typology
import Linglib.Phenomena.Gradability.Vagueness
import Linglib.Phenomena.Nonliteral.Humor.Studies.KaoEtAl2016
import Linglib.Phenomena.Nonliteral.Hyperbole.KaoEtAl2014
import Linglib.Phenomena.Imperatives.Studies.SumersEtAl2023
import Linglib.Phenomena.Imperatives.Typology
import Linglib.Phenomena.Gradability.Imprecision.Basic
import Linglib.Phenomena.Gradability.Imprecision.FormMeaning
import Linglib.Phenomena.Gradability.Imprecision.InferencePreservation
import Linglib.Phenomena.Gradability.Imprecision.Numerals
import Linglib.Phenomena.Numerals.Studies.WoodinEtAl2024
import Linglib.Phenomena.Gradability.Imprecision.Studies.EgreEtAl2023
import Linglib.Phenomena.Gradability.Imprecision.Studies.BeltramaSchwarz2024
import Linglib.Phenomena.Gradability.Imprecision.Studies.BeltramaSoltBurnett2022
import Linglib.Phenomena.Gradability.Imprecision.Studies.LassiterGoodman2017
import Linglib.Phenomena.Gradability.Imprecision.Projection
import Linglib.Phenomena.Gradability.Imprecision.RSA_EgreEtAl2023Bridge
import Linglib.Phenomena.FillerGap.Islands.Data
import Linglib.Phenomena.FillerGap.Islands.MannerOfSpeaking
import Linglib.Phenomena.FillerGap.Compare
import Linglib.Phenomena.Nonliteral.Irony.KaoEtAl2015
import Linglib.Phenomena.Nonliteral.Metaphor.KaoEtAl2014
import Linglib.Phenomena.Numerals.Studies.ClausWalch2024
import Linglib.Phenomena.Numerals.Snyder2026Bridge
import Linglib.Phenomena.Numerals.Embedding
import Linglib.Phenomena.Numerals.Compare
import Linglib.Phenomena.Numerals.Typology
import Linglib.Phenomena.Quantification.BaleSchwarz2026Bridge
import Linglib.Phenomena.Quantification.Scontras2014Bridge
import Linglib.Phenomena.Modality.ConditionalModalityScenarioBridge
import Linglib.Phenomena.Modality.ConditionalModalityBridge
import Linglib.Phenomena.Modality.ModalConcord.Data
import Linglib.Phenomena.Modality.ModalConcord.Bridge
import Linglib.Phenomena.Modality.ModalConcord.LiuRotter2025
import Linglib.Phenomena.Modality.ModalConcord.LiuRotter2025Bridge
import Linglib.Phenomena.Modality.Basic
import Linglib.Phenomena.Modality.EpistemicEvidentiality
import Linglib.Phenomena.Modality.FreeChoice
import Linglib.Phenomena.Modality.PracticalReasoning
import Linglib.Phenomena.Modality.InformationalBackgrounds
import Linglib.Phenomena.Modality.DegreeCollapse
import Linglib.Phenomena.Modality.GermanModalsBridge
import Linglib.Phenomena.Modality.Studies.FreeChoiceFarsi
import Linglib.Phenomena.Modality.Studies.Khoo2015
import Linglib.Phenomena.Modality.Studies.Khoo2015Bridge
import Linglib.Phenomena.Modality.Typology
import Linglib.Phenomena.Modality.TypologyBridge
import Linglib.Theories.Semantics.Dynamic.Systems.BSML.Basic
import Linglib.Theories.Semantics.Dynamic.Systems.BSML.FreeChoice
import Linglib.Phenomena.Modality.Studies.Aloni2022Bridge
import Linglib.Comparisons.FreeChoice
import Linglib.Phenomena.Negation.Basic
import Linglib.Phenomena.Negation.ExpletiveNegationBridge
import Linglib.Phenomena.WordOrder.NonProjectivity
import Linglib.Phenomena.Negation.DoubleNegation
import Linglib.Phenomena.Negation.CzechThreeWayNegBridge
import Linglib.Phenomena.Negation.CzechThreeWayNegTypologyBridge
import Linglib.Phenomena.Negation.FlexibleNegation
import Linglib.Phenomena.Morphology.CompositionBridge
import Linglib.Phenomena.Morphology.DegreeCompositionBridge
import Linglib.Phenomena.Morphology.ZwickyPullum1983Bridge
import Linglib.Phenomena.Morphology.Typology
import Linglib.Phenomena.Morphology.Studies.AckermanMalouf2013.Bridge
import Linglib.Phenomena.Negation.Studies.StankovaSimik2024.Data
import Linglib.Phenomena.Plurals.Basic
import Linglib.Phenomena.Plurals.Homogeneity
import Linglib.Phenomena.Plurals.NonMaximality
import Linglib.Phenomena.Plurals.Studies.HaslingerEtAl2025Bridge
import Linglib.Phenomena.Plurals.Studies.QingEtAl2025
import Linglib.Phenomena.Plurals.Compare
import Linglib.Phenomena.Polarity.Basic
import Linglib.Phenomena.Polarity.DisjunctionIgnorance
import Linglib.Phenomena.Polarity.Exceptives
import Linglib.Phenomena.Polarity.NPIs
import Linglib.Phenomena.Polarity.Studies.Schwab2022
import Linglib.Phenomena.Polarity.Studies.VonFintel1999
import Linglib.Phenomena.Polarity.Typology
import Linglib.Phenomena.Politeness.Honorifics
import Linglib.Phenomena.Politeness.Studies.MachinoEtAl2025
import Linglib.Phenomena.Politeness.Studies.MachinoEtAl2025Bridge
import Linglib.Phenomena.Politeness.Studies.YoonEtAl2020
import Linglib.Phenomena.Polysemy.Data
import Linglib.Phenomena.Polysemy.CopredBridge
import Linglib.Phenomena.Possession.Typology
import Linglib.Phenomena.Presupposition.Basic
import Linglib.Phenomena.Presupposition.Diagnostics
import Linglib.Phenomena.Presupposition.ProjectiveContent
import Linglib.Phenomena.Presupposition.Studies.DegenTonhauser2021
import Linglib.Phenomena.Presupposition.Studies.HeKaiserIskarous2025
import Linglib.Phenomena.Presupposition.Studies.LoGuercio2025
import Linglib.Phenomena.Presupposition.Studies.ScontrasTonhauser2025
import Linglib.Phenomena.Presupposition.Studies.Wang2025
import Linglib.Phenomena.Presupposition.Studies.Warstadt2022
import Linglib.Phenomena.Presupposition.Studies.Yagi2025
import Linglib.Phenomena.Presupposition.RSA_HeKaiserIskarous2025Bridge
import Linglib.Phenomena.Presupposition.RSA_Warstadt2022Bridge
import Linglib.Phenomena.Presupposition.Compare
import Linglib.Phenomena.Modality.OutlookMarkers
import Linglib.Phenomena.Agreement.NounCategorization
import Linglib.Phenomena.Agreement.NounCategorizationBridge
import Linglib.Phenomena.Agreement.Typology
import Linglib.Phenomena.Quantification.Basic
import Linglib.Phenomena.Quantification.Data
import Linglib.Phenomena.Quantification.ExamplesBridge
import Linglib.Phenomena.Quantification.Typology
import Linglib.Phenomena.Quantification.Bridge
import Linglib.Phenomena.Quantification.Studies.FrankeBergen2020
import Linglib.Phenomena.Quantification.Studies.ScontrasPearl2021
import Linglib.Phenomena.Quantification.Compare
import Linglib.Phenomena.Questions.Basic
import Linglib.Phenomena.Questions.Typology
import Linglib.Phenomena.Questions.TypologyBridge
import Linglib.Phenomena.Questions.Embedding
import Linglib.Phenomena.Questions.Coordination
import Linglib.Phenomena.Questions.Exhaustivity
import Linglib.Phenomena.Questions.FocusAnswer
import Linglib.Phenomena.Questions.MentionSome
import Linglib.Phenomena.Questions.MultipleWh
import Linglib.Phenomena.Questions.NandaoQs
import Linglib.Phenomena.Questions.NandaoQsBridge
import Linglib.Phenomena.Questions.NegativeQuestions
import Linglib.Phenomena.Questions.PolarAnswers
import Linglib.Phenomena.Questions.PragmaticAnswerhood
import Linglib.Phenomena.Questions.ScopeReadings
import Linglib.Phenomena.Questions.SlavicPQStrategies
import Linglib.Phenomena.Questions.Studies.HawkinsEtAl2025
import Linglib.Phenomena.Questions.WhComplement
import Linglib.Phenomena.Questions.Compare
import Linglib.Phenomena.Questions.Studies.TurkHirschInce2026Bridge
import Linglib.Phenomena.Reference.DirectReference
import Linglib.Phenomena.Reference.Studies.FrankGoodman2012
import Linglib.Phenomena.Reference.Studies.HawkinsGweonGoodman2021
import Linglib.Phenomena.Reference.Studies.SikosEtAl2021
import Linglib.Phenomena.Reference.Studies.SikosEtAl2021Bridge
import Linglib.Phenomena.Reference.Studies.Percus2000
import Linglib.Phenomena.ScalarImplicatures.Basic
import Linglib.Phenomena.ScalarImplicatures.Studies.BaleEtAl2025
import Linglib.Phenomena.ScalarImplicatures.Studies.BaleEtAl2025Bridge
import Linglib.Phenomena.ScalarImplicatures.Studies.CremersWilcoxSpector2023
import Linglib.Phenomena.ScalarImplicatures.Studies.GeurtsPouscoulous2009
import Linglib.Phenomena.ScalarImplicatures.Studies.MeyerFeiman2021
import Linglib.Phenomena.ScalarImplicatures.Studies.MeyerFeiman2021Bridge
import Linglib.Phenomena.ScalarImplicatures.Studies.Ronai2024
import Linglib.Phenomena.ScalarImplicatures.Studies.VanTielEtAl2016
import Linglib.Phenomena.ScalarImplicatures.Studies.VanTielEtAl2021
import Linglib.Phenomena.TenseAspect.Data
import Linglib.Phenomena.TenseAspect.Bridge
import Linglib.Phenomena.TenseAspect.ThenPresentBridge
import Linglib.Phenomena.TenseAspect.Compare
import Linglib.Phenomena.TenseAspect.Typology
import Linglib.Phenomena.TenseAspect.AgentivityBridge
import Linglib.Phenomena.TenseAspect.Studies.AlstottAravind2026
import Linglib.Phenomena.WordOrder.Basic
import Linglib.Phenomena.WordOrder.SubjectAuxInversion
import Linglib.Phenomena.WordOrder.Typology
import Linglib.Phenomena.WordOrder.VerbPosition
import Linglib.Phenomena.WordOrder.Gradience
import Linglib.Phenomena.WordOrder.Studies.HahnDegenFutrell2021
import Linglib.Phenomena.TenseAspect.TemporalAdverbialsBridge
import Linglib.Phenomena.ScalarImplicatures.WeakEvidenceEffect
import Linglib.Phenomena.ScalarImplicatures.Compare
import Linglib.Phenomena.ScalarImplicatures.CompareAgreement
import Linglib.Phenomena.ScalarImplicatures.GoodmanStuhlmuller2013

-- Theories: CCG
import Linglib.Theories.Syntax.CCG.Core.Basic
import Linglib.Theories.Syntax.CCG.Core.Combinators
import Linglib.Theories.Syntax.CCG.Core.FromFragments
import Linglib.Theories.Syntax.CCG.Bridge.Interface
import Linglib.Theories.Syntax.CCG.Bridge.Homomorphism
import Linglib.Theories.Syntax.CCG.Bridge.Derivation
import Linglib.Phenomena.Agreement.CCGBridge
import Linglib.Phenomena.Coordination.CCGBridge
import Linglib.Theories.Syntax.CCG.CrossSerial
import Linglib.Phenomena.WordOrder.CCG_DerivationsBridge
import Linglib.Theories.Syntax.CCG.Gapping
import Linglib.Phenomena.Entailment.CCGBridge
import Linglib.Theories.Syntax.CCG.Formal.Equivalence
import Linglib.Theories.Syntax.CCG.Formal.FormalLanguageTheory
import Linglib.Theories.Syntax.CCG.Formal.GenerativeCapacity
import Linglib.Theories.Syntax.CCG.Scope
import Linglib.Theories.Syntax.CCG.Intonation

-- Comparisons (pure metatheory)
import Linglib.Comparisons.CommandRelations
import Linglib.Comparisons.GenericSemantics
import Linglib.Comparisons.Mueller2013
import Linglib.Comparisons.Partee1973
import Linglib.Comparisons.RelevanceTheories
import Linglib.Comparisons.RSAandPDS
import Linglib.Comparisons.RSAExhExpressivity
import Linglib.Comparisons.RSANeoGricean
import Linglib.Comparisons.SauerlandRSA
import Linglib.Comparisons.SDSandRSA
import Linglib.Comparisons.TenseModalEvidentiality
import Linglib.Comparisons.TenseTheories
import Linglib.Comparisons.VaguenessTheories
import Linglib.Comparisons.ProjectionMechanisms
import Linglib.Comparisons.KratzerEpistemicRSA

-- Theories: Dependency Grammar
import Linglib.Theories.Syntax.DependencyGrammar.Core.Basic
import Linglib.Theories.Syntax.DependencyGrammar.Core.Projection
import Linglib.Theories.Syntax.DependencyGrammar.Core.Dominance
import Linglib.Theories.Syntax.DependencyGrammar.Core.LexicalRules
import Linglib.Theories.Syntax.DependencyGrammar.Core.Nominal
import Linglib.Theories.Syntax.DependencyGrammar.Formal.HeadCriteria
import Linglib.Theories.Syntax.DependencyGrammar.Formal.DependencyLength
import Linglib.Theories.Syntax.DependencyGrammar.Formal.HarmonicOrder
import Linglib.Theories.Syntax.DependencyGrammar.Formal.Catena
import Linglib.Theories.Syntax.DependencyGrammar.Formal.CatenalConstruction
import Linglib.Theories.Syntax.DependencyGrammar.Formal.EnhancedDependencies
import Linglib.Theories.Syntax.DependencyGrammar.Formal.VPDivergence
import Linglib.Theories.Syntax.DependencyGrammar.Formal.NonProjective
import Linglib.Theories.Syntax.DependencyGrammar.Formal.Government
import Linglib.Theories.Syntax.DependencyGrammar.Formal.Ellipsis
import Linglib.Theories.Syntax.DependencyGrammar.Formal.Discontinuity
import Linglib.Theories.Syntax.DependencyGrammar.Formal.Islands
import Linglib.Theories.Syntax.DependencyGrammar.Formal.CoordinationParallelism
import Linglib.Theories.Syntax.DependencyGrammar.Formal.MemorySurprisal.Basic
import Linglib.Theories.Syntax.DependencyGrammar.Formal.MemorySurprisal.FedzechkinaEtAl2017
import Linglib.Phenomena.WordOrder.DG_MemorySurprisalBridge
import Linglib.Theories.Syntax.DependencyGrammar.Formal.MemorySurprisal.MorphemeOrder
import Linglib.Theories.Syntax.DependencyGrammar.Coordination
import Linglib.Theories.Syntax.DependencyGrammar.Coreference
import Linglib.Theories.Syntax.DependencyGrammar.CRDC
import Linglib.Phenomena.WordOrder.DG_InversionBridge
import Linglib.Theories.Syntax.DependencyGrammar.LongDistance

-- Theories: Dynamic Semantics
-- Theories: Dynamic Semantics — Core
import Linglib.Theories.Semantics.Dynamic.Core.Basic
import Linglib.Theories.Semantics.Dynamic.Core.CCP
import Linglib.Theories.Semantics.Dynamic.Core.DiscourseRef
import Linglib.Theories.Semantics.Dynamic.Core.DynamicTy2
import Linglib.Theories.Semantics.Dynamic.Core.Translation
import Linglib.Theories.Semantics.Dynamic.Core.Update
-- Theories: Dynamic Semantics — Effects
import Linglib.Theories.Semantics.Dynamic.Effects.State.Basic
import Linglib.Theories.Semantics.Dynamic.Effects.State.DPL
import Linglib.Theories.Semantics.Dynamic.Effects.State.DPLBridge
import Linglib.Theories.Semantics.Dynamic.Effects.State.DRT
import Linglib.Theories.Semantics.Dynamic.Effects.Nondeterminism.Basic
import Linglib.Theories.Semantics.Dynamic.Effects.Nondeterminism.Charlow2019
import Linglib.Theories.Semantics.Dynamic.Effects.Nondeterminism.PointwiseUpdate
import Linglib.Theories.Semantics.Dynamic.Effects.Continuation.Basic
import Linglib.Theories.Semantics.Dynamic.Effects.Bilateral.Basic
import Linglib.Theories.Semantics.Dynamic.Effects.Bilateral.FreeChoice
import Linglib.Theories.Semantics.Dynamic.Effects.Probability.Basic
import Linglib.Theories.Semantics.Dynamic.Effects.Epistemic.Basic
-- Theories: Dynamic Semantics — Systems
import Linglib.Theories.Semantics.Dynamic.Systems.BUS.Basic
import Linglib.Theories.Semantics.Dynamic.Systems.BUS.DynamicTy2
import Linglib.Theories.Semantics.Dynamic.Systems.CDRT.Basic
import Linglib.Theories.Semantics.Dynamic.Systems.CDRT.DynamicTy2
import Linglib.Theories.Semantics.Dynamic.Systems.DynamicGQ.Basic
import Linglib.Theories.Semantics.Dynamic.Systems.DynamicGQ.UpdateTheoretic
import Linglib.Theories.Semantics.Dynamic.Systems.DynamicGQ.HigherOrder
import Linglib.Theories.Semantics.Dynamic.Systems.DynamicGQ.SubtypePolymorphism
import Linglib.Theories.Semantics.Dynamic.Systems.DynamicGQ.PostSuppositional
import Linglib.Theories.Semantics.Dynamic.Systems.IntensionalCDRT.Basic
import Linglib.Theories.Semantics.Dynamic.Systems.IntensionalCDRT.Connectives
import Linglib.Theories.Semantics.Dynamic.Systems.IntensionalCDRT.MendesDerivations
import Linglib.Theories.Semantics.Dynamic.Systems.IntensionalCDRT.ModalDonkeyAnaphora
import Linglib.Theories.Semantics.Dynamic.Systems.IntensionalCDRT.PresuppositionWeakening
import Linglib.Theories.Semantics.Dynamic.Systems.IntensionalCDRT.Situations
import Linglib.Theories.Semantics.Dynamic.Systems.IntensionalCDRT.Update
import Linglib.Theories.Semantics.Dynamic.Systems.PLA.Basic
import Linglib.Theories.Semantics.Dynamic.Systems.PLA.Belief
import Linglib.Theories.Semantics.Dynamic.Systems.PLA.DeepTheorems
import Linglib.Theories.Semantics.Dynamic.Systems.PLA.DynamicTy2
import Linglib.Theories.Semantics.Dynamic.Systems.PLA.Epistemic
import Linglib.Theories.Semantics.Dynamic.Systems.PLA.Quantifiers
import Linglib.Theories.Semantics.Dynamic.Systems.PLA.Semantics
import Linglib.Theories.Semantics.Dynamic.Systems.PLA.Update
-- Theories: Dynamic Semantics — Comparisons & top-level
import Linglib.Theories.Semantics.Dynamic.Comparisons.PLA_BUS
import Linglib.Theories.Semantics.Dynamic.State
import Linglib.Theories.Semantics.Dynamic.TeamSemantics
-- Theories: Decision-Theoretic Semantics (Merin 1999)
import Linglib.Theories.Pragmatics.DecisionTheoretic.Core
import Linglib.Theories.Pragmatics.DecisionTheoretic.ScalarImplicature
import Linglib.Theories.Pragmatics.DecisionTheoretic.But
import Linglib.Theories.Pragmatics.DecisionTheoretic.Even
import Linglib.Theories.Pragmatics.DecisionTheoretic.Also
-- Theories: TTR (Type Theory with Records)
import Linglib.Theories.Semantics.TypeTheoretic.Core
import Linglib.Theories.Semantics.TypeTheoretic.Copredication
import Linglib.Theories.Semantics.TypeTheoretic.Discourse
import Linglib.Theories.Semantics.TypeTheoretic.FrameBridge
import Linglib.Theories.Semantics.TypeTheoretic.Modality
import Linglib.Theories.Semantics.TypeTheoretic.Quantification
import Linglib.Theories.Semantics.TypeTheoretic.Underspecification

-- Theories: Construction Grammar
import Linglib.Theories.Syntax.ConstructionGrammar.Basic
import Linglib.Theories.Syntax.ConstructionGrammar.Studies.FillmoreKayOConnor1988
import Linglib.Theories.Syntax.ConstructionGrammar.Studies.GoldbergShirtz2025
import Linglib.Theories.Syntax.ConstructionGrammar.ArgumentStructure
import Linglib.Phenomena.Constructions.CxG_KayFillmore1999Bridge
import Linglib.Phenomena.Constructions.DG_OsborneGross2012Bridge
import Linglib.Theories.Syntax.ConstructionGrammar.Studies.GoldbergJackendoff2004

-- Theories: HPSG
import Linglib.Theories.Syntax.HPSG.Core.Basic
import Linglib.Theories.Syntax.HPSG.Core.FromFragments
import Linglib.Theories.Syntax.HPSG.Core.HeadFiller
import Linglib.Theories.Syntax.HPSG.Core.LexicalRules
import Linglib.Theories.Syntax.HPSG.Coreference
import Linglib.Theories.Syntax.HPSG.Inversion

-- Theories: Information Structure (now in Focus/)
import Linglib.Theories.Semantics.Focus.KratzerSelkirk2020

-- Theories: Minimalism
import Linglib.Theories.Syntax.Minimalism.Core.Agree
import Linglib.Theories.Syntax.Minimalism.Formal.Amalgamation
import Linglib.Theories.Syntax.Minimalism.Formal.Constraints.HMC
import Linglib.Theories.Syntax.Minimalism.Coreference
import Linglib.Theories.Syntax.Minimalism.Derivations
import Linglib.Theories.Syntax.Minimalism.Core.FromFragments
import Linglib.Theories.Syntax.Minimalism.Formal.HeadMovement.Basic
import Linglib.Theories.Syntax.Minimalism.HeadMovement.BulgarianLHM
import Linglib.Theories.Syntax.Minimalism.HeadMovement.GermanicV2
import Linglib.Phenomena.Politeness.Minimalism_AllocutivityBridge
import Linglib.Theories.Syntax.Minimalism.Inversion
import Linglib.Theories.Syntax.Minimalism.SpeechActs
import Linglib.Theories.Syntax.Minimalism.Core.Labeling
import Linglib.Theories.Syntax.Minimalism.Core.Phase
import Linglib.Theories.Syntax.Minimalism.Formal.MergeUnification
import Linglib.Theories.Syntax.Minimalism.Scope
import Linglib.Theories.Syntax.Minimalism.Bridge.Interface
import Linglib.Theories.Syntax.Minimalism.Bridge.CombinationSchemata
import Linglib.Theories.Syntax.Minimalism.Bridge.RelativeClauses
import Linglib.Theories.Syntax.Minimalism.Core.Structure
import Linglib.Theories.Syntax.Minimalism.Core.Basic
import Linglib.Theories.Syntax.Minimalism.Core.Voice
import Linglib.Theories.Syntax.Minimalism.Core.Applicative
import Linglib.Theories.Syntax.Minimalism.Bridge.EventStructureBridge
import Linglib.Theories.Morphology.DM.Fission
import Linglib.Theories.Morphology.Core.CliticVsAffix
import Linglib.Theories.Morphology.WP.LCEC
import Linglib.Theories.Syntax.Minimalism.VoiceAppl
import Linglib.Theories.Syntax.Minimalism.Formal.MCB2023.FreeMagmaEquiv
import Linglib.Theories.Syntax.Minimalism.Formal.MCB2023.Accessible
import Linglib.Theories.Syntax.Minimalism.Formal.MCB2023.BinaryOptimality
import Linglib.Theories.Syntax.Minimalism.Formal.MCB2023.Coproduct
import Linglib.Theories.Syntax.Minimalism.Formal.Workspace
import Linglib.Theories.Syntax.Minimalism.Formal.XBar
import Linglib.Theories.Syntax.Minimalism.Formal.Linearization.LCA

-- Theories: Semantics.Montague (Montague architecture)
import Linglib.Theories.Semantics.Lexical.Adjective.Comparative
import Linglib.Theories.Semantics.Lexical.Adjective.Intensification
import Linglib.Theories.Semantics.Lexical.Adjective.Theory
import Linglib.Theories.Semantics.Reference.Binding
import Linglib.Theories.Semantics.Montague.Basic
import Linglib.Theories.Semantics.Montague.Composition
import Linglib.Theories.Semantics.Montague.Conjunction
import Linglib.Theories.Semantics.Montague.Derivation
import Linglib.Theories.Semantics.Montague.Lexicon
import Linglib.Theories.Semantics.Entailment.Polarity
import Linglib.Theories.Semantics.Tense.BranchingTime
import Linglib.Theories.Semantics.Montague.Scope
import Linglib.Phenomena.Entailment.Montague_TruthConditionsBridge
import Linglib.Theories.Semantics.Lexical.Determiner.Demonstrative.AhnZhu2025
import Linglib.Theories.Semantics.Probabilistic.Measurement.Basic
import Linglib.Theories.Semantics.Lexical.Numeral.Embedding
import Linglib.Theories.Semantics.Lexical.Numeral.Polysemy
import Linglib.Theories.Semantics.Lexical.Numeral.Precision
import Linglib.Theories.Semantics.Lexical.Numeral.Semantics
import Linglib.Theories.Semantics.Lexical.Determiner.Definite
import Linglib.Theories.Semantics.Lexical.Determiner.Quantifier

import Linglib.Theories.Semantics.Lexical.Expressives.Basic
import Linglib.Theories.Semantics.Lexical.Expressives.OutlookMarker
import Linglib.Theories.Semantics.Probabilistic.Scenarios.Basic
import Linglib.Theories.Semantics.Probabilistic.Graded.BayesianSemantics
import Linglib.Theories.Semantics.Probabilistic.Graded.GradedProposition
import Linglib.Theories.Pragmatics.RSA.Core.SemanticBackend
import Linglib.Theories.Interfaces.SyntaxSemantics.SyntaxInterface
import Linglib.Theories.Semantics.Montague.Modification
import Linglib.Theories.Semantics.Lexical.Noun.GradableNouns
import Linglib.Theories.Semantics.Lexical.Noun.Kind.Carlson1977
import Linglib.Theories.Semantics.Lexical.Noun.Kind.Chierchia1998
import Linglib.Theories.Semantics.Lexical.Noun.Kind.Dayal2004
import Linglib.Theories.Semantics.Lexical.Noun.Kind.Generics
import Linglib.Theories.Semantics.Lexical.Noun.Kind.Krifka2004
import Linglib.Theories.Semantics.Lexical.Noun.Relational.Barker2011
import Linglib.Theories.Semantics.Lexical.Noun.TypeShifting
import Linglib.Theories.Semantics.Lexical.Particle.Additive
import Linglib.Theories.Semantics.Lexical.Plural.Distributivity
import Linglib.Theories.Semantics.Montague.PTQ
import Linglib.Theories.Semantics.Entailment.AntiAdditivity
import Linglib.Theories.Semantics.Entailment.Basic
import Linglib.Theories.Semantics.Entailment.Monotonicity
import Linglib.Phenomena.Entailment.Entailment_NegationTestsBridge
import Linglib.Theories.Semantics.Entailment.PolarityBuilder
import Linglib.Theories.Semantics.Entailment.PresuppositionPolarity
import Linglib.Theories.Semantics.Entailment.ScaleInteraction
import Linglib.Theories.Semantics.Entailment.StrawsonEntailment
import Linglib.Theories.Semantics.Polarity.CzechNegation
import Linglib.Theories.Semantics.Focus.BackgroundedIslands
import Linglib.Phenomena.Focus.Focus_DomainWideningBridge
import Linglib.Theories.Semantics.Focus.Interpretation
import Linglib.Theories.Semantics.Focus.Particles
import Linglib.Theories.Semantics.Presupposition.BeliefEmbedding
import Linglib.Theories.Semantics.Presupposition.LocalContext
import Linglib.Theories.Semantics.Presupposition.OntologicalPreconditions
import Linglib.Theories.Semantics.Presupposition.TonhauserDerivation
import Linglib.Theories.Semantics.Tense.Compositional
import Linglib.Theories.Semantics.Tense.TenseAspectComposition
import Linglib.Theories.Semantics.Tense.TemporalAdverbials
import Linglib.Theories.Semantics.Tense.Evidential
import Linglib.Theories.Semantics.Tense.ParticipantPerspective
import Linglib.Theories.Semantics.Tense.TsiliaEtAl2026
import Linglib.Theories.Semantics.Tense.TemporalConnectives
import Linglib.Theories.Semantics.Tense.PerfectPolysemy
import Linglib.Theories.Semantics.Tense.SequenceOfTense
import Linglib.Theories.Semantics.Tense.Declerck
import Linglib.Theories.Semantics.Montague.Variables
import Linglib.Theories.Semantics.Lexical.Verb.Aspect
import Linglib.Theories.Semantics.Lexical.Verb.ChangeOfState.Theory
import Linglib.Theories.Semantics.Lexical.Verb.Habituals
import Linglib.Theories.Semantics.Lexical.Verb.SelectionalPreferences
import Linglib.Theories.Semantics.Lexical.Verb.ViewpointAspect

-- Theories: Semantics.Events (neo-Davidsonian)
import Linglib.Theories.Semantics.Events.Basic
import Linglib.Theories.Semantics.Events.DegreeEvents
import Linglib.Theories.Semantics.Events.ThematicRoles
import Linglib.Theories.Semantics.Events.ThematicRolesGrounding
import Linglib.Theories.Semantics.Events.Mereology
import Linglib.Theories.Semantics.Events.StratifiedReference
import Linglib.Theories.Semantics.Events.Krifka1989
import Linglib.Theories.Semantics.Events.Krifka1998
import Linglib.Theories.Semantics.Events.Agentivity
import Linglib.Theories.Semantics.Events.ProtoRoles
import Linglib.Theories.Semantics.Events.EventStructure
import Linglib.Theories.Semantics.Events.RootTypology
import Linglib.Theories.Semantics.Events.SpatialTrace
import Linglib.Theories.Semantics.Events.DimensionBridge
import Linglib.Theories.Semantics.Events.TemporalDecomposition

-- Theories: Semantics.Intensional (possible-worlds semantics)
import Linglib.Theories.Semantics.Intensional.Basic
import Linglib.Theories.Semantics.Attitudes.BuilderProperties
import Linglib.Theories.Semantics.Attitudes.CDistributivity
import Linglib.Theories.Semantics.Attitudes.ContentComposition
import Linglib.Theories.Semantics.Attitudes.ContrafactiveGap
import Linglib.Theories.Semantics.Attitudes.Doxastic
import Linglib.Theories.Semantics.Attitudes.Intensional
import Linglib.Theories.Semantics.Attitudes.Parasitic
import Linglib.Theories.Semantics.Attitudes.Preferential
import Linglib.Theories.Semantics.Attitudes.SituationDependent
import Linglib.Theories.Semantics.Attitudes.NegRaising
import Linglib.Theories.Semantics.Attitudes.Monotonicity
import Linglib.Theories.Semantics.Truthmaker.Basic
import Linglib.Theories.Semantics.Causation.Basic
import Linglib.Theories.Semantics.Causation.Builder
import Linglib.Theories.Semantics.Causation.CoerciveImplication
import Linglib.Theories.Semantics.Causation.Examples
import Linglib.Theories.Semantics.Causation.GradedCausation
import Linglib.Theories.Semantics.Causation.Integration
import Linglib.Theories.Semantics.Causation.Necessity
import Linglib.Theories.Semantics.Causation.Sufficiency
import Linglib.Theories.Semantics.Causation.Implicative
import Linglib.Theories.Semantics.Causation.ProductionDependence
import Linglib.Theories.Semantics.Causation.Resultatives
import Linglib.Theories.Semantics.Conditionals.Assertability
import Linglib.Theories.Semantics.Conditionals.Basic
import Linglib.Theories.Semantics.Conditionals.ConditionalType
import Linglib.Theories.Semantics.Conditionals.Counterfactual
import Linglib.Theories.Semantics.Conditionals.Exhaustivity
import Linglib.Theories.Semantics.Conditionals.LeftNested
import Linglib.Theories.Semantics.Modality.Basic
import Linglib.Theories.Semantics.Modality.Compare
import Linglib.Theories.Semantics.Modality.Disjunction
import Linglib.Theories.Semantics.Modality.BiasedPQ
import Linglib.Theories.Semantics.Modality.Kratzer
import Linglib.Theories.Semantics.Modality.PhillipsBrown
import Linglib.Theories.Semantics.Modality.ProbabilityOrdering
import Linglib.Theories.Semantics.Modality.SatisfactionOrdering
import Linglib.Theories.Semantics.Modality.Ability
import Linglib.Theories.Semantics.Modality.Simple
import Linglib.Theories.Semantics.Modality.Typology
import Linglib.Theories.Semantics.Mood.Basic
import Linglib.Theories.Semantics.Reference.Basic
import Linglib.Theories.Semantics.Reference.Kaplan
import Linglib.Theories.Semantics.Reference.Donnellan
import Linglib.Theories.Semantics.Reference.Almog2014
import Linglib.Theories.Semantics.Reference.Demonstratives
import Linglib.Theories.Semantics.Reference.KaplanLD
import Linglib.Theories.Semantics.Reference.Monsters
import Linglib.Theories.Semantics.Reference.Kripke
import Linglib.Theories.Semantics.Intensional.Situations.Elbourne
import Linglib.Theories.Semantics.Intensional.Situations.Percus
import Linglib.Theories.Semantics.Tense.Basic
import Linglib.Theories.Semantics.Tense.Abusch
import Linglib.Theories.Semantics.Tense.VonStechow
import Linglib.Theories.Semantics.Tense.Kratzer
import Linglib.Theories.Semantics.Tense.Ogihara
import Linglib.Theories.Semantics.Tense.Klecha
import Linglib.Theories.Semantics.Tense.Deal
import Linglib.Theories.Semantics.Tense.Sharvit
import Linglib.Theories.Syntax.Minimalism.Tense.Zeijlstra
import Linglib.Theories.Syntax.Minimalism.Tense.Wurmbrand

-- Theories: Semantics.Questions
import Linglib.Theories.Semantics.Questions.Answerhood
import Linglib.Theories.Semantics.Questions.Basic
import Linglib.Theories.Semantics.Questions.Coordination
import Linglib.Theories.Semantics.Questions.EconomyOddness
import Linglib.Theories.Semantics.Questions.EntropyNPIs
import Linglib.Theories.Semantics.Questions.GSVanRooyBridge
import Linglib.Theories.Semantics.Questions.Hamblin
import Linglib.Theories.Semantics.Questions.Inquisitive
import Linglib.Theories.Semantics.Questions.LeftPeriphery
import Linglib.Theories.Semantics.Questions.LiftedTypes
import Linglib.Theories.Semantics.Questions.MentionSome
import Linglib.Theories.Semantics.Questions.Partition
import Linglib.Theories.Semantics.Questions.Polarity
import Linglib.Theories.Semantics.Questions.QParticleLayer
import Linglib.Theories.Semantics.Questions.PragmaticAnswerhood
import Linglib.Theories.Semantics.Questions.ProbabilisticAnswerhood
import Linglib.Theories.Semantics.Questions.ScopeReadings
import Linglib.Theories.Semantics.Questions.SignalingGames
import Linglib.Theories.Semantics.Questions.DegreeQuestion
import Linglib.Theories.Semantics.Questions.VerumFocus

-- Theories: NeoGricean
import Linglib.Theories.Pragmatics.NeoGricean.Analyticity
import Linglib.Theories.Pragmatics.NeoGricean.ConventionalImplicatures
import Linglib.Theories.Pragmatics.NeoGricean.Core.AlternativeGeneration
import Linglib.Theories.Pragmatics.NeoGricean.Core.Alternatives
import Linglib.Theories.Pragmatics.NeoGricean.Core.Basic
import Linglib.Theories.Pragmatics.NeoGricean.Core.Competence
import Linglib.Theories.Pragmatics.NeoGricean.Core.Markedness
import Linglib.Theories.Pragmatics.NeoGricean.Evaluativity
import Linglib.Theories.Pragmatics.NeoGricean.Exhaustivity.Basic
import Linglib.Theories.Pragmatics.NeoGricean.Exhaustivity.Chierchia2004
import Linglib.Theories.Pragmatics.NeoGricean.Exhaustivity.Chierchia2013
import Linglib.Theories.Pragmatics.NeoGricean.Exhaustivity.EFCI
import Linglib.Theories.Pragmatics.NeoGricean.Exhaustivity.EFCIClosure
import Linglib.Theories.Pragmatics.NeoGricean.Exhaustivity.Interface
import Linglib.Theories.Pragmatics.NeoGricean.Implementations.BarLevFox2020
import Linglib.Theories.Pragmatics.NeoGricean.Implementations.FoxSpector2018
import Linglib.Theories.Pragmatics.NeoGricean.Implementations.MontagueExhaustivity
import Linglib.Theories.Pragmatics.NeoGricean.Implementations.Spector2007
import Linglib.Theories.Pragmatics.NeoGricean.NegationScope
import Linglib.Theories.Pragmatics.NeoGricean.Presuppositions
import Linglib.Theories.Pragmatics.NeoGricean.ScalarImplicatures.Basic
import Linglib.Theories.Pragmatics.NeoGricean.Constraints.NumericalExpressions
import Linglib.Theories.Pragmatics.NeoGricean.Constraints.Wang2025
import Linglib.Theories.Pragmatics.NeoGricean.ScalarImplicatures.Operations

-- Theories: RSA
import Linglib.Theories.Pragmatics.RSA.Core.Basic
import Linglib.Theories.Pragmatics.RSA.Core.BasicQ
import Linglib.Theories.Pragmatics.RSA.Core.ChainComparison
import Linglib.Theories.Pragmatics.RSA.Core.CombinedUtility
import Linglib.Theories.Pragmatics.RSA.Core.Config
import Linglib.Theories.Pragmatics.RSA.Core.CompositionalRSA
import Linglib.Theories.Pragmatics.RSA.Core.Convergence
import Linglib.Theories.Pragmatics.RSA.Core.Discourse
import Linglib.Theories.Pragmatics.RSA.Core.DiscourseIntegration
import Linglib.Theories.Pragmatics.RSA.Core.EmbeddedSI
import Linglib.Theories.Pragmatics.RSA.Core.Eval
import Linglib.Theories.Pragmatics.RSA.Core.Intensional
import Linglib.Theories.Pragmatics.RSA.Core.Model
import Linglib.Theories.Pragmatics.RSA.Core.Noise
import Linglib.Theories.Pragmatics.RSA.Core.Distribution
import Linglib.Theories.Pragmatics.RSA.Core.RationalPower
import Linglib.Theories.Pragmatics.RSA.Core.Priors
import Linglib.Theories.Pragmatics.RSA.Core.Softmax.Limits
import Linglib.Theories.Pragmatics.RSA.Implementations.DegenEtAl2020
import Linglib.Theories.Pragmatics.RSA.Quantities
import Linglib.Theories.Pragmatics.RSA.Extensions.ArgumentativeStrength
import Linglib.Theories.Pragmatics.RSA.Extensions.NoncooperativeCommunication
import Linglib.Theories.Pragmatics.RSA.Extensions.InformationTheory.Basic
import Linglib.Theories.Pragmatics.RSA.Extensions.InformationTheory.PhaseTransition
import Linglib.Theories.Pragmatics.RSA.Extensions.InformationTheory.RateDistortion
import Linglib.Theories.Pragmatics.RSA.Extensions.InformationTheory.UtilityDynamics
import Linglib.Theories.Pragmatics.RSA.Extensions.InformationTheory.UtilityNonMonotonicity
import Linglib.Theories.Pragmatics.RSA.Extensions.LexicalUncertainty.Basic
import Linglib.Theories.Pragmatics.RSA.Extensions.LexicalUncertainty.Compositional
import Linglib.Theories.Pragmatics.RSA.Implementations.Alsop2024
import Linglib.Theories.Pragmatics.RSA.Implementations.BarnettEtAl2022
import Linglib.Theories.Pragmatics.RSA.Implementations.BellerGerstenberg2025
import Linglib.Theories.Pragmatics.RSA.Implementations.BergenGoodman2015
import Linglib.Theories.Pragmatics.RSA.Implementations.ChampollionAlsopGrosu2019
import Linglib.Theories.Pragmatics.RSA.Implementations.CremersWilcoxSpector2023
import Linglib.Theories.Pragmatics.RSA.Implementations.CumminsFranke2021
import Linglib.Theories.Pragmatics.RSA.Implementations.EgreEtAl2023
import Linglib.Theories.Pragmatics.RSA.Implementations.Franke2011
import Linglib.Theories.Pragmatics.RSA.Implementations.FrankeBergen2020
import Linglib.Theories.Pragmatics.RSA.Implementations.GrusdtLassiterFranke2022
import Linglib.Theories.Pragmatics.RSA.Implementations.HardingGerstenbergIcard2025
import Linglib.Theories.Pragmatics.RSA.Implementations.HawkinsEtAl2025
import Linglib.Theories.Pragmatics.RSA.Implementations.HawkinsGweonGoodman2021
import Linglib.Phenomena.Gradability.RSA_Nouwen2024Bridge
import Linglib.Theories.Pragmatics.RSA.Implementations.PottsEtAl2016
import Linglib.Theories.Pragmatics.RSA.Implementations.QingEtAl2016
import Linglib.Theories.Pragmatics.RSA.Implementations.ScontrasPearl2021
import Linglib.Theories.Pragmatics.RSA.Implementations.ScontrasTonhauser2025
import Linglib.Theories.Pragmatics.RSA.Implementations.ScopeFreezing
import Linglib.Theories.Pragmatics.RSA.Implementations.SumersEtAl2023
import Linglib.Theories.Pragmatics.RSA.Implementations.TesslerFranke2020
import Linglib.Theories.Pragmatics.RSA.Implementations.TesslerGoodman2019
import Linglib.Theories.Pragmatics.RSA.Implementations.TesslerGoodman2022
import Linglib.Theories.Pragmatics.RSA.Implementations.VanTielEtAl2021
import Linglib.Theories.Pragmatics.RSA.Implementations.WaldonDegen2021
import Linglib.Theories.Pragmatics.RSA.Implementations.YoonEtAl2020
import Linglib.Theories.Pragmatics.RSA.Questions.Basic
import Linglib.Theories.Pragmatics.RSA.Questions.PolarQuestions
import Linglib.Theories.Pragmatics.RSA.Questions.ResponseSelection
import Linglib.Theories.Pragmatics.RSA.ScalarImplicatures.Basic
import Linglib.Theories.Pragmatics.RSA.ScalarImplicatures.Embedded.Attitudes
import Linglib.Theories.Pragmatics.RSA.ScalarImplicatures.Embedded.Basic
import Linglib.Theories.Pragmatics.RSA.ScalarImplicatures.Embedded.Conditionals
import Linglib.Theories.Pragmatics.RSA.ScalarImplicatures.Embedded.Questions
import Linglib.Theories.Pragmatics.RSA.ScalarImplicatures.Hurford

-- Theories: Sociolinguistics
import Linglib.Theories.Sociolinguistics.PropertySpace
import Linglib.Theories.Sociolinguistics.SCM
import Linglib.Theories.Sociolinguistics.EckertMontague
import Linglib.Theories.Sociolinguistics.SMG

-- Theories: SDS
import Linglib.Theories.Semantics.Probabilistic.SDS.Core
import Linglib.Theories.Semantics.Probabilistic.SDS.Examples
import Linglib.Phenomena.Nonliteral.Humor.SDS_KaoEtAl2016Bridge
import Linglib.Theories.Semantics.Probabilistic.SDS.Marginalization
import Linglib.Theories.Semantics.Probabilistic.SDS.MeasureTheory
import Linglib.Theories.Semantics.Probabilistic.SDS.ThresholdInstances
import Linglib.Theories.Semantics.Probabilistic.SDS.ThresholdSemantics

