import Linglib.Core.Combinatorics.RootedTree.Decorated
import Mathlib.Algebra.MonoidAlgebra.Basic

/-!
# Bialgebra Carrier of Decorated Forests @cite{marcolli-chomsky-berwick-2025}

The `R`-linear free module on `Forest α` (multisets of decorated trees),
with multiplication = disjoint union of forests. This is the underlying
carrier of the Connes-Kreimer-style bialgebra of decorated rooted trees.

Per @cite{marcolli-chomsky-berwick-2025} Lemma 1.2.10, the contraction
coproduct (next file: `Coproduct.lean`) gives `Hc` the structure of a
graded *commutative* bialgebra — but NOT (yet) a Hopf algebra. The
Hopf algebra arises only after quotienting by the ideal generated by
`1 - α` for `α ∈ SO_0` (the leaves are degree-0 group-like elements
lacking inverses, which prevents the antipode from existing on `Hc`
itself). The eventual Hopf algebra is on the quotient `Hc / (1 - α)`.

## On `abbrev Hc`

`Hc R α` is an `abbrev` for `AddMonoidAlgebra R (Forest α)`. All
mathlib-provided algebraic structure on `AddMonoidAlgebra` (Semiring,
CommSemiring, Ring, CommRing, Algebra, FunLike) is inherited
automatically. **Note**: this also activates mathlib's
`instance : Bialgebra R (AddMonoidAlgebra R M)` from
`Mathlib/RingTheory/Bialgebra/MonoidAlgebra.lean`, which uses the
*group-like* coproduct `Δ(F) = F ⊗ F` — NOT the Connes-Kreimer
coproduct. The Connes-Kreimer coproducts (`comulAlgHom` for Δ^c,
`comulDelAlgHom` for Δ^d in `Coproduct.lean`) are reachable BY NAME
only, never as typeclass instances.

Until the (1 - α) quotient lands and the Connes-Kreimer Hopf
structure is registered as the canonical instance, downstream code
must call `comulAlgHom` / `comulDelAlgHom` explicitly rather than
relying on `Coalgebra.comul` projection.

## Layer status

`[UPSTREAM]` candidate. Future home is something like
`Mathlib.Combinatorics.HopfAlgebra.ConnesKreimer.Defs`. This file is
part of the Stage 0.5 hoist out of `Theories/Syntax/Minimalist/Hopf/`
(per `scratch/mcb_stage1_plan.md`).
-/

namespace ConnesKreimer

/-- The bialgebra carrier: formal `R`-linear combinations of forests.
    `abbrev` so all `AddMonoidAlgebra` instances apply automatically.
    See module docstring for the group-like-Bialgebra activation
    caveat. -/
abbrev Hc (R : Type*) [CommSemiring R] (α : Type*) [DecidableEq α] : Type _ :=
  AddMonoidAlgebra R (Forest α)

end ConnesKreimer
