import Linglib.Core.Combinatorics.RootedTree.Decorated
import Mathlib.Algebra.MonoidAlgebra.Basic

/-!
# Bialgebra Carrier of Decorated Forests @cite{marcolli-chomsky-berwick-2025}

The `R`-linear free module on `Forest α` (multisets of decorated trees),
with multiplication = disjoint union of forests. This is the underlying
carrier of the Connes-Kreimer-style bialgebra of decorated rooted trees.

Per @cite{marcolli-chomsky-berwick-2025} Lemma 1.2.10, the contraction
coproduct (next file: `Coproduct.lean`) gives `Hc` the structure of a
graded *commutative* bialgebra — but NOT (yet) a Hopf algebra. The
Hopf algebra arises only after quotienting by the ideal generated by
`1 - α` for `α ∈ SO_0` (the leaves are degree-0 group-like elements
lacking inverses, which prevents the antipode from existing on `Hc`
itself). The eventual Hopf algebra is on the quotient `Hc / (1 - α)`.

## On `def Hc`, not `abbrev Hc`

`Hc R α` is a `def` (not `abbrev`) for `AddMonoidAlgebra R (Forest α)`.
This is the **mathlib-canonical pattern** (cf. `Mathlib.Algebra.MonoidAlgebra.Defs`
where `MonoidAlgebra R M : Type _ := M →₀ R` is also `def`, generated
to `AddMonoidAlgebra` via `to_additive_dont_translate`): the wrapper
`def` keeps the typeclass slot unique to *our* Connes-Kreimer
`Bialgebra` instance (registered in `Bialgebra.lean` via
`Bialgebra.ofAlgHom`), preventing conflict with mathlib's
`AddMonoidAlgebra.instBialgebra` group-like default
(Δ(F) = F ⊗ F) which would otherwise fire automatically and give the
wrong coproduct.

The mathlib pattern: a `def`-wrapped algebra type forwards needed
foundational instances (Semiring, Algebra, FunLike) manually so the
typeclass slot for the discriminated structure (Bialgebra, here) is
unambiguous.

## Layer status

`[UPSTREAM]` candidate. Future home is something like
`Mathlib.Combinatorics.HopfAlgebra.ConnesKreimer.Defs`. This file is
part of the Stage 0.5/0.7/1 hoist out of `Theories/Syntax/Minimalist/Hopf/`
(per `scratch/mcb_stage1_plan.md`).
-/

namespace ConnesKreimer

/-- The bialgebra carrier: formal `R`-linear combinations of forests.

    `def` (not `abbrev`) per the mathlib `MonoidAlgebra` pattern: the
    wrapper keeps the typeclass slot unique to our Connes-Kreimer
    `Bialgebra` instance (in `Bialgebra.lean`), preventing conflict
    with mathlib's group-like default. See module docstring. -/
def Hc (R : Type*) [CommSemiring R] (α : Type*) [DecidableEq α] : Type _ :=
  AddMonoidAlgebra R (Forest α)

/-! ## Mathlib instances forwarded for `Hc R α`

Since `Hc` is `def`, mathlib instances on `AddMonoidAlgebra R (Forest α)`
need explicit forwarding to be visible on `Hc R α`. -/

noncomputable instance Hc.instSemiring (R : Type*) [CommSemiring R]
    (α : Type*) [DecidableEq α] : Semiring (Hc R α) :=
  inferInstanceAs (Semiring (AddMonoidAlgebra R (Forest α)))

noncomputable instance Hc.instCommSemiring (R : Type*) [CommSemiring R]
    (α : Type*) [DecidableEq α] : CommSemiring (Hc R α) :=
  inferInstanceAs (CommSemiring (AddMonoidAlgebra R (Forest α)))

noncomputable instance Hc.instRing (R : Type*) [CommRing R]
    (α : Type*) [DecidableEq α] : Ring (Hc R α) :=
  inferInstanceAs (Ring (AddMonoidAlgebra R (Forest α)))

noncomputable instance Hc.instCommRing (R : Type*) [CommRing R]
    (α : Type*) [DecidableEq α] : CommRing (Hc R α) :=
  inferInstanceAs (CommRing (AddMonoidAlgebra R (Forest α)))

noncomputable instance Hc.instAlgebra (R : Type*) [CommSemiring R]
    (α : Type*) [DecidableEq α] : Algebra R (Hc R α) :=
  inferInstanceAs (Algebra R (AddMonoidAlgebra R (Forest α)))

/-- Forward the `Finsupp.funLike` instance so that elements of `Hc R α`
    can be applied as functions `Forest α → R`. Needed for `counit`
    and other finsupp-flavored lemmas. -/
instance Hc.instFunLike (R : Type*) [CommSemiring R]
    (α : Type*) [DecidableEq α] : FunLike (Hc R α) (Forest α) R :=
  inferInstanceAs (FunLike (Forest α →₀ R) (Forest α) R)

end ConnesKreimer
