import Linglib.Core.Scales.EpistemicScale.Cancellation

/-!
# Shared helpers for Fin 4 cancellation chamber proofs

Auto-generated helper lemmas used by the 88 chamber proofs.
-/

namespace Core.Scale

attribute [local instance] Classical.propDecidable

-- Precomputed set-difference equalities for Fin 4
lemma sd_0_0 : ({(0 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0_01 : ({(0 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0_02 : ({(0 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0_03 : ({(0 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0_012 : ({(0 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0_013 : ({(0 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0_023 : ({(0 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0_0123 : ({(0 : Fin 4)} : Set (Fin 4)) \ (Set.univ : Set (Fin 4)) = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_1_1 : ({(1 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_1_01 : ({(1 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_1_12 : ({(1 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_1_13 : ({(1 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_1_012 : ({(1 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_1_013 : ({(1 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_1_123 : ({(1 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_1_0123 : ({(1 : Fin 4)} : Set (Fin 4)) \ (Set.univ : Set (Fin 4)) = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_2_2 : ({(2 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_2_02 : ({(2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_2_12 : ({(2 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_2_23 : ({(2 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_2_012 : ({(2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_2_023 : ({(2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_2_123 : ({(2 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_2_0123 : ({(2 : Fin 4)} : Set (Fin 4)) \ (Set.univ : Set (Fin 4)) = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_3_3 : ({(3 : Fin 4)} : Set (Fin 4)) \ {(3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_3_03 : ({(3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_3_13 : ({(3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_3_23 : ({(3 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_3_013 : ({(3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_3_023 : ({(3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_3_123 : ({(3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_3_0123 : ({(3 : Fin 4)} : Set (Fin 4)) \ (Set.univ : Set (Fin 4)) = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_01_0 : ({(0 : Fin 4), (1 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_01_1 : ({(0 : Fin 4), (1 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_01_01 : ({(0 : Fin 4), (1 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_01_02 : ({(0 : Fin 4), (1 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_01_03 : ({(0 : Fin 4), (1 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (3 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_01_12 : ({(0 : Fin 4), (1 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_01_13 : ({(0 : Fin 4), (1 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_01_012 : ({(0 : Fin 4), (1 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_01_013 : ({(0 : Fin 4), (1 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_01_023 : ({(0 : Fin 4), (1 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_01_123 : ({(0 : Fin 4), (1 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_01_0123 : ({(0 : Fin 4), (1 : Fin 4)} : Set (Fin 4)) \ (Set.univ : Set (Fin 4)) = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_02_0 : ({(0 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_02_2 : ({(0 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_02_01 : ({(0 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_02_02 : ({(0 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_02_03 : ({(0 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (3 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_02_12 : ({(0 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_02_23 : ({(0 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_02_012 : ({(0 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_02_013 : ({(0 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_02_023 : ({(0 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_02_123 : ({(0 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_02_0123 : ({(0 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ (Set.univ : Set (Fin 4)) = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_03_0 : ({(0 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_03_3 : ({(0 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(3 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_03_01 : ({(0 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_03_02 : ({(0 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_03_03 : ({(0 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_03_13 : ({(0 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_03_23 : ({(0 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_03_012 : ({(0 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_03_013 : ({(0 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_03_023 : ({(0 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_03_123 : ({(0 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_03_0123 : ({(0 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ (Set.univ : Set (Fin 4)) = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_12_1 : ({(1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_12_2 : ({(1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_12_01 : ({(1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_12_02 : ({(1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_12_12 : ({(1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_12_13 : ({(1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (3 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_12_23 : ({(1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4), (3 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_12_012 : ({(1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_12_013 : ({(1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_12_023 : ({(1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_12_123 : ({(1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_12_0123 : ({(1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ (Set.univ : Set (Fin 4)) = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_13_1 : ({(1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_13_3 : ({(1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(3 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_13_01 : ({(1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_13_03 : ({(1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (3 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_13_12 : ({(1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_13_13 : ({(1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_13_23 : ({(1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4), (3 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_13_012 : ({(1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_13_013 : ({(1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_13_023 : ({(1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_13_123 : ({(1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_13_0123 : ({(1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ (Set.univ : Set (Fin 4)) = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_23_2 : ({(2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_23_3 : ({(2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(3 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_23_02 : ({(2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_23_03 : ({(2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (3 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_23_12 : ({(2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_23_13 : ({(2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (3 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_23_23 : ({(2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_23_012 : ({(2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_23_013 : ({(2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_23_023 : ({(2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_23_123 : ({(2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_23_0123 : ({(2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ (Set.univ : Set (Fin 4)) = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_012_0 : ({(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4)} = {(1 : Fin 4), (2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_012_1 : ({(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4)} = {(0 : Fin 4), (2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_012_2 : ({(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4)} = {(0 : Fin 4), (1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_012_01 : ({(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_012_02 : ({(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_012_03 : ({(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (3 : Fin 4)} = {(1 : Fin 4), (2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_012_12 : ({(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_012_13 : ({(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4), (2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_012_23 : ({(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4), (1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_012_012 : ({(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_012_013 : ({(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_012_023 : ({(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_012_123 : ({(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_012_0123 : ({(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} : Set (Fin 4)) \ (Set.univ : Set (Fin 4)) = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_013_0 : ({(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4)} = {(1 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_013_1 : ({(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4)} = {(0 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_013_3 : ({(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(3 : Fin 4)} = {(0 : Fin 4), (1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_013_01 : ({(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_013_02 : ({(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4)} = {(1 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_013_03 : ({(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (3 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_013_12 : ({(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4)} = {(0 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_013_13 : ({(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_013_23 : ({(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4), (1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_013_012 : ({(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_013_013 : ({(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_013_023 : ({(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_013_123 : ({(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_013_0123 : ({(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ (Set.univ : Set (Fin 4)) = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_023_0 : ({(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4)} = {(2 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_023_2 : ({(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4)} = {(0 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_023_3 : ({(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(3 : Fin 4)} = {(0 : Fin 4), (2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_023_01 : ({(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4)} = {(2 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_023_02 : ({(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_023_03 : ({(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (3 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_023_12 : ({(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4)} = {(0 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_023_13 : ({(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4), (2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_023_23 : ({(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_023_012 : ({(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_023_013 : ({(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_023_023 : ({(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_023_123 : ({(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_023_0123 : ({(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ (Set.univ : Set (Fin 4)) = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_123_1 : ({(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4)} = {(2 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_123_2 : ({(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4)} = {(1 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_123_3 : ({(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(3 : Fin 4)} = {(1 : Fin 4), (2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_123_01 : ({(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4)} = {(2 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_123_02 : ({(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4)} = {(1 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_123_03 : ({(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (3 : Fin 4)} = {(1 : Fin 4), (2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_123_12 : ({(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_123_13 : ({(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (3 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_123_23 : ({(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(2 : Fin 4), (3 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_123_012 : ({(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_123_013 : ({(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_123_023 : ({(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_123_123 : ({(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_123_0123 : ({(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} : Set (Fin 4)) \ (Set.univ : Set (Fin 4)) = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0123_0 : (Set.univ : Set (Fin 4)) \ {(0 : Fin 4)} = {(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0123_1 : (Set.univ : Set (Fin 4)) \ {(1 : Fin 4)} = {(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0123_2 : (Set.univ : Set (Fin 4)) \ {(2 : Fin 4)} = {(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0123_3 : (Set.univ : Set (Fin 4)) \ {(3 : Fin 4)} = {(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0123_01 : (Set.univ : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4)} = {(2 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0123_02 : (Set.univ : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4)} = {(1 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0123_03 : (Set.univ : Set (Fin 4)) \ {(0 : Fin 4), (3 : Fin 4)} = {(1 : Fin 4), (2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0123_12 : (Set.univ : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4)} = {(0 : Fin 4), (3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0123_13 : (Set.univ : Set (Fin 4)) \ {(1 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4), (2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0123_23 : (Set.univ : Set (Fin 4)) \ {(2 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4), (1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0123_012 : (Set.univ : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (2 : Fin 4)} = {(3 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0123_013 : (Set.univ : Set (Fin 4)) \ {(0 : Fin 4), (1 : Fin 4), (3 : Fin 4)} = {(2 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0123_023 : (Set.univ : Set (Fin 4)) \ {(0 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = {(1 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0123_123 : (Set.univ : Set (Fin 4)) \ {(1 : Fin 4), (2 : Fin 4), (3 : Fin 4)} = {(0 : Fin 4)} := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]
lemma sd_0123_0123 : (Set.univ : Set (Fin 4)) \ (Set.univ : Set (Fin 4)) = (∅ : Set (Fin 4)) := by ext x; fin_cases x <;> simp [Set.mem_diff, Set.mem_insert_iff]

end Core.Scale