/-
Copyright (c) 2026 Robert Hawkins. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Robert Hawkins
-/
module

public import Mathlib.Algebra.BigOperators.Field
public import Mathlib.Algebra.BigOperators.Fin
public import Mathlib.Algebra.Order.BigOperators.Ring.Finset
public import Mathlib.Basic.Real.Basic
public import Mathlib.RingTheory.Polynomial.Pochhammer

/-!
# The Pólya urn

An urn holds balls of the colours in `α` with positive weights `θ c`. Draws are made one at a
time; after `n` draws in which colour `c` came up `x c` times, the next draw is colour `c` with
probability

  `(θ c + x c) / (∑ θ + n)`,

the prediction rule of [pitman-2006] Exercise 2.2.2, `polyaUrnPredictive`. Multiplying these
probabilities along a sequence gives the probability of the sequence, which depends only on its
count vector `x`:

  `polyaUrnProb θ x = ∏ c, (θ c)_{x c} / (∑ θ)_{∑ x}`

in rising factorials `(a)_m = a (a + 1) ⋯ (a + m - 1)` (`ascPochhammer`). The drawn sequence is
exchangeable, with Dirichlet-distributed limiting frequencies ([pitman-2006] Exercise 2.2.2).

This file is measure-free: the law of the sequence, its exchangeability and the
Dirichlet–multinomial distribution of the counts are in
`Linglib.Core.Probability.Distributions.DirichletMultinomial`.

## Main definitions

* `ProbabilityTheory.countVec s`: how often each colour occurs in the sequence `s`.
* `ProbabilityTheory.polyaUrnPredictive θ x c`: the probability of drawing `c` next.
* `ProbabilityTheory.polyaUrnProb θ x`: the probability of a sequence with count vector `x`.

## Main results

* `ProbabilityTheory.polyaUrnProb_update_succ`, `ProbabilityTheory.polyaUrnProb_countVec_snoc`:
  drawing colour `c` multiplies the probability by the probability of drawing `c`.
* `ProbabilityTheory.polyaUrnProb_add`: conjugacy; after the counts `x`, the urn with weights
  `θ + x` gives the probability of the further counts `y`.
* `ProbabilityTheory.sum_polyaUrnPredictive`: the prediction rule is a probability.

## Implementation notes

The weights are a plain function `θ : α → ℝ`, positivity being a hypothesis of the results that
need it, and updating them by observed counts is the sum `θ + x`. The identities between
`polyaUrnProb` and `polyaUrnPredictive` hold without hypotheses.

The partition of the draws generated by the symmetric urn with `m` colours of weight `κ` is the
Pitman–Yor partition with discount `-κ` and concentration `m κ` ([pitman-2006] Exercise 2.2.5
and p. 61); as `κ → 0` with `m κ` tending to a concentration `c > 0` it tends to the
discount-`0` partition, generated by the Blackwell–MacQueen urn ([pitman-2006] Exercise 2.2.6 and
p. 61). Neither is formalized here.

## References

* [pitman-2006]
-/

@[expose] public section

open Finset

namespace ProbabilityTheory

variable {α : Type*}

/-! ### Count vectors -/

section CountVec

variable [DecidableEq α] {n : ℕ}

/-- The count vector of a sequence: how often each colour occurs in it. -/
def countVec (s : Fin n → α) (c : α) : ℕ :=
  #{i | s i = c}

@[simp]
theorem countVec_zero (s : Fin 0 → α) : countVec s = 0 := by
  funext c; simp [countVec]

/-- Prepending a draw increments its colour's count. -/
theorem countVec_cons (c : α) (s : Fin n → α) :
    countVec (Fin.cons c s : Fin (n + 1) → α) =
      Function.update (countVec s) c (countVec s c + 1) := by
  funext d
  simp only [countVec, card_filter, Fin.sum_univ_succ, Fin.cons_zero, Fin.cons_succ]
  obtain rfl | hd := eq_or_ne d c
  · simp [add_comm]
  · simp [Function.update_of_ne hd, Ne.symm hd, countVec]

/-- Appending a draw increments its colour's count. -/
theorem countVec_snoc (c : α) (s : Fin n → α) :
    countVec (Fin.snoc s c : Fin (n + 1) → α) =
      Function.update (countVec s) c (countVec s c + 1) := by
  funext d
  simp only [countVec, card_filter, Fin.sum_univ_castSucc, Fin.snoc_castSucc, Fin.snoc_last]
  obtain rfl | hd := eq_or_ne d c
  · simp
  · simp [Function.update_of_ne hd, Ne.symm hd, countVec]

/-- Permuting a sequence does not change its counts. -/
theorem countVec_comp_perm (s : Fin n → α) (σ : Equiv.Perm (Fin n)) :
    countVec (s ∘ σ) = countVec s := by
  funext c
  exact card_bij (fun i _ ↦ σ i) (by simp) (fun _ _ _ _ h ↦ σ.injective h)
    (fun j hj ↦ ⟨σ.symm j, by simpa using hj, by simp⟩)

/-- The counts of a sequence of `n` draws add up to `n`. -/
theorem sum_countVec [Fintype α] (s : Fin n → α) : ∑ c, countVec s c = n := by
  simp only [countVec]
  rw [← card_eq_sum_card_fiberwise (f := s) (t := univ) fun _ _ ↦ mem_univ _, card_univ,
    Fintype.card_fin]

end CountVec

/-! ### The prediction rule and the probability of a sequence -/

variable [Fintype α] (θ : α → ℝ)

/-- The probability that the urn with weights `θ` draws colour `c` after draws with counts `x`:
`(θ c + x c) / (∑ θ + ∑ x)` ([pitman-2006] Exercise 2.2.2). -/
noncomputable def polyaUrnPredictive (x : α → ℕ) (c : α) : ℝ :=
  (θ c + x c) / (∑ i, θ i + ∑ i, (x i : ℝ))

/-- The probability that the urn with weights `θ` draws a given sequence with counts `x`. -/
noncomputable def polyaUrnProb (x : α → ℕ) : ℝ :=
  (∏ c, (ascPochhammer ℝ (x c)).eval (θ c)) / (ascPochhammer ℝ (∑ c, x c)).eval (∑ c, θ c)

@[simp]
theorem polyaUrnProb_zero : polyaUrnProb θ 0 = 1 := by
  simp [polyaUrnProb]

/-- The first draw is proportional to the weights. -/
theorem polyaUrnPredictive_zero (c : α) : polyaUrnPredictive θ 0 c = θ c / ∑ i, θ i := by
  simp [polyaUrnPredictive]

/-- Drawing colour `c` multiplies the probability of the sequence by the probability of drawing
`c`: the rising-factorial recursion `(a)_{m + 1} = (a)_m (a + m)` at `c` and at the total. -/
theorem polyaUrnProb_update_succ [DecidableEq α] (x : α → ℕ) (c : α) :
    polyaUrnProb θ (Function.update x c (x c + 1)) =
      polyaUrnProb θ x * polyaUrnPredictive θ x c := by
  have hsum : ∑ i, Function.update x c (x c + 1) i = ∑ i, x i + 1 := by
    rw [sum_update_of_mem (mem_univ c), sdiff_singleton_eq_erase, ← add_sum_erase _ _ (mem_univ c)]
    ring
  have hprod : ∏ i, (ascPochhammer ℝ (Function.update x c (x c + 1) i)).eval (θ i) =
      (∏ i, (ascPochhammer ℝ (x i)).eval (θ i)) * (θ c + x c) := by
    rw [← mul_prod_erase univ _ (mem_univ c), ← mul_prod_erase univ
        (fun i ↦ (ascPochhammer ℝ (x i)).eval (θ i)) (mem_univ c), Function.update_self,
      ascPochhammer_succ_eval, prod_congr rfl fun i hi ↦ by
        rw [Function.update_of_ne (ne_of_mem_erase hi)]]
    ring
  rw [polyaUrnProb, polyaUrnProb, polyaUrnPredictive, hsum, hprod, ascPochhammer_succ_eval,
    div_mul_div_comm, Nat.cast_sum]

/-- Appending colour `c` to a sequence multiplies its probability by the probability of drawing
`c`. -/
theorem polyaUrnProb_countVec_snoc [DecidableEq α] (c : α) {n : ℕ} (s : Fin n → α) :
    polyaUrnProb θ (countVec (Fin.snoc s c : Fin (n + 1) → α)) =
      polyaUrnProb θ (countVec s) * polyaUrnPredictive θ (countVec s) c := by
  rw [countVec_snoc, polyaUrnProb_update_succ]

/-- Prepending colour `c` to a sequence multiplies its probability by the probability of drawing
`c` first given the rest; the counts do not see the order. -/
theorem polyaUrnProb_countVec_cons [DecidableEq α] (c : α) {n : ℕ} (s : Fin n → α) :
    polyaUrnProb θ (countVec (Fin.cons c s : Fin (n + 1) → α)) =
      polyaUrnProb θ (countVec s) * polyaUrnPredictive θ (countVec s) c := by
  rw [countVec_cons, polyaUrnProb_update_succ]

/-- **Conjugacy.** The probability of counts `x + y` is the probability of `x` times the
probability of `y` under the urn whose weights are raised by `x`. -/
theorem polyaUrnProb_add (x y : α → ℕ) :
    polyaUrnProb θ (x + y) = polyaUrnProb θ x * polyaUrnProb (θ + fun c ↦ (x c : ℝ)) y := by
  have hasc (a : ℝ) (m k : ℕ) : (ascPochhammer ℝ (m + k)).eval a =
      (ascPochhammer ℝ m).eval a * (ascPochhammer ℝ k).eval (a + m) := by
    rw [← ascPochhammer_mul, Polynomial.eval_mul, Polynomial.eval_comp, Polynomial.eval_add,
      Polynomial.eval_X, Polynomial.eval_natCast]
  simp only [polyaUrnProb, Pi.add_apply, sum_add_distrib, hasc, prod_mul_distrib, Nat.cast_sum]
  rw [div_mul_div_comm]

variable {θ}

theorem polyaUrnPredictive_nonneg (hθ : ∀ i, 0 ≤ θ i) (x : α → ℕ) (c : α) :
    0 ≤ polyaUrnPredictive θ x c :=
  div_nonneg (add_nonneg (hθ c) (Nat.cast_nonneg _))
    (add_nonneg (sum_nonneg fun i _ ↦ hθ i) (sum_nonneg fun _ _ ↦ Nat.cast_nonneg _))

/-- The prediction rule is a probability on the colours. -/
theorem sum_polyaUrnPredictive [Nonempty α] (hθ : ∀ i, 0 < θ i) (x : α → ℕ) :
    ∑ c, polyaUrnPredictive θ x c = 1 := by
  have h : 0 < ∑ i, θ i + ∑ i, (x i : ℝ) :=
    add_pos_of_pos_of_nonneg (sum_pos (fun i _ ↦ hθ i) univ_nonempty)
      (sum_nonneg fun _ _ ↦ Nat.cast_nonneg _)
  simp only [polyaUrnPredictive, ← sum_div, sum_add_distrib]
  exact div_self h.ne'

theorem polyaUrnProb_pos [Nonempty α] (hθ : ∀ i, 0 < θ i) (x : α → ℕ) : 0 < polyaUrnProb θ x :=
  div_pos (prod_pos fun i _ ↦ ascPochhammer_pos _ _ (hθ i))
    (ascPochhammer_pos _ _ (sum_pos (fun i _ ↦ hθ i) univ_nonempty))

end ProbabilityTheory
