import Linglib.Core.Mereology

/-!
# Link 1983: The Logical Analysis of Plurals and Mass Terms

@cite{link-1983}

Link introduces a model structure 𝔅 = ⟨E, A, D, h⟩ for the ontology
of plurals and mass terms:

- E is a complete atomic Boolean algebra of individuals (join ⊔ᵢ, ordering ≤ᵢ)
- A ⊆ E are atoms — singular objects (this card, that ring)
- D is a join-semilattice of portions of matter
- h : E\{0} → D is a semilattice homomorphism (materialization)

The two-level structure (E vs D, connected by h) is Link's key innovation.
It separates *individual part* (Π, the lattice ordering on E) from
*material part* (⊤, induced by h). "The cards" and "the deck of cards"
may be made of the same matter (h-equivalent) while being distinct
individuals in E.

## Operators

| Link | Definition | Linglib |
|---|---|---|
| `*P` | Closure of P under ⊔ᵢ | `Mereology.AlgClosure` |
| `⊕P` | `*P ∧ ¬At` (proper plural) | `properPlural` |
| `Distr(P)` | `∀x. Px → At x` | `Distr` |
| `Inv(P)` | Closed under m-equivalent substitution | `Inv` |
| `a Π b` | `a ≤ᵢ b` (individual part) | `≤` |
| `a ⊤ b` | `h(a) ≤ h(b)` (material part) | `mPart` |
| `a ~ b` | `h(a) = h(b)` (material equivalence) | `mEquiv` |

## Connection to Existing Infrastructure

Link's `*` IS `Mereology.AlgClosure`. Link's cumulative reference
IS `Mereology.CUM`. Link's atom IS `Mereology.Atom`. This file
makes the connection explicit by stating Link's theorems in terms
of the existing `Core/Mereology.lean` definitions, correcting
attributions that had previously cited only @cite{champollion-2017}.
-/

namespace Semantics.Plurality.Link1983

open Mereology

-- ════════════════════════════════════════════════════
-- § 1. Link's Predicate Operators
-- ════════════════════════════════════════════════════

variable {E : Type*} [SemilatticeSup E]

/-- `*P`: Link's star operator — plural closure under join.
    `‖*P‖` is the complete ⊔ᵢ-subsemilattice generated by `‖P‖`.
    This IS `Mereology.AlgClosure`. -/
abbrev star (P : E → Prop) : E → Prop := AlgClosure P

/-- `⊕P`: the proper plural predicate (D.12).
    `⊕Pa ↔ *Pa ∧ ¬At a`.
    If P = child', then ⊕P = children': non-atomic sums of
    child-individuals. -/
def properPlural (P : E → Prop) (x : E) : Prop :=
  AlgClosure P x ∧ ¬Atom x

/-- `Distr(P)`: P is a distributive predicate (D.19).
    Distributive predicates are true of atoms only.
    Common nouns like "child" and intransitive verbs like "die"
    are distributive. Collective predicates like "gather" are not. -/
def Distr (P : E → Prop) : Prop :=
  ∀ x, P x → Atom x

/-- `Inv(P)`: P is an invariant predicate (D.21).
    Invariant predicates are closed under substitution of
    materially equivalent individuals. Spatio-temporal predicates
    like "be-on-the-table" are invariant: "the cards are on
    the table" iff "the deck of cards is on the table." -/
def Inv {D : Type*} [Preorder D] (h : E → D) (P : E → Prop) : Prop :=
  ∀ x y, h x = h y → (P x ↔ P y)

-- ════════════════════════════════════════════════════
-- § 2. The Constitution Relation
-- ════════════════════════════════════════════════════

section Constitution

variable {D : Type*} [SemilatticeSup D]

/-- Link's materialization: a semilattice homomorphism h : E → D
    mapping individuals to their material constitution (D.22).
    h commutes with join: h(x ⊔ y) = h(x) ⊔ h(y). -/
structure Materialization (E D : Type*)
    [SemilatticeSup E] [SemilatticeSup D] where
  /-- The materialization function. -/
  h : E → D
  /-- h preserves join. -/
  h_hom : IsSumHom h

/-- Material part (m-part) relation (D.23): `x ≤ₘ y ↔ h(x) ≤ h(y)`.
    "The portion of matter constituting x is part of the portion
    constituting y." Coarser than individual part (≤ᵢ). -/
def mPart (mat : Materialization E D) (x y : E) : Prop :=
  mat.h x ≤ mat.h y

/-- Material equivalence (D.24): `x ~ y ↔ h(x) = h(y)`.
    "x and y are made of the same stuff." -/
def mEquiv (mat : Materialization E D) (x y : E) : Prop :=
  mat.h x = mat.h y

/-- T.2: Individual part implies material part.
    `a Π b → a ⊤ b`. Follows from monotonicity of h. -/
theorem iPart_implies_mPart (mat : Materialization E D) {x y : E}
    (h : x ≤ y) : mPart mat x y :=
  mat.h_hom.monotone h

/-- T.4 (partial): Material equivalence is an equivalence relation. -/
theorem mEquiv_equivalence (mat : Materialization E D) :
    Equivalence (mEquiv mat) where
  refl _ := rfl
  symm := Eq.symm
  trans := Eq.trans

/-- Material equivalence ↔ mutual material part. -/
theorem mEquiv_iff_mPart_both (mat : Materialization E D) {x y : E} :
    mEquiv mat x y ↔ mPart mat x y ∧ mPart mat y x :=
  ⟨fun h => ⟨le_of_eq h, le_of_eq h.symm⟩,
   fun ⟨h1, h2⟩ => le_antisymm h1 h2⟩

/-- Invariant predicates respect material equivalence by definition. -/
theorem inv_mEquiv {mat : Materialization E D} {P : E → Prop}
    (hInv : Inv mat.h P) {x y : E} (hEq : mEquiv mat x y) :
    P x ↔ P y :=
  hInv x y hEq

end Constitution

-- ════════════════════════════════════════════════════
-- § 3. Link's Theorems
-- ════════════════════════════════════════════════════

section Theorems

variable {E : Type*} [SemilatticeSup E]

/-- T.7: `P ⊆ *P` — every predicate is contained in its plural closure. -/
theorem T7_star_extends {P : E → Prop} {x : E} (h : P x) :
    star P x :=
  subset_algClosure h

/-- T.11: `CUM(*P)` — *P is always cumulative.
    If `*P(x)` and `*P(y)` then `*P(x ⊔ y)`. This is the formal
    content of Link's "homogeneous reference" property. -/
theorem T11_star_cum {P : E → Prop} : CUM (star P) :=
  algClosure_cum

/-- T.8 (backward): For atoms, `*P` implies `P`.
    An atom cannot arise as a proper join (since `a ≤ a ⊔ b`
    forces `a = a ⊔ b` for atoms), so the only way
    `AlgClosure P x` can hold for an atom is via the base case. -/
theorem T8_atom_of_star {P : E → Prop} :
    ∀ {x : E}, Atom x → AlgClosure P x → P x := by
  intro x hAtom hStar
  induction hStar with
  | base hp => exact hp
  | @sum a b _ _ iha _ =>
    have heq : a = a ⊔ b := hAtom a le_sup_left
    have hAtom_a : Atom a :=
      fun y hy => (hAtom y (le_trans hy le_sup_left)).trans heq.symm
    have h := iha hAtom_a
    rw [show a ⊔ b = a from heq.symm]
    exact h

/-- T.8: `At x → (Px ↔ *Px)` — for atoms, P and *P coincide. -/
theorem T8_atom_star_iff {P : E → Prop} {x : E} (hAtom : Atom x) :
    P x ↔ star P x :=
  ⟨subset_algClosure, T8_atom_of_star hAtom⟩

/-- T.9 (partial): every element of `*P` has a P-individual as a part.
    Every plural individual contains at least one base individual. -/
theorem T9_star_has_base_part {P : E → Prop} {x : E}
    (hStar : star P x) : ∃ y, P y ∧ y ≤ x := by
  induction hStar with
  | base hp => exact ⟨_, hp, le_refl _⟩
  | sum _ _ iha _ =>
    obtain ⟨y, hy, hle⟩ := iha
    exact ⟨y, hy, le_trans hle le_sup_left⟩

/-- T.6: Distributive predicates and proper plurals are disjoint.
    If P is distributive (true of atoms only), then no P-individual
    is a proper plural (non-atomic). -/
theorem T6_distr_disjoint_properPlural {P : E → Prop}
    (hDistr : Distr P) {x : E} (hPx : P x) :
    ¬properPlural P x :=
  fun ⟨_, hNotAtom⟩ => hNotAtom (hDistr x hPx)

/-- Contrapositive of T.6: proper plurals of distributive predicates
    are NOT in P itself. -/
theorem properPlural_not_base {P : E → Prop}
    (hDistr : Distr P) {x : E} (hPP : properPlural P x) :
    ¬P x :=
  fun hPx => T6_distr_disjoint_properPlural hDistr hPx hPP

end Theorems

-- ════════════════════════════════════════════════════
-- § 4. Distributive Inference (join-prime atoms)
-- ════════════════════════════════════════════════════

section DistributiveInference

variable {E : Type*} [SemilatticeSup E]

/-- Atoms are join-prime: if an atom is below a join, it is below
    one of the joinands. This holds in Boolean algebras and
    distributive lattices. Link assumes E is a complete atomic
    Boolean algebra (D.22), so this is always available. -/
def AtomJoinPrime (E : Type*) [SemilatticeSup E] : Prop :=
  ∀ (a : E), Atom a → ∀ (x y : E), a ≤ x ⊔ y → a ≤ x ∨ a ≤ y

/-- Link's distributive inference:
    If P is distributive and `*P(x)`, then every atom below x
    satisfies P.

    "John, Paul, George, and Ringo are pop stars" → `*popStar(j⊕p⊕g⊕r)`
    "Paul is a pop star" → `popStar(p)`

    Requires atoms to be join-prime (holds in Link's Boolean algebra). -/
theorem distr_atom_part {P : E → Prop} (hDistr : Distr P)
    (hJP : AtomJoinPrime E) :
    ∀ {x : E}, star P x → ∀ {y : E}, Atom y → y ≤ x → P y := by
  intro x hStar
  induction hStar with
  | base hp =>
    intro z hz hle
    have heq : z = _ := (hDistr _ hp) z hle
    rwa [heq]
  | @sum a b _ _ iha ihb =>
    intro z hz hle
    rcases hJP z hz a b hle with h | h
    · exact iha hz h
    · exact ihb hz h

end DistributiveInference

-- ════════════════════════════════════════════════════
-- § 5. Predicate Classification
-- ════════════════════════════════════════════════════

section Classification

variable {E : Type*} [SemilatticeSup E]

/-- If P is distributive, then ⊕P extends P with genuinely new
    entities: the join of two distinct P-atoms is a proper plural. -/
theorem distr_properPlural_extends {P : E → Prop}
    (_hDistr : Distr P) {x y : E}
    (hx : P x) (hy : P y) (hne : x ≠ y) :
    properPlural P (x ⊔ y) :=
  ⟨AlgClosure.sum (AlgClosure.base hx) (AlgClosure.base hy),
   fun hAtom => hne
     ((hAtom x le_sup_left).trans (hAtom y le_sup_right).symm)⟩

/-- CUM for the proper plural ⊕P: sums of proper plurals are
    proper plurals. -/
theorem properPlural_cum {P : E → Prop} {x y : E}
    (hx : properPlural P x) (hy : properPlural P y) :
    properPlural P (x ⊔ y) := by
  refine ⟨algClosure_cum _ _ hx.1 hy.1, fun hAtom => ?_⟩
  have : x = x ⊔ y := hAtom x le_sup_left
  exact hx.2 (fun z hz => by rw [show x ⊔ y = x from this.symm] at hAtom; exact hAtom z hz)

end Classification

-- ════════════════════════════════════════════════════
-- § 6. Connection to Finset-Based Distributivity
-- ════════════════════════════════════════════════════

/-! Link's `Distr(P)` — P applies to atoms only — is the mereological
    foundation for `distMaximal` in `Distributivity.lean`. The Finset-based
    operator `distMaximal P x w = ∀a ∈ x. P(a)(w)` corresponds to
    Link's distributive inference (`distr_atom_part`): if P is distributive,
    distributing to every atom-part and checking each is correct.

    The connection is structural: Link works with a lattice E and atoms,
    while `distMaximal` works with `Finset Atom`. The correspondence is:
    - Link's atoms A ⊆ E = the type `Atom` in `Distributivity.lean`
    - Link's ≤ᵢ (individual part) = Finset membership `a ∈ x`
    - Link's `*P(x)` (plural closure) = "the members of x all satisfy P"
    - `Distr(P) ∧ *P(x)` → `∀a atom-part-of x. P(a)` = `distMaximal P x w` -/

/-- Link's `distr_atom_part` is the mereological justification for
    `Distributivity.distMaximal`. In the Finset-based setting:

    - A `Finset Atom` corresponds to a plurality `x ∈ E`
    - Each element `a ∈ x` corresponds to an atom `a ≤ᵢ x`
    - `distMaximal P x w = ∀a ∈ x. P(a)(w)` checks every atom

    For distributive predicates (`Distr P`), `distr_atom_part` proves
    this is correct: `*P(x)` holds iff every atom-part of x satisfies P.
    For collective predicates (¬Distr P), `distMaximal` would be
    too strong — the predicate may hold of the plurality without
    holding of each atom (e.g., "gathered", "surrounded").

    The key correspondence:
    - `distr_atom_part` (lattice) ≅ `distMaximal_forces_all` (Finset)
    - `T8_atom_star_iff` (lattice) ≅ `distMaximal_singleton` (Finset) -/
theorem distr_star_iff_all_atoms {P : E → Prop} (hDistr : Distr P)
    (hJP : AtomJoinPrime E) {x : E} :
    star P x → ∀ {y : E}, Atom y → y ≤ x → P y :=
  distr_atom_part hDistr hJP

end Semantics.Plurality.Link1983
