import Mathlib.Data.Setoid.Partition
import Linglib.Semantics.Questions.Hamblin
import Linglib.Semantics.Questions.Entailment
import Linglib.Semantics.Questions.Partition.QUD
import Linglib.Semantics.Questions.Partition.Lattice

/-!
# Partition questions

The correspondence between partition-style inquiry
([groenendijk-stokhof-1984]'s question semantics, a `Setoid W`) and
the more general inquisitive content `Question W`
([ciardelli-groenendijk-roelofsen-2018]). The embedding is one-way:
every partition is an issue whose alternatives are its cells, but
mention-some, intermediate-exhaustive, and conditional-question
alternative sets are non-disjoint or non-exhaustive and are not the
classes of any equivalence relation.

## Main definitions

- `fromSetoid r` — the issue whose alternatives are the cells of `r`.
- `fromSetoidEmbedding` — `fromSetoid` bundled as an order embedding
  `Setoid W ↪o Question W`.
- `IsPartition P` — `Setoid.IsPartition (alt P)`.
- `toSetoid h` — the equivalence relation of a partition issue.
- `QUD.toQuestion q` — the issue whose alternatives are a QUD's cells.

## Main theorems

- `fromSetoid_eq_iSup_ofSet_classes` — a partition issue is the Hamblin
  disjunction of the declaratives generated by its cells.
- `fromSetoid_le_iff` — partition refinement is issue entailment.
- `alt_fromSetoid`, `info_fromSetoid` — the alternatives are the cells;
  partition issues are non-informative.
- `isPartition_polar`, `isPartition_ofList` — the basic Hamblin
  constructions yield partition issues under nontriviality /
  disjointness / cover hypotheses.
- `toSetoid_fromSetoid`, `fromSetoid_toSetoid` — the two round-trip
  directions of the partition–setoid correspondence.
-/


namespace Question

variable {W : Type*}

/-! ### The `Setoid → Question` embedding -/

/-- The issue raised by a setoid `r`: a state `q` resolves it iff `q`
is empty or contained in an `r`-equivalence class. -/
def fromSetoid (r : Setoid W) : Question W :=
  ofLowerSet {q | q = ∅ ∨ ∃ c ∈ r.classes, q ⊆ c} (Or.inl rfl) <| by
    rintro a b hba (rfl | ⟨c, hc, hac⟩)
    · exact Or.inl (Set.subset_empty_iff.mp hba)
    · exact Or.inr ⟨c, hc, hba.trans hac⟩

/-- A partition issue is the Hamblin disjunction of the declaratives
generated by its cells — the `fromSetoid` instance of the shape the
Resolutions Theorem (`eq_iSup_ofSet_alt`) establishes in general. -/
theorem fromSetoid_eq_iSup_ofSet_classes (r : Setoid W) :
    fromSetoid r = ⨆ c ∈ r.classes, ofSet c := by
  ext q; rw [mem_biSup_iff]; rfl

/-- Partition-derived issues are non-informative: they raise an issue
but supply no information. -/
theorem info_fromSetoid (r : Setoid W) : (fromSetoid r).info = Set.univ :=
  Set.eq_univ_of_forall fun w =>
    ⟨_, Or.inr ⟨_, r.mem_classes w, subset_rfl⟩, r.refl' w⟩

/-! ### Alternatives of `fromSetoid` -/

/-- Each cell of `r` is an alternative of `fromSetoid r`. -/
theorem mem_alt_fromSetoid_of_mem_classes (r : Setoid W) {c : Set W}
    (hc : c ∈ r.classes) : c ∈ alt (fromSetoid r) := by
  obtain ⟨v, rfl⟩ := hc
  refine ⟨Or.inr ⟨_, r.mem_classes v, subset_rfl⟩, ?_⟩
  rintro q (rfl | ⟨c', ⟨v', rfl⟩, hqc'⟩) hcq
  · exact absurd (hcq (r.refl' v)) (Set.notMem_empty v)
  · exact hcq.antisymm fun x hx =>
      r.trans' (hqc' hx) (r.symm' (hqc' (hcq (r.refl' v))))

/-- Every alternative of `fromSetoid r` is the empty state or a cell of
`r` (the empty case only when `W` is empty). -/
theorem eq_empty_or_mem_classes_of_mem_alt_fromSetoid (r : Setoid W)
    {p : Set W} (hp : p ∈ alt (fromSetoid r)) : p = ∅ ∨ p ∈ r.classes := by
  obtain ⟨rfl | ⟨c, hc, hpc⟩, hmax⟩ := hp
  · exact Or.inl rfl
  · exact Or.inr (hmax c (Or.inr ⟨c, hc, subset_rfl⟩) hpc ▸ hc)

/-- The alternatives of `fromSetoid r` are exactly the cells of `r`.
Nonemptiness rules out the degenerate `∅`-alternative that appears
when `W` is empty. -/
@[simp] theorem alt_fromSetoid [Nonempty W] (r : Setoid W) :
    alt (fromSetoid r) = r.classes := by
  refine Set.Subset.antisymm (fun p hp => ?_)
    fun c => mem_alt_fromSetoid_of_mem_classes r
  rcases eq_empty_or_mem_classes_of_mem_alt_fromSetoid r hp with rfl | hclass
  · obtain ⟨w⟩ := ‹Nonempty W›
    have heq := hp.2 _ (Or.inr ⟨_, r.mem_classes w, subset_rfl⟩) (Set.empty_subset _)
    exact ((Set.notMem_empty w) (heq ▸ r.refl' w)).elim
  · exact hclass

/-- A setoid with two distinct cells yields an inquisitive content. -/
theorem isInquisitive_fromSetoid_of_two_classes
    (r : Setoid W) (w₁ w₂ : W) (hne : ¬ r w₁ w₂) :
    (fromSetoid r).isInquisitive :=
  isInquisitive_of_two_alternatives _
    (mem_alt_fromSetoid_of_mem_classes r (r.mem_classes w₁))
    (mem_alt_fromSetoid_of_mem_classes r (r.mem_classes w₂))
    fun h => hne ((Set.ext_iff.mp h w₁).mp (r.refl' w₁))

/-! ### Refinement is entailment -/

/-- The embedding reflects the order: a setoid is finer than another
iff its issue entails the other's — Groenendijk–Stokhof's "partition
refinement is question entailment". -/
theorem fromSetoid_le_iff (r₁ r₂ : Setoid W) :
    fromSetoid r₁ ≤ fromSetoid r₂ ↔ r₁ ≤ r₂ := by
  constructor
  -- the doubleton {x, y} resolves fromSetoid r₁, hence fromSetoid r₂
  · intro hle x y hxy
    have hpair : ({x, y} : Set W) ∈ fromSetoid r₁ :=
      Or.inr ⟨_, r₁.mem_classes y,
        Set.insert_subset_iff.mpr ⟨hxy, Set.singleton_subset_iff.mpr (r₁.refl' y)⟩⟩
    rcases hle hpair with hempty | ⟨c, hc, hsub⟩
    · exact absurd (hempty ▸ Set.mem_insert x {y}) (Set.notMem_empty x)
    · exact r₂.rel_iff_exists_classes.mpr
        ⟨c, hc, hsub (Set.mem_insert x _), hsub (Set.mem_insert_of_mem x rfl)⟩
  -- a state in an r₁-cell is in the surrounding r₂-cell
  · rintro hle q (rfl | ⟨c, ⟨v, rfl⟩, hqc⟩)
    · exact (fromSetoid r₂).contains_empty
    · exact Or.inr ⟨_, r₂.mem_classes v, fun z hz => hle (hqc hz)⟩

/-- `fromSetoid` as an order embedding: the Groenendijk–Stokhof
partition order sits order-faithfully inside the inquisitive algebra.
Companion of `ofSetEmbedding`, which embeds the declaratives. -/
def fromSetoidEmbedding : Setoid W ↪o Question W :=
  OrderEmbedding.ofMapLEIff fromSetoid fromSetoid_le_iff

/-- Monotonicity of the embedding. -/
theorem fromSetoid_mono {r₁ r₂ : Setoid W} (h : r₁ ≤ r₂) :
    fromSetoid r₁ ≤ fromSetoid r₂ :=
  (fromSetoid_le_iff r₁ r₂).mpr h

/-- Under finiteness, question entailment between partition issues is
the `Setoid` refinement order: the `Question`-level and `Setoid`-level
encodings of refinement coincide. -/
theorem fromSetoid_entails_iff [Finite W] (r₁ r₂ : Setoid W) :
    (fromSetoid r₁).Entails (fromSetoid r₂) ↔ r₁ ≤ r₂ := by
  rw [entails_iff_le (Set.toFinite _) (Set.toFinite _), fromSetoid_le_iff]

/-! ### `IsPartition` predicate -/

/-- An issue is a **partition** iff its alternative set is a partition
of `W` in mathlib's `Setoid.IsPartition` sense: no empty alternative,
and every world lies in a unique alternative. The Groenendijk–Stokhof
partition shape. -/
def IsPartition (P : Question W) : Prop :=
  Setoid.IsPartition (alt P)

namespace IsPartition

/-- Alternatives of a partition issue are pairwise disjoint. -/
theorem pairwiseDisjoint {P : Question W} (h : P.IsPartition) :
    (alt P).PairwiseDisjoint id :=
  Setoid.IsPartition.pairwiseDisjoint h

/-- Alternatives of a partition issue are nonempty. -/
theorem nonempty_of_mem_alt {P : Question W} (h : P.IsPartition)
    {p : Set W} (hp : p ∈ alt P) : p.Nonempty :=
  Setoid.nonempty_of_mem_partition h hp

/-- The union of a partition issue's alternatives is the whole universe. -/
theorem sUnion_alt_eq_univ {P : Question W} (h : P.IsPartition) :
    ⋃₀ alt P = Set.univ :=
  Setoid.IsPartition.sUnion_eq_univ h

/-- Partition issues are non-informative: every world lies in some
alternative, hence in some resolving proposition. -/
theorem info_eq_univ {P : Question W} (h : P.IsPartition) :
    info P = Set.univ :=
  Set.eq_univ_of_univ_subset (h.sUnion_alt_eq_univ ▸ sUnion_alt_subset_info P)

end IsPartition

/-! ### `toSetoid` — equivalence relation from a partition issue -/

/-- The setoid derived from a partition issue: two worlds are
equivalent iff they lie in the same alternative cell. Built from
mathlib's `Setoid.mkClasses` on the alternative set. -/
def toSetoid {P : Question W} (h : P.IsPartition) : Setoid W :=
  Setoid.mkClasses (alt P) h.2

/-- The equivalence classes of `toSetoid h` are exactly the
alternatives of `P` — the defining round-trip property of
`Setoid.mkClasses`. -/
@[simp] theorem classes_toSetoid {P : Question W} (h : P.IsPartition) :
    (toSetoid h).classes = alt P :=
  Setoid.classes_mkClasses (alt P) h

/-- Two worlds are related under `toSetoid h` iff they share an
alternative cell. -/
theorem toSetoid_rel_iff {P : Question W} (h : P.IsPartition) (w v : W) :
    (toSetoid h) w v ↔ ∃ p ∈ alt P, w ∈ p ∧ v ∈ p := by
  rw [Setoid.rel_iff_exists_classes, classes_toSetoid h]

/-! ### Bridge to the Bool-based `QUD` -/

/-- The issue raised by a `QUD`: its alternatives are exactly the QUD's
equivalence classes. The bridge is one-way: not every `Question`
arises from a `QUD` (mention-some, intermediate-exhaustive, and
conditional-question alternatives are non-disjoint or non-exhaustive
and so are not the cells of any equivalence relation —
[theiler-etal-2018]). -/
def _root_.QUD.toQuestion (q : QUD W) : Question W :=
  fromSetoid q.toSetoid

/-- `QUD` refinement is question entailment of the induced partition
issues: the Bool-layer `⊑` agrees with the `Question`-layer entailment
order. -/
theorem _root_.QUD.refines_iff_toQuestion_entails {M : Type*} [Finite M]
    (q q' : QUD M) :
    q.refines q' ↔ q.toQuestion.Entails q'.toQuestion := by
  rw [QUD.refines_iff_toSetoid_le, ← fromSetoid_entails_iff]; rfl

/-! ### Round-trips with `fromSetoid`

`fromSetoid` and `toSetoid` compose to the identity in both
directions: on setoids whenever `W` is inhabited, and on partition
issues whenever every resolving state extends to an alternative. The
latter hypothesis is essential: over infinite `W` a partition issue
may contain resolving states that extend to no alternative. -/

/-- Under `Nonempty W`, `fromSetoid r` is a partition issue. -/
theorem isPartition_fromSetoid [Nonempty W] (r : Setoid W) :
    (fromSetoid r).IsPartition := by
  rw [IsPartition, alt_fromSetoid]; exact r.isPartition_classes

/-- **Round-trip**, `Setoid → Question → Setoid`: the setoid derived
from the partition issue of `r` is `r` itself. -/
theorem toSetoid_fromSetoid [Nonempty W] (r : Setoid W) :
    toSetoid (isPartition_fromSetoid r) = r :=
  Setoid.classes_inj.mpr (by rw [classes_toSetoid, alt_fromSetoid])

/-- **Round-trip**, `Question → Setoid → Question`: a partition issue
whose resolving states all extend to alternatives is recovered from
its setoid. The extension hypothesis is discharged by
`exists_alt_above` when `P.props` is finite. -/
theorem fromSetoid_toSetoid {P : Question W} (h : P.IsPartition)
    (hExt : ∀ p ∈ P.props, ∃ q ∈ alt P, p ⊆ q) :
    fromSetoid (toSetoid h) = P := by
  rw [fromSetoid_eq_iSup_ofSet_classes, classes_toSetoid]
  exact (eq_iSup_ofSet_alt_of_exists_alt P hExt).symm

/-! ### `IsPartition` for the basic Hamblin constructions -/

/-- `polar p` is a partition issue when `p` is non-trivial: the two
alternatives `p` and `pᶜ` partition `W` by excluded middle. -/
theorem isPartition_polar {p : Set W} (hne : p ≠ ∅) (hnu : p ≠ Set.univ) :
    (polar p).IsPartition := by
  rw [IsPartition, alt_polar_of_nontrivial hne hnu]
  refine Set.PairwiseDisjoint.isPartition_of_exists_of_ne_empty ?_ (fun w => ?_) ?_
  · rintro s (rfl | rfl) t (rfl | rfl) hst
    exacts [absurd rfl hst, disjoint_compl_right, disjoint_compl_left, absurd rfl hst]
  · exact (Classical.em (w ∈ p)).elim (⟨p, Set.mem_insert _ _, ·⟩)
      (⟨pᶜ, Set.mem_insert_of_mem _ rfl, ·⟩)
  · rintro (h | h)
    · exact hne h.symm
    · exact hnu (Set.compl_empty_iff.mp h.symm)

/-- `ofList L` is a partition issue when `L` is a nonempty list of
pairwise-disjoint nonempty cells that exhaust `W`. -/
theorem isPartition_ofList {L : List (Set W)} (hL : L ≠ [])
    (hdisj : ∀ p₁ ∈ L, ∀ p₂ ∈ L, p₁ ≠ p₂ → Disjoint p₁ p₂)
    (hne : ∀ p ∈ L, p ≠ ∅)
    (hcover : ∀ w : W, ∃ p ∈ L, w ∈ p) :
    (ofList L).IsPartition := by
  rw [IsPartition, alt_ofList_of_pairwise_disjoint_nonempty L hL hdisj hne]
  exact Set.PairwiseDisjoint.isPartition_of_exists_of_ne_empty
    (fun p₁ h₁ p₂ h₂ h₁₂ => hdisj p₁ h₁ p₂ h₂ h₁₂) hcover fun h => hne ∅ h rfl

end Question
