/-
Copyright (c) 2026 Robert Hawkins. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Robert Hawkins
-/
module

public import Mathlib.Algebra.BigOperators.Fin
public import Mathlib.Algebra.Group.Action.Defs
public import Mathlib.Data.Finset.Max
public import Mathlib.Data.Fintype.Pi
public import Mathlib.Data.Fintype.Sum
public import Mathlib.GroupTheory.Perm.Basic
public import Mathlib.Order.Partition.Finpartition

/-!
# Partitions generated by functions and by families

The partition of a finite type generated by a function `s : ι → β` has the fibres of `s` as its
blocks, `i` and `j` sharing a block when `s i = s j`; every partition of `ι` is generated by the
function sending each element to its block (`ofFun_part`). A finite family `φ : ι → α` in a
Boolean algebra generates a partition of `⊤` whose parts are its nonzero minterms, the meets
`±φ i` over all `i`; for a family of finsets these are the fibres of the membership function.
Permutations of `ι` act on its partitions by relabelling, and the multiset of block sizes is
invariant. A partition of `Fin n`
is also generated by labelling each element with the least element of its block
(`ofFun_minLabel`), and the label sequences arising this way are those built by appending at
each step an earlier label or the next index: the tables of the Chinese restaurant process
labelled by their first customer.

## Main definitions

* `Finpartition.ofFun s`: the partition of `ι` generated by `s`.
* `minterm φ σ`: the meet of `φ i` for the `i` with `σ i` true and of `(φ i)ᶜ` for the others.
* `Finpartition.minterms φ`: the partition of `⊤` into the nonzero minterms of `φ`.
* `Finpartition.partSizes P`: the multiset of the sizes of the blocks.
* The action of `Equiv.Perm ι` on `Finpartition (univ : Finset ι)`.
* `Finpartition.minLabel P`: the labelling of a partition of `Fin n` by the least element of
  each block.

## Main results

* `Finpartition.ofFun_congr`: the partition depends only on which values coincide.
* `disjoint_minterm`, `sup_minterm`: distinct minterms are disjoint and the minterms join to `⊤`.
* `Finpartition.minterms_sumElim`: the minterms of a union of two families are the meet of the
  two partitions.
* `Finpartition.parts_minterms_eq_parts_ofFun`: the minterms of a family of finsets are the fibres
  of membership.
* `Finpartition.ofFun_part`, `Finpartition.ofFun_minLabel`: every partition is generated by its
  blocks, and by its least-element labelling.
* `Finpartition.partSizes_ofFun`: the block sizes are the multiplicities of the values.
* `Finpartition.ofFun_comp_perm`, `Finpartition.partSizes_smul`: precomposing with a permutation
  relabels the partition, which keeps its block sizes.
* `Finpartition.minLabel_ofFun_snoc`, `Finpartition.minLabel_ofFun_of_snoc`: a sequence of
  least-element labels extends by exactly an earlier label or the next index.

[UPSTREAM] candidates for `Mathlib.Order.Partition.Finpartition`.
-/

@[expose] public section

open Finset

/-! ### Minterms -/

section Minterm

variable {α ι κ : Type*} [BooleanAlgebra α] [Fintype ι] [Fintype κ]

/-- The minterm of `φ` at `σ` is the meet of `φ i` for the `i` with `σ i` true and of `(φ i)ᶜ`
for the others. -/
def minterm (φ : ι → α) (σ : ι → Bool) : α :=
  univ.inf fun i ↦ if σ i then φ i else (φ i)ᶜ

variable {φ : ι → α} {σ τ : ι → Bool} {i : ι}

theorem minterm_le_of_true (h : σ i = true) : minterm φ σ ≤ φ i :=
  (inf_le (f := fun i ↦ if σ i then φ i else (φ i)ᶜ) (mem_univ i)).trans_eq (by simp [h])

theorem minterm_le_compl_of_false (h : σ i = false) : minterm φ σ ≤ (φ i)ᶜ :=
  (inf_le (f := fun i ↦ if σ i then φ i else (φ i)ᶜ) (mem_univ i)).trans_eq (by simp [h])

theorem disjoint_minterm (h : σ ≠ τ) : Disjoint (minterm φ σ) (minterm φ τ) := by
  obtain ⟨i, hi⟩ := Function.ne_iff.mp h
  cases hσ : σ i
  · have hτ : τ i = true := by simpa [hσ] using hi.symm
    exact (disjoint_compl_left.mono_left (minterm_le_compl_of_false hσ)).mono_right
      (minterm_le_of_true hτ)
  · have hτ : τ i = false := by simpa [hσ] using hi.symm
    exact (disjoint_compl_right.mono_left (minterm_le_of_true hσ)).mono_right
      (minterm_le_compl_of_false hτ)

theorem minterm_sumElim (φ : ι → α) (ψ : κ → α) (σ : ι ⊕ κ → Bool) :
    minterm (Sum.elim φ ψ) σ = minterm φ (σ ∘ .inl) ⊓ minterm ψ (σ ∘ .inr) := by
  simp only [minterm, ← univ_disjSum_univ, inf_disjSum]
  rfl

theorem minterm_comp_equiv (e : κ ≃ ι) (φ : ι → α) (σ : κ → Bool) :
    minterm (φ ∘ e) σ = minterm φ (σ ∘ e.symm) := by
  rw [minterm, minterm, ← univ_map_equiv_to_embedding e, inf_map]
  congr 1
  funext k
  simp

theorem mem_minterm {γ : Type*} [Fintype γ] [DecidableEq γ] {φ : ι → Finset γ} {x : γ} :
    x ∈ minterm φ σ ↔ ∀ i, x ∈ φ i ↔ σ i = true := by
  rw [← singleton_subset_iff, minterm, Finset.le_inf_iff]
  refine forall_congr' fun i ↦ ?_
  cases σ i <;> simp

variable [DecidableEq ι]

variable (φ) in
/-- The minterms of a family join to `⊤`. -/
theorem sup_minterm : univ.sup (minterm φ) = ⊤ := by
  suffices ∀ s : Finset ι,
      univ.sup (fun σ : ι → Bool ↦ s.inf fun i ↦ if σ i then φ i else (φ i)ᶜ) = ⊤ from this univ
  intro s
  induction s using Finset.induction with
  | empty => simp [sup_const univ_nonempty]
  | insert j s hj ih =>
    refine eq_top_iff.2 (ih.symm.trans_le (Finset.sup_le fun σ _ ↦ ?_))
    set g : (ι → Bool) → α := fun τ ↦ s.inf fun i ↦ if τ i then φ i else (φ i)ᶜ
    have hg (b : Bool) : g (Function.update σ j b) = g σ :=
      Finset.inf_congr rfl fun i hi ↦ by rw [Function.update_of_ne (ne_of_mem_of_not_mem hi hj)]
    calc g σ = (φ j ⊓ g σ) ⊔ ((φ j)ᶜ ⊓ g σ) := by rw [← inf_sup_right, sup_compl_eq_top, top_inf_eq]
      _ ≤ _ := by
        refine sup_le (le_sup_of_le (mem_univ (Function.update σ j true)) (le_of_eq ?_))
          (le_sup_of_le (mem_univ (Function.update σ j false)) (le_of_eq ?_))
        · rw [Finset.inf_insert, Function.update_self, ← hg true]; rfl
        · rw [Finset.inf_insert, Function.update_self, ← hg false]; rfl

end Minterm

namespace Finpartition

variable {ι β : Type*} [Fintype ι] [DecidableEq ι] [DecidableEq β]

/-- The partition of `ι` generated by `s` puts two elements in one block when `s` takes the same
value at both. -/
def ofFun (s : ι → β) : Finpartition (univ : Finset ι) :=
  @ofSetoid _ _ _ (Setoid.ker s) fun a b ↦ inferInstanceAs (Decidable (s a = s b))

theorem parts_ofFun (s : ι → β) :
    (ofFun s).parts = univ.image fun i ↦ ({j | s i = s j} : Finset ι) := by
  rw [ofFun, ofSetoid, ofSetSetoid_parts]
  rfl

theorem mem_part_ofFun {s : ι → β} {i j : ι} : j ∈ (ofFun s).part i ↔ s i = s j := by
  rw [ofFun, mem_part_ofSetoid_iff_rel]
  rfl

/-- The partition generated by a function depends only on which of its values coincide. -/
theorem ofFun_congr {γ : Type*} [DecidableEq γ] {s : ι → β} {t : ι → γ}
    (h : ∀ i j, s i = s j ↔ t i = t j) : ofFun s = ofFun t := by
  ext B
  simp only [parts_ofFun, h]

/-- Every partition of `ι` is generated by the function sending each element to its block. -/
theorem ofFun_part (P : Finpartition (univ : Finset ι)) : ofFun P.part = P := by
  ext B
  simp only [parts_ofFun, mem_image, mem_univ, true_and]
  constructor
  · rintro ⟨i, rfl⟩
    convert P.part_mem.2 (mem_univ i) using 1
    ext j
    simp only [mem_filter, mem_univ, true_and]
    rw [P.mem_part_iff_part_eq_part (mem_univ j) (mem_univ i), eq_comm]
  · intro hB
    obtain ⟨i, hi⟩ := P.nonempty_of_mem_parts hB
    refine ⟨i, ?_⟩
    rw [← P.part_eq_of_mem hB hi]
    ext j
    simp only [mem_filter, mem_univ, true_and]
    rw [P.mem_part_iff_part_eq_part (mem_univ j) (mem_univ i), eq_comm]

/-- The multiset of the sizes of the blocks. -/
def partSizes {s : Finset ι} (P : Finpartition s) : Multiset ℕ := P.parts.val.map card

omit [Fintype ι] in
/-- The block sizes add up to the size of the partitioned set. -/
@[simp]
theorem sum_partSizes {s : Finset ι} (P : Finpartition s) : P.partSizes.sum = #s := by
  rw [partSizes, ← P.sum_card_parts, sum_eq_multiset_sum]

/-- The block sizes of the partition generated by `s` are the multiplicities of its values. -/
theorem partSizes_ofFun (s : ι → β) :
    (ofFun s).partSizes = (univ.image s).val.map fun v ↦ #{i | s i = v} := by
  have hp : (ofFun s).parts = (univ.image s).image fun v ↦ ({j | v = s j} : Finset ι) := by
    rw [parts_ofFun, image_image]
    rfl
  have hinj : Set.InjOn (fun v ↦ ({j | v = s j} : Finset ι)) (univ.image s : Set β) := by
    rintro v hv w - h
    obtain ⟨i, -, rfl⟩ := mem_image.1 hv
    have : i ∈ ({j | s i = s j} : Finset ι) := by simp
    rw [show ({j | s i = s j} : Finset ι) = ({j | w = s j} : Finset ι) from h] at this
    exact (by simpa using this : w = s i).symm
  rw [partSizes, hp, image_val_of_injOn hinj, Multiset.map_map]
  congr 1
  funext v
  simp [eq_comm]

/-- The partition generated by `s` has one block per value. -/
@[simp]
theorem card_partSizes_ofFun (s : ι → β) : (ofFun s).partSizes.card = #(univ.image s) := by
  rw [partSizes_ofFun, Multiset.card_map]
  rfl

theorem part_ofFun_eq_part_ofFun_iff {s : ι → β} {i j : ι} :
    (ofFun s).part i = (ofFun s).part j ↔ s i = s j := by
  rw [← (ofFun s).mem_part_iff_part_eq_part (mem_univ i) (mem_univ j), mem_part_ofFun, eq_comm]

/-- Composing the block map of a generated partition with `g` generates the same partition as
composing the generator with `g`. -/
theorem ofFun_part_ofFun_comp (s : ι → β) (g : ι → ι) :
    ofFun ((ofFun s).part ∘ g) = ofFun (s ∘ g) :=
  ofFun_congr fun _ _ ↦ part_ofFun_eq_part_ofFun_iff

/-! ### Relabelling by permutations -/

/-- A permutation `σ` of `ι` relabels a partition of `ι`, moving each block `B` to `σ '' B`. -/
instance : MulAction (Equiv.Perm ι) (Finpartition (univ : Finset ι)) where
  smul σ P := ofFun (P.part ∘ ⇑σ⁻¹)
  one_smul P := by
    show ofFun (P.part ∘ ⇑(1 : Equiv.Perm ι)⁻¹) = P
    simpa using ofFun_part P
  mul_smul σ τ P := by
    show ofFun (P.part ∘ ⇑(σ * τ)⁻¹) = ofFun ((ofFun (P.part ∘ ⇑τ⁻¹)).part ∘ ⇑σ⁻¹)
    rw [ofFun_part_ofFun_comp, mul_inv_rev, Equiv.Perm.coe_mul, Function.comp_assoc]

theorem smul_def (σ : Equiv.Perm ι) (P : Finpartition (univ : Finset ι)) :
    σ • P = ofFun (P.part ∘ ⇑σ⁻¹) := rfl

/-- Precomposing a function with a permutation relabels the partition it generates. -/
theorem ofFun_comp_perm (s : ι → β) (σ : Equiv.Perm ι) : ofFun (s ∘ σ) = σ⁻¹ • ofFun s := by
  rw [smul_def, inv_inv, ofFun_part_ofFun_comp]

/-- Relabelling preserves the block sizes. -/
theorem partSizes_smul (σ : Equiv.Perm ι) (P : Finpartition (univ : Finset ι)) :
    (σ • P).partSizes = P.partSizes := by
  conv_rhs => rw [← ofFun_part P]
  rw [smul_def, partSizes_ofFun, partSizes_ofFun, image_comp, image_univ_equiv]
  congr 1
  funext B
  exact card_equiv σ⁻¹ fun i ↦ by simp

/-! ### Labelling by least elements -/

section Fin

variable {n : ℕ}

/-- The label of `i` in a partition of `Fin n` is the least element of its block. -/
def minLabel (P : Finpartition (univ : Finset (Fin n))) (i : Fin n) : ℕ :=
  (P.part i).min' (P.part_nonempty.2 (mem_univ i))

theorem minLabel_le (P : Finpartition (univ : Finset (Fin n))) (i : Fin n) : P.minLabel i ≤ i :=
  Fin.le_iff_val_le_val.1 (min'_le _ _ (P.mem_part_self.2 (mem_univ i)))

theorem minLabel_eq_of_mem {P : Finpartition (univ : Finset (Fin n))} {i j : Fin n}
    (hj : j ∈ P.part i) (hmin : ∀ k ∈ P.part i, j ≤ k) : P.minLabel i = j :=
  congrArg Fin.val (le_antisymm (min'_le _ _ hj) (le_min' _ _ _ hmin))

/-- A partition of `Fin n` is generated by its labelling by least elements. -/
theorem ofFun_minLabel (P : Finpartition (univ : Finset (Fin n))) : ofFun P.minLabel = P := by
  refine (ofFun_congr fun i j ↦ ⟨fun h ↦ ?_, fun h ↦ by simp only [minLabel, h]⟩).trans
    (ofFun_part P)
  have hi := min'_mem _ (P.part_nonempty.2 (mem_univ i))
  have hj := min'_mem _ (P.part_nonempty.2 (mem_univ j))
  rw [show (P.part i).min' _ = (P.part j).min' _ from Fin.ext h] at hi
  exact P.eq_of_mem_parts (P.part_mem.2 (mem_univ i)) (P.part_mem.2 (mem_univ j)) hi hj

/-- In a sequence of least-element labels, each label is the index where it first occurs. -/
theorem le_of_minLabel_ofFun_eq {s : Fin n → ℕ} (hs : (ofFun s).minLabel = s) (k : Fin n) :
    s k ≤ k ∧ ∃ h : s k < n, s ⟨s k, h⟩ = s k ∧ ∀ k', s k = s k' → s k ≤ k' := by
  have hm := min'_mem _ ((ofFun s).part_nonempty.2 (mem_univ k))
  have hval : ((ofFun s).part k).min' ((ofFun s).part_nonempty.2 (mem_univ k)) = s k :=
    congrFun hs k
  have hle := (ofFun s).minLabel_le k
  rw [congrFun hs k] at hle
  refine ⟨hle, hle.trans_lt k.2, ?_, fun k' hk' ↦ ?_⟩
  · rw [mem_part_ofFun] at hm
    convert hm.symm using 2
    exact Fin.ext hval.symm
  · rw [← hval]
    exact Fin.le_iff_val_le_val.1 (min'_le _ _ (mem_part_ofFun.2 hk'))

/-- Appending an earlier label, or the next index, to a sequence of least-element labels gives a
sequence of least-element labels. -/
theorem minLabel_ofFun_snoc {s : Fin n → ℕ} (hs : (ofFun s).minLabel = s) {c : ℕ}
    (hc : c ∈ univ.image s ∨ c = n) :
    (ofFun (Fin.snoc s c : Fin (n + 1) → ℕ)).minLabel = Fin.snoc s c := by
  have hv := le_of_minLabel_ofFun_eq hs
  funext i
  cases i using Fin.lastCases with
  | last =>
    rw [Fin.snoc_last]
    obtain hc | hc := hc
    · obtain ⟨k₀, -, rfl⟩ := mem_image.1 hc
      obtain ⟨-, hlt, hfix, hmin⟩ := hv k₀
      refine minLabel_eq_of_mem (j := Fin.castSucc ⟨s k₀, hlt⟩) ?_ fun k hk ↦ ?_
      · rw [mem_part_ofFun, Fin.snoc_last, Fin.snoc_castSucc, hfix]
      · rw [mem_part_ofFun] at hk
        cases k using Fin.lastCases with
        | last => exact Fin.le_last _
        | cast k => simpa [Fin.le_iff_val_le_val] using hmin k (by simpa using hk)
    · subst c
      refine minLabel_eq_of_mem (j := Fin.last n) ((ofFun _).mem_part_self.2 (mem_univ _))
        fun k hk ↦ ?_
      rw [mem_part_ofFun] at hk
      cases k using Fin.lastCases with
      | last => exact le_rfl
      | cast k =>
        simp only [Fin.snoc_last, Fin.snoc_castSucc] at hk
        exact absurd ((hv k).1.trans_lt k.2) (by omega)
  | cast k =>
    rw [Fin.snoc_castSucc]
    obtain ⟨-, hlt, hfix, hmin⟩ := hv k
    refine minLabel_eq_of_mem (j := Fin.castSucc ⟨s k, hlt⟩) ?_ fun k' hk' ↦ ?_
    · rw [mem_part_ofFun, Fin.snoc_castSucc, Fin.snoc_castSucc, hfix]
    · rw [mem_part_ofFun] at hk'
      cases k' using Fin.lastCases with
      | last => exact Fin.le_last _
      | cast k' => simpa [Fin.le_iff_val_le_val] using hmin k' (by simpa using hk')

/-- A sequence of least-element labels stays one when its last entry is removed, and its last
entry is an earlier label or the next index. -/
theorem minLabel_ofFun_of_snoc {s : Fin n → ℕ} {c : ℕ}
    (hs : (ofFun (Fin.snoc s c : Fin (n + 1) → ℕ)).minLabel = Fin.snoc s c) :
    (ofFun s).minLabel = s ∧ (c ∈ univ.image s ∨ c = n) := by
  have hv := le_of_minLabel_ofFun_eq hs
  constructor
  · funext k
    obtain ⟨hle, hlt', hfix, hmin⟩ := hv k.castSucc
    simp only [Fin.snoc_castSucc, Fin.val_castSucc] at hle hlt' hfix hmin
    have hlt : s k < n := hle.trans_lt k.2
    refine minLabel_eq_of_mem (j := ⟨s k, hlt⟩) ?_ fun k' hk' ↦ ?_
    · rw [mem_part_ofFun]
      rw [show (⟨s k, _⟩ : Fin (n + 1)) = Fin.castSucc ⟨s k, hlt⟩ from rfl,
        Fin.snoc_castSucc] at hfix
      exact hfix.symm
    · rw [mem_part_ofFun] at hk'
      simpa [Fin.le_iff_val_le_val] using hmin k'.castSucc (by simpa using hk')
  · obtain ⟨hle, hlt, hfix, -⟩ := hv (Fin.last n)
    simp only [Fin.snoc_last, Fin.val_last] at hle hlt hfix
    obtain hcn | rfl := hle.lt_or_eq
    · left
      rw [show (⟨c, hlt⟩ : Fin (n + 1)) = Fin.castSucc ⟨c, hcn⟩ from rfl,
        Fin.snoc_castSucc] at hfix
      exact mem_image.2 ⟨_, mem_univ _, hfix⟩
    · exact Or.inr rfl

variable {β : Type*} [DecidableEq β]

theorem image_snoc (s : Fin n → β) (c : β) :
    univ.image (Fin.snoc s c : Fin (n + 1) → β) = insert c (univ.image s) := by
  ext v
  simp [Fin.exists_fin_succ', eq_comm, or_comm]

theorem card_filter_snoc (s : Fin n → β) (c v : β) :
    #{i | (Fin.snoc s c : Fin (n + 1) → β) i = v} = #{i | s i = v} + if c = v then 1 else 0 := by
  rw [card_filter, card_filter, Fin.sum_univ_castSucc]
  simp only [Fin.snoc_castSucc, Fin.snoc_last]

/-- Appending a new value adds a block of size one. -/
theorem partSizes_ofFun_snoc_of_notMem {s : Fin n → β} {c : β} (hc : c ∉ univ.image s) :
    (ofFun (Fin.snoc s c : Fin (n + 1) → β)).partSizes = 1 ::ₘ (ofFun s).partSizes := by
  have h0 : #{i | s i = c} = 0 := card_eq_zero.2 (filter_eq_empty_iff.2 fun i _ h ↦
    hc (mem_image.2 ⟨i, mem_univ _, h⟩))
  rw [partSizes_ofFun, partSizes_ofFun, image_snoc, insert_val_of_notMem hc, Multiset.map_cons,
    card_filter_snoc]
  simp only [↓reduceIte, h0, zero_add]
  congr 1
  refine Multiset.map_congr rfl fun v hv ↦ ?_
  have hcv : c ≠ v := fun h ↦ hc (by rw [h]; exact hv)
  simp [card_filter_snoc, hcv]

/-- Appending an existing value enlarges its block by one. -/
theorem partSizes_ofFun_snoc_of_mem {s : Fin n → β} {c : β} (hc : c ∈ univ.image s) :
    (ofFun (Fin.snoc s c : Fin (n + 1) → β)).partSizes =
      (#{i | s i = c} + 1) ::ₘ (ofFun s).partSizes.erase #{i | s i = c} := by
  rw [partSizes_ofFun, partSizes_ofFun, image_snoc, insert_eq_of_mem hc]
  have hcv : c ∈ (univ.image s).val := hc
  have hrest : ((univ.image s).val.erase c).map
      (fun v ↦ #{i | (Fin.snoc s c : Fin (n + 1) → β) i = v}) =
      ((univ.image s).val.erase c).map fun v ↦ #{i | s i = v} :=
    Multiset.map_congr rfl fun v hv ↦ by
      have hne : c ≠ v := by
        rintro rfl
        exact (univ.image s).nodup.notMem_erase hv
      simp [card_filter_snoc, hne]
  conv_lhs => rw [← Multiset.cons_erase hcv]
  rw [Multiset.map_cons, hrest, Multiset.map_erase_of_mem _ _ hcv, card_filter_snoc]
  simp

end Fin

/-! ### The partition into minterms -/

section Minterms

variable {α κ : Type*} [BooleanAlgebra α] [DecidableEq α]

variable (φ : ι → α) in
/-- The partition of `⊤` generated by a family has its nonzero minterms as parts. -/
def minterms : Finpartition (⊤ : α) :=
  .ofErase (univ.image (minterm φ))
    (Set.PairwiseDisjoint.supIndep fun a ha b hb hab ↦ by
      obtain ⟨σ, -, rfl⟩ := mem_image.1 ha
      obtain ⟨τ, -, rfl⟩ := mem_image.1 hb
      exact disjoint_minterm fun h ↦ hab (h ▸ rfl))
    (by rw [sup_image, Function.id_comp, sup_minterm])

theorem mem_minterms_parts {φ : ι → α} {a : α} :
    a ∈ (minterms φ).parts ↔ a ≠ ⊥ ∧ ∃ σ, minterm φ σ = a := by
  simp [minterms]

/-- Reindexing a family does not change its minterms. -/
theorem parts_minterms_comp_equiv [Fintype κ] [DecidableEq κ] (e : κ ≃ ι) (φ : ι → α) :
    (minterms (φ ∘ e)).parts = (minterms φ).parts := by
  ext a
  simp only [mem_minterms_parts, minterm_comp_equiv]
  refine and_congr_right fun _ ↦ ⟨fun ⟨σ, h⟩ ↦ ⟨_, h⟩, fun ⟨τ, h⟩ ↦ ⟨τ ∘ e, ?_⟩⟩
  simpa [Function.comp_assoc] using h

/-- The minterms of the union of two families form the meet of their partitions into minterms. -/
theorem minterms_sumElim [Fintype κ] [DecidableEq κ] (φ : ι → α) (ψ : κ → α) :
    minterms (Sum.elim φ ψ) = minterms φ ⊓ minterms ψ := by
  ext a
  simp only [parts_inf, mem_erase, mem_image, mem_product, mem_minterms_parts, Prod.exists,
    minterm_sumElim]
  refine and_congr_right fun ha ↦ ⟨?_, ?_⟩
  · rintro ⟨σ, rfl⟩
    exact ⟨_, _, ⟨⟨ne_bot_of_le_ne_bot ha inf_le_left, _, rfl⟩,
      ne_bot_of_le_ne_bot ha inf_le_right, _, rfl⟩, rfl⟩
  · rintro ⟨-, -, ⟨⟨-, σ, rfl⟩, -, τ, rfl⟩, rfl⟩
    exact ⟨Sum.elim σ τ, by simp [Function.comp_def]⟩

/-- The minterms of a family of finsets are the fibres of membership in the family. -/
theorem parts_minterms_eq_parts_ofFun {γ : Type*} [Fintype γ] [DecidableEq γ]
    (φ : ι → Finset γ) :
    (minterms φ).parts = (ofFun fun x i ↦ decide (x ∈ φ i)).parts := by
  have key (x : γ) : minterm φ (fun i ↦ decide (x ∈ φ i)) =
      ({y | (fun i ↦ decide (x ∈ φ i)) = fun i ↦ decide (y ∈ φ i)} : Finset γ) := by
    ext y
    rw [mem_minterm, mem_filter, funext_iff]
    simp only [mem_univ, true_and, decide_eq_decide, decide_eq_true_iff]
    exact forall_congr' fun _ ↦ Iff.comm
  ext B
  simp only [mem_minterms_parts, parts_ofFun, mem_image, mem_univ, true_and]
  constructor
  · rintro ⟨hB, σ, rfl⟩
    obtain ⟨x, hx⟩ := Finset.nonempty_iff_ne_empty.2 hB
    have hσ : σ = fun i ↦ decide (x ∈ φ i) := funext fun i ↦ by
      rw [Bool.eq_iff_iff, decide_eq_true_iff]
      exact ((mem_minterm.1 hx) i).symm
    exact ⟨x, hσ ▸ (key x).symm⟩
  · rintro ⟨x, rfl⟩
    exact ⟨Finset.ne_empty_of_mem (a := x) (by simp), _, key x⟩

end Minterms

end Finpartition
