module

public import Mathlib.Tactic.DeriveFintype
public import Linglib.Core.Order.Bundle

/-!
# PHOIBLE 2.0 schema
[moran-mccloy-2019]

Substrate types for the PHOIBLE 2.0 phonological inventory database
(Moran & McCloy 2019, http://phoible.org, DOI 10.5281/zenodo.2626687).

PHOIBLE 2.0 contains 3000+ inventories (doculects) covering 2100+ ISO 639-3
language codes. Each entry is a (languoid × phoneme) pair with distinctive-
feature decomposition. The CSV `data/phoible-2019/phoible.csv` has 49
columns and ~105K rows.

This Lean substrate mirrors the row-level structure: an `Inventory` is a
list of `Phoneme`s, each carrying a `FeatureMatrix`, a `Bundle` over the PHOIBLE
features.
Per-inventory data lives in `Data/PHOIBLE/Inventories/{Lang}.lean`,
auto-generated by `scripts/gen_phoible.py`.

## Relation to WALS / Maddieson 2013

PHOIBLE 2.0 is the field-canonical successor to UPSID and to WALS Maddieson
chapters 1–19 for inventory facts: ~3000 inventories vs. WALS's ~563
languages, with the original transcribed inventory preserved (rather than
collapsed into Maddieson's 5-bin partition). The two are complementary:
WALS gives partition-based typology; PHOIBLE gives the underlying
inventories.

## Citation

> Moran, Steven & McCloy, Daniel (eds.) 2019. PHOIBLE 2.0. Jena: Max Planck
> Institute for the Science of Human History.
> http://phoible.org. DOI: 10.5281/zenodo.2626687

-/

@[expose] public section

namespace Data.PHOIBLE

/-- PHOIBLE segment class (the `SegmentClass` column). -/
inductive SegmentClass where
  | consonant
  | vowel
  | tone
  deriving DecidableEq, BEq, Repr

/-- PHOIBLE source database (the `Source` column). PHOIBLE aggregates
    nine donor databases. -/
inductive Source where
  /-- Stanford Phonology Archive. -/
  | spa
  /-- UCLA Phonological Segment Inventory Database. -/
  | upsid
  /-- Alphabets of Africa (Hartell 1993, Chanard 2006). -/
  | aa
  /-- Sounds of the World's Languages (Maddieson & Disner 1984). -/
  | gm
  /-- Christopher Green & Steven Moran's African inventories. -/
  | ph
  /-- Ramaswami's Indian languages collection (1999). -/
  | ra
  /-- South American Phonological Inventory Database (Michael et al.). -/
  | saphon
  /-- Eurasia (Nikolaev). -/
  | ea
  /-- Eric Round's Australian. -/
  | er
  deriving DecidableEq, BEq, Repr

/-- The PHOIBLE distinctive features, the PHOIBLE-Hayes feature system (cf.
    `phoible/dev/raw-data/FEATURES/`), with the tone and stress columns. -/
inductive Feature where
  | syllabic | short | long | consonantal | sonorant | continuant | delayedRelease
  | approximant | tap | trill | nasal | lateral | labial | round | labiodental | coronal
  | anterior | distributed | strident | dorsal | high | low | front | back | tense
  | retractedTongueRoot | advancedTongueRoot | periodicGlottalSource | epilaryngealSource
  | spreadGlottis | constrictedGlottis | fortis | lenis | raisedLarynxEjective
  | loweredLarynxImplosive | click | tone | stress
  deriving DecidableEq, Repr, Fintype

/-- A PHOIBLE feature matrix is a bundle over the features, with `+` and `−` as the two
    values and PHOIBLE's `0`, not applicable, left unspecified. Generated inventories build
    one with `Bundle.ofList`, listing the specified features. -/
abbrev FeatureMatrix := Bundle Feature fun _ ↦ Bool

/-- A PHOIBLE phoneme entry carries its IPA glyph, its feature matrix and its metadata. -/
structure Phoneme where
  /-- IPA representation (the `Phoneme` column). -/
  glyph : String
  /-- Hex-encoded Unicode codepoint sequence (the `GlyphID` column). -/
  glyphId : String
  /-- Allophones as a space-separated IPA list (the `Allophones` column).
      Empty when `NA` in source. -/
  allophones : List String
  /-- Whether the segment is marginal in the inventory (the `Marginal`
      column: `TRUE` → true, `FALSE` or `NA` → false). -/
  marginal : Bool
  segmentClass : SegmentClass
  features : FeatureMatrix
  deriving DecidableEq

/-- A PHOIBLE inventory collapses the rows sharing an inventory identifier into one
    structure with its phoneme list. -/
structure Inventory where
  /-- PHOIBLE InventoryID (unique per inventory). -/
  id : Nat
  /-- Glottolog code. -/
  glottocode : String
  /-- ISO 639-3 code (may be empty for some doculects). -/
  iso : String
  languageName : String
  /-- Specific dialect, if recorded; empty when `NA` in source. -/
  specificDialect : String
  source : Source
  /-- The inventory's full phoneme list. -/
  phonemes : List Phoneme
  deriving DecidableEq

/-- Number of phonemes in an inventory. -/
def Inventory.size (inv : Inventory) : Nat := inv.phonemes.length

/-- Number of consonants in an inventory. -/
def Inventory.consonantCount (inv : Inventory) : Nat :=
  (inv.phonemes.filter (·.segmentClass == SegmentClass.consonant)).length

/-- Number of vowels in an inventory. -/
def Inventory.vowelCount (inv : Inventory) : Nat :=
  (inv.phonemes.filter (·.segmentClass == SegmentClass.vowel)).length

/-- Number of distinct tones in an inventory. -/
def Inventory.toneCount (inv : Inventory) : Nat :=
  (inv.phonemes.filter (·.segmentClass == SegmentClass.tone)).length

end Data.PHOIBLE
