import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 101A: Expression of Pronominal Subjects
@cite{wals-2013}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 101A`.

Chapter 101, 711 languages.
-/

namespace Core.WALS.F101A

/-- WALS 101A values. -/
inductive ExpressionOfPronominalSubjects where
  /-- Obligatory pronouns in subject position (82 languages). -/
  | obligatoryPronounsInSubjectPosition
  /-- Subject affixes on verb (437 languages). -/
  | subjectAffixesOnVerb
  /-- Subject clitics on variable host (32 languages). -/
  | subjectCliticsOnVariableHost
  /-- Subject pronouns in different position (67 languages). -/
  | subjectPronounsInDifferentPosition
  /-- Optional pronouns in subject position (61 languages). -/
  | optionalPronounsInSubjectPosition
  /-- Mixed (32 languages). -/
  | mixed
  deriving DecidableEq, BEq, Repr

private def allData_0 : List (Datapoint ExpressionOfPronominalSubjects) :=
  [ { walsCode := "aar", iso := "aiw", value := .subjectAffixesOnVerb }
  , { walsCode := "abk", iso := "abk", value := .subjectAffixesOnVerb }
  , { walsCode := "abv", iso := "abz", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "abu", iso := "kgr", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "acg", iso := "aca", value := .subjectAffixesOnVerb }
  , { walsCode := "acl", iso := "ach", value := .subjectAffixesOnVerb }
  , { walsCode := "aco", iso := "kjq", value := .subjectAffixesOnVerb }
  , { walsCode := "aga", iso := "agd", value := .subjectAffixesOnVerb }
  , { walsCode := "ain", iso := "ain", value := .subjectAffixesOnVerb }
  , { walsCode := "aja", iso := "aja", value := .subjectAffixesOnVerb }
  , { walsCode := "all", iso := "nrz", value := .subjectAffixesOnVerb }
  , { walsCode := "ala", iso := "amp", value := .subjectAffixesOnVerb }
  , { walsCode := "alb", iso := "sqi", value := .subjectAffixesOnVerb }
  , { walsCode := "aln", iso := "alp", value := .mixed }
  , { walsCode := "aml", iso := "omb", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "amq", iso := "amk", value := .subjectAffixesOnVerb }
  , { walsCode := "amb", iso := "abt", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "amh", iso := "amh", value := .subjectAffixesOnVerb }
  , { walsCode := "amx", iso := "imi", value := .subjectAffixesOnVerb }
  , { walsCode := "anj", iso := "aty", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "ang", iso := "agg", value := .subjectAffixesOnVerb }
  , { walsCode := "agt", iso := "awg", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "any", iso := "anu", value := .subjectAffixesOnVerb }
  , { walsCode := "ane", iso := "anz", value := .subjectAffixesOnVerb }
  , { walsCode := "ao", iso := "njo", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "apw", iso := "apw", value := .subjectAffixesOnVerb }
  , { walsCode := "apl", iso := "apy", value := .subjectAffixesOnVerb }
  , { walsCode := "apu", iso := "apu", value := .subjectAffixesOnVerb }
  , { walsCode := "aeg", iso := "arz", value := .subjectAffixesOnVerb }
  , { walsCode := "arg", iso := "afb", value := .subjectAffixesOnVerb }
  , { walsCode := "arq", iso := "acm", value := .subjectAffixesOnVerb }
  , { walsCode := "amr", iso := "ary", value := .subjectAffixesOnVerb }
  , { walsCode := "asy", iso := "apc", value := .subjectAffixesOnVerb }
  , { walsCode := "arp", iso := "ape", value := .subjectAffixesOnVerb }
  , { walsCode := "arm", iso := "hye", value := .subjectAffixesOnVerb }
  , { walsCode := "arw", iso := "hyw", value := .subjectAffixesOnVerb }
  , { walsCode := "amp", iso := "aer", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "asm", iso := "cns", value := .subjectAffixesOnVerb }
  , { walsCode := "ass", iso := "asm", value := .subjectAffixesOnVerb }
  , { walsCode := "ata", iso := "tay", value := .subjectCliticsOnVariableHost }
  , { walsCode := "ath", iso := "aph", value := .subjectAffixesOnVerb }
  , { walsCode := "awa", iso := "awb", value := .subjectAffixesOnVerb }
  , { walsCode := "awp", iso := "kwi", value := .subjectAffixesOnVerb }
  , { walsCode := "awt", iso := "kmn", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "aym", iso := "ayr", value := .subjectAffixesOnVerb }
  , { walsCode := "ayr", iso := "ayo", value := .subjectAffixesOnVerb }
  , { walsCode := "bbl", iso := "bvx", value := .subjectAffixesOnVerb }
  , { walsCode := "bab", iso := "bav", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "bgr", iso := "fuu", value := .subjectAffixesOnVerb }
  , { walsCode := "bku", iso := "bri", value := .subjectAffixesOnVerb }
  , { walsCode := "blz", iso := "", value := .subjectAffixesOnVerb }
  , { walsCode := "bvi", iso := "", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "bnn", iso := "bcm", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "ble", iso := "bci", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "brs", iso := "bsn", value := .subjectAffixesOnVerb }
  , { walsCode := "brp", iso := "bpe", value := .subjectAffixesOnVerb }
  , { walsCode := "bae", iso := "bae", value := .subjectAffixesOnVerb }
  , { walsCode := "bsr", iso := "bsc", value := .subjectAffixesOnVerb }
  , { walsCode := "bas", iso := "bas", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "bsk", iso := "bak", value := .subjectAffixesOnVerb }
  , { walsCode := "bsq", iso := "eus", value := .subjectAffixesOnVerb }
  , { walsCode := "bkr", iso := "btx", value := .mixed }
  , { walsCode := "baw", iso := "bgr", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "bej", iso := "bej", value := .subjectAffixesOnVerb }
  , { walsCode := "bel", iso := "byw", value := .subjectAffixesOnVerb }
  , { walsCode := "bco", iso := "blc", value := .subjectAffixesOnVerb }
  , { walsCode := "bem", iso := "bem", value := .subjectAffixesOnVerb }
  , { walsCode := "bfg", iso := "grr", value := .subjectAffixesOnVerb }
  , { walsCode := "bma", iso := "tzm", value := .subjectAffixesOnVerb }
  , { walsCode := "brf", iso := "rif", value := .subjectAffixesOnVerb }
  , { walsCode := "bik", iso := "bhw", value := .subjectAffixesOnVerb }
  , { walsCode := "bid", iso := "bid", value := .mixed }
  , { walsCode := "bln", iso := "byn", value := .subjectAffixesOnVerb }
  , { walsCode := "blx", iso := "bll", value := .subjectAffixesOnVerb }
  , { walsCode := "bil", iso := "blb", value := .subjectCliticsOnVariableHost }
  , { walsCode := "bmb", iso := "bim", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "bin", iso := "bhg", value := .subjectAffixesOnVerb }
  , { walsCode := "big", iso := "yul", value := .subjectAffixesOnVerb }
  , { walsCode := "bbw", iso := "gup", value := .subjectAffixesOnVerb }
  , { walsCode := "bii", iso := "bzr", value := .subjectAffixesOnVerb }
  , { walsCode := "bir", iso := "bom", value := .subjectAffixesOnVerb }
  , { walsCode := "bla", iso := "bla", value := .subjectCliticsOnVariableHost }
  , { walsCode := "bob", iso := "bni", value := .subjectAffixesOnVerb }
  , { walsCode := "bol", iso := "bli", value := .subjectAffixesOnVerb }
  , { walsCode := "brr", iso := "bor", value := .subjectAffixesOnVerb }
  , { walsCode := "brh", iso := "brh", value := .subjectAffixesOnVerb }
  , { walsCode := "bre", iso := "bre", value := .subjectAffixesOnVerb }
  , { walsCode := "bud", iso := "bdm", value := .mixed }
  , { walsCode := "bul", iso := "bul", value := .subjectAffixesOnVerb }
  , { walsCode := "buw", iso := "bum", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "bum", iso := "tkw", value := .subjectAffixesOnVerb }
  , { walsCode := "bnb", iso := "bck", value := .subjectAffixesOnVerb }
  , { walsCode := "brm", iso := "mya", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "brn", iso := "bds", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "bur", iso := "bsk", value := .subjectAffixesOnVerb }
  , { walsCode := "bus", iso := "bqp", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "bsh", iso := "buf", value := .subjectAffixesOnVerb }
  , { walsCode := "bya", iso := "bee", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "cah", iso := "chl", value := .subjectAffixesOnVerb }
  , { walsCode := "cax", iso := "", value := .subjectAffixesOnVerb }
  , { walsCode := "cde", iso := "mch", value := .subjectAffixesOnVerb }
  , { walsCode := "ctl", iso := "cat", value := .subjectAffixesOnVerb }
  , { walsCode := "cav", iso := "cav", value := .mixed }
  , { walsCode := "cyv", iso := "cyb", value := .subjectAffixesOnVerb }
  , { walsCode := "chh", iso := "sgw", value := .subjectAffixesOnVerb }
  , { walsCode := "cai", iso := "suq", value := .subjectAffixesOnVerb }
  , { walsCode := "cld", iso := "cld", value := .subjectAffixesOnVerb }
  , { walsCode := "chg", iso := "nbc", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "chn", iso := "chx", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "chc", iso := "che", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "cmh", iso := "ute", value := .subjectCliticsOnVariableHost }
  , { walsCode := "che", iso := "chr", value := .subjectAffixesOnVerb }
  , { walsCode := "cic", iso := "nya", value := .subjectAffixesOnVerb }
  , { walsCode := "chi", iso := "cid", value := .subjectAffixesOnVerb }
  , { walsCode := "chs", iso := "csy", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "cti", iso := "ctd", value := .mixed }
  , { walsCode := "cle", iso := "cle", value := .subjectAffixesOnVerb }
  , { walsCode := "cct", iso := "cho", value := .subjectAffixesOnVerb }
  , { walsCode := "cln", iso := "cht", value := .subjectAffixesOnVerb }
  , { walsCode := "chx", iso := "clo", value := .subjectAffixesOnVerb }
  , { walsCode := "cmy", iso := "chf", value := .subjectAffixesOnVerb }
  , { walsCode := "chk", iso := "ckt", value := .subjectAffixesOnVerb }
  , { walsCode := "cba", iso := "boi", value := .subjectAffixesOnVerb }
  , { walsCode := "cmn", iso := "com", value := .subjectCliticsOnVariableHost }
  , { walsCode := "coo", iso := "csz", value := .subjectAffixesOnVerb }
  , { walsCode := "crn", iso := "cor", value := .subjectAffixesOnVerb }
  , { walsCode := "cre", iso := "crk", value := .subjectCliticsOnVariableHost }
  , { walsCode := "cea", iso := "csw", value := .subjectCliticsOnVariableHost }
  , { walsCode := "cro", iso := "cro", value := .subjectAffixesOnVerb }
  , { walsCode := "cub", iso := "cub", value := .subjectAffixesOnVerb }
  , { walsCode := "cup", iso := "cup", value := .mixed }
  , { walsCode := "cze", iso := "ces", value := .subjectAffixesOnVerb }
  , { walsCode := "cem", iso := "cam", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "dag", iso := "dgz", value := .subjectAffixesOnVerb }
  , { walsCode := "dga", iso := "dga", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "dgb", iso := "dag", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "dni", iso := "dni", value := .subjectAffixesOnVerb }
  , { walsCode := "dsh", iso := "dan", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "des", iso := "des", value := .subjectAffixesOnVerb }
  , { walsCode := "dha", iso := "dsh", value := .mixed }
  , { walsCode := "dhi", iso := "div", value := .subjectAffixesOnVerb }
  , { walsCode := "die", iso := "dih", value := .subjectAffixesOnVerb }
  , { walsCode := "dig", iso := "mhu", value := .subjectAffixesOnVerb }
  , { walsCode := "dim", iso := "dim", value := .subjectAffixesOnVerb }
  , { walsCode := "din", iso := "din", value := .mixed }
  , { walsCode := "dio", iso := "dyo", value := .subjectAffixesOnVerb }
  , { walsCode := "djp", iso := "dwu", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "dlm", iso := "kbv", value := .subjectAffixesOnVerb }
  , { walsCode := "dom", iso := "rmt", value := .subjectAffixesOnVerb }
  , { walsCode := "dds", iso := "dds", value := .subjectAffixesOnVerb }
  , { walsCode := "doy", iso := "dow", value := .mixed }
  , { walsCode := "dre", iso := "dhv", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "dum", iso := "vam", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "dun", iso := "duc", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "dut", iso := "nld", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "ebi", iso := "igb", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "efi", iso := "efi", value := .subjectAffixesOnVerb }
  , { walsCode := "eip", iso := "eip", value := .subjectAffixesOnVerb }
  , { walsCode := "eko", iso := "eko", value := .subjectAffixesOnVerb }
  , { walsCode := "emb", iso := "emp", value := .subjectAffixesOnVerb }
  , { walsCode := "ene", iso := "", value := .subjectAffixesOnVerb }
  , { walsCode := "egn", iso := "enn", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "eng", iso := "eng", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "epe", iso := "sja", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "err", iso := "erg", value := .subjectAffixesOnVerb }
  , { walsCode := "esm", iso := "", value := .subjectAffixesOnVerb }
  , { walsCode := "est", iso := "ekk", value := .subjectAffixesOnVerb }
  , { walsCode := "eve", iso := "evn", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "ewe", iso := "ewe", value := .subjectAffixesOnVerb }
  , { walsCode := "ewo", iso := "ewo", value := .subjectAffixesOnVerb }
  , { walsCode := "fij", iso := "fij", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "fin", iso := "fin", value := .mixed }
  , { walsCode := "fre", iso := "fra", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "fri", iso := "fry", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "fua", iso := "fub", value := .subjectAffixesOnVerb }
  , { walsCode := "fur", iso := "fvr", value := .subjectAffixesOnVerb }
  , { walsCode := "fut", iso := "fut", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "fye", iso := "pym", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "gaa", iso := "gbu", value := .subjectAffixesOnVerb }
  , { walsCode := "gds", iso := "gaj", value := .subjectAffixesOnVerb }
  , { walsCode := "gae", iso := "gla", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "gah", iso := "gah", value := .subjectAffixesOnVerb }
  , { walsCode := "gar", iso := "grt", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "geo", iso := "kat", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "ger", iso := "deu", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "gim", iso := "bcq", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "goe", iso := "ank", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "gln", iso := "gvf", value := .subjectAffixesOnVerb }
  , { walsCode := "goo", iso := "gni", value := .subjectAffixesOnVerb }
  , { walsCode := "grb", iso := "grj", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "grk", iso := "ell", value := .subjectAffixesOnVerb }
  , { walsCode := "grw", iso := "kal", value := .subjectAffixesOnVerb }
  , { walsCode := "gjj", iso := "gub", value := .subjectAffixesOnVerb }
  , { walsCode := "gua", iso := "gug", value := .subjectAffixesOnVerb }
  , { walsCode := "grj", iso := "var", value := .subjectCliticsOnVariableHost }
  , { walsCode := "gud", iso := "gde", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "gul", iso := "kcm", value := .subjectAffixesOnVerb }
  , { walsCode := "gmw", iso := "gvs", value := .subjectAffixesOnVerb }
  , { walsCode := "gum", iso := "kgs", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "gmz", iso := "guk", value := .subjectAffixesOnVerb }
  , { walsCode := "grg", iso := "gge", value := .subjectAffixesOnVerb }
  , { walsCode := "gur", iso := "", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "guu", iso := "kky", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "gwa", iso := "gbr", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "gwo", iso := "kcg", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "gyc", iso := "jya", value := .subjectAffixesOnVerb }
  , { walsCode := "ga", iso := "gaa", value := .subjectAffixesOnVerb }
  , { walsCode := "hai", iso := "hai", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "hlu", iso := "hur", value := .subjectAffixesOnVerb }
  , { walsCode := "ham", iso := "hmt", value := .subjectAffixesOnVerb }
  , { walsCode := "hat", iso := "had", value := .subjectAffixesOnVerb }
  , { walsCode := "hau", iso := "hau", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "haw", iso := "haw", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "hya", iso := "hay", value := .subjectAffixesOnVerb }
  , { walsCode := "hay", iso := "vay", value := .subjectAffixesOnVerb }
  , { walsCode := "heb", iso := "heb", value := .mixed }
  , { walsCode := "heh", iso := "heh", value := .subjectAffixesOnVerb }
  , { walsCode := "hei", iso := "hei", value := .subjectCliticsOnVariableHost }
  , { walsCode := "hix", iso := "hix", value := .subjectAffixesOnVerb }
  , { walsCode := "hma", iso := "hmr", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "hmo", iso := "hnj", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "hua", iso := "ygr", value := .subjectAffixesOnVerb }
  , { walsCode := "hmi", iso := "hto", value := .subjectAffixesOnVerb }
  , { walsCode := "hnd", iso := "hke", value := .subjectAffixesOnVerb }
  , { walsCode := "hun", iso := "hun", value := .subjectAffixesOnVerb }
  , { walsCode := "isa", iso := "ksi", value := .subjectAffixesOnVerb }
  , { walsCode := "iaa", iso := "iai", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "iba", iso := "iba", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "ice", iso := "isl", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "ifu", iso := "ifb", value := .subjectAffixesOnVerb }
  , { walsCode := "igb", iso := "ibo", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "ige", iso := "ige", value := .subjectAffixesOnVerb }
  , { walsCode := "ik", iso := "ikx", value := .subjectAffixesOnVerb }
  , { walsCode := "ika", iso := "arh", value := .subjectAffixesOnVerb }
  , { walsCode := "ila", iso := "ilb", value := .subjectAffixesOnVerb }
  , { walsCode := "imo", iso := "imn", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "ina", iso := "szp", value := .subjectAffixesOnVerb }
  , { walsCode := "ind", iso := "ind", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "ing", iso := "inh", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "irq", iso := "irk", value := .subjectAffixesOnVerb }
  , { walsCode := "iri", iso := "gle", value := .mixed }
  , { walsCode := "ita", iso := "ita", value := .subjectAffixesOnVerb }
  , { walsCode := "ite", iso := "itl", value := .subjectAffixesOnVerb }
  , { walsCode := "ito", iso := "ito", value := .subjectAffixesOnVerb }
  , { walsCode := "izi", iso := "izz", value := .subjectAffixesOnVerb }
  , { walsCode := "jab", iso := "jae", value := .subjectAffixesOnVerb }
  , { walsCode := "jak", iso := "jac", value := .mixed }
  , { walsCode := "jam", iso := "djd", value := .subjectAffixesOnVerb }
  , { walsCode := "jpn", iso := "jpn", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "jwr", iso := "jaa", value := .mixed }
  , { walsCode := "jng", iso := "kac", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "juk", iso := "jbu", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "jmo", iso := "bex", value := .subjectAffixesOnVerb }
  , { walsCode := "juh", iso := "ktz", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "kab", iso := "kbd", value := .subjectAffixesOnVerb }
  , { walsCode := "kby", iso := "kbp", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "kdw", iso := "kbc", value := .subjectAffixesOnVerb }
  , { walsCode := "kgr", iso := "kki", value := .subjectAffixesOnVerb }
  , { walsCode := "krr", iso := "kxa", value := .subjectAffixesOnVerb }
  , { walsCode := "kae", iso := "tbd", value := .subjectAffixesOnVerb }
  , { walsCode := "kma", iso := "kay", value := .subjectAffixesOnVerb }
  , { walsCode := "kmz", iso := "kms", value := .subjectAffixesOnVerb }
  , { walsCode := "kms", iso := "xas", value := .subjectAffixesOnVerb }
  , { walsCode := "kba", iso := "kam", value := .subjectAffixesOnVerb }
  , { walsCode := "kam", iso := "xbr", value := .subjectAffixesOnVerb }
  , { walsCode := "kan", iso := "ogo", value := .subjectAffixesOnVerb }
  , { walsCode := "knd", iso := "kan", value := .subjectAffixesOnVerb }
  , { walsCode := "kno", iso := "kxo", value := .subjectAffixesOnVerb }
  , { walsCode := "knr", iso := "knc", value := .subjectAffixesOnVerb }
  , { walsCode := "krc", iso := "krc", value := .subjectAffixesOnVerb }
  , { walsCode := "kmj", iso := "kdj", value := .subjectAffixesOnVerb }
  , { walsCode := "kyr", iso := "yuj", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "krk", iso := "kyh", value := .subjectAffixesOnVerb }
  , { walsCode := "kaa", iso := "arr", value := .mixed }
  , { walsCode := "kas", iso := "kas", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "kau", iso := "pss", value := .mixed }
  , { walsCode := "kyl", iso := "eky", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "kay", iso := "gyd", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "kel", iso := "sbc", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "ken", iso := "kyq", value := .mixed }
  , { walsCode := "ksa", iso := "kee", value := .subjectAffixesOnVerb }
  , { walsCode := "kew", iso := "kew", value := .subjectAffixesOnVerb }
  , { walsCode := "kha", iso := "khk", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "kmh", iso := "kjl", value := .subjectAffixesOnVerb }
  , { walsCode := "kty", iso := "kca", value := .subjectAffixesOnVerb }
  , { walsCode := "khs", iso := "kha", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "kmu", iso := "kjg", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "kik", iso := "kik", value := .subjectAffixesOnVerb }
  , { walsCode := "klv", iso := "kij", value := .subjectAffixesOnVerb }
  , { walsCode := "kga", iso := "zga", value := .subjectAffixesOnVerb }
  , { walsCode := "kio", iso := "kio", value := .subjectAffixesOnVerb }
  , { walsCode := "kgz", iso := "kir", value := .subjectAffixesOnVerb }
  , { walsCode := "krb", iso := "gil", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "kis", iso := "kss", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "klm", iso := "kla", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "shp", iso := "yak", value := .mixed }
  , { walsCode := "koa", iso := "cku", value := .subjectAffixesOnVerb }
  , { walsCode := "kob", iso := "kpw", value := .subjectAffixesOnVerb }
  , { walsCode := "koe", iso := "xwg", value := .subjectAffixesOnVerb }
  , { walsCode := "kkt", iso := "kkk", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "kmb", iso := "", value := .subjectAffixesOnVerb }
  , { walsCode := "kon", iso := "kng", value := .subjectAffixesOnVerb }
  , { walsCode := "knw", iso := "mjd", value := .subjectCliticsOnVariableHost }
  , { walsCode := "krn", iso := "kqz", value := .subjectCliticsOnVariableHost }
  , { walsCode := "kor", iso := "kor", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "kku", iso := "kfq", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "kfe", iso := "kfz", value := .subjectAffixesOnVerb }
  , { walsCode := "krw", iso := "khe", value := .subjectAffixesOnVerb }
  , { walsCode := "kch", iso := "khq", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "kse", iso := "ses", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "kre", iso := "krs", value := .subjectAffixesOnVerb }
  , { walsCode := "kro", iso := "kgo", value := .mixed }
  , { walsCode := "knc", iso := "uwa", value := .mixed }
  , { walsCode := "knm", iso := "kun", value := .subjectAffixesOnVerb }
  , { walsCode := "kmp", iso := "kup", value := .subjectAffixesOnVerb }
  , { walsCode := "krd", iso := "ckb", value := .subjectAffixesOnVerb }
  , { walsCode := "kut", iso := "kut", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "thy", iso := "thd", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "kwa", iso := "kwd", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "kwk", iso := "kwk", value := .subjectAffixesOnVerb }
  , { walsCode := "kwn", iso := "kwn", value := .subjectAffixesOnVerb }
  , { walsCode := "kwz", iso := "xwa", value := .subjectAffixesOnVerb }
  , { walsCode := "kwt", iso := "kwo", value := .subjectAffixesOnVerb }
  , { walsCode := "kxo", iso := "xuu", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "kyk", iso := "kyc", value := .subjectAffixesOnVerb }
  , { walsCode := "laa", iso := "gdm", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "lad", iso := "lbj", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "lah", iso := "lhu", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "lai", iso := "cnh", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "lkt", iso := "lkt", value := .subjectAffixesOnVerb }
  , { walsCode := "lal", iso := "ywt", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "lmn", iso := "lmn", value := .mixed }
  , { walsCode := "lmb", iso := "lam", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "lmp", iso := "ljp", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "lgi", iso := "lag", value := .subjectAffixesOnVerb }
  , { walsCode := "lan", iso := "laj", value := .subjectAffixesOnVerb }
  , { walsCode := "lat", iso := "lav", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "lav", iso := "lvk", value := .subjectAffixesOnVerb }
  , { walsCode := "leg", iso := "lea", value := .subjectAffixesOnVerb }
  , { walsCode := "lel", iso := "lln", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "llm", iso := "lef", value := .subjectAffixesOnVerb }
  , { walsCode := "len", iso := "tnl", value := .subjectAffixesOnVerb }
  , { walsCode := "lep", iso := "lep", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "let", iso := "lti", value := .subjectAffixesOnVerb }
  , { walsCode := "lez", iso := "lez", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "lil", iso := "lil", value := .subjectAffixesOnVerb }
  , { walsCode := "lim", iso := "lif", value := .subjectAffixesOnVerb }
  , { walsCode := "lml", iso := "lmc", value := .subjectAffixesOnVerb }
  , { walsCode := "lin", iso := "lin", value := .subjectAffixesOnVerb }
  , { walsCode := "lit", iso := "lit", value := .subjectAffixesOnVerb }
  , { walsCode := "ara", iso := "arw", value := .subjectAffixesOnVerb }
  , { walsCode := "ldo", iso := "bdu", value := .subjectAffixesOnVerb }
  , { walsCode := "lgu", iso := "lgu", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "lon", iso := "los", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "lou", iso := "loj", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "luc", iso := "lch", value := .subjectAffixesOnVerb }
  , { walsCode := "lda", iso := "lug", value := .subjectAffixesOnVerb }
  , { walsCode := "lul", iso := "ule", value := .subjectAffixesOnVerb }
  , { walsCode := "lbu", iso := "lun", value := .subjectAffixesOnVerb }
  , { walsCode := "luo", iso := "luo", value := .subjectAffixesOnVerb }
  , { walsCode := "kkv", iso := "khl", value := .subjectAffixesOnVerb }
  , { walsCode := "luv", iso := "lue", value := .subjectAffixesOnVerb }
  , { walsCode := "luy", iso := "luy", value := .subjectAffixesOnVerb }
  , { walsCode := "mad", iso := "mhi", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "maa", iso := "mas", value := .subjectAffixesOnVerb }
  , { walsCode := "mab", iso := "mde", value := .subjectAffixesOnVerb }
  , { walsCode := "mac", iso := "mbc", value := .subjectAffixesOnVerb }
  , { walsCode := "mae", iso := "mmw", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "mne", iso := "nmu", value := .subjectAffixesOnVerb }
  , { walsCode := "mpr", iso := "", value := .subjectAffixesOnVerb }
  , { walsCode := "maj", iso := "mpe", value := .subjectAffixesOnVerb }
  , { walsCode := "mak", iso := "myh", value := .subjectCliticsOnVariableHost }
  , { walsCode := "mkd", iso := "kde", value := .subjectAffixesOnVerb }
  , { walsCode := "mua", iso := "mgh", value := .subjectAffixesOnVerb }
  , { walsCode := "mal", iso := "plt", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "mym", iso := "mal", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "mlu", iso := "mgl", value := .subjectAffixesOnVerb }
  , { walsCode := "mlg", iso := "", value := .mixed }
  , { walsCode := "mmw", iso := "mgr", value := .subjectAffixesOnVerb }
  , { walsCode := "mnm", iso := "mva", value := .subjectAffixesOnVerb }
  , { walsCode := "mdn", iso := "mhq", value := .subjectAffixesOnVerb }
  , { walsCode := "mnd", iso := "cmn", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "myi", iso := "mpc", value := .subjectAffixesOnVerb }
  , { walsCode := "mbt", iso := "mdj", value := .subjectAffixesOnVerb }
  , { walsCode := "mgg", iso := "mjg", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "mwb", iso := "mbb", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "mns", iso := "mns", value := .subjectAffixesOnVerb }
  , { walsCode := "mao", iso := "mri", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "map", iso := "arn", value := .subjectAffixesOnVerb }
  , { walsCode := "mra", iso := "mec", value := .subjectAffixesOnVerb }
  , { walsCode := "mku", iso := "zmr", value := .subjectAffixesOnVerb }
  , { walsCode := "mny", iso := "zmc", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "mme", iso := "mhr", value := .subjectAffixesOnVerb }
  , { walsCode := "mar", iso := "mrc", value := .subjectAffixesOnVerb }
  , { walsCode := "mrt", iso := "vma", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "mas", iso := "mcn", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "msl", iso := "mls", value := .subjectAffixesOnVerb }
  , { walsCode := "mtb", iso := "mgw", value := .subjectAffixesOnVerb }
  , { walsCode := "mka", iso := "mxx", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "mau", iso := "mph", value := .subjectAffixesOnVerb }
  , { walsCode := "may", iso := "ayz", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "mzh", iso := "mau", value := .subjectAffixesOnVerb }
  , { walsCode := "mhu", iso := "lnb", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "mbr", iso := "mpk", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "mby", iso := "myb", value := .subjectAffixesOnVerb }
  , { walsCode := "mbl", iso := "mdq", value := .subjectAffixesOnVerb }
  , { walsCode := "mee", iso := "mym", value := .subjectAffixesOnVerb }
  , { walsCode := "meh", iso := "gdq", value := .subjectAffixesOnVerb }
  , { walsCode := "mei", iso := "mni", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "mek", iso := "skf", value := .mixed }
  , { walsCode := "men", iso := "mez", value := .subjectCliticsOnVariableHost }
  , { walsCode := "mea", iso := "mej", value := .subjectAffixesOnVerb }
  , { walsCode := "mpt", iso := "mpt", value := .subjectAffixesOnVerb }
  , { walsCode := "mki", iso := "mik", value := .subjectAffixesOnVerb }
  , { walsCode := "min", iso := "min", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "mir", iso := "mep", value := .subjectAffixesOnVerb }
  , { walsCode := "mss", iso := "skd", value := .subjectAffixesOnVerb }
  , { walsCode := "mxc", iso := "mig", value := .mixed }
  , { walsCode := "miy", iso := "mkf", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "miz", iso := "lus", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "mlm", iso := "mra", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "mcc", iso := "omc", value := .subjectAffixesOnVerb }
  , { walsCode := "mcv", iso := "moc", value := .subjectAffixesOnVerb }
  , { walsCode := "mof", iso := "mif", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "moh", iso := "moh", value := .subjectAffixesOnVerb }
  , { walsCode := "mok", iso := "mkj", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "mon", iso := "mnw", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "mbo", iso := "mxk", value := .subjectAffixesOnVerb }
  , { walsCode := "moo", iso := "mos", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "moe", iso := "myv", value := .subjectAffixesOnVerb }
  , { walsCode := "mro", iso := "mor", value := .subjectAffixesOnVerb }
  , { walsCode := "mou", iso := "mgd", value := .subjectAffixesOnVerb }
  , { walsCode := "mpu", iso := "akc", value := .subjectAffixesOnVerb }
  , { walsCode := "aoj", iso := "aoj", value := .subjectAffixesOnVerb }
  , { walsCode := "msc", iso := "chb", value := .subjectAffixesOnVerb }
  , { walsCode := "mum", iso := "mzm", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "mna", iso := "mnb", value := .subjectAffixesOnVerb }
  , { walsCode := "mun", iso := "unr", value := .subjectCliticsOnVariableHost }
  , { walsCode := "mup", iso := "sur", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "mrl", iso := "mur", value := .subjectAffixesOnVerb }
  , { walsCode := "mgu", iso := "mug", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "mus", iso := "emi", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "mut", iso := "css", value := .subjectCliticsOnVariableHost }
  , { walsCode := "nab", iso := "naf", value := .subjectAffixesOnVerb }
  , { walsCode := "nag", iso := "nce", value := .subjectAffixesOnVerb }
  , { walsCode := "nhh", iso := "", value := .subjectAffixesOnVerb }
  , { walsCode := "nhm", iso := "ncl", value := .subjectAffixesOnVerb }
  , { walsCode := "nhn", iso := "ncj", value := .subjectAffixesOnVerb }
  , { walsCode := "nht", iso := "nhg", value := .subjectAffixesOnVerb }
  , { walsCode := "bio", iso := "bio", value := .subjectAffixesOnVerb }
  , { walsCode := "nak", iso := "nak", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "nal", iso := "nal", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "kho", iso := "naq", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "nmb", iso := "nab", value := .subjectAffixesOnVerb }
  , { walsCode := "nam", iso := "nnm", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "nan", iso := "niq", value := .subjectAffixesOnVerb }
  , { walsCode := "nph", iso := "npa", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "nav", iso := "nav", value := .subjectAffixesOnVerb }
  , { walsCode := "ndb", iso := "nde", value := .subjectAffixesOnVerb }
  , { walsCode := "ndj", iso := "djj", value := .subjectAffixesOnVerb }
  , { walsCode := "ndo", iso := "ndo", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "ndt", iso := "ndv", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "ndy", iso := "djk", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "nnd", iso := "anh", value := .subjectAffixesOnVerb }
  , { walsCode := "ntu", iso := "yrk", value := .subjectAffixesOnVerb }
  , { walsCode := "naj", iso := "aij", value := .subjectAffixesOnVerb }
  , { walsCode := "nwd", iso := "new", value := .subjectAffixesOnVerb }
  , { walsCode := "nez", iso := "nez", value := .subjectAffixesOnVerb }
  , { walsCode := "ntj", iso := "ntj", value := .mixed }
  , { walsCode := "ngj", iso := "nju", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "nga", iso := "nio", value := .subjectAffixesOnVerb }
  , { walsCode := "nbm", iso := "nbm", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "nti", iso := "niy", value := .subjectAffixesOnVerb }
  , { walsCode := "ngi", iso := "wyb", value := .subjectCliticsOnVariableHost }
  , { walsCode := "ngz", iso := "ngi", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "ngo", iso := "ngo", value := .subjectAffixesOnVerb }
  , { walsCode := "nha", iso := "nha", value := .subjectCliticsOnVariableHost }
  , { walsCode := "nia", iso := "nia", value := .mixed }
  , { walsCode := "nsn", iso := "nsz", value := .mixed }
  , { walsCode := "nsg", iso := "ncg", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "niu", iso := "niu", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "niv", iso := "niv", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "nke", iso := "isi", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "nko", iso := "cgg", value := .subjectAffixesOnVerb }
  , { walsCode := "non", iso := "nhu", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "nor", iso := "nor", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "nse", iso := "nse", value := .subjectAffixesOnVerb }
  , { walsCode := "nua", iso := "nxl", value := .subjectAffixesOnVerb }
  , { walsCode := "nbd", iso := "dgl", value := .subjectAffixesOnVerb }
  , { walsCode := "nue", iso := "nus", value := .subjectAffixesOnVerb }
  , { walsCode := "nug", iso := "nuy", value := .subjectAffixesOnVerb }
  , { walsCode := "nuu", iso := "nuk", value := .subjectCliticsOnVariableHost }
  , { walsCode := "nym", iso := "nym", value := .subjectAffixesOnVerb }
  , { walsCode := "nya", iso := "nyt", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "nyn", iso := "nyh", value := .subjectAffixesOnVerb }
  , { walsCode := "nis", iso := "njz", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "nyu", iso := "nyv", value := .subjectAffixesOnVerb }
  , { walsCode := "ood", iso := "ood", value := .subjectCliticsOnVariableHost }
  , { walsCode := "obo", iso := "ann", value := .subjectAffixesOnVerb }
  , { walsCode := "ocu", iso := "ocu", value := .subjectAffixesOnVerb }
  ]

private def allData_1 : List (Datapoint ExpressionOfPronominalSubjects) :=
  [ { walsCode := "obg", iso := "ogu", value := .subjectAffixesOnVerb }
  , { walsCode := "oji", iso := "", value := .subjectCliticsOnVariableHost }
  , { walsCode := "olo", iso := "ong", value := .subjectAffixesOnVerb }
  , { walsCode := "ond", iso := "one", value := .subjectAffixesOnVerb }
  , { walsCode := "oro", iso := "okv", value := .subjectAffixesOnVerb }
  , { walsCode := "orh", iso := "hae", value := .subjectAffixesOnVerb }
  , { walsCode := "ory", iso := "ury", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "osa", iso := "osa", value := .subjectAffixesOnVerb }
  , { walsCode := "otm", iso := "ote", value := .subjectAffixesOnVerb }
  , { walsCode := "pkn", iso := "drl", value := .subjectAffixesOnVerb }
  , { walsCode := "pms", iso := "pma", value := .subjectAffixesOnVerb }
  , { walsCode := "pno", iso := "pao", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "pai", iso := "pwn", value := .subjectAffixesOnVerb }
  , { walsCode := "plk", iso := "plu", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "pam", iso := "pmz", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "pan", iso := "pan", value := .subjectAffixesOnVerb }
  , { walsCode := "pre", iso := "asa", value := .subjectAffixesOnVerb }
  , { walsCode := "psm", iso := "pqm", value := .subjectCliticsOnVariableHost }
  , { walsCode := "plh", iso := "plh", value := .subjectAffixesOnVerb }
  , { walsCode := "pau", iso := "pad", value := .subjectAffixesOnVerb }
  , { walsCode := "pwn", iso := "paw", value := .subjectAffixesOnVerb }
  , { walsCode := "prs", iso := "pes", value := .subjectAffixesOnVerb }
  , { walsCode := "pga", iso := "plg", value := .subjectAffixesOnVerb }
  , { walsCode := "pog", iso := "poy", value := .subjectAffixesOnVerb }
  , { walsCode := "pkt", iso := "pko", value := .subjectAffixesOnVerb }
  , { walsCode := "pol", iso := "pol", value := .subjectCliticsOnVariableHost }
  , { walsCode := "pso", iso := "pom", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "por", iso := "por", value := .subjectAffixesOnVerb }
  , { walsCode := "pra", iso := "prn", value := .subjectAffixesOnVerb }
  , { walsCode := "pul", iso := "puw", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "pae", iso := "pbb", value := .subjectCliticsOnVariableHost }
  , { walsCode := "qim", iso := "qvi", value := .subjectAffixesOnVerb }
  , { walsCode := "ram", iso := "rma", value := .subjectAffixesOnVerb }
  , { walsCode := "rap", iso := "rap", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "rem", iso := "bfw", value := .subjectAffixesOnVerb }
  , { walsCode := "rim", iso := "rim", value := .subjectAffixesOnVerb }
  , { walsCode := "rit", iso := "rit", value := .subjectCliticsOnVariableHost }
  , { walsCode := "ron", iso := "cla", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "rov", iso := "rug", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "ruk", iso := "dru", value := .subjectAffixesOnVerb }
  , { walsCode := "rum", iso := "klq", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "run", iso := "rou", value := .subjectAffixesOnVerb }
  , { walsCode := "rny", iso := "nyn", value := .subjectAffixesOnVerb }
  , { walsCode := "rru", iso := "nyo", value := .subjectAffixesOnVerb }
  , { walsCode := "rus", iso := "rus", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "rut", iso := "rut", value := .subjectAffixesOnVerb }
  , { walsCode := "sah", iso := "saj", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "sak", iso := "sku", value := .subjectAffixesOnVerb }
  , { walsCode := "slb", iso := "sbe", value := .subjectAffixesOnVerb }
  , { walsCode := "sdw", iso := "sad", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "san", iso := "sag", value := .subjectAffixesOnVerb }
  , { walsCode := "sgu", iso := "snq", value := .subjectAffixesOnVerb }
  , { walsCode := "snm", iso := "xsu", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "sap", iso := "spu", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "src", iso := "srs", value := .subjectAffixesOnVerb }
  , { walsCode := "sar", iso := "dju", value := .subjectAffixesOnVerb }
  , { walsCode := "skp", iso := "sel", value := .subjectAffixesOnVerb }
  , { walsCode := "sml", iso := "sza", value := .subjectAffixesOnVerb }
  , { walsCode := "sgl", iso := "szg", value := .subjectAffixesOnVerb }
  , { walsCode := "scr", iso := "hbs", value := .subjectAffixesOnVerb }
  , { walsCode := "ser", iso := "sei", value := .subjectAffixesOnVerb }
  , { walsCode := "ses", iso := "sot", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "shm", iso := "ksb", value := .subjectAffixesOnVerb }
  , { walsCode := "shu", iso := "shs", value := .subjectAffixesOnVerb }
  , { walsCode := "sid", iso := "sid", value := .subjectAffixesOnVerb }
  , { walsCode := "sio", iso := "xsi", value := .subjectAffixesOnVerb }
  , { walsCode := "qum", iso := "qum", value := .subjectAffixesOnVerb }
  , { walsCode := "sro", iso := "ssd", value := .subjectAffixesOnVerb }
  , { walsCode := "sis", iso := "baa", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "siu", iso := "sis", value := .subjectAffixesOnVerb }
  , { walsCode := "sla", iso := "den", value := .subjectAffixesOnVerb }
  , { walsCode := "slo", iso := "slv", value := .subjectAffixesOnVerb }
  , { walsCode := "so", iso := "teu", value := .subjectAffixesOnVerb }
  , { walsCode := "sob", iso := "sob", value := .subjectAffixesOnVerb }
  , { walsCode := "som", iso := "som", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "snn", iso := "snk", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "srb", iso := "", value := .subjectAffixesOnVerb }
  , { walsCode := "stn", iso := "nso", value := .subjectAffixesOnVerb }
  , { walsCode := "sgb", iso := "mnx", value := .subjectAffixesOnVerb }
  , { walsCode := "spa", iso := "spa", value := .subjectAffixesOnVerb }
  , { walsCode := "squ", iso := "squ", value := .subjectAffixesOnVerb }
  , { walsCode := "sue", iso := "sue", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "skm", iso := "suk", value := .subjectAffixesOnVerb }
  , { walsCode := "sul", iso := "sua", value := .subjectAffixesOnVerb }
  , { walsCode := "sup", iso := "spp", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "swa", iso := "swh", value := .subjectAffixesOnVerb }
  , { walsCode := "swe", iso := "swe", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "tab", iso := "mky", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "tbl", iso := "tnm", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "tbw", iso := "tap", value := .subjectAffixesOnVerb }
  , { walsCode := "taf", iso := "sps", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "trr", iso := "tbg", value := .subjectAffixesOnVerb }
  , { walsCode := "taj", iso := "tgk", value := .subjectAffixesOnVerb }
  , { walsCode := "tkl", iso := "tkm", value := .subjectAffixesOnVerb }
  , { walsCode := "tsk", iso := "taq", value := .subjectAffixesOnVerb }
  , { walsCode := "tnc", iso := "tcb", value := .subjectAffixesOnVerb }
  , { walsCode := "tar", iso := "tae", value := .subjectAffixesOnVerb }
  , { walsCode := "tvo", iso := "tat", value := .subjectAffixesOnVerb }
  , { walsCode := "tau", iso := "tya", value := .subjectAffixesOnVerb }
  , { walsCode := "tmr", iso := "tea", value := .subjectAffixesOnVerb }
  , { walsCode := "ten", iso := "tex", value := .subjectAffixesOnVerb }
  , { walsCode := "tep", iso := "tpt", value := .subjectAffixesOnVerb }
  , { walsCode := "tpn", iso := "ntp", value := .mixed }
  , { walsCode := "tps", iso := "stp", value := .subjectAffixesOnVerb }
  , { walsCode := "trb", iso := "tfr", value := .subjectAffixesOnVerb }
  , { walsCode := "tes", iso := "teo", value := .subjectAffixesOnVerb }
  , { walsCode := "tet", iso := "tll", value := .subjectAffixesOnVerb }
  , { walsCode := "tha", iso := "tha", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "tid", iso := "tvo", value := .mixed }
  , { walsCode := "tgk", iso := "tgc", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "tgr", iso := "tig", value := .subjectAffixesOnVerb }
  , { walsCode := "tja", iso := "dih", value := .subjectAffixesOnVerb }
  , { walsCode := "tmc", iso := "tjm", value := .subjectAffixesOnVerb }
  , { walsCode := "tim", iso := "tih", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "tin", iso := "cir", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "tiv", iso := "tiv", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "tiw", iso := "tiw", value := .subjectAffixesOnVerb }
  , { walsCode := "tli", iso := "tli", value := .subjectAffixesOnVerb }
  , { walsCode := "tob", iso := "tob", value := .subjectAffixesOnVerb }
  , { walsCode := "tlo", iso := "tlb", value := .subjectAffixesOnVerb }
  , { walsCode := "tla", iso := "ksd", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "toz", iso := "toi", value := .subjectAffixesOnVerb }
  , { walsCode := "ton", iso := "tqw", value := .subjectAffixesOnVerb }
  , { walsCode := "tru", iso := "tpy", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "tsz", iso := "ddo", value := .subjectAffixesOnVerb }
  , { walsCode := "tsi", iso := "tsi", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "tsn", iso := "tso", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "tgh", iso := "thv", value := .subjectAffixesOnVerb }
  , { walsCode := "tgn", iso := "tzn", value := .subjectAffixesOnVerb }
  , { walsCode := "tuk", iso := "", value := .subjectAffixesOnVerb }
  , { walsCode := "tki", iso := "bag", value := .subjectAffixesOnVerb }
  , { walsCode := "tnk", iso := "lcm", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "tun", iso := "tun", value := .subjectAffixesOnVerb }
  , { walsCode := "tna", iso := "tuv", value := .subjectAffixesOnVerb }
  , { walsCode := "tur", iso := "tur", value := .subjectAffixesOnVerb }
  , { walsCode := "tkm", iso := "tuk", value := .subjectAffixesOnVerb }
  , { walsCode := "tus", iso := "tus", value := .subjectAffixesOnVerb }
  , { walsCode := "tte", iso := "tta", value := .subjectAffixesOnVerb }
  , { walsCode := "tvt", iso := "tvt", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "tuv", iso := "tyv", value := .subjectAffixesOnVerb }
  , { walsCode := "uby", iso := "uby", value := .subjectAffixesOnVerb }
  , { walsCode := "udm", iso := "udm", value := .subjectAffixesOnVerb }
  , { walsCode := "ukr", iso := "ukr", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "uld", iso := "udl", value := .subjectAffixesOnVerb }
  , { walsCode := "una", iso := "mtg", value := .subjectAffixesOnVerb }
  , { walsCode := "ung", iso := "ung", value := .subjectAffixesOnVerb }
  , { walsCode := "ura", iso := "uur", value := .subjectAffixesOnVerb }
  , { walsCode := "uhi", iso := "urf", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "url", iso := "urk", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "urn", iso := "ura", value := .subjectAffixesOnVerb }
  , { walsCode := "urk", iso := "urb", value := .subjectAffixesOnVerb }
  , { walsCode := "usa", iso := "wnu", value := .subjectAffixesOnVerb }
  , { walsCode := "usr", iso := "usa", value := .subjectAffixesOnVerb }
  , { walsCode := "ute", iso := "ute", value := .subjectCliticsOnVariableHost }
  , { walsCode := "uyg", iso := "uig", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "uzb", iso := "", value := .subjectAffixesOnVerb }
  , { walsCode := "vai", iso := "vai", value := .obligatoryPronounsInSubjectPosition }
  , { walsCode := "ven", iso := "ven", value := .subjectAffixesOnVerb }
  , { walsCode := "vie", iso := "vie", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "wai", iso := "waw", value := .subjectAffixesOnVerb }
  , { walsCode := "wal", iso := "van", value := .subjectAffixesOnVerb }
  , { walsCode := "wlm", iso := "wmt", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "wam", iso := "wmb", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "wry", iso := "wrz", value := .subjectAffixesOnVerb }
  , { walsCode := "wrd", iso := "wrr", value := .subjectAffixesOnVerb }
  , { walsCode := "wrk", iso := "gae", value := .subjectAffixesOnVerb }
  , { walsCode := "wrm", iso := "wsa", value := .subjectAffixesOnVerb }
  , { walsCode := "war", iso := "pav", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "wrl", iso := "wbp", value := .subjectCliticsOnVariableHost }
  , { walsCode := "wrg", iso := "wgy", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "wrb", iso := "gjm", value := .subjectCliticsOnVariableHost }
  , { walsCode := "wrw", iso := "wwr", value := .subjectAffixesOnVerb }
  , { walsCode := "was", iso := "was", value := .subjectAffixesOnVerb }
  , { walsCode := "wth", iso := "wth", value := .subjectCliticsOnVariableHost }
  , { walsCode := "wat", iso := "wbv", value := .subjectCliticsOnVariableHost }
  , { walsCode := "way", iso := "oym", value := .subjectAffixesOnVerb }
  , { walsCode := "wed", iso := "wed", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "wma", iso := "mqs", value := .subjectAffixesOnVerb }
  , { walsCode := "wic", iso := "wic", value := .subjectAffixesOnVerb }
  , { walsCode := "wir", iso := "wgu", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "wiy", iso := "wiy", value := .subjectAffixesOnVerb }
  , { walsCode := "wol", iso := "woe", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "wlf", iso := "wol", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "wya", iso := "wya", value := .subjectAffixesOnVerb }
  , { walsCode := "xho", iso := "xho", value := .subjectPronounsInDifferentPosition }
  , { walsCode := "ygr", iso := "ygr", value := .subjectAffixesOnVerb }
  , { walsCode := "yag", iso := "yad", value := .subjectCliticsOnVariableHost }
  , { walsCode := "yah", iso := "yag", value := .mixed }
  , { walsCode := "yal", iso := "kkl", value := .subjectAffixesOnVerb }
  , { walsCode := "yao", iso := "yao", value := .subjectAffixesOnVerb }
  , { walsCode := "yaq", iso := "yaq", value := .mixed }
  , { walsCode := "yar", iso := "yrb", value := .subjectAffixesOnVerb }
  , { walsCode := "ywl", iso := "yok", value := .subjectAffixesOnVerb }
  , { walsCode := "yel", iso := "yle", value := .subjectAffixesOnVerb }
  , { walsCode := "yid", iso := "yii", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "yim", iso := "yee", value := .subjectAffixesOnVerb }
  , { walsCode := "yin", iso := "yij", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "yng", iso := "yia", value := .subjectCliticsOnVariableHost }
  , { walsCode := "yor", iso := "yor", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "yuc", iso := "yuc", value := .subjectAffixesOnVerb }
  , { walsCode := "yko", iso := "yux", value := .subjectAffixesOnVerb }
  , { walsCode := "yuk", iso := "gcd", value := .subjectCliticsOnVariableHost }
  , { walsCode := "ypk", iso := "esu", value := .subjectAffixesOnVerb }
  , { walsCode := "yur", iso := "yur", value := .subjectAffixesOnVerb }
  , { walsCode := "yuw", iso := "kld", value := .optionalPronounsInSubjectPosition }
  , { walsCode := "zai", iso := "zai", value := .subjectAffixesOnVerb }
  , { walsCode := "zap", iso := "zaw", value := .subjectAffixesOnVerb }
  , { walsCode := "zay", iso := "zay", value := .subjectAffixesOnVerb }
  , { walsCode := "zqc", iso := "zoc", value := .subjectAffixesOnVerb }
  , { walsCode := "zul", iso := "zul", value := .subjectAffixesOnVerb }
  , { walsCode := "eme", iso := "eme", value := .subjectAffixesOnVerb }
  ]

/-- Complete WALS 101A dataset (711 languages). -/
def allData : List (Datapoint ExpressionOfPronominalSubjects) := allData_0 ++ allData_1

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F101A
