import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 105A: Ditransitive Constructions: The Verb 'Give'
@cite{wals-2013}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 105A`.

Chapter 105, 378 languages.
-/

namespace Core.WALS.F105A

/-- WALS 105A values. -/
inductive DitransitiveConstructionsTheVerbGive where
  /-- Indirect-object construction (189 languages). -/
  | indirectObjectConstruction
  /-- Double-object construction (84 languages). -/
  | doubleObjectConstruction
  /-- Secondary-object construction (65 languages). -/
  | secondaryObjectConstruction
  /-- Mixed (40 languages). -/
  | mixed
  deriving DecidableEq, BEq, Repr

/-- Complete WALS 105A dataset (378 languages). -/
def allData : List (Datapoint DitransitiveConstructionsTheVerbGive) :=
  [ { walsCode := "xam", iso := "xam", value := .doubleObjectConstruction }
  , { walsCode := "abk", iso := "abk", value := .indirectObjectConstruction }
  , { walsCode := "abu", iso := "kgr", value := .indirectObjectConstruction }
  , { walsCode := "ace", iso := "ace", value := .mixed }
  , { walsCode := "ain", iso := "ain", value := .secondaryObjectConstruction }
  , { walsCode := "akn", iso := "aka", value := .doubleObjectConstruction }
  , { walsCode := "akw", iso := "ake", value := .secondaryObjectConstruction }
  , { walsCode := "akh", iso := "ahk", value := .indirectObjectConstruction }
  , { walsCode := "all", iso := "nrz", value := .secondaryObjectConstruction }
  , { walsCode := "ala", iso := "amp", value := .secondaryObjectConstruction }
  , { walsCode := "ale", iso := "ale", value := .indirectObjectConstruction }
  , { walsCode := "aly", iso := "aly", value := .mixed }
  , { walsCode := "aml", iso := "omb", value := .indirectObjectConstruction }
  , { walsCode := "ame", iso := "aey", value := .indirectObjectConstruction }
  , { walsCode := "amh", iso := "amh", value := .doubleObjectConstruction }
  , { walsCode := "ano", iso := "nun", value := .indirectObjectConstruction }
  , { walsCode := "apu", iso := "apu", value := .mixed }
  , { walsCode := "aeg", iso := "arz", value := .mixed }
  , { walsCode := "ana", iso := "aro", value := .doubleObjectConstruction }
  , { walsCode := "alk", iso := "apr", value := .indirectObjectConstruction }
  , { walsCode := "amp", iso := "aer", value := .mixed }
  , { walsCode := "awp", iso := "kwi", value := .indirectObjectConstruction }
  , { walsCode := "bab", iso := "bav", value := .mixed }
  , { walsCode := "bdm", iso := "bia", value := .indirectObjectConstruction }
  , { walsCode := "bag", iso := "bmi", value := .indirectObjectConstruction }
  , { walsCode := "bai", iso := "bca", value := .indirectObjectConstruction }
  , { walsCode := "baj", iso := "bdl", value := .doubleObjectConstruction }
  , { walsCode := "bak", iso := "bkc", value := .indirectObjectConstruction }
  , { walsCode := "bnn", iso := "bcm", value := .secondaryObjectConstruction }
  , { walsCode := "brs", iso := "bsn", value := .secondaryObjectConstruction }
  , { walsCode := "bae", iso := "bae", value := .indirectObjectConstruction }
  , { walsCode := "bsq", iso := "eus", value := .indirectObjectConstruction }
  , { walsCode := "bzi", iso := "bvz", value := .indirectObjectConstruction }
  , { walsCode := "baw", iso := "bgr", value := .mixed }
  , { walsCode := "bel", iso := "byw", value := .secondaryObjectConstruction }
  , { walsCode := "bco", iso := "blc", value := .secondaryObjectConstruction }
  , { walsCode := "bfg", iso := "grr", value := .indirectObjectConstruction }
  , { walsCode := "bma", iso := "tzm", value := .indirectObjectConstruction }
  , { walsCode := "ber", iso := "wti", value := .indirectObjectConstruction }
  , { walsCode := "bho", iso := "bho", value := .indirectObjectConstruction }
  , { walsCode := "bbw", iso := "gup", value := .secondaryObjectConstruction }
  , { walsCode := "bii", iso := "bzr", value := .indirectObjectConstruction }
  , { walsCode := "biu", iso := "", value := .indirectObjectConstruction }
  , { walsCode := "bla", iso := "bla", value := .secondaryObjectConstruction }
  , { walsCode := "boz", iso := "boz", value := .indirectObjectConstruction }
  , { walsCode := "bkt", iso := "bkk", value := .indirectObjectConstruction }
  , { walsCode := "bum", iso := "tkw", value := .indirectObjectConstruction }
  , { walsCode := "but", iso := "bxm", value := .indirectObjectConstruction }
  , { walsCode := "brm", iso := "mya", value := .doubleObjectConstruction }
  , { walsCode := "bur", iso := "bsk", value := .indirectObjectConstruction }
  , { walsCode := "bya", iso := "bee", value := .indirectObjectConstruction }
  , { walsCode := "cnl", iso := "ram", value := .indirectObjectConstruction }
  , { walsCode := "cnt", iso := "yue", value := .mixed }
  , { walsCode := "cha", iso := "cha", value := .secondaryObjectConstruction }
  , { walsCode := "chn", iso := "chx", value := .indirectObjectConstruction }
  , { walsCode := "che", iso := "chr", value := .secondaryObjectConstruction }
  , { walsCode := "cct", iso := "cho", value := .indirectObjectConstruction }
  , { walsCode := "chr", iso := "crw", value := .indirectObjectConstruction }
  , { walsCode := "chk", iso := "ckt", value := .indirectObjectConstruction }
  , { walsCode := "cmn", iso := "com", value := .doubleObjectConstruction }
  , { walsCode := "coo", iso := "csz", value := .secondaryObjectConstruction }
  , { walsCode := "cop", iso := "cop", value := .indirectObjectConstruction }
  , { walsCode := "cre", iso := "crk", value := .secondaryObjectConstruction }
  , { walsCode := "dga", iso := "dga", value := .doubleObjectConstruction }
  , { walsCode := "dgb", iso := "dag", value := .doubleObjectConstruction }
  , { walsCode := "dah", iso := "dal", value := .doubleObjectConstruction }
  , { walsCode := "drg", iso := "dar", value := .indirectObjectConstruction }
  , { walsCode := "dhb", iso := "xgm", value := .doubleObjectConstruction }
  , { walsCode := "dhi", iso := "div", value := .indirectObjectConstruction }
  , { walsCode := "dja", iso := "dyy", value := .indirectObjectConstruction }
  , { walsCode := "djr", iso := "ddj", value := .mixed }
  , { walsCode := "dji", iso := "jig", value := .mixed }
  , { walsCode := "doy", iso := "dow", value := .doubleObjectConstruction }
  , { walsCode := "dre", iso := "dhv", value := .mixed }
  , { walsCode := "dua", iso := "dua", value := .doubleObjectConstruction }
  , { walsCode := "dug", iso := "gwd", value := .indirectObjectConstruction }
  , { walsCode := "dyi", iso := "dbl", value := .mixed }
  , { walsCode := "efi", iso := "efi", value := .doubleObjectConstruction }
  , { walsCode := "eng", iso := "eng", value := .mixed }
  , { walsCode := "epe", iso := "sja", value := .indirectObjectConstruction }
  , { walsCode := "err", iso := "erg", value := .secondaryObjectConstruction }
  , { walsCode := "eve", iso := "evn", value := .indirectObjectConstruction }
  , { walsCode := "ewo", iso := "ewo", value := .doubleObjectConstruction }
  , { walsCode := "fij", iso := "fij", value := .indirectObjectConstruction }
  , { walsCode := "fin", iso := "fin", value := .indirectObjectConstruction }
  , { walsCode := "fon", iso := "fon", value := .doubleObjectConstruction }
  , { walsCode := "fre", iso := "fra", value := .indirectObjectConstruction }
  , { walsCode := "fye", iso := "pym", value := .doubleObjectConstruction }
  , { walsCode := "gaa", iso := "gbu", value := .secondaryObjectConstruction }
  , { walsCode := "gam", iso := "gmv", value := .indirectObjectConstruction }
  , { walsCode := "gap", iso := "pwg", value := .secondaryObjectConstruction }
  , { walsCode := "gar", iso := "grt", value := .indirectObjectConstruction }
  , { walsCode := "geo", iso := "kat", value := .indirectObjectConstruction }
  , { walsCode := "ger", iso := "deu", value := .indirectObjectConstruction }
  , { walsCode := "gol", iso := "gol", value := .doubleObjectConstruction }
  , { walsCode := "goo", iso := "gni", value := .secondaryObjectConstruction }
  , { walsCode := "grb", iso := "grj", value := .doubleObjectConstruction }
  , { walsCode := "grk", iso := "ell", value := .indirectObjectConstruction }
  , { walsCode := "grw", iso := "kal", value := .secondaryObjectConstruction }
  , { walsCode := "gua", iso := "gug", value := .indirectObjectConstruction }
  , { walsCode := "gdf", iso := "gdf", value := .indirectObjectConstruction }
  , { walsCode := "gum", iso := "kgs", value := .doubleObjectConstruction }
  , { walsCode := "grg", iso := "gge", value := .secondaryObjectConstruction }
  , { walsCode := "guu", iso := "kky", value := .indirectObjectConstruction }
  , { walsCode := "hai", iso := "hai", value := .indirectObjectConstruction }
  , { walsCode := "hli", iso := "hur", value := .secondaryObjectConstruction }
  , { walsCode := "hat", iso := "had", value := .indirectObjectConstruction }
  , { walsCode := "hau", iso := "hau", value := .secondaryObjectConstruction }
  , { walsCode := "hay", iso := "vay", value := .secondaryObjectConstruction }
  , { walsCode := "hdi", iso := "xed", value := .doubleObjectConstruction }
  , { walsCode := "heb", iso := "heb", value := .indirectObjectConstruction }
  , { walsCode := "hin", iso := "hin", value := .indirectObjectConstruction }
  , { walsCode := "hix", iso := "hix", value := .indirectObjectConstruction }
  , { walsCode := "hma", iso := "hmr", value := .mixed }
  , { walsCode := "hmo", iso := "hnj", value := .indirectObjectConstruction }
  , { walsCode := "hoa", iso := "hoa", value := .mixed }
  , { walsCode := "hui", iso := "hch", value := .secondaryObjectConstruction }
  , { walsCode := "hun", iso := "hun", value := .indirectObjectConstruction }
  , { walsCode := "hzb", iso := "huz", value := .indirectObjectConstruction }
  , { walsCode := "igb", iso := "ibo", value := .doubleObjectConstruction }
  , { walsCode := "ik", iso := "ikx", value := .indirectObjectConstruction }
  , { walsCode := "ika", iso := "arh", value := .mixed }
  , { walsCode := "imo", iso := "imn", value := .indirectObjectConstruction }
  , { walsCode := "ind", iso := "ind", value := .mixed }
  , { walsCode := "ing", iso := "inh", value := .indirectObjectConstruction }
  , { walsCode := "irq", iso := "irk", value := .indirectObjectConstruction }
  , { walsCode := "ita", iso := "ita", value := .indirectObjectConstruction }
  , { walsCode := "itz", iso := "itz", value := .indirectObjectConstruction }
  , { walsCode := "jab", iso := "jae", value := .indirectObjectConstruction }
  , { walsCode := "jak", iso := "jac", value := .indirectObjectConstruction }
  , { walsCode := "jam", iso := "djd", value := .secondaryObjectConstruction }
  , { walsCode := "jpn", iso := "jpn", value := .indirectObjectConstruction }
  , { walsCode := "jel", iso := "jek", value := .indirectObjectConstruction }
  , { walsCode := "jng", iso := "kac", value := .indirectObjectConstruction }
  , { walsCode := "juh", iso := "ktz", value := .secondaryObjectConstruction }
  , { walsCode := "krr", iso := "kxa", value := .secondaryObjectConstruction }
  , { walsCode := "kly", iso := "mwp", value := .indirectObjectConstruction }
  , { walsCode := "kgu", iso := "ktg", value := .mixed }
  , { walsCode := "kma", iso := "kay", value := .indirectObjectConstruction }
  , { walsCode := "kan", iso := "ogo", value := .doubleObjectConstruction }
  , { walsCode := "knd", iso := "kan", value := .indirectObjectConstruction }
  , { walsCode := "knr", iso := "knc", value := .indirectObjectConstruction }
  , { walsCode := "kas", iso := "kas", value := .indirectObjectConstruction }
  , { walsCode := "kyl", iso := "eky", value := .doubleObjectConstruction }
  , { walsCode := "kem", iso := "ahg", value := .indirectObjectConstruction }
  , { walsCode := "ker", iso := "ker", value := .indirectObjectConstruction }
  , { walsCode := "ket", iso := "ket", value := .doubleObjectConstruction }
  , { walsCode := "kha", iso := "khk", value := .indirectObjectConstruction }
  , { walsCode := "kmh", iso := "kjl", value := .secondaryObjectConstruction }
  , { walsCode := "kty", iso := "kca", value := .mixed }
  , { walsCode := "khs", iso := "kha", value := .indirectObjectConstruction }
  , { walsCode := "khm", iso := "khm", value := .mixed }
  , { walsCode := "kmu", iso := "kjg", value := .indirectObjectConstruction }
  , { walsCode := "kik", iso := "kik", value := .doubleObjectConstruction }
  , { walsCode := "klv", iso := "kij", value := .secondaryObjectConstruction }
  , { walsCode := "kin", iso := "kin", value := .doubleObjectConstruction }
  , { walsCode := "krb", iso := "gil", value := .doubleObjectConstruction }
  , { walsCode := "kis", iso := "kss", value := .doubleObjectConstruction }
  , { walsCode := "klm", iso := "kla", value := .indirectObjectConstruction }
  , { walsCode := "koa", iso := "cku", value := .indirectObjectConstruction }
  , { walsCode := "kob", iso := "kpw", value := .doubleObjectConstruction }
  , { walsCode := "kod", iso := "kfa", value := .indirectObjectConstruction }
  , { walsCode := "kmb", iso := "", value := .mixed }
  , { walsCode := "kda", iso := "kfc", value := .indirectObjectConstruction }
  , { walsCode := "kon", iso := "kng", value := .mixed }
  , { walsCode := "kor", iso := "kor", value := .indirectObjectConstruction }
  , { walsCode := "kku", iso := "kfq", value := .doubleObjectConstruction }
  , { walsCode := "kfe", iso := "kfz", value := .secondaryObjectConstruction }
  , { walsCode := "kse", iso := "ses", value := .mixed }
  , { walsCode := "kro", iso := "kgo", value := .indirectObjectConstruction }
  , { walsCode := "knc", iso := "uwa", value := .indirectObjectConstruction }
  , { walsCode := "kya", iso := "gvn", value := .indirectObjectConstruction }
  , { walsCode := "kuk", iso := "bfa", value := .doubleObjectConstruction }
  , { walsCode := "knm", iso := "kun", value := .indirectObjectConstruction }
  , { walsCode := "kug", iso := "cmn", value := .doubleObjectConstruction }
  , { walsCode := "kut", iso := "kut", value := .secondaryObjectConstruction }
  , { walsCode := "kwa", iso := "kwd", value := .indirectObjectConstruction }
  , { walsCode := "lad", iso := "lbj", value := .indirectObjectConstruction }
  , { walsCode := "lai", iso := "cnh", value := .secondaryObjectConstruction }
  , { walsCode := "lak", iso := "lbe", value := .indirectObjectConstruction }
  , { walsCode := "lkt", iso := "lkt", value := .doubleObjectConstruction }
  , { walsCode := "lan", iso := "laj", value := .mixed }
  , { walsCode := "lat", iso := "lav", value := .indirectObjectConstruction }
  , { walsCode := "lav", iso := "lvk", value := .indirectObjectConstruction }
  , { walsCode := "laz", iso := "lzz", value := .secondaryObjectConstruction }
  , { walsCode := "lel", iso := "lln", value := .doubleObjectConstruction }
  , { walsCode := "lep", iso := "lep", value := .indirectObjectConstruction }
  , { walsCode := "lez", iso := "lez", value := .indirectObjectConstruction }
  , { walsCode := "lil", iso := "lil", value := .secondaryObjectConstruction }
  , { walsCode := "lml", iso := "lmc", value := .secondaryObjectConstruction }
  , { walsCode := "lin", iso := "lin", value := .doubleObjectConstruction }
  , { walsCode := "lis", iso := "lis", value := .indirectObjectConstruction }
  , { walsCode := "ara", iso := "arw", value := .indirectObjectConstruction }
  , { walsCode := "lgu", iso := "lgu", value := .indirectObjectConstruction }
  , { walsCode := "lbu", iso := "lun", value := .doubleObjectConstruction }
  , { walsCode := "mad", iso := "mhi", value := .indirectObjectConstruction }
  , { walsCode := "mle", iso := "mdy", value := .indirectObjectConstruction }
  , { walsCode := "mac", iso := "mbc", value := .indirectObjectConstruction }
  , { walsCode := "mdr", iso := "mad", value := .indirectObjectConstruction }
  , { walsCode := "mpr", iso := "", value := .indirectObjectConstruction }
  , { walsCode := "mai", iso := "mai", value := .indirectObjectConstruction }
  , { walsCode := "mak", iso := "myh", value := .doubleObjectConstruction }
  , { walsCode := "mym", iso := "mal", value := .indirectObjectConstruction }
  , { walsCode := "mlt", iso := "mlt", value := .indirectObjectConstruction }
  , { walsCode := "mam", iso := "mam", value := .indirectObjectConstruction }
  , { walsCode := "mnd", iso := "cmn", value := .mixed }
  , { walsCode := "myi", iso := "mpc", value := .doubleObjectConstruction }
  , { walsCode := "mgg", iso := "mjg", value := .indirectObjectConstruction }
  , { walsCode := "mao", iso := "mri", value := .indirectObjectConstruction }
  , { walsCode := "map", iso := "arn", value := .secondaryObjectConstruction }
  , { walsCode := "mku", iso := "zmr", value := .doubleObjectConstruction }
  , { walsCode := "mhi", iso := "mar", value := .indirectObjectConstruction }
  , { walsCode := "mar", iso := "mrc", value := .secondaryObjectConstruction }
  , { walsCode := "mrq", iso := "", value := .doubleObjectConstruction }
  , { walsCode := "mrt", iso := "vma", value := .secondaryObjectConstruction }
  , { walsCode := "mts", iso := "mpq", value := .doubleObjectConstruction }
  , { walsCode := "myr", iso := "mcf", value := .doubleObjectConstruction }
  , { walsCode := "may", iso := "ayz", value := .mixed }
  , { walsCode := "mbb", iso := "vmb", value := .indirectObjectConstruction }
  , { walsCode := "mby", iso := "myb", value := .doubleObjectConstruction }
  , { walsCode := "mbi", iso := "baw", value := .indirectObjectConstruction }
  , { walsCode := "mei", iso := "mni", value := .indirectObjectConstruction }
  , { walsCode := "mde", iso := "men", value := .mixed }
  , { walsCode := "mxc", iso := "mig", value := .indirectObjectConstruction }
  , { walsCode := "miy", iso := "mkf", value := .doubleObjectConstruction }
  , { walsCode := "mlm", iso := "mra", value := .doubleObjectConstruction }
  , { walsCode := "mcv", iso := "moc", value := .mixed }
  , { walsCode := "mno", iso := "mnr", value := .doubleObjectConstruction }
  , { walsCode := "mbo", iso := "mxk", value := .indirectObjectConstruction }
  , { walsCode := "mos", iso := "cas", value := .secondaryObjectConstruction }
  , { walsCode := "mot", iso := "siw", value := .secondaryObjectConstruction }
  , { walsCode := "mdg", iso := "mua", value := .indirectObjectConstruction }
  , { walsCode := "mup", iso := "sur", value := .indirectObjectConstruction }
  , { walsCode := "mrl", iso := "mur", value := .doubleObjectConstruction }
  , { walsCode := "mgu", iso := "mug", value := .indirectObjectConstruction }
  , { walsCode := "mus", iso := "emi", value := .indirectObjectConstruction }
  , { walsCode := "nab", iso := "naf", value := .secondaryObjectConstruction }
  , { walsCode := "nag", iso := "nce", value := .indirectObjectConstruction }
  , { walsCode := "nht", iso := "nhg", value := .doubleObjectConstruction }
  , { walsCode := "kho", iso := "naq", value := .doubleObjectConstruction }
  , { walsCode := "nmb", iso := "nab", value := .secondaryObjectConstruction }
  , { walsCode := "ndb", iso := "nde", value := .doubleObjectConstruction }
  , { walsCode := "ndj", iso := "djj", value := .secondaryObjectConstruction }
  , { walsCode := "nep", iso := "npi", value := .indirectObjectConstruction }
  , { walsCode := "nwd", iso := "new", value := .indirectObjectConstruction }
  , { walsCode := "ngl", iso := "nig", value := .secondaryObjectConstruction }
  , { walsCode := "ngi", iso := "wyb", value := .secondaryObjectConstruction }
  , { walsCode := "nha", iso := "nha", value := .doubleObjectConstruction }
  , { walsCode := "nia", iso := "nia", value := .indirectObjectConstruction }
  , { walsCode := "nsg", iso := "ncg", value := .indirectObjectConstruction }
  , { walsCode := "niu", iso := "niu", value := .indirectObjectConstruction }
  , { walsCode := "niv", iso := "niv", value := .secondaryObjectConstruction }
  , { walsCode := "nko", iso := "cgg", value := .secondaryObjectConstruction }
  , { walsCode := "nse", iso := "nse", value := .doubleObjectConstruction }
  , { walsCode := "nua", iso := "nxl", value := .indirectObjectConstruction }
  , { walsCode := "nbd", iso := "dgl", value := .indirectObjectConstruction }
  , { walsCode := "nku", iso := "xnz", value := .doubleObjectConstruction }
  , { walsCode := "nuu", iso := "nuk", value := .doubleObjectConstruction }
  , { walsCode := "ood", iso := "ood", value := .doubleObjectConstruction }
  , { walsCode := "obo", iso := "ann", value := .doubleObjectConstruction }
  , { walsCode := "oji", iso := "", value := .secondaryObjectConstruction }
  , { walsCode := "olu", iso := "plo", value := .mixed }
  , { walsCode := "orh", iso := "hae", value := .indirectObjectConstruction }
  , { walsCode := "ory", iso := "ury", value := .indirectObjectConstruction }
  , { walsCode := "pms", iso := "pma", value := .indirectObjectConstruction }
  , { walsCode := "pta", iso := "duf", value := .indirectObjectConstruction }
  , { walsCode := "pai", iso := "pwn", value := .mixed }
  , { walsCode := "pal", iso := "pau", value := .secondaryObjectConstruction }
  , { walsCode := "pny", iso := "pnw", value := .doubleObjectConstruction }
  , { walsCode := "ptt", iso := "lae", value := .indirectObjectConstruction }
  , { walsCode := "per", iso := "pip", value := .indirectObjectConstruction }
  , { walsCode := "prs", iso := "pes", value := .indirectObjectConstruction }
  , { walsCode := "pga", iso := "plg", value := .doubleObjectConstruction }
  , { walsCode := "prh", iso := "myp", value := .doubleObjectConstruction }
  , { walsCode := "pit", iso := "pjt", value := .doubleObjectConstruction }
  , { walsCode := "ppi", iso := "pit", value := .doubleObjectConstruction }
  , { walsCode := "pur", iso := "tsz", value := .indirectObjectConstruction }
  , { walsCode := "pae", iso := "pbb", value := .indirectObjectConstruction }
  , { walsCode := "qaf", iso := "aar", value := .indirectObjectConstruction }
  , { walsCode := "qia", iso := "", value := .indirectObjectConstruction }
  , { walsCode := "qhu", iso := "qub", value := .secondaryObjectConstruction }
  , { walsCode := "qim", iso := "qvi", value := .indirectObjectConstruction }
  , { walsCode := "rap", iso := "rap", value := .indirectObjectConstruction }
  , { walsCode := "raw", iso := "raw", value := .indirectObjectConstruction }
  , { walsCode := "ret", iso := "tnc", value := .doubleObjectConstruction }
  , { walsCode := "ron", iso := "cla", value := .indirectObjectConstruction }
  , { walsCode := "rus", iso := "rus", value := .indirectObjectConstruction }
  , { walsCode := "sno", iso := "sme", value := .indirectObjectConstruction }
  , { walsCode := "slb", iso := "sbe", value := .mixed }
  , { walsCode := "syu", iso := "sll", value := .doubleObjectConstruction }
  , { walsCode := "san", iso := "sag", value := .indirectObjectConstruction }
  , { walsCode := "sgu", iso := "snq", value := .doubleObjectConstruction }
  , { walsCode := "snm", iso := "xsu", value := .indirectObjectConstruction }
  , { walsCode := "sap", iso := "spu", value := .indirectObjectConstruction }
  , { walsCode := "sed", iso := "sed", value := .mixed }
  , { walsCode := "skp", iso := "sel", value := .indirectObjectConstruction }
  , { walsCode := "sml", iso := "sza", value := .indirectObjectConstruction }
  , { walsCode := "shk", iso := "shp", value := .doubleObjectConstruction }
  , { walsCode := "sho", iso := "shh", value := .doubleObjectConstruction }
  , { walsCode := "sng", iso := "snc", value := .secondaryObjectConstruction }
  , { walsCode := "sla", iso := "den", value := .indirectObjectConstruction }
  , { walsCode := "so", iso := "teu", value := .indirectObjectConstruction }
  , { walsCode := "som", iso := "som", value := .secondaryObjectConstruction }
  , { walsCode := "stn", iso := "nso", value := .doubleObjectConstruction }
  , { walsCode := "spa", iso := "spa", value := .indirectObjectConstruction }
  , { walsCode := "sud", iso := "tgo", value := .indirectObjectConstruction }
  , { walsCode := "sue", iso := "sue", value := .indirectObjectConstruction }
  , { walsCode := "sun", iso := "sun", value := .mixed }
  , { walsCode := "sup", iso := "spp", value := .indirectObjectConstruction }
  , { walsCode := "swa", iso := "swh", value := .doubleObjectConstruction }
  , { walsCode := "tab", iso := "mky", value := .doubleObjectConstruction }
  , { walsCode := "tag", iso := "tgl", value := .mixed }
  , { walsCode := "tam", iso := "taj", value := .indirectObjectConstruction }
  , { walsCode := "tml", iso := "tam", value := .indirectObjectConstruction }
  , { walsCode := "tar", iso := "tae", value := .doubleObjectConstruction }
  , { walsCode := "tau", iso := "tya", value := .secondaryObjectConstruction }
  , { walsCode := "tps", iso := "stp", value := .secondaryObjectConstruction }
  , { walsCode := "trb", iso := "tfr", value := .indirectObjectConstruction }
  , { walsCode := "trt", iso := "tft", value := .mixed }
  , { walsCode := "ttn", iso := "tet", value := .mixed }
  , { walsCode := "tha", iso := "tha", value := .indirectObjectConstruction }
  , { walsCode := "tis", iso := "bod", value := .indirectObjectConstruction }
  , { walsCode := "tib", iso := "bod", value := .indirectObjectConstruction }
  , { walsCode := "tid", iso := "tvo", value := .mixed }
  , { walsCode := "tig", iso := "tir", value := .indirectObjectConstruction }
  , { walsCode := "tja", iso := "dih", value := .doubleObjectConstruction }
  , { walsCode := "tik", iso := "tik", value := .doubleObjectConstruction }
  , { walsCode := "tin", iso := "cir", value := .indirectObjectConstruction }
  , { walsCode := "tiw", iso := "tiw", value := .secondaryObjectConstruction }
  , { walsCode := "tbt", iso := "tti", value := .secondaryObjectConstruction }
  , { walsCode := "tms", iso := "dto", value := .indirectObjectConstruction }
  , { walsCode := "tor", iso := "rth", value := .indirectObjectConstruction }
  , { walsCode := "trw", iso := "trw", value := .indirectObjectConstruction }
  , { walsCode := "tru", iso := "tpy", value := .indirectObjectConstruction }
  , { walsCode := "tst", iso := "huq", value := .indirectObjectConstruction }
  , { walsCode := "tsz", iso := "ddo", value := .indirectObjectConstruction }
  , { walsCode := "tgl", iso := "tsj", value := .indirectObjectConstruction }
  , { walsCode := "tsi", iso := "tsi", value := .indirectObjectConstruction }
  , { walsCode := "tgn", iso := "tzn", value := .indirectObjectConstruction }
  , { walsCode := "tuk", iso := "", value := .doubleObjectConstruction }
  , { walsCode := "tnn", iso := "tvu", value := .doubleObjectConstruction }
  , { walsCode := "tna", iso := "tuv", value := .doubleObjectConstruction }
  , { walsCode := "tur", iso := "tur", value := .indirectObjectConstruction }
  , { walsCode := "tzu", iso := "tzj", value := .indirectObjectConstruction }
  , { walsCode := "tsh", iso := "par", value := .doubleObjectConstruction }
  , { walsCode := "udh", iso := "ude", value := .indirectObjectConstruction }
  , { walsCode := "udm", iso := "udm", value := .indirectObjectConstruction }
  , { walsCode := "uku", iso := "kuu", value := .indirectObjectConstruction }
  , { walsCode := "urk", iso := "urb", value := .indirectObjectConstruction }
  , { walsCode := "usa", iso := "wnu", value := .secondaryObjectConstruction }
  , { walsCode := "vie", iso := "vie", value := .doubleObjectConstruction }
  , { walsCode := "wlm", iso := "wmt", value := .doubleObjectConstruction }
  , { walsCode := "wam", iso := "wmb", value := .doubleObjectConstruction }
  , { walsCode := "wra", iso := "wba", value := .indirectObjectConstruction }
  , { walsCode := "wry", iso := "wrz", value := .doubleObjectConstruction }
  , { walsCode := "wrd", iso := "wrr", value := .secondaryObjectConstruction }
  , { walsCode := "wrm", iso := "wsa", value := .indirectObjectConstruction }
  , { walsCode := "war", iso := "pav", value := .secondaryObjectConstruction }
  , { walsCode := "wrl", iso := "wbp", value := .mixed }
  , { walsCode := "wrg", iso := "wgy", value := .mixed }
  , { walsCode := "wch", iso := "mzh", value := .secondaryObjectConstruction }
  , { walsCode := "wir", iso := "wgu", value := .indirectObjectConstruction }
  , { walsCode := "wlf", iso := "wol", value := .doubleObjectConstruction }
  , { walsCode := "yag", iso := "yad", value := .secondaryObjectConstruction }
  , { walsCode := "yny", iso := "jao", value := .mixed }
  , { walsCode := "yaq", iso := "yaq", value := .secondaryObjectConstruction }
  , { walsCode := "yid", iso := "yii", value := .indirectObjectConstruction }
  , { walsCode := "yim", iso := "yee", value := .indirectObjectConstruction }
  , { walsCode := "yng", iso := "yia", value := .secondaryObjectConstruction }
  , { walsCode := "yir", iso := "yyr", value := .doubleObjectConstruction }
  , { walsCode := "yor", iso := "yor", value := .secondaryObjectConstruction }
  , { walsCode := "yko", iso := "yux", value := .indirectObjectConstruction }
  , { walsCode := "ytu", iso := "ykg", value := .indirectObjectConstruction }
  , { walsCode := "zaq", iso := "zpi", value := .indirectObjectConstruction }
  , { walsCode := "zay", iso := "zay", value := .indirectObjectConstruction }
  , { walsCode := "zaz", iso := "diq", value := .indirectObjectConstruction }
  , { walsCode := "zch", iso := "zoh", value := .secondaryObjectConstruction }
  , { walsCode := "zul", iso := "zul", value := .doubleObjectConstruction }
  ]

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F105A
