import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 116A: Polar Questions
@cite{dryer-2013-wals}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 116A`.

Chapter 116, 955 languages.
-/

namespace Core.WALS.F116A

/-- WALS 116A values. -/
inductive PolarQuestionType where
  /-- Question particle (585 languages). -/
  | questionParticle
  /-- Interrogative verb morphology (164 languages). -/
  | interrogativeVerbMorphology
  /-- Mixture of previous two types (15 languages). -/
  | mixtureOfPreviousTwoTypes
  /-- Interrogative word order (13 languages). -/
  | interrogativeWordOrder
  /-- Absence of declarative morphemes (4 languages). -/
  | absenceOfDeclarativeMorphemes
  /-- Interrogative intonation only (173 languages). -/
  | interrogativeIntonationOnly
  /-- No interrogative-declarative distinction (1 languages). -/
  | noInterrogativeDeclarativeDistinction
  deriving DecidableEq, BEq, Repr

private def allData_0 : List (Datapoint PolarQuestionType) :=
  [ { walsCode := "xoo", iso := "nmn", value := .questionParticle }
  , { walsCode := "ani", iso := "hnh", value := .questionParticle }
  , { walsCode := "huc", iso := "huc", value := .questionParticle }
  , { walsCode := "aar", iso := "aiw", value := .interrogativeVerbMorphology }
  , { walsCode := "abk", iso := "abk", value := .interrogativeVerbMorphology }
  , { walsCode := "abu", iso := "kgr", value := .questionParticle }
  , { walsCode := "ace", iso := "ace", value := .questionParticle }
  , { walsCode := "acn", iso := "acn", value := .questionParticle }
  , { walsCode := "acu", iso := "acu", value := .interrogativeVerbMorphology }
  , { walsCode := "adi", iso := "adj", value := .questionParticle }
  , { walsCode := "adz", iso := "adz", value := .interrogativeIntonationOnly }
  , { walsCode := "aga", iso := "agd", value := .interrogativeVerbMorphology }
  , { walsCode := "agc", iso := "agt", value := .questionParticle }
  , { walsCode := "agd", iso := "duo", value := .questionParticle }
  , { walsCode := "ain", iso := "ain", value := .questionParticle }
  , { walsCode := "ajg", iso := "ajg", value := .questionParticle }
  , { walsCode := "akn", iso := "aka", value := .questionParticle }
  , { walsCode := "akh", iso := "ahk", value := .questionParticle }
  , { walsCode := "all", iso := "nrz", value := .questionParticle }
  , { walsCode := "ala", iso := "amp", value := .interrogativeIntonationOnly }
  , { walsCode := "alb", iso := "sqi", value := .questionParticle }
  , { walsCode := "aln", iso := "alp", value := .questionParticle }
  , { walsCode := "amc", iso := "amc", value := .questionParticle }
  , { walsCode := "amn", iso := "amn", value := .questionParticle }
  , { walsCode := "aml", iso := "omb", value := .interrogativeIntonationOnly }
  , { walsCode := "amq", iso := "amk", value := .questionParticle }
  , { walsCode := "amb", iso := "abt", value := .questionParticle }
  , { walsCode := "ame", iso := "aey", value := .questionParticle }
  , { walsCode := "amh", iso := "amh", value := .mixtureOfPreviousTwoTypes }
  , { walsCode := "amo", iso := "amo", value := .questionParticle }
  , { walsCode := "amx", iso := "imi", value := .questionParticle }
  , { walsCode := "anj", iso := "aty", value := .questionParticle }
  , { walsCode := "agm", iso := "njm", value := .questionParticle }
  , { walsCode := "anc", iso := "anc", value := .questionParticle }
  , { walsCode := "ang", iso := "agg", value := .interrogativeVerbMorphology }
  , { walsCode := "ann", iso := "aoi", value := .questionParticle }
  , { walsCode := "ano", iso := "nun", value := .interrogativeIntonationOnly }
  , { walsCode := "anu", iso := "cko", value := .questionParticle }
  , { walsCode := "ao", iso := "njo", value := .questionParticle }
  , { walsCode := "apw", iso := "apw", value := .interrogativeVerbMorphology }
  , { walsCode := "apl", iso := "apy", value := .interrogativeIntonationOnly }
  , { walsCode := "apt", iso := "apt", value := .questionParticle }
  , { walsCode := "api", iso := "apn", value := .questionParticle }
  , { walsCode := "apu", iso := "apu", value := .interrogativeIntonationOnly }
  , { walsCode := "aeg", iso := "arz", value := .questionParticle }
  , { walsCode := "arg", iso := "afb", value := .interrogativeIntonationOnly }
  , { walsCode := "ams", iso := "arb", value := .questionParticle }
  , { walsCode := "amr", iso := "ary", value := .questionParticle }
  , { walsCode := "asy", iso := "apc", value := .questionParticle }
  , { walsCode := "ana", iso := "aro", value := .interrogativeVerbMorphology }
  , { walsCode := "aab", iso := "aah", value := .questionParticle }
  , { walsCode := "arp", iso := "ape", value := .questionParticle }
  , { walsCode := "arc", iso := "aqc", value := .interrogativeVerbMorphology }
  , { walsCode := "arm", iso := "hye", value := .interrogativeIntonationOnly }
  , { walsCode := "arw", iso := "hyw", value := .interrogativeIntonationOnly }
  , { walsCode := "alk", iso := "apr", value := .interrogativeIntonationOnly }
  , { walsCode := "aro", iso := "aia", value := .questionParticle }
  , { walsCode := "amp", iso := "aer", value := .questionParticle }
  , { walsCode := "asm", iso := "cns", value := .questionParticle }
  , { walsCode := "ass", iso := "asm", value := .interrogativeVerbMorphology }
  , { walsCode := "ata", iso := "tay", value := .questionParticle }
  , { walsCode := "ath", iso := "aph", value := .interrogativeVerbMorphology }
  , { walsCode := "ava", iso := "ava", value := .questionParticle }
  , { walsCode := "avk", iso := "avi", value := .questionParticle }
  , { walsCode := "awp", iso := "kwi", value := .questionParticle }
  , { walsCode := "awt", iso := "kmn", value := .questionParticle }
  , { walsCode := "aym", iso := "ayr", value := .questionParticle }
  , { walsCode := "azi", iso := "azb", value := .interrogativeIntonationOnly }
  , { walsCode := "aze", iso := "", value := .questionParticle }
  , { walsCode := "bab", iso := "bav", value := .questionParticle }
  , { walsCode := "bdm", iso := "bia", value := .interrogativeIntonationOnly }
  , { walsCode := "baf", iso := "bfd", value := .interrogativeIntonationOnly }
  , { walsCode := "bag", iso := "bmi", value := .questionParticle }
  , { walsCode := "bai", iso := "bca", value := .questionParticle }
  , { walsCode := "bwc", iso := "bdr", value := .questionParticle }
  , { walsCode := "bkn", iso := "bdu", value := .questionParticle }
  , { walsCode := "blt", iso := "bft", value := .interrogativeVerbMorphology }
  , { walsCode := "bam", iso := "bam", value := .questionParticle }
  , { walsCode := "bnj", iso := "bdy", value := .questionParticle }
  , { walsCode := "bgz", iso := "bdg", value := .interrogativeIntonationOnly }
  , { walsCode := "bao", iso := "peh", value := .interrogativeVerbMorphology }
  , { walsCode := "ble", iso := "bci", value := .interrogativeIntonationOnly }
  , { walsCode := "baa", iso := "bbb", value := .questionParticle }
  , { walsCode := "brs", iso := "bsn", value := .interrogativeVerbMorphology }
  , { walsCode := "bar", iso := "bfa", value := .questionParticle }
  , { walsCode := "brp", iso := "bpe", value := .questionParticle }
  , { walsCode := "bae", iso := "bae", value := .interrogativeIntonationOnly }
  , { walsCode := "bsk", iso := "bak", value := .questionParticle }
  , { walsCode := "bsq", iso := "eus", value := .questionParticle }
  , { walsCode := "bkr", iso := "btx", value := .questionParticle }
  , { walsCode := "baw", iso := "bgr", value := .questionParticle }
  , { walsCode := "bej", iso := "bej", value := .interrogativeVerbMorphology }
  , { walsCode := "bel", iso := "byw", value := .questionParticle }
  , { walsCode := "bco", iso := "blc", value := .interrogativeVerbMorphology }
  , { walsCode := "blr", iso := "bel", value := .questionParticle }
  , { walsCode := "bem", iso := "bem", value := .questionParticle }
  , { walsCode := "bfg", iso := "grr", value := .questionParticle }
  , { walsCode := "bma", iso := "tzm", value := .questionParticle }
  , { walsCode := "brf", iso := "rif", value := .questionParticle }
  , { walsCode := "zag", iso := "zag", value := .interrogativeVerbMorphology }
  , { walsCode := "ber", iso := "wti", value := .questionParticle }
  , { walsCode := "bti", iso := "", value := .interrogativeVerbMorphology }
  , { walsCode := "bho", iso := "bho", value := .questionParticle }
  , { walsCode := "bik", iso := "bhw", value := .interrogativeIntonationOnly }
  , { walsCode := "bln", iso := "byn", value := .interrogativeVerbMorphology }
  , { walsCode := "blx", iso := "bll", value := .questionParticle }
  , { walsCode := "bil", iso := "blb", value := .interrogativeIntonationOnly }
  , { walsCode := "bmb", iso := "bim", value := .interrogativeVerbMorphology }
  , { walsCode := "bbw", iso := "gup", value := .questionParticle }
  , { walsCode := "bii", iso := "bzr", value := .interrogativeIntonationOnly }
  , { walsCode := "bir", iso := "bom", value := .questionParticle }
  , { walsCode := "biu", iso := "", value := .interrogativeVerbMorphology }
  , { walsCode := "bla", iso := "bla", value := .interrogativeVerbMorphology }
  , { walsCode := "bbf", iso := "bbo", value := .questionParticle }
  , { walsCode := "bod", iso := "brx", value := .interrogativeVerbMorphology }
  , { walsCode := "bgo", iso := "bot", value := .questionParticle }
  , { walsCode := "bon", iso := "bpu", value := .questionParticle }
  , { walsCode := "btk", iso := "lbk", value := .questionParticle }
  , { walsCode := "bra", iso := "brb", value := .questionParticle }
  , { walsCode := "bre", iso := "bre", value := .questionParticle }
  , { walsCode := "bud", iso := "bdm", value := .questionParticle }
  , { walsCode := "bug", iso := "bug", value := .questionParticle }
  , { walsCode := "bgn", iso := "bgg", value := .questionParticle }
  , { walsCode := "bnu", iso := "", value := .questionParticle }
  , { walsCode := "bul", iso := "bul", value := .questionParticle }
  , { walsCode := "bum", iso := "tkw", value := .interrogativeIntonationOnly }
  , { walsCode := "ghr", iso := "bfu", value := .questionParticle }
  , { walsCode := "brm", iso := "mya", value := .interrogativeVerbMorphology }
  , { walsCode := "brn", iso := "bds", value := .interrogativeVerbMorphology }
  , { walsCode := "bur", iso := "bsk", value := .interrogativeVerbMorphology }
  , { walsCode := "bus", iso := "bqp", value := .questionParticle }
  , { walsCode := "bsh", iso := "buf", value := .interrogativeIntonationOnly }
  , { walsCode := "bya", iso := "bee", value := .questionParticle }
  , { walsCode := "cah", iso := "chl", value := .interrogativeIntonationOnly }
  , { walsCode := "cml", iso := "rab", value := .interrogativeIntonationOnly }
  , { walsCode := "cax", iso := "", value := .questionParticle }
  , { walsCode := "cnm", iso := "knm", value := .questionParticle }
  , { walsCode := "can", iso := "cbu", value := .interrogativeVerbMorphology }
  , { walsCode := "cnl", iso := "ram", value := .questionParticle }
  , { walsCode := "cnt", iso := "yue", value := .questionParticle }
  , { walsCode := "crp", iso := "cbc", value := .interrogativeVerbMorphology }
  , { walsCode := "car", iso := "car", value := .interrogativeVerbMorphology }
  , { walsCode := "ctl", iso := "cat", value := .interrogativeIntonationOnly }
  , { walsCode := "cga", iso := "old", value := .questionParticle }
  , { walsCode := "chh", iso := "sgw", value := .questionParticle }
  , { walsCode := "cai", iso := "suq", value := .interrogativeIntonationOnly }
  , { walsCode := "chw", iso := "cja", value := .questionParticle }
  , { walsCode := "cha", iso := "cha", value := .questionParticle }
  , { walsCode := "chg", iso := "nbc", value := .mixtureOfPreviousTwoTypes }
  , { walsCode := "chn", iso := "chx", value := .mixtureOfPreviousTwoTypes }
  , { walsCode := "cso", iso := "ctp", value := .questionParticle }
  , { walsCode := "chc", iso := "che", value := .interrogativeVerbMorphology }
  , { walsCode := "cmh", iso := "ute", value := .questionParticle }
  , { walsCode := "che", iso := "chr", value := .questionParticle }
  , { walsCode := "cic", iso := "nya", value := .questionParticle }
  , { walsCode := "chi", iso := "cid", value := .interrogativeVerbMorphology }
  , { walsCode := "cmr", iso := "mrh", value := .questionParticle }
  , { walsCode := "chs", iso := "csy", value := .questionParticle }
  , { walsCode := "cti", iso := "ctd", value := .questionParticle }
  , { walsCode := "ccm", iso := "cco", value := .questionParticle }
  , { walsCode := "cle", iso := "cle", value := .questionParticle }
  , { walsCode := "cpl", iso := "cpa", value := .interrogativeIntonationOnly }
  , { walsCode := "chq", iso := "chq", value := .questionParticle }
  , { walsCode := "cpy", iso := "cap", value := .interrogativeVerbMorphology }
  , { walsCode := "chp", iso := "chp", value := .questionParticle }
  , { walsCode := "ctm", iso := "ctm", value := .questionParticle }
  , { walsCode := "cct", iso := "cho", value := .questionParticle }
  , { walsCode := "chx", iso := "clo", value := .questionParticle }
  , { walsCode := "cmy", iso := "chf", value := .interrogativeIntonationOnly }
  , { walsCode := "chr", iso := "crw", value := .questionParticle }
  , { walsCode := "chk", iso := "ckt", value := .interrogativeIntonationOnly }
  , { walsCode := "cba", iso := "boi", value := .interrogativeVerbMorphology }
  , { walsCode := "chv", iso := "chv", value := .interrogativeVerbMorphology }
  , { walsCode := "cbo", iso := "cao", value := .questionParticle }
  , { walsCode := "coa", iso := "xcw", value := .interrogativeVerbMorphology }
  , { walsCode := "coc", iso := "cod", value := .questionParticle }
  , { walsCode := "cmn", iso := "com", value := .questionParticle }
  , { walsCode := "coo", iso := "csz", value := .questionParticle }
  , { walsCode := "cop", iso := "cop", value := .questionParticle }
  , { walsCode := "crn", iso := "cor", value := .questionParticle }
  , { walsCode := "cre", iso := "crk", value := .questionParticle }
  , { walsCode := "cea", iso := "csw", value := .questionParticle }
  , { walsCode := "cub", iso := "cub", value := .interrogativeVerbMorphology }
  , { walsCode := "cup", iso := "cup", value := .interrogativeIntonationOnly }
  , { walsCode := "cze", iso := "ces", value := .interrogativeWordOrder }
  , { walsCode := "cem", iso := "cam", value := .questionParticle }
  , { walsCode := "dgr", iso := "dta", value := .questionParticle }
  , { walsCode := "dan", iso := "dnj", value := .questionParticle }
  , { walsCode := "dni", iso := "dni", value := .interrogativeVerbMorphology }
  , { walsCode := "dsh", iso := "dan", value := .interrogativeWordOrder }
  , { walsCode := "drm", iso := "drd", value := .questionParticle }
  , { walsCode := "des", iso := "des", value := .interrogativeVerbMorphology }
  , { walsCode := "deu", iso := "der", value := .interrogativeVerbMorphology }
  , { walsCode := "dha", iso := "dsh", value := .interrogativeIntonationOnly }
  , { walsCode := "dhi", iso := "div", value := .questionParticle }
  , { walsCode := "die", iso := "dih", value := .interrogativeVerbMorphology }
  , { walsCode := "dim", iso := "dim", value := .interrogativeVerbMorphology }
  , { walsCode := "dng", iso := "diz", value := .questionParticle }
  , { walsCode := "din", iso := "din", value := .absenceOfDeclarativeMorphemes }
  , { walsCode := "dio", iso := "dyo", value := .interrogativeIntonationOnly }
  , { walsCode := "diy", iso := "dif", value := .interrogativeIntonationOnly }
  , { walsCode := "djm", iso := "djr", value := .interrogativeIntonationOnly }
  , { walsCode := "djp", iso := "dwu", value := .mixtureOfPreviousTwoTypes }
  , { walsCode := "dji", iso := "jig", value := .questionParticle }
  , { walsCode := "dlm", iso := "kbv", value := .interrogativeIntonationOnly }
  , { walsCode := "dmk", iso := "dmk", value := .questionParticle }
  , { walsCode := "don", iso := "kmc", value := .questionParticle }
  , { walsCode := "dds", iso := "dds", value := .questionParticle }
  , { walsCode := "doy", iso := "dow", value := .questionParticle }
  , { walsCode := "dre", iso := "dhv", value := .questionParticle }
  , { walsCode := "duk", iso := "dud", value := .questionParticle }
  , { walsCode := "dul", iso := "duu", value := .questionParticle }
  , { walsCode := "dum", iso := "vam", value := .questionParticle }
  , { walsCode := "dun", iso := "duc", value := .questionParticle }
  , { walsCode := "dut", iso := "nld", value := .interrogativeWordOrder }
  , { walsCode := "dyi", iso := "dbl", value := .questionParticle }
  , { walsCode := "ebi", iso := "igb", value := .questionParticle }
  , { walsCode := "erk", iso := "erk", value := .interrogativeIntonationOnly }
  , { walsCode := "efi", iso := "efi", value := .questionParticle }
  , { walsCode := "ega", iso := "ega", value := .questionParticle }
  , { walsCode := "eip", iso := "eip", value := .interrogativeVerbMorphology }
  , { walsCode := "ora", iso := "ema", value := .interrogativeIntonationOnly }
  , { walsCode := "emb", iso := "emp", value := .interrogativeVerbMorphology }
  , { walsCode := "ene", iso := "", value := .interrogativeVerbMorphology }
  , { walsCode := "egn", iso := "enn", value := .questionParticle }
  , { walsCode := "eno", iso := "eno", value := .interrogativeIntonationOnly }
  , { walsCode := "eng", iso := "eng", value := .interrogativeWordOrder }
  , { walsCode := "epe", iso := "sja", value := .interrogativeVerbMorphology }
  , { walsCode := "err", iso := "erg", value := .questionParticle }
  , { walsCode := "ese", iso := "ese", value := .questionParticle }
  , { walsCode := "est", iso := "ekk", value := .questionParticle }
  , { walsCode := "eud", iso := "", value := .questionParticle }
  , { walsCode := "evn", iso := "eve", value := .questionParticle }
  , { walsCode := "eve", iso := "evn", value := .questionParticle }
  , { walsCode := "ewe", iso := "ewe", value := .questionParticle }
  , { walsCode := "ewo", iso := "ewo", value := .questionParticle }
  , { walsCode := "fas", iso := "faa", value := .interrogativeVerbMorphology }
  , { walsCode := "fij", iso := "fij", value := .interrogativeIntonationOnly }
  , { walsCode := "fin", iso := "fin", value := .questionParticle }
  , { walsCode := "foe", iso := "foi", value := .interrogativeVerbMorphology }
  , { walsCode := "pdp", iso := "ppo", value := .interrogativeVerbMorphology }
  , { walsCode := "fre", iso := "fra", value := .questionParticle }
  , { walsCode := "fri", iso := "fry", value := .interrogativeWordOrder }
  , { walsCode := "fua", iso := "fub", value := .questionParticle }
  , { walsCode := "ful", iso := "fun", value := .interrogativeVerbMorphology }
  , { walsCode := "fut", iso := "fut", value := .questionParticle }
  , { walsCode := "fye", iso := "pym", value := .questionParticle }
  , { walsCode := "gds", iso := "gaj", value := .interrogativeVerbMorphology }
  , { walsCode := "gae", iso := "gla", value := .interrogativeVerbMorphology }
  , { walsCode := "gah", iso := "gah", value := .interrogativeVerbMorphology }
  , { walsCode := "gal", iso := "adl", value := .interrogativeVerbMorphology }
  , { walsCode := "gap", iso := "pwg", value := .questionParticle }
  , { walsCode := "gar", iso := "grt", value := .interrogativeVerbMorphology }
  , { walsCode := "grr", iso := "wrk", value := .questionParticle }
  , { walsCode := "gav", iso := "gvo", value := .questionParticle }
  , { walsCode := "gbb", iso := "gbp", value := .questionParticle }
  , { walsCode := "gel", iso := "nlg", value := .questionParticle }
  , { walsCode := "geo", iso := "kat", value := .interrogativeIntonationOnly }
  , { walsCode := "ger", iso := "deu", value := .interrogativeWordOrder }
  , { walsCode := "gim", iso := "bcq", value := .interrogativeVerbMorphology }
  , { walsCode := "git", iso := "git", value := .questionParticle }
  , { walsCode := "goa", iso := "guc", value := .questionParticle }
  , { walsCode := "goe", iso := "ank", value := .questionParticle }
  , { walsCode := "gok", iso := "gkn", value := .questionParticle }
  , { walsCode := "gln", iso := "gvf", value := .interrogativeVerbMorphology }
  , { walsCode := "gon", iso := "gno", value := .questionParticle }
  , { walsCode := "grb", iso := "grj", value := .questionParticle }
  , { walsCode := "grk", iso := "ell", value := .questionParticle }
  , { walsCode := "grw", iso := "kal", value := .interrogativeVerbMorphology }
  , { walsCode := "ghb", iso := "guh", value := .interrogativeIntonationOnly }
  , { walsCode := "gua", iso := "gug", value := .questionParticle }
  , { walsCode := "grj", iso := "var", value := .interrogativeIntonationOnly }
  , { walsCode := "gud", iso := "gde", value := .questionParticle }
  , { walsCode := "gug", iso := "ktd", value := .questionParticle }
  , { walsCode := "guh", iso := "ghs", value := .questionParticle }
  , { walsCode := "guj", iso := "guj", value := .interrogativeIntonationOnly }
  , { walsCode := "gul", iso := "kcm", value := .questionParticle }
  , { walsCode := "gmw", iso := "gvs", value := .interrogativeIntonationOnly }
  , { walsCode := "gum", iso := "kgs", value := .interrogativeIntonationOnly }
  , { walsCode := "gmz", iso := "guk", value := .interrogativeVerbMorphology }
  , { walsCode := "gnb", iso := "wlg", value := .interrogativeIntonationOnly }
  , { walsCode := "guw", iso := "guw", value := .questionParticle }
  , { walsCode := "ggu", iso := "gnr", value := .questionParticle }
  , { walsCode := "gur", iso := "", value := .questionParticle }
  , { walsCode := "gdb", iso := "gbj", value := .interrogativeVerbMorphology }
  , { walsCode := "gwa", iso := "gbr", value := .questionParticle }
  , { walsCode := "gyc", iso := "jya", value := .interrogativeVerbMorphology }
  , { walsCode := "hai", iso := "hai", value := .questionParticle }
  , { walsCode := "ham", iso := "hmt", value := .questionParticle }
  , { walsCode := "hat", iso := "had", value := .questionParticle }
  , { walsCode := "hau", iso := "hau", value := .questionParticle }
  , { walsCode := "hya", iso := "hay", value := .interrogativeIntonationOnly }
  , { walsCode := "hay", iso := "vay", value := .interrogativeIntonationOnly }
  , { walsCode := "hdi", iso := "xed", value := .questionParticle }
  , { walsCode := "heb", iso := "heb", value := .questionParticle }
  , { walsCode := "hil", iso := "hil", value := .questionParticle }
  , { walsCode := "hin", iso := "hin", value := .questionParticle }
  , { walsCode := "hix", iso := "hix", value := .interrogativeIntonationOnly }
  , { walsCode := "hma", iso := "hmr", value := .questionParticle }
  , { walsCode := "hmo", iso := "hnj", value := .questionParticle }
  , { walsCode := "ho", iso := "hoc", value := .questionParticle }
  , { walsCode := "hoa", iso := "hoa", value := .interrogativeIntonationOnly }
  , { walsCode := "hop", iso := "hop", value := .questionParticle }
  , { walsCode := "hua", iso := "ygr", value := .interrogativeVerbMorphology }
  , { walsCode := "htc", iso := "hus", value := .interrogativeIntonationOnly }
  , { walsCode := "hve", iso := "huv", value := .questionParticle }
  , { walsCode := "hmi", iso := "hto", value := .interrogativeIntonationOnly }
  , { walsCode := "hnd", iso := "hke", value := .questionParticle }
  , { walsCode := "hun", iso := "hun", value := .questionParticle }
  , { walsCode := "hzb", iso := "huz", value := .interrogativeVerbMorphology }
  , { walsCode := "hpd", iso := "jup", value := .interrogativeWordOrder }
  , { walsCode := "iaa", iso := "iai", value := .questionParticle }
  , { walsCode := "iba", iso := "iba", value := .questionParticle }
  , { walsCode := "idu", iso := "clk", value := .interrogativeVerbMorphology }
  , { walsCode := "ifu", iso := "ifb", value := .questionParticle }
  , { walsCode := "ifm", iso := "ifm", value := .questionParticle }
  , { walsCode := "igb", iso := "ibo", value := .interrogativeIntonationOnly }
  , { walsCode := "ige", iso := "ige", value := .questionParticle }
  , { walsCode := "ijo", iso := "ijc", value := .interrogativeVerbMorphology }
  , { walsCode := "ik", iso := "ikx", value := .questionParticle }
  , { walsCode := "ika", iso := "arh", value := .mixtureOfPreviousTwoTypes }
  , { walsCode := "imo", iso := "imn", value := .questionParticle }
  , { walsCode := "ina", iso := "szp", value := .questionParticle }
  , { walsCode := "ind", iso := "ind", value := .questionParticle }
  , { walsCode := "ing", iso := "inh", value := .interrogativeVerbMorphology }
  , { walsCode := "irq", iso := "irk", value := .interrogativeVerbMorphology }
  , { walsCode := "irr", iso := "irh", value := .interrogativeIntonationOnly }
  , { walsCode := "iri", iso := "gle", value := .questionParticle }
  , { walsCode := "ita", iso := "ita", value := .interrogativeIntonationOnly }
  , { walsCode := "ite", iso := "itl", value := .questionParticle }
  , { walsCode := "ito", iso := "ito", value := .interrogativeVerbMorphology }
  , { walsCode := "iwa", iso := "ibd", value := .questionParticle }
  , { walsCode := "iwm", iso := "iwm", value := .questionParticle }
  , { walsCode := "jar", iso := "izr", value := .questionParticle }
  , { walsCode := "izi", iso := "izz", value := .questionParticle }
  , { walsCode := "jab", iso := "jae", value := .questionParticle }
  , { walsCode := "jak", iso := "jac", value := .interrogativeIntonationOnly }
  , { walsCode := "jms", iso := "djm", value := .questionParticle }
  , { walsCode := "jpn", iso := "jpn", value := .questionParticle }
  , { walsCode := "jeb", iso := "jeb", value := .questionParticle }
  , { walsCode := "jng", iso := "kac", value := .questionParticle }
  , { walsCode := "jug", iso := "nst", value := .interrogativeVerbMorphology }
  , { walsCode := "juk", iso := "jbu", value := .questionParticle }
  , { walsCode := "jmo", iso := "bex", value := .interrogativeIntonationOnly }
  , { walsCode := "juh", iso := "ktz", value := .questionParticle }
  , { walsCode := "kab", iso := "kbd", value := .absenceOfDeclarativeMorphemes }
  , { walsCode := "kby", iso := "kbp", value := .questionParticle }
  , { walsCode := "kbl", iso := "kab", value := .interrogativeIntonationOnly }
  , { walsCode := "kdz", iso := "kzj", value := .questionParticle }
  , { walsCode := "kae", iso := "tbd", value := .interrogativeVerbMorphology }
  , { walsCode := "kmk", iso := "xal", value := .interrogativeVerbMorphology }
  , { walsCode := "kma", iso := "kay", value := .interrogativeIntonationOnly }
  , { walsCode := "kmz", iso := "kms", value := .interrogativeIntonationOnly }
  , { walsCode := "kba", iso := "kam", value := .interrogativeIntonationOnly }
  , { walsCode := "kmr", iso := "kgq", value := .interrogativeVerbMorphology }
  , { walsCode := "kan", iso := "ogo", value := .interrogativeVerbMorphology }
  , { walsCode := "knk", iso := "kna", value := .questionParticle }
  , { walsCode := "knd", iso := "kan", value := .questionParticle }
  , { walsCode := "kno", iso := "kxo", value := .questionParticle }
  , { walsCode := "knr", iso := "knc", value := .interrogativeVerbMorphology }
  , { walsCode := "kar", iso := "kah", value := .questionParticle }
  , { walsCode := "krc", iso := "krc", value := .interrogativeVerbMorphology }
  , { walsCode := "krj", iso := "gbd", value := .questionParticle }
  , { walsCode := "kkp", iso := "kaa", value := .interrogativeVerbMorphology }
  , { walsCode := "kbw", iso := "bwe", value := .questionParticle }
  , { walsCode := "kpw", iso := "kjp", value := .questionParticle }
  , { walsCode := "ksg", iso := "ksw", value := .questionParticle }
  , { walsCode := "kmj", iso := "kdj", value := .questionParticle }
  , { walsCode := "kaa", iso := "arr", value := .questionParticle }
  , { walsCode := "ksm", iso := "xsm", value := .questionParticle }
  , { walsCode := "kas", iso := "kas", value := .mixtureOfPreviousTwoTypes }
  , { walsCode := "ksn", iso := "cog", value := .questionParticle }
  , { walsCode := "kau", iso := "pss", value := .questionParticle }
  , { walsCode := "kws", iso := "xaw", value := .interrogativeIntonationOnly }
  , { walsCode := "kyz", iso := "kyz", value := .questionParticle }
  , { walsCode := "kyl", iso := "eky", value := .questionParticle }
  , { walsCode := "kyp", iso := "txu", value := .questionParticle }
  , { walsCode := "kay", iso := "gyd", value := .interrogativeIntonationOnly }
  , { walsCode := "kel", iso := "sbc", value := .questionParticle }
  , { walsCode := "kem", iso := "ahg", value := .interrogativeVerbMorphology }
  , { walsCode := "ken", iso := "kyq", value := .questionParticle }
  , { walsCode := "ker", iso := "ker", value := .questionParticle }
  , { walsCode := "ksa", iso := "kee", value := .questionParticle }
  , { walsCode := "ket", iso := "ket", value := .questionParticle }
  , { walsCode := "kew", iso := "kew", value := .questionParticle }
  , { walsCode := "khg", iso := "klr", value := .questionParticle }
  , { walsCode := "kha", iso := "khk", value := .questionParticle }
  , { walsCode := "kmh", iso := "kjl", value := .interrogativeVerbMorphology }
  , { walsCode := "khr", iso := "khr", value := .questionParticle }
  , { walsCode := "khs", iso := "kha", value := .questionParticle }
  , { walsCode := "khi", iso := "kjj", value := .interrogativeVerbMorphology }
  , { walsCode := "khm", iso := "khm", value := .questionParticle }
  , { walsCode := "kmu", iso := "kjg", value := .questionParticle }
  , { walsCode := "khn", iso := "kkh", value := .questionParticle }
  , { walsCode := "kik", iso := "kik", value := .interrogativeIntonationOnly }
  , { walsCode := "klv", iso := "kij", value := .interrogativeIntonationOnly }
  , { walsCode := "klw", iso := "klb", value := .interrogativeVerbMorphology }
  , { walsCode := "kil", iso := "lub", value := .questionParticle }
  , { walsCode := "kim", iso := "kig", value := .questionParticle }
  , { walsCode := "knn", iso := "kfk", value := .interrogativeVerbMorphology }
  , { walsCode := "kio", iso := "kio", value := .questionParticle }
  , { walsCode := "kgz", iso := "kir", value := .questionParticle }
  , { walsCode := "kis", iso := "kss", value := .interrogativeIntonationOnly }
  , { walsCode := "kiw", iso := "kjd", value := .questionParticle }
  , { walsCode := "klm", iso := "kla", value := .questionParticle }
  , { walsCode := "kob", iso := "kpw", value := .questionParticle }
  , { walsCode := "koe", iso := "xwg", value := .interrogativeVerbMorphology }
  , { walsCode := "kmo", iso := "kpx", value := .questionParticle }
  , { walsCode := "kta", iso := "kqi", value := .questionParticle }
  , { walsCode := "kok", iso := "trp", value := .interrogativeVerbMorphology }
  , { walsCode := "kol", iso := "kfb", value := .interrogativeVerbMorphology }
  , { walsCode := "kmb", iso := "", value := .questionParticle }
  , { walsCode := "xbi", iso := "xbi", value := .interrogativeIntonationOnly }
  , { walsCode := "knw", iso := "mjd", value := .interrogativeVerbMorphology }
  , { walsCode := "kni", iso := "kma", value := .interrogativeIntonationOnly }
  , { walsCode := "krn", iso := "kqz", value := .questionParticle }
  , { walsCode := "kor", iso := "kor", value := .interrogativeVerbMorphology }
  , { walsCode := "kje", iso := "coe", value := .interrogativeVerbMorphology }
  , { walsCode := "kfe", iso := "kfz", value := .questionParticle }
  , { walsCode := "krw", iso := "khe", value := .questionParticle }
  , { walsCode := "kos", iso := "kos", value := .questionParticle }
  , { walsCode := "kch", iso := "khq", value := .interrogativeIntonationOnly }
  , { walsCode := "kse", iso := "ses", value := .questionParticle }
  , { walsCode := "kqq", iso := "kqq", value := .interrogativeIntonationOnly }
  , { walsCode := "kre", iso := "krs", value := .questionParticle }
  , { walsCode := "kro", iso := "kgo", value := .interrogativeVerbMorphology }
  , { walsCode := "knc", iso := "uwa", value := .interrogativeIntonationOnly }
  , { walsCode := "kya", iso := "gvn", value := .questionParticle }
  , { walsCode := "kmn", iso := "kue", value := .interrogativeVerbMorphology }
  , { walsCode := "kum", iso := "kfy", value := .questionParticle }
  , { walsCode := "kun", iso := "kvn", value := .interrogativeIntonationOnly }
  , { walsCode := "knm", iso := "kun", value := .interrogativeVerbMorphology }
  , { walsCode := "kuo", iso := "kto", value := .interrogativeIntonationOnly }
  , { walsCode := "kut", iso := "kut", value := .questionParticle }
  , { walsCode := "thy", iso := "thd", value := .interrogativeIntonationOnly }
  , { walsCode := "kuu", iso := "kuy", value := .interrogativeIntonationOnly }
  , { walsCode := "kuv", iso := "kxv", value := .questionParticle }
  , { walsCode := "kwn", iso := "kwn", value := .questionParticle }
  , { walsCode := "kwz", iso := "xwa", value := .interrogativeVerbMorphology }
  , { walsCode := "kwo", iso := "kmo", value := .questionParticle }
  , { walsCode := "kxo", iso := "xuu", value := .questionParticle }
  , { walsCode := "kyk", iso := "kyc", value := .interrogativeVerbMorphology }
  , { walsCode := "kgy", iso := "kgy", value := .mixtureOfPreviousTwoTypes }
  , { walsCode := "laa", iso := "gdm", value := .questionParticle }
  , { walsCode := "lab", iso := "lbu", value := .interrogativeIntonationOnly }
  , { walsCode := "lac", iso := "lac", value := .questionParticle }
  , { walsCode := "lad", iso := "lbj", value := .interrogativeVerbMorphology }
  , { walsCode := "lag", iso := "kot", value := .questionParticle }
  , { walsCode := "lah", iso := "lhu", value := .questionParticle }
  , { walsCode := "lai", iso := "cnh", value := .questionParticle }
  , { walsCode := "lkt", iso := "lkt", value := .questionParticle }
  , { walsCode := "lal", iso := "ywt", value := .questionParticle }
  , { walsCode := "lmh", iso := "slp", value := .interrogativeIntonationOnly }
  , { walsCode := "lmg", iso := "hia", value := .questionParticle }
  , { walsCode := "lmn", iso := "lmn", value := .questionParticle }
  , { walsCode := "lmb", iso := "lam", value := .questionParticle }
  , { walsCode := "lmp", iso := "ljp", value := .questionParticle }
  , { walsCode := "lan", iso := "laj", value := .interrogativeIntonationOnly }
  , { walsCode := "lao", iso := "lao", value := .questionParticle }
  , { walsCode := "lat", iso := "lav", value := .questionParticle }
  , { walsCode := "lav", iso := "lvk", value := .questionParticle }
  , { walsCode := "lel", iso := "lln", value := .questionParticle }
  , { walsCode := "len", iso := "tnl", value := .questionParticle }
  , { walsCode := "ldu", iso := "led", value := .questionParticle }
  , { walsCode := "lep", iso := "lep", value := .questionParticle }
  , { walsCode := "lew", iso := "lww", value := .questionParticle }
  , { walsCode := "lez", iso := "lez", value := .interrogativeVerbMorphology }
  , { walsCode := "lho", iso := "lhm", value := .interrogativeVerbMorphology }
  , { walsCode := "lnd", iso := "liy", value := .questionParticle }
  , { walsCode := "lin", iso := "lin", value := .interrogativeIntonationOnly }
  , { walsCode := "lis", iso := "lis", value := .interrogativeVerbMorphology }
  , { walsCode := "lit", iso := "lit", value := .questionParticle }
  , { walsCode := "lgt", iso := "log", value := .questionParticle }
  , { walsCode := "ara", iso := "arw", value := .interrogativeIntonationOnly }
  , { walsCode := "ldo", iso := "bdu", value := .questionParticle }
  , { walsCode := "lon", iso := "los", value := .interrogativeIntonationOnly }
  , { walsCode := "lot", iso := "njh", value := .interrogativeVerbMorphology }
  , { walsCode := "loz", iso := "loz", value := .questionParticle }
  , { walsCode := "lug", iso := "lgg", value := .questionParticle }
  , { walsCode := "lui", iso := "lui", value := .questionParticle }
  , { walsCode := "lbu", iso := "lun", value := .interrogativeIntonationOnly }
  , { walsCode := "lun", iso := "nst", value := .questionParticle }
  , { walsCode := "luo", iso := "luo", value := .interrogativeIntonationOnly }
  , { walsCode := "luv", iso := "lue", value := .questionParticle }
  , { walsCode := "mad", iso := "mhi", value := .questionParticle }
  , { walsCode := "maa", iso := "mas", value := .questionParticle }
  , { walsCode := "mab", iso := "mde", value := .interrogativeVerbMorphology }
  , { walsCode := "mcd", iso := "mkd", value := .questionParticle }
  , { walsCode := "mac", iso := "mbc", value := .interrogativeIntonationOnly }
  , { walsCode := "mae", iso := "mmw", value := .questionParticle }
  , { walsCode := "mne", iso := "nmu", value := .interrogativeVerbMorphology }
  , { walsCode := "mpr", iso := "", value := .questionParticle }
  , { walsCode := "msn", iso := "mbq", value := .questionParticle }
  , { walsCode := "maj", iso := "mpe", value := .questionParticle }
  , { walsCode := "mak", iso := "myh", value := .questionParticle }
  , { walsCode := "mkj", iso := "mkz", value := .questionParticle }
  , { walsCode := "mal", iso := "plt", value := .questionParticle }
  , { walsCode := "mym", iso := "mal", value := .questionParticle }
  , { walsCode := "mlg", iso := "", value := .interrogativeIntonationOnly }
  , { walsCode := "mam", iso := "mam", value := .questionParticle }
  ]

private def allData_1 : List (Datapoint PolarQuestionType) :=
  [ { walsCode := "mmn", iso := "mmn", value := .questionParticle }
  , { walsCode := "mmi", iso := "mcs", value := .questionParticle }
  , { walsCode := "mmv", iso := "mdi", value := .questionParticle }
  , { walsCode := "mds", iso := "xmm", value := .questionParticle }
  , { walsCode := "mnm", iso := "mva", value := .interrogativeIntonationOnly }
  , { walsCode := "mnc", iso := "mnc", value := .interrogativeVerbMorphology }
  , { walsCode := "mdn", iso := "mhq", value := .interrogativeVerbMorphology }
  , { walsCode := "mnd", iso := "cmn", value := .questionParticle }
  , { walsCode := "mmb", iso := "mna", value := .questionParticle }
  , { walsCode := "myi", iso := "mpc", value := .questionParticle }
  , { walsCode := "mng", iso := "mqy", value := .interrogativeWordOrder }
  , { walsCode := "mgg", iso := "mjg", value := .interrogativeVerbMorphology }
  , { walsCode := "maw", iso := "mlq", value := .questionParticle }
  , { walsCode := "man", iso := "mev", value := .interrogativeIntonationOnly }
  , { walsCode := "mwb", iso := "mbb", value := .questionParticle }
  , { walsCode := "mns", iso := "mns", value := .mixtureOfPreviousTwoTypes }
  , { walsCode := "mao", iso := "mri", value := .interrogativeIntonationOnly }
  , { walsCode := "map", iso := "arn", value := .questionParticle }
  , { walsCode := "mra", iso := "mec", value := .interrogativeIntonationOnly }
  , { walsCode := "mku", iso := "zmr", value := .interrogativeIntonationOnly }
  , { walsCode := "mhi", iso := "mar", value := .questionParticle }
  , { walsCode := "mny", iso := "zmc", value := .questionParticle }
  , { walsCode := "mrg", iso := "mrt", value := .questionParticle }
  , { walsCode := "mar", iso := "mrc", value := .interrogativeVerbMorphology }
  , { walsCode := "mrd", iso := "mrz", value := .mixtureOfPreviousTwoTypes }
  , { walsCode := "mrq", iso := "", value := .questionParticle }
  , { walsCode := "mrt", iso := "vma", value := .interrogativeIntonationOnly }
  , { walsCode := "mru", iso := "mhx", value := .questionParticle }
  , { walsCode := "mas", iso := "mcn", value := .questionParticle }
  , { walsCode := "msl", iso := "mls", value := .interrogativeVerbMorphology }
  , { walsCode := "mtt", iso := "wam", value := .interrogativeVerbMorphology }
  , { walsCode := "mts", iso := "mpq", value := .interrogativeVerbMorphology }
  , { walsCode := "mka", iso := "mxx", value := .questionParticle }
  , { walsCode := "mau", iso := "mph", value := .questionParticle }
  , { walsCode := "max", iso := "mbl", value := .questionParticle }
  , { walsCode := "may", iso := "ayz", value := .questionParticle }
  , { walsCode := "mzh", iso := "mau", value := .questionParticle }
  , { walsCode := "mbr", iso := "mpk", value := .questionParticle }
  , { walsCode := "mby", iso := "myb", value := .questionParticle }
  , { walsCode := "mbi", iso := "baw", value := .questionParticle }
  , { walsCode := "mdo", iso := "gmm", value := .questionParticle }
  , { walsCode := "mbm", iso := "mdd", value := .questionParticle }
  , { walsCode := "mee", iso := "mym", value := .questionParticle }
  , { walsCode := "meh", iso := "gdq", value := .interrogativeIntonationOnly }
  , { walsCode := "mei", iso := "mni", value := .questionParticle }
  , { walsCode := "mek", iso := "skf", value := .questionParticle }
  , { walsCode := "mke", iso := "mek", value := .questionParticle }
  , { walsCode := "mde", iso := "men", value := .interrogativeIntonationOnly }
  , { walsCode := "men", iso := "mez", value := .interrogativeVerbMorphology }
  , { walsCode := "mey", iso := "mcr", value := .questionParticle }
  , { walsCode := "mer", iso := "ulk", value := .interrogativeIntonationOnly }
  , { walsCode := "mea", iso := "mej", value := .questionParticle }
  , { walsCode := "mpt", iso := "mpt", value := .questionParticle }
  , { walsCode := "mie", iso := "ium", value := .questionParticle }
  , { walsCode := "mik", iso := "mjw", value := .interrogativeVerbMorphology }
  , { walsCode := "hna", iso := "hna", value := .questionParticle }
  , { walsCode := "mir", iso := "mep", value := .questionParticle }
  , { walsCode := "msg", iso := "mrg", value := .interrogativeVerbMorphology }
  , { walsCode := "mis", iso := "miq", value := .mixtureOfPreviousTwoTypes }
  , { walsCode := "mxx", iso := "mxp", value := .questionParticle }
  , { walsCode := "mco", iso := "mco", value := .questionParticle }
  , { walsCode := "mxc", iso := "mig", value := .noInterrogativeDeclarativeDistinction }
  , { walsCode := "mxj", iso := "mio", value := .questionParticle }
  , { walsCode := "mxo", iso := "mie", value := .questionParticle }
  , { walsCode := "mxp", iso := "mil", value := .questionParticle }
  , { walsCode := "mxy", iso := "mpm", value := .questionParticle }
  , { walsCode := "miy", iso := "mkf", value := .questionParticle }
  , { walsCode := "miz", iso := "lus", value := .questionParticle }
  , { walsCode := "mcc", iso := "omc", value := .questionParticle }
  , { walsCode := "mok", iso := "mkj", value := .questionParticle }
  , { walsCode := "mon", iso := "mnw", value := .questionParticle }
  , { walsCode := "mkh", iso := "", value := .questionParticle }
  , { walsCode := "mni", iso := "mnz", value := .interrogativeVerbMorphology }
  , { walsCode := "mno", iso := "mnr", value := .questionParticle }
  , { walsCode := "moo", iso := "mos", value := .questionParticle }
  , { walsCode := "mor", iso := "mhz", value := .questionParticle }
  , { walsCode := "mri", iso := "mok", value := .questionParticle }
  , { walsCode := "mro", iso := "mor", value := .mixtureOfPreviousTwoTypes }
  , { walsCode := "mou", iso := "mgd", value := .questionParticle }
  , { walsCode := "mos", iso := "cas", value := .questionParticle }
  , { walsCode := "mtu", iso := "meu", value := .questionParticle }
  , { walsCode := "mov", iso := "mzp", value := .interrogativeIntonationOnly }
  , { walsCode := "mpu", iso := "akc", value := .questionParticle }
  , { walsCode := "aoj", iso := "aoj", value := .questionParticle }
  , { walsCode := "msc", iso := "chb", value := .interrogativeVerbMorphology }
  , { walsCode := "mum", iso := "mzm", value := .questionParticle }
  , { walsCode := "mna", iso := "mnb", value := .interrogativeIntonationOnly }
  , { walsCode := "mun", iso := "unr", value := .questionParticle }
  , { walsCode := "mgk", iso := "mhk", value := .questionParticle }
  , { walsCode := "mup", iso := "sur", value := .questionParticle }
  , { walsCode := "mrl", iso := "mur", value := .interrogativeIntonationOnly }
  , { walsCode := "mpa", iso := "mwf", value := .questionParticle }
  , { walsCode := "mrw", iso := "zmu", value := .questionParticle }
  , { walsCode := "mgu", iso := "mug", value := .questionParticle }
  , { walsCode := "mus", iso := "emi", value := .questionParticle }
  , { walsCode := "mut", iso := "css", value := .questionParticle }
  , { walsCode := "mwo", iso := "mlv", value := .interrogativeIntonationOnly }
  , { walsCode := "nab", iso := "naf", value := .interrogativeIntonationOnly }
  , { walsCode := "ndr", iso := "wyy", value := .interrogativeIntonationOnly }
  , { walsCode := "nad", iso := "mbj", value := .interrogativeIntonationOnly }
  , { walsCode := "nma", iso := "nbi", value := .questionParticle }
  , { walsCode := "ngt", iso := "nmf", value := .interrogativeVerbMorphology }
  , { walsCode := "nze", iso := "nzm", value := .questionParticle }
  , { walsCode := "nag", iso := "nce", value := .questionParticle }
  , { walsCode := "nht", iso := "nhg", value := .interrogativeIntonationOnly }
  , { walsCode := "kho", iso := "naq", value := .questionParticle }
  , { walsCode := "nmb", iso := "nab", value := .interrogativeVerbMorphology }
  , { walsCode := "nam", iso := "nnm", value := .questionParticle }
  , { walsCode := "nnc", iso := "ncb", value := .questionParticle }
  , { walsCode := "nan", iso := "niq", value := .questionParticle }
  , { walsCode := "nnk", iso := "nnk", value := .interrogativeIntonationOnly }
  , { walsCode := "nph", iso := "npa", value := .interrogativeVerbMorphology }
  , { walsCode := "nar", iso := "nrb", value := .questionParticle }
  , { walsCode := "nas", iso := "nas", value := .questionParticle }
  , { walsCode := "nav", iso := "nav", value := .questionParticle }
  , { walsCode := "nax", iso := "nxq", value := .questionParticle }
  , { walsCode := "ncm", iso := "bud", value := .questionParticle }
  , { walsCode := "ndb", iso := "nde", value := .questionParticle }
  , { walsCode := "ndj", iso := "djj", value := .interrogativeIntonationOnly }
  , { walsCode := "ndy", iso := "djk", value := .interrogativeIntonationOnly }
  , { walsCode := "nnd", iso := "anh", value := .interrogativeVerbMorphology }
  , { walsCode := "naj", iso := "aij", value := .interrogativeIntonationOnly }
  , { walsCode := "nep", iso := "npi", value := .questionParticle }
  , { walsCode := "nev", iso := "pia", value := .questionParticle }
  , { walsCode := "nwd", iso := "new", value := .questionParticle }
  , { walsCode := "new", iso := "new", value := .questionParticle }
  , { walsCode := "ney", iso := "ney", value := .questionParticle }
  , { walsCode := "nez", iso := "nez", value := .questionParticle }
  , { walsCode := "ngd", iso := "nxg", value := .interrogativeIntonationOnly }
  , { walsCode := "nkb", iso := "ngk", value := .questionParticle }
  , { walsCode := "ngm", iso := "sba", value := .questionParticle }
  , { walsCode := "nga", iso := "nio", value := .interrogativeVerbMorphology }
  , { walsCode := "ngn", iso := "nid", value := .questionParticle }
  , { walsCode := "ngk", iso := "nam", value := .interrogativeIntonationOnly }
  , { walsCode := "nbm", iso := "nbm", value := .questionParticle }
  , { walsCode := "ngb", iso := "nga", value := .questionParticle }
  , { walsCode := "ndi", iso := "ngb", value := .interrogativeIntonationOnly }
  , { walsCode := "nti", iso := "niy", value := .questionParticle }
  , { walsCode := "ngi", iso := "wyb", value := .questionParticle }
  , { walsCode := "ngz", iso := "ngi", value := .interrogativeIntonationOnly }
  , { walsCode := "ngo", iso := "ngo", value := .interrogativeIntonationOnly }
  , { walsCode := "nha", iso := "nha", value := .interrogativeIntonationOnly }
  , { walsCode := "nia", iso := "nia", value := .questionParticle }
  , { walsCode := "nsn", iso := "nsz", value := .questionParticle }
  , { walsCode := "nsg", iso := "ncg", value := .questionParticle }
  , { walsCode := "nif", iso := "num", value := .interrogativeIntonationOnly }
  , { walsCode := "niu", iso := "niu", value := .questionParticle }
  , { walsCode := "niv", iso := "niv", value := .questionParticle }
  , { walsCode := "nke", iso := "isi", value := .questionParticle }
  , { walsCode := "nkn", iso := "nko", value := .questionParticle }
  , { walsCode := "nko", iso := "cgg", value := .questionParticle }
  , { walsCode := "noc", iso := "njb", value := .interrogativeVerbMorphology }
  , { walsCode := "non", iso := "nhu", value := .questionParticle }
  , { walsCode := "noo", iso := "snf", value := .questionParticle }
  , { walsCode := "nor", iso := "nor", value := .interrogativeWordOrder }
  , { walsCode := "nua", iso := "nxl", value := .interrogativeIntonationOnly }
  , { walsCode := "nbd", iso := "dgl", value := .interrogativeVerbMorphology }
  , { walsCode := "nun", iso := "nut", value := .questionParticle }
  , { walsCode := "nug", iso := "nuy", value := .questionParticle }
  , { walsCode := "nup", iso := "nup", value := .questionParticle }
  , { walsCode := "nyk", iso := "tpq", value := .interrogativeVerbMorphology }
  , { walsCode := "nyn", iso := "nyh", value := .questionParticle }
  , { walsCode := "nyu", iso := "nyv", value := .questionParticle }
  , { walsCode := "ood", iso := "ood", value := .questionParticle }
  , { walsCode := "obo", iso := "ann", value := .questionParticle }
  , { walsCode := "ocu", iso := "ocu", value := .questionParticle }
  , { walsCode := "obg", iso := "ogu", value := .questionParticle }
  , { walsCode := "oji", iso := "", value := .questionParticle }
  , { walsCode := "olo", iso := "ong", value := .questionParticle }
  , { walsCode := "omh", iso := "oma", value := .questionParticle }
  , { walsCode := "ond", iso := "one", value := .questionParticle }
  , { walsCode := "ong", iso := "oon", value := .mixtureOfPreviousTwoTypes }
  , { walsCode := "oya", iso := "ory", value := .questionParticle }
  , { walsCode := "oro", iso := "okv", value := .mixtureOfPreviousTwoTypes }
  , { walsCode := "orh", iso := "hae", value := .interrogativeIntonationOnly }
  , { walsCode := "osa", iso := "osa", value := .interrogativeIntonationOnly }
  , { walsCode := "otm", iso := "ote", value := .questionParticle }
  , { walsCode := "paa", iso := "pqa", value := .interrogativeIntonationOnly }
  , { walsCode := "pms", iso := "pma", value := .interrogativeIntonationOnly }
  , { walsCode := "pno", iso := "pao", value := .questionParticle }
  , { walsCode := "pai", iso := "pwn", value := .interrogativeIntonationOnly }
  , { walsCode := "pal", iso := "pau", value := .interrogativeWordOrder }
  , { walsCode := "plk", iso := "plu", value := .questionParticle }
  , { walsCode := "pnx", iso := "kre", value := .questionParticle }
  , { walsCode := "pan", iso := "pan", value := .questionParticle }
  , { walsCode := "psh", iso := "pst", value := .interrogativeIntonationOnly }
  , { walsCode := "ptt", iso := "lae", value := .interrogativeVerbMorphology }
  , { walsCode := "pau", iso := "pad", value := .interrogativeVerbMorphology }
  , { walsCode := "paw", iso := "pwa", value := .interrogativeVerbMorphology }
  , { walsCode := "per", iso := "pip", value := .questionParticle }
  , { walsCode := "prs", iso := "pes", value := .questionParticle }
  , { walsCode := "pga", iso := "plg", value := .questionParticle }
  , { walsCode := "pip", iso := "ppl", value := .interrogativeIntonationOnly }
  , { walsCode := "prh", iso := "myp", value := .mixtureOfPreviousTwoTypes }
  , { walsCode := "pir", iso := "pib", value := .questionParticle }
  , { walsCode := "pis", iso := "psa", value := .questionParticle }
  , { walsCode := "ppi", iso := "pit", value := .interrogativeIntonationOnly }
  , { walsCode := "pod", iso := "pbi", value := .questionParticle }
  , { walsCode := "poh", iso := "pon", value := .interrogativeIntonationOnly }
  , { walsCode := "pok", iso := "rwa", value := .questionParticle }
  , { walsCode := "pol", iso := "pol", value := .questionParticle }
  , { walsCode := "pme", iso := "peb", value := .interrogativeVerbMorphology }
  , { walsCode := "pso", iso := "pom", value := .interrogativeVerbMorphology }
  , { walsCode := "psw", iso := "psw", value := .interrogativeIntonationOnly }
  , { walsCode := "por", iso := "por", value := .questionParticle }
  , { walsCode := "pum", iso := "pmi", value := .questionParticle }
  , { walsCode := "puq", iso := "puq", value := .absenceOfDeclarativeMorphemes }
  , { walsCode := "prk", iso := "prx", value := .interrogativeVerbMorphology }
  , { walsCode := "pae", iso := "pbb", value := .interrogativeVerbMorphology }
  , { walsCode := "par", iso := "lkr", value := .interrogativeIntonationOnly }
  , { walsCode := "qaw", iso := "alc", value := .interrogativeVerbMorphology }
  , { walsCode := "qia", iso := "", value := .interrogativeVerbMorphology }
  , { walsCode := "qhu", iso := "qub", value := .interrogativeVerbMorphology }
  , { walsCode := "qim", iso := "qvi", value := .questionParticle }
  , { walsCode := "qui", iso := "qui", value := .interrogativeVerbMorphology }
  , { walsCode := "rap", iso := "rap", value := .questionParticle }
  , { walsCode := "raw", iso := "raw", value := .questionParticle }
  , { walsCode := "rem", iso := "bfw", value := .interrogativeVerbMorphology }
  , { walsCode := "res", iso := "rgr", value := .questionParticle }
  , { walsCode := "ret", iso := "tnc", value := .questionParticle }
  , { walsCode := "rit", iso := "rit", value := .questionParticle }
  , { walsCode := "rwe", iso := "rmw", value := .questionParticle }
  , { walsCode := "rom", iso := "ron", value := .interrogativeIntonationOnly }
  , { walsCode := "ron", iso := "cla", value := .questionParticle }
  , { walsCode := "rot", iso := "rtm", value := .questionParticle }
  , { walsCode := "rov", iso := "rug", value := .interrogativeIntonationOnly }
  , { walsCode := "ruk", iso := "dru", value := .interrogativeIntonationOnly }
  , { walsCode := "rum", iso := "klq", value := .questionParticle }
  , { walsCode := "run", iso := "rou", value := .interrogativeVerbMorphology }
  , { walsCode := "rny", iso := "nyn", value := .interrogativeIntonationOnly }
  , { walsCode := "rus", iso := "rus", value := .questionParticle }
  , { walsCode := "sno", iso := "sme", value := .questionParticle }
  , { walsCode := "sah", iso := "saj", value := .interrogativeIntonationOnly }
  , { walsCode := "slb", iso := "sbe", value := .questionParticle }
  , { walsCode := "sal", iso := "sln", value := .interrogativeVerbMorphology }
  , { walsCode := "syu", iso := "sll", value := .interrogativeVerbMorphology }
  , { walsCode := "sle", iso := "ndi", value := .questionParticle }
  , { walsCode := "sam", iso := "smo", value := .questionParticle }
  , { walsCode := "san", iso := "sag", value := .questionParticle }
  , { walsCode := "sta", iso := "sce", value := .interrogativeVerbMorphology }
  , { walsCode := "stl", iso := "sat", value := .interrogativeVerbMorphology }
  , { walsCode := "snm", iso := "xsu", value := .interrogativeIntonationOnly }
  , { walsCode := "sap", iso := "spu", value := .questionParticle }
  , { walsCode := "src", iso := "srs", value := .interrogativeVerbMorphology }
  , { walsCode := "srd", iso := "sro", value := .questionParticle }
  , { walsCode := "sar", iso := "dju", value := .interrogativeIntonationOnly }
  , { walsCode := "svs", iso := "svs", value := .interrogativeIntonationOnly }
  , { walsCode := "sed", iso := "sed", value := .questionParticle }
  , { walsCode := "sem", iso := "nsm", value := .questionParticle }
  , { walsCode := "sml", iso := "sza", value := .interrogativeIntonationOnly }
  , { walsCode := "smn", iso := "mus", value := .interrogativeVerbMorphology }
  , { walsCode := "scr", iso := "hbs", value := .questionParticle }
  , { walsCode := "ser", iso := "sei", value := .questionParticle }
  , { walsCode := "ses", iso := "sot", value := .interrogativeIntonationOnly }
  , { walsCode := "shh", iso := "mcd", value := .questionParticle }
  , { walsCode := "skw", iso := "swv", value := .interrogativeIntonationOnly }
  , { walsCode := "she", iso := "xsr", value := .questionParticle }
  , { walsCode := "shl", iso := "shk", value := .interrogativeIntonationOnly }
  , { walsCode := "sna", iso := "scl", value := .interrogativeVerbMorphology }
  , { walsCode := "shk", iso := "shp", value := .questionParticle }
  , { walsCode := "shi", iso := "shb", value := .questionParticle }
  , { walsCode := "ryu", iso := "ryu", value := .interrogativeVerbMorphology }
  , { walsCode := "shu", iso := "shs", value := .questionParticle }
  , { walsCode := "sia", iso := "snp", value := .interrogativeVerbMorphology }
  , { walsCode := "sid", iso := "sid", value := .interrogativeIntonationOnly }
  , { walsCode := "skk", iso := "sip", value := .questionParticle }
  , { walsCode := "sng", iso := "snc", value := .questionParticle }
  , { walsCode := "sio", iso := "xsi", value := .questionParticle }
  , { walsCode := "qum", iso := "qum", value := .questionParticle }
  , { walsCode := "srn", iso := "srq", value := .questionParticle }
  , { walsCode := "sro", iso := "ssd", value := .questionParticle }
  , { walsCode := "sis", iso := "baa", value := .questionParticle }
  , { walsCode := "siu", iso := "sis", value := .questionParticle }
  , { walsCode := "sko", iso := "skv", value := .questionParticle }
  , { walsCode := "sla", iso := "den", value := .questionParticle }
  , { walsCode := "slo", iso := "slv", value := .questionParticle }
  , { walsCode := "so", iso := "teu", value := .questionParticle }
  , { walsCode := "sob", iso := "sob", value := .questionParticle }
  , { walsCode := "som", iso := "som", value := .questionParticle }
  , { walsCode := "snn", iso := "snk", value := .questionParticle }
  , { walsCode := "son", iso := "sov", value := .questionParticle }
  , { walsCode := "sgb", iso := "mnx", value := .questionParticle }
  , { walsCode := "sea", iso := "tvk", value := .interrogativeIntonationOnly }
  , { walsCode := "spa", iso := "spa", value := .interrogativeWordOrder }
  , { walsCode := "squ", iso := "squ", value := .questionParticle }
  , { walsCode := "sre", iso := "kpm", value := .questionParticle }
  , { walsCode := "sti", iso := "", value := .questionParticle }
  , { walsCode := "sud", iso := "tgo", value := .interrogativeIntonationOnly }
  , { walsCode := "sue", iso := "sue", value := .interrogativeVerbMorphology }
  , { walsCode := "sul", iso := "sua", value := .interrogativeIntonationOnly }
  , { walsCode := "slg", iso := "suv", value := .questionParticle }
  , { walsCode := "sun", iso := "sun", value := .questionParticle }
  , { walsCode := "sup", iso := "spp", value := .questionParticle }
  , { walsCode := "swa", iso := "swh", value := .questionParticle }
  , { walsCode := "swt", iso := "ssw", value := .questionParticle }
  , { walsCode := "swe", iso := "swe", value := .interrogativeWordOrder }
  , { walsCode := "tab", iso := "mky", value := .interrogativeIntonationOnly }
  , { walsCode := "tbw", iso := "tap", value := .interrogativeIntonationOnly }
  , { walsCode := "tac", iso := "tna", value := .questionParticle }
  , { walsCode := "tag", iso := "tgl", value := .questionParticle }
  , { walsCode := "tah", iso := "tah", value := .questionParticle }
  , { walsCode := "taf", iso := "sps", value := .interrogativeIntonationOnly }
  , { walsCode := "taj", iso := "tgk", value := .questionParticle }
  , { walsCode := "tkl", iso := "tkm", value := .questionParticle }
  , { walsCode := "tak", iso := "tbc", value := .questionParticle }
  , { walsCode := "tam", iso := "taj", value := .questionParticle }
  , { walsCode := "tsk", iso := "taq", value := .questionParticle }
  , { walsCode := "tml", iso := "tam", value := .interrogativeVerbMorphology }
  , { walsCode := "tbx", iso := "skj", value := .interrogativeVerbMorphology }
  , { walsCode := "twe", iso := "tac", value := .questionParticle }
  , { walsCode := "tao", iso := "tro", value := .questionParticle }
  , { walsCode := "tar", iso := "tae", value := .interrogativeIntonationOnly }
  , { walsCode := "tas", iso := "shi", value := .mixtureOfPreviousTwoTypes }
  , { walsCode := "tat", iso := "txx", value := .questionParticle }
  , { walsCode := "tvo", iso := "tat", value := .questionParticle }
  , { walsCode := "tau", iso := "tya", value := .questionParticle }
  , { walsCode := "tbo", iso := "tbl", value := .questionParticle }
  , { walsCode := "tel", iso := "tel", value := .interrogativeVerbMorphology }
  , { walsCode := "tne", iso := "tem", value := .questionParticle }
  , { walsCode := "ten", iso := "tex", value := .interrogativeIntonationOnly }
  , { walsCode := "tny", iso := "kza", value := .questionParticle }
  , { walsCode := "teo", iso := "tio", value := .interrogativeIntonationOnly }
  , { walsCode := "tee", iso := "tee", value := .questionParticle }
  , { walsCode := "tpn", iso := "ntp", value := .questionParticle }
  , { walsCode := "tps", iso := "stp", value := .interrogativeIntonationOnly }
  , { walsCode := "ter", iso := "ttr", value := .questionParticle }
  , { walsCode := "trb", iso := "tfr", value := .questionParticle }
  , { walsCode := "tet", iso := "tll", value := .questionParticle }
  , { walsCode := "ttn", iso := "tet", value := .questionParticle }
  , { walsCode := "tha", iso := "tha", value := .questionParticle }
  , { walsCode := "tho", iso := "thp", value := .questionParticle }
  , { walsCode := "tmo", iso := "bod", value := .interrogativeVerbMorphology }
  , { walsCode := "tib", iso := "bod", value := .questionParticle }
  , { walsCode := "tid", iso := "tvo", value := .interrogativeIntonationOnly }
  , { walsCode := "tgk", iso := "tgc", value := .questionParticle }
  , { walsCode := "tja", iso := "dih", value := .questionParticle }
  , { walsCode := "tim", iso := "tih", value := .questionParticle }
  , { walsCode := "tni", iso := "lbf", value := .interrogativeVerbMorphology }
  , { walsCode := "tin", iso := "cir", value := .questionParticle }
  , { walsCode := "tir", iso := "tri", value := .interrogativeIntonationOnly }
  , { walsCode := "tiw", iso := "tiw", value := .questionParticle }
  , { walsCode := "tlp", iso := "tcf", value := .questionParticle }
  , { walsCode := "tob", iso := "tob", value := .interrogativeIntonationOnly }
  , { walsCode := "tbt", iso := "tti", value := .interrogativeIntonationOnly }
  , { walsCode := "tke", iso := "tkl", value := .interrogativeIntonationOnly }
  , { walsCode := "tla", iso := "ksd", value := .questionParticle }
  , { walsCode := "toz", iso := "toi", value := .questionParticle }
  , { walsCode := "ton", iso := "tqw", value := .interrogativeVerbMorphology }
  , { walsCode := "txj", iso := "too", value := .questionParticle }
  , { walsCode := "tri", iso := "trc", value := .questionParticle }
  , { walsCode := "tsf", iso := "cof", value := .interrogativeVerbMorphology }
  , { walsCode := "tsz", iso := "ddo", value := .interrogativeVerbMorphology }
  , { walsCode := "tgl", iso := "tsj", value := .questionParticle }
  , { walsCode := "tsi", iso := "tsi", value := .interrogativeIntonationOnly }
  , { walsCode := "tsn", iso := "tso", value := .questionParticle }
  , { walsCode := "ttu", iso := "bbl", value := .questionParticle }
  , { walsCode := "tai", iso := "thz", value := .interrogativeIntonationOnly }
  , { walsCode := "tgh", iso := "thv", value := .questionParticle }
  , { walsCode := "tbu", iso := "", value := .questionParticle }
  , { walsCode := "tuc", iso := "tuo", value := .interrogativeVerbMorphology }
  , { walsCode := "tuk", iso := "", value := .questionParticle }
  , { walsCode := "tnn", iso := "tvu", value := .questionParticle }
  , { walsCode := "tun", iso := "tun", value := .interrogativeVerbMorphology }
  , { walsCode := "tna", iso := "tuv", value := .questionParticle }
  , { walsCode := "tur", iso := "tur", value := .questionParticle }
  , { walsCode := "tus", iso := "tus", value := .questionParticle }
  , { walsCode := "tte", iso := "tta", value := .interrogativeVerbMorphology }
  , { walsCode := "tvt", iso := "tvt", value := .questionParticle }
  , { walsCode := "tvl", iso := "tvl", value := .interrogativeIntonationOnly }
  , { walsCode := "tuv", iso := "tyv", value := .questionParticle }
  , { walsCode := "tuy", iso := "tue", value := .interrogativeVerbMorphology }
  , { walsCode := "tzo", iso := "tzo", value := .questionParticle }
  , { walsCode := "tzu", iso := "tzj", value := .questionParticle }
  , { walsCode := "tsh", iso := "par", value := .questionParticle }
  , { walsCode := "uby", iso := "uby", value := .interrogativeVerbMorphology }
  , { walsCode := "udh", iso := "ude", value := .interrogativeIntonationOnly }
  , { walsCode := "ukr", iso := "ukr", value := .questionParticle }
  , { walsCode := "uld", iso := "udl", value := .questionParticle }
  , { walsCode := "uli", iso := "uli", value := .interrogativeIntonationOnly }
  , { walsCode := "una", iso := "mtg", value := .interrogativeVerbMorphology }
  , { walsCode := "url", iso := "urk", value := .questionParticle }
  , { walsCode := "urt", iso := "urt", value := .questionParticle }
  , { walsCode := "urd", iso := "urd", value := .questionParticle }
  , { walsCode := "urk", iso := "urb", value := .questionParticle }
  , { walsCode := "usa", iso := "wnu", value := .interrogativeIntonationOnly }
  , { walsCode := "usr", iso := "usa", value := .interrogativeVerbMorphology }
  , { walsCode := "ute", iso := "ute", value := .questionParticle }
  , { walsCode := "uzb", iso := "", value := .interrogativeVerbMorphology }
  , { walsCode := "vie", iso := "vie", value := .questionParticle }
  , { walsCode := "vnm", iso := "vnm", value := .interrogativeIntonationOnly }
  , { walsCode := "wwa", iso := "wwa", value := .questionParticle }
  , { walsCode := "wah", iso := "", value := .questionParticle }
  , { walsCode := "wak", iso := "wbl", value := .interrogativeVerbMorphology }
  , { walsCode := "wal", iso := "van", value := .questionParticle }
  , { walsCode := "wbn", iso := "wms", value := .questionParticle }
  , { walsCode := "wao", iso := "auc", value := .interrogativeVerbMorphology }
  , { walsCode := "wap", iso := "wao", value := .interrogativeVerbMorphology }
  , { walsCode := "wra", iso := "wba", value := .interrogativeVerbMorphology }
  , { walsCode := "wrk", iso := "gae", value := .interrogativeWordOrder }
  , { walsCode := "war", iso := "pav", value := .interrogativeIntonationOnly }
  , { walsCode := "wrl", iso := "wbp", value := .questionParticle }
  , { walsCode := "wrn", iso := "wnd", value := .interrogativeIntonationOnly }
  , { walsCode := "wrg", iso := "wgy", value := .interrogativeIntonationOnly }
  , { walsCode := "was", iso := "was", value := .questionParticle }
  , { walsCode := "wsk", iso := "wsk", value := .questionParticle }
  , { walsCode := "wtm", iso := "wax", value := .interrogativeVerbMorphology }
  , { walsCode := "wth", iso := "wth", value := .questionParticle }
  , { walsCode := "way", iso := "oym", value := .questionParticle }
  , { walsCode := "wel", iso := "cym", value := .questionParticle }
  , { walsCode := "wem", iso := "xww", value := .interrogativeIntonationOnly }
  , { walsCode := "wma", iso := "mqs", value := .interrogativeIntonationOnly }
  , { walsCode := "wic", iso := "wic", value := .questionParticle }
  , { walsCode := "wch", iso := "mzh", value := .questionParticle }
  , { walsCode := "wn", iso := "wig", value := .questionParticle }
  , { walsCode := "wik", iso := "yok", value := .questionParticle }
  , { walsCode := "wiy", iso := "wiy", value := .questionParticle }
  , { walsCode := "wly", iso := "wal", value := .interrogativeVerbMorphology }
  , { walsCode := "wol", iso := "woe", value := .interrogativeIntonationOnly }
  , { walsCode := "wlf", iso := "wol", value := .questionParticle }
  , { walsCode := "xas", iso := "kao", value := .questionParticle }
  , { walsCode := "xav", iso := "xav", value := .questionParticle }
  , { walsCode := "xho", iso := "xho", value := .questionParticle }
  , { walsCode := "ygr", iso := "ygr", value := .questionParticle }
  , { walsCode := "yag", iso := "yad", value := .questionParticle }
  , { walsCode := "yal", iso := "kkl", value := .interrogativeVerbMorphology }
  , { walsCode := "yap", iso := "yap", value := .interrogativeIntonationOnly }
  , { walsCode := "yqy", iso := "jaq", value := .questionParticle }
  , { walsCode := "yaq", iso := "yaq", value := .questionParticle }
  , { walsCode := "yar", iso := "yrb", value := .questionParticle }
  , { walsCode := "ywl", iso := "yok", value := .questionParticle }
  , { walsCode := "yiw", iso := "ywq", value := .questionParticle }
  , { walsCode := "yid", iso := "yii", value := .interrogativeIntonationOnly }
  , { walsCode := "yin", iso := "yij", value := .questionParticle }
  , { walsCode := "yng", iso := "yia", value := .interrogativeIntonationOnly }
  , { walsCode := "yok", iso := "yok", value := .questionParticle }
  , { walsCode := "yor", iso := "yor", value := .interrogativeIntonationOnly }
  , { walsCode := "yuc", iso := "yuc", value := .questionParticle }
  , { walsCode := "yko", iso := "yux", value := .interrogativeIntonationOnly }
  , { walsCode := "yuk", iso := "gcd", value := .questionParticle }
  , { walsCode := "yul", iso := "yul", value := .questionParticle }
  , { walsCode := "ypk", iso := "esu", value := .questionParticle }
  , { walsCode := "yur", iso := "yur", value := .questionParticle }
  , { walsCode := "yuw", iso := "kld", value := .questionParticle }
  , { walsCode := "zai", iso := "zai", value := .questionParticle }
  , { walsCode := "zap", iso := "zaw", value := .questionParticle }
  , { walsCode := "zya", iso := "zav", value := .questionParticle }
  , { walsCode := "zzo", iso := "zpq", value := .interrogativeIntonationOnly }
  , { walsCode := "zay", iso := "zay", value := .absenceOfDeclarativeMorphemes }
  , { walsCode := "zaz", iso := "diq", value := .interrogativeIntonationOnly }
  , { walsCode := "zhn", iso := "zgb", value := .questionParticle }
  , { walsCode := "zch", iso := "zoh", value := .interrogativeIntonationOnly }
  , { walsCode := "zqc", iso := "zoc", value := .interrogativeVerbMorphology }
  , { walsCode := "zul", iso := "zul", value := .questionParticle }
  , { walsCode := "eme", iso := "eme", value := .questionParticle }
  , { walsCode := "omi", iso := "aom", value := .questionParticle }
  ]

/-- Complete WALS 116A dataset (955 languages). -/
def allData : List (Datapoint PolarQuestionType) := allData_0 ++ allData_1

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F116A
