import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 119A: Nominal and Locational Predication
@cite{stassen-2013b}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 119A`.

Chapter 119, 386 languages.
-/

namespace Core.WALS.F119A

/-- WALS 119A values. -/
inductive NominalLocationalPredication where
  /-- Different (269 languages). -/
  | different
  /-- Identical (117 languages). -/
  | identical
  deriving DecidableEq, BEq, Repr

/-- Complete WALS 119A dataset (386 languages). -/
def allData : List (Datapoint NominalLocationalPredication) :=
  [ { walsCode := "abz", iso := "abq", value := .different }
  , { walsCode := "abk", iso := "abk", value := .different }
  , { walsCode := "ace", iso := "ace", value := .different }
  , { walsCode := "acl", iso := "ach", value := .different }
  , { walsCode := "acm", iso := "acv", value := .different }
  , { walsCode := "aco", iso := "kjq", value := .different }
  , { walsCode := "ady", iso := "ady", value := .different }
  , { walsCode := "ahu", iso := "ahh", value := .identical }
  , { walsCode := "ain", iso := "ain", value := .different }
  , { walsCode := "akn", iso := "aka", value := .different }
  , { walsCode := "abm", iso := "akz", value := .different }
  , { walsCode := "ala", iso := "amp", value := .different }
  , { walsCode := "alb", iso := "sqi", value := .identical }
  , { walsCode := "ame", iso := "aey", value := .different }
  , { walsCode := "amh", iso := "amh", value := .identical }
  , { walsCode := "agm", iso := "njm", value := .different }
  , { walsCode := "apl", iso := "apy", value := .identical }
  , { walsCode := "aeg", iso := "arz", value := .identical }
  , { walsCode := "amr", iso := "ary", value := .identical }
  , { walsCode := "arp", iso := "ape", value := .different }
  , { walsCode := "arc", iso := "aqc", value := .identical }
  , { walsCode := "arm", iso := "hye", value := .identical }
  , { walsCode := "aro", iso := "aia", value := .different }
  , { walsCode := "amp", iso := "aer", value := .identical }
  , { walsCode := "asm", iso := "cns", value := .identical }
  , { walsCode := "ava", iso := "ava", value := .identical }
  , { walsCode := "awp", iso := "kwi", value := .identical }
  , { walsCode := "awt", iso := "kmn", value := .different }
  , { walsCode := "bab", iso := "bav", value := .identical }
  , { walsCode := "bag", iso := "bmi", value := .different }
  , { walsCode := "blc", iso := "bgn", value := .identical }
  , { walsCode := "bam", iso := "bam", value := .different }
  , { walsCode := "baa", iso := "bbb", value := .different }
  , { walsCode := "brs", iso := "bsn", value := .identical }
  , { walsCode := "bar", iso := "bfa", value := .different }
  , { walsCode := "bsq", iso := "eus", value := .different }
  , { walsCode := "bto", iso := "bbc", value := .different }
  , { walsCode := "bej", iso := "bej", value := .identical }
  , { walsCode := "ben", iso := "ben", value := .identical }
  , { walsCode := "bma", iso := "tzm", value := .different }
  , { walsCode := "bik", iso := "bhw", value := .different }
  , { walsCode := "bln", iso := "byn", value := .identical }
  , { walsCode := "blx", iso := "bll", value := .different }
  , { walsCode := "bla", iso := "bla", value := .different }
  , { walsCode := "bod", iso := "brx", value := .different }
  , { walsCode := "bgo", iso := "bot", value := .different }
  , { walsCode := "brr", iso := "bor", value := .different }
  , { walsCode := "bre", iso := "bre", value := .identical }
  , { walsCode := "bri", iso := "bzd", value := .different }
  , { walsCode := "bul", iso := "bul", value := .identical }
  , { walsCode := "bui", iso := "bzq", value := .different }
  , { walsCode := "but", iso := "bxm", value := .identical }
  , { walsCode := "brj", iso := "bji", value := .different }
  , { walsCode := "brm", iso := "mya", value := .different }
  , { walsCode := "bur", iso := "bsk", value := .identical }
  , { walsCode := "cah", iso := "chl", value := .different }
  , { walsCode := "cnl", iso := "ram", value := .different }
  , { walsCode := "car", iso := "car", value := .identical }
  , { walsCode := "ceb", iso := "ceb", value := .different }
  , { walsCode := "cha", iso := "cha", value := .different }
  , { walsCode := "cso", iso := "ctp", value := .different }
  , { walsCode := "chc", iso := "che", value := .identical }
  , { walsCode := "cmh", iso := "ute", value := .different }
  , { walsCode := "che", iso := "chr", value := .different }
  , { walsCode := "cmr", iso := "mrh", value := .different }
  , { walsCode := "ccm", iso := "cco", value := .different }
  , { walsCode := "cct", iso := "cho", value := .different }
  , { walsCode := "chr", iso := "crw", value := .different }
  , { walsCode := "chk", iso := "ckt", value := .different }
  , { walsCode := "cbo", iso := "cao", value := .identical }
  , { walsCode := "cil", iso := "lua", value := .identical }
  , { walsCode := "ccp", iso := "coc", value := .identical }
  , { walsCode := "coo", iso := "csz", value := .different }
  , { walsCode := "cop", iso := "cop", value := .different }
  , { walsCode := "cre", iso := "crk", value := .different }
  , { walsCode := "cro", iso := "cro", value := .different }
  , { walsCode := "cze", iso := "ces", value := .identical }
  , { walsCode := "dab", iso := "dbq", value := .different }
  , { walsCode := "dag", iso := "dgz", value := .identical }
  , { walsCode := "dgb", iso := "dag", value := .different }
  , { walsCode := "din", iso := "din", value := .different }
  , { walsCode := "diy", iso := "dif", value := .identical }
  , { walsCode := "diz", iso := "mdx", value := .different }
  , { walsCode := "dua", iso := "dua", value := .identical }
  , { walsCode := "dmi", iso := "dus", value := .different }
  , { walsCode := "dut", iso := "nld", value := .identical }
  , { walsCode := "dyi", iso := "dbl", value := .different }
  , { walsCode := "eka", iso := "ekg", value := .identical }
  , { walsCode := "eng", iso := "eng", value := .identical }
  , { walsCode := "epe", iso := "sja", value := .different }
  , { walsCode := "est", iso := "ekk", value := .identical }
  , { walsCode := "evn", iso := "eve", value := .identical }
  , { walsCode := "eve", iso := "evn", value := .identical }
  , { walsCode := "ewe", iso := "ewe", value := .different }
  , { walsCode := "fij", iso := "fij", value := .different }
  , { walsCode := "fin", iso := "fin", value := .identical }
  , { walsCode := "frd", iso := "frd", value := .different }
  , { walsCode := "for", iso := "for", value := .different }
  , { walsCode := "fre", iso := "fra", value := .identical }
  , { walsCode := "fni", iso := "fuv", value := .different }
  , { walsCode := "gae", iso := "gla", value := .different }
  , { walsCode := "gll", iso := "gbi", value := .different }
  , { walsCode := "gar", iso := "grt", value := .different }
  , { walsCode := "gbb", iso := "gbp", value := .different }
  , { walsCode := "geo", iso := "kat", value := .identical }
  , { walsCode := "nbh", iso := "ghl", value := .different }
  , { walsCode := "goa", iso := "guc", value := .different }
  , { walsCode := "gdi", iso := "god", value := .different }
  , { walsCode := "god", iso := "gdo", value := .identical }
  , { walsCode := "gol", iso := "gol", value := .different }
  , { walsCode := "grb", iso := "grj", value := .different }
  , { walsCode := "grk", iso := "ell", value := .identical }
  , { walsCode := "grw", iso := "kal", value := .different }
  , { walsCode := "gjj", iso := "gub", value := .different }
  , { walsCode := "gua", iso := "gug", value := .different }
  , { walsCode := "gud", iso := "gde", value := .different }
  , { walsCode := "gum", iso := "kgs", value := .different }
  , { walsCode := "grn", iso := "gur", value := .different }
  , { walsCode := "guu", iso := "kky", value := .different }
  , { walsCode := "hcr", iso := "hat", value := .different }
  , { walsCode := "hmr", iso := "amf", value := .different }
  , { walsCode := "hau", iso := "hau", value := .different }
  , { walsCode := "heb", iso := "heb", value := .identical }
  , { walsCode := "hei", iso := "hei", value := .different }
  , { walsCode := "hin", iso := "hin", value := .identical }
  , { walsCode := "hix", iso := "hix", value := .identical }
  , { walsCode := "hop", iso := "hop", value := .different }
  , { walsCode := "hui", iso := "hch", value := .different }
  , { walsCode := "hun", iso := "hun", value := .identical }
  , { walsCode := "hzb", iso := "huz", value := .identical }
  , { walsCode := "hup", iso := "hup", value := .identical }
  , { walsCode := "iaa", iso := "iai", value := .different }
  , { walsCode := "ice", iso := "isl", value := .identical }
  , { walsCode := "igb", iso := "ibo", value := .different }
  , { walsCode := "ik", iso := "ikx", value := .different }
  , { walsCode := "ilo", iso := "ilo", value := .different }
  , { walsCode := "imo", iso := "imn", value := .different }
  , { walsCode := "ind", iso := "ind", value := .different }
  , { walsCode := "irq", iso := "irk", value := .different }
  , { walsCode := "iri", iso := "gle", value := .different }
  , { walsCode := "iwa", iso := "ibd", value := .different }
  , { walsCode := "jab", iso := "jae", value := .different }
  , { walsCode := "jak", iso := "jac", value := .different }
  , { walsCode := "jpn", iso := "jpn", value := .different }
  , { walsCode := "jeb", iso := "jeb", value := .different }
  , { walsCode := "juh", iso := "ktz", value := .identical }
  , { walsCode := "kab", iso := "kbd", value := .different }
  , { walsCode := "kbl", iso := "kab", value := .different }
  , { walsCode := "kls", iso := "fla", value := .different }
  , { walsCode := "kgu", iso := "ktg", value := .different }
  , { walsCode := "knk", iso := "kna", value := .different }
  , { walsCode := "knd", iso := "kan", value := .identical }
  , { walsCode := "knr", iso := "knc", value := .different }
  , { walsCode := "kpm", iso := "pam", value := .different }
  , { walsCode := "krk", iso := "kyh", value := .different }
  , { walsCode := "ksm", iso := "xsm", value := .different }
  , { walsCode := "ktl", iso := "kcr", value := .different }
  , { walsCode := "ket", iso := "ket", value := .different }
  , { walsCode := "kew", iso := "kew", value := .different }
  , { walsCode := "kha", iso := "khk", value := .identical }
  , { walsCode := "kty", iso := "kca", value := .identical }
  , { walsCode := "khs", iso := "kha", value := .different }
  , { walsCode := "khm", iso := "khm", value := .different }
  , { walsCode := "kic", iso := "kic", value := .different }
  , { walsCode := "klv", iso := "kij", value := .different }
  , { walsCode := "kio", iso := "kio", value := .different }
  , { walsCode := "kob", iso := "kpw", value := .identical }
  , { walsCode := "kta", iso := "kqi", value := .different }
  , { walsCode := "kzy", iso := "kpv", value := .identical }
  , { walsCode := "kko", iso := "knk", value := .different }
  , { walsCode := "kor", iso := "kor", value := .different }
  , { walsCode := "kku", iso := "kfq", value := .identical }
  , { walsCode := "kpe", iso := "xpe", value := .different }
  , { walsCode := "kro", iso := "kgo", value := .different }
  , { walsCode := "knm", iso := "kun", value := .different }
  , { walsCode := "kur", iso := "kru", value := .different }
  , { walsCode := "kwa", iso := "kwd", value := .different }
  , { walsCode := "kwk", iso := "kwk", value := .different }
  , { walsCode := "kat", iso := "kmg", value := .different }
  , { walsCode := "lad", iso := "lbj", value := .different }
  , { walsCode := "lah", iso := "lhu", value := .different }
  , { walsCode := "lkt", iso := "lkt", value := .different }
  , { walsCode := "lao", iso := "lao", value := .different }
  , { walsCode := "lat", iso := "lav", value := .identical }
  , { walsCode := "laz", iso := "lzz", value := .identical }
  , { walsCode := "len", iso := "tnl", value := .different }
  , { walsCode := "lep", iso := "lep", value := .different }
  , { walsCode := "lez", iso := "lez", value := .different }
  , { walsCode := "lil", iso := "lil", value := .different }
  , { walsCode := "lnd", iso := "liy", value := .different }
  , { walsCode := "lis", iso := "lis", value := .different }
  , { walsCode := "lit", iso := "lit", value := .identical }
  , { walsCode := "lon", iso := "los", value := .different }
  , { walsCode := "lnw", iso := "crc", value := .different }
  , { walsCode := "lda", iso := "lug", value := .identical }
  , { walsCode := "luo", iso := "luo", value := .different }
  , { walsCode := "maa", iso := "mas", value := .different }
  , { walsCode := "mac", iso := "mbc", value := .identical }
  , { walsCode := "mal", iso := "plt", value := .different }
  , { walsCode := "mlk", iso := "mpb", value := .different }
  , { walsCode := "mym", iso := "mal", value := .different }
  , { walsCode := "mlt", iso := "mlt", value := .identical }
  , { walsCode := "mam", iso := "mam", value := .different }
  , { walsCode := "mnm", iso := "mva", value := .different }
  , { walsCode := "mnc", iso := "mnc", value := .different }
  , { walsCode := "mnd", iso := "cmn", value := .different }
  , { walsCode := "myi", iso := "mpc", value := .identical }
  , { walsCode := "mbt", iso := "mdj", value := .identical }
  , { walsCode := "mng", iso := "mqy", value := .different }
  , { walsCode := "maw", iso := "mlq", value := .different }
  , { walsCode := "mwb", iso := "mbb", value := .different }
  , { walsCode := "mns", iso := "mns", value := .identical }
  , { walsCode := "mao", iso := "mri", value := .different }
  , { walsCode := "map", iso := "arn", value := .different }
  , { walsCode := "mku", iso := "zmr", value := .different }
  , { walsCode := "mrg", iso := "mrt", value := .different }
  , { walsCode := "mme", iso := "mhr", value := .identical }
  , { walsCode := "mrd", iso := "mrz", value := .identical }
  , { walsCode := "mka", iso := "mxx", value := .different }
  , { walsCode := "mau", iso := "mph", value := .different }
  , { walsCode := "mei", iso := "mni", value := .different }
  , { walsCode := "men", iso := "mez", value := .different }
  , { walsCode := "mie", iso := "ium", value := .different }
  , { walsCode := "mis", iso := "miq", value := .identical }
  , { walsCode := "mxp", iso := "mil", value := .different }
  , { walsCode := "miz", iso := "lus", value := .different }
  , { walsCode := "moj", iso := "mov", value := .identical }
  , { walsCode := "mok", iso := "mkj", value := .different }
  , { walsCode := "moo", iso := "mos", value := .different }
  , { walsCode := "moe", iso := "myv", value := .identical }
  , { walsCode := "mou", iso := "mgd", value := .different }
  , { walsCode := "mtu", iso := "meu", value := .different }
  , { walsCode := "mun", iso := "unr", value := .different }
  , { walsCode := "mrl", iso := "mur", value := .different }
  , { walsCode := "mut", iso := "css", value := .different }
  , { walsCode := "nht", iso := "nhg", value := .identical }
  , { walsCode := "nak", iso := "nak", value := .different }
  , { walsCode := "kho", iso := "naq", value := .different }
  , { walsCode := "nbb", iso := "nmb", value := .different }
  , { walsCode := "nai", iso := "gld", value := .identical }
  , { walsCode := "nar", iso := "nrb", value := .different }
  , { walsCode := "nas", iso := "nas", value := .different }
  , { walsCode := "nav", iso := "nav", value := .different }
  , { walsCode := "ntu", iso := "yrk", value := .identical }
  , { walsCode := "nep", iso := "npi", value := .different }
  , { walsCode := "nez", iso := "nez", value := .identical }
  , { walsCode := "ngl", iso := "nig", value := .identical }
  , { walsCode := "ngk", iso := "nam", value := .identical }
  , { walsCode := "ndi", iso := "ngb", value := .different }
  , { walsCode := "ngi", iso := "wyb", value := .identical }
  , { walsCode := "ngz", iso := "ngi", value := .different }
  , { walsCode := "nca", iso := "caq", value := .different }
  , { walsCode := "niu", iso := "niu", value := .different }
  , { walsCode := "niv", iso := "niv", value := .different }
  , { walsCode := "nko", iso := "cgg", value := .identical }
  , { walsCode := "nue", iso := "nus", value := .different }
  , { walsCode := "nup", iso := "nup", value := .different }
  , { walsCode := "nuu", iso := "nuk", value := .different }
  , { walsCode := "ood", iso := "ood", value := .different }
  , { walsCode := "ojs", iso := "ojs", value := .different }
  , { walsCode := "ond", iso := "one", value := .different }
  , { walsCode := "orh", iso := "hae", value := .identical }
  , { walsCode := "otm", iso := "ote", value := .different }
  , { walsCode := "otr", iso := "otr", value := .different }
  , { walsCode := "pms", iso := "pma", value := .different }
  , { walsCode := "pai", iso := "pwn", value := .different }
  , { walsCode := "plr", iso := "fap", value := .different }
  , { walsCode := "pna", iso := "pmf", value := .different }
  , { walsCode := "pap", iso := "pap", value := .different }
  , { walsCode := "prd", iso := "pci", value := .different }
  , { walsCode := "ptp", iso := "gfk", value := .different }
  , { walsCode := "plh", iso := "plh", value := .different }
  , { walsCode := "pau", iso := "pad", value := .different }
  , { walsCode := "pwn", iso := "paw", value := .identical }
  , { walsCode := "prs", iso := "pes", value := .identical }
  , { walsCode := "pir", iso := "pib", value := .different }
  , { walsCode := "pit", iso := "pjt", value := .different }
  , { walsCode := "pol", iso := "pol", value := .identical }
  , { walsCode := "pop", iso := "pbe", value := .different }
  , { walsCode := "qcu", iso := "quz", value := .identical }
  , { walsCode := "qim", iso := "qvi", value := .identical }
  , { walsCode := "ram", iso := "rma", value := .identical }
  , { walsCode := "ras", iso := "ras", value := .different }
  , { walsCode := "rem", iso := "bfw", value := .different }
  , { walsCode := "ret", iso := "tnc", value := .identical }
  , { walsCode := "rka", iso := "rmy", value := .identical }
  , { walsCode := "rom", iso := "ron", value := .identical }
  , { walsCode := "rti", iso := "twu", value := .different }
  , { walsCode := "rot", iso := "rtm", value := .different }
  , { walsCode := "rus", iso := "rus", value := .identical }
  , { walsCode := "smt", iso := "uma", value := .identical }
  , { walsCode := "sal", iso := "sln", value := .different }
  , { walsCode := "sam", iso := "smo", value := .different }
  , { walsCode := "snm", iso := "xsu", value := .identical }
  , { walsCode := "sed", iso := "sed", value := .different }
  , { walsCode := "sel", iso := "ona", value := .different }
  , { walsCode := "skp", iso := "sel", value := .identical }
  , { walsCode := "snc", iso := "see", value := .different }
  , { walsCode := "snt", iso := "set", value := .different }
  , { walsCode := "scr", iso := "hbs", value := .identical }
  , { walsCode := "sey", iso := "crs", value := .different }
  , { walsCode := "shl", iso := "shk", value := .different }
  , { walsCode := "shk", iso := "shp", value := .identical }
  , { walsCode := "shn", iso := "sna", value := .identical }
  , { walsCode := "sng", iso := "snc", value := .different }
  , { walsCode := "snh", iso := "sin", value := .different }
  , { walsCode := "sro", iso := "ssd", value := .identical }
  , { walsCode := "siu", iso := "sis", value := .different }
  , { walsCode := "sla", iso := "den", value := .different }
  , { walsCode := "som", iso := "som", value := .different }
  , { walsCode := "sor", iso := "srb", value := .different }
  , { walsCode := "spa", iso := "spa", value := .different }
  , { walsCode := "squ", iso := "squ", value := .different }
  , { walsCode := "sra", iso := "srn", value := .different }
  , { walsCode := "sre", iso := "kpm", value := .different }
  , { walsCode := "sun", iso := "sun", value := .different }
  , { walsCode := "sup", iso := "spp", value := .different }
  , { walsCode := "swa", iso := "swh", value := .identical }
  , { walsCode := "swe", iso := "swe", value := .identical }
  , { walsCode := "tag", iso := "tgl", value := .different }
  , { walsCode := "tah", iso := "tah", value := .different }
  , { walsCode := "tml", iso := "tam", value := .identical }
  , { walsCode := "tas", iso := "shi", value := .different }
  , { walsCode := "tvo", iso := "tat", value := .identical }
  , { walsCode := "tel", iso := "tel", value := .identical }
  , { walsCode := "tmr", iso := "tea", value := .different }
  , { walsCode := "tne", iso := "tem", value := .different }
  , { walsCode := "tep", iso := "tpt", value := .different }
  , { walsCode := "tes", iso := "teo", value := .different }
  , { walsCode := "tha", iso := "tha", value := .different }
  , { walsCode := "tgk", iso := "tgc", value := .different }
  , { walsCode := "tgr", iso := "tig", value := .identical }
  , { walsCode := "tiv", iso := "tiv", value := .different }
  , { walsCode := "tiw", iso := "tiw", value := .different }
  , { walsCode := "tli", iso := "tli", value := .identical }
  , { walsCode := "tpi", iso := "tpi", value := .different }
  , { walsCode := "tla", iso := "ksd", value := .different }
  , { walsCode := "tno", iso := "tdn", value := .different }
  , { walsCode := "tng", iso := "ton", value := .different }
  , { walsCode := "tot", iso := "tlc", value := .different }
  , { walsCode := "tug", iso := "thv", value := .different }
  , { walsCode := "tbu", iso := "", value := .different }
  , { walsCode := "tuk", iso := "", value := .different }
  , { walsCode := "tup", iso := "tpn", value := .different }
  , { walsCode := "tna", iso := "tuv", value := .different }
  , { walsCode := "tur", iso := "tur", value := .identical }
  , { walsCode := "tus", iso := "tus", value := .different }
  , { walsCode := "tzo", iso := "tzo", value := .different }
  , { walsCode := "tzu", iso := "tzj", value := .different }
  , { walsCode := "tsh", iso := "par", value := .different }
  , { walsCode := "uby", iso := "uby", value := .different }
  , { walsCode := "ung", iso := "ung", value := .identical }
  , { walsCode := "uhi", iso := "urf", value := .different }
  , { walsCode := "urk", iso := "urb", value := .different }
  , { walsCode := "usa", iso := "wnu", value := .identical }
  , { walsCode := "uzb", iso := "", value := .identical }
  , { walsCode := "vai", iso := "vai", value := .different }
  , { walsCode := "vie", iso := "vie", value := .different }
  , { walsCode := "vot", iso := "vot", value := .identical }
  , { walsCode := "wap", iso := "wao", value := .different }
  , { walsCode := "wrp", iso := "wrp", value := .different }
  , { walsCode := "wsk", iso := "wsk", value := .different }
  , { walsCode := "wau", iso := "noa", value := .identical }
  , { walsCode := "wel", iso := "cym", value := .different }
  , { walsCode := "wic", iso := "wic", value := .identical }
  , { walsCode := "wch", iso := "mzh", value := .different }
  , { walsCode := "wol", iso := "woe", value := .different }
  , { walsCode := "wlo", iso := "wlo", value := .different }
  , { walsCode := "wlf", iso := "wol", value := .different }
  , { walsCode := "ygr", iso := "ygr", value := .identical }
  , { walsCode := "yag", iso := "yad", value := .identical }
  , { walsCode := "ykt", iso := "sah", value := .identical }
  , { walsCode := "yaq", iso := "yaq", value := .different }
  , { walsCode := "yav", iso := "yuf", value := .identical }
  , { walsCode := "yid", iso := "yii", value := .identical }
  , { walsCode := "yim", iso := "yee", value := .different }
  , { walsCode := "yor", iso := "yor", value := .different }
  , { walsCode := "yko", iso := "yux", value := .different }
  , { walsCode := "yur", iso := "yur", value := .different }
  , { walsCode := "yuw", iso := "kld", value := .different }
  , { walsCode := "zan", iso := "zne", value := .different }
  , { walsCode := "zai", iso := "zai", value := .different }
  , { walsCode := "zar", iso := "dje", value := .different }
  , { walsCode := "zaz", iso := "diq", value := .identical }
  , { walsCode := "zqc", iso := "zoc", value := .different }
  , { walsCode := "zul", iso := "zul", value := .identical }
  ]

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F119A
