import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 130A: Finger and Hand
@cite{wals-2013}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 130A`.

Chapter 130, 593 languages.
-/

namespace Core.WALS.F130A

/-- WALS 130A values. -/
inductive FingerAndHand where
  /-- Identical (72 languages). -/
  | identical
  /-- Different (521 languages). -/
  | different
  deriving DecidableEq, BEq, Repr

private def allData_0 : List (Datapoint FingerAndHand) :=
  [ { walsCode := "xoo", iso := "nmn", value := .different }
  , { walsCode := "arx", iso := "alu", value := .different }
  , { walsCode := "abw", iso := "abe", value := .different }
  , { walsCode := "abi", iso := "axb", value := .different }
  , { walsCode := "abk", iso := "abk", value := .different }
  , { walsCode := "acg", iso := "aca", value := .different }
  , { walsCode := "acu", iso := "acu", value := .different }
  , { walsCode := "acm", iso := "acv", value := .different }
  , { walsCode := "afr", iso := "afr", value := .different }
  , { walsCode := "agr", iso := "agr", value := .different }
  , { walsCode := "aht", iso := "aht", value := .different }
  , { walsCode := "abm", iso := "akz", value := .different }
  , { walsCode := "ale", iso := "ale", value := .different }
  , { walsCode := "alg", iso := "alq", value := .different }
  , { walsCode := "atq", iso := "ems", value := .different }
  , { walsCode := "aly", iso := "aly", value := .identical }
  , { walsCode := "amc", iso := "amc", value := .identical }
  , { walsCode := "amk", iso := "amr", value := .different }
  , { walsCode := "amh", iso := "amh", value := .different }
  , { walsCode := "amu", iso := "ame", value := .different }
  , { walsCode := "apc", iso := "apm", value := .different }
  , { walsCode := "apj", iso := "apj", value := .different }
  , { walsCode := "apw", iso := "apw", value := .identical }
  , { walsCode := "api", iso := "apn", value := .different }
  , { walsCode := "amr", iso := "ary", value := .different }
  , { walsCode := "akr", iso := "ari", value := .different }
  , { walsCode := "arw", iso := "hyw", value := .different }
  , { walsCode := "aro", iso := "aia", value := .different }
  , { walsCode := "amp", iso := "aer", value := .identical }
  , { walsCode := "atk", iso := "aqp", value := .identical }
  , { walsCode := "ati", iso := "atj", value := .identical }
  , { walsCode := "ats", iso := "atw", value := .different }
  , { walsCode := "awa", iso := "awb", value := .different }
  , { walsCode := "awp", iso := "kwi", value := .different }
  , { walsCode := "aym", iso := "ayr", value := .different }
  , { walsCode := "ayo", iso := "", value := .different }
  , { walsCode := "aze", iso := "", value := .different }
  , { walsCode := "blj", iso := "koe", value := .different }
  , { walsCode := "bab", iso := "bav", value := .different }
  , { walsCode := "bgr", iso := "fuu", value := .different }
  , { walsCode := "bpb", iso := "bdq", value := .different }
  , { walsCode := "bam", iso := "bam", value := .different }
  , { walsCode := "bnj", iso := "bdy", value := .identical }
  , { walsCode := "bca", iso := "bdy", value := .different }
  , { walsCode := "bwa", iso := "bdy", value := .identical }
  , { walsCode := "byu", iso := "bdy", value := .identical }
  , { walsCode := "bnv", iso := "bvv", value := .different }
  , { walsCode := "brs", iso := "bsn", value := .different }
  , { walsCode := "bae", iso := "bae", value := .different }
  , { walsCode := "mti", iso := "mot", value := .different }
  , { walsCode := "bsq", iso := "eus", value := .different }
  , { walsCode := "blr", iso := "bel", value := .different }
  , { walsCode := "bem", iso := "bem", value := .different }
  , { walsCode := "bnq", iso := "nhb", value := .different }
  , { walsCode := "beo", iso := "bue", value := .identical }
  , { walsCode := "bkl", iso := "bcl", value := .different }
  , { walsCode := "blx", iso := "bll", value := .different }
  , { walsCode := "bkd", iso := "bkd", value := .different }
  , { walsCode := "bla", iso := "bla", value := .different }
  , { walsCode := "bok", iso := "bqc", value := .different }
  , { walsCode := "btk", iso := "lbk", value := .different }
  , { walsCode := "bor", iso := "boa", value := .different }
  , { walsCode := "brc", iso := "brn", value := .different }
  , { walsCode := "bre", iso := "bre", value := .different }
  , { walsCode := "bnb", iso := "bck", value := .identical }
  , { walsCode := "but", iso := "bxm", value := .different }
  , { walsCode := "bur", iso := "bsk", value := .different }
  , { walsCode := "cab", iso := "cjp", value := .different }
  , { walsCode := "cac", iso := "cbv", value := .different }
  , { walsCode := "cah", iso := "chl", value := .identical }
  , { walsCode := "cak", iso := "cak", value := .different }
  , { walsCode := "cax", iso := "", value := .different }
  , { walsCode := "cpa", iso := "cjo", value := .different }
  , { walsCode := "cam", iso := "kbh", value := .different }
  , { walsCode := "cnl", iso := "ram", value := .different }
  , { walsCode := "cnt", iso := "yue", value := .different }
  , { walsCode := "cap", iso := "kaq", value := .different }
  , { walsCode := "crp", iso := "cbc", value := .different }
  , { walsCode := "car", iso := "car", value := .different }
  , { walsCode := "crj", iso := "cbd", value := .identical }
  , { walsCode := "crl", iso := "cal", value := .different }
  , { walsCode := "crq", iso := "crx", value := .different }
  , { walsCode := "cas", iso := "cbr", value := .different }
  , { walsCode := "csh", iso := "cbs", value := .different }
  , { walsCode := "ctl", iso := "cat", value := .different }
  , { walsCode := "ctw", iso := "chc", value := .different }
  , { walsCode := "cat", iso := "cto", value := .different }
  , { walsCode := "cav", iso := "cav", value := .different }
  , { walsCode := "cay", iso := "cbi", value := .different }
  , { walsCode := "ceb", iso := "ceb", value := .different }
  , { walsCode := "cai", iso := "suq", value := .different }
  , { walsCode := "chw", iso := "cja", value := .different }
  , { walsCode := "cha", iso := "cha", value := .different }
  , { walsCode := "ctt", iso := "cta", value := .different }
  , { walsCode := "chy", iso := "cbt", value := .identical }
  , { walsCode := "chl", iso := "cjh", value := .different }
  , { walsCode := "cmh", iso := "ute", value := .different }
  , { walsCode := "che", iso := "chr", value := .different }
  , { walsCode := "cyn", iso := "chy", value := .different }
  , { walsCode := "cck", iso := "cic", value := .different }
  , { walsCode := "cec", iso := "cob", value := .different }
  , { walsCode := "chi", iso := "cid", value := .different }
  , { walsCode := "cma", iso := "cbg", value := .different }
  , { walsCode := "cle", iso := "cle", value := .different }
  , { walsCode := "csf", iso := "cuc", value := .different }
  , { walsCode := "chp", iso := "chp", value := .different }
  , { walsCode := "crg", iso := "gui", value := .different }
  , { walsCode := "cch", iso := "coz", value := .different }
  , { walsCode := "cct", iso := "cho", value := .different }
  , { walsCode := "col", iso := "ctu", value := .different }
  , { walsCode := "cho", iso := "chd", value := .different }
  , { walsCode := "cmy", iso := "chf", value := .different }
  , { walsCode := "crt", iso := "", value := .different }
  , { walsCode := "chr", iso := "crw", value := .different }
  , { walsCode := "chj", iso := "cac", value := .different }
  , { walsCode := "cin", iso := "inz", value := .different }
  , { walsCode := "cuu", iso := "chk", value := .different }
  , { walsCode := "cla", iso := "clm", value := .different }
  , { walsCode := "ccp", iso := "coc", value := .identical }
  , { walsCode := "cof", iso := "con", value := .different }
  , { walsCode := "cog", iso := "kog", value := .different }
  , { walsCode := "clc", iso := "", value := .different }
  , { walsCode := "cmn", iso := "com", value := .different }
  , { walsCode := "cmc", iso := "xcm", value := .identical }
  , { walsCode := "cor", iso := "crn", value := .different }
  , { walsCode := "crn", iso := "cor", value := .different }
  , { walsCode := "cre", iso := "crk", value := .different }
  , { walsCode := "crk", iso := "mus", value := .different }
  , { walsCode := "cro", iso := "cro", value := .different }
  , { walsCode := "cub", iso := "cub", value := .different }
  , { walsCode := "cui", iso := "cui", value := .different }
  , { walsCode := "ctc", iso := "", value := .different }
  , { walsCode := "cut", iso := "cuy", value := .different }
  , { walsCode := "cur", iso := "kpc", value := .different }
  , { walsCode := "cze", iso := "ces", value := .different }
  , { walsCode := "dak", iso := "dak", value := .different }
  , { walsCode := "dam", iso := "mbp", value := .different }
  , { walsCode := "dsh", iso := "dan", value := .different }
  , { walsCode := "dgx", iso := "ing", value := .different }
  , { walsCode := "des", iso := "des", value := .different }
  , { walsCode := "die", iso := "dih", value := .identical }
  , { walsCode := "dig", iso := "mhu", value := .different }
  , { walsCode := "csk", iso := "csk", value := .different }
  , { walsCode := "dja", iso := "dyy", value := .identical }
  , { walsCode := "djp", iso := "dwu", value := .different }
  , { walsCode := "dji", iso := "jig", value := .identical }
  , { walsCode := "dre", iso := "dhv", value := .different }
  , { walsCode := "dca", iso := "dgc", value := .different }
  , { walsCode := "dut", iso := "nld", value := .different }
  , { walsCode := "efi", iso := "efi", value := .different }
  , { walsCode := "eka", iso := "ekg", value := .different }
  , { walsCode := "emb", iso := "emp", value := .different }
  , { walsCode := "ena", iso := "enq", value := .different }
  , { walsCode := "eng", iso := "eng", value := .different }
  , { walsCode := "ese", iso := "ese", value := .different }
  , { walsCode := "eud", iso := "", value := .identical }
  , { walsCode := "eve", iso := "evn", value := .different }
  , { walsCode := "eya", iso := "eya", value := .different }
  , { walsCode := "fij", iso := "fij", value := .different }
  , { walsCode := "fin", iso := "fin", value := .different }
  , { walsCode := "for", iso := "for", value := .different }
  , { walsCode := "fox", iso := "sac", value := .different }
  , { walsCode := "fre", iso := "fra", value := .different }
  , { walsCode := "fut", iso := "fut", value := .different }
  , { walsCode := "gad", iso := "ged", value := .different }
  , { walsCode := "gae", iso := "gla", value := .different }
  , { walsCode := "geo", iso := "kat", value := .different }
  , { walsCode := "ger", iso := "deu", value := .different }
  , { walsCode := "gid", iso := "gih", value := .different }
  , { walsCode := "git", iso := "git", value := .different }
  , { walsCode := "goa", iso := "guc", value := .different }
  , { walsCode := "grk", iso := "ell", value := .different }
  , { walsCode := "gre", iso := "kal", value := .different }
  , { walsCode := "ghb", iso := "guh", value := .different }
  , { walsCode := "gjj", iso := "gub", value := .different }
  , { walsCode := "gmb", iso := "gum", value := .different }
  , { walsCode := "gna", iso := "gva", value := .different }
  , { walsCode := "gno", iso := "gvc", value := .different }
  , { walsCode := "gua", iso := "gug", value := .different }
  , { walsCode := "gto", iso := "gta", value := .different }
  , { walsCode := "gyb", iso := "guo", value := .different }
  , { walsCode := "gul", iso := "kcm", value := .different }
  , { walsCode := "grm", iso := "gux", value := .different }
  , { walsCode := "guu", iso := "kky", value := .different }
  , { walsCode := "gku", iso := "pue", value := .different }
  , { walsCode := "hai", iso := "hai", value := .different }
  , { walsCode := "hau", iso := "hau", value := .different }
  , { walsCode := "haw", iso := "haw", value := .identical }
  , { walsCode := "heb", iso := "heb", value := .different }
  , { walsCode := "hid", iso := "hid", value := .different }
  , { walsCode := "hil", iso := "hil", value := .different }
  , { walsCode := "hmd", iso := "mww", value := .different }
  , { walsCode := "hop", iso := "hop", value := .different }
  , { walsCode := "hmb", iso := "hub", value := .different }
  , { walsCode := "htc", iso := "hus", value := .different }
  , { walsCode := "hve", iso := "huv", value := .different }
  , { walsCode := "hui", iso := "hch", value := .different }
  , { walsCode := "hmi", iso := "hto", value := .different }
  , { walsCode := "hmu", iso := "hux", value := .different }
  , { walsCode := "hum", iso := "huu", value := .different }
  , { walsCode := "hun", iso := "hun", value := .different }
  , { walsCode := "hpd", iso := "jup", value := .different }
  , { walsCode := "hup", iso := "hup", value := .identical }
  , { walsCode := "ifu", iso := "ifb", value := .different }
  , { walsCode := "igb", iso := "ibo", value := .different }
  , { walsCode := "ik", iso := "ikx", value := .different }
  , { walsCode := "ika", iso := "arh", value := .different }
  , { walsCode := "ill", iso := "mia", value := .different }
  , { walsCode := "ilo", iso := "ilo", value := .different }
  , { walsCode := "ind", iso := "ind", value := .different }
  , { walsCode := "iql", iso := "ike", value := .different }
  , { walsCode := "iri", iso := "gle", value := .different }
  , { walsCode := "ita", iso := "ita", value := .different }
  , { walsCode := "itw", iso := "itv", value := .different }
  , { walsCode := "itz", iso := "itz", value := .different }
  , { walsCode := "ixc", iso := "ixc", value := .different }
  , { walsCode := "ixi", iso := "ixl", value := .different }
  , { walsCode := "inu", iso := "esi", value := .identical }
  , { walsCode := "jak", iso := "jac", value := .different }
  , { walsCode := "jpn", iso := "jpn", value := .different }
  , { walsCode := "jeh", iso := "jeh", value := .different }
  , { walsCode := "jiv", iso := "jiv", value := .identical }
  , { walsCode := "jmo", iso := "bex", value := .different }
  , { walsCode := "juh", iso := "ktz", value := .different }
  , { walsCode := "kek", iso := "kek", value := .different }
  , { walsCode := "kdz", iso := "kzj", value := .different }
  , { walsCode := "kng", iso := "kgp", value := .different }
  , { walsCode := "klz", iso := "kck", value := .different }
  , { walsCode := "kls", iso := "fla", value := .identical }
  , { walsCode := "kmk", iso := "xal", value := .different }
  , { walsCode := "kgt", iso := "ikt", value := .different }
  , { walsCode := "kea", iso := "kjb", value := .different }
  , { walsCode := "kwe", iso := "knj", value := .different }
  , { walsCode := "kky", iso := "kne", value := .different }
  , { walsCode := "knd", iso := "kan", value := .different }
  , { walsCode := "knr", iso := "knc", value := .different }
  , { walsCode := "kpn", iso := "kpg", value := .different }
  , { walsCode := "krc", iso := "krc", value := .different }
  , { walsCode := "jva", iso := "kpj", value := .identical }
  , { walsCode := "kkw", iso := "zkk", value := .identical }
  , { walsCode := "kdg", iso := "", value := .different }
  , { walsCode := "krk", iso := "kyh", value := .identical }
  , { walsCode := "kas", iso := "kas", value := .different }
  , { walsCode := "ktu", iso := "", value := .different }
  , { walsCode := "kaq", iso := "zku", value := .identical }
  , { walsCode := "kws", iso := "xaw", value := .different }
  , { walsCode := "kaz", iso := "kaz", value := .different }
  , { walsCode := "ksa", iso := "kee", value := .identical }
  , { walsCode := "kew", iso := "kew", value := .different }
  , { walsCode := "khk", iso := "kjh", value := .different }
  , { walsCode := "khg", iso := "klr", value := .different }
  , { walsCode := "kha", iso := "khk", value := .different }
  , { walsCode := "kmh", iso := "kjl", value := .different }
  , { walsCode := "kic", iso := "kic", value := .different }
  , { walsCode := "klw", iso := "klb", value := .different }
  , { walsCode := "kio", iso := "kio", value := .different }
  , { walsCode := "kgz", iso := "kir", value := .different }
  , { walsCode := "kis", iso := "kss", value := .different }
  , { walsCode := "ktb", iso := "ktu", value := .different }
  , { walsCode := "klm", iso := "kla", value := .different }
  , { walsCode := "koa", iso := "cku", value := .different }
  , { walsCode := "kon", iso := "kng", value := .different }
  , { walsCode := "kor", iso := "kor", value := .different }
  , { walsCode := "kje", iso := "coe", value := .different }
  , { walsCode := "kfe", iso := "kfz", value := .different }
  , { walsCode := "kos", iso := "kos", value := .different }
  , { walsCode := "kyn", iso := "koy", value := .different }
  , { walsCode := "kro", iso := "kgo", value := .different }
  , { walsCode := "knc", iso := "uwa", value := .different }
  , { walsCode := "kul", iso := "dwr", value := .different }
  , { walsCode := "kuq", iso := "kum", value := .different }
  , { walsCode := "kun", iso := "kvn", value := .different }
  , { walsCode := "kth", iso := "gwi", value := .different }
  , { walsCode := "kut", iso := "kut", value := .different }
  , { walsCode := "kwa", iso := "kwd", value := .different }
  , { walsCode := "kxo", iso := "xuu", value := .identical }
  , { walsCode := "kat", iso := "kmg", value := .different }
  , { walsCode := "lao", iso := "lao", value := .different }
  , { walsCode := "lau", iso := "llu", value := .different }
  , { walsCode := "len", iso := "tnl", value := .different }
  , { walsCode := "lez", iso := "lez", value := .different }
  , { walsCode := "lit", iso := "lit", value := .different }
  , { walsCode := "ara", iso := "arw", value := .different }
  , { walsCode := "lnw", iso := "crc", value := .different }
  , { walsCode := "lui", iso := "lui", value := .different }
  , { walsCode := "lus", iso := "lut", value := .different }
  , { walsCode := "mab", iso := "mde", value := .different }
  , { walsCode := "mcg", iso := "mbn", value := .different }
  , { walsCode := "mch", iso := "mcb", value := .different }
  , { walsCode := "mcn", iso := "myy", value := .different }
  , { walsCode := "mhc", iso := "xpq", value := .different }
  , { walsCode := "mne", iso := "nmu", value := .different }
  , { walsCode := "mai", iso := "mai", value := .different }
  , { walsCode := "mal", iso := "plt", value := .different }
  , { walsCode := "mym", iso := "mal", value := .different }
  , { walsCode := "mnc", iso := "mnc", value := .different }
  , { walsCode := "mnd", iso := "cmn", value := .different }
  , { walsCode := "myi", iso := "mpc", value := .different }
  , { walsCode := "mgg", iso := "mjg", value := .different }
  , { walsCode := "mwb", iso := "mbb", value := .different }
  , { walsCode := "mao", iso := "mri", value := .different }
  , { walsCode := "mpy", iso := "mcg", value := .different }
  , { walsCode := "map", iso := "arn", value := .different }
  , { walsCode := "mku", iso := "zmr", value := .identical }
  , { walsCode := "mhi", iso := "mar", value := .different }
  , { walsCode := "msh", iso := "mah", value := .different }
  , { walsCode := "mrt", iso := "vma", value := .different }
  , { walsCode := "mtt", iso := "wam", value := .different }
  , { walsCode := "myr", iso := "mcf", value := .different }
  , { walsCode := "sum", iso := "yan", value := .different }
  , { walsCode := "myo", iso := "mfy", value := .different }
  , { walsCode := "maz", iso := "maz", value := .different }
  , { walsCode := "mzc", iso := "maq", value := .different }
  , { walsCode := "mby", iso := "myb", value := .different }
  , { walsCode := "men", iso := "mez", value := .different }
  , { walsCode := "mer", iso := "ulk", value := .different }
  , { walsCode := "mic", iso := "mic", value := .different }
  , { walsCode := "mid", iso := "mei", value := .different }
  , { walsCode := "mij", iso := "mxj", value := .different }
  , { walsCode := "mis", iso := "miq", value := .different }
  , { walsCode := "mkb", iso := "csi", value := .different }
  , { walsCode := "mcs", iso := "csm", value := .different }
  , { walsCode := "mwl", iso := "lmw", value := .different }
  , { walsCode := "mwn", iso := "nsq", value := .identical }
  , { walsCode := "mwp", iso := "pmw", value := .identical }
  , { walsCode := "mss", iso := "skd", value := .different }
  , { walsCode := "mco", iso := "mco", value := .different }
  , { walsCode := "mtp", iso := "mto", value := .different }
  , { walsCode := "mxu", iso := "mih", value := .different }
  , { walsCode := "mjc", iso := "mjc", value := .different }
  , { walsCode := "mxg", iso := "mig", value := .different }
  , { walsCode := "miz", iso := "lus", value := .different }
  , { walsCode := "moc", iso := "moy", value := .different }
  , { walsCode := "mcv", iso := "moc", value := .different }
  , { walsCode := "mog", iso := "mhj", value := .different }
  , { walsCode := "moh", iso := "moh", value := .identical }
  , { walsCode := "moj", iso := "mov", value := .different }
  , { walsCode := "mok", iso := "mkj", value := .different }
  , { walsCode := "mtg", iso := "moe", value := .different }
  , { walsCode := "mop", iso := "mop", value := .different }
  , { walsCode := "mos", iso := "cas", value := .different }
  , { walsCode := "mov", iso := "mzp", value := .different }
  , { walsCode := "mui", iso := "bmr", value := .different }
  , { walsCode := "mum", iso := "mzm", value := .different }
  , { walsCode := "muu", iso := "myu", value := .identical }
  , { walsCode := "mse", iso := "umu", value := .different }
  , { walsCode := "mup", iso := "sur", value := .different }
  , { walsCode := "mpa", iso := "mwf", value := .identical }
  , { walsCode := "mut", iso := "css", value := .different }
  , { walsCode := "muy", iso := "myw", value := .different }
  , { walsCode := "nhu", iso := "ncj", value := .different }
  , { walsCode := "npa", iso := "nhp", value := .different }
  , { walsCode := "nsz", iso := "azz", value := .different }
  , { walsCode := "nht", iso := "nhg", value := .different }
  , { walsCode := "nhx", iso := "ngu", value := .different }
  , { walsCode := "nnm", iso := "tvl", value := .different }
  , { walsCode := "nas", iso := "nas", value := .different }
  , { walsCode := "nsk", iso := "nsk", value := .different }
  , { walsCode := "nat", iso := "ncz", value := .identical }
  , { walsCode := "nav", iso := "nav", value := .identical }
  , { walsCode := "ndj", iso := "djj", value := .identical }
  , { walsCode := "nne", iso := "nen", value := .different }
  , { walsCode := "nep", iso := "npi", value := .different }
  , { walsCode := "nez", iso := "nez", value := .identical }
  , { walsCode := "ntj", iso := "ntj", value := .different }
  , { walsCode := "ngj", iso := "nju", value := .identical }
  , { walsCode := "ngn", iso := "nid", value := .different }
  , { walsCode := "nlu", iso := "nrl", value := .different }
  , { walsCode := "ngi", iso := "wyb", value := .identical }
  , { walsCode := "ngz", iso := "ngi", value := .identical }
  , { walsCode := "nbr", iso := "gym", value := .different }
  , { walsCode := "nro", iso := "nhr", value := .different }
  , { walsCode := "nsn", iso := "nsz", value := .different }
  , { walsCode := "niu", iso := "niu", value := .different }
  , { walsCode := "chu", iso := "cag", value := .different }
  , { walsCode := "nko", iso := "cgg", value := .different }
  , { walsCode := "nog", iso := "nog", value := .different }
  , { walsCode := "nom", iso := "not", value := .different }
  , { walsCode := "nor", iso := "nor", value := .different }
  , { walsCode := "nbd", iso := "dgl", value := .different }
  , { walsCode := "nuk", iso := "mbr", value := .different }
  , { walsCode := "nkr", iso := "nkr", value := .different }
  , { walsCode := "nun", iso := "nut", value := .different }
  , { walsCode := "nug", iso := "nuy", value := .identical }
  , { walsCode := "nuu", iso := "nuk", value := .different }
  , { walsCode := "nym", iso := "nym", value := .different }
  , { walsCode := "nya", iso := "nyt", value := .different }
  , { walsCode := "nju", iso := "nys", value := .different }
  , { walsCode := "ood", iso := "ood", value := .different }
  , { walsCode := "oca", iso := "oca", value := .different }
  , { walsCode := "oji", iso := "", value := .different }
  , { walsCode := "ojm", iso := "ciw", value := .identical }
  , { walsCode := "oka", iso := "oka", value := .different }
  , { walsCode := "olu", iso := "plo", value := .different }
  , { walsCode := "ond", iso := "one", value := .identical }
  , { walsCode := "onn", iso := "ono", value := .identical }
  , { walsCode := "ore", iso := "ore", value := .different }
  , { walsCode := "oko", iso := "ort", value := .different }
  , { walsCode := "owc", iso := "gaz", value := .different }
  , { walsCode := "osa", iso := "osa", value := .different }
  , { walsCode := "osm", iso := "otq", value := .different }
  , { walsCode := "pkn", iso := "drl", value := .identical }
  , { walsCode := "pac", iso := "pac", value := .identical }
  , { walsCode := "pno", iso := "pao", value := .different }
  , { walsCode := "pal", iso := "pau", value := .different }
  , { walsCode := "pnn", iso := "pag", value := .different }
  , { walsCode := "pan", iso := "pan", value := .different }
  , { walsCode := "psm", iso := "pqm", value := .different }
  , { walsCode := "pem", iso := "aoc", value := .different }
  , { walsCode := "per", iso := "pip", value := .different }
  , { walsCode := "ppc", iso := "pio", value := .different }
  , { walsCode := "pia", iso := "pid", value := .different }
  , { walsCode := "pin", iso := "piu", value := .identical }
  , { walsCode := "pip", iso := "ppl", value := .different }
  , { walsCode := "prt", iso := "pir", value := .different }
  , { walsCode := "pir", iso := "pib", value := .different }
  , { walsCode := "pit", iso := "pjt", value := .identical }
  , { walsCode := "pla", iso := "gob", value := .different }
  , { walsCode := "poh", iso := "pon", value := .different }
  , { walsCode := "pol", iso := "pol", value := .different }
  , { walsCode := "pme", iso := "peb", value := .different }
  , { walsCode := "psj", iso := "poe", value := .different }
  , { walsCode := "psv", iso := "pbf", value := .different }
  , { walsCode := "zqs", iso := "poi", value := .different }
  , { walsCode := "pcm", iso := "poc", value := .different }
  , { walsCode := "por", iso := "por", value := .different }
  , { walsCode := "pow", iso := "pim", value := .different }
  , { walsCode := "pui", iso := "pui", value := .different }
  , { walsCode := "pul", iso := "puw", value := .different }
  , { walsCode := "pur", iso := "tsz", value := .different }
  , { walsCode := "pae", iso := "pbb", value := .different }
  , { walsCode := "qaw", iso := "alc", value := .different }
  , { walsCode := "qan", iso := "qxa", value := .different }
  , { walsCode := "qca", iso := "qvc", value := .different }
  , { walsCode := "qec", iso := "qug", value := .different }
  , { walsCode := "qch", iso := "quc", value := .different }
  , { walsCode := "qui", iso := "qui", value := .identical }
  , { walsCode := "rad", iso := "rad", value := .different }
  , { walsCode := "ram", iso := "rma", value := .different }
  , { walsCode := "rap", iso := "rap", value := .different }
  , { walsCode := "rng", iso := "ren", value := .different }
  , { walsCode := "rnn", iso := "mnv", value := .different }
  , { walsCode := "res", iso := "rgr", value := .different }
  , { walsCode := "ret", iso := "tnc", value := .different }
  , { walsCode := "rgn", iso := "rog", value := .different }
  , { walsCode := "rom", iso := "ron", value := .different }
  , { walsCode := "rus", iso := "rus", value := .different }
  , { walsCode := "sno", iso := "sme", value := .different }
  , { walsCode := "smt", iso := "uma", value := .different }
  , { walsCode := "sal", iso := "sln", value := .different }
  , { walsCode := "sss", iso := "str", value := .different }
  , { walsCode := "sam", iso := "smo", value := .different }
  , { walsCode := "stl", iso := "sat", value := .different }
  , { walsCode := "say", iso := "pos", value := .different }
  , { walsCode := "sec", iso := "sey", value := .different }
  , { walsCode := "sed", iso := "sed", value := .different }
  , { walsCode := "sel", iso := "ona", value := .different }
  , { walsCode := "smj", iso := "sea", value := .different }
  , { walsCode := "snc", iso := "see", value := .identical }
  , { walsCode := "scr", iso := "hbs", value := .different }
  , { walsCode := "ser", iso := "sei", value := .identical }
  , { walsCode := "shs", iso := "sht", value := .identical }
  , { walsCode := "shw", iso := "sjw", value := .different }
  , { walsCode := "shl", iso := "shk", value := .different }
  , { walsCode := "shk", iso := "shp", value := .different }
  , { walsCode := "shn", iso := "sna", value := .different }
  , { walsCode := "sho", iso := "shh", value := .different }
  , { walsCode := "shu", iso := "shs", value := .different }
  , { walsCode := "snh", iso := "sin", value := .different }
  , { walsCode := "sin", iso := "snn", value := .different }
  , { walsCode := "sri", iso := "sri", value := .different }
  , { walsCode := "sla", iso := "den", value := .different }
  , { walsCode := "slv", iso := "xsl", value := .different }
  , { walsCode := "svk", iso := "slk", value := .different }
  , { walsCode := "sol", iso := "evn", value := .different }
  , { walsCode := "son", iso := "sov", value := .different }
  , { walsCode := "sea", iso := "tvk", value := .different }
  , { walsCode := "spa", iso := "spa", value := .different }
  , { walsCode := "spo", iso := "spo", value := .different }
  , { walsCode := "squ", iso := "squ", value := .different }
  , { walsCode := "sus", iso := "sus", value := .different }
  , { walsCode := "sva", iso := "sva", value := .different }
  , { walsCode := "swa", iso := "swh", value := .different }
  , { walsCode := "sba", iso := "slc", value := .different }
  , { walsCode := "tac", iso := "tna", value := .different }
  , { walsCode := "tag", iso := "tgl", value := .different }
  , { walsCode := "tah", iso := "tah", value := .identical }
  , { walsCode := "tml", iso := "tam", value := .different }
  , { walsCode := "tnj", iso := "tfn", value := .different }
  , { walsCode := "tnl", iso := "taa", value := .different }
  , { walsCode := "tga", iso := "hrc", value := .different }
  , { walsCode := "tpt", iso := "tpj", value := .different }
  , { walsCode := "tce", iso := "tar", value := .different }
  , { walsCode := "tar", iso := "tae", value := .different }
  , { walsCode := "toy", iso := "", value := .identical }
  , { walsCode := "tvo", iso := "tat", value := .different }
  , { walsCode := "tty", iso := "tav", value := .different }
  , { walsCode := "tsg", iso := "tsg", value := .different }
  , { walsCode := "teh", iso := "teh", value := .different }
  , { walsCode := "tlf", iso := "tlf", value := .different }
  ]

private def allData_1 : List (Datapoint FingerAndHand) :=
  [ { walsCode := "trb", iso := "tfr", value := .different }
  , { walsCode := "tsj", iso := "tew", value := .different }
  , { walsCode := "tha", iso := "tha", value := .different }
  , { walsCode := "tho", iso := "thp", value := .identical }
  , { walsCode := "tib", iso := "bod", value := .different }
  , { walsCode := "tic", iso := "tca", value := .different }
  , { walsCode := "tbe", iso := "tig", value := .different }
  , { walsCode := "twn", iso := "twf", value := .different }
  , { walsCode := "tlp", iso := "tcf", value := .different }
  , { walsCode := "toa", iso := "tqo", value := .different }
  , { walsCode := "tob", iso := "tob", value := .different }
  , { walsCode := "toj", iso := "toj", value := .different }
  , { walsCode := "tpi", iso := "tpi", value := .different }
  , { walsCode := "tol", iso := "jic", value := .different }
  , { walsCode := "tpa", iso := "top", value := .different }
  , { walsCode := "tos", iso := "tos", value := .different }
  , { walsCode := "txj", iso := "too", value := .different }
  , { walsCode := "trc", iso := "trs", value := .different }
  , { walsCode := "tsf", iso := "cof", value := .different }
  , { walsCode := "tsi", iso := "tsi", value := .different }
  , { walsCode := "tsw", iso := "tsn", value := .different }
  , { walsCode := "tua", iso := "pmt", value := .identical }
  , { walsCode := "tub", iso := "tbu", value := .different }
  , { walsCode := "tuc", iso := "tuo", value := .different }
  , { walsCode := "tnb", iso := "tuf", value := .different }
  , { walsCode := "tun", iso := "tun", value := .identical }
  , { walsCode := "tup", iso := "tpn", value := .different }
  , { walsCode := "tna", iso := "tuv", value := .different }
  , { walsCode := "tur", iso := "tur", value := .different }
  , { walsCode := "tkm", iso := "tuk", value := .different }
  , { walsCode := "tus", iso := "tus", value := .different }
  , { walsCode := "tut", iso := "ttm", value := .different }
  , { walsCode := "tuy", iso := "tue", value := .different }
  , { walsCode := "tze", iso := "tzh", value := .different }
  , { walsCode := "tzt", iso := "tzh", value := .different }
  , { walsCode := "tzo", iso := "tzo", value := .different }
  , { walsCode := "tsh", iso := "par", value := .different }
  , { walsCode := "udh", iso := "ude", value := .different }
  , { walsCode := "ukr", iso := "ukr", value := .different }
  , { walsCode := "uhi", iso := "urf", value := .different }
  , { walsCode := "urk", iso := "urb", value := .identical }
  , { walsCode := "ute", iso := "ute", value := .different }
  , { walsCode := "uzb", iso := "", value := .different }
  , { walsCode := "ved", iso := "ved", value := .different }
  , { walsCode := "bno", iso := "bao", value := .different }
  , { walsCode := "wam", iso := "wmb", value := .identical }
  , { walsCode := "wap", iso := "wao", value := .different }
  , { walsCode := "wra", iso := "wba", value := .different }
  , { walsCode := "wrd", iso := "wrr", value := .different }
  , { walsCode := "wrl", iso := "wbp", value := .identical }
  , { walsCode := "wth", iso := "wth", value := .different }
  , { walsCode := "way", iso := "oym", value := .different }
  , { walsCode := "wel", iso := "cym", value := .different }
  , { walsCode := "wem", iso := "xww", value := .different }
  , { walsCode := "wic", iso := "wic", value := .different }
  , { walsCode := "wch", iso := "mzh", value := .different }
  , { walsCode := "wmu", iso := "wim", value := .different }
  , { walsCode := "wnb", iso := "win", value := .identical }
  , { walsCode := "win", iso := "wnw", value := .identical }
  , { walsCode := "wir", iso := "wgu", value := .different }
  , { walsCode := "wiy", iso := "wiy", value := .different }
  , { walsCode := "wwr", iso := "wyi", value := .different }
  , { walsCode := "wol", iso := "woe", value := .different }
  , { walsCode := "xer", iso := "xer", value := .different }
  , { walsCode := "xok", iso := "xok", value := .identical }
  , { walsCode := "xar", iso := "ane", value := .different }
  , { walsCode := "ygr", iso := "ygr", value := .identical }
  , { walsCode := "yah", iso := "yag", value := .different }
  , { walsCode := "yak", iso := "yaf", value := .different }
  , { walsCode := "yan", iso := "ynn", value := .identical }
  , { walsCode := "yap", iso := "yap", value := .different }
  , { walsCode := "yar", iso := "yrb", value := .different }
  , { walsCode := "yav", iso := "yuf", value := .different }
  , { walsCode := "yir", iso := "yyr", value := .identical }
  , { walsCode := "yyo", iso := "xyy", value := .different }
  , { walsCode := "yct", iso := "yua", value := .different }
  , { walsCode := "ycn", iso := "ycn", value := .different }
  , { walsCode := "yki", iso := "yuk", value := .different }
  , { walsCode := "ykp", iso := "yup", value := .identical }
  , { walsCode := "yuk", iso := "gcd", value := .identical }
  , { walsCode := "ypk", iso := "esu", value := .different }
  , { walsCode := "yus", iso := "ess", value := .different }
  , { walsCode := "yrt", iso := "yui", value := .different }
  , { walsCode := "zai", iso := "zai", value := .different }
  , { walsCode := "zaj", iso := "zaa", value := .different }
  , { walsCode := "zap", iso := "zaw", value := .different }
  , { walsCode := "zam", iso := "zpm", value := .different }
  , { walsCode := "zzo", iso := "zpq", value := .different }
  , { walsCode := "zqc", iso := "zoc", value := .different }
  , { walsCode := "zfl", iso := "zos", value := .different }
  , { walsCode := "zqr", iso := "zor", value := .different }
  , { walsCode := "zul", iso := "zul", value := .different }
  , { walsCode := "zun", iso := "zun", value := .different }
  ]

/-- Complete WALS 130A dataset (593 languages). -/
def allData : List (Datapoint FingerAndHand) := allData_0 ++ allData_1

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F130A
