import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 143G: Minor morphological means of signaling negation
@cite{wals-2013}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 143G`.

Chapter 143, 1325 languages.
-/

namespace Core.WALS.F143G

/-- WALS 143G values. -/
inductive MinorMorphologicalMeansOfSignalingNegation where
  /-- NegTone (7 languages). -/
  | negtone
  /-- NegInfix (2 languages). -/
  | neginfix
  /-- NegStemChange (1 languages). -/
  | negstemchange
  /-- None (1315 languages). -/
  | none
  deriving DecidableEq, BEq, Repr

private def allData_0 : List (Datapoint MinorMorphologicalMeansOfSignalingNegation) :=
  [ { walsCode := "ani", iso := "hnh", value := .none }
  , { walsCode := "xam", iso := "xam", value := .none }
  , { walsCode := "huc", iso := "huc", value := .none }
  , { walsCode := "aar", iso := "aiw", value := .none }
  , { walsCode := "aba", iso := "aau", value := .none }
  , { walsCode := "abi", iso := "axb", value := .none }
  , { walsCode := "abk", iso := "abk", value := .none }
  , { walsCode := "abv", iso := "abz", value := .none }
  , { walsCode := "abu", iso := "kgr", value := .none }
  , { walsCode := "ace", iso := "ace", value := .none }
  , { walsCode := "acg", iso := "aca", value := .none }
  , { walsCode := "acl", iso := "ach", value := .none }
  , { walsCode := "acu", iso := "acu", value := .none }
  , { walsCode := "acm", iso := "acv", value := .none }
  , { walsCode := "aco", iso := "kjq", value := .none }
  , { walsCode := "adg", iso := "adn", value := .none }
  , { walsCode := "adi", iso := "adj", value := .none }
  , { walsCode := "adz", iso := "adz", value := .none }
  , { walsCode := "agh", iso := "agq", value := .none }
  , { walsCode := "agc", iso := "agt", value := .none }
  , { walsCode := "agd", iso := "duo", value := .none }
  , { walsCode := "ain", iso := "ain", value := .none }
  , { walsCode := "aja", iso := "aja", value := .none }
  , { walsCode := "ajg", iso := "ajg", value := .none }
  , { walsCode := "akn", iso := "aka", value := .none }
  , { walsCode := "akh", iso := "ahk", value := .none }
  , { walsCode := "all", iso := "nrz", value := .none }
  , { walsCode := "ala", iso := "amp", value := .none }
  , { walsCode := "alw", iso := "alh", value := .none }
  , { walsCode := "alb", iso := "sqi", value := .none }
  , { walsCode := "als", iso := "aes", value := .none }
  , { walsCode := "aln", iso := "alp", value := .none }
  , { walsCode := "aly", iso := "aly", value := .none }
  , { walsCode := "amc", iso := "amc", value := .none }
  , { walsCode := "amn", iso := "amn", value := .none }
  , { walsCode := "aml", iso := "omb", value := .none }
  , { walsCode := "amq", iso := "amk", value := .none }
  , { walsCode := "amb", iso := "abt", value := .none }
  , { walsCode := "amt", iso := "adx", value := .none }
  , { walsCode := "ame", iso := "aey", value := .none }
  , { walsCode := "amh", iso := "amh", value := .none }
  , { walsCode := "amo", iso := "amo", value := .none }
  , { walsCode := "amx", iso := "imi", value := .none }
  , { walsCode := "anj", iso := "aty", value := .none }
  , { walsCode := "agm", iso := "njm", value := .none }
  , { walsCode := "anc", iso := "anc", value := .none }
  , { walsCode := "ang", iso := "agg", value := .none }
  , { walsCode := "ann", iso := "aoi", value := .none }
  , { walsCode := "anu", iso := "cko", value := .none }
  , { walsCode := "any", iso := "anu", value := .none }
  , { walsCode := "ane", iso := "anz", value := .none }
  , { walsCode := "ao", iso := "njo", value := .none }
  , { walsCode := "apw", iso := "apw", value := .none }
  , { walsCode := "apl", iso := "apy", value := .none }
  , { walsCode := "apt", iso := "apt", value := .none }
  , { walsCode := "apu", iso := "apu", value := .none }
  , { walsCode := "abn", iso := "ard", value := .none }
  , { walsCode := "aeg", iso := "arz", value := .none }
  , { walsCode := "arg", iso := "afb", value := .none }
  , { walsCode := "arq", iso := "acm", value := .none }
  , { walsCode := "arj", iso := "afb", value := .none }
  , { walsCode := "ams", iso := "arb", value := .none }
  , { walsCode := "amr", iso := "ary", value := .none }
  , { walsCode := "asy", iso := "apc", value := .none }
  , { walsCode := "ana", iso := "aro", value := .none }
  , { walsCode := "aab", iso := "aah", value := .none }
  , { walsCode := "arp", iso := "ape", value := .none }
  , { walsCode := "arc", iso := "aqc", value := .none }
  , { walsCode := "arm", iso := "hye", value := .none }
  , { walsCode := "arw", iso := "hyw", value := .none }
  , { walsCode := "alk", iso := "apr", value := .none }
  , { walsCode := "aro", iso := "aia", value := .none }
  , { walsCode := "amp", iso := "aer", value := .none }
  , { walsCode := "awe", iso := "are", value := .none }
  , { walsCode := "asm", iso := "cns", value := .none }
  , { walsCode := "ass", iso := "asm", value := .none }
  , { walsCode := "asu", iso := "asu", value := .none }
  , { walsCode := "ata", iso := "tay", value := .none }
  , { walsCode := "ath", iso := "aph", value := .none }
  , { walsCode := "au", iso := "avt", value := .none }
  , { walsCode := "ava", iso := "ava", value := .none }
  , { walsCode := "awa", iso := "awb", value := .none }
  , { walsCode := "awp", iso := "kwi", value := .none }
  , { walsCode := "awt", iso := "kmn", value := .none }
  , { walsCode := "aym", iso := "ayr", value := .none }
  , { walsCode := "azi", iso := "azb", value := .none }
  , { walsCode := "aze", iso := "", value := .none }
  , { walsCode := "bbl", iso := "bvx", value := .none }
  , { walsCode := "bab", iso := "bav", value := .none }
  , { walsCode := "bac", iso := "wdj", value := .none }
  , { walsCode := "bdm", iso := "bia", value := .none }
  , { walsCode := "baf", iso := "bfd", value := .none }
  , { walsCode := "bag", iso := "bmi", value := .none }
  , { walsCode := "bgr", iso := "fuu", value := .none }
  , { walsCode := "bai", iso := "bca", value := .none }
  , { walsCode := "baj", iso := "bdl", value := .none }
  , { walsCode := "bwc", iso := "bdr", value := .none }
  , { walsCode := "bak", iso := "bkc", value := .none }
  , { walsCode := "bka", iso := "bdh", value := .none }
  , { walsCode := "bku", iso := "bri", value := .none }
  , { walsCode := "blz", iso := "", value := .none }
  , { walsCode := "bvi", iso := "", value := .none }
  , { walsCode := "blt", iso := "bft", value := .none }
  , { walsCode := "bam", iso := "bam", value := .none }
  , { walsCode := "bnn", iso := "bcm", value := .none }
  , { walsCode := "bao", iso := "peh", value := .none }
  , { walsCode := "ble", iso := "bci", value := .negtone }
  , { walsCode := "brl", iso := "loy", value := .none }
  , { walsCode := "baa", iso := "bbb", value := .none }
  , { walsCode := "bbu", iso := "brm", value := .none }
  , { walsCode := "brs", iso := "bsn", value := .none }
  , { walsCode := "mug", iso := "mlp", value := .none }
  , { walsCode := "bar", iso := "bfa", value := .none }
  , { walsCode := "brp", iso := "bpe", value := .none }
  , { walsCode := "bae", iso := "bae", value := .none }
  , { walsCode := "bas", iso := "bas", value := .none }
  , { walsCode := "bsk", iso := "bak", value := .none }
  , { walsCode := "bsq", iso := "eus", value := .none }
  , { walsCode := "bkr", iso := "btx", value := .none }
  , { walsCode := "bto", iso := "bbc", value := .none }
  , { walsCode := "baq", iso := "brg", value := .none }
  , { walsCode := "bzi", iso := "bvz", value := .none }
  , { walsCode := "baw", iso := "bgr", value := .none }
  , { walsCode := "bej", iso := "bej", value := .none }
  , { walsCode := "bel", iso := "byw", value := .none }
  , { walsCode := "bco", iso := "blc", value := .none }
  , { walsCode := "blr", iso := "bel", value := .none }
  , { walsCode := "ben", iso := "ben", value := .none }
  , { walsCode := "bch", iso := "shy", value := .none }
  , { walsCode := "bfg", iso := "grr", value := .none }
  , { walsCode := "bmz", iso := "mzb", value := .none }
  , { walsCode := "brf", iso := "rif", value := .none }
  , { walsCode := "zag", iso := "zag", value := .none }
  , { walsCode := "ber", iso := "wti", value := .none }
  , { walsCode := "bti", iso := "", value := .none }
  , { walsCode := "bho", iso := "bho", value := .none }
  , { walsCode := "bik", iso := "bhw", value := .none }
  , { walsCode := "bid", iso := "bid", value := .none }
  , { walsCode := "bia", iso := "bip", value := .none }
  , { walsCode := "bln", iso := "byn", value := .none }
  , { walsCode := "blx", iso := "bll", value := .none }
  , { walsCode := "bil", iso := "blb", value := .none }
  , { walsCode := "bmb", iso := "bim", value := .none }
  , { walsCode := "big", iso := "yul", value := .none }
  , { walsCode := "bni", iso := "bin", value := .none }
  , { walsCode := "bbw", iso := "gup", value := .none }
  , { walsCode := "bii", iso := "bzr", value := .none }
  , { walsCode := "bir", iso := "bom", value := .none }
  , { walsCode := "biu", iso := "", value := .none }
  , { walsCode := "bla", iso := "bla", value := .none }
  , { walsCode := "boa", iso := "kvg", value := .none }
  , { walsCode := "bob", iso := "bni", value := .none }
  , { walsCode := "bbf", iso := "bbo", value := .none }
  , { walsCode := "bod", iso := "brx", value := .none }
  , { walsCode := "boi", iso := "bzf", value := .none }
  , { walsCode := "bok", iso := "bqc", value := .none }
  , { walsCode := "bol", iso := "bli", value := .none }
  , { walsCode := "bgo", iso := "bot", value := .none }
  , { walsCode := "btk", iso := "lbk", value := .none }
  , { walsCode := "boj", iso := "adi", value := .none }
  , { walsCode := "brr", iso := "bor", value := .none }
  , { walsCode := "brh", iso := "brh", value := .none }
  , { walsCode := "bra", iso := "brb", value := .none }
  , { walsCode := "bre", iso := "bre", value := .none }
  , { walsCode := "bri", iso := "bzd", value := .none }
  , { walsCode := "bud", iso := "bdm", value := .none }
  , { walsCode := "bug", iso := "bug", value := .none }
  , { walsCode := "bgn", iso := "bgg", value := .none }
  , { walsCode := "bun", iso := "buo", value := .none }
  , { walsCode := "bnu", iso := "", value := .none }
  , { walsCode := "bul", iso := "bul", value := .none }
  , { walsCode := "buy", iso := "bwu", value := .none }
  , { walsCode := "buw", iso := "bum", value := .none }
  , { walsCode := "bum", iso := "tkw", value := .none }
  , { walsCode := "ghr", iso := "bfu", value := .none }
  , { walsCode := "pnu", iso := "buh", value := .none }
  , { walsCode := "bua", iso := "bvr", value := .none }
  , { walsCode := "but", iso := "bxm", value := .none }
  , { walsCode := "brm", iso := "mya", value := .none }
  , { walsCode := "brn", iso := "bds", value := .none }
  , { walsCode := "bur", iso := "bsk", value := .none }
  , { walsCode := "bus", iso := "bqp", value := .none }
  , { walsCode := "bsh", iso := "buf", value := .none }
  , { walsCode := "bya", iso := "bee", value := .none }
  , { walsCode := "cah", iso := "chl", value := .none }
  , { walsCode := "cak", iso := "cak", value := .none }
  , { walsCode := "cml", iso := "rab", value := .none }
  , { walsCode := "cax", iso := "", value := .none }
  , { walsCode := "cam", iso := "kbh", value := .none }
  , { walsCode := "cnm", iso := "knm", value := .none }
  , { walsCode := "can", iso := "cbu", value := .none }
  , { walsCode := "cnl", iso := "ram", value := .none }
  , { walsCode := "cnt", iso := "yue", value := .none }
  , { walsCode := "crp", iso := "cbc", value := .none }
  , { walsCode := "car", iso := "car", value := .none }
  , { walsCode := "cde", iso := "mch", value := .none }
  , { walsCode := "cas", iso := "cbr", value := .none }
  , { walsCode := "ctl", iso := "cat", value := .none }
  , { walsCode := "cay", iso := "cbi", value := .none }
  , { walsCode := "cyv", iso := "cyb", value := .none }
  , { walsCode := "cga", iso := "old", value := .none }
  , { walsCode := "chh", iso := "sgw", value := .none }
  , { walsCode := "cai", iso := "suq", value := .none }
  , { walsCode := "chw", iso := "cja", value := .none }
  , { walsCode := "chb", iso := "can", value := .none }
  , { walsCode := "cha", iso := "cha", value := .none }
  , { walsCode := "chg", iso := "nbc", value := .none }
  , { walsCode := "chn", iso := "chx", value := .none }
  , { walsCode := "cso", iso := "ctp", value := .none }
  , { walsCode := "cya", iso := "ctp", value := .none }
  , { walsCode := "chd", iso := "cdn", value := .none }
  , { walsCode := "chc", iso := "che", value := .none }
  , { walsCode := "cmh", iso := "ute", value := .none }
  , { walsCode := "cpn", iso := "cdm", value := .none }
  , { walsCode := "che", iso := "chr", value := .none }
  , { walsCode := "cic", iso := "nya", value := .none }
  , { walsCode := "chi", iso := "cid", value := .none }
  , { walsCode := "cmr", iso := "mrh", value := .none }
  , { walsCode := "chs", iso := "csy", value := .none }
  , { walsCode := "cti", iso := "ctd", value := .none }
  , { walsCode := "ccm", iso := "cco", value := .none }
  , { walsCode := "cle", iso := "cle", value := .none }
  , { walsCode := "cpl", iso := "cpa", value := .none }
  , { walsCode := "chq", iso := "chq", value := .none }
  , { walsCode := "ckl", iso := "chh", value := .none }
  , { walsCode := "cpy", iso := "cap", value := .none }
  , { walsCode := "chp", iso := "chp", value := .none }
  , { walsCode := "cqt", iso := "cax", value := .none }
  , { walsCode := "ctm", iso := "ctm", value := .none }
  , { walsCode := "cct", iso := "cho", value := .none }
  , { walsCode := "cln", iso := "cht", value := .none }
  , { walsCode := "chx", iso := "clo", value := .none }
  , { walsCode := "cmy", iso := "chf", value := .none }
  , { walsCode := "crt", iso := "", value := .none }
  , { walsCode := "chr", iso := "crw", value := .none }
  , { walsCode := "chj", iso := "cac", value := .none }
  , { walsCode := "chk", iso := "ckt", value := .none }
  , { walsCode := "cba", iso := "boi", value := .none }
  , { walsCode := "chv", iso := "chv", value := .none }
  , { walsCode := "cbo", iso := "cao", value := .none }
  , { walsCode := "coa", iso := "xcw", value := .none }
  , { walsCode := "coc", iso := "cod", value := .none }
  , { walsCode := "cmn", iso := "com", value := .none }
  , { walsCode := "coo", iso := "csz", value := .none }
  , { walsCode := "cop", iso := "cop", value := .none }
  , { walsCode := "crn", iso := "cor", value := .none }
  , { walsCode := "cre", iso := "crk", value := .none }
  , { walsCode := "cea", iso := "csw", value := .none }
  , { walsCode := "cub", iso := "cub", value := .none }
  , { walsCode := "cui", iso := "cui", value := .none }
  , { walsCode := "cup", iso := "cup", value := .none }
  , { walsCode := "cze", iso := "ces", value := .none }
  , { walsCode := "cem", iso := "cam", value := .none }
  , { walsCode := "dag", iso := "dgz", value := .none }
  , { walsCode := "dga", iso := "dga", value := .none }
  , { walsCode := "dgb", iso := "dag", value := .none }
  , { walsCode := "dgr", iso := "dta", value := .none }
  , { walsCode := "dan", iso := "dnj", value := .none }
  , { walsCode := "dni", iso := "dni", value := .none }
  , { walsCode := "dsh", iso := "dan", value := .none }
  , { walsCode := "drm", iso := "drd", value := .none }
  , { walsCode := "deg", iso := "deg", value := .negtone }
  , { walsCode := "des", iso := "des", value := .none }
  , { walsCode := "deu", iso := "der", value := .none }
  , { walsCode := "dha", iso := "dsh", value := .none }
  , { walsCode := "dhw", iso := "tbh", value := .none }
  , { walsCode := "dhm", iso := "dhi", value := .none }
  , { walsCode := "dhi", iso := "div", value := .none }
  , { walsCode := "did", iso := "did", value := .none }
  , { walsCode := "die", iso := "dih", value := .none }
  , { walsCode := "dig", iso := "mhu", value := .none }
  , { walsCode := "dms", iso := "dis", value := .none }
  , { walsCode := "dim", iso := "dim", value := .none }
  , { walsCode := "din", iso := "din", value := .none }
  , { walsCode := "dio", iso := "dyo", value := .none }
  , { walsCode := "diy", iso := "dif", value := .none }
  , { walsCode := "dja", iso := "dyy", value := .none }
  , { walsCode := "djm", iso := "djr", value := .none }
  , { walsCode := "djp", iso := "dwu", value := .none }
  , { walsCode := "djn", iso := "dji", value := .none }
  , { walsCode := "dji", iso := "jig", value := .none }
  , { walsCode := "dmk", iso := "dmk", value := .none }
  , { walsCode := "dom", iso := "rmt", value := .none }
  , { walsCode := "dgo", iso := "doo", value := .none }
  , { walsCode := "dds", iso := "dds", value := .none }
  , { walsCode := "doy", iso := "dow", value := .negtone }
  , { walsCode := "dre", iso := "dhv", value := .none }
  , { walsCode := "dua", iso := "dua", value := .none }
  , { walsCode := "duk", iso := "dud", value := .none }
  , { walsCode := "dul", iso := "duu", value := .none }
  , { walsCode := "dma", iso := "dma", value := .none }
  , { walsCode := "dmi", iso := "dus", value := .none }
  , { walsCode := "dum", iso := "vam", value := .none }
  , { walsCode := "dun", iso := "duc", value := .none }
  , { walsCode := "dut", iso := "nld", value := .none }
  , { walsCode := "dyi", iso := "dbl", value := .none }
  , { walsCode := "ebi", iso := "igb", value := .none }
  , { walsCode := "erk", iso := "erk", value := .none }
  , { walsCode := "efi", iso := "efi", value := .none }
  , { walsCode := "ega", iso := "ega", value := .none }
  , { walsCode := "eip", iso := "eip", value := .none }
  , { walsCode := "eka", iso := "ekg", value := .none }
  , { walsCode := "eko", iso := "eko", value := .none }
  , { walsCode := "emb", iso := "emp", value := .none }
  , { walsCode := "ene", iso := "", value := .none }
  , { walsCode := "egn", iso := "enn", value := .negtone }
  , { walsCode := "eno", iso := "eno", value := .none }
  , { walsCode := "eng", iso := "eng", value := .none }
  , { walsCode := "eny", iso := "gey", value := .none }
  , { walsCode := "epe", iso := "sja", value := .none }
  , { walsCode := "err", iso := "erg", value := .none }
  , { walsCode := "ese", iso := "ese", value := .none }
  , { walsCode := "est", iso := "ekk", value := .none }
  , { walsCode := "eud", iso := "", value := .none }
  , { walsCode := "evn", iso := "eve", value := .none }
  , { walsCode := "eve", iso := "evn", value := .none }
  , { walsCode := "ewe", iso := "ewe", value := .none }
  , { walsCode := "ewo", iso := "ewo", value := .negtone }
  , { walsCode := "fij", iso := "fij", value := .none }
  , { walsCode := "fin", iso := "fin", value := .none }
  , { walsCode := "fon", iso := "fon", value := .none }
  , { walsCode := "fre", iso := "fra", value := .none }
  , { walsCode := "fua", iso := "fub", value := .none }
  , { walsCode := "ful", iso := "fun", value := .none }
  , { walsCode := "fur", iso := "fvr", value := .none }
  , { walsCode := "fut", iso := "fut", value := .none }
  , { walsCode := "fye", iso := "pym", value := .none }
  , { walsCode := "gaa", iso := "gbu", value := .none }
  , { walsCode := "gds", iso := "gaj", value := .none }
  , { walsCode := "gae", iso := "gla", value := .none }
  , { walsCode := "gah", iso := "gah", value := .none }
  , { walsCode := "gal", iso := "adl", value := .none }
  , { walsCode := "gap", iso := "pwg", value := .none }
  , { walsCode := "gar", iso := "grt", value := .none }
  , { walsCode := "grr", iso := "wrk", value := .none }
  , { walsCode := "grs", iso := "gyb", value := .none }
  , { walsCode := "grf", iso := "cab", value := .none }
  , { walsCode := "gav", iso := "gvo", value := .none }
  , { walsCode := "gbs", iso := "gso", value := .none }
  , { walsCode := "gbb", iso := "gbp", value := .none }
  , { walsCode := "gel", iso := "nlg", value := .none }
  , { walsCode := "gla", iso := "gqu", value := .none }
  , { walsCode := "geo", iso := "kat", value := .none }
  , { walsCode := "ger", iso := "deu", value := .none }
  , { walsCode := "gim", iso := "bcq", value := .none }
  , { walsCode := "giz", iso := "gis", value := .none }
  , { walsCode := "goa", iso := "guc", value := .none }
  , { walsCode := "god", iso := "gdo", value := .none }
  , { walsCode := "goe", iso := "ank", value := .none }
  , { walsCode := "gok", iso := "gkn", value := .none }
  , { walsCode := "gln", iso := "gvf", value := .none }
  , { walsCode := "gon", iso := "gno", value := .none }
  , { walsCode := "goo", iso := "gni", value := .none }
  , { walsCode := "grb", iso := "grj", value := .none }
  , { walsCode := "grk", iso := "ell", value := .none }
  , { walsCode := "grw", iso := "kal", value := .none }
  , { walsCode := "gjj", iso := "gub", value := .none }
  , { walsCode := "gua", iso := "gug", value := .none }
  , { walsCode := "grj", iso := "var", value := .none }
  , { walsCode := "gud", iso := "gde", value := .none }
  , { walsCode := "gug", iso := "ktd", value := .none }
  , { walsCode := "guh", iso := "ghs", value := .none }
  , { walsCode := "guj", iso := "guj", value := .none }
  , { walsCode := "gul", iso := "kcm", value := .none }
  , { walsCode := "gir", iso := "glj", value := .none }
  , { walsCode := "gmw", iso := "gvs", value := .none }
  , { walsCode := "gmz", iso := "guk", value := .none }
  , { walsCode := "gnb", iso := "wlg", value := .none }
  , { walsCode := "ggu", iso := "gnr", value := .none }
  , { walsCode := "gur", iso := "", value := .none }
  , { walsCode := "guu", iso := "kky", value := .none }
  , { walsCode := "gwa", iso := "gbr", value := .none }
  , { walsCode := "gwo", iso := "kcg", value := .none }
  , { walsCode := "gyc", iso := "jya", value := .none }
  , { walsCode := "ga", iso := "gaa", value := .none }
  , { walsCode := "gku", iso := "pue", value := .none }
  , { walsCode := "hai", iso := "hai", value := .none }
  , { walsCode := "hak", iso := "hak", value := .none }
  , { walsCode := "hal", iso := "hla", value := .none }
  , { walsCode := "hlu", iso := "hur", value := .none }
  , { walsCode := "ham", iso := "hmt", value := .none }
  , { walsCode := "han", iso := "hni", value := .none }
  , { walsCode := "har", iso := "tmd", value := .none }
  , { walsCode := "hat", iso := "had", value := .none }
  , { walsCode := "hau", iso := "hau", value := .none }
  , { walsCode := "haw", iso := "haw", value := .none }
  , { walsCode := "hya", iso := "hay", value := .none }
  , { walsCode := "hay", iso := "vay", value := .none }
  , { walsCode := "hdi", iso := "xed", value := .none }
  , { walsCode := "heb", iso := "heb", value := .none }
  , { walsCode := "heh", iso := "heh", value := .none }
  , { walsCode := "hei", iso := "hei", value := .none }
  , { walsCode := "hid", iso := "hid", value := .none }
  , { walsCode := "hil", iso := "hil", value := .none }
  , { walsCode := "hin", iso := "hin", value := .none }
  , { walsCode := "hix", iso := "hix", value := .none }
  , { walsCode := "lic", iso := "lic", value := .none }
  , { walsCode := "hma", iso := "hmr", value := .none }
  , { walsCode := "hmo", iso := "hnj", value := .none }
  , { walsCode := "hoa", iso := "hoa", value := .none }
  , { walsCode := "hol", iso := "hoo", value := .none }
  , { walsCode := "hop", iso := "hop", value := .none }
  , { walsCode := "hua", iso := "ygr", value := .none }
  , { walsCode := "hlp", iso := "yuf", value := .none }
  , { walsCode := "htc", iso := "hus", value := .none }
  , { walsCode := "hve", iso := "huv", value := .none }
  , { walsCode := "hui", iso := "hch", value := .none }
  , { walsCode := "hmi", iso := "hto", value := .none }
  , { walsCode := "hum", iso := "huu", value := .none }
  , { walsCode := "hnd", iso := "hke", value := .none }
  , { walsCode := "hun", iso := "hun", value := .none }
  , { walsCode := "hzb", iso := "huz", value := .none }
  , { walsCode := "hpd", iso := "jup", value := .none }
  , { walsCode := "hup", iso := "hup", value := .none }
  , { walsCode := "isa", iso := "ksi", value := .none }
  , { walsCode := "iaa", iso := "iai", value := .none }
  , { walsCode := "iau", iso := "tmu", value := .none }
  , { walsCode := "iba", iso := "iba", value := .none }
  , { walsCode := "ice", iso := "isl", value := .none }
  , { walsCode := "ido", iso := "idu", value := .none }
  , { walsCode := "idu", iso := "clk", value := .none }
  , { walsCode := "idn", iso := "viv", value := .none }
  , { walsCode := "mxe", iso := "mxe", value := .none }
  , { walsCode := "ifu", iso := "ifb", value := .none }
  , { walsCode := "ifm", iso := "ifm", value := .none }
  , { walsCode := "ige", iso := "ige", value := .none }
  , { walsCode := "ign", iso := "ign", value := .none }
  , { walsCode := "ijo", iso := "ijc", value := .none }
  , { walsCode := "ik", iso := "ikx", value := .none }
  , { walsCode := "ika", iso := "arh", value := .none }
  , { walsCode := "ila", iso := "ilb", value := .none }
  , { walsCode := "imo", iso := "imn", value := .none }
  , { walsCode := "ina", iso := "szp", value := .none }
  , { walsCode := "ind", iso := "ind", value := .none }
  , { walsCode := "igs", iso := "tbi", value := .none }
  , { walsCode := "ing", iso := "inh", value := .none }
  , { walsCode := "inn", iso := "ynd", value := .none }
  , { walsCode := "iqu", iso := "iqu", value := .none }
  , { walsCode := "irx", iso := "irn", value := .none }
  , { walsCode := "irq", iso := "irk", value := .none }
  , { walsCode := "irr", iso := "irh", value := .none }
  , { walsCode := "iri", iso := "gle", value := .none }
  , { walsCode := "ita", iso := "ita", value := .none }
  , { walsCode := "ite", iso := "itl", value := .none }
  , { walsCode := "iwm", iso := "iwm", value := .none }
  , { walsCode := "kwy", iso := "yom", value := .none }
  , { walsCode := "jar", iso := "izr", value := .none }
  , { walsCode := "izi", iso := "izz", value := .none }
  , { walsCode := "jab", iso := "jae", value := .none }
  , { walsCode := "jak", iso := "jac", value := .none }
  , { walsCode := "jms", iso := "djm", value := .none }
  , { walsCode := "jpn", iso := "jpn", value := .none }
  , { walsCode := "jaq", iso := "jqr", value := .none }
  , { walsCode := "jeb", iso := "jeb", value := .none }
  , { walsCode := "jng", iso := "kac", value := .none }
  , { walsCode := "jiv", iso := "jiv", value := .none }
  , { walsCode := "joh", iso := "rgk", value := .none }
  , { walsCode := "juk", iso := "jbu", value := .none }
  , { walsCode := "jmo", iso := "bex", value := .none }
  , { walsCode := "juh", iso := "ktz", value := .none }
  , { walsCode := "kab", iso := "kbd", value := .none }
  , { walsCode := "kby", iso := "kbp", value := .none }
  , { walsCode := "kbl", iso := "kab", value := .none }
  , { walsCode := "kac", iso := "xac", value := .none }
  , { walsCode := "kdz", iso := "kzj", value := .none }
  , { walsCode := "kdw", iso := "kbc", value := .none }
  , { walsCode := "kad", iso := "xtc", value := .none }
  , { walsCode := "kgr", iso := "kki", value := .none }
  , { walsCode := "kng", iso := "kgp", value := .none }
  , { walsCode := "krr", iso := "kxa", value := .none }
  , { walsCode := "kae", iso := "tbd", value := .none }
  , { walsCode := "kls", iso := "fla", value := .none }
  , { walsCode := "kmk", iso := "xal", value := .none }
  , { walsCode := "kll", iso := "bco", value := .none }
  , { walsCode := "kma", iso := "kay", value := .none }
  , { walsCode := "kmz", iso := "kms", value := .none }
  , { walsCode := "kms", iso := "xas", value := .none }
  , { walsCode := "kba", iso := "kam", value := .none }
  , { walsCode := "kbo", iso := "kbx", value := .none }
  , { walsCode := "kmi", iso := "kcu", value := .none }
  , { walsCode := "kmr", iso := "kgq", value := .none }
  , { walsCode := "kmw", iso := "xmu", value := .none }
  , { walsCode := "kan", iso := "ogo", value := .none }
  , { walsCode := "knk", iso := "kna", value := .none }
  , { walsCode := "xns", iso := "xns", value := .none }
  , { walsCode := "knd", iso := "kan", value := .none }
  , { walsCode := "knb", iso := "khd", value := .none }
  , { walsCode := "knr", iso := "knc", value := .none }
  , { walsCode := "kar", iso := "kah", value := .none }
  , { walsCode := "krc", iso := "krc", value := .none }
  , { walsCode := "krj", iso := "gbd", value := .none }
  , { walsCode := "kkp", iso := "kaa", value := .none }
  , { walsCode := "kbw", iso := "bwe", value := .none }
  , { walsCode := "kpw", iso := "kjp", value := .none }
  , { walsCode := "ksg", iso := "ksw", value := .none }
  , { walsCode := "kmj", iso := "kdj", value := .none }
  , { walsCode := "kyr", iso := "yuj", value := .none }
  , { walsCode := "krk", iso := "kyh", value := .none }
  , { walsCode := "kaa", iso := "arr", value := .none }
  , { walsCode := "kas", iso := "kas", value := .none }
  ]

private def allData_1 : List (Datapoint MinorMorphologicalMeansOfSignalingNegation) :=
  [ { walsCode := "ksn", iso := "cog", value := .none }
  , { walsCode := "ktc", iso := "xtc", value := .none }
  , { walsCode := "kti", iso := "kts", value := .none }
  , { walsCode := "ktl", iso := "kcr", value := .none }
  , { walsCode := "kau", iso := "pss", value := .none }
  , { walsCode := "kws", iso := "xaw", value := .none }
  , { walsCode := "kyz", iso := "kyz", value := .none }
  , { walsCode := "kyl", iso := "eky", value := .none }
  , { walsCode := "kyp", iso := "txu", value := .none }
  , { walsCode := "kay", iso := "gyd", value := .none }
  , { walsCode := "kel", iso := "sbc", value := .none }
  , { walsCode := "kem", iso := "ahg", value := .none }
  , { walsCode := "ken", iso := "kyq", value := .none }
  , { walsCode := "ker", iso := "ker", value := .none }
  , { walsCode := "ksa", iso := "kee", value := .none }
  , { walsCode := "ket", iso := "ket", value := .none }
  , { walsCode := "kew", iso := "kew", value := .none }
  , { walsCode := "khl", iso := "klj", value := .none }
  , { walsCode := "khg", iso := "klr", value := .none }
  , { walsCode := "kha", iso := "khk", value := .none }
  , { walsCode := "kmh", iso := "kjl", value := .none }
  , { walsCode := "khd", iso := "khg", value := .none }
  , { walsCode := "knz", iso := "khg", value := .none }
  , { walsCode := "kty", iso := "kca", value := .none }
  , { walsCode := "khr", iso := "khr", value := .none }
  , { walsCode := "khs", iso := "kha", value := .none }
  , { walsCode := "khm", iso := "khm", value := .none }
  , { walsCode := "kmu", iso := "kjg", value := .none }
  , { walsCode := "khn", iso := "kkh", value := .none }
  , { walsCode := "kik", iso := "kik", value := .none }
  , { walsCode := "klv", iso := "kij", value := .none }
  , { walsCode := "klw", iso := "klb", value := .none }
  , { walsCode := "kil", iso := "lub", value := .none }
  , { walsCode := "kim", iso := "kig", value := .none }
  , { walsCode := "kga", iso := "zga", value := .none }
  , { walsCode := "knn", iso := "kfk", value := .none }
  , { walsCode := "kin", iso := "kin", value := .none }
  , { walsCode := "kio", iso := "kio", value := .none }
  , { walsCode := "kri", iso := "kzw", value := .none }
  , { walsCode := "kie", iso := "geb", value := .none }
  , { walsCode := "krb", iso := "gil", value := .none }
  , { walsCode := "kir", iso := "cme", value := .none }
  , { walsCode := "kis", iso := "kss", value := .negtone }
  , { walsCode := "kiw", iso := "kjd", value := .none }
  , { walsCode := "klm", iso := "kla", value := .none }
  , { walsCode := "kla", iso := "klu", value := .none }
  , { walsCode := "shp", iso := "yak", value := .none }
  , { walsCode := "koa", iso := "cku", value := .none }
  , { walsCode := "kob", iso := "kpw", value := .none }
  , { walsCode := "koe", iso := "xwg", value := .none }
  , { walsCode := "kmo", iso := "kpx", value := .none }
  , { walsCode := "koi", iso := "kbk", value := .none }
  , { walsCode := "kta", iso := "kqi", value := .none }
  , { walsCode := "kok", iso := "trp", value := .none }
  , { walsCode := "kkt", iso := "kkk", value := .none }
  , { walsCode := "kol", iso := "kfb", value := .none }
  , { walsCode := "kmb", iso := "", value := .none }
  , { walsCode := "xbi", iso := "xbi", value := .none }
  , { walsCode := "kop", iso := "koi", value := .none }
  , { walsCode := "kzy", iso := "kpv", value := .none }
  , { walsCode := "kom", iso := "xom", value := .none }
  , { walsCode := "kon", iso := "kng", value := .none }
  , { walsCode := "knw", iso := "mjd", value := .none }
  , { walsCode := "kni", iso := "kma", value := .none }
  , { walsCode := "krn", iso := "kqz", value := .none }
  , { walsCode := "kor", iso := "kor", value := .none }
  , { walsCode := "kfe", iso := "kfz", value := .none }
  , { walsCode := "krw", iso := "khe", value := .none }
  , { walsCode := "kry", iso := "kpy", value := .none }
  , { walsCode := "kos", iso := "kos", value := .none }
  , { walsCode := "koy", iso := "kff", value := .none }
  , { walsCode := "kch", iso := "khq", value := .none }
  , { walsCode := "kse", iso := "ses", value := .none }
  , { walsCode := "krh", iso := "xra", value := .none }
  , { walsCode := "kre", iso := "krs", value := .none }
  , { walsCode := "kro", iso := "kgo", value := .none }
  , { walsCode := "knc", iso := "uwa", value := .none }
  , { walsCode := "kya", iso := "gvn", value := .none }
  , { walsCode := "klg", iso := "kle", value := .none }
  , { walsCode := "kmn", iso := "kue", value := .none }
  , { walsCode := "kum", iso := "kfy", value := .none }
  , { walsCode := "kun", iso := "kvn", value := .none }
  , { walsCode := "knm", iso := "kun", value := .none }
  , { walsCode := "kmp", iso := "kup", value := .none }
  , { walsCode := "kuo", iso := "kto", value := .none }
  , { walsCode := "krd", iso := "ckb", value := .none }
  , { walsCode := "kus", iso := "kgg", value := .none }
  , { walsCode := "kut", iso := "kut", value := .none }
  , { walsCode := "thy", iso := "thd", value := .none }
  , { walsCode := "kuv", iso := "kxv", value := .none }
  , { walsCode := "kwa", iso := "kwd", value := .none }
  , { walsCode := "kwn", iso := "kwn", value := .none }
  , { walsCode := "kwz", iso := "xwa", value := .none }
  , { walsCode := "kwb", iso := "kwe", value := .none }
  , { walsCode := "kwo", iso := "kmo", value := .none }
  , { walsCode := "kwt", iso := "kwo", value := .none }
  , { walsCode := "kxo", iso := "xuu", value := .none }
  , { walsCode := "kgy", iso := "kgy", value := .none }
  , { walsCode := "kyq", iso := "nuk", value := .none }
  , { walsCode := "laa", iso := "gdm", value := .none }
  , { walsCode := "lab", iso := "lbu", value := .none }
  , { walsCode := "lac", iso := "lac", value := .none }
  , { walsCode := "lad", iso := "lbj", value := .none }
  , { walsCode := "lag", iso := "kot", value := .none }
  , { walsCode := "lah", iso := "lhu", value := .none }
  , { walsCode := "lai", iso := "cnh", value := .none }
  , { walsCode := "lkt", iso := "lkt", value := .none }
  , { walsCode := "lal", iso := "ywt", value := .none }
  , { walsCode := "lmh", iso := "slp", value := .none }
  , { walsCode := "lmg", iso := "hia", value := .none }
  , { walsCode := "lmn", iso := "lmn", value := .none }
  , { walsCode := "lmu", iso := "lmu", value := .none }
  , { walsCode := "lmp", iso := "ljp", value := .none }
  , { walsCode := "lgi", iso := "lag", value := .none }
  , { walsCode := "lan", iso := "laj", value := .none }
  , { walsCode := "lao", iso := "lao", value := .none }
  , { walsCode := "lar", iso := "lrg", value := .none }
  , { walsCode := "lat", iso := "lav", value := .none }
  , { walsCode := "lav", iso := "lvk", value := .none }
  , { walsCode := "leb", iso := "agh", value := .none }
  , { walsCode := "leg", iso := "lea", value := .none }
  , { walsCode := "agb", iso := "agb", value := .none }
  , { walsCode := "lec", iso := "lec", value := .none }
  , { walsCode := "lel", iso := "lln", value := .none }
  , { walsCode := "llm", iso := "lef", value := .none }
  , { walsCode := "len", iso := "tnl", value := .none }
  , { walsCode := "ldu", iso := "led", value := .none }
  , { walsCode := "lng", iso := "enx", value := .none }
  , { walsCode := "lep", iso := "lep", value := .none }
  , { walsCode := "les", iso := "les", value := .none }
  , { walsCode := "let", iso := "lti", value := .none }
  , { walsCode := "lew", iso := "lww", value := .none }
  , { walsCode := "lez", iso := "lez", value := .none }
  , { walsCode := "lho", iso := "lhm", value := .none }
  , { walsCode := "lim", iso := "lif", value := .none }
  , { walsCode := "lnd", iso := "liy", value := .none }
  , { walsCode := "lin", iso := "lin", value := .none }
  , { walsCode := "lis", iso := "lis", value := .none }
  , { walsCode := "lit", iso := "lit", value := .none }
  , { walsCode := "lgt", iso := "log", value := .none }
  , { walsCode := "ara", iso := "arw", value := .none }
  , { walsCode := "ldo", iso := "bdu", value := .none }
  , { walsCode := "lgu", iso := "lgu", value := .none }
  , { walsCode := "lon", iso := "los", value := .none }
  , { walsCode := "lot", iso := "njh", value := .none }
  , { walsCode := "lou", iso := "loj", value := .none }
  , { walsCode := "luc", iso := "lch", value := .none }
  , { walsCode := "lda", iso := "lug", value := .none }
  , { walsCode := "lug", iso := "lgg", value := .none }
  , { walsCode := "lui", iso := "lui", value := .none }
  , { walsCode := "lbu", iso := "lun", value := .none }
  , { walsCode := "luo", iso := "luo", value := .none }
  , { walsCode := "kkv", iso := "khl", value := .none }
  , { walsCode := "luv", iso := "lue", value := .none }
  , { walsCode := "jlu", iso := "lwo", value := .none }
  , { walsCode := "ma", iso := "msj", value := .none }
  , { walsCode := "mad", iso := "mhi", value := .none }
  , { walsCode := "maa", iso := "mas", value := .none }
  , { walsCode := "mab", iso := "mde", value := .none }
  , { walsCode := "mcd", iso := "mkd", value := .none }
  , { walsCode := "mch", iso := "mcb", value := .none }
  , { walsCode := "mac", iso := "mbc", value := .none }
  , { walsCode := "mda", iso := "mxu", value := .none }
  , { walsCode := "mdm", iso := "dmd", value := .none }
  , { walsCode := "mae", iso := "mmw", value := .none }
  , { walsCode := "mag", iso := "mgp", value := .none }
  , { walsCode := "mgi", iso := "mgu", value := .none }
  , { walsCode := "mne", iso := "nmu", value := .none }
  , { walsCode := "mrs", iso := "zrs", value := .none }
  , { walsCode := "msn", iso := "mbq", value := .none }
  , { walsCode := "mai", iso := "mai", value := .none }
  , { walsCode := "maj", iso := "mpe", value := .none }
  , { walsCode := "mkz", iso := "mcp", value := .none }
  , { walsCode := "mak", iso := "myh", value := .none }
  , { walsCode := "mkj", iso := "mkz", value := .none }
  , { walsCode := "mkl", iso := "mgf", value := .none }
  , { walsCode := "mkd", iso := "kde", value := .none }
  , { walsCode := "mua", iso := "mgh", value := .none }
  , { walsCode := "mal", iso := "plt", value := .none }
  , { walsCode := "mlk", iso := "mpb", value := .none }
  , { walsCode := "mym", iso := "mal", value := .none }
  , { walsCode := "mlu", iso := "mgl", value := .none }
  , { walsCode := "mlg", iso := "", value := .none }
  , { walsCode := "mam", iso := "mam", value := .none }
  , { walsCode := "mmn", iso := "mmn", value := .none }
  , { walsCode := "mmw", iso := "mgr", value := .none }
  , { walsCode := "mmv", iso := "mdi", value := .none }
  , { walsCode := "mnm", iso := "mva", value := .none }
  , { walsCode := "nmm", iso := "nmm", value := .none }
  , { walsCode := "mnc", iso := "mnc", value := .none }
  , { walsCode := "mdn", iso := "mhq", value := .none }
  , { walsCode := "mnd", iso := "cmn", value := .none }
  , { walsCode := "mkg", iso := "mnk", value := .none }
  , { walsCode := "mmb", iso := "mna", value := .none }
  , { walsCode := "myi", iso := "mpc", value := .none }
  , { walsCode := "mbt", iso := "mdj", value := .none }
  , { walsCode := "mgg", iso := "mjg", value := .none }
  , { walsCode := "maw", iso := "mlq", value := .none }
  , { walsCode := "man", iso := "mev", value := .none }
  , { walsCode := "mwb", iso := "mbb", value := .none }
  , { walsCode := "mns", iso := "mns", value := .none }
  , { walsCode := "mao", iso := "mri", value := .none }
  , { walsCode := "map", iso := "arn", value := .none }
  , { walsCode := "mra", iso := "mec", value := .none }
  , { walsCode := "mku", iso := "zmr", value := .none }
  , { walsCode := "mhi", iso := "mar", value := .none }
  , { walsCode := "mny", iso := "zmc", value := .none }
  , { walsCode := "mrg", iso := "mrt", value := .none }
  , { walsCode := "mme", iso := "mhr", value := .none }
  , { walsCode := "mar", iso := "mrc", value := .none }
  , { walsCode := "mrd", iso := "mrz", value := .none }
  , { walsCode := "mrr", iso := "zmt", value := .none }
  , { walsCode := "mrq", iso := "", value := .none }
  , { walsCode := "mrh", iso := "mfr", value := .none }
  , { walsCode := "mrt", iso := "vma", value := .none }
  , { walsCode := "mru", iso := "mhx", value := .none }
  , { walsCode := "mas", iso := "mcn", value := .none }
  , { walsCode := "msk", iso := "jle", value := .none }
  , { walsCode := "msl", iso := "mls", value := .none }
  , { walsCode := "mts", iso := "mpq", value := .none }
  , { walsCode := "mdl", iso := "zml", value := .none }
  , { walsCode := "mtb", iso := "mgw", value := .none }
  , { walsCode := "mka", iso := "mxx", value := .none }
  , { walsCode := "mau", iso := "mph", value := .none }
  , { walsCode := "may", iso := "ayz", value := .none }
  , { walsCode := "myg", iso := "mdm", value := .none }
  , { walsCode := "mzc", iso := "maq", value := .none }
  , { walsCode := "mba", iso := "mfc", value := .none }
  , { walsCode := "mhu", iso := "lnb", value := .none }
  , { walsCode := "mbr", iso := "mpk", value := .none }
  , { walsCode := "mby", iso := "myb", value := .none }
  , { walsCode := "mbe", iso := "mdt", value := .none }
  , { walsCode := "mbi", iso := "baw", value := .none }
  , { walsCode := "mdo", iso := "gmm", value := .none }
  , { walsCode := "mbl", iso := "mdq", value := .none }
  , { walsCode := "mdw", iso := "mdw", value := .none }
  , { walsCode := "mbm", iso := "mdd", value := .none }
  , { walsCode := "mee", iso := "mym", value := .none }
  , { walsCode := "meh", iso := "gdq", value := .none }
  , { walsCode := "mei", iso := "mni", value := .none }
  , { walsCode := "mek", iso := "skf", value := .none }
  , { walsCode := "mke", iso := "mek", value := .none }
  , { walsCode := "mde", iso := "men", value := .none }
  , { walsCode := "men", iso := "mez", value := .none }
  , { walsCode := "mnt", iso := "mwv", value := .none }
  , { walsCode := "mer", iso := "ulk", value := .none }
  , { walsCode := "mea", iso := "mej", value := .none }
  , { walsCode := "mpt", iso := "mpt", value := .none }
  , { walsCode := "mie", iso := "ium", value := .none }
  , { walsCode := "mig", iso := "mmy", value := .none }
  , { walsCode := "mii", iso := "", value := .none }
  , { walsCode := "mki", iso := "mik", value := .none }
  , { walsCode := "mik", iso := "mjw", value := .none }
  , { walsCode := "hna", iso := "hna", value := .none }
  , { walsCode := "min", iso := "min", value := .none }
  , { walsCode := "mhl", iso := "mrg", value := .none }
  , { walsCode := "mir", iso := "mep", value := .none }
  , { walsCode := "msg", iso := "mrg", value := .none }
  , { walsCode := "mis", iso := "miq", value := .none }
  , { walsCode := "mss", iso := "skd", value := .none }
  , { walsCode := "mxx", iso := "mxp", value := .none }
  , { walsCode := "mco", iso := "mco", value := .none }
  , { walsCode := "mxc", iso := "mig", value := .none }
  , { walsCode := "mxj", iso := "mio", value := .none }
  , { walsCode := "mxo", iso := "mie", value := .none }
  , { walsCode := "mxp", iso := "mil", value := .none }
  , { walsCode := "miy", iso := "mkf", value := .none }
  , { walsCode := "miz", iso := "lus", value := .none }
  , { walsCode := "mcv", iso := "moc", value := .none }
  , { walsCode := "mog", iso := "mhj", value := .none }
  , { walsCode := "moh", iso := "moh", value := .none }
  , { walsCode := "mok", iso := "mkj", value := .none }
  , { walsCode := "mom", iso := "mso", value := .none }
  , { walsCode := "mon", iso := "mnw", value := .none }
  , { walsCode := "mga", iso := "ndt", value := .none }
  , { walsCode := "mkh", iso := "", value := .none }
  , { walsCode := "mni", iso := "mnz", value := .none }
  , { walsCode := "mno", iso := "mnr", value := .none }
  , { walsCode := "moo", iso := "mos", value := .none }
  , { walsCode := "mor", iso := "mhz", value := .none }
  , { walsCode := "mri", iso := "mok", value := .none }
  , { walsCode := "moe", iso := "myv", value := .none }
  , { walsCode := "mro", iso := "mor", value := .none }
  , { walsCode := "mou", iso := "mgd", value := .none }
  , { walsCode := "mos", iso := "cas", value := .none }
  , { walsCode := "mtu", iso := "meu", value := .none }
  , { walsCode := "mot", iso := "siw", value := .none }
  , { walsCode := "mov", iso := "mzp", value := .none }
  , { walsCode := "mpo", iso := "mye", value := .none }
  , { walsCode := "mpu", iso := "akc", value := .none }
  , { walsCode := "aoj", iso := "aoj", value := .none }
  , { walsCode := "mui", iso := "bmr", value := .none }
  , { walsCode := "msc", iso := "chb", value := .none }
  , { walsCode := "mum", iso := "mzm", value := .none }
  , { walsCode := "mna", iso := "mnb", value := .none }
  , { walsCode := "mdg", iso := "mua", value := .none }
  , { walsCode := "mun", iso := "unr", value := .none }
  , { walsCode := "mgk", iso := "mhk", value := .none }
  , { walsCode := "mup", iso := "sur", value := .none }
  , { walsCode := "mrl", iso := "mur", value := .none }
  , { walsCode := "mpa", iso := "mwf", value := .none }
  , { walsCode := "mur", iso := "muz", value := .none }
  , { walsCode := "mrw", iso := "zmu", value := .none }
  , { walsCode := "mgu", iso := "mug", value := .none }
  , { walsCode := "msm", iso := "msu", value := .none }
  , { walsCode := "msq", iso := "hur", value := .none }
  , { walsCode := "mus", iso := "emi", value := .none }
  , { walsCode := "mut", iso := "css", value := .none }
  , { walsCode := "mwe", iso := "mwe", value := .none }
  , { walsCode := "mwo", iso := "mlv", value := .none }
  , { walsCode := "nab", iso := "naf", value := .none }
  , { walsCode := "ndr", iso := "wyy", value := .none }
  , { walsCode := "nad", iso := "mbj", value := .none }
  , { walsCode := "nma", iso := "nbi", value := .none }
  , { walsCode := "ngt", iso := "nmf", value := .none }
  , { walsCode := "nze", iso := "nzm", value := .none }
  , { walsCode := "nag", iso := "nce", value := .none }
  , { walsCode := "nah", iso := "nll", value := .none }
  , { walsCode := "nhh", iso := "", value := .none }
  , { walsCode := "nhm", iso := "ncl", value := .none }
  , { walsCode := "nht", iso := "nhg", value := .none }
  , { walsCode := "bio", iso := "bio", value := .none }
  , { walsCode := "nak", iso := "nak", value := .none }
  , { walsCode := "nkk", iso := "nck", value := .none }
  , { walsCode := "nal", iso := "nal", value := .none }
  , { walsCode := "kho", iso := "naq", value := .none }
  , { walsCode := "nmb", iso := "nab", value := .none }
  , { walsCode := "nam", iso := "nnm", value := .none }
  , { walsCode := "nde", iso := "nnb", value := .none }
  , { walsCode := "nan", iso := "niq", value := .none }
  , { walsCode := "nrg", iso := "sen", value := .none }
  , { walsCode := "nnk", iso := "nnk", value := .none }
  , { walsCode := "nph", iso := "npa", value := .none }
  , { walsCode := "nar", iso := "nrb", value := .none }
  , { walsCode := "nas", iso := "nas", value := .none }
  , { walsCode := "nav", iso := "nav", value := .none }
  , { walsCode := "nax", iso := "nxq", value := .none }
  , { walsCode := "ncm", iso := "bud", value := .none }
  , { walsCode := "ndb", iso := "nde", value := .none }
  , { walsCode := "ndj", iso := "djj", value := .none }
  , { walsCode := "ndo", iso := "ndo", value := .none }
  , { walsCode := "ndu", iso := "nmd", value := .none }
  , { walsCode := "ndt", iso := "ndv", value := .none }
  , { walsCode := "ndy", iso := "djk", value := .none }
  , { walsCode := "neh", iso := "nsn", value := .none }
  , { walsCode := "ntu", iso := "yrk", value := .none }
  , { walsCode := "nne", iso := "nen", value := .none }
  , { walsCode := "naj", iso := "aij", value := .none }
  , { walsCode := "nep", iso := "npi", value := .none }
  , { walsCode := "nev", iso := "pia", value := .none }
  , { walsCode := "nwd", iso := "new", value := .neginfix }
  , { walsCode := "new", iso := "new", value := .none }
  , { walsCode := "nez", iso := "nez", value := .none }
  , { walsCode := "ntj", iso := "ntj", value := .none }
  , { walsCode := "ngd", iso := "nxg", value := .none }
  , { walsCode := "ngj", iso := "nju", value := .none }
  , { walsCode := "ngl", iso := "nig", value := .none }
  , { walsCode := "ngm", iso := "sba", value := .none }
  , { walsCode := "nga", iso := "nio", value := .none }
  , { walsCode := "ngn", iso := "nid", value := .none }
  , { walsCode := "ngk", iso := "nam", value := .none }
  , { walsCode := "ngw", iso := "nxn", value := .none }
  , { walsCode := "nbm", iso := "nbm", value := .none }
  , { walsCode := "nti", iso := "niy", value := .none }
  , { walsCode := "ngi", iso := "wyb", value := .none }
  , { walsCode := "ngz", iso := "ngi", value := .none }
  , { walsCode := "ngo", iso := "ngo", value := .none }
  , { walsCode := "ngu", iso := "llp", value := .none }
  , { walsCode := "nbr", iso := "gym", value := .none }
  , { walsCode := "nha", iso := "nha", value := .none }
  , { walsCode := "nia", iso := "nia", value := .none }
  , { walsCode := "nca", iso := "caq", value := .none }
  , { walsCode := "nsn", iso := "nsz", value := .none }
  , { walsCode := "nsg", iso := "ncg", value := .none }
  , { walsCode := "nif", iso := "num", value := .none }
  , { walsCode := "niu", iso := "niu", value := .none }
  , { walsCode := "niv", iso := "niv", value := .none }
  , { walsCode := "nke", iso := "isi", value := .none }
  , { walsCode := "nkn", iso := "nko", value := .none }
  , { walsCode := "nko", iso := "cgg", value := .none }
  , { walsCode := "noc", iso := "njb", value := .none }
  , { walsCode := "non", iso := "nhu", value := .none }
  , { walsCode := "noo", iso := "snf", value := .none }
  , { walsCode := "nor", iso := "nor", value := .none }
  , { walsCode := "nse", iso := "nse", value := .none }
  , { walsCode := "nto", iso := "nto", value := .none }
  , { walsCode := "nua", iso := "nxl", value := .none }
  , { walsCode := "nbd", iso := "dgl", value := .none }
  , { walsCode := "nku", iso := "xnz", value := .none }
  , { walsCode := "nue", iso := "nus", value := .none }
  , { walsCode := "nun", iso := "nut", value := .none }
  , { walsCode := "nug", iso := "nuy", value := .none }
  , { walsCode := "yi", iso := "iii", value := .none }
  , { walsCode := "nup", iso := "nup", value := .none }
  , { walsCode := "nyk", iso := "tpq", value := .none }
  , { walsCode := "nym", iso := "nym", value := .none }
  , { walsCode := "nyr", iso := "nna", value := .none }
  , { walsCode := "nyn", iso := "nyh", value := .none }
  , { walsCode := "nyh", iso := "nih", value := .none }
  , { walsCode := "nyi", iso := "nyi", value := .none }
  , { walsCode := "nis", iso := "njz", value := .none }
  , { walsCode := "nyu", iso := "nyv", value := .none }
  , { walsCode := "nza", iso := "nzk", value := .none }
  , { walsCode := "ood", iso := "ood", value := .none }
  , { walsCode := "obo", iso := "ann", value := .none }
  , { walsCode := "ocu", iso := "ocu", value := .none }
  , { walsCode := "obg", iso := "ogu", value := .none }
  , { walsCode := "oir", iso := "xal", value := .none }
  , { walsCode := "oji", iso := "", value := .none }
  , { walsCode := "oks", iso := "opm", value := .none }
  , { walsCode := "olo", iso := "ong", value := .none }
  , { walsCode := "omh", iso := "oma", value := .none }
  , { walsCode := "one", iso := "aun", value := .none }
  , { walsCode := "ond", iso := "one", value := .none }
  , { walsCode := "ong", iso := "oon", value := .none }
  , { walsCode := "ono", iso := "ons", value := .none }
  , { walsCode := "ori", iso := "tag", value := .none }
  , { walsCode := "oya", iso := "ory", value := .none }
  , { walsCode := "ork", iso := "oaa", value := .none }
  , { walsCode := "oro", iso := "okv", value := .none }
  , { walsCode := "orh", iso := "hae", value := .negtone }
  , { walsCode := "orw", iso := "ssn", value := .none }
  , { walsCode := "osa", iso := "osa", value := .none }
  , { walsCode := "oss", iso := "oss", value := .none }
  , { walsCode := "otm", iso := "ote", value := .none }
  , { walsCode := "otr", iso := "otr", value := .none }
  , { walsCode := "paa", iso := "pqa", value := .none }
  , { walsCode := "pkn", iso := "drl", value := .none }
  , { walsCode := "pms", iso := "pma", value := .none }
  , { walsCode := "pno", iso := "pao", value := .none }
  , { walsCode := "pai", iso := "pwn", value := .none }
  , { walsCode := "pal", iso := "pau", value := .none }
  , { walsCode := "plg", iso := "pll", value := .none }
  , { walsCode := "pnn", iso := "pag", value := .none }
  , { walsCode := "png", iso := "pbr", value := .none }
  , { walsCode := "pan", iso := "pan", value := .none }
  , { walsCode := "pre", iso := "asa", value := .none }
  , { walsCode := "psh", iso := "pst", value := .none }
  , { walsCode := "psm", iso := "pqm", value := .none }
  , { walsCode := "pat", iso := "ptp", value := .none }
  , { walsCode := "ptt", iso := "lae", value := .none }
  , { walsCode := "ptw", iso := "pwi", value := .none }
  , { walsCode := "plh", iso := "plh", value := .none }
  , { walsCode := "pau", iso := "pad", value := .none }
  , { walsCode := "paw", iso := "pwa", value := .none }
  , { walsCode := "pwn", iso := "paw", value := .none }
  , { walsCode := "pec", iso := "pay", value := .none }
  , { walsCode := "per", iso := "pip", value := .none }
  , { walsCode := "prs", iso := "pes", value := .none }
  , { walsCode := "pia", iso := "pid", value := .none }
  , { walsCode := "pga", iso := "plg", value := .none }
  , { walsCode := "pba", iso := "pia", value := .none }
  , { walsCode := "pip", iso := "ppl", value := .none }
  , { walsCode := "prh", iso := "myp", value := .none }
  , { walsCode := "pis", iso := "psa", value := .none }
  , { walsCode := "pit", iso := "pjt", value := .none }
  , { walsCode := "ppi", iso := "pit", value := .none }
  , { walsCode := "pod", iso := "pbi", value := .none }
  , { walsCode := "pog", iso := "poy", value := .none }
  , { walsCode := "poh", iso := "pon", value := .none }
  , { walsCode := "pkt", iso := "pko", value := .none }
  , { walsCode := "pol", iso := "pol", value := .none }
  , { walsCode := "pme", iso := "peb", value := .none }
  , { walsCode := "pso", iso := "pom", value := .none }
  , { walsCode := "psj", iso := "poe", value := .none }
  , { walsCode := "zqs", iso := "poi", value := .none }
  , { walsCode := "psw", iso := "psw", value := .none }
  , { walsCode := "por", iso := "por", value := .none }
  , { walsCode := "pra", iso := "prn", value := .none }
  , { walsCode := "pul", iso := "puw", value := .none }
  , { walsCode := "pum", iso := "pmi", value := .none }
  , { walsCode := "pun", iso := "wdj", value := .none }
  , { walsCode := "prk", iso := "prx", value := .none }
  , { walsCode := "pur", iso := "tsz", value := .none }
  , { walsCode := "pae", iso := "pbb", value := .none }
  , { walsCode := "par", iso := "lkr", value := .none }
  , { walsCode := "qaw", iso := "alc", value := .none }
  , { walsCode := "qia", iso := "", value := .none }
  , { walsCode := "qhu", iso := "qub", value := .none }
  , { walsCode := "qim", iso := "qvi", value := .none }
  , { walsCode := "qui", iso := "qui", value := .none }
  , { walsCode := "rag", iso := "lml", value := .none }
  , { walsCode := "ram", iso := "rma", value := .none }
  , { walsCode := "rpa", iso := "bod", value := .none }
  , { walsCode := "rao", iso := "rao", value := .none }
  , { walsCode := "rap", iso := "rap", value := .none }
  , { walsCode := "ras", iso := "ras", value := .none }
  , { walsCode := "rwa", iso := "rwo", value := .none }
  , { walsCode := "raw", iso := "raw", value := .none }
  , { walsCode := "rem", iso := "bfw", value := .none }
  , { walsCode := "res", iso := "rgr", value := .none }
  , { walsCode := "ret", iso := "tnc", value := .none }
  , { walsCode := "rik", iso := "rkb", value := .none }
  , { walsCode := "rim", iso := "rim", value := .none }
  , { walsCode := "rit", iso := "rit", value := .none }
  , { walsCode := "rwe", iso := "rmw", value := .none }
  , { walsCode := "rom", iso := "ron", value := .none }
  , { walsCode := "rsu", iso := "roh", value := .none }
  , { walsCode := "ron", iso := "cla", value := .none }
  , { walsCode := "rot", iso := "rtm", value := .none }
  ]

private def allData_2 : List (Datapoint MinorMorphologicalMeansOfSignalingNegation) :=
  [ { walsCode := "rov", iso := "rug", value := .none }
  , { walsCode := "ruk", iso := "dru", value := .none }
  , { walsCode := "cos", iso := "", value := .none }
  , { walsCode := "rum", iso := "klq", value := .none }
  , { walsCode := "rnd", iso := "run", value := .none }
  , { walsCode := "run", iso := "rou", value := .none }
  , { walsCode := "rny", iso := "nyn", value := .none }
  , { walsCode := "rru", iso := "nyo", value := .none }
  , { walsCode := "rus", iso := "rus", value := .none }
  , { walsCode := "sno", iso := "sme", value := .none }
  , { walsCode := "sah", iso := "saj", value := .none }
  , { walsCode := "sak", iso := "sku", value := .none }
  , { walsCode := "slb", iso := "sbe", value := .none }
  , { walsCode := "sal", iso := "sln", value := .none }
  , { walsCode := "syu", iso := "sll", value := .none }
  , { walsCode := "sam", iso := "smo", value := .none }
  , { walsCode := "sdw", iso := "sad", value := .none }
  , { walsCode := "san", iso := "sag", value := .none }
  , { walsCode := "sgu", iso := "snq", value := .none }
  , { walsCode := "sta", iso := "sce", value := .none }
  , { walsCode := "stl", iso := "sat", value := .none }
  , { walsCode := "snm", iso := "xsu", value := .none }
  , { walsCode := "sap", iso := "spu", value := .none }
  , { walsCode := "src", iso := "srs", value := .none }
  , { walsCode := "srd", iso := "sro", value := .none }
  , { walsCode := "sar", iso := "dju", value := .none }
  , { walsCode := "svs", iso := "svs", value := .none }
  , { walsCode := "saw", iso := "hvn", value := .none }
  , { walsCode := "sed", iso := "sed", value := .none }
  , { walsCode := "see", iso := "trv", value := .none }
  , { walsCode := "sel", iso := "ona", value := .none }
  , { walsCode := "sem", iso := "nsm", value := .none }
  , { walsCode := "sme", iso := "sif", value := .none }
  , { walsCode := "sml", iso := "sza", value := .none }
  , { walsCode := "smn", iso := "mus", value := .none }
  , { walsCode := "sgl", iso := "szg", value := .none }
  , { walsCode := "snt", iso := "set", value := .none }
  , { walsCode := "scr", iso := "hbs", value := .none }
  , { walsCode := "ser", iso := "sei", value := .none }
  , { walsCode := "ses", iso := "sot", value := .none }
  , { walsCode := "shb", iso := "sbf", value := .none }
  , { walsCode := "shm", iso := "ksb", value := .none }
  , { walsCode := "shh", iso := "mcd", value := .none }
  , { walsCode := "sht", iso := "shj", value := .none }
  , { walsCode := "skw", iso := "swv", value := .none }
  , { walsCode := "she", iso := "xsr", value := .none }
  , { walsCode := "shl", iso := "shk", value := .none }
  , { walsCode := "sna", iso := "scl", value := .none }
  , { walsCode := "shk", iso := "shp", value := .none }
  , { walsCode := "shy", iso := "yuy", value := .none }
  , { walsCode := "shi", iso := "shb", value := .none }
  , { walsCode := "shn", iso := "sna", value := .none }
  , { walsCode := "shu", iso := "shs", value := .none }
  , { walsCode := "sia", iso := "snp", value := .none }
  , { walsCode := "sir", iso := "sjr", value := .none }
  , { walsCode := "sid", iso := "sid", value := .none }
  , { walsCode := "skk", iso := "sip", value := .none }
  , { walsCode := "sil", iso := "dau", value := .none }
  , { walsCode := "sng", iso := "snc", value := .none }
  , { walsCode := "sio", iso := "xsi", value := .none }
  , { walsCode := "sin", iso := "snn", value := .none }
  , { walsCode := "qum", iso := "qum", value := .none }
  , { walsCode := "sro", iso := "ssd", value := .none }
  , { walsCode := "ssa", iso := "sil", value := .none }
  , { walsCode := "sis", iso := "baa", value := .none }
  , { walsCode := "siu", iso := "sis", value := .none }
  , { walsCode := "sla", iso := "den", value := .none }
  , { walsCode := "slo", iso := "slv", value := .none }
  , { walsCode := "so", iso := "teu", value := .none }
  , { walsCode := "sob", iso := "sob", value := .none }
  , { walsCode := "sod", iso := "gru", value := .none }
  , { walsCode := "som", iso := "som", value := .none }
  , { walsCode := "snn", iso := "snk", value := .none }
  , { walsCode := "son", iso := "sov", value := .none }
  , { walsCode := "sor", iso := "srb", value := .none }
  , { walsCode := "srb", iso := "", value := .none }
  , { walsCode := "stn", iso := "nso", value := .none }
  , { walsCode := "sgb", iso := "mnx", value := .none }
  , { walsCode := "tou", iso := "wib", value := .none }
  , { walsCode := "spa", iso := "spa", value := .none }
  , { walsCode := "squ", iso := "squ", value := .none }
  , { walsCode := "sre", iso := "kpm", value := .none }
  , { walsCode := "sti", iso := "", value := .none }
  , { walsCode := "sub", iso := "sbs", value := .none }
  , { walsCode := "sud", iso := "tgo", value := .none }
  , { walsCode := "sue", iso := "sue", value := .none }
  , { walsCode := "skm", iso := "suk", value := .none }
  , { walsCode := "sul", iso := "sua", value := .none }
  , { walsCode := "sun", iso := "sun", value := .none }
  , { walsCode := "sug", iso := "sjg", value := .none }
  , { walsCode := "sup", iso := "spp", value := .none }
  , { walsCode := "swa", iso := "swh", value := .none }
  , { walsCode := "swt", iso := "ssw", value := .none }
  , { walsCode := "swe", iso := "swe", value := .none }
  , { walsCode := "sba", iso := "slc", value := .none }
  , { walsCode := "tab", iso := "mky", value := .none }
  , { walsCode := "tba", iso := "sst", value := .none }
  , { walsCode := "tbl", iso := "tnm", value := .neginfix }
  , { walsCode := "tbw", iso := "tap", value := .none }
  , { walsCode := "tac", iso := "tna", value := .none }
  , { walsCode := "tag", iso := "tgl", value := .none }
  , { walsCode := "tah", iso := "tah", value := .none }
  , { walsCode := "taf", iso := "sps", value := .none }
  , { walsCode := "trr", iso := "tbg", value := .none }
  , { walsCode := "taj", iso := "tgk", value := .none }
  , { walsCode := "tkl", iso := "tkm", value := .none }
  , { walsCode := "tak", iso := "tbc", value := .none }
  , { walsCode := "tal", iso := "tlj", value := .none }
  , { walsCode := "tma", iso := "tma", value := .none }
  , { walsCode := "tmm", iso := "mla", value := .none }
  , { walsCode := "tam", iso := "taj", value := .none }
  , { walsCode := "tsk", iso := "taq", value := .negstemchange }
  , { walsCode := "tml", iso := "tam", value := .none }
  , { walsCode := "tnc", iso := "tcb", value := .none }
  , { walsCode := "tan", iso := "tan", value := .none }
  , { walsCode := "tbx", iso := "skj", value := .none }
  , { walsCode := "tpt", iso := "tpj", value := .none }
  , { walsCode := "tce", iso := "tar", value := .none }
  , { walsCode := "twe", iso := "tac", value := .none }
  , { walsCode := "tao", iso := "tro", value := .none }
  , { walsCode := "tar", iso := "tae", value := .none }
  , { walsCode := "tas", iso := "shi", value := .none }
  , { walsCode := "tts", iso := "tks", value := .none }
  , { walsCode := "tsg", iso := "tsg", value := .none }
  , { walsCode := "tau", iso := "tya", value := .none }
  , { walsCode := "taw", iso := "tbo", value := .none }
  , { walsCode := "tbo", iso := "tbl", value := .none }
  , { walsCode := "tel", iso := "tel", value := .none }
  , { walsCode := "tmn", iso := "teq", value := .none }
  , { walsCode := "tmr", iso := "tea", value := .none }
  , { walsCode := "tne", iso := "tem", value := .none }
  , { walsCode := "ten", iso := "tex", value := .none }
  , { walsCode := "tny", iso := "kza", value := .none }
  , { walsCode := "teo", iso := "tio", value := .none }
  , { walsCode := "tee", iso := "tee", value := .none }
  , { walsCode := "tep", iso := "tpt", value := .none }
  , { walsCode := "tpn", iso := "ntp", value := .none }
  , { walsCode := "ter", iso := "ttr", value := .none }
  , { walsCode := "trb", iso := "tfr", value := .none }
  , { walsCode := "tes", iso := "teo", value := .none }
  , { walsCode := "tet", iso := "tll", value := .none }
  , { walsCode := "ttn", iso := "tet", value := .none }
  , { walsCode := "tha", iso := "tha", value := .none }
  , { walsCode := "thn", iso := "thf", value := .none }
  , { walsCode := "tho", iso := "thp", value := .none }
  , { walsCode := "thu", iso := "tdh", value := .none }
  , { walsCode := "tdr", iso := "bod", value := .none }
  , { walsCode := "tmo", iso := "bod", value := .none }
  , { walsCode := "tis", iso := "bod", value := .none }
  , { walsCode := "tib", iso := "bod", value := .none }
  , { walsCode := "tid", iso := "tvo", value := .none }
  , { walsCode := "tgk", iso := "tgc", value := .none }
  , { walsCode := "tig", iso := "tir", value := .none }
  , { walsCode := "tgr", iso := "tig", value := .none }
  , { walsCode := "tja", iso := "dih", value := .none }
  , { walsCode := "tim", iso := "tih", value := .none }
  , { walsCode := "tin", iso := "cir", value := .none }
  , { walsCode := "tir", iso := "tri", value := .none }
  , { walsCode := "trm", iso := "suq", value := .none }
  , { walsCode := "tiv", iso := "tiv", value := .none }
  , { walsCode := "twn", iso := "twf", value := .none }
  , { walsCode := "tiw", iso := "tiw", value := .none }
  , { walsCode := "tlp", iso := "tcf", value := .none }
  , { walsCode := "tli", iso := "tli", value := .none }
  , { walsCode := "tob", iso := "tob", value := .none }
  , { walsCode := "tbt", iso := "tti", value := .none }
  , { walsCode := "tlo", iso := "tlb", value := .none }
  , { walsCode := "tod", iso := "sbu", value := .none }
  , { walsCode := "tke", iso := "tkl", value := .none }
  , { walsCode := "tol", iso := "jic", value := .none }
  , { walsCode := "tla", iso := "ksd", value := .none }
  , { walsCode := "tno", iso := "tdn", value := .none }
  , { walsCode := "toz", iso := "toi", value := .none }
  , { walsCode := "tng", iso := "ton", value := .none }
  , { walsCode := "ton", iso := "tqw", value := .none }
  , { walsCode := "tpa", iso := "top", value := .none }
  , { walsCode := "tri", iso := "trc", value := .none }
  , { walsCode := "tru", iso := "tpy", value := .none }
  , { walsCode := "tsf", iso := "cof", value := .none }
  , { walsCode := "tsz", iso := "ddo", value := .none }
  , { walsCode := "tgl", iso := "tsj", value := .none }
  , { walsCode := "tsi", iso := "tsi", value := .none }
  , { walsCode := "tgo", iso := "tsv", value := .none }
  , { walsCode := "tsn", iso := "tso", value := .none }
  , { walsCode := "ttu", iso := "bbl", value := .none }
  , { walsCode := "tgh", iso := "thv", value := .none }
  , { walsCode := "tbu", iso := "", value := .none }
  , { walsCode := "tuc", iso := "tuo", value := .none }
  , { walsCode := "tuk", iso := "", value := .none }
  , { walsCode := "tki", iso := "bag", value := .none }
  , { walsCode := "tul", iso := "tcy", value := .none }
  , { walsCode := "tnn", iso := "tvu", value := .none }
  , { walsCode := "tun", iso := "tun", value := .none }
  , { walsCode := "tpr", iso := "tui", value := .none }
  , { walsCode := "tna", iso := "tuv", value := .none }
  , { walsCode := "tur", iso := "tur", value := .none }
  , { walsCode := "tus", iso := "tus", value := .none }
  , { walsCode := "tte", iso := "tta", value := .none }
  , { walsCode := "tvl", iso := "tvl", value := .none }
  , { walsCode := "tuv", iso := "tyv", value := .none }
  , { walsCode := "tuy", iso := "tue", value := .none }
  , { walsCode := "tye", iso := "woa", value := .none }
  , { walsCode := "tzo", iso := "tzo", value := .none }
  , { walsCode := "tzu", iso := "tzj", value := .none }
  , { walsCode := "tsh", iso := "par", value := .none }
  , { walsCode := "uby", iso := "uby", value := .none }
  , { walsCode := "udi", iso := "udi", value := .none }
  , { walsCode := "udh", iso := "ude", value := .none }
  , { walsCode := "udm", iso := "udm", value := .none }
  , { walsCode := "ukr", iso := "ukr", value := .none }
  , { walsCode := "uld", iso := "udl", value := .none }
  , { walsCode := "uli", iso := "uli", value := .none }
  , { walsCode := "una", iso := "mtg", value := .none }
  , { walsCode := "ung", iso := "ung", value := .none }
  , { walsCode := "url", iso := "urk", value := .none }
  , { walsCode := "urn", iso := "ura", value := .none }
  , { walsCode := "urt", iso := "urt", value := .none }
  , { walsCode := "urd", iso := "urd", value := .none }
  , { walsCode := "uru", iso := "ure", value := .none }
  , { walsCode := "urk", iso := "urb", value := .none }
  , { walsCode := "usa", iso := "wnu", value := .none }
  , { walsCode := "usr", iso := "usa", value := .none }
  , { walsCode := "ute", iso := "ute", value := .none }
  , { walsCode := "uyg", iso := "uig", value := .none }
  , { walsCode := "uzb", iso := "", value := .none }
  , { walsCode := "vai", iso := "vai", value := .none }
  , { walsCode := "ven", iso := "ven", value := .none }
  , { walsCode := "vie", iso := "vie", value := .none }
  , { walsCode := "vnm", iso := "vnm", value := .none }
  , { walsCode := "wag", iso := "waq", value := .none }
  , { walsCode := "wah", iso := "", value := .none }
  , { walsCode := "wai", iso := "waw", value := .none }
  , { walsCode := "wak", iso := "wbl", value := .none }
  , { walsCode := "wal", iso := "van", value := .none }
  , { walsCode := "wlm", iso := "wmt", value := .none }
  , { walsCode := "wam", iso := "wmb", value := .none }
  , { walsCode := "wbn", iso := "wms", value := .none }
  , { walsCode := "wme", iso := "wme", value := .none }
  , { walsCode := "wna", iso := "wan", value := .none }
  , { walsCode := "wao", iso := "auc", value := .none }
  , { walsCode := "wap", iso := "wao", value := .none }
  , { walsCode := "wra", iso := "wba", value := .none }
  , { walsCode := "wrd", iso := "wrr", value := .none }
  , { walsCode := "wrk", iso := "gae", value := .none }
  , { walsCode := "wrm", iso := "wsa", value := .none }
  , { walsCode := "war", iso := "pav", value := .none }
  , { walsCode := "wrl", iso := "wbp", value := .none }
  , { walsCode := "wlw", iso := "wrb", value := .none }
  , { walsCode := "wrn", iso := "wnd", value := .none }
  , { walsCode := "wrg", iso := "wgy", value := .none }
  , { walsCode := "wrb", iso := "gjm", value := .none }
  , { walsCode := "was", iso := "was", value := .none }
  , { walsCode := "wsk", iso := "wsk", value := .none }
  , { walsCode := "wtm", iso := "wax", value := .none }
  , { walsCode := "wat", iso := "wbv", value := .none }
  , { walsCode := "wau", iso := "noa", value := .none }
  , { walsCode := "way", iso := "oym", value := .none }
  , { walsCode := "wed", iso := "wed", value := .none }
  , { walsCode := "wel", iso := "cym", value := .none }
  , { walsCode := "wec", iso := "cym", value := .none }
  , { walsCode := "wem", iso := "xww", value := .none }
  , { walsCode := "wma", iso := "mqs", value := .none }
  , { walsCode := "wic", iso := "wic", value := .none }
  , { walsCode := "wch", iso := "mzh", value := .none }
  , { walsCode := "wmu", iso := "wim", value := .none }
  , { walsCode := "wik", iso := "yok", value := .none }
  , { walsCode := "win", iso := "wnw", value := .none }
  , { walsCode := "wiy", iso := "wiy", value := .none }
  , { walsCode := "woi", iso := "woi", value := .none }
  , { walsCode := "wly", iso := "wal", value := .none }
  , { walsCode := "wol", iso := "woe", value := .none }
  , { walsCode := "wlf", iso := "wol", value := .none }
  , { walsCode := "wom", iso := "wmx", value := .none }
  , { walsCode := "wor", iso := "wro", value := .none }
  , { walsCode := "wya", iso := "wya", value := .none }
  , { walsCode := "xav", iso := "xav", value := .none }
  , { walsCode := "xho", iso := "xho", value := .none }
  , { walsCode := "xar", iso := "ane", value := .none }
  , { walsCode := "ygr", iso := "ygr", value := .none }
  , { walsCode := "yag", iso := "yad", value := .none }
  , { walsCode := "ykt", iso := "sah", value := .none }
  , { walsCode := "yam", iso := "yaa", value := .none }
  , { walsCode := "ybi", iso := "ybi", value := .none }
  , { walsCode := "yao", iso := "yao", value := .none }
  , { walsCode := "yap", iso := "yap", value := .none }
  , { walsCode := "yqy", iso := "jaq", value := .none }
  , { walsCode := "yaq", iso := "yaq", value := .none }
  , { walsCode := "yar", iso := "yrb", value := .none }
  , { walsCode := "yrr", iso := "yae", value := .none }
  , { walsCode := "ywl", iso := "yok", value := .none }
  , { walsCode := "ywr", iso := "ywr", value := .none }
  , { walsCode := "yei", iso := "jei", value := .none }
  , { walsCode := "ylm", iso := "jel", value := .none }
  , { walsCode := "yiw", iso := "ywq", value := .none }
  , { walsCode := "yid", iso := "yii", value := .none }
  , { walsCode := "yim", iso := "yee", value := .none }
  , { walsCode := "yin", iso := "yij", value := .none }
  , { walsCode := "yng", iso := "yia", value := .none }
  , { walsCode := "yok", iso := "yok", value := .none }
  , { walsCode := "yor", iso := "yor", value := .none }
  , { walsCode := "yuc", iso := "yuc", value := .none }
  , { walsCode := "yko", iso := "yux", value := .none }
  , { walsCode := "ytu", iso := "ykg", value := .none }
  , { walsCode := "yuk", iso := "gcd", value := .none }
  , { walsCode := "yul", iso := "yul", value := .none }
  , { walsCode := "ypk", iso := "esu", value := .none }
  , { walsCode := "yrm", iso := "", value := .none }
  , { walsCode := "yur", iso := "yur", value := .none }
  , { walsCode := "yuw", iso := "kld", value := .none }
  , { walsCode := "zan", iso := "zne", value := .none }
  , { walsCode := "zpr", iso := "zro", value := .none }
  , { walsCode := "zai", iso := "zai", value := .none }
  , { walsCode := "zap", iso := "zaw", value := .none }
  , { walsCode := "zzo", iso := "zpq", value := .none }
  , { walsCode := "zar", iso := "dje", value := .none }
  , { walsCode := "zay", iso := "zay", value := .none }
  , { walsCode := "zaz", iso := "diq", value := .none }
  , { walsCode := "zch", iso := "zoh", value := .none }
  , { walsCode := "zqc", iso := "zoc", value := .none }
  , { walsCode := "zqo", iso := "zoc", value := .none }
  , { walsCode := "zul", iso := "zul", value := .none }
  , { walsCode := "zun", iso := "zun", value := .none }
  , { walsCode := "rgc", iso := "jya", value := .none }
  , { walsCode := "eme", iso := "eme", value := .none }
  , { walsCode := "omi", iso := "aom", value := .none }
  ]

/-- Complete WALS 143G dataset (1325 languages). -/
def allData : List (Datapoint MinorMorphologicalMeansOfSignalingNegation) := allData_0 ++ allData_1 ++ allData_2

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F143G
