import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 144S: SOVNeg Order
@cite{wals-2013}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 144S`.

Chapter 144, 490 languages.
-/

namespace Core.WALS.F144S

/-- WALS 144S values. -/
inductive SovnegOrder where
  /-- Word&NoDoubleNeg (60 languages). -/
  | wordNodoubleneg
  /-- Suffix&NoDoubleNeg (142 languages). -/
  | suffixNodoubleneg
  /-- Word&OptDoubleNeg (7 languages). -/
  | wordOptdoubleneg
  /-- Suffix&OptDoubleNeg (8 languages). -/
  | suffixOptdoubleneg
  /-- Word&OnlyWithAnotherNeg (10 languages). -/
  | wordOnlywithanotherneg
  /-- Suffix&OnlyWithAnotherNeg (32 languages). -/
  | suffixOnlywithanotherneg
  /-- Type 1 / Type 2 (8 languages). -/
  | type1Type2
  /-- Type 1 / Type 6 (2 languages). -/
  | type1Type6
  /-- Type 5 / Type 4 (2 languages). -/
  | type5Type4
  /-- Type 5 / Type 6 (2 languages). -/
  | type5Type6
  /-- NoSOVNeg (217 languages). -/
  | nosovneg
  deriving DecidableEq, BEq, Repr

/-- Complete WALS 144S dataset (490 languages). -/
def allData : List (Datapoint SovnegOrder) :=
  [ { walsCode := "aba", iso := "aau", value := .wordNodoubleneg }
  , { walsCode := "abk", iso := "abk", value := .suffixNodoubleneg }
  , { walsCode := "abv", iso := "abz", value := .wordNodoubleneg }
  , { walsCode := "adg", iso := "adn", value := .wordOptdoubleneg }
  , { walsCode := "ain", iso := "ain", value := .nosovneg }
  , { walsCode := "ajg", iso := "ajg", value := .wordNodoubleneg }
  , { walsCode := "akh", iso := "ahk", value := .nosovneg }
  , { walsCode := "all", iso := "nrz", value := .nosovneg }
  , { walsCode := "ala", iso := "amp", value := .nosovneg }
  , { walsCode := "aly", iso := "aly", value := .suffixNodoubleneg }
  , { walsCode := "amn", iso := "amn", value := .suffixOnlywithanotherneg }
  , { walsCode := "amb", iso := "abt", value := .suffixNodoubleneg }
  , { walsCode := "ame", iso := "aey", value := .suffixOptdoubleneg }
  , { walsCode := "amh", iso := "amh", value := .suffixOnlywithanotherneg }
  , { walsCode := "agm", iso := "njm", value := .wordNodoubleneg }
  , { walsCode := "ang", iso := "agg", value := .suffixNodoubleneg }
  , { walsCode := "ao", iso := "njo", value := .suffixOnlywithanotherneg }
  , { walsCode := "apw", iso := "apw", value := .suffixOnlywithanotherneg }
  , { walsCode := "apl", iso := "apy", value := .suffixNodoubleneg }
  , { walsCode := "apt", iso := "apt", value := .suffixNodoubleneg }
  , { walsCode := "abn", iso := "ard", value := .nosovneg }
  , { walsCode := "arc", iso := "aqc", value := .suffixNodoubleneg }
  , { walsCode := "arm", iso := "hye", value := .nosovneg }
  , { walsCode := "arw", iso := "hyw", value := .nosovneg }
  , { walsCode := "amp", iso := "aer", value := .suffixNodoubleneg }
  , { walsCode := "asm", iso := "cns", value := .wordNodoubleneg }
  , { walsCode := "ass", iso := "asm", value := .nosovneg }
  , { walsCode := "ath", iso := "aph", value := .suffixNodoubleneg }
  , { walsCode := "ava", iso := "ava", value := .wordNodoubleneg }
  , { walsCode := "awa", iso := "awb", value := .nosovneg }
  , { walsCode := "awp", iso := "kwi", value := .type5Type6 }
  , { walsCode := "awt", iso := "kmn", value := .nosovneg }
  , { walsCode := "aym", iso := "ayr", value := .nosovneg }
  , { walsCode := "azi", iso := "azb", value := .suffixNodoubleneg }
  , { walsCode := "aze", iso := "", value := .suffixNodoubleneg }
  , { walsCode := "bdm", iso := "bia", value := .nosovneg }
  , { walsCode := "baf", iso := "bfd", value := .nosovneg }
  , { walsCode := "blt", iso := "bft", value := .wordNodoubleneg }
  , { walsCode := "bam", iso := "bam", value := .nosovneg }
  , { walsCode := "bao", iso := "peh", value := .nosovneg }
  , { walsCode := "brl", iso := "loy", value := .nosovneg }
  , { walsCode := "baa", iso := "bbb", value := .nosovneg }
  , { walsCode := "brp", iso := "bpe", value := .nosovneg }
  , { walsCode := "bsq", iso := "eus", value := .nosovneg }
  , { walsCode := "bzi", iso := "bvz", value := .wordNodoubleneg }
  , { walsCode := "baw", iso := "bgr", value := .wordNodoubleneg }
  , { walsCode := "bej", iso := "bej", value := .nosovneg }
  , { walsCode := "ben", iso := "ben", value := .wordNodoubleneg }
  , { walsCode := "zag", iso := "zag", value := .suffixNodoubleneg }
  , { walsCode := "bti", iso := "", value := .suffixNodoubleneg }
  , { walsCode := "bho", iso := "bho", value := .nosovneg }
  , { walsCode := "blx", iso := "bll", value := .wordOptdoubleneg }
  , { walsCode := "biu", iso := "", value := .nosovneg }
  , { walsCode := "boa", iso := "kvg", value := .suffixNodoubleneg }
  , { walsCode := "bok", iso := "bqc", value := .wordOptdoubleneg }
  , { walsCode := "bri", iso := "bzd", value := .nosovneg }
  , { walsCode := "ghr", iso := "bfu", value := .nosovneg }
  , { walsCode := "bua", iso := "bvr", value := .nosovneg }
  , { walsCode := "but", iso := "bxm", value := .suffixNodoubleneg }
  , { walsCode := "brm", iso := "mya", value := .wordOnlywithanotherneg }
  , { walsCode := "bur", iso := "bsk", value := .nosovneg }
  , { walsCode := "bus", iso := "bqp", value := .wordNodoubleneg }
  , { walsCode := "cah", iso := "chl", value := .nosovneg }
  , { walsCode := "cml", iso := "rab", value := .suffixOnlywithanotherneg }
  , { walsCode := "can", iso := "cbu", value := .suffixNodoubleneg }
  , { walsCode := "cnl", iso := "ram", value := .wordNodoubleneg }
  , { walsCode := "car", iso := "car", value := .suffixNodoubleneg }
  , { walsCode := "cde", iso := "mch", value := .suffixNodoubleneg }
  , { walsCode := "cas", iso := "cbr", value := .suffixNodoubleneg }
  , { walsCode := "cay", iso := "cbi", value := .suffixNodoubleneg }
  , { walsCode := "chh", iso := "sgw", value := .nosovneg }
  , { walsCode := "cai", iso := "suq", value := .wordNodoubleneg }
  , { walsCode := "chb", iso := "can", value := .nosovneg }
  , { walsCode := "chg", iso := "nbc", value := .nosovneg }
  , { walsCode := "chd", iso := "cdn", value := .nosovneg }
  , { walsCode := "chc", iso := "che", value := .nosovneg }
  , { walsCode := "cpn", iso := "cdm", value := .suffixNodoubleneg }
  , { walsCode := "cpy", iso := "cap", value := .nosovneg }
  , { walsCode := "chp", iso := "chp", value := .wordNodoubleneg }
  , { walsCode := "ctm", iso := "ctm", value := .suffixNodoubleneg }
  , { walsCode := "cct", iso := "cho", value := .suffixNodoubleneg }
  , { walsCode := "cln", iso := "cht", value := .suffixNodoubleneg }
  , { walsCode := "chv", iso := "chv", value := .suffixNodoubleneg }
  , { walsCode := "coa", iso := "xcw", value := .suffixNodoubleneg }
  , { walsCode := "cmn", iso := "com", value := .nosovneg }
  , { walsCode := "cui", iso := "cui", value := .suffixOnlywithanotherneg }
  , { walsCode := "cup", iso := "cup", value := .nosovneg }
  , { walsCode := "dag", iso := "dgz", value := .nosovneg }
  , { walsCode := "dgr", iso := "dta", value := .nosovneg }
  , { walsCode := "dan", iso := "dnj", value := .nosovneg }
  , { walsCode := "dni", iso := "dni", value := .wordNodoubleneg }
  , { walsCode := "drm", iso := "drd", value := .nosovneg }
  , { walsCode := "des", iso := "des", value := .suffixNodoubleneg }
  , { walsCode := "deu", iso := "der", value := .suffixNodoubleneg }
  , { walsCode := "dha", iso := "dsh", value := .suffixOnlywithanotherneg }
  , { walsCode := "dhm", iso := "dhi", value := .nosovneg }
  , { walsCode := "die", iso := "dih", value := .wordNodoubleneg }
  , { walsCode := "dig", iso := "mhu", value := .suffixNodoubleneg }
  , { walsCode := "dim", iso := "dim", value := .suffixNodoubleneg }
  , { walsCode := "din", iso := "din", value := .nosovneg }
  , { walsCode := "dja", iso := "dyy", value := .nosovneg }
  , { walsCode := "djp", iso := "dwu", value := .nosovneg }
  , { walsCode := "dji", iso := "jig", value := .nosovneg }
  , { walsCode := "dds", iso := "dds", value := .suffixNodoubleneg }
  , { walsCode := "dum", iso := "vam", value := .wordNodoubleneg }
  , { walsCode := "dun", iso := "duc", value := .type1Type6 }
  , { walsCode := "dut", iso := "nld", value := .nosovneg }
  , { walsCode := "eip", iso := "eip", value := .wordNodoubleneg }
  , { walsCode := "eka", iso := "ekg", value := .wordNodoubleneg }
  , { walsCode := "ene", iso := "", value := .nosovneg }
  , { walsCode := "epe", iso := "sja", value := .suffixNodoubleneg }
  , { walsCode := "ese", iso := "ese", value := .wordNodoubleneg }
  , { walsCode := "eud", iso := "", value := .nosovneg }
  , { walsCode := "evn", iso := "eve", value := .suffixOnlywithanotherneg }
  , { walsCode := "eve", iso := "evn", value := .suffixOnlywithanotherneg }
  , { walsCode := "fur", iso := "fvr", value := .suffixOnlywithanotherneg }
  , { walsCode := "gds", iso := "gaj", value := .nosovneg }
  , { walsCode := "gah", iso := "gah", value := .suffixNodoubleneg }
  , { walsCode := "gal", iso := "adl", value := .suffixNodoubleneg }
  , { walsCode := "gap", iso := "pwg", value := .nosovneg }
  , { walsCode := "gar", iso := "grt", value := .suffixNodoubleneg }
  , { walsCode := "geo", iso := "kat", value := .nosovneg }
  , { walsCode := "ger", iso := "deu", value := .nosovneg }
  , { walsCode := "gim", iso := "bcq", value := .suffixNodoubleneg }
  , { walsCode := "gln", iso := "gvf", value := .suffixNodoubleneg }
  , { walsCode := "gon", iso := "gno", value := .suffixNodoubleneg }
  , { walsCode := "grb", iso := "grj", value := .nosovneg }
  , { walsCode := "grw", iso := "kal", value := .suffixNodoubleneg }
  , { walsCode := "gug", iso := "ktd", value := .suffixNodoubleneg }
  , { walsCode := "guh", iso := "ghs", value := .suffixOptdoubleneg }
  , { walsCode := "guj", iso := "guj", value := .nosovneg }
  , { walsCode := "gmw", iso := "gvs", value := .nosovneg }
  , { walsCode := "gur", iso := "", value := .nosovneg }
  , { walsCode := "guu", iso := "kky", value := .nosovneg }
  , { walsCode := "gwa", iso := "gbr", value := .wordOnlywithanotherneg }
  , { walsCode := "hai", iso := "hai", value := .suffixOnlywithanotherneg }
  , { walsCode := "ham", iso := "hmt", value := .nosovneg }
  , { walsCode := "hay", iso := "vay", value := .nosovneg }
  , { walsCode := "hid", iso := "hid", value := .suffixNodoubleneg }
  , { walsCode := "hin", iso := "hin", value := .nosovneg }
  , { walsCode := "hop", iso := "hop", value := .nosovneg }
  , { walsCode := "hua", iso := "ygr", value := .nosovneg }
  , { walsCode := "hlp", iso := "yuf", value := .wordOptdoubleneg }
  , { walsCode := "hui", iso := "hch", value := .nosovneg }
  , { walsCode := "hmi", iso := "hto", value := .suffixNodoubleneg }
  , { walsCode := "hum", iso := "huu", value := .suffixNodoubleneg }
  , { walsCode := "hzb", iso := "huz", value := .suffixNodoubleneg }
  , { walsCode := "hpd", iso := "jup", value := .suffixNodoubleneg }
  , { walsCode := "isa", iso := "ksi", value := .wordNodoubleneg }
  , { walsCode := "idn", iso := "viv", value := .nosovneg }
  , { walsCode := "ijo", iso := "ijc", value := .type1Type2 }
  , { walsCode := "ika", iso := "arh", value := .suffixNodoubleneg }
  , { walsCode := "inn", iso := "ynd", value := .nosovneg }
  , { walsCode := "irx", iso := "irn", value := .suffixNodoubleneg }
  , { walsCode := "irq", iso := "irk", value := .suffixNodoubleneg }
  , { walsCode := "ite", iso := "itl", value := .suffixOnlywithanotherneg }
  , { walsCode := "iwm", iso := "iwm", value := .wordNodoubleneg }
  , { walsCode := "jms", iso := "djm", value := .suffixNodoubleneg }
  , { walsCode := "jpn", iso := "jpn", value := .suffixNodoubleneg }
  , { walsCode := "jng", iso := "kac", value := .nosovneg }
  , { walsCode := "jiv", iso := "jiv", value := .suffixNodoubleneg }
  , { walsCode := "joh", iso := "rgk", value := .nosovneg }
  , { walsCode := "kab", iso := "kbd", value := .suffixNodoubleneg }
  , { walsCode := "kac", iso := "xac", value := .suffixNodoubleneg }
  , { walsCode := "kng", iso := "kgp", value := .wordNodoubleneg }
  , { walsCode := "krr", iso := "kxa", value := .wordNodoubleneg }
  , { walsCode := "kae", iso := "tbd", value := .nosovneg }
  , { walsCode := "kll", iso := "bco", value := .suffixNodoubleneg }
  , { walsCode := "kma", iso := "kay", value := .suffixOptdoubleneg }
  , { walsCode := "kmz", iso := "kms", value := .wordNodoubleneg }
  , { walsCode := "kms", iso := "xas", value := .nosovneg }
  , { walsCode := "kbo", iso := "kbx", value := .suffixNodoubleneg }
  , { walsCode := "kmr", iso := "kgq", value := .suffixNodoubleneg }
  , { walsCode := "xns", iso := "xns", value := .nosovneg }
  , { walsCode := "knd", iso := "kan", value := .suffixNodoubleneg }
  , { walsCode := "knb", iso := "khd", value := .nosovneg }
  , { walsCode := "knr", iso := "knc", value := .suffixNodoubleneg }
  , { walsCode := "krc", iso := "krc", value := .type1Type2 }
  , { walsCode := "kkp", iso := "kaa", value := .suffixNodoubleneg }
  , { walsCode := "kyr", iso := "yuj", value := .type1Type2 }
  , { walsCode := "kaa", iso := "arr", value := .wordNodoubleneg }
  , { walsCode := "kti", iso := "kts", value := .wordNodoubleneg }
  , { walsCode := "kyz", iso := "kyz", value := .suffixOptdoubleneg }
  , { walsCode := "kyp", iso := "txu", value := .wordNodoubleneg }
  , { walsCode := "kem", iso := "ahg", value := .suffixNodoubleneg }
  , { walsCode := "ket", iso := "ket", value := .nosovneg }
  , { walsCode := "kew", iso := "kew", value := .nosovneg }
  , { walsCode := "khl", iso := "klj", value := .suffixNodoubleneg }
  , { walsCode := "khg", iso := "klr", value := .suffixOnlywithanotherneg }
  , { walsCode := "kha", iso := "khk", value := .suffixNodoubleneg }
  , { walsCode := "kmh", iso := "kjl", value := .nosovneg }
  , { walsCode := "khd", iso := "khg", value := .nosovneg }
  , { walsCode := "knz", iso := "khg", value := .nosovneg }
  , { walsCode := "kty", iso := "kca", value := .nosovneg }
  , { walsCode := "klw", iso := "klb", value := .wordOptdoubleneg }
  , { walsCode := "kim", iso := "kig", value := .wordNodoubleneg }
  , { walsCode := "knn", iso := "kfk", value := .nosovneg }
  , { walsCode := "kio", iso := "kio", value := .suffixOnlywithanotherneg }
  , { walsCode := "kie", iso := "geb", value := .wordNodoubleneg }
  , { walsCode := "kis", iso := "kss", value := .wordOnlywithanotherneg }
  , { walsCode := "kiw", iso := "kjd", value := .suffixOnlywithanotherneg }
  , { walsCode := "kla", iso := "klu", value := .nosovneg }
  , { walsCode := "koa", iso := "cku", value := .suffixNodoubleneg }
  , { walsCode := "kob", iso := "kpw", value := .suffixNodoubleneg }
  , { walsCode := "kmo", iso := "kpx", value := .suffixNodoubleneg }
  , { walsCode := "kta", iso := "kqi", value := .suffixNodoubleneg }
  , { walsCode := "kok", iso := "trp", value := .suffixNodoubleneg }
  , { walsCode := "kol", iso := "kfb", value := .type1Type2 }
  , { walsCode := "kmb", iso := "", value := .suffixOptdoubleneg }
  , { walsCode := "kor", iso := "kor", value := .nosovneg }
  , { walsCode := "krw", iso := "khe", value := .suffixOnlywithanotherneg }
  , { walsCode := "kry", iso := "kpy", value := .suffixOnlywithanotherneg }
  , { walsCode := "koy", iso := "kff", value := .suffixNodoubleneg }
  , { walsCode := "kse", iso := "ses", value := .nosovneg }
  , { walsCode := "krh", iso := "xra", value := .suffixNodoubleneg }
  , { walsCode := "kya", iso := "gvn", value := .nosovneg }
  , { walsCode := "kmn", iso := "kue", value := .suffixNodoubleneg }
  , { walsCode := "kum", iso := "kfy", value := .nosovneg }
  , { walsCode := "kun", iso := "kvn", value := .suffixNodoubleneg }
  , { walsCode := "knm", iso := "kun", value := .suffixNodoubleneg }
  , { walsCode := "kmp", iso := "kup", value := .nosovneg }
  , { walsCode := "krd", iso := "ckb", value := .nosovneg }
  , { walsCode := "kus", iso := "kgg", value := .suffixNodoubleneg }
  , { walsCode := "thy", iso := "thd", value := .nosovneg }
  , { walsCode := "kuv", iso := "kxv", value := .suffixNodoubleneg }
  , { walsCode := "kwz", iso := "xwa", value := .suffixNodoubleneg }
  , { walsCode := "kwo", iso := "kmo", value := .suffixOptdoubleneg }
  , { walsCode := "kwt", iso := "kwo", value := .wordOnlywithanotherneg }
  , { walsCode := "lad", iso := "lbj", value := .suffixNodoubleneg }
  , { walsCode := "lah", iso := "lhu", value := .nosovneg }
  , { walsCode := "lai", iso := "cnh", value := .wordNodoubleneg }
  , { walsCode := "lkt", iso := "lkt", value := .wordNodoubleneg }
  , { walsCode := "lal", iso := "ywt", value := .nosovneg }
  , { walsCode := "lmn", iso := "lmn", value := .wordNodoubleneg }
  , { walsCode := "lav", iso := "lvk", value := .type1Type2 }
  , { walsCode := "agb", iso := "agb", value := .nosovneg }
  , { walsCode := "ldu", iso := "led", value := .wordNodoubleneg }
  , { walsCode := "lep", iso := "lep", value := .suffixOnlywithanotherneg }
  , { walsCode := "lez", iso := "lez", value := .suffixNodoubleneg }
  , { walsCode := "lis", iso := "lis", value := .nosovneg }
  , { walsCode := "lot", iso := "njh", value := .nosovneg }
  , { walsCode := "mab", iso := "mde", value := .type5Type4 }
  , { walsCode := "mac", iso := "mbc", value := .wordNodoubleneg }
  , { walsCode := "mag", iso := "mgp", value := .nosovneg }
  , { walsCode := "mgi", iso := "mgu", value := .nosovneg }
  , { walsCode := "mne", iso := "nmu", value := .suffixNodoubleneg }
  , { walsCode := "mrs", iso := "zrs", value := .suffixNodoubleneg }
  , { walsCode := "msn", iso := "mbq", value := .wordOnlywithanotherneg }
  , { walsCode := "mkj", iso := "mkz", value := .nosovneg }
  , { walsCode := "mkl", iso := "mgf", value := .nosovneg }
  , { walsCode := "mym", iso := "mal", value := .suffixNodoubleneg }
  , { walsCode := "mnm", iso := "mva", value := .nosovneg }
  , { walsCode := "mnc", iso := "mnc", value := .suffixNodoubleneg }
  , { walsCode := "mdn", iso := "mhq", value := .suffixOnlywithanotherneg }
  , { walsCode := "mkg", iso := "mnk", value := .nosovneg }
  , { walsCode := "mgg", iso := "mjg", value := .nosovneg }
  , { walsCode := "maw", iso := "mlq", value := .nosovneg }
  , { walsCode := "man", iso := "mev", value := .nosovneg }
  , { walsCode := "mns", iso := "mns", value := .nosovneg }
  , { walsCode := "mku", iso := "zmr", value := .wordOnlywithanotherneg }
  , { walsCode := "mhi", iso := "mar", value := .wordNodoubleneg }
  , { walsCode := "mny", iso := "zmc", value := .nosovneg }
  , { walsCode := "mar", iso := "mrc", value := .suffixOnlywithanotherneg }
  , { walsCode := "mrd", iso := "mrz", value := .nosovneg }
  , { walsCode := "mrr", iso := "zmt", value := .nosovneg }
  , { walsCode := "mrh", iso := "mfr", value := .nosovneg }
  , { walsCode := "mru", iso := "mhx", value := .nosovneg }
  , { walsCode := "msl", iso := "mls", value := .suffixNodoubleneg }
  , { walsCode := "mts", iso := "mpq", value := .suffixNodoubleneg }
  , { walsCode := "mdl", iso := "zml", value := .nosovneg }
  , { walsCode := "mka", iso := "mxx", value := .wordOnlywithanotherneg }
  , { walsCode := "mbi", iso := "baw", value := .nosovneg }
  , { walsCode := "mdw", iso := "mdw", value := .wordNodoubleneg }
  , { walsCode := "mee", iso := "mym", value := .suffixNodoubleneg }
  , { walsCode := "mek", iso := "skf", value := .wordNodoubleneg }
  , { walsCode := "mde", iso := "men", value := .nosovneg }
  , { walsCode := "mer", iso := "ulk", value := .nosovneg }
  , { walsCode := "mpt", iso := "mpt", value := .suffixNodoubleneg }
  , { walsCode := "mki", iso := "mik", value := .suffixNodoubleneg }
  , { walsCode := "mik", iso := "mjw", value := .suffixNodoubleneg }
  , { walsCode := "msg", iso := "mrg", value := .suffixNodoubleneg }
  , { walsCode := "mis", iso := "miq", value := .suffixNodoubleneg }
  , { walsCode := "miz", iso := "lus", value := .wordNodoubleneg }
  , { walsCode := "mog", iso := "mhj", value := .nosovneg }
  , { walsCode := "mom", iso := "mso", value := .suffixOnlywithanotherneg }
  , { walsCode := "mkh", iso := "", value := .type1Type2 }
  , { walsCode := "mni", iso := "mnz", value := .nosovneg }
  , { walsCode := "mno", iso := "mnr", value := .nosovneg }
  , { walsCode := "mri", iso := "mok", value := .nosovneg }
  , { walsCode := "mtu", iso := "meu", value := .wordNodoubleneg }
  , { walsCode := "msc", iso := "chb", value := .suffixNodoubleneg }
  , { walsCode := "mun", iso := "unr", value := .nosovneg }
  , { walsCode := "mpa", iso := "mwf", value := .nosovneg }
  , { walsCode := "mur", iso := "muz", value := .nosovneg }
  , { walsCode := "nab", iso := "naf", value := .nosovneg }
  , { walsCode := "nma", iso := "nbi", value := .wordNodoubleneg }
  , { walsCode := "ngt", iso := "nmf", value := .nosovneg }
  , { walsCode := "nag", iso := "nce", value := .wordNodoubleneg }
  , { walsCode := "kho", iso := "naq", value := .wordNodoubleneg }
  , { walsCode := "nmb", iso := "nab", value := .suffixNodoubleneg }
  , { walsCode := "nam", iso := "nnm", value := .nosovneg }
  , { walsCode := "nnk", iso := "nnk", value := .wordNodoubleneg }
  , { walsCode := "nar", iso := "nrb", value := .nosovneg }
  , { walsCode := "nas", iso := "nas", value := .type1Type2 }
  , { walsCode := "nav", iso := "nav", value := .nosovneg }
  , { walsCode := "ntu", iso := "yrk", value := .nosovneg }
  , { walsCode := "naj", iso := "aij", value := .nosovneg }
  , { walsCode := "nep", iso := "npi", value := .suffixNodoubleneg }
  , { walsCode := "nev", iso := "pia", value := .nosovneg }
  , { walsCode := "nwd", iso := "new", value := .nosovneg }
  , { walsCode := "new", iso := "new", value := .nosovneg }
  , { walsCode := "ntj", iso := "ntj", value := .suffixNodoubleneg }
  , { walsCode := "nga", iso := "nio", value := .nosovneg }
  , { walsCode := "nti", iso := "niy", value := .nosovneg }
  , { walsCode := "nbr", iso := "gym", value := .nosovneg }
  , { walsCode := "niv", iso := "niv", value := .type5Type4 }
  , { walsCode := "noc", iso := "njb", value := .suffixNodoubleneg }
  , { walsCode := "nbd", iso := "dgl", value := .suffixNodoubleneg }
  , { walsCode := "nku", iso := "xnz", value := .suffixNodoubleneg }
  , { walsCode := "nue", iso := "nus", value := .nosovneg }
  , { walsCode := "yi", iso := "iii", value := .nosovneg }
  , { walsCode := "nyk", iso := "tpq", value := .nosovneg }
  , { walsCode := "nyi", iso := "nyi", value := .nosovneg }
  , { walsCode := "oir", iso := "xal", value := .nosovneg }
  , { walsCode := "oks", iso := "opm", value := .nosovneg }
  , { walsCode := "omh", iso := "oma", value := .suffixNodoubleneg }
  , { walsCode := "ong", iso := "oon", value := .wordNodoubleneg }
  , { walsCode := "ori", iso := "tag", value := .nosovneg }
  , { walsCode := "oya", iso := "ory", value := .suffixNodoubleneg }
  , { walsCode := "oro", iso := "okv", value := .suffixNodoubleneg }
  , { walsCode := "orh", iso := "hae", value := .nosovneg }
  , { walsCode := "orw", iso := "ssn", value := .suffixOnlywithanotherneg }
  , { walsCode := "osa", iso := "osa", value := .wordNodoubleneg }
  , { walsCode := "oss", iso := "oss", value := .nosovneg }
  , { walsCode := "pno", iso := "pao", value := .nosovneg }
  , { walsCode := "pan", iso := "pan", value := .nosovneg }
  , { walsCode := "psh", iso := "pst", value := .nosovneg }
  , { walsCode := "ptt", iso := "lae", value := .nosovneg }
  , { walsCode := "paw", iso := "pwa", value := .type1Type2 }
  , { walsCode := "prs", iso := "pes", value := .nosovneg }
  , { walsCode := "pba", iso := "pia", value := .nosovneg }
  , { walsCode := "prh", iso := "myp", value := .suffixNodoubleneg }
  , { walsCode := "pis", iso := "psa", value := .wordOnlywithanotherneg }
  , { walsCode := "pme", iso := "peb", value := .suffixNodoubleneg }
  , { walsCode := "pso", iso := "pom", value := .suffixOnlywithanotherneg }
  , { walsCode := "pra", iso := "prn", value := .nosovneg }
  , { walsCode := "pum", iso := "pmi", value := .suffixNodoubleneg }
  , { walsCode := "pun", iso := "wdj", value := .nosovneg }
  , { walsCode := "prk", iso := "prx", value := .suffixNodoubleneg }
  , { walsCode := "pae", iso := "pbb", value := .suffixNodoubleneg }
  , { walsCode := "qhu", iso := "qub", value := .wordOnlywithanotherneg }
  , { walsCode := "qim", iso := "qvi", value := .nosovneg }
  , { walsCode := "ram", iso := "rma", value := .suffixNodoubleneg }
  , { walsCode := "rpa", iso := "bod", value := .nosovneg }
  , { walsCode := "rao", iso := "rao", value := .suffixNodoubleneg }
  , { walsCode := "ras", iso := "ras", value := .nosovneg }
  , { walsCode := "rwa", iso := "rwo", value := .nosovneg }
  , { walsCode := "raw", iso := "raw", value := .nosovneg }
  , { walsCode := "res", iso := "rgr", value := .nosovneg }
  , { walsCode := "ret", iso := "tnc", value := .suffixNodoubleneg }
  , { walsCode := "rik", iso := "rkb", value := .nosovneg }
  , { walsCode := "rum", iso := "klq", value := .suffixNodoubleneg }
  , { walsCode := "run", iso := "rou", value := .suffixOptdoubleneg }
  , { walsCode := "slb", iso := "sbe", value := .nosovneg }
  , { walsCode := "syu", iso := "sll", value := .suffixNodoubleneg }
  , { walsCode := "sdw", iso := "sad", value := .suffixNodoubleneg }
  , { walsCode := "sta", iso := "sce", value := .nosovneg }
  , { walsCode := "stl", iso := "sat", value := .nosovneg }
  , { walsCode := "snm", iso := "xsu", value := .wordNodoubleneg }
  , { walsCode := "src", iso := "srs", value := .nosovneg }
  , { walsCode := "sar", iso := "dju", value := .suffixNodoubleneg }
  , { walsCode := "svs", iso := "svs", value := .nosovneg }
  , { walsCode := "sme", iso := "sif", value := .wordNodoubleneg }
  , { walsCode := "smn", iso := "mus", value := .suffixNodoubleneg }
  , { walsCode := "snt", iso := "set", value := .nosovneg }
  , { walsCode := "ser", iso := "sei", value := .nosovneg }
  , { walsCode := "shb", iso := "sbf", value := .wordNodoubleneg }
  , { walsCode := "shh", iso := "mcd", value := .suffixNodoubleneg }
  , { walsCode := "skw", iso := "swv", value := .nosovneg }
  , { walsCode := "she", iso := "xsr", value := .nosovneg }
  , { walsCode := "sna", iso := "scl", value := .nosovneg }
  , { walsCode := "shk", iso := "shp", value := .suffixNodoubleneg }
  , { walsCode := "shi", iso := "shb", value := .wordNodoubleneg }
  , { walsCode := "sia", iso := "snp", value := .suffixNodoubleneg }
  , { walsCode := "sid", iso := "sid", value := .nosovneg }
  , { walsCode := "sil", iso := "dau", value := .nosovneg }
  , { walsCode := "sng", iso := "snc", value := .nosovneg }
  , { walsCode := "sro", iso := "ssd", value := .wordNodoubleneg }
  , { walsCode := "sla", iso := "den", value := .wordNodoubleneg }
  , { walsCode := "sod", iso := "gru", value := .nosovneg }
  , { walsCode := "som", iso := "som", value := .nosovneg }
  , { walsCode := "snn", iso := "snk", value := .nosovneg }
  , { walsCode := "srb", iso := "", value := .nosovneg }
  , { walsCode := "sue", iso := "sue", value := .nosovneg }
  , { walsCode := "sup", iso := "spp", value := .wordOptdoubleneg }
  , { walsCode := "tba", iso := "sst", value := .suffixNodoubleneg }
  , { walsCode := "tbl", iso := "tnm", value := .type5Type6 }
  , { walsCode := "trr", iso := "tbg", value := .nosovneg }
  , { walsCode := "taj", iso := "tgk", value := .nosovneg }
  , { walsCode := "tkl", iso := "tkm", value := .nosovneg }
  , { walsCode := "tak", iso := "tbc", value := .nosovneg }
  , { walsCode := "tma", iso := "tma", value := .suffixNodoubleneg }
  , { walsCode := "tam", iso := "taj", value := .nosovneg }
  , { walsCode := "tml", iso := "tam", value := .suffixNodoubleneg }
  , { walsCode := "tpt", iso := "tpj", value := .suffixNodoubleneg }
  , { walsCode := "tce", iso := "tar", value := .nosovneg }
  , { walsCode := "twe", iso := "tac", value := .nosovneg }
  , { walsCode := "tao", iso := "tro", value := .suffixNodoubleneg }
  , { walsCode := "tar", iso := "tae", value := .suffixOptdoubleneg }
  , { walsCode := "tau", iso := "tya", value := .nosovneg }
  , { walsCode := "taw", iso := "tbo", value := .nosovneg }
  , { walsCode := "tel", iso := "tel", value := .suffixNodoubleneg }
  , { walsCode := "trb", iso := "tfr", value := .wordNodoubleneg }
  , { walsCode := "thn", iso := "thf", value := .nosovneg }
  , { walsCode := "thu", iso := "tdh", value := .suffixOnlywithanotherneg }
  , { walsCode := "tdr", iso := "bod", value := .nosovneg }
  , { walsCode := "tmo", iso := "bod", value := .wordNodoubleneg }
  , { walsCode := "tib", iso := "bod", value := .nosovneg }
  , { walsCode := "tig", iso := "tir", value := .suffixOnlywithanotherneg }
  , { walsCode := "tgr", iso := "tig", value := .nosovneg }
  , { walsCode := "tja", iso := "dih", value := .wordOptdoubleneg }
  , { walsCode := "trm", iso := "suq", value := .suffixOnlywithanotherneg }
  , { walsCode := "twn", iso := "twf", value := .nosovneg }
  , { walsCode := "tli", iso := "tli", value := .nosovneg }
  , { walsCode := "tlo", iso := "tlb", value := .suffixNodoubleneg }
  , { walsCode := "tod", iso := "sbu", value := .nosovneg }
  , { walsCode := "ton", iso := "tqw", value := .suffixNodoubleneg }
  , { walsCode := "tru", iso := "tpy", value := .wordNodoubleneg }
  , { walsCode := "tsf", iso := "cof", value := .suffixNodoubleneg }
  , { walsCode := "tsz", iso := "ddo", value := .wordNodoubleneg }
  , { walsCode := "tgl", iso := "tsj", value := .type1Type6 }
  , { walsCode := "ttu", iso := "bbl", value := .nosovneg }
  , { walsCode := "tbu", iso := "", value := .suffixNodoubleneg }
  , { walsCode := "tul", iso := "tcy", value := .suffixNodoubleneg }
  , { walsCode := "tnn", iso := "tvu", value := .nosovneg }
  , { walsCode := "tun", iso := "tun", value := .suffixNodoubleneg }
  , { walsCode := "tur", iso := "tur", value := .suffixNodoubleneg }
  , { walsCode := "tte", iso := "tta", value := .suffixOnlywithanotherneg }
  , { walsCode := "tuv", iso := "tyv", value := .suffixNodoubleneg }
  , { walsCode := "tuy", iso := "tue", value := .suffixNodoubleneg }
  , { walsCode := "tye", iso := "woa", value := .wordOnlywithanotherneg }
  , { walsCode := "tsh", iso := "par", value := .suffixOnlywithanotherneg }
  , { walsCode := "uby", iso := "uby", value := .suffixNodoubleneg }
  , { walsCode := "udi", iso := "udi", value := .nosovneg }
  , { walsCode := "udh", iso := "ude", value := .nosovneg }
  , { walsCode := "udm", iso := "udm", value := .wordNodoubleneg }
  , { walsCode := "una", iso := "mtg", value := .nosovneg }
  , { walsCode := "urd", iso := "urd", value := .nosovneg }
  , { walsCode := "urk", iso := "urb", value := .wordNodoubleneg }
  , { walsCode := "usa", iso := "wnu", value := .nosovneg }
  , { walsCode := "usr", iso := "usa", value := .nosovneg }
  , { walsCode := "uyg", iso := "uig", value := .suffixNodoubleneg }
  , { walsCode := "uzb", iso := "", value := .suffixNodoubleneg }
  , { walsCode := "vai", iso := "vai", value := .nosovneg }
  , { walsCode := "wag", iso := "waq", value := .nosovneg }
  , { walsCode := "wah", iso := "", value := .nosovneg }
  , { walsCode := "wak", iso := "wbl", value := .nosovneg }
  , { walsCode := "wbn", iso := "wms", value := .suffixNodoubleneg }
  , { walsCode := "wme", iso := "wme", value := .nosovneg }
  , { walsCode := "wna", iso := "wan", value := .wordNodoubleneg }
  , { walsCode := "wao", iso := "auc", value := .suffixNodoubleneg }
  , { walsCode := "wap", iso := "wao", value := .suffixNodoubleneg }
  , { walsCode := "wlw", iso := "wrb", value := .nosovneg }
  , { walsCode := "was", iso := "was", value := .suffixNodoubleneg }
  , { walsCode := "wsk", iso := "wsk", value := .nosovneg }
  , { walsCode := "way", iso := "oym", value := .suffixOnlywithanotherneg }
  , { walsCode := "wed", iso := "wed", value := .nosovneg }
  , { walsCode := "wic", iso := "wic", value := .nosovneg }
  , { walsCode := "wmu", iso := "wim", value := .nosovneg }
  , { walsCode := "wly", iso := "wal", value := .suffixNodoubleneg }
  , { walsCode := "wom", iso := "wmx", value := .wordNodoubleneg }
  , { walsCode := "ygr", iso := "ygr", value := .nosovneg }
  , { walsCode := "ykt", iso := "sah", value := .suffixNodoubleneg }
  , { walsCode := "yam", iso := "yaa", value := .suffixNodoubleneg }
  , { walsCode := "yqy", iso := "jaq", value := .suffixOnlywithanotherneg }
  , { walsCode := "yaq", iso := "yaq", value := .nosovneg }
  , { walsCode := "yar", iso := "yrb", value := .suffixNodoubleneg }
  , { walsCode := "yei", iso := "jei", value := .nosovneg }
  , { walsCode := "ylm", iso := "jel", value := .nosovneg }
  , { walsCode := "yiw", iso := "ywq", value := .nosovneg }
  , { walsCode := "yid", iso := "yii", value := .nosovneg }
  , { walsCode := "yuc", iso := "yuc", value := .nosovneg }
  , { walsCode := "yko", iso := "yux", value := .nosovneg }
  , { walsCode := "ytu", iso := "ykg", value := .nosovneg }
  , { walsCode := "yuw", iso := "kld", value := .nosovneg }
  , { walsCode := "zay", iso := "zay", value := .suffixNodoubleneg }
  , { walsCode := "zaz", iso := "diq", value := .nosovneg }
  , { walsCode := "zun", iso := "zun", value := .suffixOnlywithanotherneg }
  , { walsCode := "rgc", iso := "jya", value := .nosovneg }
  , { walsCode := "eme", iso := "eme", value := .suffixOnlywithanotherneg }
  ]

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F144S
