import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 16A: Weight Factors in Weight-Sensitive Stress Systems
@cite{wals-2013}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 16A`.

Chapter 16, 500 languages.
-/

namespace Core.WALS.F16A

/-- WALS 16A values. -/
inductive WeightFactorsInWeightSensitiveStressSystems where
  /-- No weight (261 languages). -/
  | noWeight
  /-- Long vowel (65 languages). -/
  | longVowel
  /-- Coda consonant (18 languages). -/
  | codaConsonant
  /-- Long vowel or coda consonant (35 languages). -/
  | longVowelOrCodaConsonant
  /-- Prominence (41 languages). -/
  | prominence
  /-- Lexical stress (38 languages). -/
  | lexicalStress
  /-- Combined (42 languages). -/
  | combined
  deriving DecidableEq, BEq, Repr

/-- Complete WALS 16A dataset (500 languages). -/
def allData : List (Datapoint WeightFactorsInWeightSensitiveStressSystems) :=
  [ { walsCode := "abk", iso := "abk", value := .lexicalStress }
  , { walsCode := "ace", iso := "ace", value := .prominence }
  , { walsCode := "acg", iso := "aca", value := .noWeight }
  , { walsCode := "agu", iso := "agu", value := .longVowel }
  , { walsCode := "akl", iso := "akl", value := .codaConsonant }
  , { walsCode := "ala", iso := "amp", value := .prominence }
  , { walsCode := "alw", iso := "alh", value := .noWeight }
  , { walsCode := "aln", iso := "alp", value := .noWeight }
  , { walsCode := "atq", iso := "ems", value := .combined }
  , { walsCode := "aly", iso := "aly", value := .noWeight }
  , { walsCode := "ame", iso := "aey", value := .codaConsonant }
  , { walsCode := "agt", iso := "awg", value := .noWeight }
  , { walsCode := "apu", iso := "apu", value := .longVowel }
  , { walsCode := "ahs", iso := "mey", value := .combined }
  , { walsCode := "abe", iso := "apc", value := .longVowelOrCodaConsonant }
  , { walsCode := "ael", iso := "ayl", value := .combined }
  , { walsCode := "aeg", iso := "arz", value := .combined }
  , { walsCode := "arg", iso := "afb", value := .longVowel }
  , { walsCode := "arh", iso := "acw", value := .longVowelOrCodaConsonant }
  , { walsCode := "arl", iso := "apc", value := .longVowelOrCodaConsonant }
  , { walsCode := "arv", iso := "ajp", value := .combined }
  , { walsCode := "apa", iso := "ajp", value := .combined }
  , { walsCode := "asy", iso := "apc", value := .longVowelOrCodaConsonant }
  , { walsCode := "atb", iso := "atq", value := .noWeight }
  , { walsCode := "ana", iso := "aro", value := .noWeight }
  , { walsCode := "arp", iso := "ape", value := .noWeight }
  , { walsCode := "arc", iso := "aqc", value := .prominence }
  , { walsCode := "arm", iso := "hye", value := .prominence }
  , { walsCode := "aro", iso := "aia", value := .noWeight }
  , { walsCode := "awe", iso := "are", value := .noWeight }
  , { walsCode := "asm", iso := "cns", value := .lexicalStress }
  , { walsCode := "au", iso := "avt", value := .prominence }
  , { walsCode := "ava", iso := "ava", value := .combined }
  , { walsCode := "awd", iso := "awa", value := .longVowelOrCodaConsonant }
  , { walsCode := "awt", iso := "kmn", value := .noWeight }
  , { walsCode := "aym", iso := "ayr", value := .noWeight }
  , { walsCode := "bdm", iso := "bia", value := .noWeight }
  , { walsCode := "bag", iso := "bmi", value := .noWeight }
  , { walsCode := "bgv", iso := "kva", value := .combined }
  , { walsCode := "blk", iso := "blz", value := .noWeight }
  , { walsCode := "bal", iso := "ban", value := .noWeight }
  , { walsCode := "bbm", iso := "ptu", value := .noWeight }
  , { walsCode := "bna", iso := "jaa", value := .noWeight }
  , { walsCode := "bwa", iso := "bdy", value := .longVowel }
  , { walsCode := "bgg", iso := "bgz", value := .longVowel }
  , { walsCode := "bnl", iso := "bjb", value := .noWeight }
  , { walsCode := "bnt", iso := "bnq", value := .noWeight }
  , { walsCode := "bae", iso := "bae", value := .noWeight }
  , { walsCode := "bsk", iso := "bak", value := .noWeight }
  , { walsCode := "bqi", iso := "eus", value := .lexicalStress }
  , { walsCode := "bqb", iso := "eus", value := .noWeight }
  , { walsCode := "bqg", iso := "eus", value := .lexicalStress }
  , { walsCode := "bqh", iso := "eus", value := .codaConsonant }
  , { walsCode := "bql", iso := "eus", value := .noWeight }
  , { walsCode := "bqn", iso := "eus", value := .noWeight }
  , { walsCode := "bqo", iso := "eus", value := .noWeight }
  , { walsCode := "bqr", iso := "eus", value := .noWeight }
  , { walsCode := "bqs", iso := "eus", value := .noWeight }
  , { walsCode := "bso", iso := "eus", value := .lexicalStress }
  , { walsCode := "bqz", iso := "eus", value := .lexicalStress }
  , { walsCode := "bkr", iso := "btx", value := .combined }
  , { walsCode := "bto", iso := "bbc", value := .noWeight }
  , { walsCode := "baw", iso := "bgr", value := .noWeight }
  , { walsCode := "bej", iso := "bej", value := .noWeight }
  , { walsCode := "ben", iso := "ben", value := .noWeight }
  , { walsCode := "bma", iso := "tzm", value := .noWeight }
  , { walsCode := "bho", iso := "bho", value := .combined }
  , { walsCode := "bik", iso := "bhw", value := .noWeight }
  , { walsCode := "bkl", iso := "bcl", value := .lexicalStress }
  , { walsCode := "bim", iso := "bhp", value := .noWeight }
  , { walsCode := "bbw", iso := "gup", value := .noWeight }
  , { walsCode := "bre", iso := "bre", value := .noWeight }
  , { walsCode := "bug", iso := "bug", value := .noWeight }
  , { walsCode := "bui", iso := "bzq", value := .longVowel }
  , { walsCode := "bua", iso := "bvr", value := .noWeight }
  , { walsCode := "buu", iso := "mhs", value := .noWeight }
  , { walsCode := "bur", iso := "bsk", value := .lexicalStress }
  , { walsCode := "cah", iso := "chl", value := .combined }
  , { walsCode := "cpa", iso := "cjo", value := .noWeight }
  , { walsCode := "cnl", iso := "ram", value := .noWeight }
  , { walsCode := "cap", iso := "kaq", value := .combined }
  , { walsCode := "car", iso := "car", value := .longVowelOrCodaConsonant }
  , { walsCode := "ctl", iso := "cat", value := .lexicalStress }
  , { walsCode := "cav", iso := "cav", value := .noWeight }
  , { walsCode := "cyg", iso := "cay", value := .combined }
  , { walsCode := "cyv", iso := "cyb", value := .noWeight }
  , { walsCode := "ceb", iso := "ceb", value := .longVowelOrCodaConsonant }
  , { walsCode := "cha", iso := "cha", value := .codaConsonant }
  , { walsCode := "cya", iso := "ctp", value := .noWeight }
  , { walsCode := "cpn", iso := "cdm", value := .noWeight }
  , { walsCode := "cle", iso := "cle", value := .noWeight }
  , { walsCode := "cct", iso := "cho", value := .longVowelOrCodaConsonant }
  , { walsCode := "chk", iso := "ckt", value := .noWeight }
  , { walsCode := "chv", iso := "chv", value := .prominence }
  , { walsCode := "cmn", iso := "com", value := .noWeight }
  , { walsCode := "coo", iso := "csz", value := .noWeight }
  , { walsCode := "crn", iso := "cor", value := .noWeight }
  , { walsCode := "cre", iso := "crk", value := .noWeight }
  , { walsCode := "crk", iso := "mus", value := .combined }
  , { walsCode := "cub", iso := "cub", value := .prominence }
  , { walsCode := "cup", iso := "cup", value := .noWeight }
  , { walsCode := "cze", iso := "ces", value := .noWeight }
  , { walsCode := "daa", iso := "kzf", value := .noWeight }
  , { walsCode := "dak", iso := "dak", value := .noWeight }
  , { walsCode := "dni", iso := "dni", value := .noWeight }
  , { walsCode := "dsh", iso := "dan", value := .longVowelOrCodaConsonant }
  , { walsCode := "dri", iso := "prs", value := .noWeight }
  , { walsCode := "des", iso := "des", value := .lexicalStress }
  , { walsCode := "dhw", iso := "tbh", value := .longVowel }
  , { walsCode := "dhu", iso := "dhu", value := .longVowel }
  , { walsCode := "die", iso := "dih", value := .combined }
  , { walsCode := "dio", iso := "dyo", value := .noWeight }
  , { walsCode := "diy", iso := "dif", value := .noWeight }
  , { walsCode := "djr", iso := "ddj", value := .longVowel }
  , { walsCode := "dji", iso := "jig", value := .noWeight }
  , { walsCode := "dob", iso := "kvo", value := .lexicalStress }
  , { walsCode := "dou", iso := "tds", value := .noWeight }
  , { walsCode := "dre", iso := "dhv", value := .noWeight }
  , { walsCode := "dut", iso := "nld", value := .codaConsonant }
  , { walsCode := "dyi", iso := "dbl", value := .noWeight }
  , { walsCode := "eka", iso := "ekg", value := .lexicalStress }
  , { walsCode := "emc", iso := "cmi", value := .combined }
  , { walsCode := "eno", iso := "eno", value := .noWeight }
  , { walsCode := "eng", iso := "eng", value := .longVowelOrCodaConsonant }
  , { walsCode := "epe", iso := "sja", value := .longVowel }
  , { walsCode := "ese", iso := "ese", value := .noWeight }
  , { walsCode := "est", iso := "ekk", value := .longVowel }
  , { walsCode := "eve", iso := "evn", value := .longVowel }
  , { walsCode := "far", iso := "fao", value := .noWeight }
  , { walsCode := "fij", iso := "fij", value := .longVowel }
  , { walsCode := "fin", iso := "fin", value := .noWeight }
  , { walsCode := "frd", iso := "frd", value := .noWeight }
  , { walsCode := "for", iso := "for", value := .prominence }
  , { walsCode := "fre", iso := "fra", value := .prominence }
  , { walsCode := "glp", iso := "dhg", value := .noWeight }
  , { walsCode := "gae", iso := "gla", value := .noWeight }
  , { walsCode := "gll", iso := "gbi", value := .noWeight }
  , { walsCode := "grr", iso := "wrk", value := .noWeight }
  , { walsCode := "gay", iso := "gay", value := .prominence }
  , { walsCode := "geo", iso := "kat", value := .noWeight }
  , { walsCode := "ger", iso := "deu", value := .codaConsonant }
  , { walsCode := "gid", iso := "gih", value := .longVowel }
  , { walsCode := "god", iso := "gdo", value := .prominence }
  , { walsCode := "goo", iso := "gni", value := .longVowelOrCodaConsonant }
  , { walsCode := "gor", iso := "gow", value := .longVowelOrCodaConsonant }
  , { walsCode := "grb", iso := "grj", value := .lexicalStress }
  , { walsCode := "grk", iso := "ell", value := .lexicalStress }
  , { walsCode := "grw", iso := "kal", value := .longVowelOrCodaConsonant }
  , { walsCode := "gua", iso := "gug", value := .noWeight }
  , { walsCode := "gug", iso := "ktd", value := .noWeight }
  , { walsCode := "guj", iso := "guj", value := .prominence }
  , { walsCode := "guu", iso := "kky", value := .noWeight }
  , { walsCode := "hno", iso := "hdn", value := .prominence }
  , { walsCode := "hln", iso := "hal", value := .noWeight }
  , { walsCode := "hnn", iso := "hnn", value := .lexicalStress }
  , { walsCode := "haw", iso := "haw", value := .longVowel }
  , { walsCode := "heb", iso := "heb", value := .noWeight }
  , { walsCode := "hin", iso := "hin", value := .longVowelOrCodaConsonant }
  , { walsCode := "hix", iso := "hix", value := .longVowelOrCodaConsonant }
  , { walsCode := "hop", iso := "hop", value := .longVowelOrCodaConsonant }
  , { walsCode := "htc", iso := "hus", value := .longVowel }
  , { walsCode := "hmu", iso := "hux", value := .noWeight }
  , { walsCode := "hun", iso := "hun", value := .longVowel }
  , { walsCode := "hzb", iso := "huz", value := .longVowel }
  , { walsCode := "iaa", iso := "iai", value := .noWeight }
  , { walsCode := "ice", iso := "isl", value := .noWeight }
  , { walsCode := "ind", iso := "ind", value := .noWeight }
  , { walsCode := "iga", iso := "inb", value := .combined }
  , { walsCode := "ing", iso := "inh", value := .noWeight }
  , { walsCode := "irq", iso := "irk", value := .combined }
  , { walsCode := "irr", iso := "irh", value := .noWeight }
  , { walsCode := "iri", iso := "gle", value := .longVowel }
  , { walsCode := "irm", iso := "gle", value := .longVowel }
  , { walsCode := "ita", iso := "ita", value := .lexicalStress }
  , { walsCode := "jak", iso := "jac", value := .noWeight }
  , { walsCode := "jaq", iso := "jqr", value := .noWeight }
  , { walsCode := "jav", iso := "jav", value := .prominence }
  , { walsCode := "jum", iso := "jua", value := .noWeight }
  , { walsCode := "kli", iso := "lew", value := .noWeight }
  , { walsCode := "kaw", iso := "kgk", value := .noWeight }
  , { walsCode := "kal", iso := "gwc", value := .noWeight }
  , { walsCode := "klp", iso := "kyl", value := .noWeight }
  , { walsCode := "kgu", iso := "ktg", value := .noWeight }
  , { walsCode := "kam", iso := "xbr", value := .noWeight }
  , { walsCode := "kra", iso := "leu", value := .combined }
  , { walsCode := "krl", iso := "krl", value := .longVowelOrCodaConsonant }
  , { walsCode := "krk", iso := "kyh", value := .longVowel }
  , { walsCode := "ksh", iso := "kju", value := .longVowelOrCodaConsonant }
  , { walsCode := "kaj", iso := "bpp", value := .prominence }
  , { walsCode := "kws", iso := "xaw", value := .longVowel }
  , { walsCode := "kay", iso := "gyd", value := .combined }
  , { walsCode := "kei", iso := "kei", value := .noWeight }
  , { walsCode := "kap", iso := "kcl", value := .noWeight }
  , { walsCode := "ker", iso := "ker", value := .combined }
  , { walsCode := "ktn", iso := "xte", value := .lexicalStress }
  , { walsCode := "kew", iso := "kew", value := .lexicalStress }
  , { walsCode := "kha", iso := "khk", value := .longVowel }
  , { walsCode := "khs", iso := "kha", value := .noWeight }
  , { walsCode := "khm", iso := "khm", value := .prominence }
  , { walsCode := "kmu", iso := "kjg", value := .noWeight }
  , { walsCode := "klv", iso := "kij", value := .longVowelOrCodaConsonant }
  , { walsCode := "ksr", iso := "kje", value := .noWeight }
  , { walsCode := "kit", iso := "kii", value := .noWeight }
  , { walsCode := "klm", iso := "kla", value := .longVowelOrCodaConsonant }
  , { walsCode := "koa", iso := "cku", value := .longVowel }
  , { walsCode := "kob", iso := "kpw", value := .noWeight }
  , { walsCode := "koo", iso := "kvv", value := .lexicalStress }
  , { walsCode := "kop", iso := "koi", value := .longVowel }
  , { walsCode := "kon", iso := "kng", value := .noWeight }
  , { walsCode := "kjo", iso := "kjc", value := .noWeight }
  , { walsCode := "kfe", iso := "kfz", value := .noWeight }
  , { walsCode := "koy", iso := "kff", value := .longVowelOrCodaConsonant }
  , { walsCode := "kro", iso := "kgo", value := .prominence }
  , { walsCode := "kya", iso := "gvn", value := .noWeight }
  , { walsCode := "kuz", iso := "mbt", value := .prominence }
  , { walsCode := "knm", iso := "kun", value := .lexicalStress }
  , { walsCode := "kjn", iso := "kjn", value := .noWeight }
  , { walsCode := "kut", iso := "kut", value := .lexicalStress }
  , { walsCode := "kuu", iso := "kuy", value := .longVowel }
  , { walsCode := "kwa", iso := "kwd", value := .noWeight }
  , { walsCode := "kwk", iso := "kwk", value := .combined }
  , { walsCode := "lmh", iso := "slp", value := .prominence }
  , { walsCode := "lmp", iso := "ljp", value := .noWeight }
  , { walsCode := "lla", iso := "lby", value := .noWeight }
  , { walsCode := "lan", iso := "laj", value := .noWeight }
  , { walsCode := "lar", iso := "lrg", value := .longVowel }
  , { walsCode := "lrk", iso := "alo", value := .noWeight }
  , { walsCode := "lat", iso := "lav", value := .noWeight }
  , { walsCode := "lje", iso := "law", value := .noWeight }
  , { walsCode := "lav", iso := "lvk", value := .noWeight }
  , { walsCode := "len", iso := "tnl", value := .noWeight }
  , { walsCode := "let", iso := "lti", value := .longVowel }
  , { walsCode := "lez", iso := "lez", value := .codaConsonant }
  , { walsCode := "lit", iso := "lit", value := .lexicalStress }
  , { walsCode := "liv", iso := "liv", value := .noWeight }
  , { walsCode := "ara", iso := "arw", value := .noWeight }
  , { walsCode := "lui", iso := "lui", value := .longVowel }
  , { walsCode := "luv", iso := "lue", value := .noWeight }
  , { walsCode := "myn", iso := "mhy", value := .noWeight }
  , { walsCode := "mcd", iso := "mkd", value := .noWeight }
  , { walsCode := "mac", iso := "mbc", value := .longVowelOrCodaConsonant }
  , { walsCode := "mdm", iso := "dmd", value := .prominence }
  , { walsCode := "mae", iso := "mmw", value := .noWeight }
  , { walsCode := "mne", iso := "nmu", value := .codaConsonant }
  , { walsCode := "mrs", iso := "zrs", value := .longVowel }
  , { walsCode := "mai", iso := "mai", value := .longVowel }
  , { walsCode := "mak", iso := "myh", value := .longVowel }
  , { walsCode := "mks", iso := "mak", value := .noWeight }
  , { walsCode := "mlc", iso := "mcm", value := .codaConsonant }
  , { walsCode := "mal", iso := "plt", value := .noWeight }
  , { walsCode := "mlk", iso := "mpb", value := .prominence }
  , { walsCode := "mly", iso := "zsm", value := .combined }
  , { walsCode := "mym", iso := "mal", value := .longVowel }
  , { walsCode := "mlt", iso := "mlt", value := .combined }
  , { walsCode := "mam", iso := "mam", value := .combined }
  , { walsCode := "mms", iso := "mqj", value := .noWeight }
  , { walsCode := "mnm", iso := "mva", value := .codaConsonant }
  , { walsCode := "mnd", iso := "cmn", value := .lexicalStress }
  , { walsCode := "myi", iso := "mpc", value := .noWeight }
  , { walsCode := "mng", iso := "mqy", value := .prominence }
  , { walsCode := "mns", iso := "mns", value := .noWeight }
  , { walsCode := "mnj", iso := "mpj", value := .noWeight }
  , { walsCode := "mnx", iso := "glv", value := .noWeight }
  , { walsCode := "mao", iso := "mri", value := .longVowel }
  , { walsCode := "map", iso := "arn", value := .noWeight }
  , { walsCode := "mku", iso := "zmr", value := .noWeight }
  , { walsCode := "mny", iso := "zmc", value := .noWeight }
  , { walsCode := "mah", iso := "mrj", value := .longVowel }
  , { walsCode := "mme", iso := "mhr", value := .longVowel }
  , { walsCode := "mar", iso := "mrc", value := .noWeight }
  , { walsCode := "mrd", iso := "mrz", value := .noWeight }
  , { walsCode := "mrt", iso := "vma", value := .longVowel }
  , { walsCode := "mau", iso := "mph", value := .noWeight }
  , { walsCode := "may", iso := "ayz", value := .noWeight }
  , { walsCode := "myy", iso := "xyj", value := .noWeight }
  , { walsCode := "mbb", iso := "vmb", value := .noWeight }
  , { walsCode := "meb", iso := "bew", value := .prominence }
  , { walsCode := "men", iso := "mez", value := .longVowel }
  , { walsCode := "mnt", iso := "mwv", value := .noWeight }
  , { walsCode := "mta", iso := "sdo", value := .noWeight }
  , { walsCode := "mea", iso := "mej", value := .noWeight }
  , { walsCode := "min", iso := "min", value := .noWeight }
  , { walsCode := "mis", iso := "miq", value := .noWeight }
  , { walsCode := "mcs", iso := "csm", value := .longVowelOrCodaConsonant }
  , { walsCode := "mwn", iso := "nsq", value := .longVowelOrCodaConsonant }
  , { walsCode := "mss", iso := "skd", value := .longVowelOrCodaConsonant }
  , { walsCode := "moh", iso := "moh", value := .noWeight }
  , { walsCode := "mgd", iso := "mog", value := .longVowelOrCodaConsonant }
  , { walsCode := "mmo", iso := "mdf", value := .prominence }
  , { walsCode := "mna", iso := "mnb", value := .noWeight }
  , { walsCode := "mun", iso := "unr", value := .codaConsonant }
  , { walsCode := "mse", iso := "umu", value := .combined }
  , { walsCode := "mrk", iso := "mtf", value := .longVowel }
  , { walsCode := "mrl", iso := "mur", value := .longVowel }
  , { walsCode := "mrw", iso := "zmu", value := .longVowel }
  , { walsCode := "nht", iso := "nhg", value := .noWeight }
  , { walsCode := "nbb", iso := "nmb", value := .noWeight }
  , { walsCode := "nmb", iso := "nab", value := .noWeight }
  , { walsCode := "npu", iso := "npy", value := .noWeight }
  , { walsCode := "ndy", iso := "djk", value := .longVowelOrCodaConsonant }
  , { walsCode := "ntu", iso := "yrk", value := .codaConsonant }
  , { walsCode := "nne", iso := "nen", value := .noWeight }
  , { walsCode := "naj", iso := "aij", value := .noWeight }
  , { walsCode := "nsy", iso := "aii", value := .noWeight }
  , { walsCode := "nep", iso := "npi", value := .longVowel }
  , { walsCode := "nez", iso := "nez", value := .lexicalStress }
  , { walsCode := "ngd", iso := "nxg", value := .prominence }
  , { walsCode := "ngl", iso := "nig", value := .noWeight }
  , { walsCode := "nkb", iso := "ngk", value := .noWeight }
  , { walsCode := "ngr", iso := "nay", value := .noWeight }
  , { walsCode := "ngi", iso := "wyb", value := .longVowel }
  , { walsCode := "nia", iso := "nia", value := .noWeight }
  , { walsCode := "nin", iso := "niz", value := .noWeight }
  , { walsCode := "niv", iso := "niv", value := .noWeight }
  , { walsCode := "nor", iso := "nor", value := .longVowelOrCodaConsonant }
  , { walsCode := "nua", iso := "nxl", value := .noWeight }
  , { walsCode := "nbd", iso := "dgl", value := .longVowelOrCodaConsonant }
  , { walsCode := "nug", iso := "nuy", value := .noWeight }
  , { walsCode := "nbo", iso := "now", value := .noWeight }
  , { walsCode := "nya", iso := "nyt", value := .combined }
  , { walsCode := "nju", iso := "nys", value := .noWeight }
  , { walsCode := "obk", iso := "afz", value := .prominence }
  , { walsCode := "occ", iso := "oci", value := .combined }
  , { walsCode := "olm", iso := "nij", value := .noWeight }
  , { walsCode := "ond", iso := "one", value := .noWeight }
  , { walsCode := "ono", iso := "ons", value := .noWeight }
  , { walsCode := "orc", iso := "oac", value := .noWeight }
  , { walsCode := "oss", iso := "oss", value := .longVowel }
  , { walsCode := "oto", iso := "iow", value := .longVowel }
  , { walsCode := "pkn", iso := "drl", value := .noWeight }
  , { walsCode := "pms", iso := "pma", value := .noWeight }
  , { walsCode := "pad", iso := "pdo", value := .noWeight }
  , { walsCode := "pag", iso := "pgu", value := .noWeight }
  , { walsCode := "put", iso := "ute", value := .noWeight }
  , { walsCode := "pai", iso := "pwn", value := .noWeight }
  , { walsCode := "pna", iso := "pmf", value := .noWeight }
  , { walsCode := "psh", iso := "pst", value := .noWeight }
  , { walsCode := "psm", iso := "pqm", value := .combined }
  , { walsCode := "plh", iso := "plh", value := .noWeight }
  , { walsCode := "pau", iso := "pad", value := .noWeight }
  , { walsCode := "prs", iso := "pes", value := .noWeight }
  , { walsCode := "pin", iso := "piu", value := .noWeight }
  , { walsCode := "prh", iso := "myp", value := .combined }
  , { walsCode := "pir", iso := "pib", value := .noWeight }
  , { walsCode := "pit", iso := "pjt", value := .noWeight }
  , { walsCode := "ppi", iso := "pit", value := .noWeight }
  , { walsCode := "pkm", iso := "poh", value := .noWeight }
  , { walsCode := "plb", iso := "pox", value := .longVowel }
  , { walsCode := "pol", iso := "pol", value := .noWeight }
  , { walsCode := "pme", iso := "peb", value := .noWeight }
  , { walsCode := "por", iso := "por", value := .lexicalStress }
  , { walsCode := "plp", iso := "nij", value := .noWeight }
  , { walsCode := "pul", iso := "puw", value := .prominence }
  , { walsCode := "pur", iso := "tsz", value := .lexicalStress }
  , { walsCode := "que", iso := "yum", value := .noWeight }
  , { walsCode := "qay", iso := "quy", value := .noWeight }
  , { walsCode := "qim", iso := "qvi", value := .noWeight }
  , { walsCode := "qch", iso := "quc", value := .noWeight }
  , { walsCode := "ram", iso := "rma", value := .longVowelOrCodaConsonant }
  , { walsCode := "rap", iso := "rap", value := .noWeight }
  , { walsCode := "rit", iso := "rit", value := .noWeight }
  , { walsCode := "rnr", iso := "rml", value := .noWeight }
  , { walsCode := "rom", iso := "ron", value := .lexicalStress }
  , { walsCode := "rsm", iso := "roh", value := .combined }
  , { walsCode := "ror", iso := "rro", value := .longVowel }
  , { walsCode := "rti", iso := "twu", value := .noWeight }
  , { walsCode := "rot", iso := "rtm", value := .longVowel }
  , { walsCode := "rus", iso := "rus", value := .lexicalStress }
  , { walsCode := "sno", iso := "sme", value := .noWeight }
  , { walsCode := "sao", iso := "ssy", value := .lexicalStress }
  , { walsCode := "sah", iso := "saj", value := .noWeight }
  , { walsCode := "sak", iso := "sku", value := .prominence }
  , { walsCode := "sps", iso := "slh", value := .lexicalStress }
  , { walsCode := "sbg", iso := "sse", value := .noWeight }
  , { walsCode := "sgr", iso := "sxn", value := .noWeight }
  , { walsCode := "snm", iso := "xsu", value := .noWeight }
  , { walsCode := "srd", iso := "sro", value := .noWeight }
  , { walsCode := "swi", iso := "szw", value := .prominence }
  , { walsCode := "sed", iso := "sed", value := .noWeight }
  , { walsCode := "sru", iso := "slu", value := .codaConsonant }
  , { walsCode := "sly", iso := "sly", value := .noWeight }
  , { walsCode := "slp", iso := "spl", value := .noWeight }
  , { walsCode := "skp", iso := "sel", value := .longVowel }
  , { walsCode := "sml", iso := "sza", value := .noWeight }
  , { walsCode := "snc", iso := "see", value := .prominence }
  , { walsCode := "snt", iso := "set", value := .codaConsonant }
  , { walsCode := "scr", iso := "hbs", value := .prominence }
  , { walsCode := "ser", iso := "sei", value := .longVowel }
  , { walsCode := "shk", iso := "shp", value := .codaConsonant }
  , { walsCode := "shi", iso := "shb", value := .prominence }
  , { walsCode := "skr", iso := "tty", value := .prominence }
  , { walsCode := "skl", iso := "skh", value := .noWeight }
  , { walsCode := "sdh", iso := "snd", value := .noWeight }
  , { walsCode := "sio", iso := "xsi", value := .longVowel }
  , { walsCode := "sro", iso := "ssd", value := .noWeight }
  , { walsCode := "sla", iso := "den", value := .lexicalStress }
  , { walsCode := "svk", iso := "slk", value := .noWeight }
  , { walsCode := "slo", iso := "slv", value := .prominence }
  , { walsCode := "svc", iso := "csb", value := .combined }
  , { walsCode := "srb", iso := "", value := .noWeight }
  , { walsCode := "sea", iso := "tvk", value := .longVowel }
  , { walsCode := "spa", iso := "spa", value := .combined }
  , { walsCode := "spo", iso := "spo", value := .lexicalStress }
  , { walsCode := "squ", iso := "squ", value := .prominence }
  , { walsCode := "sto", iso := "sto", value := .codaConsonant }
  , { walsCode := "sun", iso := "sun", value := .prominence }
  , { walsCode := "sup", iso := "spp", value := .noWeight }
  , { walsCode := "swa", iso := "swh", value := .noWeight }
  , { walsCode := "swe", iso := "swe", value := .longVowelOrCodaConsonant }
  , { walsCode := "tab", iso := "mky", value := .noWeight }
  , { walsCode := "tbr", iso := "tby", value := .noWeight }
  , { walsCode := "tbl", iso := "tnm", value := .prominence }
  , { walsCode := "tac", iso := "tna", value := .noWeight }
  , { walsCode := "tag", iso := "tgl", value := .lexicalStress }
  , { walsCode := "tah", iso := "tah", value := .longVowel }
  , { walsCode := "taj", iso := "tgk", value := .noWeight }
  , { walsCode := "tld", iso := "tld", value := .noWeight }
  , { walsCode := "tns", iso := "nwi", value := .longVowelOrCodaConsonant }
  , { walsCode := "tgw", iso := "txn", value := .codaConsonant }
  , { walsCode := "tas", iso := "shi", value := .noWeight }
  , { walsCode := "taw", iso := "tbo", value := .noWeight }
  , { walsCode := "teh", iso := "teh", value := .noWeight }
  , { walsCode := "tps", iso := "stp", value := .longVowelOrCodaConsonant }
  , { walsCode := "thp", iso := "typ", value := .noWeight }
  , { walsCode := "tib", iso := "bod", value := .longVowel }
  , { walsCode := "tgk", iso := "tgc", value := .noWeight }
  , { walsCode := "tse", iso := "aoz", value := .noWeight }
  , { walsCode := "tmc", iso := "tjm", value := .noWeight }
  , { walsCode := "try", iso := "tiy", value := .noWeight }
  , { walsCode := "tiw", iso := "tiw", value := .noWeight }
  , { walsCode := "tlo", iso := "tlb", value := .longVowel }
  , { walsCode := "tol", iso := "jic", value := .codaConsonant }
  , { walsCode := "tla", iso := "ksd", value := .noWeight }
  , { walsCode := "tno", iso := "tdn", value := .combined }
  , { walsCode := "tng", iso := "ton", value := .longVowel }
  , { walsCode := "tnt", iso := "tnt", value := .combined }
  , { walsCode := "trd", iso := "sda", value := .noWeight }
  , { walsCode := "tor", iso := "rth", value := .noWeight }
  , { walsCode := "tru", iso := "tpy", value := .noWeight }
  , { walsCode := "tsa", iso := "tkr", value := .prominence }
  , { walsCode := "tsi", iso := "tsi", value := .noWeight }
  , { walsCode := "tua", iso := "pmt", value := .noWeight }
  , { walsCode := "tuk", iso := "", value := .noWeight }
  , { walsCode := "tun", iso := "tun", value := .noWeight }
  , { walsCode := "tur", iso := "tur", value := .lexicalStress }
  , { walsCode := "tzo", iso := "tzo", value := .noWeight }
  , { walsCode := "tbb", iso := "tub", value := .longVowel }
  , { walsCode := "tsh", iso := "par", value := .longVowel }
  , { walsCode := "uli", iso := "uli", value := .noWeight }
  , { walsCode := "uma", iso := "ppk", value := .noWeight }
  , { walsCode := "unm", iso := "unm", value := .combined }
  , { walsCode := "ung", iso := "ung", value := .longVowel }
  , { walsCode := "uhi", iso := "urf", value := .noWeight }
  , { walsCode := "urk", iso := "urb", value := .noWeight }
  , { walsCode := "usa", iso := "wnu", value := .lexicalStress }
  , { walsCode := "uzn", iso := "uzn", value := .noWeight }
  , { walsCode := "vot", iso := "vot", value := .noWeight }
  , { walsCode := "wah", iso := "", value := .noWeight }
  , { walsCode := "wlm", iso := "wmt", value := .noWeight }
  , { walsCode := "wam", iso := "wmb", value := .longVowel }
  , { walsCode := "wbn", iso := "wms", value := .noWeight }
  , { walsCode := "wan", iso := "xwk", value := .noWeight }
  , { walsCode := "wao", iso := "auc", value := .noWeight }
  , { walsCode := "wra", iso := "wba", value := .noWeight }
  , { walsCode := "wrd", iso := "wrr", value := .noWeight }
  , { walsCode := "war", iso := "pav", value := .noWeight }
  , { walsCode := "wrl", iso := "wbp", value := .noWeight }
  , { walsCode := "wrg", iso := "wgy", value := .combined }
  , { walsCode := "wel", iso := "cym", value := .noWeight }
  , { walsCode := "wer", iso := "wer", value := .noWeight }
  , { walsCode := "wet", iso := "lex", value := .noWeight }
  , { walsCode := "wic", iso := "wic", value := .prominence }
  , { walsCode := "wch", iso := "mzh", value := .noWeight }
  , { walsCode := "wnb", iso := "win", value := .noWeight }
  , { walsCode := "wiy", iso := "wiy", value := .lexicalStress }
  , { walsCode := "woi", iso := "woi", value := .lexicalStress }
  , { walsCode := "wlo", iso := "wlo", value := .longVowel }
  , { walsCode := "ymd", iso := "jmd", value := .noWeight }
  , { walsCode := "yan", iso := "ynn", value := .longVowelOrCodaConsonant }
  , { walsCode := "yny", iso := "jao", value := .noWeight }
  , { walsCode := "yap", iso := "yap", value := .combined }
  , { walsCode := "yaq", iso := "yaq", value := .combined }
  , { walsCode := "ywl", iso := "yok", value := .noWeight }
  , { walsCode := "yzv", iso := "kpv", value := .prominence }
  , { walsCode := "yel", iso := "yle", value := .noWeight }
  , { walsCode := "yid", iso := "yii", value := .longVowel }
  , { walsCode := "yil", iso := "yll", value := .prominence }
  , { walsCode := "yim", iso := "yee", value := .noWeight }
  , { walsCode := "yin", iso := "yij", value := .longVowel }
  , { walsCode := "yir", iso := "yyr", value := .noWeight }
  , { walsCode := "yuc", iso := "yuc", value := .lexicalStress }
  , { walsCode := "yko", iso := "yux", value := .longVowelOrCodaConsonant }
  , { walsCode := "ypk", iso := "esu", value := .combined }
  , { walsCode := "ych", iso := "esu", value := .combined }
  , { walsCode := "yun", iso := "esu", value := .combined }
  , { walsCode := "ysl", iso := "ess", value := .longVowel }
  , { walsCode := "yuw", iso := "kld", value := .longVowel }
  , { walsCode := "zqc", iso := "zoc", value := .noWeight }
  , { walsCode := "zul", iso := "zul", value := .noWeight }
  , { walsCode := "zun", iso := "zun", value := .noWeight }
  ]

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F16A
