import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 18A: Absence of Common Consonants
@cite{wals-2013}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 18A`.

Chapter 18, 567 languages.
-/

namespace Core.WALS.F18A

/-- WALS 18A values. -/
inductive AbsenceOfCommonConsonants where
  /-- All present (503 languages). -/
  | allPresent
  /-- No bilabials (4 languages). -/
  | noBilabials
  /-- No fricatives (48 languages). -/
  | noFricatives
  /-- No nasals (10 languages). -/
  | noNasals
  /-- No bilabials or nasals (1 languages). -/
  | noBilabialsOrNasals
  /-- No fricatives or nasals (1 languages). -/
  | noFricativesOrNasals
  deriving DecidableEq, BEq, Repr

private def allData_0 : List (Datapoint AbsenceOfCommonConsonants) :=
  [ { walsCode := "xoo", iso := "nmn", value := .allPresent }
  , { walsCode := "ani", iso := "hnh", value := .allPresent }
  , { walsCode := "abi", iso := "axb", value := .allPresent }
  , { walsCode := "abk", iso := "abk", value := .allPresent }
  , { walsCode := "acm", iso := "acv", value := .allPresent }
  , { walsCode := "ach", iso := "guq", value := .allPresent }
  , { walsCode := "aco", iso := "kjq", value := .allPresent }
  , { walsCode := "adz", iso := "adz", value := .allPresent }
  , { walsCode := "agh", iso := "agq", value := .allPresent }
  , { walsCode := "aht", iso := "aht", value := .allPresent }
  , { walsCode := "aik", iso := "tba", value := .allPresent }
  , { walsCode := "ain", iso := "ain", value := .allPresent }
  , { walsCode := "aiz", iso := "ahp", value := .allPresent }
  , { walsCode := "akn", iso := "aka", value := .allPresent }
  , { walsCode := "akw", iso := "ake", value := .allPresent }
  , { walsCode := "abm", iso := "akz", value := .allPresent }
  , { walsCode := "ala", iso := "amp", value := .allPresent }
  , { walsCode := "alw", iso := "alh", value := .noFricatives }
  , { walsCode := "alb", iso := "sqi", value := .allPresent }
  , { walsCode := "aea", iso := "ale", value := .allPresent }
  , { walsCode := "ald", iso := "ald", value := .allPresent }
  , { walsCode := "amc", iso := "amc", value := .allPresent }
  , { walsCode := "ame", iso := "aey", value := .allPresent }
  , { walsCode := "amh", iso := "amh", value := .allPresent }
  , { walsCode := "amo", iso := "amo", value := .allPresent }
  , { walsCode := "amu", iso := "ame", value := .allPresent }
  , { walsCode := "amz", iso := "amu", value := .allPresent }
  , { walsCode := "adk", iso := "ano", value := .noNasals }
  , { walsCode := "ant", iso := "agm", value := .noFricatives }
  , { walsCode := "anc", iso := "anc", value := .allPresent }
  , { walsCode := "ao", iso := "njo", value := .allPresent }
  , { walsCode := "api", iso := "apn", value := .allPresent }
  , { walsCode := "apu", iso := "apu", value := .allPresent }
  , { walsCode := "arb", iso := "arl", value := .allPresent }
  , { walsCode := "aeg", iso := "arz", value := .allPresent }
  , { walsCode := "ana", iso := "aro", value := .allPresent }
  , { walsCode := "arp", iso := "ape", value := .allPresent }
  , { walsCode := "arc", iso := "aqc", value := .allPresent }
  , { walsCode := "arm", iso := "hye", value := .allPresent }
  , { walsCode := "amp", iso := "aer", value := .noFricatives }
  , { walsCode := "asm", iso := "cns", value := .allPresent }
  , { walsCode := "ata", iso := "tay", value := .allPresent }
  , { walsCode := "ava", iso := "ava", value := .allPresent }
  , { walsCode := "awp", iso := "kwi", value := .allPresent }
  , { walsCode := "awn", iso := "awn", value := .allPresent }
  , { walsCode := "aym", iso := "ayr", value := .allPresent }
  , { walsCode := "aze", iso := "", value := .allPresent }
  , { walsCode := "bag", iso := "bmi", value := .allPresent }
  , { walsCode := "bai", iso := "bca", value := .allPresent }
  , { walsCode := "baj", iso := "bdl", value := .allPresent }
  , { walsCode := "bki", iso := "bkq", value := .allPresent }
  , { walsCode := "bam", iso := "bam", value := .allPresent }
  , { walsCode := "byu", iso := "bdy", value := .noFricatives }
  , { walsCode := "brd", iso := "bcj", value := .noFricatives }
  , { walsCode := "brb", iso := "bba", value := .allPresent }
  , { walsCode := "bsk", iso := "bak", value := .allPresent }
  , { walsCode := "bsq", iso := "eus", value := .allPresent }
  , { walsCode := "bkr", iso := "btx", value := .allPresent }
  , { walsCode := "bto", iso := "bbc", value := .allPresent }
  , { walsCode := "baw", iso := "bgr", value := .allPresent }
  , { walsCode := "bee", iso := "beq", value := .allPresent }
  , { walsCode := "bej", iso := "bej", value := .allPresent }
  , { walsCode := "bco", iso := "blc", value := .allPresent }
  , { walsCode := "ben", iso := "ben", value := .allPresent }
  , { walsCode := "bma", iso := "tzm", value := .allPresent }
  , { walsCode := "ber", iso := "wti", value := .allPresent }
  , { walsCode := "bir", iso := "bom", value := .allPresent }
  , { walsCode := "bis", iso := "bib", value := .allPresent }
  , { walsCode := "bbf", iso := "bbo", value := .allPresent }
  , { walsCode := "bod", iso := "brx", value := .allPresent }
  , { walsCode := "brr", iso := "bor", value := .noFricatives }
  , { walsCode := "brh", iso := "brh", value := .allPresent }
  , { walsCode := "bra", iso := "brb", value := .allPresent }
  , { walsCode := "bre", iso := "bre", value := .allPresent }
  , { walsCode := "bri", iso := "bzd", value := .allPresent }
  , { walsCode := "brw", iso := "brv", value := .allPresent }
  , { walsCode := "bul", iso := "bul", value := .allPresent }
  , { walsCode := "bua", iso := "bvr", value := .noFricatives }
  , { walsCode := "brm", iso := "mya", value := .allPresent }
  , { walsCode := "bur", iso := "bsk", value := .allPresent }
  , { walsCode := "bet", iso := "bev", value := .allPresent }
  , { walsCode := "cac", iso := "cbv", value := .noFricatives }
  , { walsCode := "cad", iso := "cad", value := .allPresent }
  , { walsCode := "cah", iso := "chl", value := .allPresent }
  , { walsCode := "cax", iso := "", value := .allPresent }
  , { walsCode := "cam", iso := "kbh", value := .allPresent }
  , { walsCode := "cnl", iso := "ram", value := .allPresent }
  , { walsCode := "cnt", iso := "yue", value := .allPresent }
  , { walsCode := "car", iso := "car", value := .allPresent }
  , { walsCode := "ctl", iso := "cat", value := .allPresent }
  , { walsCode := "cay", iso := "cbi", value := .allPresent }
  , { walsCode := "cyv", iso := "cyb", value := .allPresent }
  , { walsCode := "chw", iso := "cja", value := .allPresent }
  , { walsCode := "cha", iso := "cha", value := .allPresent }
  , { walsCode := "cso", iso := "ctp", value := .allPresent }
  , { walsCode := "chl", iso := "cjh", value := .allPresent }
  , { walsCode := "che", iso := "chr", value := .allPresent }
  , { walsCode := "cck", iso := "cic", value := .allPresent }
  , { walsCode := "cti", iso := "ctd", value := .allPresent }
  , { walsCode := "cle", iso := "cle", value := .allPresent }
  , { walsCode := "chq", iso := "chq", value := .allPresent }
  , { walsCode := "chp", iso := "chp", value := .noBilabials }
  , { walsCode := "cve", iso := "cjv", value := .allPresent }
  , { walsCode := "chk", iso := "ckt", value := .allPresent }
  , { walsCode := "chv", iso := "chv", value := .allPresent }
  , { walsCode := "cil", iso := "lua", value := .allPresent }
  , { walsCode := "ccp", iso := "coc", value := .allPresent }
  , { walsCode := "cof", iso := "con", value := .allPresent }
  , { walsCode := "cmn", iso := "com", value := .allPresent }
  , { walsCode := "coo", iso := "csz", value := .allPresent }
  , { walsCode := "cre", iso := "crk", value := .allPresent }
  , { walsCode := "cub", iso := "cub", value := .noNasals }
  , { walsCode := "dad", iso := "mps", value := .allPresent }
  , { walsCode := "dag", iso := "dgz", value := .allPresent }
  , { walsCode := "dgb", iso := "dag", value := .allPresent }
  , { walsCode := "dgr", iso := "dta", value := .allPresent }
  , { walsCode := "dah", iso := "dal", value := .allPresent }
  , { walsCode := "ddf", iso := "daj", value := .allPresent }
  , { walsCode := "dan", iso := "dnj", value := .allPresent }
  , { walsCode := "dnw", iso := "daa", value := .allPresent }
  , { walsCode := "dni", iso := "dni", value := .allPresent }
  , { walsCode := "dar", iso := "dry", value := .allPresent }
  , { walsCode := "det", iso := "shg", value := .allPresent }
  , { walsCode := "die", iso := "dih", value := .allPresent }
  , { walsCode := "din", iso := "din", value := .noFricatives }
  , { walsCode := "dio", iso := "dyo", value := .allPresent }
  , { walsCode := "diy", iso := "dif", value := .noFricatives }
  , { walsCode := "diz", iso := "mdx", value := .allPresent }
  , { walsCode := "djp", iso := "dwu", value := .noFricatives }
  , { walsCode := "der", iso := "kbv", value := .noFricatives }
  , { walsCode := "don", iso := "kmc", value := .allPresent }
  , { walsCode := "doy", iso := "dow", value := .allPresent }
  , { walsCode := "dre", iso := "dhv", value := .allPresent }
  , { walsCode := "dum", iso := "vam", value := .allPresent }
  , { walsCode := "dyi", iso := "dbl", value := .noFricatives }
  , { walsCode := "efi", iso := "efi", value := .allPresent }
  , { walsCode := "eja", iso := "etu", value := .allPresent }
  , { walsCode := "eka", iso := "ekg", value := .noFricatives }
  , { walsCode := "eng", iso := "eng", value := .allPresent }
  , { walsCode := "epe", iso := "sja", value := .noNasals }
  , { walsCode := "evn", iso := "eve", value := .allPresent }
  , { walsCode := "eve", iso := "evn", value := .allPresent }
  , { walsCode := "ewe", iso := "ewe", value := .allPresent }
  , { walsCode := "ewo", iso := "ewo", value := .allPresent }
  , { walsCode := "eya", iso := "eya", value := .noBilabialsOrNasals }
  , { walsCode := "fas", iso := "faa", value := .allPresent }
  , { walsCode := "fef", iso := "fmp", value := .allPresent }
  , { walsCode := "fij", iso := "fij", value := .allPresent }
  , { walsCode := "fin", iso := "fin", value := .allPresent }
  , { walsCode := "fre", iso := "fra", value := .allPresent }
  , { walsCode := "ful", iso := "fun", value := .allPresent }
  , { walsCode := "fur", iso := "fvr", value := .allPresent }
  , { walsCode := "fuz", iso := "cdo", value := .allPresent }
  , { walsCode := "fye", iso := "pym", value := .allPresent }
  , { walsCode := "gds", iso := "gaj", value := .noFricatives }
  , { walsCode := "gar", iso := "grt", value := .allPresent }
  , { walsCode := "grr", iso := "wrk", value := .noFricatives }
  , { walsCode := "gbb", iso := "gbp", value := .allPresent }
  , { walsCode := "gla", iso := "gqu", value := .allPresent }
  , { walsCode := "geo", iso := "kat", value := .allPresent }
  , { walsCode := "ger", iso := "deu", value := .allPresent }
  , { walsCode := "goa", iso := "guc", value := .allPresent }
  , { walsCode := "goo", iso := "gni", value := .noFricatives }
  , { walsCode := "gan", iso := "apq", value := .noFricatives }
  , { walsCode := "grb", iso := "grj", value := .allPresent }
  , { walsCode := "grk", iso := "ell", value := .allPresent }
  , { walsCode := "grw", iso := "kal", value := .allPresent }
  , { walsCode := "ghb", iso := "guh", value := .allPresent }
  , { walsCode := "gmb", iso := "gum", value := .allPresent }
  , { walsCode := "gua", iso := "gug", value := .allPresent }
  , { walsCode := "gwa", iso := "gbr", value := .allPresent }
  , { walsCode := "ga", iso := "gaa", value := .allPresent }
  , { walsCode := "had", iso := "hts", value := .allPresent }
  , { walsCode := "hai", iso := "hai", value := .allPresent }
  , { walsCode := "hak", iso := "hak", value := .allPresent }
  , { walsCode := "hmr", iso := "amf", value := .allPresent }
  , { walsCode := "ham", iso := "hmt", value := .allPresent }
  , { walsCode := "hau", iso := "hau", value := .allPresent }
  , { walsCode := "haw", iso := "haw", value := .noFricatives }
  , { walsCode := "hba", iso := "heb", value := .allPresent }
  , { walsCode := "hin", iso := "hin", value := .allPresent }
  , { walsCode := "hix", iso := "hix", value := .allPresent }
  , { walsCode := "hmo", iso := "hnj", value := .allPresent }
  , { walsCode := "hop", iso := "hop", value := .allPresent }
  , { walsCode := "htc", iso := "hus", value := .allPresent }
  , { walsCode := "hve", iso := "huv", value := .allPresent }
  , { walsCode := "hum", iso := "huu", value := .allPresent }
  , { walsCode := "hun", iso := "hun", value := .allPresent }
  , { walsCode := "hzb", iso := "huz", value := .allPresent }
  , { walsCode := "hup", iso := "hup", value := .allPresent }
  , { walsCode := "iaa", iso := "iai", value := .allPresent }
  , { walsCode := "iba", iso := "iba", value := .allPresent }
  , { walsCode := "igb", iso := "ibo", value := .allPresent }
  , { walsCode := "ign", iso := "ign", value := .allPresent }
  , { walsCode := "ijo", iso := "ijc", value := .allPresent }
  , { walsCode := "ik", iso := "ikx", value := .allPresent }
  , { walsCode := "ika", iso := "arh", value := .allPresent }
  , { walsCode := "imo", iso := "imn", value := .allPresent }
  , { walsCode := "ind", iso := "ind", value := .allPresent }
  , { walsCode := "igs", iso := "tbi", value := .allPresent }
  , { walsCode := "ing", iso := "inh", value := .allPresent }
  , { walsCode := "irx", iso := "irn", value := .allPresent }
  , { walsCode := "irq", iso := "irk", value := .allPresent }
  , { walsCode := "irr", iso := "irh", value := .allPresent }
  , { walsCode := "ird", iso := "gle", value := .allPresent }
  , { walsCode := "iso", iso := "iso", value := .allPresent }
  , { walsCode := "ite", iso := "itl", value := .allPresent }
  , { walsCode := "ito", iso := "ito", value := .allPresent }
  , { walsCode := "iva", iso := "ivb", value := .allPresent }
  , { walsCode := "iwm", iso := "iwm", value := .allPresent }
  , { walsCode := "jak", iso := "jac", value := .allPresent }
  , { walsCode := "jpn", iso := "jpn", value := .allPresent }
  , { walsCode := "jpr", iso := "jru", value := .allPresent }
  , { walsCode := "jaq", iso := "jqr", value := .allPresent }
  , { walsCode := "jav", iso := "jav", value := .allPresent }
  , { walsCode := "jeb", iso := "jeb", value := .allPresent }
  , { walsCode := "jeh", iso := "jeh", value := .allPresent }
  , { walsCode := "jng", iso := "kac", value := .allPresent }
  , { walsCode := "jiv", iso := "jiv", value := .allPresent }
  , { walsCode := "jom", iso := "tlo", value := .allPresent }
  , { walsCode := "juh", iso := "ktz", value := .allPresent }
  , { walsCode := "kek", iso := "kek", value := .allPresent }
  , { walsCode := "kab", iso := "kbd", value := .allPresent }
  , { walsCode := "kad", iso := "xtc", value := .allPresent }
  , { walsCode := "kng", iso := "kgp", value := .noNasals }
  , { walsCode := "kly", iso := "mwp", value := .allPresent }
  , { walsCode := "kal", iso := "gwc", value := .allPresent }
  , { walsCode := "kgu", iso := "ktg", value := .noFricatives }
  , { walsCode := "knk", iso := "kna", value := .allPresent }
  , { walsCode := "knd", iso := "kan", value := .allPresent }
  , { walsCode := "knr", iso := "knc", value := .allPresent }
  , { walsCode := "ksg", iso := "ksw", value := .allPresent }
  , { walsCode := "krk", iso := "kyh", value := .allPresent }
  , { walsCode := "kas", iso := "kas", value := .allPresent }
  , { walsCode := "kws", iso := "xaw", value := .allPresent }
  , { walsCode := "kyl", iso := "eky", value := .allPresent }
  , { walsCode := "kay", iso := "gyd", value := .noFricatives }
  , { walsCode := "ked", iso := "ksx", value := .allPresent }
  , { walsCode := "kef", iso := "kbr", value := .allPresent }
  , { walsCode := "ker", iso := "ker", value := .allPresent }
  , { walsCode := "ket", iso := "ket", value := .allPresent }
  , { walsCode := "kew", iso := "kew", value := .allPresent }
  , { walsCode := "kha", iso := "khk", value := .allPresent }
  , { walsCode := "kty", iso := "kca", value := .allPresent }
  , { walsCode := "khr", iso := "khr", value := .allPresent }
  , { walsCode := "khs", iso := "kha", value := .allPresent }
  , { walsCode := "khm", iso := "khm", value := .allPresent }
  , { walsCode := "kmu", iso := "kjg", value := .allPresent }
  , { walsCode := "klv", iso := "kij", value := .allPresent }
  , { walsCode := "kio", iso := "kio", value := .allPresent }
  , { walsCode := "kgz", iso := "kir", value := .allPresent }
  , { walsCode := "krb", iso := "gil", value := .noFricatives }
  , { walsCode := "kss", iso := "kss", value := .allPresent }
  , { walsCode := "kiw", iso := "kjd", value := .allPresent }
  , { walsCode := "klm", iso := "kla", value := .allPresent }
  , { walsCode := "kla", iso := "klu", value := .noNasals }
  , { walsCode := "koa", iso := "cku", value := .allPresent }
  , { walsCode := "kob", iso := "kpw", value := .allPresent }
  , { walsCode := "koh", iso := "bcs", value := .allPresent }
  , { walsCode := "koi", iso := "kbk", value := .allPresent }
  , { walsCode := "kzy", iso := "kpv", value := .allPresent }
  , { walsCode := "kom", iso := "xom", value := .allPresent }
  , { walsCode := "kkn", iso := "knn", value := .allPresent }
  , { walsCode := "kgi", iso := "cou", value := .allPresent }
  , { walsCode := "kor", iso := "kor", value := .allPresent }
  , { walsCode := "kfe", iso := "kfz", value := .allPresent }
  , { walsCode := "kry", iso := "kpy", value := .allPresent }
  , { walsCode := "kot", iso := "kfe", value := .allPresent }
  , { walsCode := "ktk", iso := "aal", value := .allPresent }
  , { walsCode := "koy", iso := "kff", value := .allPresent }
  , { walsCode := "kch", iso := "khq", value := .allPresent }
  , { walsCode := "kse", iso := "ses", value := .allPresent }
  , { walsCode := "kpa", iso := "kpk", value := .noNasals }
  , { walsCode := "kpe", iso := "xpe", value := .allPresent }
  , { walsCode := "kro", iso := "kgo", value := .allPresent }
  , { walsCode := "kya", iso := "gvn", value := .noFricatives }
  , { walsCode := "kul", iso := "dwr", value := .allPresent }
  , { walsCode := "kun", iso := "kvn", value := .allPresent }
  , { walsCode := "knm", iso := "kun", value := .allPresent }
  , { walsCode := "kmp", iso := "kup", value := .allPresent }
  , { walsCode := "krd", iso := "ckb", value := .allPresent }
  , { walsCode := "kur", iso := "kru", value := .allPresent }
  , { walsCode := "kut", iso := "kut", value := .allPresent }
  , { walsCode := "kwa", iso := "kwd", value := .allPresent }
  , { walsCode := "kwk", iso := "kwk", value := .allPresent }
  , { walsCode := "kwo", iso := "kmo", value := .allPresent }
  , { walsCode := "lad", iso := "lbj", value := .allPresent }
  , { walsCode := "lah", iso := "lhu", value := .allPresent }
  , { walsCode := "lak", iso := "lbe", value := .allPresent }
  , { walsCode := "lkt", iso := "lkt", value := .allPresent }
  , { walsCode := "lkk", iso := "lbc", value := .allPresent }
  , { walsCode := "lam", iso := "lme", value := .allPresent }
  , { walsCode := "lan", iso := "laj", value := .noFricatives }
  , { walsCode := "lat", iso := "lav", value := .allPresent }
  , { walsCode := "lav", iso := "lvk", value := .allPresent }
  , { walsCode := "llm", iso := "lef", value := .allPresent }
  , { walsCode := "len", iso := "tnl", value := .allPresent }
  , { walsCode := "lep", iso := "lep", value := .allPresent }
  , { walsCode := "lez", iso := "lez", value := .allPresent }
  , { walsCode := "lit", iso := "lit", value := .allPresent }
  , { walsCode := "lua", iso := "nie", value := .allPresent }
  , { walsCode := "lug", iso := "lgg", value := .allPresent }
  , { walsCode := "lui", iso := "lui", value := .allPresent }
  , { walsCode := "luo", iso := "luo", value := .allPresent }
  , { walsCode := "lus", iso := "lut", value := .allPresent }
  , { walsCode := "kkv", iso := "khl", value := .allPresent }
  , { walsCode := "luv", iso := "lue", value := .allPresent }
  , { walsCode := "lu", iso := "khb", value := .allPresent }
  , { walsCode := "mya", iso := "slz", value := .allPresent }
  , { walsCode := "maa", iso := "mas", value := .allPresent }
  , { walsCode := "mab", iso := "mde", value := .allPresent }
  , { walsCode := "mne", iso := "nmu", value := .allPresent }
  , { walsCode := "mak", iso := "myh", value := .allPresent }
  , { walsCode := "mal", iso := "plt", value := .allPresent }
  , { walsCode := "mlk", iso := "mpb", value := .noFricatives }
  , { walsCode := "mla", iso := "", value := .allPresent }
  , { walsCode := "mnc", iso := "mnc", value := .allPresent }
  , { walsCode := "mnd", iso := "cmn", value := .allPresent }
  , { walsCode := "myi", iso := "mpc", value := .noFricatives }
  , { walsCode := "mgg", iso := "mjg", value := .allPresent }
  , { walsCode := "mao", iso := "mri", value := .allPresent }
  , { walsCode := "map", iso := "arn", value := .allPresent }
  , { walsCode := "mrn", iso := "mrw", value := .noFricatives }
  , { walsCode := "mku", iso := "zmr", value := .noFricatives }
  , { walsCode := "mrg", iso := "mrt", value := .allPresent }
  , { walsCode := "mme", iso := "mhr", value := .allPresent }
  , { walsCode := "mar", iso := "mrc", value := .allPresent }
  , { walsCode := "mrd", iso := "mrz", value := .allPresent }
  , { walsCode := "mrt", iso := "vma", value := .noFricatives }
  , { walsCode := "mau", iso := "mph", value := .allPresent }
  , { walsCode := "max", iso := "mbl", value := .noFricativesOrNasals }
  , { walsCode := "may", iso := "ayz", value := .allPresent }
  , { walsCode := "maz", iso := "maz", value := .allPresent }
  , { walsCode := "mzc", iso := "maq", value := .allPresent }
  , { walsCode := "mba", iso := "mfc", value := .allPresent }
  , { walsCode := "mbb", iso := "vmb", value := .noFricatives }
  , { walsCode := "mbm", iso := "mdd", value := .allPresent }
  , { walsCode := "mei", iso := "mni", value := .allPresent }
  , { walsCode := "mie", iso := "ium", value := .allPresent }
  , { walsCode := "hok", iso := "nan", value := .allPresent }
  , { walsCode := "mss", iso := "skd", value := .allPresent }
  , { walsCode := "mtp", iso := "mto", value := .allPresent }
  , { walsCode := "mxc", iso := "mig", value := .allPresent }
  , { walsCode := "mxm", iso := "mig", value := .allPresent }
  , { walsCode := "mog", iso := "mhj", value := .allPresent }
  , { walsCode := "mor", iso := "mhz", value := .allPresent }
  , { walsCode := "mro", iso := "mor", value := .allPresent }
  , { walsCode := "mov", iso := "mzp", value := .allPresent }
  , { walsCode := "mui", iso := "bmr", value := .allPresent }
  , { walsCode := "mum", iso := "mzm", value := .allPresent }
  , { walsCode := "mun", iso := "unr", value := .allPresent }
  , { walsCode := "mrl", iso := "mur", value := .allPresent }
  , { walsCode := "mpa", iso := "mwf", value := .noFricatives }
  , { walsCode := "nhn", iso := "ncj", value := .allPresent }
  , { walsCode := "nht", iso := "nhg", value := .allPresent }
  , { walsCode := "kho", iso := "naq", value := .allPresent }
  , { walsCode := "nmb", iso := "nab", value := .allPresent }
  , { walsCode := "nai", iso := "gld", value := .allPresent }
  , { walsCode := "nnc", iso := "ncb", value := .allPresent }
  , { walsCode := "nan", iso := "niq", value := .allPresent }
  , { walsCode := "nar", iso := "nrb", value := .allPresent }
  , { walsCode := "nas", iso := "nas", value := .allPresent }
  , { walsCode := "nbk", iso := "ntu", value := .allPresent }
  , { walsCode := "nav", iso := "nav", value := .allPresent }
  , { walsCode := "nax", iso := "nxq", value := .allPresent }
  , { walsCode := "ndt", iso := "ndv", value := .allPresent }
  , { walsCode := "ndy", iso := "djk", value := .allPresent }
  , { walsCode := "ntu", iso := "yrk", value := .allPresent }
  , { walsCode := "nap", iso := "trg", value := .allPresent }
  , { walsCode := "nep", iso := "npi", value := .allPresent }
  , { walsCode := "new", iso := "new", value := .allPresent }
  , { walsCode := "nez", iso := "nez", value := .allPresent }
  , { walsCode := "nga", iso := "nio", value := .allPresent }
  , { walsCode := "nti", iso := "niy", value := .allPresent }
  , { walsCode := "ngi", iso := "wyb", value := .allPresent }
  , { walsCode := "ngz", iso := "ngi", value := .allPresent }
  , { walsCode := "nim", iso := "nir", value := .allPresent }
  , { walsCode := "chu", iso := "cag", value := .allPresent }
  , { walsCode := "niv", iso := "niv", value := .allPresent }
  , { walsCode := "nko", iso := "cgg", value := .allPresent }
  , { walsCode := "nob", iso := "fia", value := .allPresent }
  , { walsCode := "non", iso := "nhu", value := .allPresent }
  , { walsCode := "nor", iso := "nor", value := .allPresent }
  , { walsCode := "nun", iso := "nut", value := .allPresent }
  , { walsCode := "nug", iso := "nuy", value := .noFricatives }
  , { walsCode := "nuu", iso := "nuk", value := .allPresent }
  , { walsCode := "nkt", iso := "cbn", value := .allPresent }
  , { walsCode := "nyg", iso := "nyp", value := .allPresent }
  , { walsCode := "nyi", iso := "nyi", value := .allPresent }
  , { walsCode := "nis", iso := "njz", value := .allPresent }
  , { walsCode := "ood", iso := "ood", value := .allPresent }
  , { walsCode := "oca", iso := "oca", value := .allPresent }
  , { walsCode := "ogb", iso := "ogb", value := .allPresent }
  , { walsCode := "oji", iso := "", value := .allPresent }
  , { walsCode := "ond", iso := "one", value := .noBilabials }
  , { walsCode := "orm", iso := "oru", value := .allPresent }
  , { walsCode := "orh", iso := "hae", value := .allPresent }
  , { walsCode := "otm", iso := "ote", value := .allPresent }
  , { walsCode := "pms", iso := "pma", value := .allPresent }
  , { walsCode := "pac", iso := "pac", value := .allPresent }
  , { walsCode := "pai", iso := "pwn", value := .allPresent }
  , { walsCode := "pnr", iso := "pbh", value := .noFricatives }
  , { walsCode := "puk", iso := "prk", value := .allPresent }
  , { walsCode := "psh", iso := "pst", value := .allPresent }
  , { walsCode := "psm", iso := "pqm", value := .allPresent }
  , { walsCode := "pau", iso := "pad", value := .allPresent }
  , { walsCode := "paw", iso := "pwa", value := .allPresent }
  , { walsCode := "pec", iso := "pay", value := .allPresent }
  , { walsCode := "prs", iso := "pes", value := .allPresent }
  , { walsCode := "phl", iso := "pww", value := .allPresent }
  , { walsCode := "prh", iso := "myp", value := .noNasals }
  , { walsCode := "pit", iso := "pjt", value := .noFricatives }
  , { walsCode := "poa", iso := "fwa", value := .allPresent }
  , { walsCode := "poh", iso := "pon", value := .allPresent }
  , { walsCode := "pol", iso := "pol", value := .allPresent }
  , { walsCode := "pso", iso := "pom", value := .allPresent }
  , { walsCode := "pur", iso := "tsz", value := .allPresent }
  , { walsCode := "pae", iso := "pbb", value := .allPresent }
  , { walsCode := "bng", iso := "byx", value := .allPresent }
  , { walsCode := "qaw", iso := "alc", value := .allPresent }
  , { walsCode := "qco", iso := "quh", value := .allPresent }
  , { walsCode := "qui", iso := "qui", value := .noNasals }
  , { walsCode := "ram", iso := "rma", value := .allPresent }
  , { walsCode := "rap", iso := "rap", value := .allPresent }
  , { walsCode := "res", iso := "rgr", value := .allPresent }
  , { walsCode := "rom", iso := "ron", value := .allPresent }
  , { walsCode := "rsc", iso := "roh", value := .allPresent }
  , { walsCode := "ror", iso := "rro", value := .allPresent }
  , { walsCode := "rtk", iso := "roo", value := .noNasals }
  , { walsCode := "ruk", iso := "dru", value := .allPresent }
  , { walsCode := "rus", iso := "rus", value := .allPresent }
  , { walsCode := "rut", iso := "rut", value := .allPresent }
  , { walsCode := "sab", iso := "snv", value := .allPresent }
  , { walsCode := "scs", iso := "sma", value := .allPresent }
  , { walsCode := "sdw", iso := "sad", value := .allPresent }
  , { walsCode := "san", iso := "sag", value := .allPresent }
  , { walsCode := "snm", iso := "xsu", value := .allPresent }
  , { walsCode := "svs", iso := "svs", value := .allPresent }
  , { walsCode := "seb", iso := "kpz", value := .allPresent }
  , { walsCode := "sed", iso := "sed", value := .allPresent }
  , { walsCode := "slp", iso := "spl", value := .allPresent }
  , { walsCode := "sel", iso := "ona", value := .allPresent }
  , { walsCode := "skp", iso := "sel", value := .allPresent }
  , { walsCode := "sml", iso := "sza", value := .allPresent }
  , { walsCode := "snd", iso := "sef", value := .allPresent }
  , { walsCode := "snc", iso := "see", value := .allPresent }
  , { walsCode := "snt", iso := "set", value := .allPresent }
  , { walsCode := "sha", iso := "shn", value := .allPresent }
  , { walsCode := "shs", iso := "sht", value := .allPresent }
  , { walsCode := "shk", iso := "shp", value := .allPresent }
  , { walsCode := "shi", iso := "shb", value := .allPresent }
  , { walsCode := "shu", iso := "shs", value := .allPresent }
  , { walsCode := "sdh", iso := "snd", value := .allPresent }
  , { walsCode := "snh", iso := "sin", value := .allPresent }
  , { walsCode := "sin", iso := "snn", value := .allPresent }
  , { walsCode := "srn", iso := "srq", value := .allPresent }
  , { walsCode := "sla", iso := "den", value := .allPresent }
  , { walsCode := "som", iso := "som", value := .allPresent }
  , { walsCode := "soq", iso := "sqt", value := .allPresent }
  , { walsCode := "sor", iso := "srb", value := .allPresent }
  , { walsCode := "spa", iso := "spa", value := .allPresent }
  , { walsCode := "squ", iso := "squ", value := .allPresent }
  , { walsCode := "sre", iso := "kpm", value := .allPresent }
  , { walsCode := "sue", iso := "sue", value := .allPresent }
  , { walsCode := "sui", iso := "swi", value := .allPresent }
  , { walsCode := "sup", iso := "spp", value := .allPresent }
  , { walsCode := "swa", iso := "swh", value := .allPresent }
  , { walsCode := "sba", iso := "slc", value := .allPresent }
  , { walsCode := "tab", iso := "mky", value := .allPresent }
  , { walsCode := "tac", iso := "tna", value := .allPresent }
  , { walsCode := "tag", iso := "tgl", value := .allPresent }
  , { walsCode := "tma", iso := "tma", value := .allPresent }
  , { walsCode := "tam", iso := "taj", value := .allPresent }
  , { walsCode := "tmp", iso := "tpm", value := .allPresent }
  , { walsCode := "tok", iso := "yer", value := .allPresent }
  , { walsCode := "tas", iso := "shi", value := .allPresent }
  , { walsCode := "tsg", iso := "tsg", value := .allPresent }
  , { walsCode := "teh", iso := "teh", value := .allPresent }
  , { walsCode := "tks", iso := "kkw", value := .allPresent }
  , { walsCode := "tel", iso := "tel", value := .allPresent }
  , { walsCode := "tmn", iso := "teq", value := .allPresent }
  , { walsCode := "tne", iso := "tem", value := .allPresent }
  , { walsCode := "ter", iso := "ttr", value := .allPresent }
  , { walsCode := "ttn", iso := "tet", value := .allPresent }
  , { walsCode := "tha", iso := "tha", value := .allPresent }
  , { walsCode := "tib", iso := "bod", value := .allPresent }
  , { walsCode := "tic", iso := "tca", value := .allPresent }
  , { walsCode := "tgk", iso := "tgc", value := .allPresent }
  , { walsCode := "tgr", iso := "tig", value := .allPresent }
  , { walsCode := "try", iso := "tiy", value := .allPresent }
  , { walsCode := "twn", iso := "twf", value := .allPresent }
  , { walsCode := "tiw", iso := "tiw", value := .allPresent }
  , { walsCode := "tlp", iso := "tcf", value := .allPresent }
  , { walsCode := "tli", iso := "tli", value := .noBilabials }
  , { walsCode := "toa", iso := "tqo", value := .allPresent }
  , { walsCode := "tol", iso := "jic", value := .allPresent }
  , { walsCode := "ton", iso := "tqw", value := .allPresent }
  , { walsCode := "dts", iso := "dts", value := .allPresent }
  , { walsCode := "tpa", iso := "top", value := .allPresent }
  , { walsCode := "tru", iso := "tpy", value := .allPresent }
  ]

private def allData_1 : List (Datapoint AbsenceOfCommonConsonants) :=
  [ { walsCode := "tsi", iso := "tsi", value := .allPresent }
  , { walsCode := "tso", iso := "tsu", value := .allPresent }
  , { walsCode := "ttu", iso := "bbl", value := .allPresent }
  , { walsCode := "tug", iso := "thv", value := .allPresent }
  , { walsCode := "tuk", iso := "", value := .allPresent }
  , { walsCode := "tul", iso := "tcy", value := .allPresent }
  , { walsCode := "tun", iso := "tun", value := .allPresent }
  , { walsCode := "tur", iso := "tur", value := .allPresent }
  , { walsCode := "tuv", iso := "tyv", value := .allPresent }
  , { walsCode := "tza", iso := "tzh", value := .allPresent }
  , { walsCode := "umb", iso := "umb", value := .allPresent }
  , { walsCode := "una", iso := "mtg", value := .allPresent }
  , { walsCode := "ung", iso := "ung", value := .noFricatives }
  , { walsCode := "urk", iso := "urb", value := .allPresent }
  , { walsCode := "usa", iso := "wnu", value := .allPresent }
  , { walsCode := "uzn", iso := "uzn", value := .allPresent }
  , { walsCode := "vie", iso := "vie", value := .allPresent }
  , { walsCode := "wah", iso := "", value := .noFricatives }
  , { walsCode := "bno", iso := "bao", value := .noNasals }
  , { walsCode := "wam", iso := "wmb", value := .noFricatives }
  , { walsCode := "wnt", iso := "wnc", value := .allPresent }
  , { walsCode := "wao", iso := "auc", value := .noFricatives }
  , { walsCode := "wps", iso := "wap", value := .allPresent }
  , { walsCode := "wap", iso := "wao", value := .allPresent }
  , { walsCode := "wra", iso := "wba", value := .allPresent }
  , { walsCode := "wry", iso := "wrz", value := .noFricatives }
  , { walsCode := "wrd", iso := "wrr", value := .noFricatives }
  , { walsCode := "war", iso := "pav", value := .noFricatives }
  , { walsCode := "wrs", iso := "wrs", value := .allPresent }
  , { walsCode := "wma", iso := "mqs", value := .allPresent }
  , { walsCode := "wdo", iso := "pjt", value := .noFricatives }
  , { walsCode := "wic", iso := "wic", value := .noBilabials }
  , { walsCode := "wch", iso := "mzh", value := .allPresent }
  , { walsCode := "wmu", iso := "wim", value := .noFricatives }
  , { walsCode := "win", iso := "wnw", value := .allPresent }
  , { walsCode := "wiy", iso := "wiy", value := .allPresent }
  , { walsCode := "woi", iso := "woi", value := .allPresent }
  , { walsCode := "wlf", iso := "wol", value := .allPresent }
  , { walsCode := "wuc", iso := "wuu", value := .allPresent }
  , { walsCode := "ygr", iso := "ygr", value := .allPresent }
  , { walsCode := "yag", iso := "yad", value := .noFricatives }
  , { walsCode := "ykt", iso := "sah", value := .allPresent }
  , { walsCode := "yan", iso := "ynn", value := .allPresent }
  , { walsCode := "yny", iso := "jao", value := .noFricatives }
  , { walsCode := "yap", iso := "yap", value := .allPresent }
  , { walsCode := "yaq", iso := "yaq", value := .allPresent }
  , { walsCode := "yar", iso := "yrb", value := .allPresent }
  , { walsCode := "yaw", iso := "yva", value := .allPresent }
  , { walsCode := "yay", iso := "pcc", value := .allPresent }
  , { walsCode := "yel", iso := "yle", value := .noFricatives }
  , { walsCode := "yes", iso := "yss", value := .allPresent }
  , { walsCode := "yey", iso := "yey", value := .allPresent }
  , { walsCode := "yid", iso := "yii", value := .noFricatives }
  , { walsCode := "yim", iso := "yee", value := .noFricatives }
  , { walsCode := "yor", iso := "yor", value := .allPresent }
  , { walsCode := "yct", iso := "yua", value := .allPresent }
  , { walsCode := "yuc", iso := "yuc", value := .allPresent }
  , { walsCode := "ycn", iso := "ycn", value := .allPresent }
  , { walsCode := "yko", iso := "yux", value := .allPresent }
  , { walsCode := "ytu", iso := "ykg", value := .allPresent }
  , { walsCode := "yul", iso := "yul", value := .allPresent }
  , { walsCode := "yus", iso := "ess", value := .allPresent }
  , { walsCode := "yur", iso := "yur", value := .allPresent }
  , { walsCode := "zan", iso := "zne", value := .allPresent }
  , { walsCode := "zqc", iso := "zoc", value := .allPresent }
  , { walsCode := "zul", iso := "zul", value := .allPresent }
  , { walsCode := "zun", iso := "zun", value := .allPresent }
  ]

/-- Complete WALS 18A dataset (567 languages). -/
def allData : List (Datapoint AbsenceOfCommonConsonants) := allData_0 ++ allData_1

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F18A
