import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 27A: Reduplication
@cite{rubino-2013}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 27A`.

Chapter 27, 368 languages.
-/

namespace Core.WALS.F27A

/-- WALS 27A values. -/
inductive ReduplicationType where
  /-- Productive full and partial reduplication (278 languages). -/
  | productiveFullAndPartialReduplication
  /-- Full reduplication only (35 languages). -/
  | fullReduplicationOnly
  /-- No productive reduplication (55 languages). -/
  | noProductiveReduplication
  deriving DecidableEq, BEq, Repr

/-- Complete WALS 27A dataset (368 languages). -/
def allData : List (Datapoint ReduplicationType) :=
  [ { walsCode := "abk", iso := "abk", value := .productiveFullAndPartialReduplication }
  , { walsCode := "agl", iso := "agx", value := .noProductiveReduplication }
  , { walsCode := "agc", iso := "agt", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ain", iso := "ain", value := .fullReduplicationOnly }
  , { walsCode := "akn", iso := "aka", value := .productiveFullAndPartialReduplication }
  , { walsCode := "abm", iso := "akz", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ala", iso := "amp", value := .productiveFullAndPartialReduplication }
  , { walsCode := "alw", iso := "alh", value := .productiveFullAndPartialReduplication }
  , { walsCode := "aly", iso := "aly", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ame", iso := "aey", value := .productiveFullAndPartialReduplication }
  , { walsCode := "amh", iso := "amh", value := .productiveFullAndPartialReduplication }
  , { walsCode := "adk", iso := "ano", value := .noProductiveReduplication }
  , { walsCode := "apl", iso := "apy", value := .productiveFullAndPartialReduplication }
  , { walsCode := "api", iso := "apn", value := .productiveFullAndPartialReduplication }
  , { walsCode := "apu", iso := "apu", value := .noProductiveReduplication }
  , { walsCode := "aeg", iso := "arz", value := .productiveFullAndPartialReduplication }
  , { walsCode := "asy", iso := "apc", value := .productiveFullAndPartialReduplication }
  , { walsCode := "arp", iso := "ape", value := .productiveFullAndPartialReduplication }
  , { walsCode := "arm", iso := "hye", value := .fullReduplicationOnly }
  , { walsCode := "arw", iso := "hyw", value := .fullReduplicationOnly }
  , { walsCode := "amp", iso := "aer", value := .productiveFullAndPartialReduplication }
  , { walsCode := "asm", iso := "cns", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ass", iso := "asm", value := .productiveFullAndPartialReduplication }
  , { walsCode := "awp", iso := "kwi", value := .noProductiveReduplication }
  , { walsCode := "aym", iso := "ayr", value := .productiveFullAndPartialReduplication }
  , { walsCode := "bag", iso := "bmi", value := .fullReduplicationOnly }
  , { walsCode := "baj", iso := "bdl", value := .productiveFullAndPartialReduplication }
  , { walsCode := "bal", iso := "ban", value := .productiveFullAndPartialReduplication }
  , { walsCode := "bnj", iso := "bdy", value := .productiveFullAndPartialReduplication }
  , { walsCode := "bnw", iso := "bwi", value := .noProductiveReduplication }
  , { walsCode := "brs", iso := "bsn", value := .noProductiveReduplication }
  , { walsCode := "bsq", iso := "eus", value := .productiveFullAndPartialReduplication }
  , { walsCode := "bej", iso := "bej", value := .productiveFullAndPartialReduplication }
  , { walsCode := "bco", iso := "blc", value := .productiveFullAndPartialReduplication }
  , { walsCode := "bma", iso := "tzm", value := .productiveFullAndPartialReduplication }
  , { walsCode := "bkl", iso := "bcl", value := .productiveFullAndPartialReduplication }
  , { walsCode := "blx", iso := "bll", value := .productiveFullAndPartialReduplication }
  , { walsCode := "bis", iso := "bib", value := .productiveFullAndPartialReduplication }
  , { walsCode := "bsm", iso := "bis", value := .productiveFullAndPartialReduplication }
  , { walsCode := "blq", iso := "bol", value := .productiveFullAndPartialReduplication }
  , { walsCode := "buw", iso := "bum", value := .productiveFullAndPartialReduplication }
  , { walsCode := "bua", iso := "bvr", value := .fullReduplicationOnly }
  , { walsCode := "brm", iso := "mya", value := .fullReduplicationOnly }
  , { walsCode := "cah", iso := "chl", value := .productiveFullAndPartialReduplication }
  , { walsCode := "cax", iso := "", value := .productiveFullAndPartialReduplication }
  , { walsCode := "cnl", iso := "ram", value := .productiveFullAndPartialReduplication }
  , { walsCode := "car", iso := "car", value := .noProductiveReduplication }
  , { walsCode := "ctl", iso := "cat", value := .noProductiveReduplication }
  , { walsCode := "cyv", iso := "cyb", value := .productiveFullAndPartialReduplication }
  , { walsCode := "chh", iso := "sgw", value := .productiveFullAndPartialReduplication }
  , { walsCode := "cha", iso := "cha", value := .productiveFullAndPartialReduplication }
  , { walsCode := "cvc", iso := "cbk", value := .fullReduplicationOnly }
  , { walsCode := "chl", iso := "cjh", value := .productiveFullAndPartialReduplication }
  , { walsCode := "cmk", iso := "xch", value := .productiveFullAndPartialReduplication }
  , { walsCode := "cck", iso := "cic", value := .productiveFullAndPartialReduplication }
  , { walsCode := "cle", iso := "cle", value := .fullReduplicationOnly }
  , { walsCode := "cct", iso := "cho", value := .productiveFullAndPartialReduplication }
  , { walsCode := "col", iso := "ctu", value := .productiveFullAndPartialReduplication }
  , { walsCode := "chr", iso := "crw", value := .productiveFullAndPartialReduplication }
  , { walsCode := "chk", iso := "ckt", value := .productiveFullAndPartialReduplication }
  , { walsCode := "cba", iso := "boi", value := .productiveFullAndPartialReduplication }
  , { walsCode := "cin", iso := "inz", value := .productiveFullAndPartialReduplication }
  , { walsCode := "cuu", iso := "chk", value := .productiveFullAndPartialReduplication }
  , { walsCode := "cla", iso := "clm", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ccp", iso := "coc", value := .fullReduplicationOnly }
  , { walsCode := "coe", iso := "crd", value := .productiveFullAndPartialReduplication }
  , { walsCode := "cwe", iso := "col", value := .productiveFullAndPartialReduplication }
  , { walsCode := "cmn", iso := "com", value := .productiveFullAndPartialReduplication }
  , { walsCode := "cmx", iso := "coo", value := .productiveFullAndPartialReduplication }
  , { walsCode := "coo", iso := "csz", value := .productiveFullAndPartialReduplication }
  , { walsCode := "cre", iso := "crk", value := .productiveFullAndPartialReduplication }
  , { walsCode := "dag", iso := "dgz", value := .productiveFullAndPartialReduplication }
  , { walsCode := "dga", iso := "dga", value := .productiveFullAndPartialReduplication }
  , { walsCode := "dah", iso := "dal", value := .productiveFullAndPartialReduplication }
  , { walsCode := "dri", iso := "prs", value := .productiveFullAndPartialReduplication }
  , { walsCode := "dhm", iso := "dhi", value := .productiveFullAndPartialReduplication }
  , { walsCode := "diy", iso := "dif", value := .productiveFullAndPartialReduplication }
  , { walsCode := "djp", iso := "dwu", value := .productiveFullAndPartialReduplication }
  , { walsCode := "djr", iso := "ddj", value := .productiveFullAndPartialReduplication }
  , { walsCode := "dji", iso := "jig", value := .productiveFullAndPartialReduplication }
  , { walsCode := "dre", iso := "dhv", value := .productiveFullAndPartialReduplication }
  , { walsCode := "dyi", iso := "dbl", value := .productiveFullAndPartialReduplication }
  , { walsCode := "eng", iso := "eng", value := .noProductiveReduplication }
  , { walsCode := "epe", iso := "sja", value := .productiveFullAndPartialReduplication }
  , { walsCode := "err", iso := "erg", value := .fullReduplicationOnly }
  , { walsCode := "eve", iso := "evn", value := .noProductiveReduplication }
  , { walsCode := "ewe", iso := "ewe", value := .productiveFullAndPartialReduplication }
  , { walsCode := "fij", iso := "fij", value := .fullReduplicationOnly }
  , { walsCode := "fin", iso := "fin", value := .noProductiveReduplication }
  , { walsCode := "fox", iso := "sac", value := .productiveFullAndPartialReduplication }
  , { walsCode := "fre", iso := "fra", value := .noProductiveReduplication }
  , { walsCode := "fua", iso := "fub", value := .productiveFullAndPartialReduplication }
  , { walsCode := "gae", iso := "gla", value := .noProductiveReduplication }
  , { walsCode := "gar", iso := "grt", value := .productiveFullAndPartialReduplication }
  , { walsCode := "geo", iso := "kat", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ger", iso := "deu", value := .noProductiveReduplication }
  , { walsCode := "goo", iso := "gni", value := .productiveFullAndPartialReduplication }
  , { walsCode := "grk", iso := "ell", value := .noProductiveReduplication }
  , { walsCode := "grw", iso := "kal", value := .noProductiveReduplication }
  , { walsCode := "gmt", iso := "gnn", value := .fullReduplicationOnly }
  , { walsCode := "gum", iso := "kgs", value := .productiveFullAndPartialReduplication }
  , { walsCode := "hlu", iso := "hur", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ham", iso := "hmt", value := .productiveFullAndPartialReduplication }
  , { walsCode := "hrr", iso := "har", value := .productiveFullAndPartialReduplication }
  , { walsCode := "hau", iso := "hau", value := .productiveFullAndPartialReduplication }
  , { walsCode := "haw", iso := "haw", value := .productiveFullAndPartialReduplication }
  , { walsCode := "heb", iso := "heb", value := .productiveFullAndPartialReduplication }
  , { walsCode := "hil", iso := "hil", value := .productiveFullAndPartialReduplication }
  , { walsCode := "hin", iso := "hin", value := .productiveFullAndPartialReduplication }
  , { walsCode := "hix", iso := "hix", value := .noProductiveReduplication }
  , { walsCode := "hmo", iso := "hnj", value := .productiveFullAndPartialReduplication }
  , { walsCode := "hop", iso := "hop", value := .productiveFullAndPartialReduplication }
  , { walsCode := "hlp", iso := "yuf", value := .productiveFullAndPartialReduplication }
  , { walsCode := "htc", iso := "hus", value := .productiveFullAndPartialReduplication }
  , { walsCode := "hve", iso := "huv", value := .fullReduplicationOnly }
  , { walsCode := "hui", iso := "hch", value := .productiveFullAndPartialReduplication }
  , { walsCode := "hun", iso := "hun", value := .productiveFullAndPartialReduplication }
  , { walsCode := "hzb", iso := "huz", value := .productiveFullAndPartialReduplication }
  , { walsCode := "iaa", iso := "iai", value := .productiveFullAndPartialReduplication }
  , { walsCode := "igb", iso := "ibo", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ika", iso := "arh", value := .noProductiveReduplication }
  , { walsCode := "ilo", iso := "ilo", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ind", iso := "ind", value := .fullReduplicationOnly }
  , { walsCode := "iri", iso := "gle", value := .noProductiveReduplication }
  , { walsCode := "ita", iso := "ita", value := .noProductiveReduplication }
  , { walsCode := "itz", iso := "itz", value := .productiveFullAndPartialReduplication }
  , { walsCode := "jak", iso := "jac", value := .productiveFullAndPartialReduplication }
  , { walsCode := "jpn", iso := "jpn", value := .fullReduplicationOnly }
  , { walsCode := "jaq", iso := "jqr", value := .productiveFullAndPartialReduplication }
  , { walsCode := "kls", iso := "fla", value := .productiveFullAndPartialReduplication }
  , { walsCode := "kma", iso := "kay", value := .productiveFullAndPartialReduplication }
  , { walsCode := "knd", iso := "kan", value := .productiveFullAndPartialReduplication }
  , { walsCode := "knr", iso := "knc", value := .productiveFullAndPartialReduplication }
  , { walsCode := "kpm", iso := "pam", value := .productiveFullAndPartialReduplication }
  , { walsCode := "krk", iso := "kyh", value := .productiveFullAndPartialReduplication }
  , { walsCode := "kaa", iso := "arr", value := .fullReduplicationOnly }
  , { walsCode := "kay", iso := "gyd", value := .productiveFullAndPartialReduplication }
  , { walsCode := "kha", iso := "khk", value := .productiveFullAndPartialReduplication }
  , { walsCode := "khs", iso := "kha", value := .productiveFullAndPartialReduplication }
  , { walsCode := "khm", iso := "khm", value := .productiveFullAndPartialReduplication }
  , { walsCode := "kik", iso := "kik", value := .productiveFullAndPartialReduplication }
  , { walsCode := "klv", iso := "kij", value := .productiveFullAndPartialReduplication }
  , { walsCode := "kio", iso := "kio", value := .noProductiveReduplication }
  , { walsCode := "krb", iso := "gil", value := .productiveFullAndPartialReduplication }
  , { walsCode := "klm", iso := "kla", value := .productiveFullAndPartialReduplication }
  , { walsCode := "shp", iso := "yak", value := .productiveFullAndPartialReduplication }
  , { walsCode := "koa", iso := "cku", value := .productiveFullAndPartialReduplication }
  , { walsCode := "koo", iso := "kvv", value := .productiveFullAndPartialReduplication }
  , { walsCode := "kol", iso := "kfb", value := .productiveFullAndPartialReduplication }
  , { walsCode := "kor", iso := "kor", value := .productiveFullAndPartialReduplication }
  , { walsCode := "kfe", iso := "kfz", value := .noProductiveReduplication }
  , { walsCode := "krw", iso := "khe", value := .productiveFullAndPartialReduplication }
  , { walsCode := "koy", iso := "kff", value := .productiveFullAndPartialReduplication }
  , { walsCode := "kro", iso := "kgo", value := .noProductiveReduplication }
  , { walsCode := "kya", iso := "gvn", value := .productiveFullAndPartialReduplication }
  , { walsCode := "kjn", iso := "kjn", value := .productiveFullAndPartialReduplication }
  , { walsCode := "kuo", iso := "kto", value := .productiveFullAndPartialReduplication }
  , { walsCode := "kut", iso := "kut", value := .noProductiveReduplication }
  , { walsCode := "kwk", iso := "kwk", value := .productiveFullAndPartialReduplication }
  , { walsCode := "lac", iso := "lac", value := .productiveFullAndPartialReduplication }
  , { walsCode := "lkt", iso := "lkt", value := .productiveFullAndPartialReduplication }
  , { walsCode := "lmp", iso := "ljp", value := .productiveFullAndPartialReduplication }
  , { walsCode := "lan", iso := "laj", value := .noProductiveReduplication }
  , { walsCode := "lrd", iso := "lbz", value := .productiveFullAndPartialReduplication }
  , { walsCode := "lav", iso := "lvk", value := .productiveFullAndPartialReduplication }
  , { walsCode := "lez", iso := "lez", value := .noProductiveReduplication }
  , { walsCode := "lil", iso := "lil", value := .productiveFullAndPartialReduplication }
  , { walsCode := "lui", iso := "lui", value := .productiveFullAndPartialReduplication }
  , { walsCode := "luo", iso := "luo", value := .fullReduplicationOnly }
  , { walsCode := "lus", iso := "lut", value := .productiveFullAndPartialReduplication }
  , { walsCode := "kkv", iso := "khl", value := .productiveFullAndPartialReduplication }
  , { walsCode := "luv", iso := "lue", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mdr", iso := "mad", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mne", iso := "nmu", value := .noProductiveReduplication }
  , { walsCode := "maj", iso := "mpe", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mks", iso := "mak", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mal", iso := "plt", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mlk", iso := "mpb", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mym", iso := "mal", value := .fullReduplicationOnly }
  , { walsCode := "mam", iso := "mam", value := .noProductiveReduplication }
  , { walsCode := "mnm", iso := "mva", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mnd", iso := "cmn", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mmb", iso := "mna", value := .productiveFullAndPartialReduplication }
  , { walsCode := "myi", iso := "mpc", value := .productiveFullAndPartialReduplication }
  , { walsCode := "maw", iso := "mlq", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mao", iso := "mri", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mra", iso := "mec", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mku", iso := "zmr", value := .fullReduplicationOnly }
  , { walsCode := "mny", iso := "zmc", value := .fullReduplicationOnly }
  , { walsCode := "mme", iso := "mhr", value := .noProductiveReduplication }
  , { walsCode := "mar", iso := "mrc", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mrq", iso := "", value := .productiveFullAndPartialReduplication }
  , { walsCode := "msh", iso := "mah", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mrt", iso := "vma", value := .fullReduplicationOnly }
  , { walsCode := "mau", iso := "mph", value := .productiveFullAndPartialReduplication }
  , { walsCode := "may", iso := "ayz", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mei", iso := "mni", value := .productiveFullAndPartialReduplication }
  , { walsCode := "men", iso := "mez", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mki", iso := "mik", value := .productiveFullAndPartialReduplication }
  , { walsCode := "min", iso := "min", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mcs", iso := "csm", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mxl", iso := "mim", value := .fullReduplicationOnly }
  , { walsCode := "mja", iso := "mxt", value := .noProductiveReduplication }
  , { walsCode := "miy", iso := "mkf", value := .productiveFullAndPartialReduplication }
  , { walsCode := "moj", iso := "mov", value := .noProductiveReduplication }
  , { walsCode := "mok", iso := "mkj", value := .productiveFullAndPartialReduplication }
  , { walsCode := "moo", iso := "mos", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mos", iso := "cas", value := .productiveFullAndPartialReduplication }
  , { walsCode := "muh", iso := "sgw", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mpa", iso := "mwf", value := .productiveFullAndPartialReduplication }
  , { walsCode := "mwe", iso := "mwe", value := .fullReduplicationOnly }
  , { walsCode := "nhc", iso := "nhn", value := .productiveFullAndPartialReduplication }
  , { walsCode := "nak", iso := "nak", value := .productiveFullAndPartialReduplication }
  , { walsCode := "kho", iso := "naq", value := .productiveFullAndPartialReduplication }
  , { walsCode := "nnc", iso := "ncb", value := .productiveFullAndPartialReduplication }
  , { walsCode := "nde", iso := "nnb", value := .productiveFullAndPartialReduplication }
  , { walsCode := "nau", iso := "nau", value := .productiveFullAndPartialReduplication }
  , { walsCode := "nav", iso := "nav", value := .noProductiveReduplication }
  , { walsCode := "ndb", iso := "nde", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ndy", iso := "djk", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ntu", iso := "yrk", value := .noProductiveReduplication }
  , { walsCode := "nez", iso := "nez", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ngl", iso := "nig", value := .productiveFullAndPartialReduplication }
  , { walsCode := "nga", iso := "nio", value := .noProductiveReduplication }
  , { walsCode := "ngk", iso := "nam", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ngw", iso := "nxn", value := .fullReduplicationOnly }
  , { walsCode := "ngi", iso := "wyb", value := .productiveFullAndPartialReduplication }
  , { walsCode := "nia", iso := "nia", value := .productiveFullAndPartialReduplication }
  , { walsCode := "nsn", iso := "nsz", value := .noProductiveReduplication }
  , { walsCode := "niv", iso := "niv", value := .fullReduplicationOnly }
  , { walsCode := "nkr", iso := "nkr", value := .productiveFullAndPartialReduplication }
  , { walsCode := "nug", iso := "nuy", value := .productiveFullAndPartialReduplication }
  , { walsCode := "nuu", iso := "nuk", value := .productiveFullAndPartialReduplication }
  , { walsCode := "nyn", iso := "nyh", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ood", iso := "ood", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ojs", iso := "ojs", value := .productiveFullAndPartialReduplication }
  , { walsCode := "oka", iso := "oka", value := .productiveFullAndPartialReduplication }
  , { walsCode := "olo", iso := "ong", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ond", iso := "one", value := .noProductiveReduplication }
  , { walsCode := "oro", iso := "okv", value := .productiveFullAndPartialReduplication }
  , { walsCode := "orh", iso := "hae", value := .productiveFullAndPartialReduplication }
  , { walsCode := "pkn", iso := "drl", value := .fullReduplicationOnly }
  , { walsCode := "pms", iso := "pma", value := .productiveFullAndPartialReduplication }
  , { walsCode := "pac", iso := "pac", value := .productiveFullAndPartialReduplication }
  , { walsCode := "put", iso := "ute", value := .productiveFullAndPartialReduplication }
  , { walsCode := "pai", iso := "pwn", value := .productiveFullAndPartialReduplication }
  , { walsCode := "pnn", iso := "pag", value := .productiveFullAndPartialReduplication }
  , { walsCode := "pan", iso := "pan", value := .productiveFullAndPartialReduplication }
  , { walsCode := "psh", iso := "pst", value := .productiveFullAndPartialReduplication }
  , { walsCode := "pau", iso := "pad", value := .productiveFullAndPartialReduplication }
  , { walsCode := "pwn", iso := "paw", value := .noProductiveReduplication }
  , { walsCode := "prs", iso := "pes", value := .productiveFullAndPartialReduplication }
  , { walsCode := "pgl", iso := "pif", value := .productiveFullAndPartialReduplication }
  , { walsCode := "pip", iso := "ppl", value := .productiveFullAndPartialReduplication }
  , { walsCode := "prh", iso := "myp", value := .noProductiveReduplication }
  , { walsCode := "ppi", iso := "pit", value := .fullReduplicationOnly }
  , { walsCode := "poh", iso := "pon", value := .productiveFullAndPartialReduplication }
  , { walsCode := "por", iso := "por", value := .noProductiveReduplication }
  , { walsCode := "pul", iso := "puw", value := .productiveFullAndPartialReduplication }
  , { walsCode := "qay", iso := "quy", value := .productiveFullAndPartialReduplication }
  , { walsCode := "qim", iso := "qvi", value := .fullReduplicationOnly }
  , { walsCode := "qui", iso := "qui", value := .productiveFullAndPartialReduplication }
  , { walsCode := "rap", iso := "rap", value := .fullReduplicationOnly }
  , { walsCode := "rmb", iso := "rmb", value := .productiveFullAndPartialReduplication }
  , { walsCode := "rit", iso := "rit", value := .productiveFullAndPartialReduplication }
  , { walsCode := "rot", iso := "rtm", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ruk", iso := "dru", value := .productiveFullAndPartialReduplication }
  , { walsCode := "cos", iso := "", value := .productiveFullAndPartialReduplication }
  , { walsCode := "rnd", iso := "run", value := .productiveFullAndPartialReduplication }
  , { walsCode := "rny", iso := "nyn", value := .productiveFullAndPartialReduplication }
  , { walsCode := "rus", iso := "rus", value := .noProductiveReduplication }
  , { walsCode := "sst", iso := "str", value := .productiveFullAndPartialReduplication }
  , { walsCode := "sam", iso := "smo", value := .productiveFullAndPartialReduplication }
  , { walsCode := "stl", iso := "sat", value := .productiveFullAndPartialReduplication }
  , { walsCode := "swi", iso := "szw", value := .productiveFullAndPartialReduplication }
  , { walsCode := "sed", iso := "sed", value := .productiveFullAndPartialReduplication }
  , { walsCode := "sml", iso := "sza", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ser", iso := "sei", value := .noProductiveReduplication }
  , { walsCode := "ses", iso := "sot", value := .productiveFullAndPartialReduplication }
  , { walsCode := "shu", iso := "shs", value := .productiveFullAndPartialReduplication }
  , { walsCode := "sry", iso := "fos", value := .productiveFullAndPartialReduplication }
  , { walsCode := "srn", iso := "srq", value := .productiveFullAndPartialReduplication }
  , { walsCode := "sro", iso := "ssd", value := .productiveFullAndPartialReduplication }
  , { walsCode := "siu", iso := "sis", value := .productiveFullAndPartialReduplication }
  , { walsCode := "sla", iso := "den", value := .noProductiveReduplication }
  , { walsCode := "som", iso := "som", value := .productiveFullAndPartialReduplication }
  , { walsCode := "spa", iso := "spa", value := .noProductiveReduplication }
  , { walsCode := "spo", iso := "spo", value := .productiveFullAndPartialReduplication }
  , { walsCode := "squ", iso := "squ", value := .productiveFullAndPartialReduplication }
  , { walsCode := "sun", iso := "sun", value := .productiveFullAndPartialReduplication }
  , { walsCode := "swa", iso := "swh", value := .productiveFullAndPartialReduplication }
  , { walsCode := "swt", iso := "ssw", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tag", iso := "tgl", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tml", iso := "tam", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tnc", iso := "tcb", value := .noProductiveReduplication }
  , { walsCode := "tsg", iso := "tsg", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tmr", iso := "tea", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tps", iso := "stp", value := .fullReduplicationOnly }
  , { walsCode := "tha", iso := "tha", value := .productiveFullAndPartialReduplication }
  , { walsCode := "thw", iso := "ssf", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tho", iso := "thp", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tid", iso := "tvo", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tgk", iso := "tgc", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tig", iso := "tir", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tgr", iso := "tig", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tja", iso := "dih", value := .productiveFullAndPartialReduplication }
  , { walsCode := "til", iso := "til", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tim", iso := "tih", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tin", iso := "cir", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tiw", iso := "tiw", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tlp", iso := "tcf", value := .productiveFullAndPartialReduplication }
  , { walsCode := "toj", iso := "toj", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tng", iso := "ton", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tot", iso := "tlc", value := .noProductiveReduplication }
  , { walsCode := "tru", iso := "tpy", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tsi", iso := "tsi", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tso", iso := "tsu", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tsw", iso := "tsn", value := .fullReduplicationOnly }
  , { walsCode := "tuk", iso := "", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tur", iso := "tur", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tkm", iso := "tuk", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tuv", iso := "tyv", value := .productiveFullAndPartialReduplication }
  , { walsCode := "twa", iso := "twa", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tze", iso := "tzh", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tzo", iso := "tzo", value := .productiveFullAndPartialReduplication }
  , { walsCode := "tbb", iso := "tub", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ung", iso := "ung", value := .productiveFullAndPartialReduplication }
  , { walsCode := "uhi", iso := "urf", value := .productiveFullAndPartialReduplication }
  , { walsCode := "uyg", iso := "uig", value := .productiveFullAndPartialReduplication }
  , { walsCode := "vie", iso := "vie", value := .productiveFullAndPartialReduplication }
  , { walsCode := "wap", iso := "wao", value := .noProductiveReduplication }
  , { walsCode := "wry", iso := "wrz", value := .productiveFullAndPartialReduplication }
  , { walsCode := "wwy", iso := "war", value := .productiveFullAndPartialReduplication }
  , { walsCode := "wrd", iso := "wrr", value := .productiveFullAndPartialReduplication }
  , { walsCode := "wrk", iso := "gae", value := .productiveFullAndPartialReduplication }
  , { walsCode := "war", iso := "pav", value := .productiveFullAndPartialReduplication }
  , { walsCode := "wrl", iso := "wbp", value := .productiveFullAndPartialReduplication }
  , { walsCode := "was", iso := "was", value := .productiveFullAndPartialReduplication }
  , { walsCode := "wsk", iso := "wsk", value := .productiveFullAndPartialReduplication }
  , { walsCode := "wat", iso := "wbv", value := .productiveFullAndPartialReduplication }
  , { walsCode := "wel", iso := "cym", value := .noProductiveReduplication }
  , { walsCode := "wic", iso := "wic", value := .noProductiveReduplication }
  , { walsCode := "wch", iso := "mzh", value := .noProductiveReduplication }
  , { walsCode := "wmu", iso := "wim", value := .productiveFullAndPartialReduplication }
  , { walsCode := "wik", iso := "yok", value := .productiveFullAndPartialReduplication }
  , { walsCode := "wlf", iso := "wol", value := .fullReduplicationOnly }
  , { walsCode := "xav", iso := "xav", value := .noProductiveReduplication }
  , { walsCode := "xho", iso := "xho", value := .productiveFullAndPartialReduplication }
  , { walsCode := "yag", iso := "yad", value := .noProductiveReduplication }
  , { walsCode := "yan", iso := "ynn", value := .noProductiveReduplication }
  , { walsCode := "ynk", iso := "kdd", value := .fullReduplicationOnly }
  , { walsCode := "yny", iso := "jao", value := .productiveFullAndPartialReduplication }
  , { walsCode := "yaq", iso := "yaq", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ywl", iso := "yok", value := .productiveFullAndPartialReduplication }
  , { walsCode := "yid", iso := "yii", value := .productiveFullAndPartialReduplication }
  , { walsCode := "yim", iso := "yee", value := .productiveFullAndPartialReduplication }
  , { walsCode := "yin", iso := "yij", value := .productiveFullAndPartialReduplication }
  , { walsCode := "yir", iso := "yyr", value := .productiveFullAndPartialReduplication }
  , { walsCode := "yor", iso := "yor", value := .productiveFullAndPartialReduplication }
  , { walsCode := "yct", iso := "yua", value := .productiveFullAndPartialReduplication }
  , { walsCode := "yuc", iso := "yuc", value := .productiveFullAndPartialReduplication }
  , { walsCode := "yko", iso := "yux", value := .noProductiveReduplication }
  , { walsCode := "yuk", iso := "gcd", value := .productiveFullAndPartialReduplication }
  , { walsCode := "ypk", iso := "esu", value := .noProductiveReduplication }
  , { walsCode := "yur", iso := "yur", value := .productiveFullAndPartialReduplication }
  , { walsCode := "zhn", iso := "zgb", value := .fullReduplicationOnly }
  , { walsCode := "zul", iso := "zul", value := .fullReduplicationOnly }
  , { walsCode := "zun", iso := "zun", value := .noProductiveReduplication }
  ]

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F27A
