import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 33A: Coding of Nominal Plurality
@cite{haspelmath-2013b}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 33A`.

Chapter 33, 1066 languages.
-/

namespace Core.WALS.F33A

/-- WALS 33A values. -/
inductive PluralityCoding where
  /-- Plural prefix (126 languages). -/
  | pluralPrefix
  /-- Plural suffix (513 languages). -/
  | pluralSuffix
  /-- Plural stem change (6 languages). -/
  | pluralStemChange
  /-- Plural tone (4 languages). -/
  | pluralTone
  /-- Plural complete reduplication (8 languages). -/
  | pluralCompleteReduplication
  /-- Mixed morphological plural (60 languages). -/
  | mixedMorphologicalPlural
  /-- Plural word (170 languages). -/
  | pluralWord
  /-- Plural clitic (81 languages). -/
  | pluralClitic
  /-- No plural (98 languages). -/
  | noPlural
  deriving DecidableEq, BEq, Repr

private def allData_0 : List (Datapoint PluralityCoding) :=
  [ { walsCode := "xoo", iso := "nmn", value := .pluralSuffix }
  , { walsCode := "aar", iso := "aiw", value := .noPlural }
  , { walsCode := "abi", iso := "axb", value := .pluralSuffix }
  , { walsCode := "abk", iso := "abk", value := .pluralSuffix }
  , { walsCode := "abv", iso := "abz", value := .pluralWord }
  , { walsCode := "abu", iso := "kgr", value := .noPlural }
  , { walsCode := "ace", iso := "ace", value := .noPlural }
  , { walsCode := "acg", iso := "aca", value := .pluralSuffix }
  , { walsCode := "acl", iso := "ach", value := .mixedMorphologicalPlural }
  , { walsCode := "aco", iso := "kjq", value := .pluralSuffix }
  , { walsCode := "adg", iso := "adn", value := .noPlural }
  , { walsCode := "adi", iso := "adj", value := .pluralPrefix }
  , { walsCode := "agc", iso := "agt", value := .pluralWord }
  , { walsCode := "agd", iso := "duo", value := .pluralWord }
  , { walsCode := "ain", iso := "ain", value := .pluralSuffix }
  , { walsCode := "ajg", iso := "ajg", value := .pluralClitic }
  , { walsCode := "akn", iso := "aka", value := .mixedMorphologicalPlural }
  , { walsCode := "ala", iso := "amp", value := .pluralClitic }
  , { walsCode := "alw", iso := "alh", value := .pluralPrefix }
  , { walsCode := "alb", iso := "sqi", value := .pluralSuffix }
  , { walsCode := "ale", iso := "ale", value := .pluralSuffix }
  , { walsCode := "aln", iso := "alp", value := .pluralSuffix }
  , { walsCode := "aly", iso := "aly", value := .noPlural }
  , { walsCode := "amn", iso := "amn", value := .noPlural }
  , { walsCode := "aml", iso := "omb", value := .pluralWord }
  , { walsCode := "amq", iso := "amk", value := .pluralClitic }
  , { walsCode := "ame", iso := "aey", value := .mixedMorphologicalPlural }
  , { walsCode := "amh", iso := "amh", value := .pluralSuffix }
  , { walsCode := "amo", iso := "amo", value := .pluralPrefix }
  , { walsCode := "amx", iso := "imi", value := .pluralSuffix }
  , { walsCode := "anj", iso := "aty", value := .pluralPrefix }
  , { walsCode := "agm", iso := "njm", value := .pluralClitic }
  , { walsCode := "anc", iso := "anc", value := .pluralWord }
  , { walsCode := "agt", iso := "awg", value := .pluralSuffix }
  , { walsCode := "ann", iso := "aoi", value := .pluralPrefix }
  , { walsCode := "anu", iso := "cko", value := .pluralClitic }
  , { walsCode := "ayi", iso := "any", value := .pluralPrefix }
  , { walsCode := "any", iso := "anu", value := .pluralSuffix }
  , { walsCode := "ao", iso := "njo", value := .pluralSuffix }
  , { walsCode := "apl", iso := "apy", value := .pluralWord }
  , { walsCode := "apt", iso := "apt", value := .pluralWord }
  , { walsCode := "api", iso := "apn", value := .pluralWord }
  , { walsCode := "apu", iso := "apu", value := .pluralSuffix }
  , { walsCode := "abn", iso := "ard", value := .pluralSuffix }
  , { walsCode := "aeg", iso := "arz", value := .mixedMorphologicalPlural }
  , { walsCode := "arg", iso := "afb", value := .mixedMorphologicalPlural }
  , { walsCode := "arq", iso := "acm", value := .mixedMorphologicalPlural }
  , { walsCode := "arj", iso := "afb", value := .mixedMorphologicalPlural }
  , { walsCode := "amr", iso := "ary", value := .mixedMorphologicalPlural }
  , { walsCode := "asy", iso := "apc", value := .mixedMorphologicalPlural }
  , { walsCode := "ana", iso := "aro", value := .pluralWord }
  , { walsCode := "arp", iso := "ape", value := .pluralSuffix }
  , { walsCode := "arc", iso := "aqc", value := .pluralSuffix }
  , { walsCode := "arm", iso := "hye", value := .pluralSuffix }
  , { walsCode := "arw", iso := "hyw", value := .pluralSuffix }
  , { walsCode := "alk", iso := "apr", value := .pluralWord }
  , { walsCode := "aro", iso := "aia", value := .pluralWord }
  , { walsCode := "amp", iso := "aer", value := .noPlural }
  , { walsCode := "awe", iso := "are", value := .pluralSuffix }
  , { walsCode := "asm", iso := "cns", value := .pluralSuffix }
  , { walsCode := "ath", iso := "aph", value := .pluralSuffix }
  , { walsCode := "ava", iso := "ava", value := .pluralSuffix }
  , { walsCode := "avk", iso := "avi", value := .pluralWord }
  , { walsCode := "avo", iso := "avu", value := .pluralSuffix }
  , { walsCode := "awa", iso := "awb", value := .pluralSuffix }
  , { walsCode := "awp", iso := "kwi", value := .pluralSuffix }
  , { walsCode := "awt", iso := "kmn", value := .pluralSuffix }
  , { walsCode := "aym", iso := "ayr", value := .pluralSuffix }
  , { walsCode := "azi", iso := "azb", value := .pluralSuffix }
  , { walsCode := "aze", iso := "", value := .pluralSuffix }
  , { walsCode := "bdm", iso := "bia", value := .pluralSuffix }
  , { walsCode := "bfi", iso := "ksf", value := .pluralPrefix }
  , { walsCode := "bag", iso := "bmi", value := .pluralClitic }
  , { walsCode := "bgr", iso := "fuu", value := .pluralWord }
  , { walsCode := "bai", iso := "bca", value := .pluralWord }
  , { walsCode := "bwc", iso := "bdr", value := .pluralWord }
  , { walsCode := "bak", iso := "bkc", value := .pluralClitic }
  , { walsCode := "bka", iso := "bdh", value := .pluralClitic }
  , { walsCode := "bku", iso := "bri", value := .pluralPrefix }
  , { walsCode := "blg", iso := "blw", value := .pluralPrefix }
  , { walsCode := "bvi", iso := "", value := .pluralWord }
  , { walsCode := "blt", iso := "bft", value := .pluralSuffix }
  , { walsCode := "bam", iso := "bam", value := .pluralSuffix }
  , { walsCode := "bnk", iso := "abb", value := .pluralPrefix }
  , { walsCode := "bnn", iso := "bcm", value := .pluralWord }
  , { walsCode := "bao", iso := "peh", value := .pluralClitic }
  , { walsCode := "baa", iso := "bbb", value := .pluralSuffix }
  , { walsCode := "bbu", iso := "brm", value := .pluralPrefix }
  , { walsCode := "brs", iso := "bsn", value := .pluralSuffix }
  , { walsCode := "bar", iso := "bfa", value := .pluralSuffix }
  , { walsCode := "brp", iso := "bpe", value := .noPlural }
  , { walsCode := "bry", iso := "byr", value := .pluralClitic }
  , { walsCode := "bae", iso := "bae", value := .pluralSuffix }
  , { walsCode := "bas", iso := "bas", value := .pluralPrefix }
  , { walsCode := "bsk", iso := "bak", value := .pluralSuffix }
  , { walsCode := "bsq", iso := "eus", value := .pluralClitic }
  , { walsCode := "bkr", iso := "btx", value := .pluralCompleteReduplication }
  , { walsCode := "bto", iso := "bbc", value := .pluralWord }
  , { walsCode := "baq", iso := "brg", value := .pluralSuffix }
  , { walsCode := "baw", iso := "bgr", value := .pluralWord }
  , { walsCode := "bej", iso := "bej", value := .pluralSuffix }
  , { walsCode := "bco", iso := "blc", value := .pluralPrefix }
  , { walsCode := "blu", iso := "lua", value := .pluralPrefix }
  , { walsCode := "bga", iso := "bng", value := .pluralPrefix }
  , { walsCode := "bfg", iso := "grr", value := .mixedMorphologicalPlural }
  , { walsCode := "bma", iso := "tzm", value := .mixedMorphologicalPlural }
  , { walsCode := "bmz", iso := "mzb", value := .pluralSuffix }
  , { walsCode := "brf", iso := "rif", value := .mixedMorphologicalPlural }
  , { walsCode := "bsi", iso := "siz", value := .mixedMorphologicalPlural }
  , { walsCode := "zag", iso := "zag", value := .pluralTone }
  , { walsCode := "ber", iso := "wti", value := .mixedMorphologicalPlural }
  , { walsCode := "bti", iso := "", value := .pluralSuffix }
  , { walsCode := "bkb", iso := "xub", value := .pluralSuffix }
  , { walsCode := "bho", iso := "bho", value := .pluralSuffix }
  , { walsCode := "bik", iso := "bhw", value := .pluralClitic }
  , { walsCode := "bid", iso := "bid", value := .pluralSuffix }
  , { walsCode := "bkl", iso := "bcl", value := .pluralWord }
  , { walsCode := "bln", iso := "byn", value := .pluralSuffix }
  , { walsCode := "blx", iso := "bll", value := .noPlural }
  , { walsCode := "bil", iso := "blb", value := .pluralWord }
  , { walsCode := "bin", iso := "bhg", value := .mixedMorphologicalPlural }
  , { walsCode := "big", iso := "yul", value := .pluralSuffix }
  , { walsCode := "bni", iso := "bin", value := .noPlural }
  , { walsCode := "bbw", iso := "gup", value := .pluralPrefix }
  , { walsCode := "bii", iso := "bzr", value := .noPlural }
  , { walsCode := "bir", iso := "bom", value := .pluralPrefix }
  , { walsCode := "bla", iso := "bla", value := .pluralSuffix }
  , { walsCode := "bob", iso := "bni", value := .pluralPrefix }
  , { walsCode := "bbf", iso := "bbo", value := .pluralClitic }
  , { walsCode := "bod", iso := "brx", value := .pluralSuffix }
  , { walsCode := "bgo", iso := "bot", value := .pluralClitic }
  , { walsCode := "btk", iso := "lbk", value := .pluralPrefix }
  , { walsCode := "brh", iso := "brh", value := .pluralSuffix }
  , { walsCode := "bre", iso := "bre", value := .pluralSuffix }
  , { walsCode := "bri", iso := "bzd", value := .pluralSuffix }
  , { walsCode := "bdu", iso := "buu", value := .pluralPrefix }
  , { walsCode := "bud", iso := "bdm", value := .pluralSuffix }
  , { walsCode := "bgn", iso := "bgg", value := .pluralSuffix }
  , { walsCode := "bun", iso := "buo", value := .pluralSuffix }
  , { walsCode := "bnu", iso := "", value := .pluralSuffix }
  , { walsCode := "bul", iso := "bul", value := .pluralSuffix }
  , { walsCode := "pnu", iso := "buh", value := .noPlural }
  , { walsCode := "bnb", iso := "bck", value := .pluralClitic }
  , { walsCode := "but", iso := "bxm", value := .pluralSuffix }
  , { walsCode := "brm", iso := "mya", value := .pluralWord }
  , { walsCode := "brn", iso := "bds", value := .pluralSuffix }
  , { walsCode := "bur", iso := "bsk", value := .pluralSuffix }
  , { walsCode := "bus", iso := "bqp", value := .pluralClitic }
  , { walsCode := "bsh", iso := "buf", value := .pluralPrefix }
  , { walsCode := "bya", iso := "bee", value := .pluralSuffix }
  , { walsCode := "cah", iso := "chl", value := .pluralSuffix }
  , { walsCode := "cak", iso := "cak", value := .mixedMorphologicalPlural }
  , { walsCode := "cax", iso := "", value := .pluralSuffix }
  , { walsCode := "cam", iso := "kbh", value := .pluralSuffix }
  , { walsCode := "cnm", iso := "knm", value := .pluralWord }
  , { walsCode := "cnl", iso := "ram", value := .noPlural }
  , { walsCode := "cnt", iso := "yue", value := .noPlural }
  , { walsCode := "crp", iso := "cbc", value := .pluralSuffix }
  , { walsCode := "car", iso := "car", value := .pluralSuffix }
  , { walsCode := "cde", iso := "mch", value := .pluralSuffix }
  , { walsCode := "cas", iso := "cbr", value := .pluralSuffix }
  , { walsCode := "cav", iso := "cav", value := .pluralClitic }
  , { walsCode := "cyv", iso := "cyb", value := .pluralClitic }
  , { walsCode := "chh", iso := "sgw", value := .noPlural }
  , { walsCode := "cai", iso := "suq", value := .pluralSuffix }
  , { walsCode := "cld", iso := "cld", value := .pluralSuffix }
  , { walsCode := "chb", iso := "can", value := .pluralSuffix }
  , { walsCode := "cha", iso := "cha", value := .pluralWord }
  , { walsCode := "chg", iso := "nbc", value := .pluralSuffix }
  , { walsCode := "chn", iso := "chx", value := .pluralSuffix }
  , { walsCode := "cso", iso := "ctp", value := .noPlural }
  , { walsCode := "cya", iso := "ctp", value := .noPlural }
  , { walsCode := "chc", iso := "che", value := .pluralSuffix }
  , { walsCode := "cmh", iso := "ute", value := .pluralSuffix }
  , { walsCode := "che", iso := "chr", value := .pluralPrefix }
  , { walsCode := "cic", iso := "nya", value := .pluralPrefix }
  , { walsCode := "chi", iso := "cid", value := .noPlural }
  , { walsCode := "cmr", iso := "mrh", value := .pluralWord }
  , { walsCode := "chs", iso := "csy", value := .pluralSuffix }
  , { walsCode := "cti", iso := "ctd", value := .noPlural }
  , { walsCode := "ccm", iso := "cco", value := .pluralWord }
  , { walsCode := "cle", iso := "cle", value := .pluralWord }
  , { walsCode := "cpl", iso := "cpa", value := .noPlural }
  , { walsCode := "chq", iso := "chq", value := .noPlural }
  , { walsCode := "ckl", iso := "chh", value := .pluralSuffix }
  , { walsCode := "cpy", iso := "cap", value := .pluralSuffix }
  , { walsCode := "cqt", iso := "cax", value := .pluralSuffix }
  , { walsCode := "ctm", iso := "ctm", value := .pluralSuffix }
  , { walsCode := "cct", iso := "cho", value := .noPlural }
  , { walsCode := "cln", iso := "cht", value := .pluralSuffix }
  , { walsCode := "chx", iso := "clo", value := .pluralSuffix }
  , { walsCode := "cmy", iso := "chf", value := .pluralSuffix }
  , { walsCode := "chr", iso := "crw", value := .noPlural }
  , { walsCode := "chk", iso := "ckt", value := .pluralSuffix }
  , { walsCode := "chv", iso := "chv", value := .pluralSuffix }
  , { walsCode := "cbo", iso := "cao", value := .pluralWord }
  , { walsCode := "coc", iso := "cod", value := .pluralSuffix }
  , { walsCode := "coe", iso := "crd", value := .pluralWord }
  , { walsCode := "cmn", iso := "com", value := .pluralSuffix }
  , { walsCode := "coo", iso := "csz", value := .mixedMorphologicalPlural }
  , { walsCode := "cop", iso := "cop", value := .noPlural }
  , { walsCode := "crn", iso := "cor", value := .pluralSuffix }
  , { walsCode := "cre", iso := "crk", value := .pluralSuffix }
  , { walsCode := "cro", iso := "cro", value := .pluralSuffix }
  , { walsCode := "cup", iso := "cup", value := .pluralSuffix }
  , { walsCode := "cze", iso := "ces", value := .pluralSuffix }
  , { walsCode := "cem", iso := "cam", value := .pluralWord }
  , { walsCode := "dgb", iso := "dag", value := .pluralSuffix }
  , { walsCode := "dan", iso := "dnj", value := .pluralWord }
  , { walsCode := "dsh", iso := "dan", value := .pluralSuffix }
  , { walsCode := "drg", iso := "dar", value := .pluralSuffix }
  , { walsCode := "drm", iso := "drd", value := .pluralWord }
  , { walsCode := "day", iso := "dai", value := .pluralWord }
  , { walsCode := "des", iso := "des", value := .pluralSuffix }
  , { walsCode := "deu", iso := "der", value := .pluralSuffix }
  , { walsCode := "dhw", iso := "tbh", value := .pluralSuffix }
  , { walsCode := "dhr", iso := "dhr", value := .pluralSuffix }
  , { walsCode := "did", iso := "did", value := .pluralSuffix }
  , { walsCode := "die", iso := "dih", value := .noPlural }
  , { walsCode := "dms", iso := "dis", value := .pluralSuffix }
  , { walsCode := "dim", iso := "dim", value := .pluralClitic }
  , { walsCode := "din", iso := "din", value := .pluralStemChange }
  , { walsCode := "dio", iso := "dyo", value := .pluralPrefix }
  , { walsCode := "djp", iso := "dwu", value := .pluralWord }
  , { walsCode := "djr", iso := "ddj", value := .pluralCompleteReduplication }
  , { walsCode := "djn", iso := "dji", value := .pluralSuffix }
  , { walsCode := "dji", iso := "jig", value := .pluralSuffix }
  , { walsCode := "dmk", iso := "dmk", value := .pluralSuffix }
  , { walsCode := "dom", iso := "rmt", value := .pluralSuffix }
  , { walsCode := "don", iso := "kmc", value := .noPlural }
  , { walsCode := "dgo", iso := "doo", value := .pluralSuffix }
  , { walsCode := "dds", iso := "dds", value := .pluralClitic }
  , { walsCode := "doy", iso := "dow", value := .pluralSuffix }
  , { walsCode := "dre", iso := "dhv", value := .pluralWord }
  , { walsCode := "dul", iso := "duu", value := .pluralWord }
  , { walsCode := "dun", iso := "duc", value := .pluralClitic }
  , { walsCode := "dut", iso := "nld", value := .pluralSuffix }
  , { walsCode := "daw", iso := "kwa", value := .pluralClitic }
  , { walsCode := "eip", iso := "eip", value := .pluralSuffix }
  , { walsCode := "emb", iso := "emp", value := .pluralSuffix }
  , { walsCode := "ene", iso := "", value := .pluralSuffix }
  , { walsCode := "egn", iso := "enn", value := .noPlural }
  , { walsCode := "eno", iso := "eno", value := .pluralPrefix }
  , { walsCode := "eng", iso := "eng", value := .pluralSuffix }
  , { walsCode := "eny", iso := "gey", value := .pluralPrefix }
  , { walsCode := "epe", iso := "sja", value := .pluralClitic }
  , { walsCode := "err", iso := "erg", value := .pluralWord }
  , { walsCode := "ese", iso := "ese", value := .pluralWord }
  , { walsCode := "est", iso := "ekk", value := .pluralSuffix }
  , { walsCode := "eud", iso := "", value := .pluralPrefix }
  , { walsCode := "evn", iso := "eve", value := .pluralSuffix }
  , { walsCode := "eve", iso := "evn", value := .pluralSuffix }
  , { walsCode := "ewe", iso := "ewe", value := .pluralClitic }
  , { walsCode := "ewo", iso := "ewo", value := .pluralPrefix }
  , { walsCode := "fin", iso := "fin", value := .pluralSuffix }
  , { walsCode := "pdp", iso := "ppo", value := .pluralSuffix }
  , { walsCode := "fon", iso := "fon", value := .pluralWord }
  , { walsCode := "for", iso := "for", value := .pluralSuffix }
  , { walsCode := "fre", iso := "fra", value := .pluralSuffix }
  , { walsCode := "fua", iso := "fub", value := .pluralSuffix }
  , { walsCode := "ful", iso := "fun", value := .pluralSuffix }
  , { walsCode := "fur", iso := "fvr", value := .mixedMorphologicalPlural }
  , { walsCode := "fut", iso := "fut", value := .pluralWord }
  , { walsCode := "fye", iso := "pym", value := .pluralPrefix }
  , { walsCode := "gnd", iso := "gqa", value := .pluralSuffix }
  , { walsCode := "gds", iso := "gaj", value := .pluralSuffix }
  , { walsCode := "gae", iso := "gla", value := .mixedMorphologicalPlural }
  , { walsCode := "gah", iso := "gah", value := .pluralSuffix }
  , { walsCode := "gal", iso := "adl", value := .pluralSuffix }
  , { walsCode := "gam", iso := "gmv", value := .pluralSuffix }
  , { walsCode := "gar", iso := "grt", value := .pluralClitic }
  , { walsCode := "grf", iso := "cab", value := .pluralSuffix }
  , { walsCode := "gbs", iso := "gso", value := .pluralPrefix }
  , { walsCode := "gbb", iso := "gbp", value := .pluralWord }
  , { walsCode := "gel", iso := "nlg", value := .pluralWord }
  , { walsCode := "geo", iso := "kat", value := .pluralSuffix }
  , { walsCode := "ger", iso := "deu", value := .pluralSuffix }
  , { walsCode := "gil", iso := "glk", value := .pluralSuffix }
  , { walsCode := "gim", iso := "bcq", value := .pluralSuffix }
  , { walsCode := "git", iso := "git", value := .pluralPrefix }
  , { walsCode := "giz", iso := "gis", value := .pluralWord }
  , { walsCode := "goa", iso := "guc", value := .pluralSuffix }
  , { walsCode := "god", iso := "gdo", value := .pluralSuffix }
  , { walsCode := "goe", iso := "ank", value := .pluralWord }
  , { walsCode := "gok", iso := "gkn", value := .pluralWord }
  , { walsCode := "gln", iso := "gvf", value := .pluralWord }
  , { walsCode := "gon", iso := "gno", value := .pluralSuffix }
  , { walsCode := "goo", iso := "gni", value := .pluralClitic }
  , { walsCode := "grb", iso := "grj", value := .pluralSuffix }
  , { walsCode := "grk", iso := "ell", value := .pluralSuffix }
  , { walsCode := "grw", iso := "kal", value := .pluralSuffix }
  , { walsCode := "gua", iso := "gug", value := .pluralWord }
  , { walsCode := "gud", iso := "gde", value := .pluralSuffix }
  , { walsCode := "guh", iso := "ghs", value := .pluralSuffix }
  , { walsCode := "gul", iso := "kcm", value := .pluralWord }
  , { walsCode := "gmw", iso := "gvs", value := .pluralSuffix }
  , { walsCode := "gum", iso := "kgs", value := .pluralSuffix }
  , { walsCode := "gnn", iso := "gww", value := .noPlural }
  , { walsCode := "ggu", iso := "gnr", value := .pluralSuffix }
  , { walsCode := "gur", iso := "", value := .pluralWord }
  , { walsCode := "guu", iso := "kky", value := .pluralSuffix }
  , { walsCode := "gwo", iso := "kcg", value := .pluralTone }
  , { walsCode := "gyc", iso := "jya", value := .pluralSuffix }
  , { walsCode := "ga", iso := "gaa", value := .pluralSuffix }
  , { walsCode := "gku", iso := "pue", value := .noPlural }
  , { walsCode := "hai", iso := "hai", value := .pluralSuffix }
  , { walsCode := "hal", iso := "hla", value := .pluralWord }
  , { walsCode := "hhu", iso := "wos", value := .pluralSuffix }
  , { walsCode := "hat", iso := "had", value := .pluralClitic }
  , { walsCode := "hau", iso := "hau", value := .pluralSuffix }
  , { walsCode := "haw", iso := "haw", value := .pluralWord }
  , { walsCode := "hya", iso := "hay", value := .pluralPrefix }
  , { walsCode := "hay", iso := "vay", value := .pluralSuffix }
  , { walsCode := "hdi", iso := "xed", value := .pluralSuffix }
  , { walsCode := "heb", iso := "heb", value := .pluralSuffix }
  , { walsCode := "hem", iso := "hem", value := .pluralPrefix }
  , { walsCode := "hid", iso := "hid", value := .pluralSuffix }
  , { walsCode := "hin", iso := "hin", value := .pluralSuffix }
  , { walsCode := "hix", iso := "hix", value := .pluralWord }
  , { walsCode := "hma", iso := "hmr", value := .pluralSuffix }
  , { walsCode := "ho", iso := "hoc", value := .pluralSuffix }
  , { walsCode := "hoa", iso := "hoa", value := .pluralWord }
  , { walsCode := "hop", iso := "hop", value := .pluralSuffix }
  , { walsCode := "hlp", iso := "yuf", value := .pluralSuffix }
  , { walsCode := "htc", iso := "hus", value := .pluralSuffix }
  , { walsCode := "hve", iso := "huv", value := .pluralPrefix }
  , { walsCode := "hui", iso := "hch", value := .pluralSuffix }
  , { walsCode := "hmi", iso := "hto", value := .pluralSuffix }
  , { walsCode := "hum", iso := "huu", value := .pluralSuffix }
  , { walsCode := "hnd", iso := "hke", value := .pluralPrefix }
  , { walsCode := "hun", iso := "hun", value := .pluralSuffix }
  , { walsCode := "hzb", iso := "huz", value := .pluralSuffix }
  , { walsCode := "hpd", iso := "jup", value := .pluralClitic }
  , { walsCode := "hup", iso := "hup", value := .noPlural }
  , { walsCode := "isa", iso := "ksi", value := .noPlural }
  , { walsCode := "iaa", iso := "iai", value := .pluralWord }
  , { walsCode := "iba", iso := "iba", value := .noPlural }
  , { walsCode := "ice", iso := "isl", value := .pluralSuffix }
  , { walsCode := "idn", iso := "viv", value := .pluralSuffix }
  , { walsCode := "ifm", iso := "ifm", value := .pluralPrefix }
  , { walsCode := "igb", iso := "ibo", value := .mixedMorphologicalPlural }
  , { walsCode := "ign", iso := "ign", value := .pluralSuffix }
  , { walsCode := "iha", iso := "ihp", value := .mixedMorphologicalPlural }
  , { walsCode := "ijo", iso := "ijc", value := .pluralSuffix }
  , { walsCode := "ik", iso := "ikx", value := .pluralSuffix }
  , { walsCode := "ika", iso := "arh", value := .pluralWord }
  , { walsCode := "ila", iso := "ilb", value := .pluralPrefix }
  , { walsCode := "imo", iso := "imn", value := .noPlural }
  , { walsCode := "ina", iso := "szp", value := .pluralSuffix }
  , { walsCode := "ind", iso := "ind", value := .pluralCompleteReduplication }
  , { walsCode := "igs", iso := "tbi", value := .pluralSuffix }
  , { walsCode := "ing", iso := "inh", value := .pluralSuffix }
  , { walsCode := "inn", iso := "ynd", value := .pluralSuffix }
  , { walsCode := "irx", iso := "irn", value := .noPlural }
  , { walsCode := "irq", iso := "irk", value := .pluralSuffix }
  , { walsCode := "iri", iso := "gle", value := .mixedMorphologicalPlural }
  , { walsCode := "ita", iso := "ita", value := .pluralSuffix }
  , { walsCode := "ite", iso := "itl", value := .pluralSuffix }
  , { walsCode := "ito", iso := "ito", value := .pluralSuffix }
  , { walsCode := "kwy", iso := "yom", value := .pluralPrefix }
  , { walsCode := "jar", iso := "izr", value := .pluralPrefix }
  , { walsCode := "izi", iso := "izz", value := .noPlural }
  , { walsCode := "jak", iso := "jac", value := .pluralWord }
  , { walsCode := "jms", iso := "djm", value := .mixedMorphologicalPlural }
  , { walsCode := "jpn", iso := "jpn", value := .pluralSuffix }
  , { walsCode := "jaq", iso := "jqr", value := .pluralSuffix }
  , { walsCode := "jeb", iso := "jeb", value := .pluralSuffix }
  , { walsCode := "jel", iso := "jek", value := .pluralClitic }
  , { walsCode := "jng", iso := "kac", value := .pluralWord }
  , { walsCode := "jiv", iso := "jiv", value := .pluralSuffix }
  , { walsCode := "jug", iso := "nst", value := .pluralSuffix }
  , { walsCode := "juk", iso := "jbu", value := .pluralPrefix }
  , { walsCode := "jmo", iso := "bex", value := .pluralWord }
  , { walsCode := "juh", iso := "ktz", value := .pluralClitic }
  , { walsCode := "kab", iso := "kbd", value := .pluralSuffix }
  , { walsCode := "kac", iso := "xac", value := .pluralSuffix }
  , { walsCode := "kdw", iso := "kbc", value := .pluralSuffix }
  , { walsCode := "kad", iso := "xtc", value := .pluralPrefix }
  , { walsCode := "kgr", iso := "kki", value := .pluralPrefix }
  , { walsCode := "kai", iso := "kct", value := .pluralSuffix }
  , { walsCode := "krr", iso := "kxa", value := .pluralWord }
  , { walsCode := "kmk", iso := "xal", value := .pluralSuffix }
  , { walsCode := "kma", iso := "kay", value := .pluralSuffix }
  , { walsCode := "kmz", iso := "kms", value := .noPlural }
  , { walsCode := "kms", iso := "xas", value := .pluralSuffix }
  , { walsCode := "kba", iso := "kam", value := .pluralPrefix }
  , { walsCode := "kan", iso := "ogo", value := .pluralWord }
  , { walsCode := "knk", iso := "kna", value := .pluralSuffix }
  , { walsCode := "kbu", iso := "kbl", value := .pluralSuffix }
  , { walsCode := "knd", iso := "kan", value := .pluralSuffix }
  , { walsCode := "knr", iso := "knc", value := .pluralSuffix }
  , { walsCode := "kyo", iso := "kny", value := .pluralPrefix }
  , { walsCode := "kar", iso := "kah", value := .pluralClitic }
  , { walsCode := "krc", iso := "krc", value := .pluralSuffix }
  , { walsCode := "jva", iso := "kpj", value := .pluralSuffix }
  , { walsCode := "kkp", iso := "kaa", value := .pluralSuffix }
  , { walsCode := "kbw", iso := "bwe", value := .noPlural }
  , { walsCode := "ksg", iso := "ksw", value := .pluralWord }
  , { walsCode := "kmj", iso := "kdj", value := .pluralPrefix }
  , { walsCode := "krk", iso := "kyh", value := .pluralSuffix }
  , { walsCode := "kaa", iso := "arr", value := .pluralClitic }
  , { walsCode := "ktc", iso := "xtc", value := .pluralPrefix }
  , { walsCode := "ktm", iso := "", value := .mixedMorphologicalPlural }
  , { walsCode := "ktl", iso := "kcr", value := .pluralPrefix }
  , { walsCode := "kws", iso := "xaw", value := .pluralSuffix }
  , { walsCode := "kyz", iso := "kyz", value := .noPlural }
  , { walsCode := "kyl", iso := "eky", value := .noPlural }
  , { walsCode := "kay", iso := "gyd", value := .noPlural }
  , { walsCode := "kel", iso := "sbc", value := .noPlural }
  , { walsCode := "kem", iso := "ahg", value := .pluralSuffix }
  , { walsCode := "ken", iso := "kyq", value := .pluralClitic }
  , { walsCode := "ker", iso := "ker", value := .pluralPrefix }
  , { walsCode := "ksa", iso := "kee", value := .pluralClitic }
  , { walsCode := "ket", iso := "ket", value := .pluralSuffix }
  , { walsCode := "kew", iso := "kew", value := .pluralSuffix }
  , { walsCode := "khl", iso := "klj", value := .pluralSuffix }
  , { walsCode := "khg", iso := "klr", value := .pluralSuffix }
  , { walsCode := "kha", iso := "khk", value := .mixedMorphologicalPlural }
  , { walsCode := "kmh", iso := "kjl", value := .pluralSuffix }
  , { walsCode := "khd", iso := "khg", value := .pluralClitic }
  , { walsCode := "kty", iso := "kca", value := .pluralSuffix }
  , { walsCode := "khr", iso := "khr", value := .pluralClitic }
  , { walsCode := "khs", iso := "kha", value := .pluralWord }
  , { walsCode := "khi", iso := "kjj", value := .pluralSuffix }
  , { walsCode := "khm", iso := "khm", value := .pluralWord }
  , { walsCode := "kmu", iso := "kjg", value := .noPlural }
  , { walsCode := "kik", iso := "kik", value := .pluralPrefix }
  , { walsCode := "klv", iso := "kij", value := .mixedMorphologicalPlural }
  , { walsCode := "klw", iso := "klb", value := .pluralSuffix }
  , { walsCode := "kim", iso := "kig", value := .pluralWord }
  , { walsCode := "kga", iso := "zga", value := .pluralPrefix }
  , { walsCode := "knn", iso := "kfk", value := .pluralSuffix }
  , { walsCode := "kio", iso := "kio", value := .pluralSuffix }
  , { walsCode := "kri", iso := "kzw", value := .pluralSuffix }
  , { walsCode := "kie", iso := "geb", value := .pluralSuffix }
  , { walsCode := "kgz", iso := "kir", value := .pluralSuffix }
  , { walsCode := "krb", iso := "gil", value := .mixedMorphologicalPlural }
  , { walsCode := "kir", iso := "cme", value := .pluralSuffix }
  , { walsCode := "kis", iso := "kss", value := .pluralClitic }
  , { walsCode := "kiw", iso := "kjd", value := .pluralSuffix }
  , { walsCode := "klm", iso := "kla", value := .mixedMorphologicalPlural }
  , { walsCode := "kla", iso := "klu", value := .pluralSuffix }
  , { walsCode := "shp", iso := "yak", value := .pluralSuffix }
  , { walsCode := "koa", iso := "cku", value := .pluralClitic }
  , { walsCode := "kob", iso := "kpw", value := .pluralSuffix }
  , { walsCode := "koe", iso := "xwg", value := .pluralClitic }
  , { walsCode := "kmo", iso := "kpx", value := .pluralSuffix }
  , { walsCode := "kta", iso := "kqi", value := .pluralSuffix }
  , { walsCode := "kok", iso := "trp", value := .pluralSuffix }
  , { walsCode := "kkt", iso := "kkk", value := .pluralWord }
  , { walsCode := "kol", iso := "kfb", value := .pluralSuffix }
  , { walsCode := "xbi", iso := "xbi", value := .pluralWord }
  , { walsCode := "kop", iso := "koi", value := .pluralSuffix }
  , { walsCode := "kom", iso := "xom", value := .pluralPrefix }
  , { walsCode := "kon", iso := "kng", value := .pluralPrefix }
  , { walsCode := "knw", iso := "mjd", value := .pluralSuffix }
  , { walsCode := "kni", iso := "kma", value := .pluralSuffix }
  , { walsCode := "krn", iso := "kqz", value := .pluralSuffix }
  , { walsCode := "kor", iso := "kor", value := .pluralSuffix }
  , { walsCode := "kku", iso := "kfq", value := .pluralSuffix }
  , { walsCode := "kfe", iso := "kfz", value := .pluralSuffix }
  , { walsCode := "krw", iso := "khe", value := .pluralSuffix }
  , { walsCode := "kry", iso := "kpy", value := .pluralSuffix }
  , { walsCode := "koy", iso := "kff", value := .pluralSuffix }
  , { walsCode := "kch", iso := "khq", value := .pluralWord }
  , { walsCode := "kse", iso := "ses", value := .pluralClitic }
  , { walsCode := "kpe", iso := "xpe", value := .pluralSuffix }
  , { walsCode := "kpo", iso := "kpo", value := .pluralClitic }
  , { walsCode := "kre", iso := "krs", value := .pluralWord }
  , { walsCode := "kro", iso := "kgo", value := .pluralPrefix }
  , { walsCode := "knc", iso := "uwa", value := .noPlural }
  , { walsCode := "kya", iso := "gvn", value := .pluralCompleteReduplication }
  , { walsCode := "kum", iso := "kfy", value := .pluralSuffix }
  , { walsCode := "knm", iso := "kun", value := .pluralClitic }
  , { walsCode := "kuo", iso := "kto", value := .pluralWord }
  , { walsCode := "krd", iso := "ckb", value := .pluralSuffix }
  , { walsCode := "kut", iso := "kut", value := .pluralPrefix }
  , { walsCode := "thy", iso := "thd", value := .noPlural }
  , { walsCode := "kuv", iso := "kxv", value := .pluralSuffix }
  , { walsCode := "kwa", iso := "kwd", value := .pluralWord }
  , { walsCode := "kwn", iso := "kwn", value := .pluralPrefix }
  , { walsCode := "kwz", iso := "xwa", value := .noPlural }
  , { walsCode := "kwo", iso := "kmo", value := .pluralWord }
  , { walsCode := "kwt", iso := "kwo", value := .pluralSuffix }
  , { walsCode := "kxo", iso := "xuu", value := .pluralSuffix }
  , { walsCode := "kyk", iso := "kyc", value := .pluralWord }
  , { walsCode := "kgy", iso := "kgy", value := .pluralClitic }
  , { walsCode := "kyq", iso := "nuk", value := .pluralSuffix }
  , { walsCode := "laa", iso := "gdm", value := .pluralStemChange }
  , { walsCode := "lad", iso := "lbj", value := .pluralSuffix }
  , { walsCode := "laf", iso := "laf", value := .pluralPrefix }
  , { walsCode := "lag", iso := "kot", value := .mixedMorphologicalPlural }
  , { walsCode := "lah", iso := "lhu", value := .pluralSuffix }
  , { walsCode := "lai", iso := "cnh", value := .pluralWord }
  , { walsCode := "lkt", iso := "lkt", value := .pluralWord }
  , { walsCode := "lal", iso := "ywt", value := .noPlural }
  , { walsCode := "lmh", iso := "slp", value := .pluralCompleteReduplication }
  , { walsCode := "lmg", iso := "hia", value := .pluralSuffix }
  , { walsCode := "lmn", iso := "lmn", value := .pluralSuffix }
  , { walsCode := "lmb", iso := "lam", value := .pluralPrefix }
  ]

private def allData_1 : List (Datapoint PluralityCoding) :=
  [ { walsCode := "lmu", iso := "lmu", value := .pluralWord }
  , { walsCode := "lan", iso := "laj", value := .pluralSuffix }
  , { walsCode := "lao", iso := "lao", value := .noPlural }
  , { walsCode := "lar", iso := "lrg", value := .pluralSuffix }
  , { walsCode := "lat", iso := "lav", value := .pluralSuffix }
  , { walsCode := "lav", iso := "lvk", value := .pluralSuffix }
  , { walsCode := "leg", iso := "lea", value := .pluralPrefix }
  , { walsCode := "lec", iso := "lec", value := .pluralSuffix }
  , { walsCode := "lel", iso := "lln", value := .pluralSuffix }
  , { walsCode := "llm", iso := "lef", value := .pluralPrefix }
  , { walsCode := "len", iso := "tnl", value := .pluralWord }
  , { walsCode := "ldu", iso := "led", value := .pluralSuffix }
  , { walsCode := "lng", iso := "enx", value := .pluralSuffix }
  , { walsCode := "lep", iso := "lep", value := .pluralWord }
  , { walsCode := "les", iso := "les", value := .pluralSuffix }
  , { walsCode := "let", iso := "lti", value := .pluralClitic }
  , { walsCode := "lew", iso := "lww", value := .pluralWord }
  , { walsCode := "lez", iso := "lez", value := .pluralSuffix }
  , { walsCode := "lim", iso := "lif", value := .noPlural }
  , { walsCode := "lnd", iso := "liy", value := .pluralWord }
  , { walsCode := "lit", iso := "lit", value := .pluralSuffix }
  , { walsCode := "ara", iso := "arw", value := .pluralSuffix }
  , { walsCode := "ldo", iso := "bdu", value := .pluralPrefix }
  , { walsCode := "lgu", iso := "lgu", value := .pluralClitic }
  , { walsCode := "lon", iso := "los", value := .pluralWord }
  , { walsCode := "lot", iso := "njh", value := .mixedMorphologicalPlural }
  , { walsCode := "lou", iso := "loj", value := .pluralWord }
  , { walsCode := "lda", iso := "lug", value := .pluralPrefix }
  , { walsCode := "lug", iso := "lgg", value := .pluralSuffix }
  , { walsCode := "lui", iso := "lui", value := .pluralSuffix }
  , { walsCode := "lul", iso := "ule", value := .pluralSuffix }
  , { walsCode := "lbu", iso := "lun", value := .pluralPrefix }
  , { walsCode := "lun", iso := "nst", value := .pluralSuffix }
  , { walsCode := "luo", iso := "luo", value := .pluralSuffix }
  , { walsCode := "kkv", iso := "khl", value := .pluralPrefix }
  , { walsCode := "luv", iso := "lue", value := .pluralPrefix }
  , { walsCode := "jlu", iso := "lwo", value := .pluralSuffix }
  , { walsCode := "ma", iso := "msj", value := .pluralSuffix }
  , { walsCode := "mad", iso := "mhi", value := .mixedMorphologicalPlural }
  , { walsCode := "maa", iso := "mas", value := .pluralSuffix }
  , { walsCode := "mab", iso := "mde", value := .pluralSuffix }
  , { walsCode := "mac", iso := "mbc", value := .pluralSuffix }
  , { walsCode := "mda", iso := "mxu", value := .pluralWord }
  , { walsCode := "mae", iso := "mmw", value := .pluralWord }
  , { walsCode := "mgh", iso := "mag", value := .pluralSuffix }
  , { walsCode := "mag", iso := "mgp", value := .pluralSuffix }
  , { walsCode := "mne", iso := "nmu", value := .pluralSuffix }
  , { walsCode := "mpr", iso := "", value := .pluralSuffix }
  , { walsCode := "msn", iso := "mbq", value := .pluralClitic }
  , { walsCode := "mai", iso := "mai", value := .pluralWord }
  , { walsCode := "maj", iso := "mpe", value := .pluralSuffix }
  , { walsCode := "mak", iso := "myh", value := .pluralClitic }
  , { walsCode := "mkj", iso := "mkz", value := .pluralClitic }
  , { walsCode := "mua", iso := "mgh", value := .pluralPrefix }
  , { walsCode := "mal", iso := "plt", value := .noPlural }
  , { walsCode := "mlg", iso := "", value := .pluralSuffix }
  , { walsCode := "mam", iso := "mam", value := .pluralClitic }
  , { walsCode := "mmn", iso := "mmn", value := .pluralWord }
  , { walsCode := "mmi", iso := "mcs", value := .pluralSuffix }
  , { walsCode := "mmv", iso := "mdi", value := .mixedMorphologicalPlural }
  , { walsCode := "mnm", iso := "mva", value := .noPlural }
  , { walsCode := "mnc", iso := "mnc", value := .pluralSuffix }
  , { walsCode := "mdn", iso := "mhq", value := .pluralSuffix }
  , { walsCode := "mnd", iso := "cmn", value := .pluralSuffix }
  , { walsCode := "mkg", iso := "mnk", value := .pluralSuffix }
  , { walsCode := "myi", iso := "mpc", value := .pluralSuffix }
  , { walsCode := "mbt", iso := "mdj", value := .pluralPrefix }
  , { walsCode := "mng", iso := "mqy", value := .noPlural }
  , { walsCode := "mgg", iso := "mjg", value := .pluralClitic }
  , { walsCode := "mgq", iso := "mge", value := .pluralSuffix }
  , { walsCode := "maw", iso := "mlq", value := .pluralClitic }
  , { walsCode := "man", iso := "mev", value := .pluralSuffix }
  , { walsCode := "mwb", iso := "mbb", value := .pluralWord }
  , { walsCode := "mns", iso := "mns", value := .pluralSuffix }
  , { walsCode := "mao", iso := "mri", value := .pluralWord }
  , { walsCode := "map", iso := "arn", value := .pluralWord }
  , { walsCode := "mra", iso := "mec", value := .pluralPrefix }
  , { walsCode := "mku", iso := "zmr", value := .noPlural }
  , { walsCode := "mny", iso := "zmc", value := .pluralSuffix }
  , { walsCode := "mrg", iso := "mrt", value := .pluralClitic }
  , { walsCode := "mme", iso := "mhr", value := .pluralSuffix }
  , { walsCode := "mar", iso := "mrc", value := .pluralStemChange }
  , { walsCode := "mrt", iso := "vma", value := .pluralSuffix }
  , { walsCode := "mru", iso := "mhx", value := .pluralWord }
  , { walsCode := "mas", iso := "mcn", value := .pluralSuffix }
  , { walsCode := "msk", iso := "jle", value := .pluralPrefix }
  , { walsCode := "msl", iso := "mls", value := .pluralSuffix }
  , { walsCode := "mtt", iso := "wam", value := .pluralSuffix }
  , { walsCode := "mts", iso := "mpq", value := .pluralSuffix }
  , { walsCode := "mtb", iso := "mgw", value := .pluralPrefix }
  , { walsCode := "mka", iso := "mxx", value := .pluralWord }
  , { walsCode := "mau", iso := "mph", value := .pluralWord }
  , { walsCode := "may", iso := "ayz", value := .noPlural }
  , { walsCode := "myg", iso := "mdm", value := .pluralPrefix }
  , { walsCode := "mzn", iso := "mzn", value := .pluralSuffix }
  , { walsCode := "mba", iso := "mfc", value := .pluralSuffix }
  , { walsCode := "mbr", iso := "mpk", value := .pluralSuffix }
  , { walsCode := "mby", iso := "myb", value := .pluralClitic }
  , { walsCode := "mbi", iso := "baw", value := .pluralPrefix }
  , { walsCode := "mdo", iso := "gmm", value := .pluralPrefix }
  , { walsCode := "mbl", iso := "mdq", value := .pluralPrefix }
  , { walsCode := "mbm", iso := "mdd", value := .pluralWord }
  , { walsCode := "mee", iso := "mym", value := .pluralSuffix }
  , { walsCode := "meh", iso := "gdq", value := .pluralSuffix }
  , { walsCode := "mek", iso := "skf", value := .pluralClitic }
  , { walsCode := "mde", iso := "men", value := .pluralSuffix }
  , { walsCode := "men", iso := "mez", value := .pluralSuffix }
  , { walsCode := "mer", iso := "ulk", value := .pluralSuffix }
  , { walsCode := "mea", iso := "mej", value := .pluralSuffix }
  , { walsCode := "mpt", iso := "mpt", value := .pluralSuffix }
  , { walsCode := "mie", iso := "ium", value := .noPlural }
  , { walsCode := "mij", iso := "mxj", value := .pluralSuffix }
  , { walsCode := "mkr", iso := "msy", value := .pluralSuffix }
  , { walsCode := "mki", iso := "mik", value := .mixedMorphologicalPlural }
  , { walsCode := "mik", iso := "mjw", value := .pluralWord }
  , { walsCode := "hna", iso := "hna", value := .pluralClitic }
  , { walsCode := "min", iso := "min", value := .noPlural }
  , { walsCode := "msg", iso := "mrg", value := .mixedMorphologicalPlural }
  , { walsCode := "mis", iso := "miq", value := .pluralWord }
  , { walsCode := "mss", iso := "skd", value := .pluralSuffix }
  , { walsCode := "mco", iso := "mco", value := .pluralWord }
  , { walsCode := "mxc", iso := "mig", value := .pluralWord }
  , { walsCode := "mxj", iso := "mio", value := .noPlural }
  , { walsCode := "mxo", iso := "mie", value := .pluralWord }
  , { walsCode := "mxp", iso := "mil", value := .pluralWord }
  , { walsCode := "mxy", iso := "mpm", value := .pluralWord }
  , { walsCode := "miy", iso := "mkf", value := .pluralSuffix }
  , { walsCode := "miz", iso := "lus", value := .pluralWord }
  , { walsCode := "mcc", iso := "omc", value := .pluralClitic }
  , { walsCode := "mcv", iso := "moc", value := .pluralSuffix }
  , { walsCode := "mof", iso := "mif", value := .pluralWord }
  , { walsCode := "mog", iso := "mhj", value := .pluralSuffix }
  , { walsCode := "moh", iso := "moh", value := .pluralPrefix }
  , { walsCode := "mok", iso := "mkj", value := .pluralClitic }
  , { walsCode := "fqs", iso := "fqs", value := .noPlural }
  , { walsCode := "mon", iso := "mnw", value := .pluralWord }
  , { walsCode := "mga", iso := "ndt", value := .mixedMorphologicalPlural }
  , { walsCode := "mkh", iso := "", value := .pluralSuffix }
  , { walsCode := "mno", iso := "mnr", value := .pluralSuffix }
  , { walsCode := "mor", iso := "mhz", value := .pluralSuffix }
  , { walsCode := "moe", iso := "myv", value := .pluralSuffix }
  , { walsCode := "mro", iso := "mor", value := .pluralPrefix }
  , { walsCode := "mou", iso := "mgd", value := .pluralSuffix }
  , { walsCode := "mos", iso := "cas", value := .pluralSuffix }
  , { walsCode := "mtu", iso := "meu", value := .mixedMorphologicalPlural }
  , { walsCode := "mot", iso := "siw", value := .pluralSuffix }
  , { walsCode := "aoj", iso := "aoj", value := .pluralWord }
  , { walsCode := "mui", iso := "bmr", value := .pluralSuffix }
  , { walsCode := "mum", iso := "mzm", value := .pluralWord }
  , { walsCode := "mna", iso := "mnb", value := .pluralSuffix }
  , { walsCode := "mdg", iso := "mua", value := .pluralClitic }
  , { walsCode := "mun", iso := "unr", value := .pluralSuffix }
  , { walsCode := "muu", iso := "myu", value := .pluralSuffix }
  , { walsCode := "mgk", iso := "mhk", value := .pluralPrefix }
  , { walsCode := "mnz", iso := "moj", value := .pluralClitic }
  , { walsCode := "mup", iso := "sur", value := .pluralWord }
  , { walsCode := "mrl", iso := "mur", value := .pluralSuffix }
  , { walsCode := "mur", iso := "muz", value := .pluralSuffix }
  , { walsCode := "mrw", iso := "zmu", value := .mixedMorphologicalPlural }
  , { walsCode := "mgu", iso := "mug", value := .pluralSuffix }
  , { walsCode := "mus", iso := "emi", value := .pluralWord }
  , { walsCode := "mut", iso := "css", value := .pluralSuffix }
  , { walsCode := "mwe", iso := "mwe", value := .pluralPrefix }
  , { walsCode := "mwo", iso := "mlv", value := .pluralWord }
  , { walsCode := "nab", iso := "naf", value := .pluralSuffix }
  , { walsCode := "nma", iso := "nbi", value := .mixedMorphologicalPlural }
  , { walsCode := "ngt", iso := "nmf", value := .pluralClitic }
  , { walsCode := "nze", iso := "nzm", value := .pluralWord }
  , { walsCode := "nag", iso := "nce", value := .pluralSuffix }
  , { walsCode := "nhh", iso := "", value := .pluralSuffix }
  , { walsCode := "nhm", iso := "ncl", value := .mixedMorphologicalPlural }
  , { walsCode := "nhn", iso := "ncj", value := .pluralSuffix }
  , { walsCode := "nht", iso := "nhg", value := .pluralSuffix }
  , { walsCode := "nak", iso := "nak", value := .pluralWord }
  , { walsCode := "nal", iso := "nal", value := .pluralWord }
  , { walsCode := "kho", iso := "naq", value := .pluralSuffix }
  , { walsCode := "nam", iso := "nnm", value := .noPlural }
  , { walsCode := "nde", iso := "nnb", value := .pluralPrefix }
  , { walsCode := "nan", iso := "niq", value := .pluralSuffix }
  , { walsCode := "nrg", iso := "sen", value := .pluralSuffix }
  , { walsCode := "nph", iso := "npa", value := .pluralClitic }
  , { walsCode := "nar", iso := "nrb", value := .pluralSuffix }
  , { walsCode := "nav", iso := "nav", value := .pluralSuffix }
  , { walsCode := "ncm", iso := "bud", value := .mixedMorphologicalPlural }
  , { walsCode := "ndb", iso := "nde", value := .pluralPrefix }
  , { walsCode := "ndo", iso := "ndo", value := .pluralPrefix }
  , { walsCode := "ndu", iso := "nmd", value := .pluralPrefix }
  , { walsCode := "ndt", iso := "ndv", value := .pluralSuffix }
  , { walsCode := "ndy", iso := "djk", value := .pluralWord }
  , { walsCode := "ntu", iso := "yrk", value := .pluralSuffix }
  , { walsCode := "naj", iso := "aij", value := .pluralSuffix }
  , { walsCode := "nep", iso := "npi", value := .pluralSuffix }
  , { walsCode := "nev", iso := "pia", value := .pluralPrefix }
  , { walsCode := "nwd", iso := "new", value := .pluralClitic }
  , { walsCode := "new", iso := "new", value := .pluralClitic }
  , { walsCode := "ngd", iso := "nxg", value := .noPlural }
  , { walsCode := "ngj", iso := "nju", value := .pluralSuffix }
  , { walsCode := "ngl", iso := "nig", value := .noPlural }
  , { walsCode := "nkb", iso := "ngk", value := .pluralSuffix }
  , { walsCode := "ngm", iso := "sba", value := .pluralSuffix }
  , { walsCode := "ngn", iso := "nid", value := .pluralPrefix }
  , { walsCode := "ngk", iso := "nam", value := .mixedMorphologicalPlural }
  , { walsCode := "ngb", iso := "nga", value := .mixedMorphologicalPlural }
  , { walsCode := "nti", iso := "niy", value := .pluralTone }
  , { walsCode := "ngi", iso := "wyb", value := .pluralSuffix }
  , { walsCode := "ngz", iso := "ngi", value := .pluralSuffix }
  , { walsCode := "ngo", iso := "ngo", value := .pluralPrefix }
  , { walsCode := "nbr", iso := "gym", value := .pluralSuffix }
  , { walsCode := "nha", iso := "nha", value := .pluralSuffix }
  , { walsCode := "nia", iso := "nia", value := .pluralPrefix }
  , { walsCode := "nca", iso := "caq", value := .noPlural }
  , { walsCode := "nsg", iso := "ncg", value := .noPlural }
  , { walsCode := "nif", iso := "num", value := .pluralWord }
  , { walsCode := "niu", iso := "niu", value := .pluralWord }
  , { walsCode := "niv", iso := "niv", value := .pluralSuffix }
  , { walsCode := "nke", iso := "isi", value := .pluralPrefix }
  , { walsCode := "nkn", iso := "nko", value := .pluralPrefix }
  , { walsCode := "nko", iso := "cgg", value := .pluralPrefix }
  , { walsCode := "noc", iso := "njb", value := .pluralSuffix }
  , { walsCode := "nog", iso := "nog", value := .pluralSuffix }
  , { walsCode := "non", iso := "nhu", value := .pluralPrefix }
  , { walsCode := "nor", iso := "nor", value := .pluralSuffix }
  , { walsCode := "nua", iso := "nxl", value := .pluralSuffix }
  , { walsCode := "nbd", iso := "dgl", value := .pluralSuffix }
  , { walsCode := "nue", iso := "nus", value := .pluralStemChange }
  , { walsCode := "nun", iso := "nut", value := .pluralWord }
  , { walsCode := "nug", iso := "nuy", value := .pluralPrefix }
  , { walsCode := "nup", iso := "nup", value := .pluralClitic }
  , { walsCode := "nym", iso := "nym", value := .pluralPrefix }
  , { walsCode := "nyi", iso := "nyi", value := .noPlural }
  , { walsCode := "nis", iso := "njz", value := .pluralWord }
  , { walsCode := "nza", iso := "nzk", value := .pluralPrefix }
  , { walsCode := "ood", iso := "ood", value := .pluralPrefix }
  , { walsCode := "obo", iso := "ann", value := .noPlural }
  , { walsCode := "ocu", iso := "ocu", value := .pluralPrefix }
  , { walsCode := "obg", iso := "ogu", value := .pluralPrefix }
  , { walsCode := "oir", iso := "xal", value := .pluralSuffix }
  , { walsCode := "oji", iso := "", value := .pluralSuffix }
  , { walsCode := "oks", iso := "opm", value := .pluralSuffix }
  , { walsCode := "olo", iso := "ong", value := .pluralSuffix }
  , { walsCode := "one", iso := "aun", value := .pluralSuffix }
  , { walsCode := "ond", iso := "one", value := .mixedMorphologicalPlural }
  , { walsCode := "ong", iso := "oon", value := .pluralSuffix }
  , { walsCode := "ord", iso := "mvf", value := .pluralSuffix }
  , { walsCode := "oya", iso := "ory", value := .pluralSuffix }
  , { walsCode := "ork", iso := "oaa", value := .pluralSuffix }
  , { walsCode := "oro", iso := "okv", value := .pluralCompleteReduplication }
  , { walsCode := "orh", iso := "hae", value := .noPlural }
  , { walsCode := "orw", iso := "ssn", value := .noPlural }
  , { walsCode := "osa", iso := "osa", value := .pluralWord }
  , { walsCode := "oss", iso := "oss", value := .pluralSuffix }
  , { walsCode := "otr", iso := "otr", value := .pluralPrefix }
  , { walsCode := "paa", iso := "pqa", value := .pluralSuffix }
  , { walsCode := "pkn", iso := "drl", value := .noPlural }
  , { walsCode := "pms", iso := "pma", value := .pluralWord }
  , { walsCode := "pno", iso := "pao", value := .mixedMorphologicalPlural }
  , { walsCode := "pal", iso := "pau", value := .pluralPrefix }
  , { walsCode := "plk", iso := "plu", value := .pluralSuffix }
  , { walsCode := "pam", iso := "pmz", value := .mixedMorphologicalPlural }
  , { walsCode := "pan", iso := "pan", value := .pluralSuffix }
  , { walsCode := "pre", iso := "asa", value := .pluralPrefix }
  , { walsCode := "psh", iso := "pst", value := .pluralSuffix }
  , { walsCode := "psm", iso := "pqm", value := .pluralSuffix }
  , { walsCode := "ptt", iso := "lae", value := .pluralSuffix }
  , { walsCode := "ptw", iso := "pwi", value := .pluralSuffix }
  , { walsCode := "plh", iso := "plh", value := .pluralSuffix }
  , { walsCode := "pau", iso := "pad", value := .noPlural }
  , { walsCode := "pwn", iso := "paw", value := .pluralSuffix }
  , { walsCode := "per", iso := "pip", value := .noPlural }
  , { walsCode := "prs", iso := "pes", value := .pluralSuffix }
  , { walsCode := "pia", iso := "pid", value := .pluralSuffix }
  , { walsCode := "pga", iso := "plg", value := .pluralSuffix }
  , { walsCode := "pba", iso := "pia", value := .mixedMorphologicalPlural }
  , { walsCode := "pip", iso := "ppl", value := .pluralSuffix }
  , { walsCode := "prh", iso := "myp", value := .noPlural }
  , { walsCode := "poh", iso := "pon", value := .noPlural }
  , { walsCode := "pok", iso := "rwa", value := .noPlural }
  , { walsCode := "pkt", iso := "pko", value := .mixedMorphologicalPlural }
  , { walsCode := "pol", iso := "pol", value := .pluralSuffix }
  , { walsCode := "pme", iso := "peb", value := .pluralSuffix }
  , { walsCode := "pso", iso := "pom", value := .pluralSuffix }
  , { walsCode := "psw", iso := "psw", value := .pluralWord }
  , { walsCode := "por", iso := "por", value := .pluralSuffix }
  , { walsCode := "pum", iso := "pmi", value := .pluralClitic }
  , { walsCode := "prk", iso := "prx", value := .pluralSuffix }
  , { walsCode := "pur", iso := "tsz", value := .pluralSuffix }
  , { walsCode := "pae", iso := "pbb", value := .pluralSuffix }
  , { walsCode := "par", iso := "lkr", value := .mixedMorphologicalPlural }
  , { walsCode := "qia", iso := "", value := .pluralClitic }
  , { walsCode := "qhu", iso := "qub", value := .pluralSuffix }
  , { walsCode := "qim", iso := "qvi", value := .pluralSuffix }
  , { walsCode := "qui", iso := "qui", value := .pluralPrefix }
  , { walsCode := "rag", iso := "lml", value := .pluralWord }
  , { walsCode := "rji", iso := "rji", value := .noPlural }
  , { walsCode := "ram", iso := "rma", value := .pluralClitic }
  , { walsCode := "rao", iso := "rao", value := .noPlural }
  , { walsCode := "rap", iso := "rap", value := .pluralWord }
  , { walsCode := "ras", iso := "ras", value := .pluralSuffix }
  , { walsCode := "raw", iso := "raw", value := .pluralWord }
  , { walsCode := "rem", iso := "bfw", value := .pluralSuffix }
  , { walsCode := "res", iso := "rgr", value := .pluralSuffix }
  , { walsCode := "rit", iso := "rit", value := .pluralSuffix }
  , { walsCode := "rwe", iso := "rmw", value := .pluralSuffix }
  , { walsCode := "rom", iso := "ron", value := .pluralSuffix }
  , { walsCode := "ruk", iso := "dru", value := .pluralPrefix }
  , { walsCode := "run", iso := "rou", value := .pluralSuffix }
  , { walsCode := "rny", iso := "nyn", value := .pluralSuffix }
  , { walsCode := "rus", iso := "rus", value := .pluralSuffix }
  , { walsCode := "rut", iso := "rut", value := .pluralSuffix }
  , { walsCode := "saa", iso := "apb", value := .pluralWord }
  , { walsCode := "sno", iso := "sme", value := .pluralSuffix }
  , { walsCode := "sah", iso := "saj", value := .noPlural }
  , { walsCode := "sak", iso := "sku", value := .pluralPrefix }
  , { walsCode := "slb", iso := "sbe", value := .pluralSuffix }
  , { walsCode := "sal", iso := "sln", value := .pluralSuffix }
  , { walsCode := "syu", iso := "sll", value := .noPlural }
  , { walsCode := "sle", iso := "ndi", value := .pluralWord }
  , { walsCode := "sam", iso := "smo", value := .pluralWord }
  , { walsCode := "sdw", iso := "sad", value := .pluralSuffix }
  , { walsCode := "san", iso := "sag", value := .pluralPrefix }
  , { walsCode := "sta", iso := "sce", value := .pluralSuffix }
  , { walsCode := "stl", iso := "sat", value := .pluralSuffix }
  , { walsCode := "snm", iso := "xsu", value := .pluralWord }
  , { walsCode := "src", iso := "srs", value := .pluralSuffix }
  , { walsCode := "srd", iso := "sro", value := .pluralSuffix }
  , { walsCode := "sar", iso := "dju", value := .pluralClitic }
  , { walsCode := "sav", iso := "sdg", value := .pluralSuffix }
  , { walsCode := "svs", iso := "svs", value := .pluralClitic }
  , { walsCode := "seb", iso := "kpz", value := .pluralSuffix }
  , { walsCode := "sec", iso := "sey", value := .pluralSuffix }
  , { walsCode := "sed", iso := "sed", value := .pluralWord }
  , { walsCode := "slp", iso := "spl", value := .pluralSuffix }
  , { walsCode := "skp", iso := "sel", value := .pluralSuffix }
  , { walsCode := "sem", iso := "nsm", value := .pluralClitic }
  , { walsCode := "sme", iso := "sif", value := .pluralTone }
  , { walsCode := "smn", iso := "mus", value := .pluralSuffix }
  , { walsCode := "snt", iso := "set", value := .noPlural }
  , { walsCode := "scr", iso := "hbs", value := .pluralSuffix }
  , { walsCode := "ser", iso := "sei", value := .pluralSuffix }
  , { walsCode := "shb", iso := "sbf", value := .pluralWord }
  , { walsCode := "shm", iso := "ksb", value := .pluralPrefix }
  , { walsCode := "sht", iso := "shj", value := .pluralSuffix }
  , { walsCode := "shd", iso := "sdp", value := .pluralSuffix }
  , { walsCode := "shl", iso := "shk", value := .pluralSuffix }
  , { walsCode := "sna", iso := "scl", value := .pluralSuffix }
  , { walsCode := "shk", iso := "shp", value := .pluralSuffix }
  , { walsCode := "shy", iso := "yuy", value := .pluralSuffix }
  , { walsCode := "shi", iso := "shb", value := .pluralWord }
  , { walsCode := "smp", iso := "sii", value := .noPlural }
  , { walsCode := "shn", iso := "sna", value := .pluralPrefix }
  , { walsCode := "sho", iso := "shh", value := .pluralSuffix }
  , { walsCode := "sia", iso := "snp", value := .noPlural }
  , { walsCode := "sid", iso := "sid", value := .pluralSuffix }
  , { walsCode := "skk", iso := "sip", value := .pluralWord }
  , { walsCode := "sil", iso := "dau", value := .pluralSuffix }
  , { walsCode := "sng", iso := "snc", value := .pluralClitic }
  , { walsCode := "sin", iso := "snn", value := .pluralSuffix }
  , { walsCode := "qum", iso := "qum", value := .pluralWord }
  , { walsCode := "sro", iso := "ssd", value := .pluralWord }
  , { walsCode := "sis", iso := "baa", value := .pluralWord }
  , { walsCode := "siu", iso := "sis", value := .pluralSuffix }
  , { walsCode := "sla", iso := "den", value := .pluralSuffix }
  , { walsCode := "slo", iso := "slv", value := .pluralSuffix }
  , { walsCode := "so", iso := "teu", value := .pluralSuffix }
  , { walsCode := "sob", iso := "sob", value := .pluralSuffix }
  , { walsCode := "som", iso := "som", value := .pluralSuffix }
  , { walsCode := "son", iso := "sov", value := .noPlural }
  , { walsCode := "sor", iso := "srb", value := .pluralSuffix }
  , { walsCode := "stn", iso := "nso", value := .pluralPrefix }
  , { walsCode := "sgb", iso := "mnx", value := .pluralSuffix }
  , { walsCode := "sea", iso := "tvk", value := .pluralWord }
  , { walsCode := "tou", iso := "wib", value := .pluralSuffix }
  , { walsCode := "spa", iso := "spa", value := .pluralSuffix }
  , { walsCode := "spi", iso := "spt", value := .pluralSuffix }
  , { walsCode := "sre", iso := "kpm", value := .pluralPrefix }
  , { walsCode := "sti", iso := "", value := .pluralWord }
  , { walsCode := "sub", iso := "sbs", value := .pluralPrefix }
  , { walsCode := "sud", iso := "tgo", value := .mixedMorphologicalPlural }
  , { walsCode := "suk", iso := "sui", value := .pluralSuffix }
  , { walsCode := "sul", iso := "sua", value := .pluralPrefix }
  , { walsCode := "sun", iso := "sun", value := .pluralCompleteReduplication }
  , { walsCode := "sug", iso := "sjg", value := .pluralSuffix }
  , { walsCode := "sup", iso := "spp", value := .pluralSuffix }
  , { walsCode := "swa", iso := "swh", value := .pluralPrefix }
  , { walsCode := "swe", iso := "swe", value := .pluralSuffix }
  , { walsCode := "tab", iso := "mky", value := .pluralClitic }
  , { walsCode := "tba", iso := "sst", value := .noPlural }
  , { walsCode := "tbw", iso := "tap", value := .pluralPrefix }
  , { walsCode := "tac", iso := "tna", value := .pluralWord }
  , { walsCode := "tag", iso := "tgl", value := .pluralWord }
  , { walsCode := "tah", iso := "tah", value := .pluralWord }
  , { walsCode := "trr", iso := "tbg", value := .pluralSuffix }
  , { walsCode := "taj", iso := "tgk", value := .pluralSuffix }
  , { walsCode := "tkl", iso := "tkm", value := .pluralSuffix }
  , { walsCode := "tak", iso := "tbc", value := .pluralWord }
  , { walsCode := "tma", iso := "tma", value := .pluralSuffix }
  , { walsCode := "tmg", iso := "tcg", value := .noPlural }
  , { walsCode := "tam", iso := "taj", value := .pluralWord }
  , { walsCode := "tsk", iso := "taq", value := .mixedMorphologicalPlural }
  , { walsCode := "tml", iso := "tam", value := .pluralSuffix }
  , { walsCode := "tnc", iso := "tcb", value := .pluralSuffix }
  , { walsCode := "tpt", iso := "tpj", value := .pluralSuffix }
  , { walsCode := "twe", iso := "tac", value := .pluralStemChange }
  , { walsCode := "tao", iso := "tro", value := .pluralSuffix }
  , { walsCode := "tar", iso := "tae", value := .pluralSuffix }
  , { walsCode := "tas", iso := "shi", value := .mixedMorphologicalPlural }
  , { walsCode := "tvo", iso := "tat", value := .pluralSuffix }
  , { walsCode := "tts", iso := "tks", value := .pluralSuffix }
  , { walsCode := "tsg", iso := "tsg", value := .pluralWord }
  , { walsCode := "tau", iso := "tya", value := .noPlural }
  , { walsCode := "tbo", iso := "tbl", value := .pluralWord }
  , { walsCode := "tlf", iso := "tlf", value := .pluralSuffix }
  , { walsCode := "tel", iso := "tel", value := .pluralSuffix }
  , { walsCode := "tmn", iso := "teq", value := .mixedMorphologicalPlural }
  , { walsCode := "tne", iso := "tem", value := .pluralPrefix }
  , { walsCode := "ten", iso := "tex", value := .pluralSuffix }
  , { walsCode := "tny", iso := "kza", value := .pluralSuffix }
  , { walsCode := "teo", iso := "tio", value := .pluralWord }
  , { walsCode := "tee", iso := "tee", value := .mixedMorphologicalPlural }
  , { walsCode := "tep", iso := "tpt", value := .pluralSuffix }
  , { walsCode := "tpn", iso := "ntp", value := .pluralPrefix }
  , { walsCode := "tps", iso := "stp", value := .pluralPrefix }
  , { walsCode := "ter", iso := "ttr", value := .pluralClitic }
  , { walsCode := "trb", iso := "tfr", value := .pluralSuffix }
  , { walsCode := "tes", iso := "teo", value := .mixedMorphologicalPlural }
  , { walsCode := "ttn", iso := "tet", value := .pluralWord }
  , { walsCode := "ttd", iso := "tet", value := .pluralWord }
  , { walsCode := "thk", iso := "ths", value := .pluralSuffix }
  , { walsCode := "thn", iso := "thf", value := .pluralSuffix }
  , { walsCode := "thu", iso := "tdh", value := .noPlural }
  , { walsCode := "tmo", iso := "bod", value := .pluralWord }
  , { walsCode := "tic", iso := "tca", value := .pluralSuffix }
  , { walsCode := "tid", iso := "tvo", value := .noPlural }
  , { walsCode := "tgk", iso := "tgc", value := .pluralWord }
  , { walsCode := "tig", iso := "tir", value := .pluralSuffix }
  , { walsCode := "tgr", iso := "tig", value := .mixedMorphologicalPlural }
  , { walsCode := "tja", iso := "dih", value := .pluralStemChange }
  , { walsCode := "tia", iso := "tms", value := .pluralPrefix }
  , { walsCode := "tmc", iso := "tjm", value := .pluralSuffix }
  , { walsCode := "tim", iso := "tih", value := .pluralClitic }
  , { walsCode := "tin", iso := "cir", value := .pluralWord }
  , { walsCode := "tir", iso := "tri", value := .pluralSuffix }
  , { walsCode := "trm", iso := "suq", value := .pluralSuffix }
  , { walsCode := "twn", iso := "twf", value := .pluralSuffix }
  , { walsCode := "tiw", iso := "tiw", value := .pluralSuffix }
  , { walsCode := "tlp", iso := "tcf", value := .noPlural }
  , { walsCode := "tli", iso := "tli", value := .pluralSuffix }
  , { walsCode := "tob", iso := "tob", value := .pluralSuffix }
  , { walsCode := "tlo", iso := "tlb", value := .noPlural }
  , { walsCode := "tla", iso := "ksd", value := .pluralWord }
  , { walsCode := "tno", iso := "tdn", value := .pluralWord }
  , { walsCode := "toz", iso := "toi", value := .pluralPrefix }
  , { walsCode := "tng", iso := "ton", value := .pluralWord }
  , { walsCode := "ton", iso := "tqw", value := .pluralSuffix }
  , { walsCode := "trw", iso := "trw", value := .pluralSuffix }
  , { walsCode := "tot", iso := "tlc", value := .mixedMorphologicalPlural }
  , { walsCode := "tri", iso := "trc", value := .noPlural }
  , { walsCode := "tru", iso := "tpy", value := .pluralWord }
  , { walsCode := "tsf", iso := "cof", value := .pluralClitic }
  , { walsCode := "tsz", iso := "ddo", value := .pluralSuffix }
  , { walsCode := "tgl", iso := "tsj", value := .pluralClitic }
  , { walsCode := "tsi", iso := "tsi", value := .pluralPrefix }
  , { walsCode := "tgo", iso := "tsv", value := .pluralPrefix }
  , { walsCode := "ttu", iso := "bbl", value := .pluralSuffix }
  , { walsCode := "tgh", iso := "thv", value := .mixedMorphologicalPlural }
  , { walsCode := "tbu", iso := "", value := .pluralSuffix }
  , { walsCode := "tuc", iso := "tuo", value := .pluralSuffix }
  , { walsCode := "tgn", iso := "tzn", value := .pluralWord }
  , { walsCode := "tuk", iso := "", value := .noPlural }
  , { walsCode := "tul", iso := "tcy", value := .pluralSuffix }
  , { walsCode := "tnn", iso := "tvu", value := .pluralPrefix }
  , { walsCode := "tnk", iso := "lcm", value := .pluralWord }
  , { walsCode := "tun", iso := "tun", value := .pluralSuffix }
  , { walsCode := "tna", iso := "tuv", value := .mixedMorphologicalPlural }
  , { walsCode := "tur", iso := "tur", value := .pluralSuffix }
  , { walsCode := "tus", iso := "tus", value := .pluralPrefix }
  , { walsCode := "tvl", iso := "tvl", value := .pluralWord }
  , { walsCode := "tuv", iso := "tyv", value := .pluralSuffix }
  , { walsCode := "tzo", iso := "tzo", value := .pluralSuffix }
  , { walsCode := "tzu", iso := "tzj", value := .pluralWord }
  , { walsCode := "tsh", iso := "par", value := .pluralSuffix }
  , { walsCode := "uby", iso := "uby", value := .pluralSuffix }
  , { walsCode := "udi", iso := "udi", value := .pluralSuffix }
  , { walsCode := "udm", iso := "udm", value := .pluralSuffix }
  , { walsCode := "ukr", iso := "ukr", value := .pluralSuffix }
  , { walsCode := "uld", iso := "udl", value := .pluralWord }
  , { walsCode := "ung", iso := "ung", value := .pluralCompleteReduplication }
  , { walsCode := "ura", iso := "uur", value := .pluralWord }
  , { walsCode := "url", iso := "urk", value := .noPlural }
  , { walsCode := "urn", iso := "ura", value := .pluralSuffix }
  , { walsCode := "urt", iso := "urt", value := .pluralWord }
  , { walsCode := "urd", iso := "urd", value := .pluralSuffix }
  , { walsCode := "urk", iso := "urb", value := .pluralSuffix }
  , { walsCode := "usr", iso := "usa", value := .pluralSuffix }
  , { walsCode := "ute", iso := "ute", value := .pluralSuffix }
  , { walsCode := "uyg", iso := "uig", value := .pluralSuffix }
  , { walsCode := "uzb", iso := "", value := .pluralSuffix }
  , { walsCode := "vai", iso := "vai", value := .pluralWord }
  , { walsCode := "vie", iso := "vie", value := .pluralWord }
  , { walsCode := "vnm", iso := "vnm", value := .pluralWord }
  ]

private def allData_2 : List (Datapoint PluralityCoding) :=
  [ { walsCode := "wah", iso := "", value := .noPlural }
  , { walsCode := "wak", iso := "wbl", value := .pluralSuffix }
  , { walsCode := "wal", iso := "van", value := .pluralSuffix }
  , { walsCode := "wbn", iso := "wms", value := .pluralSuffix }
  , { walsCode := "wme", iso := "wme", value := .pluralWord }
  , { walsCode := "wao", iso := "auc", value := .pluralSuffix }
  , { walsCode := "wap", iso := "wao", value := .pluralSuffix }
  , { walsCode := "wra", iso := "wba", value := .pluralSuffix }
  , { walsCode := "wrd", iso := "wrr", value := .pluralSuffix }
  , { walsCode := "wrk", iso := "gae", value := .pluralSuffix }
  , { walsCode := "war", iso := "pav", value := .pluralWord }
  , { walsCode := "wrl", iso := "wbp", value := .pluralSuffix }
  , { walsCode := "wrn", iso := "wnd", value := .pluralPrefix }
  , { walsCode := "wrw", iso := "wwr", value := .pluralClitic }
  , { walsCode := "wau", iso := "noa", value := .pluralSuffix }
  , { walsCode := "wed", iso := "wed", value := .pluralPrefix }
  , { walsCode := "wel", iso := "cym", value := .pluralSuffix }
  , { walsCode := "wic", iso := "wic", value := .noPlural }
  , { walsCode := "wch", iso := "mzh", value := .pluralSuffix }
  , { walsCode := "wik", iso := "yok", value := .pluralSuffix }
  , { walsCode := "wir", iso := "wgu", value := .noPlural }
  , { walsCode := "wiy", iso := "wiy", value := .noPlural }
  , { walsCode := "wly", iso := "wal", value := .pluralSuffix }
  , { walsCode := "wlo", iso := "wlo", value := .pluralWord }
  , { walsCode := "wlf", iso := "wol", value := .mixedMorphologicalPlural }
  , { walsCode := "xas", iso := "kao", value := .pluralSuffix }
  , { walsCode := "xav", iso := "xav", value := .noPlural }
  , { walsCode := "xho", iso := "xho", value := .pluralPrefix }
  , { walsCode := "xar", iso := "ane", value := .pluralWord }
  , { walsCode := "ygr", iso := "ygr", value := .pluralClitic }
  , { walsCode := "yag", iso := "yad", value := .pluralSuffix }
  , { walsCode := "ykt", iso := "sah", value := .pluralSuffix }
  , { walsCode := "yam", iso := "yaa", value := .pluralSuffix }
  , { walsCode := "yny", iso := "jao", value := .pluralPrefix }
  , { walsCode := "yap", iso := "yap", value := .pluralWord }
  , { walsCode := "yaq", iso := "yaq", value := .pluralSuffix }
  , { walsCode := "yar", iso := "yrb", value := .pluralSuffix }
  , { walsCode := "ywl", iso := "yok", value := .pluralSuffix }
  , { walsCode := "yel", iso := "yle", value := .pluralWord }
  , { walsCode := "yid", iso := "yii", value := .noPlural }
  , { walsCode := "yim", iso := "yee", value := .pluralSuffix }
  , { walsCode := "yin", iso := "yij", value := .pluralSuffix }
  , { walsCode := "yok", iso := "yok", value := .pluralSuffix }
  , { walsCode := "yor", iso := "yor", value := .pluralWord }
  , { walsCode := "yuc", iso := "yuc", value := .pluralWord }
  , { walsCode := "ycn", iso := "ycn", value := .pluralSuffix }
  , { walsCode := "yko", iso := "yux", value := .pluralSuffix }
  , { walsCode := "ytu", iso := "ykg", value := .pluralSuffix }
  , { walsCode := "yuk", iso := "gcd", value := .pluralSuffix }
  , { walsCode := "yul", iso := "yul", value := .pluralClitic }
  , { walsCode := "ypk", iso := "esu", value := .pluralSuffix }
  , { walsCode := "yur", iso := "yur", value := .mixedMorphologicalPlural }
  , { walsCode := "yuw", iso := "kld", value := .pluralSuffix }
  , { walsCode := "zan", iso := "zne", value := .pluralPrefix }
  , { walsCode := "zpr", iso := "zro", value := .pluralSuffix }
  , { walsCode := "zai", iso := "zai", value := .pluralWord }
  , { walsCode := "zap", iso := "zaw", value := .pluralPrefix }
  , { walsCode := "zar", iso := "dje", value := .pluralClitic }
  , { walsCode := "zay", iso := "zay", value := .pluralSuffix }
  , { walsCode := "zhn", iso := "zgb", value := .noPlural }
  , { walsCode := "zqc", iso := "zoc", value := .pluralSuffix }
  , { walsCode := "zul", iso := "zul", value := .pluralPrefix }
  , { walsCode := "zun", iso := "zun", value := .pluralSuffix }
  , { walsCode := "rgc", iso := "jya", value := .pluralSuffix }
  , { walsCode := "eme", iso := "eme", value := .pluralClitic }
  , { walsCode := "omi", iso := "aom", value := .noPlural }
  ]

/-- Complete WALS 33A dataset (1066 languages). -/
def allData : List (Datapoint PluralityCoding) := allData_0 ++ allData_1 ++ allData_2

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F33A
