import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 38A: Indefinite Articles
@cite{dryer-2013-wals}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 38A`.

Chapter 38, 534 languages.
-/

namespace Core.WALS.F38A

/-- WALS 38A values. -/
inductive IndefiniteArticleType where
  /-- Indefinite word distinct from 'one' (102 languages). -/
  | indefiniteWordDistinctFromOne
  /-- Indefinite word same as 'one' (112 languages). -/
  | indefiniteWordSameAsOne
  /-- Indefinite affix (24 languages). -/
  | indefiniteAffix
  /-- No indefinite, but definite article (98 languages). -/
  | noIndefiniteButDefiniteArticle
  /-- No definite or indefinite article (198 languages). -/
  | noDefiniteOrIndefiniteArticle
  deriving DecidableEq, BEq, Repr

private def allData_0 : List (Datapoint IndefiniteArticleType) :=
  [ { walsCode := "aar", iso := "aiw", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "abk", iso := "abk", value := .indefiniteWordSameAsOne }
  , { walsCode := "abu", iso := "kgr", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "ace", iso := "ace", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "aco", iso := "kjq", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "adi", iso := "adj", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "ala", iso := "amp", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "alb", iso := "sqi", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "aln", iso := "alp", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "amc", iso := "amc", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "amn", iso := "amn", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "amq", iso := "amk", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "amb", iso := "abt", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ame", iso := "aey", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "amh", iso := "amh", value := .indefiniteWordSameAsOne }
  , { walsCode := "anj", iso := "aty", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "agm", iso := "njm", value := .indefiniteWordSameAsOne }
  , { walsCode := "ang", iso := "agg", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "anu", iso := "cko", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "any", iso := "anu", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ao", iso := "njo", value := .indefiniteWordSameAsOne }
  , { walsCode := "apl", iso := "apy", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "apu", iso := "apu", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "aeg", iso := "arz", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "arg", iso := "afb", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "arq", iso := "acm", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "arj", iso := "afb", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "amr", iso := "ary", value := .indefiniteAffix }
  , { walsCode := "asy", iso := "apc", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "ana", iso := "aro", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "arp", iso := "ape", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "arc", iso := "aqc", value := .indefiniteWordSameAsOne }
  , { walsCode := "arm", iso := "hye", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "arw", iso := "hyw", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "aro", iso := "aia", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "ata", iso := "tay", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "au", iso := "avt", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "awp", iso := "kwi", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "awt", iso := "kmn", value := .indefiniteWordSameAsOne }
  , { walsCode := "aym", iso := "ayr", value := .indefiniteWordSameAsOne }
  , { walsCode := "azi", iso := "azb", value := .indefiniteWordSameAsOne }
  , { walsCode := "bab", iso := "bav", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "bag", iso := "bmi", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "bwc", iso := "bdr", value := .indefiniteWordSameAsOne }
  , { walsCode := "blt", iso := "bft", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "bbu", iso := "brm", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "bar", iso := "bfa", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "brp", iso := "bpe", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "bsk", iso := "bak", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "bsq", iso := "eus", value := .indefiniteWordSameAsOne }
  , { walsCode := "bkr", iso := "btx", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "bto", iso := "bbc", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "baw", iso := "bgr", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "bco", iso := "blc", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "bfg", iso := "grr", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "brf", iso := "rif", value := .indefiniteWordSameAsOne }
  , { walsCode := "bsi", iso := "siz", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "zag", iso := "zag", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "bik", iso := "bhw", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "bil", iso := "blb", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "bin", iso := "bhg", value := .indefiniteWordSameAsOne }
  , { walsCode := "bni", iso := "bin", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "bbw", iso := "gup", value := .indefiniteWordSameAsOne }
  , { walsCode := "bir", iso := "bom", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "bla", iso := "bla", value := .indefiniteAffix }
  , { walsCode := "bod", iso := "brx", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "btk", iso := "lbk", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "bre", iso := "bre", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "bdu", iso := "buu", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "bum", iso := "tkw", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "brm", iso := "mya", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "brn", iso := "bds", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "bya", iso := "bee", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "cax", iso := "", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "cnl", iso := "ram", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "cnt", iso := "yue", value := .indefiniteWordSameAsOne }
  , { walsCode := "cas", iso := "cbr", value := .indefiniteWordSameAsOne }
  , { walsCode := "ctl", iso := "cat", value := .indefiniteWordSameAsOne }
  , { walsCode := "ceb", iso := "ceb", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "chh", iso := "sgw", value := .indefiniteWordSameAsOne }
  , { walsCode := "chg", iso := "nbc", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "chc", iso := "che", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "che", iso := "chr", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "chi", iso := "cid", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "cmr", iso := "mrh", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "chs", iso := "csy", value := .indefiniteWordSameAsOne }
  , { walsCode := "cti", iso := "ctd", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ccm", iso := "cco", value := .indefiniteWordSameAsOne }
  , { walsCode := "cle", iso := "cle", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "cpl", iso := "cpa", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "cmy", iso := "chf", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "chr", iso := "crw", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "chk", iso := "ckt", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "cba", iso := "boi", value := .indefiniteAffix }
  , { walsCode := "chv", iso := "chv", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "cbo", iso := "cao", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "coc", iso := "cod", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "cmn", iso := "com", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "coo", iso := "csz", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "cop", iso := "cop", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "crn", iso := "cor", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "cup", iso := "cup", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "cze", iso := "ces", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "cem", iso := "cam", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "ddj", iso := "god", value := .indefiniteWordSameAsOne }
  , { walsCode := "dag", iso := "dgz", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "dga", iso := "dga", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "dgb", iso := "dag", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "dni", iso := "dni", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "dsh", iso := "dan", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "deg", iso := "deg", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "dhr", iso := "dhr", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "did", iso := "did", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "die", iso := "dih", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "dio", iso := "dyo", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "dlm", iso := "kbv", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "doy", iso := "dow", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "duk", iso := "dud", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "dmi", iso := "dus", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "dut", iso := "nld", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "eip", iso := "eip", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "egn", iso := "enn", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "eng", iso := "eng", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "epe", iso := "sja", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "err", iso := "erg", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "est", iso := "ekk", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "eud", iso := "", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "evn", iso := "eve", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "eve", iso := "evn", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ewe", iso := "ewe", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "fij", iso := "fij", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "fin", iso := "fin", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "pdp", iso := "ppo", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "fon", iso := "fon", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "fre", iso := "fra", value := .indefiniteWordSameAsOne }
  , { walsCode := "fri", iso := "fry", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "fut", iso := "fut", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "fye", iso := "pym", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "gnd", iso := "gqa", value := .indefiniteAffix }
  , { walsCode := "gae", iso := "gla", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "gah", iso := "gah", value := .indefiniteAffix }
  , { walsCode := "gar", iso := "grt", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "gbb", iso := "gbp", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "gel", iso := "nlg", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "ger", iso := "deu", value := .indefiniteWordSameAsOne }
  , { walsCode := "gil", iso := "glk", value := .indefiniteWordSameAsOne }
  , { walsCode := "goe", iso := "ank", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "gok", iso := "gkn", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "gln", iso := "gvf", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "gon", iso := "gno", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "grb", iso := "grj", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "grk", iso := "ell", value := .indefiniteWordSameAsOne }
  , { walsCode := "grw", iso := "kal", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "gua", iso := "gug", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "gul", iso := "kcm", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "gmw", iso := "gvs", value := .indefiniteWordSameAsOne }
  , { walsCode := "gnn", iso := "gww", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "gur", iso := "", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "gwa", iso := "gbr", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "gwo", iso := "kcg", value := .indefiniteWordSameAsOne }
  , { walsCode := "ga", iso := "gaa", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "hai", iso := "hai", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "hat", iso := "had", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "hau", iso := "hau", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "haw", iso := "haw", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "heb", iso := "heb", value := .indefiniteWordSameAsOne }
  , { walsCode := "hin", iso := "hin", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "hix", iso := "hix", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "hmo", iso := "hnj", value := .indefiniteWordSameAsOne }
  , { walsCode := "hoa", iso := "hoa", value := .indefiniteWordSameAsOne }
  , { walsCode := "htc", iso := "hus", value := .indefiniteWordSameAsOne }
  , { walsCode := "hmi", iso := "hto", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "hnd", iso := "hke", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "hun", iso := "hun", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "hzb", iso := "huz", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "isa", iso := "ksi", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "iaa", iso := "iai", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "iba", iso := "iba", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ice", iso := "isl", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "ijo", iso := "ijc", value := .indefiniteAffix }
  , { walsCode := "ika", iso := "arh", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "imo", iso := "imn", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ina", iso := "szp", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "ind", iso := "ind", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "ing", iso := "inh", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "irq", iso := "irk", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "iri", iso := "gle", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "ita", iso := "ita", value := .indefiniteWordSameAsOne }
  , { walsCode := "ite", iso := "itl", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "izi", iso := "izz", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "jab", iso := "jae", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "jak", iso := "jac", value := .indefiniteWordSameAsOne }
  , { walsCode := "jms", iso := "djm", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "jpn", iso := "jpn", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "jng", iso := "kac", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "juk", iso := "jbu", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "jmo", iso := "bex", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "juh", iso := "ktz", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "kad", iso := "xtc", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "kmk", iso := "xal", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "kma", iso := "kay", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "kan", iso := "ogo", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "knd", iso := "kan", value := .indefiniteWordSameAsOne }
  , { walsCode := "knr", iso := "knc", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "krc", iso := "krc", value := .indefiniteWordSameAsOne }
  , { walsCode := "kkp", iso := "kaa", value := .indefiniteWordSameAsOne }
  , { walsCode := "kbw", iso := "bwe", value := .indefiniteWordSameAsOne }
  , { walsCode := "ksg", iso := "ksw", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "kmj", iso := "kdj", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "kaa", iso := "arr", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "kau", iso := "pss", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "kay", iso := "gyd", value := .indefiniteWordSameAsOne }
  , { walsCode := "ket", iso := "ket", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "kew", iso := "kew", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "khl", iso := "klj", value := .indefiniteWordSameAsOne }
  , { walsCode := "khg", iso := "klr", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "kha", iso := "khk", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "kmh", iso := "kjl", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "khs", iso := "kha", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "klv", iso := "kij", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "klw", iso := "klb", value := .indefiniteAffix }
  , { walsCode := "knn", iso := "kfk", value := .indefiniteWordSameAsOne }
  , { walsCode := "kio", iso := "kio", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "kgz", iso := "kir", value := .indefiniteWordSameAsOne }
  , { walsCode := "kis", iso := "kss", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "kla", iso := "klu", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "kob", iso := "kpw", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "kkt", iso := "kkk", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "kmb", iso := "", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "xbi", iso := "xbi", value := .indefiniteWordSameAsOne }
  , { walsCode := "kni", iso := "kma", value := .indefiniteAffix }
  , { walsCode := "krn", iso := "kqz", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "kor", iso := "kor", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "kfe", iso := "kfz", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "krw", iso := "khe", value := .indefiniteAffix }
  , { walsCode := "kos", iso := "kos", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "kse", iso := "ses", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "kpo", iso := "kpo", value := .indefiniteAffix }
  , { walsCode := "kro", iso := "kgo", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "knc", iso := "uwa", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "knm", iso := "kun", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "krd", iso := "ckb", value := .indefiniteAffix }
  , { walsCode := "kut", iso := "kut", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "thy", iso := "thd", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "kwn", iso := "kwn", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "kwo", iso := "kmo", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "kyk", iso := "kyc", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "lad", iso := "lbj", value := .indefiniteAffix }
  , { walsCode := "lah", iso := "lhu", value := .indefiniteWordSameAsOne }
  , { walsCode := "lai", iso := "cnh", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "lkt", iso := "lkt", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "lal", iso := "ywt", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "lmh", iso := "slp", value := .indefiniteWordSameAsOne }
  , { walsCode := "lmg", iso := "hia", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "lmn", iso := "lmn", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "lmp", iso := "ljp", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "lan", iso := "laj", value := .indefiniteAffix }
  , { walsCode := "lao", iso := "lao", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "lat", iso := "lav", value := .indefiniteWordSameAsOne }
  , { walsCode := "lav", iso := "lvk", value := .indefiniteWordSameAsOne }
  , { walsCode := "lel", iso := "lln", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "llm", iso := "lef", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "len", iso := "tnl", value := .indefiniteWordSameAsOne }
  , { walsCode := "lep", iso := "lep", value := .indefiniteWordSameAsOne }
  , { walsCode := "lew", iso := "lww", value := .indefiniteWordSameAsOne }
  , { walsCode := "lez", iso := "lez", value := .indefiniteWordSameAsOne }
  , { walsCode := "lim", iso := "lif", value := .indefiniteAffix }
  , { walsCode := "lit", iso := "lit", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ara", iso := "arw", value := .indefiniteWordSameAsOne }
  , { walsCode := "lon", iso := "los", value := .indefiniteWordSameAsOne }
  , { walsCode := "lug", iso := "lgg", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "lbu", iso := "lun", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "luo", iso := "luo", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "luv", iso := "lue", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "myn", iso := "mhy", value := .indefiniteWordSameAsOne }
  , { walsCode := "mad", iso := "mhi", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "maa", iso := "mas", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mac", iso := "mbc", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mae", iso := "mmw", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "msn", iso := "mbq", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mkj", iso := "mkz", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mal", iso := "plt", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "mlu", iso := "mgl", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mam", iso := "mam", value := .indefiniteWordSameAsOne }
  , { walsCode := "mnm", iso := "mva", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mdn", iso := "mhq", value := .indefiniteAffix }
  , { walsCode := "mgg", iso := "mjg", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "mns", iso := "mns", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mao", iso := "mri", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "map", iso := "arn", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "mra", iso := "mec", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mhi", iso := "mar", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mrg", iso := "mrt", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "mar", iso := "mrc", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "mrq", iso := "", value := .indefiniteWordSameAsOne }
  , { walsCode := "mru", iso := "mhx", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mas", iso := "mcn", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "msl", iso := "mls", value := .indefiniteAffix }
  , { walsCode := "mka", iso := "mxx", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "may", iso := "ayz", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "mzn", iso := "mzn", value := .indefiniteWordSameAsOne }
  , { walsCode := "mzc", iso := "maq", value := .indefiniteWordSameAsOne }
  , { walsCode := "mbi", iso := "baw", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "mbm", iso := "mdd", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mei", iso := "mni", value := .indefiniteWordSameAsOne }
  , { walsCode := "mde", iso := "men", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "mea", iso := "mej", value := .indefiniteWordSameAsOne }
  , { walsCode := "mpt", iso := "mpt", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "mik", iso := "mjw", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "min", iso := "min", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mis", iso := "miq", value := .indefiniteWordSameAsOne }
  , { walsCode := "mxc", iso := "mig", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mxp", iso := "mil", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mxy", iso := "mpm", value := .indefiniteWordSameAsOne }
  , { walsCode := "miy", iso := "mkf", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "miz", iso := "lus", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mok", iso := "mkj", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "moa", iso := "mte", value := .indefiniteWordSameAsOne }
  , { walsCode := "moo", iso := "mos", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "mro", iso := "mor", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mtu", iso := "meu", value := .indefiniteWordSameAsOne }
  , { walsCode := "aoj", iso := "aoj", value := .indefiniteWordSameAsOne }
  , { walsCode := "mum", iso := "mzm", value := .indefiniteWordSameAsOne }
  , { walsCode := "mun", iso := "unr", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "mup", iso := "sur", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "mgu", iso := "mug", value := .indefiniteWordSameAsOne }
  , { walsCode := "mwo", iso := "mlv", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "nab", iso := "naf", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "nht", iso := "nhg", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "kho", iso := "naq", value := .indefiniteAffix }
  , { walsCode := "nmb", iso := "nab", value := .indefiniteAffix }
  , { walsCode := "nrg", iso := "sen", value := .indefiniteAffix }
  , { walsCode := "nph", iso := "npa", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "nas", iso := "nas", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ndb", iso := "nde", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ndj", iso := "djj", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ndo", iso := "ndo", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ndu", iso := "nmd", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ndy", iso := "djk", value := .indefiniteWordSameAsOne }
  , { walsCode := "nne", iso := "nen", value := .indefiniteWordSameAsOne }
  , { walsCode := "naj", iso := "aij", value := .indefiniteWordSameAsOne }
  , { walsCode := "nev", iso := "pia", value := .indefiniteWordSameAsOne }
  , { walsCode := "nwd", iso := "new", value := .indefiniteWordSameAsOne }
  , { walsCode := "ney", iso := "ney", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "ngd", iso := "nxg", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ngl", iso := "nig", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ngm", iso := "sba", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ngb", iso := "nga", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "nti", iso := "niy", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "ngi", iso := "wyb", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ngz", iso := "ngi", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "nia", iso := "nia", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "nca", iso := "caq", value := .indefiniteWordSameAsOne }
  , { walsCode := "nsg", iso := "ncg", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "nif", iso := "num", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "nkn", iso := "nko", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "non", iso := "nhu", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "noo", iso := "snf", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "nor", iso := "nor", value := .indefiniteWordSameAsOne }
  , { walsCode := "nua", iso := "nxl", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "nbd", iso := "dgl", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "nun", iso := "nut", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "nug", iso := "nuy", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "nym", iso := "nym", value := .indefiniteWordSameAsOne }
  , { walsCode := "nyu", iso := "nyv", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "ood", iso := "ood", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "obo", iso := "ann", value := .indefiniteWordSameAsOne }
  , { walsCode := "ocu", iso := "ocu", value := .indefiniteWordSameAsOne }
  , { walsCode := "obg", iso := "ogu", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "oji", iso := "", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "ond", iso := "one", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "orh", iso := "hae", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "orw", iso := "ssn", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "osa", iso := "osa", value := .indefiniteWordSameAsOne }
  , { walsCode := "paa", iso := "pqa", value := .indefiniteWordSameAsOne }
  , { walsCode := "pms", iso := "pma", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "pno", iso := "pao", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "pal", iso := "pau", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "plk", iso := "plu", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "pan", iso := "pan", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "psh", iso := "pst", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "psm", iso := "pqm", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "pau", iso := "pad", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "per", iso := "pip", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "pia", iso := "pid", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "pga", iso := "plg", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "pip", iso := "ppl", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "prh", iso := "myp", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "poh", iso := "pon", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "pol", iso := "pol", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "pso", iso := "pom", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "por", iso := "por", value := .indefiniteWordSameAsOne }
  , { walsCode := "pra", iso := "prn", value := .indefiniteWordSameAsOne }
  , { walsCode := "pul", iso := "puw", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "pur", iso := "tsz", value := .indefiniteWordSameAsOne }
  , { walsCode := "pae", iso := "pbb", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "qaf", iso := "aar", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "qia", iso := "", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "qhu", iso := "qub", value := .indefiniteAffix }
  , { walsCode := "qim", iso := "qvi", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "qui", iso := "qui", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "ram", iso := "rma", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "rap", iso := "rap", value := .indefiniteWordSameAsOne }
  , { walsCode := "raw", iso := "raw", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "rem", iso := "bfw", value := .indefiniteWordSameAsOne }
  , { walsCode := "res", iso := "rgr", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ret", iso := "tnc", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "rwe", iso := "rmw", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "rom", iso := "ron", value := .indefiniteWordSameAsOne }
  , { walsCode := "rov", iso := "rug", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "run", iso := "rou", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "rus", iso := "rus", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "sno", iso := "sme", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "slb", iso := "sbe", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "sam", iso := "smo", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "sdw", iso := "sad", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "stl", iso := "sat", value := .indefiniteWordSameAsOne }
  , { walsCode := "src", iso := "srs", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "sar", iso := "dju", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "svs", iso := "svs", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "scr", iso := "hbs", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "sna", iso := "scl", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "shk", iso := "shp", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "sia", iso := "snp", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "sir", iso := "sjr", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "sid", iso := "sid", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "skk", iso := "sip", value := .indefiniteWordSameAsOne }
  , { walsCode := "sio", iso := "xsi", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "qum", iso := "qum", value := .indefiniteWordSameAsOne }
  , { walsCode := "srn", iso := "srq", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "sro", iso := "ssd", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "sis", iso := "baa", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "sla", iso := "den", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "som", iso := "som", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "stn", iso := "nso", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "tou", iso := "wib", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "spa", iso := "spa", value := .indefiniteWordSameAsOne }
  , { walsCode := "squ", iso := "squ", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "sti", iso := "", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "sul", iso := "sua", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "sun", iso := "sun", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "sup", iso := "spp", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "swe", iso := "swe", value := .indefiniteWordSameAsOne }
  , { walsCode := "tab", iso := "mky", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "tac", iso := "tna", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "tah", iso := "tah", value := .indefiniteWordSameAsOne }
  , { walsCode := "taf", iso := "sps", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "taj", iso := "tgk", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "tkl", iso := "tkm", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "tam", iso := "taj", value := .indefiniteWordSameAsOne }
  , { walsCode := "tce", iso := "tar", value := .indefiniteWordSameAsOne }
  , { walsCode := "twe", iso := "tac", value := .indefiniteWordSameAsOne }
  , { walsCode := "tar", iso := "tae", value := .indefiniteWordSameAsOne }
  , { walsCode := "tas", iso := "shi", value := .indefiniteAffix }
  , { walsCode := "tvo", iso := "tat", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "tts", iso := "tks", value := .indefiniteWordSameAsOne }
  , { walsCode := "tau", iso := "tya", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "tne", iso := "tem", value := .indefiniteAffix }
  , { walsCode := "ten", iso := "tex", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "tee", iso := "tee", value := .indefiniteWordSameAsOne }
  , { walsCode := "tep", iso := "tpt", value := .indefiniteWordSameAsOne }
  , { walsCode := "tpn", iso := "ntp", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "tps", iso := "stp", value := .indefiniteWordSameAsOne }
  , { walsCode := "tes", iso := "teo", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ttn", iso := "tet", value := .indefiniteWordSameAsOne }
  , { walsCode := "tha", iso := "tha", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "tmo", iso := "bod", value := .indefiniteWordSameAsOne }
  , { walsCode := "tid", iso := "tvo", value := .indefiniteWordSameAsOne }
  , { walsCode := "tgk", iso := "tgc", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "tig", iso := "tir", value := .indefiniteWordSameAsOne }
  , { walsCode := "tgr", iso := "tig", value := .indefiniteWordSameAsOne }
  , { walsCode := "tja", iso := "dih", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "tik", iso := "tik", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "tin", iso := "cir", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "tiw", iso := "tiw", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "tla", iso := "ksd", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "tng", iso := "ton", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "tri", iso := "trc", value := .indefiniteWordSameAsOne }
  , { walsCode := "tgl", iso := "tsj", value := .indefiniteWordSameAsOne }
  , { walsCode := "tsi", iso := "tsi", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "ttu", iso := "bbl", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "tbu", iso := "", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "tuc", iso := "tuo", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "tuk", iso := "", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "tul", iso := "tcy", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "tnk", iso := "lcm", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "tna", iso := "tuv", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "tur", iso := "tur", value := .indefiniteWordSameAsOne }
  , { walsCode := "tte", iso := "tta", value := .indefiniteAffix }
  , { walsCode := "tvt", iso := "tvt", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "tvl", iso := "tvl", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "tuv", iso := "tyv", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "tzu", iso := "tzj", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "tsh", iso := "par", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "uby", iso := "uby", value := .indefiniteAffix }
  , { walsCode := "ukr", iso := "ukr", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "uli", iso := "uli", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ung", iso := "ung", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "ura", iso := "uur", value := .indefiniteWordSameAsOne }
  , { walsCode := "url", iso := "urk", value := .noIndefiniteButDefiniteArticle }
  ]

private def allData_1 : List (Datapoint IndefiniteArticleType) :=
  [ { walsCode := "urd", iso := "urd", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "urk", iso := "urb", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "vai", iso := "vai", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "wah", iso := "", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "wal", iso := "van", value := .indefiniteWordSameAsOne }
  , { walsCode := "wbn", iso := "wms", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "wme", iso := "wme", value := .indefiniteWordSameAsOne }
  , { walsCode := "war", iso := "pav", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "wsk", iso := "wsk", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "wel", iso := "cym", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "wch", iso := "mzh", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "wik", iso := "yok", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "wol", iso := "woe", value := .indefiniteWordSameAsOne }
  , { walsCode := "wlf", iso := "wol", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "wor", iso := "wro", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "xas", iso := "kao", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "xho", iso := "xho", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "xar", iso := "ane", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ygr", iso := "ygr", value := .indefiniteWordSameAsOne }
  , { walsCode := "yag", iso := "yad", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "yap", iso := "yap", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "yaq", iso := "yaq", value := .indefiniteWordDistinctFromOne }
  , { walsCode := "yid", iso := "yii", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "yim", iso := "yee", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "yok", iso := "yok", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "yor", iso := "yor", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "yuc", iso := "yuc", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "yko", iso := "yux", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "ypk", iso := "esu", value := .noDefiniteOrIndefiniteArticle }
  , { walsCode := "yuw", iso := "kld", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "zai", iso := "zai", value := .indefiniteWordSameAsOne }
  , { walsCode := "zar", iso := "dje", value := .indefiniteWordSameAsOne }
  , { walsCode := "zay", iso := "zay", value := .noIndefiniteButDefiniteArticle }
  , { walsCode := "zul", iso := "zul", value := .noDefiniteOrIndefiniteArticle }
  ]

/-- Complete WALS 38A dataset (534 languages). -/
def allData : List (Datapoint IndefiniteArticleType) := allData_0 ++ allData_1

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F38A
