import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 48A: Person Marking on Adpositions
@cite{wals-2013}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 48A`.

Chapter 48, 378 languages.
-/

namespace Core.WALS.F48A

/-- WALS 48A values. -/
inductive PersonMarkingOnAdpositions where
  /-- No adpositions (63 languages). -/
  | noAdpositions
  /-- No person marking (209 languages). -/
  | noPersonMarking
  /-- Pronouns only (83 languages). -/
  | pronounsOnly
  /-- Pronouns and nouns (23 languages). -/
  | pronounsAndNouns
  deriving DecidableEq, BEq, Repr

/-- Complete WALS 48A dataset (378 languages). -/
def allData : List (Datapoint PersonMarkingOnAdpositions) :=
  [ { walsCode := "ani", iso := "hnh", value := .noPersonMarking }
  , { walsCode := "abi", iso := "axb", value := .noPersonMarking }
  , { walsCode := "abk", iso := "abk", value := .pronounsAndNouns }
  , { walsCode := "abu", iso := "kgr", value := .noPersonMarking }
  , { walsCode := "ace", iso := "ace", value := .noPersonMarking }
  , { walsCode := "acm", iso := "acv", value := .noAdpositions }
  , { walsCode := "aco", iso := "kjq", value := .noPersonMarking }
  , { walsCode := "adz", iso := "adz", value := .noPersonMarking }
  , { walsCode := "ain", iso := "ain", value := .pronounsOnly }
  , { walsCode := "ala", iso := "amp", value := .noPersonMarking }
  , { walsCode := "alb", iso := "sqi", value := .noPersonMarking }
  , { walsCode := "ame", iso := "aey", value := .noPersonMarking }
  , { walsCode := "amh", iso := "amh", value := .pronounsOnly }
  , { walsCode := "amu", iso := "ame", value := .noPersonMarking }
  , { walsCode := "anj", iso := "aty", value := .pronounsOnly }
  , { walsCode := "ane", iso := "anz", value := .pronounsOnly }
  , { walsCode := "apu", iso := "apu", value := .noAdpositions }
  , { walsCode := "abn", iso := "ard", value := .noAdpositions }
  , { walsCode := "aeg", iso := "arz", value := .pronounsOnly }
  , { walsCode := "ana", iso := "aro", value := .noPersonMarking }
  , { walsCode := "arp", iso := "ape", value := .noAdpositions }
  , { walsCode := "arm", iso := "hye", value := .noPersonMarking }
  , { walsCode := "asm", iso := "cns", value := .noPersonMarking }
  , { walsCode := "atk", iso := "aqp", value := .noPersonMarking }
  , { walsCode := "ata", iso := "tay", value := .noPersonMarking }
  , { walsCode := "au", iso := "avt", value := .pronounsOnly }
  , { walsCode := "awp", iso := "kwi", value := .noPersonMarking }
  , { walsCode := "awt", iso := "kmn", value := .noAdpositions }
  , { walsCode := "aym", iso := "ayr", value := .pronounsOnly }
  , { walsCode := "bab", iso := "bav", value := .noPersonMarking }
  , { walsCode := "bag", iso := "bmi", value := .pronounsOnly }
  , { walsCode := "bam", iso := "bam", value := .noPersonMarking }
  , { walsCode := "bnj", iso := "bdy", value := .noAdpositions }
  , { walsCode := "baa", iso := "bbb", value := .noPersonMarking }
  , { walsCode := "brs", iso := "bsn", value := .noPersonMarking }
  , { walsCode := "bar", iso := "bfa", value := .noPersonMarking }
  , { walsCode := "bsq", iso := "eus", value := .noPersonMarking }
  , { walsCode := "bkr", iso := "btx", value := .noPersonMarking }
  , { walsCode := "baw", iso := "bgr", value := .noPersonMarking }
  , { walsCode := "bej", iso := "bej", value := .noPersonMarking }
  , { walsCode := "bma", iso := "tzm", value := .pronounsOnly }
  , { walsCode := "ber", iso := "wti", value := .pronounsOnly }
  , { walsCode := "bln", iso := "byn", value := .noPersonMarking }
  , { walsCode := "brr", iso := "bor", value := .pronounsAndNouns }
  , { walsCode := "brh", iso := "brh", value := .noPersonMarking }
  , { walsCode := "bri", iso := "bzd", value := .noPersonMarking }
  , { walsCode := "bro", iso := "tcs", value := .noPersonMarking }
  , { walsCode := "brm", iso := "mya", value := .noPersonMarking }
  , { walsCode := "brn", iso := "bds", value := .noPersonMarking }
  , { walsCode := "bur", iso := "bsk", value := .pronounsOnly }
  , { walsCode := "bya", iso := "bee", value := .noPersonMarking }
  , { walsCode := "cah", iso := "chl", value := .noPersonMarking }
  , { walsCode := "cax", iso := "", value := .noPersonMarking }
  , { walsCode := "can", iso := "cbu", value := .pronounsOnly }
  , { walsCode := "cnl", iso := "ram", value := .pronounsOnly }
  , { walsCode := "cap", iso := "kaq", value := .noPersonMarking }
  , { walsCode := "car", iso := "car", value := .pronounsAndNouns }
  , { walsCode := "cav", iso := "cav", value := .noPersonMarking }
  , { walsCode := "cyv", iso := "cyb", value := .noAdpositions }
  , { walsCode := "cha", iso := "cha", value := .pronounsOnly }
  , { walsCode := "cpn", iso := "cdm", value := .noPersonMarking }
  , { walsCode := "cle", iso := "cle", value := .pronounsOnly }
  , { walsCode := "ckl", iso := "chh", value := .noPersonMarking }
  , { walsCode := "chr", iso := "crw", value := .noPersonMarking }
  , { walsCode := "chk", iso := "ckt", value := .noPersonMarking }
  , { walsCode := "cba", iso := "boi", value := .noAdpositions }
  , { walsCode := "cbo", iso := "cao", value := .pronounsOnly }
  , { walsCode := "cmn", iso := "com", value := .noPersonMarking }
  , { walsCode := "cmx", iso := "coo", value := .noPersonMarking }
  , { walsCode := "coo", iso := "csz", value := .noAdpositions }
  , { walsCode := "cop", iso := "cop", value := .pronounsOnly }
  , { walsCode := "cor", iso := "crn", value := .pronounsAndNouns }
  , { walsCode := "cre", iso := "crk", value := .noAdpositions }
  , { walsCode := "cri", iso := "crh", value := .noPersonMarking }
  , { walsCode := "cub", iso := "cub", value := .noPersonMarking }
  , { walsCode := "dag", iso := "dgz", value := .noPersonMarking }
  , { walsCode := "dga", iso := "dga", value := .noPersonMarking }
  , { walsCode := "dgr", iso := "dta", value := .noPersonMarking }
  , { walsCode := "dni", iso := "dni", value := .pronounsOnly }
  , { walsCode := "dio", iso := "dyo", value := .noPersonMarking }
  , { walsCode := "diz", iso := "mdx", value := .noPersonMarking }
  , { walsCode := "don", iso := "kmc", value := .noPersonMarking }
  , { walsCode := "doy", iso := "dow", value := .noPersonMarking }
  , { walsCode := "dre", iso := "dhv", value := .noPersonMarking }
  , { walsCode := "dum", iso := "vam", value := .noPersonMarking }
  , { walsCode := "dut", iso := "nld", value := .noPersonMarking }
  , { walsCode := "eka", iso := "ekg", value := .noPersonMarking }
  , { walsCode := "eng", iso := "eng", value := .noPersonMarking }
  , { walsCode := "epe", iso := "sja", value := .noPersonMarking }
  , { walsCode := "err", iso := "erg", value := .pronounsOnly }
  , { walsCode := "eve", iso := "evn", value := .pronounsOnly }
  , { walsCode := "ewe", iso := "ewe", value := .pronounsOnly }
  , { walsCode := "fij", iso := "fij", value := .pronounsAndNouns }
  , { walsCode := "fin", iso := "fin", value := .pronounsOnly }
  , { walsCode := "fre", iso := "fra", value := .noPersonMarking }
  , { walsCode := "fua", iso := "fub", value := .noPersonMarking }
  , { walsCode := "fur", iso := "fvr", value := .pronounsOnly }
  , { walsCode := "gar", iso := "grt", value := .noAdpositions }
  , { walsCode := "geo", iso := "kat", value := .noPersonMarking }
  , { walsCode := "ger", iso := "deu", value := .noPersonMarking }
  , { walsCode := "god", iso := "gdo", value := .noPersonMarking }
  , { walsCode := "goo", iso := "gni", value := .noPersonMarking }
  , { walsCode := "grb", iso := "grj", value := .noPersonMarking }
  , { walsCode := "grk", iso := "ell", value := .noPersonMarking }
  , { walsCode := "grw", iso := "kal", value := .pronounsOnly }
  , { walsCode := "gua", iso := "gug", value := .pronounsOnly }
  , { walsCode := "gud", iso := "gde", value := .noPersonMarking }
  , { walsCode := "gmw", iso := "gvs", value := .noPersonMarking }
  , { walsCode := "guu", iso := "kky", value := .noAdpositions }
  , { walsCode := "hai", iso := "hai", value := .noPersonMarking }
  , { walsCode := "hlu", iso := "hur", value := .noAdpositions }
  , { walsCode := "hmr", iso := "amf", value := .noAdpositions }
  , { walsCode := "ham", iso := "hmt", value := .noAdpositions }
  , { walsCode := "hat", iso := "had", value := .noPersonMarking }
  , { walsCode := "hau", iso := "hau", value := .pronounsOnly }
  , { walsCode := "heb", iso := "heb", value := .pronounsOnly }
  , { walsCode := "hin", iso := "hin", value := .noPersonMarking }
  , { walsCode := "hix", iso := "hix", value := .pronounsOnly }
  , { walsCode := "hmo", iso := "hnj", value := .noPersonMarking }
  , { walsCode := "hua", iso := "ygr", value := .noPersonMarking }
  , { walsCode := "hmi", iso := "hto", value := .pronounsOnly }
  , { walsCode := "hun", iso := "hun", value := .pronounsOnly }
  , { walsCode := "hzb", iso := "huz", value := .noPersonMarking }
  , { walsCode := "igb", iso := "ibo", value := .noPersonMarking }
  , { walsCode := "ijo", iso := "ijc", value := .pronounsOnly }
  , { walsCode := "ika", iso := "arh", value := .noPersonMarking }
  , { walsCode := "imo", iso := "imn", value := .noPersonMarking }
  , { walsCode := "ind", iso := "ind", value := .noPersonMarking }
  , { walsCode := "ing", iso := "inh", value := .noPersonMarking }
  , { walsCode := "iqu", iso := "iqu", value := .pronounsOnly }
  , { walsCode := "irq", iso := "irk", value := .noPersonMarking }
  , { walsCode := "iri", iso := "gle", value := .pronounsOnly }
  , { walsCode := "ita", iso := "ita", value := .noPersonMarking }
  , { walsCode := "jak", iso := "jac", value := .pronounsAndNouns }
  , { walsCode := "jpn", iso := "jpn", value := .noPersonMarking }
  , { walsCode := "jaq", iso := "jqr", value := .noAdpositions }
  , { walsCode := "juh", iso := "ktz", value := .noPersonMarking }
  , { walsCode := "kgu", iso := "ktg", value := .noAdpositions }
  , { walsCode := "knd", iso := "kan", value := .noPersonMarking }
  , { walsCode := "knr", iso := "knc", value := .noPersonMarking }
  , { walsCode := "kpm", iso := "pam", value := .noPersonMarking }
  , { walsCode := "kna", iso := "ktn", value := .pronounsOnly }
  , { walsCode := "krk", iso := "kyh", value := .noPersonMarking }
  , { walsCode := "kas", iso := "kas", value := .noPersonMarking }
  , { walsCode := "kws", iso := "xaw", value := .pronounsAndNouns }
  , { walsCode := "kyl", iso := "eky", value := .noPersonMarking }
  , { walsCode := "kay", iso := "gyd", value := .noAdpositions }
  , { walsCode := "ker", iso := "ker", value := .noPersonMarking }
  , { walsCode := "ket", iso := "ket", value := .pronounsAndNouns }
  , { walsCode := "kew", iso := "kew", value := .noPersonMarking }
  , { walsCode := "kha", iso := "khk", value := .noPersonMarking }
  , { walsCode := "khs", iso := "kha", value := .noPersonMarking }
  , { walsCode := "khm", iso := "khm", value := .noPersonMarking }
  , { walsCode := "kmu", iso := "kjg", value := .noPersonMarking }
  , { walsCode := "klv", iso := "kij", value := .pronounsOnly }
  , { walsCode := "kio", iso := "kio", value := .noAdpositions }
  , { walsCode := "krb", iso := "gil", value := .pronounsAndNouns }
  , { walsCode := "kis", iso := "kss", value := .noPersonMarking }
  , { walsCode := "koa", iso := "cku", value := .pronounsOnly }
  , { walsCode := "kob", iso := "kpw", value := .noPersonMarking }
  , { walsCode := "klk", iso := "xuo", value := .noPersonMarking }
  , { walsCode := "kom", iso := "xom", value := .noPersonMarking }
  , { walsCode := "kon", iso := "kng", value := .noPersonMarking }
  , { walsCode := "kjo", iso := "kjc", value := .noPersonMarking }
  , { walsCode := "kor", iso := "kor", value := .noPersonMarking }
  , { walsCode := "kfe", iso := "kfz", value := .pronounsOnly }
  , { walsCode := "kos", iso := "kos", value := .pronounsOnly }
  , { walsCode := "kch", iso := "khq", value := .noPersonMarking }
  , { walsCode := "kse", iso := "ses", value := .noPersonMarking }
  , { walsCode := "kro", iso := "kgo", value := .noPersonMarking }
  , { walsCode := "kuk", iso := "bfa", value := .noPersonMarking }
  , { walsCode := "knm", iso := "kun", value := .noPersonMarking }
  , { walsCode := "krd", iso := "ckb", value := .pronounsOnly }
  , { walsCode := "kut", iso := "kut", value := .noAdpositions }
  , { walsCode := "kwz", iso := "xwa", value := .noAdpositions }
  , { walsCode := "lad", iso := "lbj", value := .noPersonMarking }
  , { walsCode := "lah", iso := "lhu", value := .noPersonMarking }
  , { walsCode := "lak", iso := "lbe", value := .noPersonMarking }
  , { walsCode := "lkt", iso := "lkt", value := .pronounsOnly }
  , { walsCode := "lan", iso := "laj", value := .pronounsOnly }
  , { walsCode := "lrk", iso := "alo", value := .pronounsOnly }
  , { walsCode := "lat", iso := "lav", value := .noPersonMarking }
  , { walsCode := "lav", iso := "lvk", value := .pronounsAndNouns }
  , { walsCode := "lel", iso := "lln", value := .noPersonMarking }
  , { walsCode := "lep", iso := "lep", value := .noPersonMarking }
  , { walsCode := "lez", iso := "lez", value := .noPersonMarking }
  , { walsCode := "lim", iso := "lif", value := .noPersonMarking }
  , { walsCode := "ara", iso := "arw", value := .pronounsOnly }
  , { walsCode := "luv", iso := "lue", value := .noPersonMarking }
  , { walsCode := "mle", iso := "mdy", value := .noAdpositions }
  , { walsCode := "mab", iso := "mde", value := .pronounsOnly }
  , { walsCode := "mac", iso := "mbc", value := .pronounsOnly }
  , { walsCode := "mne", iso := "nmu", value := .noAdpositions }
  , { walsCode := "msn", iso := "mbq", value := .noPersonMarking }
  , { walsCode := "mak", iso := "myh", value := .noAdpositions }
  , { walsCode := "mal", iso := "plt", value := .pronounsOnly }
  , { walsCode := "mlk", iso := "mpb", value := .noAdpositions }
  , { walsCode := "mnd", iso := "cmn", value := .noPersonMarking }
  , { walsCode := "myi", iso := "mpc", value := .noAdpositions }
  , { walsCode := "mao", iso := "mri", value := .noPersonMarking }
  , { walsCode := "map", iso := "arn", value := .noPersonMarking }
  , { walsCode := "mku", iso := "zmr", value := .noPersonMarking }
  , { walsCode := "mar", iso := "mrc", value := .noAdpositions }
  , { walsCode := "mrd", iso := "mrz", value := .noPersonMarking }
  , { walsCode := "mrt", iso := "vma", value := .noAdpositions }
  , { walsCode := "msl", iso := "mls", value := .noAdpositions }
  , { walsCode := "mau", iso := "mph", value := .noPersonMarking }
  , { walsCode := "mcr", iso := "mfe", value := .noPersonMarking }
  , { walsCode := "may", iso := "ayz", value := .pronounsAndNouns }
  , { walsCode := "mby", iso := "myb", value := .pronounsOnly }
  , { walsCode := "mei", iso := "mni", value := .noPersonMarking }
  , { walsCode := "mde", iso := "men", value := .noPersonMarking }
  , { walsCode := "mis", iso := "miq", value := .noPersonMarking }
  , { walsCode := "mss", iso := "skd", value := .noAdpositions }
  , { walsCode := "mxc", iso := "mig", value := .pronounsOnly }
  , { walsCode := "miz", iso := "lus", value := .noPersonMarking }
  , { walsCode := "mlm", iso := "mra", value := .noPersonMarking }
  , { walsCode := "moh", iso := "moh", value := .noAdpositions }
  , { walsCode := "moa", iso := "mte", value := .noPersonMarking }
  , { walsCode := "mum", iso := "mzm", value := .noPersonMarking }
  , { walsCode := "mna", iso := "mnb", value := .noPersonMarking }
  , { walsCode := "mun", iso := "unr", value := .noPersonMarking }
  , { walsCode := "mup", iso := "sur", value := .pronounsOnly }
  , { walsCode := "mrl", iso := "mur", value := .pronounsOnly }
  , { walsCode := "nad", iso := "mbj", value := .noPersonMarking }
  , { walsCode := "nht", iso := "nhg", value := .pronounsAndNouns }
  , { walsCode := "nak", iso := "nak", value := .noPersonMarking }
  , { walsCode := "kho", iso := "naq", value := .noPersonMarking }
  , { walsCode := "nmb", iso := "nab", value := .noAdpositions }
  , { walsCode := "nai", iso := "gld", value := .noAdpositions }
  , { walsCode := "nan", iso := "niq", value := .noPersonMarking }
  , { walsCode := "nas", iso := "nas", value := .noPersonMarking }
  , { walsCode := "nav", iso := "nav", value := .pronounsAndNouns }
  , { walsCode := "ndo", iso := "ndo", value := .noPersonMarking }
  , { walsCode := "ndy", iso := "djk", value := .noPersonMarking }
  , { walsCode := "ntu", iso := "yrk", value := .pronounsOnly }
  , { walsCode := "nez", iso := "nez", value := .noAdpositions }
  , { walsCode := "ngl", iso := "nig", value := .noAdpositions }
  , { walsCode := "ngk", iso := "nam", value := .noAdpositions }
  , { walsCode := "nti", iso := "niy", value := .pronounsOnly }
  , { walsCode := "ngi", iso := "wyb", value := .noAdpositions }
  , { walsCode := "nbr", iso := "gym", value := .noPersonMarking }
  , { walsCode := "niv", iso := "niv", value := .pronounsOnly }
  , { walsCode := "nko", iso := "cgg", value := .pronounsOnly }
  , { walsCode := "noo", iso := "snf", value := .pronounsOnly }
  , { walsCode := "nbd", iso := "dgl", value := .pronounsOnly }
  , { walsCode := "nug", iso := "nuy", value := .noAdpositions }
  , { walsCode := "nup", iso := "nup", value := .noPersonMarking }
  , { walsCode := "nuu", iso := "nuk", value := .noAdpositions }
  , { walsCode := "nyu", iso := "nyv", value := .noPersonMarking }
  , { walsCode := "ond", iso := "one", value := .noAdpositions }
  , { walsCode := "orh", iso := "hae", value := .noPersonMarking }
  , { walsCode := "oss", iso := "oss", value := .noPersonMarking }
  , { walsCode := "otm", iso := "ote", value := .noPersonMarking }
  , { walsCode := "pms", iso := "pma", value := .pronounsOnly }
  , { walsCode := "pai", iso := "pwn", value := .noPersonMarking }
  , { walsCode := "pal", iso := "pau", value := .noPersonMarking }
  , { walsCode := "plk", iso := "plu", value := .pronounsAndNouns }
  , { walsCode := "pny", iso := "pnw", value := .noAdpositions }
  , { walsCode := "psm", iso := "pqm", value := .noAdpositions }
  , { walsCode := "pau", iso := "pad", value := .noPersonMarking }
  , { walsCode := "pec", iso := "pay", value := .noAdpositions }
  , { walsCode := "prs", iso := "pes", value := .pronounsOnly }
  , { walsCode := "pip", iso := "ppl", value := .pronounsAndNouns }
  , { walsCode := "prh", iso := "myp", value := .noPersonMarking }
  , { walsCode := "pit", iso := "pjt", value := .noPersonMarking }
  , { walsCode := "pol", iso := "pol", value := .noPersonMarking }
  , { walsCode := "pso", iso := "pom", value := .noPersonMarking }
  , { walsCode := "psj", iso := "poe", value := .noPersonMarking }
  , { walsCode := "pur", iso := "tsz", value := .noPersonMarking }
  , { walsCode := "par", iso := "lkr", value := .noPersonMarking }
  , { walsCode := "qaw", iso := "alc", value := .noPersonMarking }
  , { walsCode := "qim", iso := "qvi", value := .noPersonMarking }
  , { walsCode := "qui", iso := "qui", value := .noAdpositions }
  , { walsCode := "ram", iso := "rma", value := .pronounsOnly }
  , { walsCode := "rap", iso := "rap", value := .noPersonMarking }
  , { walsCode := "rem", iso := "bfw", value := .noPersonMarking }
  , { walsCode := "ret", iso := "tnc", value := .pronounsOnly }
  , { walsCode := "rus", iso := "rus", value := .noPersonMarking }
  , { walsCode := "sah", iso := "saj", value := .noPersonMarking }
  , { walsCode := "sal", iso := "sln", value := .pronounsOnly }
  , { walsCode := "syu", iso := "sll", value := .noPersonMarking }
  , { walsCode := "sam", iso := "smo", value := .noPersonMarking }
  , { walsCode := "san", iso := "sag", value := .noPersonMarking }
  , { walsCode := "snm", iso := "xsu", value := .noPersonMarking }
  , { walsCode := "srm", iso := "srm", value := .noPersonMarking }
  , { walsCode := "saw", iso := "hvn", value := .noPersonMarking }
  , { walsCode := "slp", iso := "spl", value := .noPersonMarking }
  , { walsCode := "sel", iso := "ona", value := .pronounsOnly }
  , { walsCode := "sem", iso := "nsm", value := .noPersonMarking }
  , { walsCode := "sml", iso := "sza", value := .noPersonMarking }
  , { walsCode := "snt", iso := "set", value := .noPersonMarking }
  , { walsCode := "shk", iso := "shp", value := .noPersonMarking }
  , { walsCode := "siu", iso := "sis", value := .noAdpositions }
  , { walsCode := "sla", iso := "den", value := .pronounsOnly }
  , { walsCode := "so", iso := "teu", value := .pronounsOnly }
  , { walsCode := "spa", iso := "spa", value := .noPersonMarking }
  , { walsCode := "squ", iso := "squ", value := .noAdpositions }
  , { walsCode := "sue", iso := "sue", value := .noPersonMarking }
  , { walsCode := "sun", iso := "sun", value := .noPersonMarking }
  , { walsCode := "sup", iso := "spp", value := .noPersonMarking }
  , { walsCode := "swa", iso := "swh", value := .noPersonMarking }
  , { walsCode := "tab", iso := "mky", value := .noPersonMarking }
  , { walsCode := "tag", iso := "tgl", value := .noAdpositions }
  , { walsCode := "tap", iso := "gpn", value := .noAdpositions }
  , { walsCode := "tkl", iso := "tkm", value := .pronounsAndNouns }
  , { walsCode := "tau", iso := "tya", value := .noAdpositions }
  , { walsCode := "taw", iso := "tbo", value := .pronounsOnly }
  , { walsCode := "tmr", iso := "tea", value := .pronounsOnly }
  , { walsCode := "tpn", iso := "ntp", value := .pronounsOnly }
  , { walsCode := "trb", iso := "tfr", value := .noPersonMarking }
  , { walsCode := "tha", iso := "tha", value := .noPersonMarking }
  , { walsCode := "tid", iso := "tvo", value := .noPersonMarking }
  , { walsCode := "tgk", iso := "tgc", value := .pronounsOnly }
  , { walsCode := "tja", iso := "dih", value := .noAdpositions }
  , { walsCode := "tin", iso := "cir", value := .noPersonMarking }
  , { walsCode := "tir", iso := "tri", value := .pronounsOnly }
  , { walsCode := "tiw", iso := "tiw", value := .noPersonMarking }
  , { walsCode := "tli", iso := "tli", value := .pronounsAndNouns }
  , { walsCode := "tol", iso := "jic", value := .noPersonMarking }
  , { walsCode := "tla", iso := "ksd", value := .noPersonMarking }
  , { walsCode := "tms", iso := "dto", value := .noPersonMarking }
  , { walsCode := "ton", iso := "tqw", value := .noPersonMarking }
  , { walsCode := "tot", iso := "tlc", value := .noPersonMarking }
  , { walsCode := "tri", iso := "trc", value := .pronounsOnly }
  , { walsCode := "tru", iso := "tpy", value := .noPersonMarking }
  , { walsCode := "tsi", iso := "tsi", value := .noPersonMarking }
  , { walsCode := "tso", iso := "tsu", value := .noPersonMarking }
  , { walsCode := "tuk", iso := "", value := .noPersonMarking }
  , { walsCode := "tun", iso := "tun", value := .noPersonMarking }
  , { walsCode := "tna", iso := "tuv", value := .noPersonMarking }
  , { walsCode := "tur", iso := "tur", value := .noPersonMarking }
  , { walsCode := "tzu", iso := "tzj", value := .pronounsAndNouns }
  , { walsCode := "udh", iso := "ude", value := .pronounsAndNouns }
  , { walsCode := "uma", iso := "ppk", value := .pronounsOnly }
  , { walsCode := "una", iso := "mtg", value := .noPersonMarking }
  , { walsCode := "ung", iso := "ung", value := .noAdpositions }
  , { walsCode := "ura", iso := "uur", value := .pronounsOnly }
  , { walsCode := "uhi", iso := "urf", value := .noAdpositions }
  , { walsCode := "urk", iso := "urb", value := .pronounsOnly }
  , { walsCode := "usa", iso := "wnu", value := .pronounsOnly }
  , { walsCode := "vie", iso := "vie", value := .noPersonMarking }
  , { walsCode := "wam", iso := "wmb", value := .noAdpositions }
  , { walsCode := "wbn", iso := "wms", value := .noPersonMarking }
  , { walsCode := "wao", iso := "auc", value := .noPersonMarking }
  , { walsCode := "wap", iso := "wao", value := .noPersonMarking }
  , { walsCode := "wra", iso := "wba", value := .noPersonMarking }
  , { walsCode := "wrd", iso := "wrr", value := .noAdpositions }
  , { walsCode := "wrk", iso := "gae", value := .pronounsOnly }
  , { walsCode := "war", iso := "pav", value := .pronounsAndNouns }
  , { walsCode := "was", iso := "was", value := .pronounsOnly }
  , { walsCode := "wsk", iso := "wsk", value := .pronounsAndNouns }
  , { walsCode := "wel", iso := "cym", value := .pronounsOnly }
  , { walsCode := "wma", iso := "mqs", value := .noPersonMarking }
  , { walsCode := "wic", iso := "wic", value := .noAdpositions }
  , { walsCode := "wch", iso := "mzh", value := .noAdpositions }
  , { walsCode := "wik", iso := "yok", value := .noAdpositions }
  , { walsCode := "win", iso := "wnw", value := .noAdpositions }
  , { walsCode := "xok", iso := "xok", value := .noPersonMarking }
  , { walsCode := "yag", iso := "yad", value := .pronounsAndNouns }
  , { walsCode := "yap", iso := "yap", value := .pronounsOnly }
  , { walsCode := "yaq", iso := "yaq", value := .noPersonMarking }
  , { walsCode := "yaw", iso := "yva", value := .pronounsOnly }
  , { walsCode := "yel", iso := "yle", value := .pronounsAndNouns }
  , { walsCode := "yes", iso := "yss", value := .pronounsOnly }
  , { walsCode := "yid", iso := "yii", value := .noAdpositions }
  , { walsCode := "yim", iso := "yee", value := .pronounsOnly }
  , { walsCode := "yor", iso := "yor", value := .noPersonMarking }
  , { walsCode := "yuc", iso := "yuc", value := .pronounsOnly }
  , { walsCode := "yko", iso := "yux", value := .noPersonMarking }
  , { walsCode := "yuk", iso := "gcd", value := .noAdpositions }
  , { walsCode := "ypk", iso := "esu", value := .noAdpositions }
  , { walsCode := "yur", iso := "yur", value := .noPersonMarking }
  , { walsCode := "zan", iso := "zne", value := .noPersonMarking }
  , { walsCode := "zsq", iso := "zab", value := .pronounsOnly }
  , { walsCode := "zqc", iso := "zoc", value := .noAdpositions }
  , { walsCode := "zul", iso := "zul", value := .noPersonMarking }
  , { walsCode := "zun", iso := "zun", value := .noAdpositions }
  ]

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F48A
