import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 55A: Numeral Classifiers
@cite{wals-2013}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 55A`.

Chapter 55, 400 languages.
-/

namespace Core.WALS.F55A

/-- WALS 55A values. -/
inductive NumeralClassifiers where
  /-- Absent (260 languages). -/
  | absent
  /-- Optional (62 languages). -/
  | optional
  /-- Obligatory (78 languages). -/
  | obligatory
  deriving DecidableEq, BEq, Repr

/-- Complete WALS 55A dataset (400 languages). -/
def allData : List (Datapoint NumeralClassifiers) :=
  [ { walsCode := "xoo", iso := "nmn", value := .absent }
  , { walsCode := "xam", iso := "xam", value := .absent }
  , { walsCode := "abk", iso := "abk", value := .absent }
  , { walsCode := "abu", iso := "kgr", value := .obligatory }
  , { walsCode := "aco", iso := "kjq", value := .absent }
  , { walsCode := "ain", iso := "ain", value := .optional }
  , { walsCode := "agw", iso := "wbj", value := .absent }
  , { walsCode := "ala", iso := "amp", value := .absent }
  , { walsCode := "alb", iso := "sqi", value := .absent }
  , { walsCode := "aln", iso := "alp", value := .obligatory }
  , { walsCode := "amk", iso := "amr", value := .absent }
  , { walsCode := "aml", iso := "omb", value := .absent }
  , { walsCode := "amb", iso := "abt", value := .absent }
  , { walsCode := "ame", iso := "aey", value := .absent }
  , { walsCode := "amh", iso := "amh", value := .absent }
  , { walsCode := "ami", iso := "ami", value := .absent }
  , { walsCode := "apu", iso := "apu", value := .absent }
  , { walsCode := "arb", iso := "arl", value := .absent }
  , { walsCode := "aeg", iso := "arz", value := .absent }
  , { walsCode := "ako", iso := "acy", value := .absent }
  , { walsCode := "amr", iso := "ary", value := .absent }
  , { walsCode := "abo", iso := "arv", value := .absent }
  , { walsCode := "arm", iso := "hye", value := .absent }
  , { walsCode := "arz", iso := "hye", value := .optional }
  , { walsCode := "aro", iso := "aia", value := .absent }
  , { walsCode := "ass", iso := "asm", value := .obligatory }
  , { walsCode := "atk", iso := "aqp", value := .absent }
  , { walsCode := "ata", iso := "tay", value := .absent }
  , { walsCode := "ath", iso := "aph", value := .obligatory }
  , { walsCode := "ava", iso := "ava", value := .absent }
  , { walsCode := "awt", iso := "kmn", value := .absent }
  , { walsCode := "aze", iso := "", value := .optional }
  , { walsCode := "bgv", iso := "kva", value := .absent }
  , { walsCode := "bal", iso := "ban", value := .optional }
  , { walsCode := "bnv", iso := "bvv", value := .obligatory }
  , { walsCode := "brl", iso := "loy", value := .absent }
  , { walsCode := "bae", iso := "bae", value := .absent }
  , { walsCode := "bsq", iso := "eus", value := .absent }
  , { walsCode := "bkr", iso := "btx", value := .optional }
  , { walsCode := "beg", iso := "dbj", value := .optional }
  , { walsCode := "bel", iso := "byw", value := .obligatory }
  , { walsCode := "ben", iso := "ben", value := .obligatory }
  , { walsCode := "bit", iso := "bth", value := .optional }
  , { walsCode := "bok", iso := "bqc", value := .obligatory }
  , { walsCode := "bor", iso := "boa", value := .optional }
  , { walsCode := "brh", iso := "brh", value := .absent }
  , { walsCode := "bul", iso := "bul", value := .absent }
  , { walsCode := "but", iso := "bxm", value := .absent }
  , { walsCode := "brm", iso := "mya", value := .obligatory }
  , { walsCode := "bur", iso := "bsk", value := .absent }
  , { walsCode := "cnl", iso := "ram", value := .absent }
  , { walsCode := "cnt", iso := "yue", value := .obligatory }
  , { walsCode := "cap", iso := "kaq", value := .absent }
  , { walsCode := "crq", iso := "crx", value := .obligatory }
  , { walsCode := "cyv", iso := "cyb", value := .absent }
  , { walsCode := "cme", iso := "cjm", value := .obligatory }
  , { walsCode := "chw", iso := "cja", value := .obligatory }
  , { walsCode := "cha", iso := "cha", value := .absent }
  , { walsCode := "chn", iso := "chx", value := .optional }
  , { walsCode := "chy", iso := "cbt", value := .optional }
  , { walsCode := "chc", iso := "che", value := .absent }
  , { walsCode := "cpn", iso := "cdm", value := .absent }
  , { walsCode := "cjo", iso := "pei", value := .absent }
  , { walsCode := "chi", iso := "cid", value := .absent }
  , { walsCode := "cku", iso := "wac", value := .absent }
  , { walsCode := "ctm", iso := "ctm", value := .absent }
  , { walsCode := "cct", iso := "cho", value := .absent }
  , { walsCode := "chx", iso := "clo", value := .obligatory }
  , { walsCode := "chk", iso := "ckt", value := .absent }
  , { walsCode := "cba", iso := "boi", value := .absent }
  , { walsCode := "cin", iso := "inz", value := .absent }
  , { walsCode := "cuu", iso := "chk", value := .obligatory }
  , { walsCode := "chv", iso := "chv", value := .absent }
  , { walsCode := "coo", iso := "csz", value := .absent }
  , { walsCode := "cre", iso := "crk", value := .absent }
  , { walsCode := "cul", iso := "cul", value := .absent }
  , { walsCode := "dga", iso := "dga", value := .absent }
  , { walsCode := "drg", iso := "dar", value := .absent }
  , { walsCode := "dat", iso := "tcc", value := .absent }
  , { walsCode := "den", iso := "dny", value := .absent }
  , { walsCode := "diz", iso := "mdx", value := .absent }
  , { walsCode := "dji", iso := "jig", value := .absent }
  , { walsCode := "dob", iso := "kvo", value := .optional }
  , { walsCode := "dre", iso := "dhv", value := .absent }
  , { walsCode := "dum", iso := "vam", value := .absent }
  , { walsCode := "dyi", iso := "dbl", value := .absent }
  , { walsCode := "eng", iso := "eng", value := .absent }
  , { walsCode := "epe", iso := "sja", value := .absent }
  , { walsCode := "err", iso := "erg", value := .absent }
  , { walsCode := "eve", iso := "evn", value := .absent }
  , { walsCode := "eya", iso := "eya", value := .obligatory }
  , { walsCode := "fij", iso := "fij", value := .absent }
  , { walsCode := "fin", iso := "fin", value := .absent }
  , { walsCode := "fre", iso := "fra", value := .absent }
  , { walsCode := "fur", iso := "fvr", value := .absent }
  , { walsCode := "fut", iso := "fut", value := .absent }
  , { walsCode := "gaa", iso := "gbu", value := .absent }
  , { walsCode := "gar", iso := "grt", value := .obligatory }
  , { walsCode := "grr", iso := "wrk", value := .absent }
  , { walsCode := "gav", iso := "gvo", value := .absent }
  , { walsCode := "gbb", iso := "gbp", value := .absent }
  , { walsCode := "geo", iso := "kat", value := .absent }
  , { walsCode := "ger", iso := "deu", value := .absent }
  , { walsCode := "gil", iso := "glk", value := .optional }
  , { walsCode := "goo", iso := "gni", value := .absent }
  , { walsCode := "gua", iso := "gug", value := .absent }
  , { walsCode := "gdf", iso := "gdf", value := .absent }
  , { walsCode := "gnn", iso := "gww", value := .absent }
  , { walsCode := "hai", iso := "hai", value := .optional }
  , { walsCode := "hat", iso := "had", value := .optional }
  , { walsCode := "hau", iso := "hau", value := .absent }
  , { walsCode := "haw", iso := "haw", value := .absent }
  , { walsCode := "heb", iso := "heb", value := .absent }
  , { walsCode := "hin", iso := "hin", value := .absent }
  , { walsCode := "hix", iso := "hix", value := .absent }
  , { walsCode := "hmd", iso := "mww", value := .obligatory }
  , { walsCode := "hua", iso := "ygr", value := .absent }
  , { walsCode := "hun", iso := "hun", value := .optional }
  , { walsCode := "hzb", iso := "huz", value := .absent }
  , { walsCode := "hpd", iso := "jup", value := .absent }
  , { walsCode := "hyo", iso := "csh", value := .obligatory }
  , { walsCode := "iaa", iso := "iai", value := .absent }
  , { walsCode := "igb", iso := "ibo", value := .absent }
  , { walsCode := "ika", iso := "arh", value := .absent }
  , { walsCode := "imo", iso := "imn", value := .absent }
  , { walsCode := "ind", iso := "ind", value := .optional }
  , { walsCode := "ing", iso := "inh", value := .absent }
  , { walsCode := "irq", iso := "irk", value := .absent }
  , { walsCode := "jah", iso := "jhi", value := .optional }
  , { walsCode := "jak", iso := "jac", value := .obligatory }
  , { walsCode := "jmm", iso := "jaa", value := .absent }
  , { walsCode := "jam", iso := "djd", value := .absent }
  , { walsCode := "jpn", iso := "jpn", value := .obligatory }
  , { walsCode := "jaq", iso := "jqr", value := .absent }
  , { walsCode := "jav", iso := "jav", value := .optional }
  , { walsCode := "jiv", iso := "jiv", value := .absent }
  , { walsCode := "juh", iso := "ktz", value := .absent }
  , { walsCode := "klp", iso := "kyl", value := .obligatory }
  , { walsCode := "kam", iso := "xbr", value := .obligatory }
  , { walsCode := "kan", iso := "ogo", value := .obligatory }
  , { walsCode := "knd", iso := "kan", value := .absent }
  , { walsCode := "knr", iso := "knc", value := .absent }
  , { walsCode := "krk", iso := "kyh", value := .absent }
  , { walsCode := "kyl", iso := "eky", value := .obligatory }
  , { walsCode := "kbr", iso := "kys", value := .optional }
  , { walsCode := "kei", iso := "kei", value := .obligatory }
  , { walsCode := "klt", iso := "kzi", value := .absent }
  , { walsCode := "keu", iso := "keu", value := .optional }
  , { walsCode := "keo", iso := "xxk", value := .obligatory }
  , { walsCode := "ktp", iso := "xdy", value := .obligatory }
  , { walsCode := "kew", iso := "kew", value := .absent }
  , { walsCode := "kha", iso := "khk", value := .absent }
  , { walsCode := "kmh", iso := "kjl", value := .obligatory }
  , { walsCode := "khr", iso := "khr", value := .optional }
  , { walsCode := "khm", iso := "khm", value := .optional }
  , { walsCode := "kmu", iso := "kjg", value := .obligatory }
  , { walsCode := "khu", iso := "cnk", value := .obligatory }
  , { walsCode := "klv", iso := "kij", value := .obligatory }
  , { walsCode := "kio", iso := "kio", value := .absent }
  , { walsCode := "krb", iso := "gil", value := .obligatory }
  , { walsCode := "kiw", iso := "kjd", value := .absent }
  , { walsCode := "klm", iso := "kla", value := .absent }
  , { walsCode := "kob", iso := "kpw", value := .absent }
  , { walsCode := "koi", iso := "kbk", value := .absent }
  , { walsCode := "kmb", iso := "", value := .absent }
  , { walsCode := "kag", iso := "kge", value := .optional }
  , { walsCode := "kzy", iso := "kpv", value := .absent }
  , { walsCode := "knu", iso := "kyx", value := .absent }
  , { walsCode := "krf", iso := "kpr", value := .absent }
  , { walsCode := "kor", iso := "kor", value := .obligatory }
  , { walsCode := "kku", iso := "kfq", value := .absent }
  , { walsCode := "kfe", iso := "kfz", value := .absent }
  , { walsCode := "kos", iso := "kos", value := .obligatory }
  , { walsCode := "kot", iso := "kfe", value := .absent }
  , { walsCode := "kch", iso := "khq", value := .absent }
  , { walsCode := "kpe", iso := "xpe", value := .absent }
  , { walsCode := "kua", iso := "sdm", value := .obligatory }
  , { walsCode := "kut", iso := "kut", value := .absent }
  , { walsCode := "kwz", iso := "xwa", value := .obligatory }
  , { walsCode := "kat", iso := "kmg", value := .absent }
  , { walsCode := "lch", iso := "lbt", value := .obligatory }
  , { walsCode := "lah", iso := "lhu", value := .obligatory }
  , { walsCode := "lai", iso := "cnh", value := .obligatory }
  , { walsCode := "lkt", iso := "lkt", value := .absent }
  , { walsCode := "lan", iso := "laj", value := .absent }
  , { walsCode := "lrk", iso := "alo", value := .obligatory }
  , { walsCode := "lat", iso := "lav", value := .absent }
  , { walsCode := "let", iso := "lti", value := .absent }
  , { walsCode := "lez", iso := "lez", value := .absent }
  , { walsCode := "lim", iso := "lif", value := .absent }
  , { walsCode := "ara", iso := "arw", value := .absent }
  , { walsCode := "lon", iso := "los", value := .obligatory }
  , { walsCode := "lov", iso := "lbo", value := .obligatory }
  , { walsCode := "luc", iso := "lch", value := .absent }
  , { walsCode := "lda", iso := "lug", value := .absent }
  , { walsCode := "lug", iso := "lgg", value := .absent }
  , { walsCode := "lui", iso := "lui", value := .absent }
  , { walsCode := "lud", iso := "lnd", value := .optional }
  , { walsCode := "luo", iso := "luo", value := .absent }
  , { walsCode := "lur", iso := "lrc", value := .optional }
  , { walsCode := "maa", iso := "mas", value := .absent }
  , { walsCode := "msy", iso := "mrd", value := .absent }
  , { walsCode := "mhm", iso := "mhe", value := .optional }
  , { walsCode := "mne", iso := "nmu", value := .absent }
  , { walsCode := "mks", iso := "mak", value := .optional }
  , { walsCode := "mal", iso := "plt", value := .absent }
  , { walsCode := "mlk", iso := "mpb", value := .absent }
  , { walsCode := "mym", iso := "mal", value := .absent }
  , { walsCode := "mli", iso := "gcc", value := .absent }
  , { walsCode := "mdn", iso := "mhq", value := .absent }
  , { walsCode := "mnr", iso := "mdr", value := .optional }
  , { walsCode := "mnd", iso := "cmn", value := .obligatory }
  , { walsCode := "mdk", iso := "mnk", value := .absent }
  , { walsCode := "myi", iso := "mpc", value := .absent }
  , { walsCode := "map", iso := "arn", value := .absent }
  , { walsCode := "mhi", iso := "mar", value := .absent }
  , { walsCode := "mrg", iso := "mrt", value := .absent }
  , { walsCode := "mar", iso := "mrc", value := .absent }
  , { walsCode := "mrt", iso := "vma", value := .absent }
  , { walsCode := "mau", iso := "mph", value := .absent }
  , { walsCode := "may", iso := "ayz", value := .optional }
  , { walsCode := "mzn", iso := "mzn", value := .optional }
  , { walsCode := "mbg", iso := "mhd", value := .absent }
  , { walsCode := "mee", iso := "mym", value := .absent }
  , { walsCode := "mel", iso := "mel", value := .optional }
  , { walsCode := "mde", iso := "men", value := .absent }
  , { walsCode := "hok", iso := "nan", value := .optional }
  , { walsCode := "min", iso := "min", value := .optional }
  , { walsCode := "mis", iso := "miq", value := .absent }
  , { walsCode := "mit", iso := "zmq", value := .absent }
  , { walsCode := "mss", iso := "skd", value := .absent }
  , { walsCode := "mxc", iso := "mig", value := .absent }
  , { walsCode := "miy", iso := "mkf", value := .absent }
  , { walsCode := "mlm", iso := "mra", value := .obligatory }
  , { walsCode := "mok", iso := "mkj", value := .obligatory }
  , { walsCode := "mll", iso := "mbe", value := .absent }
  , { walsCode := "moe", iso := "myv", value := .absent }
  , { walsCode := "mos", iso := "cas", value := .absent }
  , { walsCode := "msc", iso := "chb", value := .absent }
  , { walsCode := "muu", iso := "myu", value := .absent }
  , { walsCode := "mup", iso := "sur", value := .absent }
  , { walsCode := "mkw", iso := "xak", value := .absent }
  , { walsCode := "nah", iso := "nll", value := .absent }
  , { walsCode := "nht", iso := "nhg", value := .absent }
  , { walsCode := "kho", iso := "naq", value := .absent }
  , { walsCode := "nai", iso := "gld", value := .absent }
  , { walsCode := "npu", iso := "npy", value := .optional }
  , { walsCode := "nar", iso := "nrb", value := .absent }
  , { walsCode := "nrm", iso := "nrm", value := .optional }
  , { walsCode := "nas", iso := "nas", value := .absent }
  , { walsCode := "nau", iso := "nau", value := .obligatory }
  , { walsCode := "nav", iso := "nav", value := .absent }
  , { walsCode := "ndy", iso := "djk", value := .absent }
  , { walsCode := "nel", iso := "nee", value := .obligatory }
  , { walsCode := "ntu", iso := "yrk", value := .absent }
  , { walsCode := "naj", iso := "aij", value := .absent }
  , { walsCode := "new", iso := "new", value := .obligatory }
  , { walsCode := "ngd", iso := "nxg", value := .obligatory }
  , { walsCode := "ngy", iso := "nbj", value := .absent }
  , { walsCode := "ngi", iso := "wyb", value := .absent }
  , { walsCode := "ngz", iso := "ngi", value := .absent }
  , { walsCode := "nca", iso := "caq", value := .optional }
  , { walsCode := "niv", iso := "niv", value := .obligatory }
  , { walsCode := "nvs", iso := "niv", value := .obligatory }
  , { walsCode := "nbd", iso := "dgl", value := .absent }
  , { walsCode := "nug", iso := "nuy", value := .absent }
  , { walsCode := "nyl", iso := "yly", value := .obligatory }
  , { walsCode := "nyu", iso := "nyv", value := .absent }
  , { walsCode := "ood", iso := "ood", value := .absent }
  , { walsCode := "oca", iso := "oca", value := .optional }
  , { walsCode := "ore", iso := "ore", value := .optional }
  , { walsCode := "ori", iso := "tag", value := .absent }
  , { walsCode := "orh", iso := "hae", value := .absent }
  , { walsCode := "pad", iso := "pdo", value := .optional }
  , { walsCode := "pno", iso := "pao", value := .absent }
  , { walsCode := "put", iso := "ute", value := .absent }
  , { walsCode := "plk", iso := "plu", value := .obligatory }
  , { walsCode := "pnr", iso := "pbh", value := .absent }
  , { walsCode := "prc", iso := "pab", value := .absent }
  , { walsCode := "pau", iso := "pad", value := .absent }
  , { walsCode := "pwn", iso := "paw", value := .absent }
  , { walsCode := "prs", iso := "pes", value := .optional }
  , { walsCode := "pia", iso := "pid", value := .optional }
  , { walsCode := "pil", iso := "piv", value := .optional }
  , { walsCode := "pba", iso := "pia", value := .absent }
  , { walsCode := "pip", iso := "ppl", value := .absent }
  , { walsCode := "prh", iso := "myp", value := .absent }
  , { walsCode := "pir", iso := "pib", value := .absent }
  , { walsCode := "poh", iso := "pon", value := .obligatory }
  , { walsCode := "fma", iso := "fuc", value := .absent }
  , { walsCode := "pur", iso := "tsz", value := .obligatory }
  , { walsCode := "qcu", iso := "quz", value := .absent }
  , { walsCode := "qhu", iso := "qub", value := .absent }
  , { walsCode := "qim", iso := "qvi", value := .absent }
  , { walsCode := "qui", iso := "qui", value := .absent }
  , { walsCode := "rap", iso := "rap", value := .absent }
  , { walsCode := "rem", iso := "bfw", value := .obligatory }
  , { walsCode := "rse", iso := "rmn", value := .optional }
  , { walsCode := "ruk", iso := "dru", value := .absent }
  , { walsCode := "rru", iso := "nyo", value := .absent }
  , { walsCode := "rus", iso := "rus", value := .absent }
  , { walsCode := "rcp", iso := "", value := .absent }
  , { walsCode := "sal", iso := "sln", value := .absent }
  , { walsCode := "syu", iso := "sll", value := .absent }
  , { walsCode := "bjs", iso := "ssb", value := .optional }
  , { walsCode := "sam", iso := "smo", value := .optional }
  , { walsCode := "sdw", iso := "sad", value := .absent }
  , { walsCode := "stl", iso := "sat", value := .optional }
  , { walsCode := "snm", iso := "xsu", value := .optional }
  , { walsCode := "saw", iso := "hvn", value := .obligatory }
  , { walsCode := "see", iso := "trv", value := .absent }
  , { walsCode := "smd", iso := "sdm", value := .obligatory }
  , { walsCode := "sml", iso := "sza", value := .obligatory }
  , { walsCode := "snc", iso := "see", value := .absent }
  , { walsCode := "snt", iso := "set", value := .absent }
  , { walsCode := "ses", iso := "sot", value := .absent }
  , { walsCode := "shs", iso := "sht", value := .absent }
  , { walsCode := "shk", iso := "shp", value := .absent }
  , { walsCode := "sim", iso := "smr", value := .obligatory }
  , { walsCode := "snh", iso := "sin", value := .absent }
  , { walsCode := "sin", iso := "snn", value := .optional }
  , { walsCode := "siu", iso := "sis", value := .absent }
  , { walsCode := "so", iso := "teu", value := .obligatory }
  , { walsCode := "tou", iso := "wib", value := .obligatory }
  , { walsCode := "sue", iso := "sue", value := .absent }
  , { walsCode := "sul", iso := "sua", value := .absent }
  , { walsCode := "sup", iso := "spp", value := .absent }
  , { walsCode := "swa", iso := "swh", value := .absent }
  , { walsCode := "swt", iso := "ssw", value := .absent }
  , { walsCode := "tab", iso := "mky", value := .obligatory }
  , { walsCode := "tag", iso := "tgl", value := .absent }
  , { walsCode := "tkl", iso := "tkm", value := .absent }
  , { walsCode := "tvo", iso := "tat", value := .optional }
  , { walsCode := "tts", iso := "tks", value := .optional }
  , { walsCode := "tll", iso := "tuh", value := .absent }
  , { walsCode := "taw", iso := "tbo", value := .absent }
  , { walsCode := "tht", iso := "kps", value := .obligatory }
  , { walsCode := "tlf", iso := "tlf", value := .absent }
  , { walsCode := "tmr", iso := "tea", value := .absent }
  , { walsCode := "tps", iso := "stp", value := .absent }
  , { walsCode := "trb", iso := "tfr", value := .obligatory }
  , { walsCode := "trn", iso := "ter", value := .absent }
  , { walsCode := "ttn", iso := "tet", value := .optional }
  , { walsCode := "tha", iso := "tha", value := .obligatory }
  , { walsCode := "tho", iso := "thp", value := .optional }
  , { walsCode := "tid", iso := "tvo", value := .optional }
  , { walsCode := "tim", iso := "tih", value := .absent }
  , { walsCode := "tiw", iso := "tiw", value := .absent }
  , { walsCode := "tli", iso := "tli", value := .obligatory }
  , { walsCode := "tob", iso := "tob", value := .absent }
  , { walsCode := "tol", iso := "jic", value := .absent }
  , { walsCode := "tla", iso := "ksd", value := .absent }
  , { walsCode := "tng", iso := "ton", value := .optional }
  , { walsCode := "ton", iso := "tqw", value := .absent }
  , { walsCode := "toq", iso := "mlu", value := .optional }
  , { walsCode := "tpa", iso := "top", value := .obligatory }
  , { walsCode := "tsi", iso := "tsi", value := .obligatory }
  , { walsCode := "tso", iso := "tsu", value := .absent }
  , { walsCode := "tgh", iso := "thv", value := .absent }
  , { walsCode := "tuc", iso := "tuo", value := .optional }
  , { walsCode := "tuk", iso := "", value := .optional }
  , { walsCode := "tnn", iso := "tvu", value := .absent }
  , { walsCode := "tun", iso := "tun", value := .absent }
  , { walsCode := "tur", iso := "tur", value := .optional }
  , { walsCode := "tvl", iso := "tvl", value := .optional }
  , { walsCode := "tuv", iso := "tyv", value := .absent }
  , { walsCode := "tuy", iso := "tue", value := .obligatory }
  , { walsCode := "tze", iso := "tzh", value := .obligatory }
  , { walsCode := "uli", iso := "uli", value := .obligatory }
  , { walsCode := "ung", iso := "ung", value := .absent }
  , { walsCode := "ura", iso := "uur", value := .absent }
  , { walsCode := "uhi", iso := "urf", value := .absent }
  , { walsCode := "vaf", iso := "vaf", value := .optional }
  , { walsCode := "vie", iso := "vie", value := .obligatory }
  , { walsCode := "wgl", iso := "wbk", value := .absent }
  , { walsCode := "wao", iso := "auc", value := .obligatory }
  , { walsCode := "wap", iso := "wao", value := .absent }
  , { walsCode := "wrk", iso := "gae", value := .obligatory }
  , { walsCode := "war", iso := "pav", value := .absent }
  , { walsCode := "wrn", iso := "wnd", value := .absent }
  , { walsCode := "was", iso := "was", value := .absent }
  , { walsCode := "wur", iso := "wau", value := .optional }
  , { walsCode := "wem", iso := "xww", value := .absent }
  , { walsCode := "win", iso := "wnw", value := .absent }
  , { walsCode := "wor", iso := "wro", value := .absent }
  , { walsCode := "yag", iso := "yad", value := .obligatory }
  , { walsCode := "ymi", iso := "tao", value := .absent }
  , { walsCode := "yap", iso := "yap", value := .optional }
  , { walsCode := "ywl", iso := "yok", value := .absent }
  , { walsCode := "yes", iso := "yss", value := .absent }
  , { walsCode := "yid", iso := "yii", value := .absent }
  , { walsCode := "yim", iso := "yee", value := .absent }
  , { walsCode := "yng", iso := "yia", value := .absent }
  , { walsCode := "yor", iso := "yor", value := .absent }
  , { walsCode := "yct", iso := "yua", value := .obligatory }
  , { walsCode := "yuc", iso := "yuc", value := .absent }
  , { walsCode := "yko", iso := "yux", value := .absent }
  , { walsCode := "yuk", iso := "gcd", value := .absent }
  , { walsCode := "zul", iso := "zul", value := .absent }
  , { walsCode := "zun", iso := "zun", value := .absent }
  ]

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F55A
