import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 57A: Position of Pronominal Possessive Affixes
@cite{wals-2013}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 57A`.

Chapter 57, 902 languages.
-/

namespace Core.WALS.F57A

/-- WALS 57A values. -/
inductive PositionOfPronominalPossessiveAffixes where
  /-- Possessive prefixes (255 languages). -/
  | possessivePrefixes
  /-- Possessive suffixes (355 languages). -/
  | possessiveSuffixes
  /-- Prefixes and suffixes (32 languages). -/
  | prefixesAndSuffixes
  /-- No possessive affixes (260 languages). -/
  | noPossessiveAffixes
  deriving DecidableEq, BEq, Repr

private def allData_0 : List (Datapoint PositionOfPronominalPossessiveAffixes) :=
  [ { walsCode := "aar", iso := "aiw", value := .noPossessiveAffixes }
  , { walsCode := "abi", iso := "axb", value := .prefixesAndSuffixes }
  , { walsCode := "abk", iso := "abk", value := .possessivePrefixes }
  , { walsCode := "abv", iso := "abz", value := .possessivePrefixes }
  , { walsCode := "ace", iso := "ace", value := .noPossessiveAffixes }
  , { walsCode := "acg", iso := "aca", value := .possessivePrefixes }
  , { walsCode := "acl", iso := "ach", value := .possessiveSuffixes }
  , { walsCode := "acu", iso := "acu", value := .possessiveSuffixes }
  , { walsCode := "aco", iso := "kjq", value := .possessivePrefixes }
  , { walsCode := "adg", iso := "adn", value := .possessivePrefixes }
  , { walsCode := "adi", iso := "adj", value := .noPossessiveAffixes }
  , { walsCode := "ady", iso := "ady", value := .possessivePrefixes }
  , { walsCode := "awi", iso := "awi", value := .possessivePrefixes }
  , { walsCode := "aga", iso := "agd", value := .possessivePrefixes }
  , { walsCode := "agh", iso := "agq", value := .noPossessiveAffixes }
  , { walsCode := "agc", iso := "agt", value := .possessiveSuffixes }
  , { walsCode := "ain", iso := "ain", value := .possessivePrefixes }
  , { walsCode := "ajg", iso := "ajg", value := .possessiveSuffixes }
  , { walsCode := "akn", iso := "aka", value := .possessivePrefixes }
  , { walsCode := "ala", iso := "amp", value := .noPossessiveAffixes }
  , { walsCode := "alw", iso := "alh", value := .possessiveSuffixes }
  , { walsCode := "alb", iso := "sqi", value := .noPossessiveAffixes }
  , { walsCode := "ale", iso := "ale", value := .possessiveSuffixes }
  , { walsCode := "als", iso := "aes", value := .prefixesAndSuffixes }
  , { walsCode := "aln", iso := "alp", value := .prefixesAndSuffixes }
  , { walsCode := "aly", iso := "aly", value := .possessiveSuffixes }
  , { walsCode := "amc", iso := "amc", value := .possessivePrefixes }
  , { walsCode := "amn", iso := "amn", value := .noPossessiveAffixes }
  , { walsCode := "ama", iso := "aie", value := .possessiveSuffixes }
  , { walsCode := "aml", iso := "omb", value := .possessiveSuffixes }
  , { walsCode := "amq", iso := "amk", value := .prefixesAndSuffixes }
  , { walsCode := "ame", iso := "aey", value := .possessiveSuffixes }
  , { walsCode := "amh", iso := "amh", value := .possessiveSuffixes }
  , { walsCode := "amo", iso := "amo", value := .possessiveSuffixes }
  , { walsCode := "amx", iso := "imi", value := .possessivePrefixes }
  , { walsCode := "anj", iso := "aty", value := .possessiveSuffixes }
  , { walsCode := "anc", iso := "anc", value := .possessiveSuffixes }
  , { walsCode := "ang", iso := "agg", value := .noPossessiveAffixes }
  , { walsCode := "ann", iso := "aoi", value := .possessiveSuffixes }
  , { walsCode := "anu", iso := "cko", value := .noPossessiveAffixes }
  , { walsCode := "ane", iso := "anz", value := .possessiveSuffixes }
  , { walsCode := "ao", iso := "njo", value := .possessivePrefixes }
  , { walsCode := "apl", iso := "apy", value := .possessivePrefixes }
  , { walsCode := "api", iso := "apn", value := .possessivePrefixes }
  , { walsCode := "apu", iso := "apu", value := .possessivePrefixes }
  , { walsCode := "aeg", iso := "arz", value := .possessiveSuffixes }
  , { walsCode := "arg", iso := "afb", value := .possessiveSuffixes }
  , { walsCode := "arq", iso := "acm", value := .possessiveSuffixes }
  , { walsCode := "ams", iso := "arb", value := .possessiveSuffixes }
  , { walsCode := "amr", iso := "ary", value := .possessiveSuffixes }
  , { walsCode := "asy", iso := "apc", value := .possessiveSuffixes }
  , { walsCode := "ana", iso := "aro", value := .noPossessiveAffixes }
  , { walsCode := "arc", iso := "aqc", value := .noPossessiveAffixes }
  , { walsCode := "ari", iso := "laz", value := .possessiveSuffixes }
  , { walsCode := "arm", iso := "hye", value := .possessiveSuffixes }
  , { walsCode := "arw", iso := "hyw", value := .possessiveSuffixes }
  , { walsCode := "alk", iso := "apr", value := .possessiveSuffixes }
  , { walsCode := "aro", iso := "aia", value := .possessiveSuffixes }
  , { walsCode := "amp", iso := "aer", value := .possessiveSuffixes }
  , { walsCode := "asm", iso := "cns", value := .noPossessiveAffixes }
  , { walsCode := "atm", iso := "kuz", value := .possessivePrefixes }
  , { walsCode := "ath", iso := "aph", value := .possessivePrefixes }
  , { walsCode := "awa", iso := "awb", value := .possessivePrefixes }
  , { walsCode := "awp", iso := "kwi", value := .noPossessiveAffixes }
  , { walsCode := "awt", iso := "kmn", value := .noPossessiveAffixes }
  , { walsCode := "aym", iso := "ayr", value := .possessiveSuffixes }
  , { walsCode := "ayo", iso := "", value := .possessivePrefixes }
  , { walsCode := "ayr", iso := "ayo", value := .possessivePrefixes }
  , { walsCode := "azi", iso := "azb", value := .possessiveSuffixes }
  , { walsCode := "aze", iso := "", value := .possessiveSuffixes }
  , { walsCode := "bag", iso := "bmi", value := .possessiveSuffixes }
  , { walsCode := "bgr", iso := "fuu", value := .possessiveSuffixes }
  , { walsCode := "bai", iso := "bca", value := .noPossessiveAffixes }
  , { walsCode := "bwc", iso := "bdr", value := .possessiveSuffixes }
  , { walsCode := "bak", iso := "bkc", value := .possessiveSuffixes }
  , { walsCode := "blg", iso := "blw", value := .possessiveSuffixes }
  , { walsCode := "bvi", iso := "", value := .possessiveSuffixes }
  , { walsCode := "bnn", iso := "bcm", value := .possessiveSuffixes }
  , { walsCode := "bbu", iso := "brm", value := .possessiveSuffixes }
  , { walsCode := "brs", iso := "bsn", value := .noPossessiveAffixes }
  , { walsCode := "mug", iso := "mlp", value := .possessivePrefixes }
  , { walsCode := "bry", iso := "byr", value := .possessivePrefixes }
  , { walsCode := "bae", iso := "bae", value := .possessivePrefixes }
  , { walsCode := "bsk", iso := "bak", value := .possessiveSuffixes }
  , { walsCode := "bsq", iso := "eus", value := .noPossessiveAffixes }
  , { walsCode := "bkr", iso := "btx", value := .possessiveSuffixes }
  , { walsCode := "bto", iso := "bbc", value := .possessiveSuffixes }
  , { walsCode := "bau", iso := "bbd", value := .possessiveSuffixes }
  , { walsCode := "baq", iso := "brg", value := .possessivePrefixes }
  , { walsCode := "baw", iso := "bgr", value := .noPossessiveAffixes }
  , { walsCode := "bej", iso := "bej", value := .possessiveSuffixes }
  , { walsCode := "bel", iso := "byw", value := .possessivePrefixes }
  , { walsCode := "bco", iso := "blc", value := .possessiveSuffixes }
  , { walsCode := "bch", iso := "shy", value := .possessiveSuffixes }
  , { walsCode := "bfg", iso := "grr", value := .possessiveSuffixes }
  , { walsCode := "bma", iso := "tzm", value := .possessiveSuffixes }
  , { walsCode := "brf", iso := "rif", value := .possessiveSuffixes }
  , { walsCode := "bsi", iso := "siz", value := .possessiveSuffixes }
  , { walsCode := "zag", iso := "zag", value := .possessiveSuffixes }
  , { walsCode := "ber", iso := "wti", value := .possessiveSuffixes }
  , { walsCode := "bti", iso := "", value := .possessivePrefixes }
  , { walsCode := "bho", iso := "bho", value := .noPossessiveAffixes }
  , { walsCode := "bik", iso := "bhw", value := .possessiveSuffixes }
  , { walsCode := "bid", iso := "bid", value := .possessiveSuffixes }
  , { walsCode := "bia", iso := "bip", value := .possessiveSuffixes }
  , { walsCode := "blx", iso := "bll", value := .possessivePrefixes }
  , { walsCode := "bil", iso := "blb", value := .possessivePrefixes }
  , { walsCode := "bin", iso := "bhg", value := .noPossessiveAffixes }
  , { walsCode := "big", iso := "yul", value := .possessiveSuffixes }
  , { walsCode := "bii", iso := "bzr", value := .noPossessiveAffixes }
  , { walsCode := "bla", iso := "bla", value := .possessivePrefixes }
  , { walsCode := "boa", iso := "kvg", value := .possessivePrefixes }
  , { walsCode := "bod", iso := "brx", value := .possessivePrefixes }
  , { walsCode := "bgo", iso := "bot", value := .possessiveSuffixes }
  , { walsCode := "btk", iso := "lbk", value := .possessiveSuffixes }
  , { walsCode := "brr", iso := "bor", value := .possessivePrefixes }
  , { walsCode := "brh", iso := "brh", value := .possessiveSuffixes }
  , { walsCode := "bre", iso := "bre", value := .possessiveSuffixes }
  , { walsCode := "bri", iso := "bzd", value := .noPossessiveAffixes }
  , { walsCode := "bud", iso := "bdm", value := .possessiveSuffixes }
  , { walsCode := "bun", iso := "buo", value := .possessivePrefixes }
  , { walsCode := "bul", iso := "bul", value := .noPossessiveAffixes }
  , { walsCode := "pnu", iso := "buh", value := .noPossessiveAffixes }
  , { walsCode := "bua", iso := "bvr", value := .possessivePrefixes }
  , { walsCode := "but", iso := "bxm", value := .possessiveSuffixes }
  , { walsCode := "bmr", iso := "bmu", value := .possessiveSuffixes }
  , { walsCode := "brn", iso := "bds", value := .possessiveSuffixes }
  , { walsCode := "bur", iso := "bsk", value := .possessivePrefixes }
  , { walsCode := "bya", iso := "bee", value := .noPossessiveAffixes }
  , { walsCode := "cah", iso := "chl", value := .possessivePrefixes }
  , { walsCode := "cml", iso := "rab", value := .possessivePrefixes }
  , { walsCode := "cax", iso := "", value := .possessivePrefixes }
  , { walsCode := "cnm", iso := "knm", value := .possessivePrefixes }
  , { walsCode := "cnl", iso := "ram", value := .possessivePrefixes }
  , { walsCode := "cnt", iso := "yue", value := .noPossessiveAffixes }
  , { walsCode := "car", iso := "car", value := .possessivePrefixes }
  , { walsCode := "cde", iso := "mch", value := .possessivePrefixes }
  , { walsCode := "cas", iso := "cbr", value := .noPossessiveAffixes }
  , { walsCode := "cay", iso := "cbi", value := .noPossessiveAffixes }
  , { walsCode := "cyv", iso := "cyb", value := .prefixesAndSuffixes }
  , { walsCode := "chh", iso := "sgw", value := .possessiveSuffixes }
  , { walsCode := "cai", iso := "suq", value := .possessiveSuffixes }
  , { walsCode := "cld", iso := "cld", value := .possessiveSuffixes }
  , { walsCode := "cha", iso := "cha", value := .possessiveSuffixes }
  , { walsCode := "chg", iso := "nbc", value := .possessivePrefixes }
  , { walsCode := "cya", iso := "ctp", value := .noPossessiveAffixes }
  , { walsCode := "chc", iso := "che", value := .noPossessiveAffixes }
  , { walsCode := "cmh", iso := "ute", value := .possessiveSuffixes }
  , { walsCode := "che", iso := "chr", value := .possessivePrefixes }
  , { walsCode := "chi", iso := "cid", value := .prefixesAndSuffixes }
  , { walsCode := "cmr", iso := "mrh", value := .noPossessiveAffixes }
  , { walsCode := "chs", iso := "csy", value := .noPossessiveAffixes }
  , { walsCode := "cti", iso := "ctd", value := .possessivePrefixes }
  , { walsCode := "ccm", iso := "cco", value := .prefixesAndSuffixes }
  , { walsCode := "cle", iso := "cle", value := .prefixesAndSuffixes }
  , { walsCode := "chq", iso := "chq", value := .prefixesAndSuffixes }
  , { walsCode := "ckl", iso := "chh", value := .possessivePrefixes }
  , { walsCode := "cpy", iso := "cap", value := .noPossessiveAffixes }
  , { walsCode := "chp", iso := "chp", value := .possessivePrefixes }
  , { walsCode := "cqt", iso := "cax", value := .possessivePrefixes }
  , { walsCode := "cct", iso := "cho", value := .possessivePrefixes }
  , { walsCode := "cln", iso := "cht", value := .possessivePrefixes }
  , { walsCode := "chx", iso := "clo", value := .possessivePrefixes }
  , { walsCode := "cmy", iso := "chf", value := .possessiveSuffixes }
  , { walsCode := "chr", iso := "crw", value := .noPossessiveAffixes }
  , { walsCode := "chj", iso := "cac", value := .possessivePrefixes }
  , { walsCode := "chk", iso := "ckt", value := .noPossessiveAffixes }
  , { walsCode := "cba", iso := "boi", value := .possessivePrefixes }
  , { walsCode := "chv", iso := "chv", value := .possessiveSuffixes }
  , { walsCode := "coa", iso := "xcw", value := .possessivePrefixes }
  , { walsCode := "coe", iso := "crd", value := .prefixesAndSuffixes }
  , { walsCode := "cmn", iso := "com", value := .noPossessiveAffixes }
  , { walsCode := "cmx", iso := "coo", value := .possessivePrefixes }
  , { walsCode := "coo", iso := "csz", value := .noPossessiveAffixes }
  , { walsCode := "cor", iso := "crn", value := .possessivePrefixes }
  , { walsCode := "crn", iso := "cor", value := .noPossessiveAffixes }
  , { walsCode := "cre", iso := "crk", value := .possessivePrefixes }
  , { walsCode := "cro", iso := "cro", value := .possessivePrefixes }
  , { walsCode := "cub", iso := "cub", value := .noPossessiveAffixes }
  , { walsCode := "cup", iso := "cup", value := .possessivePrefixes }
  , { walsCode := "cze", iso := "ces", value := .noPossessiveAffixes }
  , { walsCode := "cem", iso := "cam", value := .possessiveSuffixes }
  , { walsCode := "dag", iso := "dgz", value := .possessiveSuffixes }
  , { walsCode := "dgb", iso := "dag", value := .noPossessiveAffixes }
  , { walsCode := "dgr", iso := "dta", value := .possessiveSuffixes }
  , { walsCode := "dam", iso := "mbp", value := .noPossessiveAffixes }
  , { walsCode := "dni", iso := "dni", value := .possessivePrefixes }
  , { walsCode := "dsh", iso := "dan", value := .noPossessiveAffixes }
  , { walsCode := "drg", iso := "dar", value := .noPossessiveAffixes }
  , { walsCode := "des", iso := "des", value := .noPossessiveAffixes }
  , { walsCode := "did", iso := "did", value := .possessiveSuffixes }
  , { walsCode := "die", iso := "dih", value := .possessivePrefixes }
  , { walsCode := "din", iso := "din", value := .possessiveSuffixes }
  , { walsCode := "dio", iso := "dyo", value := .possessiveSuffixes }
  , { walsCode := "djp", iso := "dwu", value := .noPossessiveAffixes }
  , { walsCode := "djr", iso := "ddj", value := .noPossessiveAffixes }
  , { walsCode := "dom", iso := "rmt", value := .possessiveSuffixes }
  , { walsCode := "dgo", iso := "doo", value := .possessiveSuffixes }
  , { walsCode := "doy", iso := "dow", value := .possessiveSuffixes }
  , { walsCode := "dre", iso := "dhv", value := .possessiveSuffixes }
  , { walsCode := "dmi", iso := "dus", value := .possessivePrefixes }
  , { walsCode := "dun", iso := "duc", value := .noPossessiveAffixes }
  , { walsCode := "dut", iso := "nld", value := .noPossessiveAffixes }
  , { walsCode := "erk", iso := "erk", value := .possessiveSuffixes }
  , { walsCode := "ene", iso := "", value := .possessiveSuffixes }
  , { walsCode := "egn", iso := "enn", value := .noPossessiveAffixes }
  , { walsCode := "eno", iso := "eno", value := .possessiveSuffixes }
  , { walsCode := "eng", iso := "eng", value := .noPossessiveAffixes }
  , { walsCode := "epe", iso := "sja", value := .noPossessiveAffixes }
  , { walsCode := "ese", iso := "ese", value := .noPossessiveAffixes }
  , { walsCode := "esm", iso := "", value := .possessiveSuffixes }
  , { walsCode := "ess", iso := "esq", value := .possessivePrefixes }
  , { walsCode := "eud", iso := "", value := .possessivePrefixes }
  , { walsCode := "evn", iso := "eve", value := .possessiveSuffixes }
  , { walsCode := "eve", iso := "evn", value := .possessiveSuffixes }
  , { walsCode := "ewe", iso := "ewe", value := .possessiveSuffixes }
  , { walsCode := "ewo", iso := "ewo", value := .noPossessiveAffixes }
  , { walsCode := "fij", iso := "fij", value := .possessiveSuffixes }
  , { walsCode := "fin", iso := "fin", value := .possessiveSuffixes }
  , { walsCode := "fre", iso := "fra", value := .noPossessiveAffixes }
  , { walsCode := "fua", iso := "fub", value := .possessiveSuffixes }
  , { walsCode := "ful", iso := "fun", value := .possessivePrefixes }
  , { walsCode := "fur", iso := "fvr", value := .noPossessiveAffixes }
  , { walsCode := "fut", iso := "fut", value := .possessiveSuffixes }
  , { walsCode := "fye", iso := "pym", value := .possessiveSuffixes }
  , { walsCode := "gds", iso := "gaj", value := .possessivePrefixes }
  , { walsCode := "gah", iso := "gah", value := .prefixesAndSuffixes }
  , { walsCode := "gal", iso := "adl", value := .noPossessiveAffixes }
  , { walsCode := "gar", iso := "grt", value := .noPossessiveAffixes }
  , { walsCode := "grr", iso := "wrk", value := .noPossessiveAffixes }
  , { walsCode := "grs", iso := "gyb", value := .possessiveSuffixes }
  , { walsCode := "grf", iso := "cab", value := .possessivePrefixes }
  , { walsCode := "gav", iso := "gvo", value := .possessivePrefixes }
  , { walsCode := "gbs", iso := "gso", value := .possessiveSuffixes }
  , { walsCode := "gbb", iso := "gbp", value := .possessiveSuffixes }
  , { walsCode := "gel", iso := "nlg", value := .possessiveSuffixes }
  , { walsCode := "geo", iso := "kat", value := .noPossessiveAffixes }
  , { walsCode := "ger", iso := "deu", value := .noPossessiveAffixes }
  , { walsCode := "giz", iso := "gis", value := .possessiveSuffixes }
  , { walsCode := "goa", iso := "guc", value := .possessivePrefixes }
  , { walsCode := "gok", iso := "gkn", value := .possessiveSuffixes }
  , { walsCode := "gln", iso := "gvf", value := .possessiveSuffixes }
  , { walsCode := "gon", iso := "gno", value := .noPossessiveAffixes }
  , { walsCode := "goo", iso := "gni", value := .possessiveSuffixes }
  , { walsCode := "gan", iso := "apq", value := .possessivePrefixes }
  , { walsCode := "grb", iso := "grj", value := .noPossessiveAffixes }
  , { walsCode := "grk", iso := "ell", value := .noPossessiveAffixes }
  , { walsCode := "grw", iso := "kal", value := .possessiveSuffixes }
  , { walsCode := "gjj", iso := "gub", value := .possessivePrefixes }
  , { walsCode := "gua", iso := "gug", value := .possessivePrefixes }
  , { walsCode := "gto", iso := "gta", value := .possessivePrefixes }
  , { walsCode := "gud", iso := "gde", value := .possessiveSuffixes }
  , { walsCode := "gmw", iso := "gvs", value := .possessiveSuffixes }
  , { walsCode := "gmz", iso := "guk", value := .possessiveSuffixes }
  , { walsCode := "gnn", iso := "gww", value := .possessivePrefixes }
  , { walsCode := "gur", iso := "", value := .noPossessiveAffixes }
  , { walsCode := "guu", iso := "kky", value := .noPossessiveAffixes }
  , { walsCode := "gyc", iso := "jya", value := .possessivePrefixes }
  , { walsCode := "gku", iso := "pue", value := .possessiveSuffixes }
  , { walsCode := "hai", iso := "hai", value := .noPossessiveAffixes }
  , { walsCode := "hal", iso := "hla", value := .possessiveSuffixes }
  , { walsCode := "hlu", iso := "hur", value := .possessiveSuffixes }
  , { walsCode := "ham", iso := "hmt", value := .possessivePrefixes }
  , { walsCode := "hhu", iso := "wos", value := .possessiveSuffixes }
  , { walsCode := "har", iso := "tmd", value := .prefixesAndSuffixes }
  , { walsCode := "hat", iso := "had", value := .possessivePrefixes }
  , { walsCode := "hau", iso := "hau", value := .possessiveSuffixes }
  , { walsCode := "haw", iso := "haw", value := .noPossessiveAffixes }
  , { walsCode := "hay", iso := "vay", value := .noPossessiveAffixes }
  , { walsCode := "hdi", iso := "xed", value := .possessiveSuffixes }
  , { walsCode := "heb", iso := "heb", value := .possessiveSuffixes }
  , { walsCode := "hil", iso := "hil", value := .noPossessiveAffixes }
  , { walsCode := "hix", iso := "hix", value := .possessivePrefixes }
  , { walsCode := "hoa", iso := "hoa", value := .possessiveSuffixes }
  , { walsCode := "hop", iso := "hop", value := .prefixesAndSuffixes }
  , { walsCode := "hua", iso := "ygr", value := .prefixesAndSuffixes }
  , { walsCode := "hlp", iso := "yuf", value := .possessivePrefixes }
  , { walsCode := "hve", iso := "huv", value := .possessivePrefixes }
  , { walsCode := "hui", iso := "hch", value := .possessivePrefixes }
  , { walsCode := "hnd", iso := "hke", value := .prefixesAndSuffixes }
  , { walsCode := "hun", iso := "hun", value := .possessiveSuffixes }
  , { walsCode := "hzb", iso := "huz", value := .noPossessiveAffixes }
  , { walsCode := "hpd", iso := "jup", value := .noPossessiveAffixes }
  , { walsCode := "hup", iso := "hup", value := .possessivePrefixes }
  , { walsCode := "isa", iso := "ksi", value := .noPossessiveAffixes }
  , { walsCode := "iaa", iso := "iai", value := .possessiveSuffixes }
  , { walsCode := "iba", iso := "iba", value := .noPossessiveAffixes }
  , { walsCode := "ice", iso := "isl", value := .noPossessiveAffixes }
  , { walsCode := "ifm", iso := "ifm", value := .noPossessiveAffixes }
  , { walsCode := "igb", iso := "ibo", value := .noPossessiveAffixes }
  , { walsCode := "ign", iso := "ign", value := .possessivePrefixes }
  , { walsCode := "ijo", iso := "ijc", value := .possessivePrefixes }
  , { walsCode := "ika", iso := "arh", value := .possessivePrefixes }
  , { walsCode := "ila", iso := "ilb", value := .possessiveSuffixes }
  , { walsCode := "imo", iso := "imn", value := .noPossessiveAffixes }
  , { walsCode := "ina", iso := "szp", value := .possessivePrefixes }
  , { walsCode := "ind", iso := "ind", value := .noPossessiveAffixes }
  , { walsCode := "igs", iso := "tbi", value := .possessiveSuffixes }
  , { walsCode := "ing", iso := "inh", value := .noPossessiveAffixes }
  , { walsCode := "inn", iso := "ynd", value := .noPossessiveAffixes }
  , { walsCode := "iqu", iso := "iqu", value := .possessivePrefixes }
  , { walsCode := "irx", iso := "irn", value := .noPossessiveAffixes }
  , { walsCode := "irq", iso := "irk", value := .possessiveSuffixes }
  , { walsCode := "irr", iso := "irh", value := .possessivePrefixes }
  , { walsCode := "iri", iso := "gle", value := .noPossessiveAffixes }
  , { walsCode := "ita", iso := "ita", value := .noPossessiveAffixes }
  , { walsCode := "ito", iso := "ito", value := .possessivePrefixes }
  , { walsCode := "iwa", iso := "ibd", value := .possessivePrefixes }
  , { walsCode := "ixi", iso := "ixl", value := .possessivePrefixes }
  , { walsCode := "jar", iso := "izr", value := .possessiveSuffixes }
  , { walsCode := "izi", iso := "izz", value := .noPossessiveAffixes }
  , { walsCode := "jbt", iso := "jbt", value := .possessivePrefixes }
  , { walsCode := "jab", iso := "jae", value := .possessiveSuffixes }
  , { walsCode := "jak", iso := "jac", value := .possessivePrefixes }
  , { walsCode := "jms", iso := "djm", value := .noPossessiveAffixes }
  , { walsCode := "jpn", iso := "jpn", value := .noPossessiveAffixes }
  , { walsCode := "jaq", iso := "jqr", value := .possessiveSuffixes }
  , { walsCode := "jrw", iso := "anq", value := .possessivePrefixes }
  , { walsCode := "jeb", iso := "jeb", value := .possessiveSuffixes }
  , { walsCode := "jng", iso := "kac", value := .noPossessiveAffixes }
  , { walsCode := "juk", iso := "jbu", value := .noPossessiveAffixes }
  , { walsCode := "juh", iso := "ktz", value := .noPossessiveAffixes }
  , { walsCode := "kdw", iso := "kbc", value := .possessivePrefixes }
  , { walsCode := "kad", iso := "xtc", value := .possessiveSuffixes }
  , { walsCode := "kai", iso := "kct", value := .noPossessiveAffixes }
  , { walsCode := "kng", iso := "kgp", value := .noPossessiveAffixes }
  , { walsCode := "krr", iso := "kxa", value := .possessiveSuffixes }
  , { walsCode := "kmk", iso := "xal", value := .possessiveSuffixes }
  , { walsCode := "kma", iso := "kay", value := .possessivePrefixes }
  , { walsCode := "kmz", iso := "kms", value := .noPossessiveAffixes }
  , { walsCode := "kms", iso := "xas", value := .possessiveSuffixes }
  , { walsCode := "kam", iso := "xbr", value := .possessiveSuffixes }
  , { walsCode := "kmr", iso := "kgq", value := .possessivePrefixes }
  , { walsCode := "kan", iso := "ogo", value := .noPossessiveAffixes }
  , { walsCode := "knk", iso := "kna", value := .noPossessiveAffixes }
  , { walsCode := "kbu", iso := "kbl", value := .possessiveSuffixes }
  , { walsCode := "knd", iso := "kan", value := .noPossessiveAffixes }
  , { walsCode := "knr", iso := "knc", value := .possessiveSuffixes }
  , { walsCode := "kar", iso := "kah", value := .possessiveSuffixes }
  , { walsCode := "krc", iso := "krc", value := .possessiveSuffixes }
  , { walsCode := "jva", iso := "kpj", value := .possessivePrefixes }
  , { walsCode := "kkp", iso := "kaa", value := .possessiveSuffixes }
  , { walsCode := "kbw", iso := "bwe", value := .possessivePrefixes }
  , { walsCode := "kmj", iso := "kdj", value := .possessivePrefixes }
  , { walsCode := "krk", iso := "kyh", value := .possessivePrefixes }
  , { walsCode := "kaa", iso := "arr", value := .possessivePrefixes }
  , { walsCode := "ktm", iso := "", value := .possessivePrefixes }
  , { walsCode := "ktl", iso := "kcr", value := .possessiveSuffixes }
  , { walsCode := "kau", iso := "pss", value := .possessiveSuffixes }
  , { walsCode := "kws", iso := "xaw", value := .possessiveSuffixes }
  , { walsCode := "kyz", iso := "kyz", value := .possessivePrefixes }
  , { walsCode := "kyl", iso := "eky", value := .noPossessiveAffixes }
  , { walsCode := "kyp", iso := "txu", value := .possessivePrefixes }
  , { walsCode := "kel", iso := "sbc", value := .prefixesAndSuffixes }
  , { walsCode := "ken", iso := "kyq", value := .possessiveSuffixes }
  , { walsCode := "ker", iso := "ker", value := .possessiveSuffixes }
  , { walsCode := "ksa", iso := "kee", value := .possessivePrefixes }
  , { walsCode := "ket", iso := "ket", value := .possessivePrefixes }
  , { walsCode := "kew", iso := "kew", value := .noPossessiveAffixes }
  , { walsCode := "khl", iso := "klj", value := .possessiveSuffixes }
  , { walsCode := "khg", iso := "klr", value := .possessivePrefixes }
  , { walsCode := "kha", iso := "khk", value := .possessiveSuffixes }
  , { walsCode := "kmh", iso := "kjl", value := .possessivePrefixes }
  , { walsCode := "kty", iso := "kca", value := .possessiveSuffixes }
  , { walsCode := "khr", iso := "khr", value := .noPossessiveAffixes }
  , { walsCode := "khs", iso := "kha", value := .noPossessiveAffixes }
  , { walsCode := "khi", iso := "kjj", value := .noPossessiveAffixes }
  , { walsCode := "khm", iso := "khm", value := .noPossessiveAffixes }
  , { walsCode := "kmu", iso := "kjg", value := .noPossessiveAffixes }
  , { walsCode := "kik", iso := "kik", value := .noPossessiveAffixes }
  , { walsCode := "klv", iso := "kij", value := .possessiveSuffixes }
  , { walsCode := "klw", iso := "klb", value := .possessivePrefixes }
  , { walsCode := "kga", iso := "zga", value := .possessiveSuffixes }
  , { walsCode := "kio", iso := "kio", value := .possessivePrefixes }
  , { walsCode := "kri", iso := "kzw", value := .possessivePrefixes }
  , { walsCode := "kgz", iso := "kir", value := .possessiveSuffixes }
  , { walsCode := "krb", iso := "gil", value := .possessiveSuffixes }
  , { walsCode := "klm", iso := "kla", value := .noPossessiveAffixes }
  , { walsCode := "shp", iso := "yak", value := .possessivePrefixes }
  , { walsCode := "koa", iso := "cku", value := .possessivePrefixes }
  , { walsCode := "kob", iso := "kpw", value := .possessivePrefixes }
  , { walsCode := "koe", iso := "xwg", value := .noPossessiveAffixes }
  , { walsCode := "kmo", iso := "kpx", value := .possessiveSuffixes }
  , { walsCode := "kok", iso := "trp", value := .possessivePrefixes }
  , { walsCode := "kkt", iso := "kkk", value := .possessiveSuffixes }
  , { walsCode := "kmb", iso := "", value := .possessivePrefixes }
  , { walsCode := "xbi", iso := "xbi", value := .noPossessiveAffixes }
  , { walsCode := "kop", iso := "koi", value := .possessiveSuffixes }
  , { walsCode := "kon", iso := "kng", value := .noPossessiveAffixes }
  , { walsCode := "knw", iso := "mjd", value := .possessivePrefixes }
  , { walsCode := "krn", iso := "kqz", value := .noPossessiveAffixes }
  , { walsCode := "kfe", iso := "kfz", value := .noPossessiveAffixes }
  , { walsCode := "krw", iso := "khe", value := .possessivePrefixes }
  , { walsCode := "kry", iso := "kpy", value := .noPossessiveAffixes }
  , { walsCode := "kos", iso := "kos", value := .possessiveSuffixes }
  , { walsCode := "kch", iso := "khq", value := .noPossessiveAffixes }
  , { walsCode := "kse", iso := "ses", value := .noPossessiveAffixes }
  , { walsCode := "krh", iso := "xra", value := .possessivePrefixes }
  , { walsCode := "kre", iso := "krs", value := .possessiveSuffixes }
  , { walsCode := "kro", iso := "kgo", value := .noPossessiveAffixes }
  , { walsCode := "knc", iso := "uwa", value := .noPossessiveAffixes }
  , { walsCode := "kya", iso := "gvn", value := .noPossessiveAffixes }
  , { walsCode := "klg", iso := "kle", value := .possessivePrefixes }
  , { walsCode := "kmn", iso := "kue", value := .possessiveSuffixes }
  , { walsCode := "knm", iso := "kun", value := .possessiveSuffixes }
  , { walsCode := "kuo", iso := "kto", value := .noPossessiveAffixes }
  , { walsCode := "krd", iso := "ckb", value := .possessiveSuffixes }
  , { walsCode := "kut", iso := "kut", value := .possessiveSuffixes }
  , { walsCode := "thy", iso := "thd", value := .noPossessiveAffixes }
  , { walsCode := "kwk", iso := "kwk", value := .possessiveSuffixes }
  , { walsCode := "kwn", iso := "kwn", value := .possessiveSuffixes }
  , { walsCode := "kwz", iso := "xwa", value := .noPossessiveAffixes }
  , { walsCode := "kwo", iso := "kmo", value := .noPossessiveAffixes }
  , { walsCode := "kwt", iso := "kwo", value := .noPossessiveAffixes }
  , { walsCode := "kxo", iso := "xuu", value := .possessiveSuffixes }
  , { walsCode := "kyk", iso := "kyc", value := .noPossessiveAffixes }
  , { walsCode := "kyq", iso := "nuk", value := .possessiveSuffixes }
  , { walsCode := "laa", iso := "gdm", value := .possessiveSuffixes }
  , { walsCode := "lag", iso := "kot", value := .possessiveSuffixes }
  , { walsCode := "lai", iso := "cnh", value := .noPossessiveAffixes }
  , { walsCode := "lkt", iso := "lkt", value := .possessivePrefixes }
  , { walsCode := "lal", iso := "ywt", value := .noPossessiveAffixes }
  , { walsCode := "lmh", iso := "slp", value := .possessiveSuffixes }
  , { walsCode := "lmg", iso := "hia", value := .possessiveSuffixes }
  , { walsCode := "lmn", iso := "lmn", value := .noPossessiveAffixes }
  , { walsCode := "lao", iso := "lao", value := .noPossessiveAffixes }
  , { walsCode := "lar", iso := "lrg", value := .possessiveSuffixes }
  , { walsCode := "lat", iso := "lav", value := .noPossessiveAffixes }
  , { walsCode := "lav", iso := "lvk", value := .possessivePrefixes }
  , { walsCode := "lec", iso := "lec", value := .possessivePrefixes }
  , { walsCode := "lel", iso := "lln", value := .possessiveSuffixes }
  , { walsCode := "len", iso := "tnl", value := .possessiveSuffixes }
  , { walsCode := "ldu", iso := "led", value := .possessivePrefixes }
  , { walsCode := "lng", iso := "enx", value := .possessivePrefixes }
  , { walsCode := "lep", iso := "lep", value := .noPossessiveAffixes }
  , { walsCode := "lew", iso := "lww", value := .possessiveSuffixes }
  , { walsCode := "lez", iso := "lez", value := .noPossessiveAffixes }
  , { walsCode := "lil", iso := "lil", value := .possessiveSuffixes }
  , { walsCode := "lml", iso := "lmc", value := .prefixesAndSuffixes }
  , { walsCode := "ara", iso := "arw", value := .possessivePrefixes }
  , { walsCode := "lgu", iso := "lgu", value := .possessiveSuffixes }
  , { walsCode := "lon", iso := "los", value := .possessiveSuffixes }
  , { walsCode := "lou", iso := "loj", value := .possessiveSuffixes }
  , { walsCode := "lda", iso := "lug", value := .possessiveSuffixes }
  , { walsCode := "lui", iso := "lui", value := .possessivePrefixes }
  , { walsCode := "lul", iso := "ule", value := .possessiveSuffixes }
  , { walsCode := "lbu", iso := "lun", value := .possessiveSuffixes }
  , { walsCode := "luo", iso := "luo", value := .possessiveSuffixes }
  , { walsCode := "kkv", iso := "khl", value := .possessiveSuffixes }
  , { walsCode := "luv", iso := "lue", value := .possessiveSuffixes }
  , { walsCode := "jlu", iso := "lwo", value := .possessiveSuffixes }
  , { walsCode := "ma", iso := "msj", value := .possessiveSuffixes }
  , { walsCode := "mab", iso := "mde", value := .noPossessiveAffixes }
  , { walsCode := "mac", iso := "mbc", value := .possessivePrefixes }
  , { walsCode := "mdm", iso := "dmd", value := .possessiveSuffixes }
  , { walsCode := "mne", iso := "nmu", value := .possessivePrefixes }
  , { walsCode := "mpr", iso := "", value := .possessivePrefixes }
  , { walsCode := "mrs", iso := "zrs", value := .possessivePrefixes }
  , { walsCode := "msn", iso := "mbq", value := .possessiveSuffixes }
  , { walsCode := "mak", iso := "myh", value := .noPossessiveAffixes }
  , { walsCode := "mkj", iso := "mkz", value := .noPossessiveAffixes }
  , { walsCode := "mkl", iso := "mgf", value := .possessiveSuffixes }
  , { walsCode := "mal", iso := "plt", value := .noPossessiveAffixes }
  , { walsCode := "mlu", iso := "mgl", value := .prefixesAndSuffixes }
  , { walsCode := "mlg", iso := "", value := .possessiveSuffixes }
  , { walsCode := "mam", iso := "mam", value := .possessivePrefixes }
  , { walsCode := "mmi", iso := "mcs", value := .possessiveSuffixes }
  , { walsCode := "mmw", iso := "mgr", value := .possessiveSuffixes }
  , { walsCode := "mmv", iso := "mdi", value := .possessivePrefixes }
  , { walsCode := "mnm", iso := "mva", value := .possessiveSuffixes }
  , { walsCode := "mdn", iso := "mhq", value := .possessivePrefixes }
  , { walsCode := "mnd", iso := "cmn", value := .noPossessiveAffixes }
  , { walsCode := "myi", iso := "mpc", value := .possessiveSuffixes }
  , { walsCode := "mbt", iso := "mdj", value := .possessiveSuffixes }
  , { walsCode := "mng", iso := "mqy", value := .possessiveSuffixes }
  , { walsCode := "mgg", iso := "mjg", value := .noPossessiveAffixes }
  , { walsCode := "mns", iso := "mns", value := .possessiveSuffixes }
  , { walsCode := "mao", iso := "mri", value := .noPossessiveAffixes }
  , { walsCode := "map", iso := "arn", value := .noPossessiveAffixes }
  , { walsCode := "mra", iso := "mec", value := .possessiveSuffixes }
  , { walsCode := "mku", iso := "zmr", value := .possessiveSuffixes }
  , { walsCode := "mrg", iso := "mrt", value := .possessiveSuffixes }
  , { walsCode := "mme", iso := "mhr", value := .possessiveSuffixes }
  , { walsCode := "mar", iso := "mrc", value := .possessivePrefixes }
  , { walsCode := "mrd", iso := "mrz", value := .possessivePrefixes }
  , { walsCode := "mrt", iso := "vma", value := .possessiveSuffixes }
  , { walsCode := "msl", iso := "mls", value := .possessiveSuffixes }
  , { walsCode := "mtt", iso := "wam", value := .possessivePrefixes }
  , { walsCode := "mts", iso := "mpq", value := .noPossessiveAffixes }
  , { walsCode := "mka", iso := "mxx", value := .noPossessiveAffixes }
  , { walsCode := "mau", iso := "mph", value := .possessivePrefixes }
  , { walsCode := "max", iso := "mbl", value := .possessivePrefixes }
  , { walsCode := "may", iso := "ayz", value := .possessivePrefixes }
  , { walsCode := "myg", iso := "mdm", value := .noPossessiveAffixes }
  , { walsCode := "mzc", iso := "maq", value := .possessiveSuffixes }
  , { walsCode := "mzh", iso := "mau", value := .possessiveSuffixes }
  , { walsCode := "mba", iso := "mfc", value := .possessivePrefixes }
  , { walsCode := "mbr", iso := "mpk", value := .possessiveSuffixes }
  , { walsCode := "mby", iso := "myb", value := .possessiveSuffixes }
  , { walsCode := "mdo", iso := "gmm", value := .noPossessiveAffixes }
  ]

private def allData_1 : List (Datapoint PositionOfPronominalPossessiveAffixes) :=
  [ { walsCode := "mee", iso := "mym", value := .possessiveSuffixes }
  , { walsCode := "mei", iso := "mni", value := .possessivePrefixes }
  , { walsCode := "mek", iso := "skf", value := .possessivePrefixes }
  , { walsCode := "mke", iso := "mek", value := .possessiveSuffixes }
  , { walsCode := "men", iso := "mez", value := .possessivePrefixes }
  , { walsCode := "mnt", iso := "mwv", value := .possessiveSuffixes }
  , { walsCode := "mea", iso := "mej", value := .possessivePrefixes }
  , { walsCode := "mpt", iso := "mpt", value := .noPossessiveAffixes }
  , { walsCode := "mig", iso := "mmy", value := .possessiveSuffixes }
  , { walsCode := "mki", iso := "mik", value := .possessivePrefixes }
  , { walsCode := "mik", iso := "mjw", value := .possessivePrefixes }
  , { walsCode := "min", iso := "min", value := .noPossessiveAffixes }
  , { walsCode := "mnv", iso := "mvn", value := .possessiveSuffixes }
  , { walsCode := "mis", iso := "miq", value := .possessiveSuffixes }
  , { walsCode := "mss", iso := "skd", value := .possessiveSuffixes }
  , { walsCode := "mco", iso := "mco", value := .possessivePrefixes }
  , { walsCode := "mxc", iso := "mig", value := .noPossessiveAffixes }
  , { walsCode := "mxj", iso := "mio", value := .possessiveSuffixes }
  , { walsCode := "mxp", iso := "mil", value := .possessiveSuffixes }
  , { walsCode := "miy", iso := "mkf", value := .possessiveSuffixes }
  , { walsCode := "miz", iso := "lus", value := .noPossessiveAffixes }
  , { walsCode := "mcc", iso := "omc", value := .noPossessiveAffixes }
  , { walsCode := "mcv", iso := "moc", value := .possessivePrefixes }
  , { walsCode := "moh", iso := "moh", value := .possessivePrefixes }
  , { walsCode := "mok", iso := "mkj", value := .possessiveSuffixes }
  , { walsCode := "mko", iso := "moz", value := .possessiveSuffixes }
  , { walsCode := "fqs", iso := "fqs", value := .noPossessiveAffixes }
  , { walsCode := "mon", iso := "mnw", value := .noPossessiveAffixes }
  , { walsCode := "mkh", iso := "", value := .possessiveSuffixes }
  , { walsCode := "mno", iso := "mnr", value := .possessivePrefixes }
  , { walsCode := "moa", iso := "mte", value := .possessiveSuffixes }
  , { walsCode := "mor", iso := "mhz", value := .possessiveSuffixes }
  , { walsCode := "moe", iso := "myv", value := .possessiveSuffixes }
  , { walsCode := "mro", iso := "mor", value := .possessiveSuffixes }
  , { walsCode := "mou", iso := "mgd", value := .possessiveSuffixes }
  , { walsCode := "mtu", iso := "meu", value := .possessiveSuffixes }
  , { walsCode := "mot", iso := "siw", value := .possessivePrefixes }
  , { walsCode := "mpu", iso := "akc", value := .possessivePrefixes }
  , { walsCode := "aoj", iso := "aoj", value := .noPossessiveAffixes }
  , { walsCode := "mui", iso := "bmr", value := .possessivePrefixes }
  , { walsCode := "mum", iso := "mzm", value := .noPossessiveAffixes }
  , { walsCode := "mna", iso := "mnb", value := .possessiveSuffixes }
  , { walsCode := "mdg", iso := "mua", value := .possessiveSuffixes }
  , { walsCode := "mud", iso := "mnf", value := .possessiveSuffixes }
  , { walsCode := "mun", iso := "unr", value := .possessiveSuffixes }
  , { walsCode := "muu", iso := "myu", value := .possessivePrefixes }
  , { walsCode := "mnz", iso := "moj", value := .noPossessiveAffixes }
  , { walsCode := "mup", iso := "sur", value := .noPossessiveAffixes }
  , { walsCode := "mrl", iso := "mur", value := .possessiveSuffixes }
  , { walsCode := "mur", iso := "muz", value := .possessiveSuffixes }
  , { walsCode := "mgu", iso := "mug", value := .possessiveSuffixes }
  , { walsCode := "msm", iso := "msu", value := .possessiveSuffixes }
  , { walsCode := "mus", iso := "emi", value := .possessiveSuffixes }
  , { walsCode := "mut", iso := "css", value := .possessivePrefixes }
  , { walsCode := "mwo", iso := "mlv", value := .possessiveSuffixes }
  , { walsCode := "nab", iso := "naf", value := .possessiveSuffixes }
  , { walsCode := "nze", iso := "nzm", value := .noPossessiveAffixes }
  , { walsCode := "nag", iso := "nce", value := .possessivePrefixes }
  , { walsCode := "nhh", iso := "", value := .possessivePrefixes }
  , { walsCode := "nhm", iso := "ncl", value := .possessivePrefixes }
  , { walsCode := "nhn", iso := "ncj", value := .possessivePrefixes }
  , { walsCode := "nht", iso := "nhg", value := .possessivePrefixes }
  , { walsCode := "bio", iso := "bio", value := .noPossessiveAffixes }
  , { walsCode := "nak", iso := "nak", value := .possessiveSuffixes }
  , { walsCode := "nkk", iso := "nck", value := .possessivePrefixes }
  , { walsCode := "nmb", iso := "nab", value := .possessivePrefixes }
  , { walsCode := "nam", iso := "nnm", value := .noPossessiveAffixes }
  , { walsCode := "nnc", iso := "ncb", value := .noPossessiveAffixes }
  , { walsCode := "nan", iso := "niq", value := .possessiveSuffixes }
  , { walsCode := "nrg", iso := "sen", value := .noPossessiveAffixes }
  , { walsCode := "nnk", iso := "nnk", value := .possessiveSuffixes }
  , { walsCode := "nas", iso := "nas", value := .possessivePrefixes }
  , { walsCode := "nav", iso := "nav", value := .possessivePrefixes }
  , { walsCode := "ncm", iso := "bud", value := .possessivePrefixes }
  , { walsCode := "ndb", iso := "nde", value := .noPossessiveAffixes }
  , { walsCode := "ndj", iso := "djj", value := .prefixesAndSuffixes }
  , { walsCode := "ndo", iso := "ndo", value := .possessiveSuffixes }
  , { walsCode := "ndu", iso := "nmd", value := .noPossessiveAffixes }
  , { walsCode := "ndt", iso := "ndv", value := .noPossessiveAffixes }
  , { walsCode := "ndy", iso := "djk", value := .noPossessiveAffixes }
  , { walsCode := "neh", iso := "nsn", value := .possessiveSuffixes }
  , { walsCode := "ntu", iso := "yrk", value := .possessiveSuffixes }
  , { walsCode := "naj", iso := "aij", value := .possessiveSuffixes }
  , { walsCode := "nev", iso := "pia", value := .possessivePrefixes }
  , { walsCode := "nwd", iso := "new", value := .noPossessiveAffixes }
  , { walsCode := "new", iso := "new", value := .noPossessiveAffixes }
  , { walsCode := "nez", iso := "nez", value := .possessivePrefixes }
  , { walsCode := "ntj", iso := "ntj", value := .possessiveSuffixes }
  , { walsCode := "ngl", iso := "nig", value := .possessiveSuffixes }
  , { walsCode := "ngm", iso := "sba", value := .possessiveSuffixes }
  , { walsCode := "nga", iso := "nio", value := .possessiveSuffixes }
  , { walsCode := "ngn", iso := "nid", value := .possessiveSuffixes }
  , { walsCode := "ngk", iso := "nam", value := .noPossessiveAffixes }
  , { walsCode := "nti", iso := "niy", value := .possessiveSuffixes }
  , { walsCode := "ngi", iso := "wyb", value := .noPossessiveAffixes }
  , { walsCode := "ngz", iso := "ngi", value := .possessiveSuffixes }
  , { walsCode := "ngo", iso := "ngo", value := .noPossessiveAffixes }
  , { walsCode := "nha", iso := "nha", value := .possessiveSuffixes }
  , { walsCode := "nia", iso := "nia", value := .possessiveSuffixes }
  , { walsCode := "nca", iso := "caq", value := .noPossessiveAffixes }
  , { walsCode := "nsn", iso := "nsz", value := .possessivePrefixes }
  , { walsCode := "nsg", iso := "ncg", value := .possessiveSuffixes }
  , { walsCode := "niu", iso := "niu", value := .noPossessiveAffixes }
  , { walsCode := "niv", iso := "niv", value := .possessivePrefixes }
  , { walsCode := "nke", iso := "isi", value := .noPossessiveAffixes }
  , { walsCode := "nog", iso := "nog", value := .possessiveSuffixes }
  , { walsCode := "non", iso := "nhu", value := .noPossessiveAffixes }
  , { walsCode := "noo", iso := "snf", value := .possessiveSuffixes }
  , { walsCode := "nor", iso := "nor", value := .noPossessiveAffixes }
  , { walsCode := "nua", iso := "nxl", value := .prefixesAndSuffixes }
  , { walsCode := "nbd", iso := "dgl", value := .possessivePrefixes }
  , { walsCode := "nue", iso := "nus", value := .possessiveSuffixes }
  , { walsCode := "nun", iso := "nut", value := .noPossessiveAffixes }
  , { walsCode := "nym", iso := "nym", value := .noPossessiveAffixes }
  , { walsCode := "nis", iso := "njz", value := .noPossessiveAffixes }
  , { walsCode := "nyu", iso := "nyv", value := .possessivePrefixes }
  , { walsCode := "nza", iso := "nzk", value := .possessiveSuffixes }
  , { walsCode := "ood", iso := "ood", value := .possessivePrefixes }
  , { walsCode := "obo", iso := "ann", value := .noPossessiveAffixes }
  , { walsCode := "ocu", iso := "ocu", value := .possessivePrefixes }
  , { walsCode := "obg", iso := "ogu", value := .noPossessiveAffixes }
  , { walsCode := "oir", iso := "xal", value := .possessiveSuffixes }
  , { walsCode := "oji", iso := "", value := .prefixesAndSuffixes }
  , { walsCode := "oks", iso := "opm", value := .prefixesAndSuffixes }
  , { walsCode := "ond", iso := "one", value := .possessivePrefixes }
  , { walsCode := "ong", iso := "oon", value := .possessiveSuffixes }
  , { walsCode := "ord", iso := "mvf", value := .possessiveSuffixes }
  , { walsCode := "ork", iso := "oaa", value := .possessiveSuffixes }
  , { walsCode := "orh", iso := "hae", value := .noPossessiveAffixes }
  , { walsCode := "osa", iso := "osa", value := .noPossessiveAffixes }
  , { walsCode := "oss", iso := "oss", value := .noPossessiveAffixes }
  , { walsCode := "paa", iso := "pqa", value := .possessiveSuffixes }
  , { walsCode := "pkn", iso := "drl", value := .possessiveSuffixes }
  , { walsCode := "pms", iso := "pma", value := .possessiveSuffixes }
  , { walsCode := "pno", iso := "pao", value := .noPossessiveAffixes }
  , { walsCode := "pal", iso := "pau", value := .possessiveSuffixes }
  , { walsCode := "plk", iso := "plu", value := .possessivePrefixes }
  , { walsCode := "pre", iso := "asa", value := .possessiveSuffixes }
  , { walsCode := "psh", iso := "pst", value := .noPossessiveAffixes }
  , { walsCode := "plh", iso := "plh", value := .prefixesAndSuffixes }
  , { walsCode := "pau", iso := "pad", value := .prefixesAndSuffixes }
  , { walsCode := "paw", iso := "pwa", value := .noPossessiveAffixes }
  , { walsCode := "pwn", iso := "paw", value := .possessivePrefixes }
  , { walsCode := "per", iso := "pip", value := .possessiveSuffixes }
  , { walsCode := "prs", iso := "pes", value := .noPossessiveAffixes }
  , { walsCode := "pia", iso := "pid", value := .possessivePrefixes }
  , { walsCode := "pga", iso := "plg", value := .possessivePrefixes }
  , { walsCode := "pba", iso := "pia", value := .possessivePrefixes }
  , { walsCode := "pip", iso := "ppl", value := .possessivePrefixes }
  , { walsCode := "pir", iso := "pib", value := .possessivePrefixes }
  , { walsCode := "pod", iso := "pbi", value := .possessiveSuffixes }
  , { walsCode := "poh", iso := "pon", value := .possessiveSuffixes }
  , { walsCode := "pok", iso := "rwa", value := .noPossessiveAffixes }
  , { walsCode := "pkt", iso := "pko", value := .possessiveSuffixes }
  , { walsCode := "pme", iso := "peb", value := .possessivePrefixes }
  , { walsCode := "zqs", iso := "poi", value := .possessivePrefixes }
  , { walsCode := "psw", iso := "psw", value := .possessiveSuffixes }
  , { walsCode := "pul", iso := "puw", value := .possessiveSuffixes }
  , { walsCode := "puq", iso := "puq", value := .noPossessiveAffixes }
  , { walsCode := "prk", iso := "prx", value := .noPossessiveAffixes }
  , { walsCode := "pur", iso := "tsz", value := .possessiveSuffixes }
  , { walsCode := "par", iso := "lkr", value := .possessiveSuffixes }
  , { walsCode := "qaf", iso := "aar", value := .noPossessiveAffixes }
  , { walsCode := "qhu", iso := "qub", value := .possessiveSuffixes }
  , { walsCode := "qim", iso := "qvi", value := .noPossessiveAffixes }
  , { walsCode := "qui", iso := "qui", value := .possessiveSuffixes }
  , { walsCode := "rag", iso := "lml", value := .possessiveSuffixes }
  , { walsCode := "ram", iso := "rma", value := .possessivePrefixes }
  , { walsCode := "rao", iso := "rao", value := .noPossessiveAffixes }
  , { walsCode := "ras", iso := "ras", value := .possessiveSuffixes }
  , { walsCode := "rwa", iso := "rwo", value := .possessiveSuffixes }
  , { walsCode := "raw", iso := "raw", value := .noPossessiveAffixes }
  , { walsCode := "rem", iso := "bfw", value := .noPossessiveAffixes }
  , { walsCode := "res", iso := "rgr", value := .possessivePrefixes }
  , { walsCode := "rik", iso := "rkb", value := .possessivePrefixes }
  , { walsCode := "rit", iso := "rit", value := .possessiveSuffixes }
  , { walsCode := "rom", iso := "ron", value := .noPossessiveAffixes }
  , { walsCode := "rov", iso := "rug", value := .possessiveSuffixes }
  , { walsCode := "ruk", iso := "dru", value := .possessiveSuffixes }
  , { walsCode := "rum", iso := "klq", value := .noPossessiveAffixes }
  , { walsCode := "run", iso := "rou", value := .possessivePrefixes }
  , { walsCode := "rny", iso := "nyn", value := .noPossessiveAffixes }
  , { walsCode := "rus", iso := "rus", value := .noPossessiveAffixes }
  , { walsCode := "rut", iso := "rut", value := .noPossessiveAffixes }
  , { walsCode := "saa", iso := "apb", value := .possessiveSuffixes }
  , { walsCode := "sno", iso := "sme", value := .possessiveSuffixes }
  , { walsCode := "sah", iso := "saj", value := .noPossessiveAffixes }
  , { walsCode := "sak", iso := "sku", value := .possessiveSuffixes }
  , { walsCode := "slb", iso := "sbe", value := .possessiveSuffixes }
  , { walsCode := "sal", iso := "sln", value := .prefixesAndSuffixes }
  , { walsCode := "syu", iso := "sll", value := .possessiveSuffixes }
  , { walsCode := "sam", iso := "smo", value := .noPossessiveAffixes }
  , { walsCode := "sdw", iso := "sad", value := .noPossessiveAffixes }
  , { walsCode := "san", iso := "sag", value := .noPossessiveAffixes }
  , { walsCode := "sta", iso := "sce", value := .possessiveSuffixes }
  , { walsCode := "stl", iso := "sat", value := .possessiveSuffixes }
  , { walsCode := "snm", iso := "xsu", value := .noPossessiveAffixes }
  , { walsCode := "src", iso := "srs", value := .possessivePrefixes }
  , { walsCode := "svs", iso := "svs", value := .noPossessiveAffixes }
  , { walsCode := "seb", iso := "kpz", value := .possessiveSuffixes }
  , { walsCode := "slp", iso := "spl", value := .possessiveSuffixes }
  , { walsCode := "skp", iso := "sel", value := .possessiveSuffixes }
  , { walsCode := "sem", iso := "nsm", value := .possessivePrefixes }
  , { walsCode := "smn", iso := "mus", value := .possessivePrefixes }
  , { walsCode := "sen", iso := "seh", value := .possessiveSuffixes }
  , { walsCode := "snt", iso := "set", value := .noPossessiveAffixes }
  , { walsCode := "scr", iso := "hbs", value := .noPossessiveAffixes }
  , { walsCode := "ser", iso := "sei", value := .possessivePrefixes }
  , { walsCode := "shm", iso := "ksb", value := .possessiveSuffixes }
  , { walsCode := "sht", iso := "shj", value := .possessiveSuffixes }
  , { walsCode := "shl", iso := "shk", value := .possessiveSuffixes }
  , { walsCode := "shk", iso := "shp", value := .noPossessiveAffixes }
  , { walsCode := "shi", iso := "shb", value := .possessiveSuffixes }
  , { walsCode := "smp", iso := "sii", value := .noPossessiveAffixes }
  , { walsCode := "shu", iso := "shs", value := .prefixesAndSuffixes }
  , { walsCode := "sia", iso := "snp", value := .possessiveSuffixes }
  , { walsCode := "skk", iso := "sip", value := .noPossessiveAffixes }
  , { walsCode := "sng", iso := "snc", value := .possessiveSuffixes }
  , { walsCode := "sio", iso := "xsi", value := .possessiveSuffixes }
  , { walsCode := "qum", iso := "qum", value := .possessivePrefixes }
  , { walsCode := "srn", iso := "srq", value := .possessivePrefixes }
  , { walsCode := "sro", iso := "ssd", value := .noPossessiveAffixes }
  , { walsCode := "sis", iso := "baa", value := .possessiveSuffixes }
  , { walsCode := "siu", iso := "sis", value := .possessiveSuffixes }
  , { walsCode := "sla", iso := "den", value := .possessivePrefixes }
  , { walsCode := "so", iso := "teu", value := .possessiveSuffixes }
  , { walsCode := "sob", iso := "sob", value := .possessiveSuffixes }
  , { walsCode := "sod", iso := "gru", value := .possessiveSuffixes }
  , { walsCode := "som", iso := "som", value := .possessiveSuffixes }
  , { walsCode := "son", iso := "sov", value := .possessiveSuffixes }
  , { walsCode := "sgb", iso := "mnx", value := .possessivePrefixes }
  , { walsCode := "spa", iso := "spa", value := .noPossessiveAffixes }
  , { walsCode := "squ", iso := "squ", value := .prefixesAndSuffixes }
  , { walsCode := "sue", iso := "sue", value := .noPossessiveAffixes }
  , { walsCode := "sul", iso := "sua", value := .possessivePrefixes }
  , { walsCode := "sup", iso := "spp", value := .noPossessiveAffixes }
  , { walsCode := "swa", iso := "swh", value := .possessiveSuffixes }
  , { walsCode := "swe", iso := "swe", value := .noPossessiveAffixes }
  , { walsCode := "tba", iso := "sst", value := .possessiveSuffixes }
  , { walsCode := "tac", iso := "tna", value := .noPossessiveAffixes }
  , { walsCode := "trr", iso := "tbg", value := .possessivePrefixes }
  , { walsCode := "taj", iso := "tgk", value := .noPossessiveAffixes }
  , { walsCode := "tkl", iso := "tkm", value := .possessiveSuffixes }
  , { walsCode := "tak", iso := "tbc", value := .possessiveSuffixes }
  , { walsCode := "tma", iso := "tma", value := .noPossessiveAffixes }
  , { walsCode := "tmg", iso := "tcg", value := .noPossessiveAffixes }
  , { walsCode := "tsk", iso := "taq", value := .possessiveSuffixes }
  , { walsCode := "tnc", iso := "tcb", value := .possessivePrefixes }
  , { walsCode := "tan", iso := "tan", value := .possessiveSuffixes }
  , { walsCode := "tpt", iso := "tpj", value := .possessivePrefixes }
  , { walsCode := "twe", iso := "tac", value := .noPossessiveAffixes }
  , { walsCode := "tar", iso := "tae", value := .possessivePrefixes }
  , { walsCode := "tas", iso := "shi", value := .possessiveSuffixes }
  , { walsCode := "tvo", iso := "tat", value := .possessiveSuffixes }
  , { walsCode := "tau", iso := "tya", value := .possessivePrefixes }
  , { walsCode := "tbo", iso := "tbl", value := .possessiveSuffixes }
  , { walsCode := "tne", iso := "tem", value := .noPossessiveAffixes }
  , { walsCode := "ten", iso := "tex", value := .noPossessiveAffixes }
  , { walsCode := "teo", iso := "tio", value := .possessiveSuffixes }
  , { walsCode := "tee", iso := "tee", value := .possessivePrefixes }
  , { walsCode := "tep", iso := "tpt", value := .possessivePrefixes }
  , { walsCode := "tpn", iso := "ntp", value := .possessivePrefixes }
  , { walsCode := "tps", iso := "stp", value := .possessivePrefixes }
  , { walsCode := "ter", iso := "ttr", value := .possessiveSuffixes }
  , { walsCode := "trb", iso := "tfr", value := .noPossessiveAffixes }
  , { walsCode := "tes", iso := "teo", value := .prefixesAndSuffixes }
  , { walsCode := "tet", iso := "tll", value := .noPossessiveAffixes }
  , { walsCode := "ttn", iso := "tet", value := .noPossessiveAffixes }
  , { walsCode := "ttd", iso := "tet", value := .noPossessiveAffixes }
  , { walsCode := "tha", iso := "tha", value := .noPossessiveAffixes }
  , { walsCode := "tic", iso := "tca", value := .possessivePrefixes }
  , { walsCode := "tid", iso := "tvo", value := .possessivePrefixes }
  , { walsCode := "tgk", iso := "tgc", value := .possessiveSuffixes }
  , { walsCode := "tig", iso := "tir", value := .possessiveSuffixes }
  , { walsCode := "tgr", iso := "tig", value := .possessiveSuffixes }
  , { walsCode := "tja", iso := "dih", value := .possessivePrefixes }
  , { walsCode := "tia", iso := "tms", value := .possessiveSuffixes }
  , { walsCode := "tmc", iso := "tjm", value := .possessiveSuffixes }
  , { walsCode := "tin", iso := "cir", value := .possessiveSuffixes }
  , { walsCode := "tir", iso := "tri", value := .possessivePrefixes }
  , { walsCode := "trm", iso := "suq", value := .possessiveSuffixes }
  , { walsCode := "twn", iso := "twf", value := .possessivePrefixes }
  , { walsCode := "tiw", iso := "tiw", value := .noPossessiveAffixes }
  , { walsCode := "tlp", iso := "tcf", value := .possessiveSuffixes }
  , { walsCode := "tli", iso := "tli", value := .possessivePrefixes }
  , { walsCode := "tob", iso := "tob", value := .possessivePrefixes }
  , { walsCode := "tlo", iso := "tlb", value := .possessivePrefixes }
  , { walsCode := "tla", iso := "ksd", value := .possessiveSuffixes }
  , { walsCode := "tno", iso := "tdn", value := .possessiveSuffixes }
  , { walsCode := "toz", iso := "toi", value := .possessiveSuffixes }
  , { walsCode := "tng", iso := "ton", value := .noPossessiveAffixes }
  , { walsCode := "ton", iso := "tqw", value := .possessivePrefixes }
  , { walsCode := "tot", iso := "tlc", value := .possessivePrefixes }
  , { walsCode := "txj", iso := "too", value := .possessivePrefixes }
  , { walsCode := "tri", iso := "trc", value := .noPossessiveAffixes }
  , { walsCode := "tru", iso := "tpy", value := .prefixesAndSuffixes }
  , { walsCode := "tsz", iso := "ddo", value := .noPossessiveAffixes }
  , { walsCode := "tgl", iso := "tsj", value := .noPossessiveAffixes }
  , { walsCode := "tsi", iso := "tsi", value := .possessiveSuffixes }
  , { walsCode := "tai", iso := "thz", value := .possessiveSuffixes }
  , { walsCode := "tbu", iso := "", value := .possessiveSuffixes }
  , { walsCode := "tgn", iso := "tzn", value := .possessivePrefixes }
  , { walsCode := "tuk", iso := "", value := .noPossessiveAffixes }
  , { walsCode := "tum", iso := "tmq", value := .possessiveSuffixes }
  , { walsCode := "tnn", iso := "tvu", value := .noPossessiveAffixes }
  , { walsCode := "tun", iso := "tun", value := .possessivePrefixes }
  , { walsCode := "tur", iso := "tur", value := .possessiveSuffixes }
  , { walsCode := "tus", iso := "tus", value := .possessivePrefixes }
  , { walsCode := "tte", iso := "tta", value := .possessivePrefixes }
  , { walsCode := "tuv", iso := "tyv", value := .possessiveSuffixes }
  , { walsCode := "tzo", iso := "tzo", value := .possessivePrefixes }
  , { walsCode := "tzu", iso := "tzj", value := .possessivePrefixes }
  , { walsCode := "tsh", iso := "par", value := .noPossessiveAffixes }
  , { walsCode := "uby", iso := "uby", value := .possessivePrefixes }
  , { walsCode := "udi", iso := "udi", value := .noPossessiveAffixes }
  , { walsCode := "udm", iso := "udm", value := .possessiveSuffixes }
  , { walsCode := "ukr", iso := "ukr", value := .noPossessiveAffixes }
  , { walsCode := "uli", iso := "uli", value := .possessiveSuffixes }
  , { walsCode := "una", iso := "mtg", value := .possessivePrefixes }
  , { walsCode := "ung", iso := "ung", value := .prefixesAndSuffixes }
  , { walsCode := "uhi", iso := "urf", value := .noPossessiveAffixes }
  , { walsCode := "url", iso := "urk", value := .noPossessiveAffixes }
  , { walsCode := "urt", iso := "urt", value := .noPossessiveAffixes }
  , { walsCode := "urk", iso := "urb", value := .possessivePrefixes }
  , { walsCode := "usr", iso := "usa", value := .prefixesAndSuffixes }
  , { walsCode := "ute", iso := "ute", value := .possessiveSuffixes }
  , { walsCode := "uyg", iso := "uig", value := .possessiveSuffixes }
  , { walsCode := "uzb", iso := "", value := .possessiveSuffixes }
  , { walsCode := "vai", iso := "vai", value := .noPossessiveAffixes }
  , { walsCode := "vie", iso := "vie", value := .noPossessiveAffixes }
  , { walsCode := "vnm", iso := "vnm", value := .possessiveSuffixes }
  , { walsCode := "wah", iso := "", value := .possessiveSuffixes }
  , { walsCode := "wak", iso := "wbl", value := .noPossessiveAffixes }
  , { walsCode := "wal", iso := "van", value := .noPossessiveAffixes }
  , { walsCode := "wbn", iso := "wms", value := .possessivePrefixes }
  , { walsCode := "wao", iso := "auc", value := .noPossessiveAffixes }
  , { walsCode := "wap", iso := "wao", value := .possessivePrefixes }
  , { walsCode := "wra", iso := "wba", value := .possessivePrefixes }
  , { walsCode := "wrk", iso := "gae", value := .possessivePrefixes }
  , { walsCode := "war", iso := "pav", value := .possessiveSuffixes }
  , { walsCode := "wrn", iso := "wnd", value := .possessivePrefixes }
  , { walsCode := "wrb", iso := "gjm", value := .possessiveSuffixes }
  , { walsCode := "wrw", iso := "wwr", value := .possessivePrefixes }
  , { walsCode := "was", iso := "was", value := .possessivePrefixes }
  , { walsCode := "wsk", iso := "wsk", value := .possessivePrefixes }
  , { walsCode := "wth", iso := "wth", value := .possessiveSuffixes }
  , { walsCode := "wat", iso := "wbv", value := .possessiveSuffixes }
  , { walsCode := "way", iso := "oym", value := .possessivePrefixes }
  , { walsCode := "wed", iso := "wed", value := .possessiveSuffixes }
  , { walsCode := "wem", iso := "xww", value := .possessiveSuffixes }
  , { walsCode := "wma", iso := "mqs", value := .possessivePrefixes }
  , { walsCode := "wic", iso := "wic", value := .possessivePrefixes }
  , { walsCode := "wch", iso := "mzh", value := .possessivePrefixes }
  , { walsCode := "wik", iso := "yok", value := .noPossessiveAffixes }
  , { walsCode := "win", iso := "wnw", value := .noPossessiveAffixes }
  , { walsCode := "wir", iso := "wgu", value := .noPossessiveAffixes }
  , { walsCode := "wiy", iso := "wiy", value := .possessivePrefixes }
  , { walsCode := "wly", iso := "wal", value := .noPossessiveAffixes }
  , { walsCode := "wol", iso := "woe", value := .possessiveSuffixes }
  , { walsCode := "wlo", iso := "wlo", value := .possessiveSuffixes }
  , { walsCode := "wlf", iso := "wol", value := .possessiveSuffixes }
  , { walsCode := "wom", iso := "wmx", value := .noPossessiveAffixes }
  , { walsCode := "wor", iso := "wro", value := .possessivePrefixes }
  , { walsCode := "wya", iso := "wya", value := .possessivePrefixes }
  , { walsCode := "xav", iso := "xav", value := .possessivePrefixes }
  , { walsCode := "xer", iso := "xer", value := .possessivePrefixes }
  , { walsCode := "xho", iso := "xho", value := .noPossessiveAffixes }
  , { walsCode := "xar", iso := "ane", value := .possessiveSuffixes }
  , { walsCode := "ygr", iso := "ygr", value := .prefixesAndSuffixes }
  , { walsCode := "yag", iso := "yad", value := .possessivePrefixes }
  , { walsCode := "yah", iso := "yag", value := .noPossessiveAffixes }
  , { walsCode := "ykt", iso := "sah", value := .possessiveSuffixes }
  , { walsCode := "yap", iso := "yap", value := .possessiveSuffixes }
  , { walsCode := "yqy", iso := "jaq", value := .possessivePrefixes }
  , { walsCode := "yaq", iso := "yaq", value := .noPossessiveAffixes }
  , { walsCode := "yar", iso := "yrb", value := .noPossessiveAffixes }
  , { walsCode := "ywl", iso := "yok", value := .noPossessiveAffixes }
  , { walsCode := "yel", iso := "yle", value := .possessivePrefixes }
  , { walsCode := "yid", iso := "yii", value := .noPossessiveAffixes }
  , { walsCode := "yng", iso := "yia", value := .possessiveSuffixes }
  , { walsCode := "yok", iso := "yok", value := .noPossessiveAffixes }
  , { walsCode := "yor", iso := "yor", value := .noPossessiveAffixes }
  , { walsCode := "yuc", iso := "yuc", value := .possessivePrefixes }
  , { walsCode := "yko", iso := "yux", value := .possessiveSuffixes }
  , { walsCode := "yuk", iso := "gcd", value := .noPossessiveAffixes }
  , { walsCode := "yul", iso := "yul", value := .possessiveSuffixes }
  , { walsCode := "ypk", iso := "esu", value := .possessiveSuffixes }
  , { walsCode := "yur", iso := "yur", value := .possessivePrefixes }
  , { walsCode := "yuw", iso := "kld", value := .noPossessiveAffixes }
  , { walsCode := "zan", iso := "zne", value := .possessiveSuffixes }
  , { walsCode := "zpr", iso := "zro", value := .possessivePrefixes }
  , { walsCode := "zai", iso := "zai", value := .possessiveSuffixes }
  , { walsCode := "zap", iso := "zaw", value := .possessiveSuffixes }
  , { walsCode := "zzo", iso := "zpq", value := .possessiveSuffixes }
  , { walsCode := "zen", iso := "zen", value := .possessiveSuffixes }
  , { walsCode := "zhn", iso := "zgb", value := .noPossessiveAffixes }
  , { walsCode := "zqc", iso := "zoc", value := .possessivePrefixes }
  , { walsCode := "zqo", iso := "zoc", value := .possessivePrefixes }
  , { walsCode := "zun", iso := "zun", value := .noPossessiveAffixes }
  , { walsCode := "rgc", iso := "jya", value := .possessivePrefixes }
  , { walsCode := "eme", iso := "eme", value := .possessivePrefixes }
  , { walsCode := "omi", iso := "aom", value := .noPossessiveAffixes }
  ]

/-- Complete WALS 57A dataset (902 languages). -/
def allData : List (Datapoint PositionOfPronominalPossessiveAffixes) := allData_0 ++ allData_1

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F57A
