import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 73A: The Optative
@cite{wals-2013}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 73A`.

Chapter 73, 319 languages.
-/

namespace Core.WALS.F73A

/-- WALS 73A values. -/
inductive Optative where
  /-- Inflectional optative present (48 languages). -/
  | present
  /-- Inflectional optative absent (271 languages). -/
  | absent
  deriving DecidableEq, BEq, Repr

/-- Complete WALS 73A dataset (319 languages). -/
def allData : List (Datapoint Optative) :=
  [ { walsCode := "abz", iso := "abq", value := .present }
  , { walsCode := "abk", iso := "abk", value := .present }
  , { walsCode := "aco", iso := "kjq", value := .absent }
  , { walsCode := "adt", iso := "ady", value := .present }
  , { walsCode := "agl", iso := "agx", value := .present }
  , { walsCode := "ain", iso := "ain", value := .absent }
  , { walsCode := "awk", iso := "akw", value := .absent }
  , { walsCode := "ala", iso := "amp", value := .absent }
  , { walsCode := "alb", iso := "sqi", value := .present }
  , { walsCode := "aso", iso := "alt", value := .absent }
  , { walsCode := "alu", iso := "alr", value := .absent }
  , { walsCode := "ame", iso := "aey", value := .absent }
  , { walsCode := "apl", iso := "apy", value := .absent }
  , { walsCode := "apu", iso := "apu", value := .absent }
  , { walsCode := "aeg", iso := "arz", value := .absent }
  , { walsCode := "amr", iso := "ary", value := .absent }
  , { walsCode := "ana", iso := "aro", value := .absent }
  , { walsCode := "arp", iso := "ape", value := .absent }
  , { walsCode := "arc", iso := "aqc", value := .present }
  , { walsCode := "arm", iso := "hye", value := .absent }
  , { walsCode := "asm", iso := "cns", value := .absent }
  , { walsCode := "ava", iso := "ava", value := .present }
  , { walsCode := "awp", iso := "kwi", value := .absent }
  , { walsCode := "aym", iso := "ayr", value := .present }
  , { walsCode := "aze", iso := "", value := .present }
  , { walsCode := "bag", iso := "bmi", value := .absent }
  , { walsCode := "bgv", iso := "kva", value := .present }
  , { walsCode := "bam", iso := "bam", value := .absent }
  , { walsCode := "brs", iso := "bsn", value := .absent }
  , { walsCode := "bsk", iso := "bak", value := .absent }
  , { walsCode := "bsq", iso := "eus", value := .absent }
  , { walsCode := "bkr", iso := "btx", value := .absent }
  , { walsCode := "baw", iso := "bgr", value := .absent }
  , { walsCode := "bem", iso := "bem", value := .absent }
  , { walsCode := "bma", iso := "tzm", value := .absent }
  , { walsCode := "bez", iso := "kap", value := .present }
  , { walsCode := "bir", iso := "bom", value := .absent }
  , { walsCode := "brh", iso := "brh", value := .absent }
  , { walsCode := "bul", iso := "bul", value := .absent }
  , { walsCode := "but", iso := "bxm", value := .present }
  , { walsCode := "brm", iso := "mya", value := .absent }
  , { walsCode := "bur", iso := "bsk", value := .absent }
  , { walsCode := "cah", iso := "chl", value := .absent }
  , { walsCode := "cak", iso := "cak", value := .absent }
  , { walsCode := "car", iso := "car", value := .absent }
  , { walsCode := "csh", iso := "cbs", value := .absent }
  , { walsCode := "ceb", iso := "ceb", value := .absent }
  , { walsCode := "cha", iso := "cha", value := .absent }
  , { walsCode := "chc", iso := "che", value := .present }
  , { walsCode := "cle", iso := "cle", value := .present }
  , { walsCode := "chr", iso := "crw", value := .absent }
  , { walsCode := "chk", iso := "ckt", value := .absent }
  , { walsCode := "chv", iso := "chv", value := .absent }
  , { walsCode := "cmn", iso := "com", value := .absent }
  , { walsCode := "coo", iso := "csz", value := .absent }
  , { walsCode := "cre", iso := "crk", value := .absent }
  , { walsCode := "dbd", iso := "dav", value := .absent }
  , { walsCode := "dgr", iso := "dta", value := .absent }
  , { walsCode := "dni", iso := "dni", value := .absent }
  , { walsCode := "dsh", iso := "dan", value := .absent }
  , { walsCode := "drg", iso := "dar", value := .present }
  , { walsCode := "dio", iso := "dyo", value := .absent }
  , { walsCode := "dre", iso := "dhv", value := .absent }
  , { walsCode := "dmi", iso := "dus", value := .present }
  , { walsCode := "eng", iso := "eng", value := .absent }
  , { walsCode := "epe", iso := "sja", value := .absent }
  , { walsCode := "est", iso := "ekk", value := .absent }
  , { walsCode := "evn", iso := "eve", value := .absent }
  , { walsCode := "eve", iso := "evn", value := .present }
  , { walsCode := "ewe", iso := "ewe", value := .absent }
  , { walsCode := "fij", iso := "fij", value := .absent }
  , { walsCode := "fin", iso := "fin", value := .absent }
  , { walsCode := "fre", iso := "fra", value := .absent }
  , { walsCode := "fur", iso := "fvr", value := .absent }
  , { walsCode := "gar", iso := "grt", value := .absent }
  , { walsCode := "gbk", iso := "gya", value := .absent }
  , { walsCode := "geo", iso := "kat", value := .present }
  , { walsCode := "ger", iso := "deu", value := .absent }
  , { walsCode := "god", iso := "gdo", value := .present }
  , { walsCode := "goo", iso := "gni", value := .absent }
  , { walsCode := "grb", iso := "grj", value := .absent }
  , { walsCode := "grk", iso := "ell", value := .absent }
  , { walsCode := "grw", iso := "kal", value := .absent }
  , { walsCode := "gua", iso := "gug", value := .present }
  , { walsCode := "guj", iso := "guj", value := .absent }
  , { walsCode := "gum", iso := "kgs", value := .absent }
  , { walsCode := "gwa", iso := "gbr", value := .absent }
  , { walsCode := "hai", iso := "hai", value := .absent }
  , { walsCode := "ham", iso := "hmt", value := .absent }
  , { walsCode := "hau", iso := "hau", value := .absent }
  , { walsCode := "hay", iso := "vay", value := .present }
  , { walsCode := "heb", iso := "heb", value := .absent }
  , { walsCode := "her", iso := "her", value := .absent }
  , { walsCode := "hin", iso := "hin", value := .absent }
  , { walsCode := "hix", iso := "hix", value := .absent }
  , { walsCode := "hmo", iso := "hnj", value := .absent }
  , { walsCode := "hun", iso := "hun", value := .absent }
  , { walsCode := "hzb", iso := "huz", value := .present }
  , { walsCode := "iaa", iso := "iai", value := .absent }
  , { walsCode := "ice", iso := "isl", value := .absent }
  , { walsCode := "ido", iso := "idu", value := .absent }
  , { walsCode := "igb", iso := "ibo", value := .absent }
  , { walsCode := "ijo", iso := "ijc", value := .absent }
  , { walsCode := "ika", iso := "arh", value := .absent }
  , { walsCode := "imo", iso := "imn", value := .absent }
  , { walsCode := "ind", iso := "ind", value := .absent }
  , { walsCode := "ing", iso := "inh", value := .present }
  , { walsCode := "iqu", iso := "iqu", value := .absent }
  , { walsCode := "irq", iso := "irk", value := .absent }
  , { walsCode := "iri", iso := "gle", value := .absent }
  , { walsCode := "jak", iso := "jac", value := .absent }
  , { walsCode := "jpn", iso := "jpn", value := .absent }
  , { walsCode := "jeb", iso := "jeb", value := .present }
  , { walsCode := "juh", iso := "ktz", value := .absent }
  , { walsCode := "kab", iso := "kbd", value := .present }
  , { walsCode := "kmk", iso := "xal", value := .absent }
  , { walsCode := "knd", iso := "kan", value := .absent }
  , { walsCode := "knr", iso := "knc", value := .absent }
  , { walsCode := "krm", iso := "kdr", value := .present }
  , { walsCode := "krk", iso := "kyh", value := .absent }
  , { walsCode := "kas", iso := "kas", value := .absent }
  , { walsCode := "ktz", iso := "bsh", value := .absent }
  , { walsCode := "kyl", iso := "eky", value := .absent }
  , { walsCode := "kay", iso := "gyd", value := .absent }
  , { walsCode := "kaz", iso := "kaz", value := .absent }
  , { walsCode := "ker", iso := "ker", value := .absent }
  , { walsCode := "ket", iso := "ket", value := .absent }
  , { walsCode := "kte", iso := "kcv", value := .absent }
  , { walsCode := "kew", iso := "kew", value := .absent }
  , { walsCode := "khk", iso := "kjh", value := .absent }
  , { walsCode := "kha", iso := "khk", value := .present }
  , { walsCode := "kty", iso := "kca", value := .absent }
  , { walsCode := "khm", iso := "khm", value := .absent }
  , { walsCode := "kmu", iso := "kjg", value := .absent }
  , { walsCode := "klv", iso := "kij", value := .absent }
  , { walsCode := "kim", iso := "kig", value := .absent }
  , { walsCode := "kin", iso := "kin", value := .absent }
  , { walsCode := "kio", iso := "kio", value := .absent }
  , { walsCode := "krb", iso := "gil", value := .absent }
  , { walsCode := "kis", iso := "kss", value := .absent }
  , { walsCode := "kiw", iso := "kjd", value := .absent }
  , { walsCode := "koa", iso := "cku", value := .absent }
  , { walsCode := "kob", iso := "kpw", value := .absent }
  , { walsCode := "kok", iso := "trp", value := .absent }
  , { walsCode := "kon", iso := "kng", value := .absent }
  , { walsCode := "krn", iso := "kqz", value := .absent }
  , { walsCode := "kor", iso := "kor", value := .absent }
  , { walsCode := "kfe", iso := "kfz", value := .absent }
  , { walsCode := "kry", iso := "kpy", value := .absent }
  , { walsCode := "kse", iso := "ses", value := .absent }
  , { walsCode := "kpe", iso := "xpe", value := .absent }
  , { walsCode := "kro", iso := "kgo", value := .absent }
  , { walsCode := "klg", iso := "kle", value := .present }
  , { walsCode := "kuq", iso := "kum", value := .present }
  , { walsCode := "kmp", iso := "kup", value := .absent }
  , { walsCode := "kji", iso := "kmr", value := .absent }
  , { walsCode := "kut", iso := "kut", value := .absent }
  , { walsCode := "kwa", iso := "kwd", value := .absent }
  , { walsCode := "lad", iso := "lbj", value := .present }
  , { walsCode := "lah", iso := "lhu", value := .absent }
  , { walsCode := "lkt", iso := "lkt", value := .absent }
  , { walsCode := "lan", iso := "laj", value := .absent }
  , { walsCode := "lat", iso := "lav", value := .absent }
  , { walsCode := "lav", iso := "lvk", value := .absent }
  , { walsCode := "lep", iso := "lep", value := .absent }
  , { walsCode := "lez", iso := "lez", value := .present }
  , { walsCode := "lim", iso := "lif", value := .present }
  , { walsCode := "lnd", iso := "liy", value := .absent }
  , { walsCode := "lin", iso := "lin", value := .absent }
  , { walsCode := "loz", iso := "loz", value := .absent }
  , { walsCode := "luo", iso := "luo", value := .absent }
  , { walsCode := "luv", iso := "lue", value := .absent }
  , { walsCode := "mab", iso := "mde", value := .absent }
  , { walsCode := "mac", iso := "mbc", value := .absent }
  , { walsCode := "mai", iso := "mai", value := .absent }
  , { walsCode := "mak", iso := "myh", value := .absent }
  , { walsCode := "mal", iso := "plt", value := .absent }
  , { walsCode := "mym", iso := "mal", value := .absent }
  , { walsCode := "mam", iso := "mam", value := .absent }
  , { walsCode := "mnm", iso := "mva", value := .absent }
  , { walsCode := "mnd", iso := "cmn", value := .absent }
  , { walsCode := "mdk", iso := "mnk", value := .absent }
  , { walsCode := "myi", iso := "mpc", value := .absent }
  , { walsCode := "man", iso := "mev", value := .absent }
  , { walsCode := "mao", iso := "mri", value := .absent }
  , { walsCode := "map", iso := "arn", value := .absent }
  , { walsCode := "mku", iso := "zmr", value := .absent }
  , { walsCode := "mme", iso := "mhr", value := .absent }
  , { walsCode := "mar", iso := "mrc", value := .present }
  , { walsCode := "mrd", iso := "mrz", value := .present }
  , { walsCode := "mrt", iso := "vma", value := .absent }
  , { walsCode := "may", iso := "ayz", value := .absent }
  , { walsCode := "mei", iso := "mni", value := .present }
  , { walsCode := "mss", iso := "skd", value := .absent }
  , { walsCode := "mxc", iso := "mig", value := .absent }
  , { walsCode := "mok", iso := "mkj", value := .absent }
  , { walsCode := "mon", iso := "mnw", value := .absent }
  , { walsCode := "mgo", iso := "lol", value := .absent }
  , { walsCode := "mop", iso := "mop", value := .absent }
  , { walsCode := "mro", iso := "mor", value := .absent }
  , { walsCode := "mun", iso := "unr", value := .present }
  , { walsCode := "nma", iso := "nbi", value := .absent }
  , { walsCode := "nht", iso := "nhg", value := .absent }
  , { walsCode := "kho", iso := "naq", value := .absent }
  , { walsCode := "nan", iso := "niq", value := .absent }
  , { walsCode := "nav", iso := "nav", value := .absent }
  , { walsCode := "ndy", iso := "djk", value := .absent }
  , { walsCode := "ntu", iso := "yrk", value := .absent }
  , { walsCode := "nep", iso := "npi", value := .present }
  , { walsCode := "new", iso := "new", value := .absent }
  , { walsCode := "nez", iso := "nez", value := .absent }
  , { walsCode := "ngl", iso := "nig", value := .absent }
  , { walsCode := "nga", iso := "nio", value := .absent }
  , { walsCode := "nti", iso := "niy", value := .absent }
  , { walsCode := "ngi", iso := "wyb", value := .absent }
  , { walsCode := "niu", iso := "niu", value := .absent }
  , { walsCode := "niv", iso := "niv", value := .absent }
  , { walsCode := "nko", iso := "cgg", value := .absent }
  , { walsCode := "nog", iso := "nog", value := .present }
  , { walsCode := "nor", iso := "nor", value := .absent }
  , { walsCode := "nbd", iso := "dgl", value := .absent }
  , { walsCode := "nun", iso := "nut", value := .absent }
  , { walsCode := "nug", iso := "nuy", value := .absent }
  , { walsCode := "obo", iso := "ann", value := .absent }
  , { walsCode := "ond", iso := "one", value := .absent }
  , { walsCode := "ong", iso := "oon", value := .absent }
  , { walsCode := "orh", iso := "hae", value := .absent }
  , { walsCode := "oss", iso := "oss", value := .absent }
  , { walsCode := "otm", iso := "ote", value := .absent }
  , { walsCode := "pms", iso := "pma", value := .absent }
  , { walsCode := "pta", iso := "duf", value := .absent }
  , { walsCode := "pai", iso := "pwn", value := .absent }
  , { walsCode := "pal", iso := "pau", value := .absent }
  , { walsCode := "pnn", iso := "pag", value := .absent }
  , { walsCode := "pan", iso := "pan", value := .absent }
  , { walsCode := "psm", iso := "pqm", value := .absent }
  , { walsCode := "pau", iso := "pad", value := .absent }
  , { walsCode := "prs", iso := "pes", value := .absent }
  , { walsCode := "pip", iso := "ppl", value := .absent }
  , { walsCode := "prh", iso := "myp", value := .absent }
  , { walsCode := "pit", iso := "pjt", value := .absent }
  , { walsCode := "ppi", iso := "pit", value := .absent }
  , { walsCode := "pso", iso := "pom", value := .present }
  , { walsCode := "pur", iso := "tsz", value := .absent }
  , { walsCode := "qim", iso := "qvi", value := .absent }
  , { walsCode := "ram", iso := "rma", value := .absent }
  , { walsCode := "rap", iso := "rap", value := .absent }
  , { walsCode := "rav", iso := "rmn", value := .absent }
  , { walsCode := "rus", iso := "rus", value := .absent }
  , { walsCode := "rut", iso := "rut", value := .present }
  , { walsCode := "stl", iso := "sat", value := .present }
  , { walsCode := "snm", iso := "xsu", value := .absent }
  , { walsCode := "see", iso := "trv", value := .absent }
  , { walsCode := "sel", iso := "ona", value := .absent }
  , { walsCode := "sml", iso := "sza", value := .absent }
  , { walsCode := "snt", iso := "set", value := .absent }
  , { walsCode := "shl", iso := "shk", value := .absent }
  , { walsCode := "shk", iso := "shp", value := .absent }
  , { walsCode := "shn", iso := "sna", value := .absent }
  , { walsCode := "shr", iso := "cjs", value := .absent }
  , { walsCode := "shu", iso := "shs", value := .absent }
  , { walsCode := "sdh", iso := "snd", value := .absent }
  , { walsCode := "sla", iso := "den", value := .absent }
  , { walsCode := "slo", iso := "slv", value := .absent }
  , { walsCode := "som", iso := "som", value := .absent }
  , { walsCode := "snn", iso := "snk", value := .absent }
  , { walsCode := "spa", iso := "spa", value := .absent }
  , { walsCode := "squ", iso := "squ", value := .absent }
  , { walsCode := "sue", iso := "sue", value := .absent }
  , { walsCode := "sup", iso := "spp", value := .absent }
  , { walsCode := "sus", iso := "sus", value := .absent }
  , { walsCode := "swa", iso := "swh", value := .absent }
  , { walsCode := "swe", iso := "swe", value := .absent }
  , { walsCode := "tab", iso := "mky", value := .absent }
  , { walsCode := "tag", iso := "tgl", value := .present }
  , { walsCode := "taz", iso := "tly", value := .present }
  , { walsCode := "tsp", iso := "tam", value := .absent }
  , { walsCode := "tmi", iso := "tat", value := .absent }
  , { walsCode := "tel", iso := "tel", value := .absent }
  , { walsCode := "tha", iso := "tha", value := .absent }
  , { walsCode := "thk", iso := "ths", value := .absent }
  , { walsCode := "tgr", iso := "tig", value := .absent }
  , { walsCode := "tiw", iso := "tiw", value := .absent }
  , { walsCode := "tms", iso := "dto", value := .absent }
  , { walsCode := "txj", iso := "too", value := .absent }
  , { walsCode := "tru", iso := "tpy", value := .absent }
  , { walsCode := "tsa", iso := "tkr", value := .present }
  , { walsCode := "tsz", iso := "ddo", value := .present }
  , { walsCode := "tbu", iso := "", value := .absent }
  , { walsCode := "tuk", iso := "", value := .absent }
  , { walsCode := "tun", iso := "tun", value := .absent }
  , { walsCode := "tur", iso := "tur", value := .absent }
  , { walsCode := "tuv", iso := "tyv", value := .absent }
  , { walsCode := "tzu", iso := "tzj", value := .absent }
  , { walsCode := "udh", iso := "ude", value := .absent }
  , { walsCode := "udm", iso := "udm", value := .absent }
  , { walsCode := "una", iso := "mtg", value := .absent }
  , { walsCode := "urd", iso := "urd", value := .absent }
  , { walsCode := "urk", iso := "urb", value := .absent }
  , { walsCode := "usa", iso := "wnu", value := .absent }
  , { walsCode := "vie", iso := "vie", value := .absent }
  , { walsCode := "wam", iso := "wmb", value := .absent }
  , { walsCode := "wra", iso := "wba", value := .absent }
  , { walsCode := "wrd", iso := "wrr", value := .absent }
  , { walsCode := "wrk", iso := "gae", value := .absent }
  , { walsCode := "war", iso := "pav", value := .absent }
  , { walsCode := "wic", iso := "wic", value := .present }
  , { walsCode := "wch", iso := "mzh", value := .absent }
  , { walsCode := "win", iso := "wnw", value := .present }
  , { walsCode := "yag", iso := "yad", value := .absent }
  , { walsCode := "ykt", iso := "sah", value := .absent }
  , { walsCode := "yaq", iso := "yaq", value := .absent }
  , { walsCode := "yid", iso := "yii", value := .absent }
  , { walsCode := "yim", iso := "yee", value := .absent }
  , { walsCode := "yor", iso := "yor", value := .absent }
  , { walsCode := "yko", iso := "yux", value := .absent }
  , { walsCode := "yur", iso := "yur", value := .absent }
  , { walsCode := "zul", iso := "zul", value := .absent }
  , { walsCode := "zun", iso := "zun", value := .present }
  ]

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F73A
