import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 77A: Semantic Distinctions of Evidentiality
@cite{deandradedehaanValenzuela-2013}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 77A`.

Chapter 77, 418 languages.
-/

namespace Core.WALS.F77A

/-- WALS 77A values. -/
inductive EvidentialityDistinctions where
  /-- No grammatical evidentials (181 languages). -/
  | noGrammaticalEvidentials
  /-- Indirect only (166 languages). -/
  | indirectOnly
  /-- Direct and indirect (71 languages). -/
  | directAndIndirect
  deriving DecidableEq, BEq, Repr

/-- Complete WALS 77A dataset (418 languages). -/
def allData : List (Datapoint EvidentialityDistinctions) :=
  [ { walsCode := "abi", iso := "axb", value := .noGrammaticalEvidentials }
  , { walsCode := "abk", iso := "abk", value := .indirectOnly }
  , { walsCode := "acm", iso := "acv", value := .indirectOnly }
  , { walsCode := "aco", iso := "kjq", value := .directAndIndirect }
  , { walsCode := "afr", iso := "afr", value := .indirectOnly }
  , { walsCode := "agr", iso := "agr", value := .noGrammaticalEvidentials }
  , { walsCode := "ain", iso := "ain", value := .directAndIndirect }
  , { walsCode := "akh", iso := "ahk", value := .directAndIndirect }
  , { walsCode := "abm", iso := "akz", value := .indirectOnly }
  , { walsCode := "ala", iso := "amp", value := .noGrammaticalEvidentials }
  , { walsCode := "alw", iso := "alh", value := .noGrammaticalEvidentials }
  , { walsCode := "alb", iso := "sqi", value := .indirectOnly }
  , { walsCode := "amc", iso := "amc", value := .indirectOnly }
  , { walsCode := "amd", iso := "adx", value := .directAndIndirect }
  , { walsCode := "ame", iso := "aey", value := .noGrammaticalEvidentials }
  , { walsCode := "amu", iso := "ame", value := .indirectOnly }
  , { walsCode := "adk", iso := "ano", value := .directAndIndirect }
  , { walsCode := "agt", iso := "awg", value := .noGrammaticalEvidentials }
  , { walsCode := "apc", iso := "apm", value := .indirectOnly }
  , { walsCode := "apl", iso := "apy", value := .directAndIndirect }
  , { walsCode := "apu", iso := "apu", value := .indirectOnly }
  , { walsCode := "aeg", iso := "arz", value := .noGrammaticalEvidentials }
  , { walsCode := "arg", iso := "afb", value := .indirectOnly }
  , { walsCode := "ana", iso := "aro", value := .indirectOnly }
  , { walsCode := "aho", iso := "arp", value := .indirectOnly }
  , { walsCode := "arp", iso := "ape", value := .noGrammaticalEvidentials }
  , { walsCode := "arc", iso := "aqc", value := .indirectOnly }
  , { walsCode := "akr", iso := "ari", value := .indirectOnly }
  , { walsCode := "arw", iso := "hyw", value := .indirectOnly }
  , { walsCode := "asm", iso := "cns", value := .indirectOnly }
  , { walsCode := "awp", iso := "kwi", value := .noGrammaticalEvidentials }
  , { walsCode := "aym", iso := "ayr", value := .directAndIndirect }
  , { walsCode := "baa", iso := "bbb", value := .noGrammaticalEvidentials }
  , { walsCode := "brs", iso := "bsn", value := .directAndIndirect }
  , { walsCode := "bsq", iso := "eus", value := .indirectOnly }
  , { walsCode := "bkr", iso := "btx", value := .noGrammaticalEvidentials }
  , { walsCode := "baq", iso := "brg", value := .indirectOnly }
  , { walsCode := "baw", iso := "bgr", value := .noGrammaticalEvidentials }
  , { walsCode := "bej", iso := "bej", value := .indirectOnly }
  , { walsCode := "bco", iso := "blc", value := .indirectOnly }
  , { walsCode := "beb", iso := "bef", value := .noGrammaticalEvidentials }
  , { walsCode := "bse", iso := "rif", value := .noGrammaticalEvidentials }
  , { walsCode := "blx", iso := "bll", value := .indirectOnly }
  , { walsCode := "bla", iso := "bla", value := .noGrammaticalEvidentials }
  , { walsCode := "bor", iso := "boa", value := .indirectOnly }
  , { walsCode := "brh", iso := "brh", value := .noGrammaticalEvidentials }
  , { walsCode := "bre", iso := "bre", value := .noGrammaticalEvidentials }
  , { walsCode := "bdk", iso := "bdk", value := .noGrammaticalEvidentials }
  , { walsCode := "bul", iso := "bul", value := .directAndIndirect }
  , { walsCode := "brm", iso := "mya", value := .noGrammaticalEvidentials }
  , { walsCode := "bur", iso := "bsk", value := .noGrammaticalEvidentials }
  , { walsCode := "cah", iso := "chl", value := .indirectOnly }
  , { walsCode := "cax", iso := "", value := .noGrammaticalEvidentials }
  , { walsCode := "can", iso := "cbu", value := .noGrammaticalEvidentials }
  , { walsCode := "cnl", iso := "ram", value := .noGrammaticalEvidentials }
  , { walsCode := "cnt", iso := "yue", value := .indirectOnly }
  , { walsCode := "crp", iso := "cbc", value := .directAndIndirect }
  , { walsCode := "car", iso := "car", value := .directAndIndirect }
  , { walsCode := "cyv", iso := "cyb", value := .noGrammaticalEvidentials }
  , { walsCode := "cha", iso := "cha", value := .indirectOnly }
  , { walsCode := "cco", iso := "tuu", value := .indirectOnly }
  , { walsCode := "cso", iso := "ctp", value := .noGrammaticalEvidentials }
  , { walsCode := "chc", iso := "che", value := .directAndIndirect }
  , { walsCode := "chl", iso := "cjh", value := .indirectOnly }
  , { walsCode := "cmh", iso := "ute", value := .noGrammaticalEvidentials }
  , { walsCode := "che", iso := "chr", value := .indirectOnly }
  , { walsCode := "cjo", iso := "pei", value := .noGrammaticalEvidentials }
  , { walsCode := "ccm", iso := "cco", value := .indirectOnly }
  , { walsCode := "cle", iso := "cle", value := .noGrammaticalEvidentials }
  , { walsCode := "ckl", iso := "chh", value := .noGrammaticalEvidentials }
  , { walsCode := "cku", iso := "wac", value := .indirectOnly }
  , { walsCode := "chp", iso := "chp", value := .indirectOnly }
  , { walsCode := "ctm", iso := "ctm", value := .indirectOnly }
  , { walsCode := "cct", iso := "cho", value := .indirectOnly }
  , { walsCode := "crt", iso := "", value := .noGrammaticalEvidentials }
  , { walsCode := "chr", iso := "crw", value := .noGrammaticalEvidentials }
  , { walsCode := "chk", iso := "ckt", value := .noGrammaticalEvidentials }
  , { walsCode := "cbo", iso := "cao", value := .indirectOnly }
  , { walsCode := "coc", iso := "cod", value := .indirectOnly }
  , { walsCode := "coe", iso := "crd", value := .indirectOnly }
  , { walsCode := "cmn", iso := "com", value := .indirectOnly }
  , { walsCode := "coo", iso := "csz", value := .indirectOnly }
  , { walsCode := "cor", iso := "crn", value := .indirectOnly }
  , { walsCode := "dag", iso := "dgz", value := .noGrammaticalEvidentials }
  , { walsCode := "dni", iso := "dni", value := .indirectOnly }
  , { walsCode := "den", iso := "dny", value := .indirectOnly }
  , { walsCode := "die", iso := "dih", value := .noGrammaticalEvidentials }
  , { walsCode := "dio", iso := "dyo", value := .noGrammaticalEvidentials }
  , { walsCode := "diy", iso := "dif", value := .directAndIndirect }
  , { walsCode := "djp", iso := "dwu", value := .noGrammaticalEvidentials }
  , { walsCode := "dre", iso := "dhv", value := .noGrammaticalEvidentials }
  , { walsCode := "dmi", iso := "dus", value := .indirectOnly }
  , { walsCode := "dut", iso := "nld", value := .indirectOnly }
  , { walsCode := "dyi", iso := "dbl", value := .noGrammaticalEvidentials }
  , { walsCode := "eka", iso := "ekg", value := .indirectOnly }
  , { walsCode := "eng", iso := "eng", value := .noGrammaticalEvidentials }
  , { walsCode := "epe", iso := "sja", value := .indirectOnly }
  , { walsCode := "ese", iso := "ese", value := .indirectOnly }
  , { walsCode := "est", iso := "ekk", value := .indirectOnly }
  , { walsCode := "eve", iso := "evn", value := .directAndIndirect }
  , { walsCode := "ewe", iso := "ewe", value := .noGrammaticalEvidentials }
  , { walsCode := "fas", iso := "faa", value := .directAndIndirect }
  , { walsCode := "fij", iso := "fij", value := .noGrammaticalEvidentials }
  , { walsCode := "fin", iso := "fin", value := .indirectOnly }
  , { walsCode := "for", iso := "for", value := .noGrammaticalEvidentials }
  , { walsCode := "fox", iso := "sac", value := .indirectOnly }
  , { walsCode := "fre", iso := "fra", value := .indirectOnly }
  , { walsCode := "fur", iso := "fvr", value := .noGrammaticalEvidentials }
  , { walsCode := "gag", iso := "gag", value := .directAndIndirect }
  , { walsCode := "gar", iso := "grt", value := .indirectOnly }
  , { walsCode := "grf", iso := "cab", value := .indirectOnly }
  , { walsCode := "geo", iso := "kat", value := .directAndIndirect }
  , { walsCode := "ger", iso := "deu", value := .indirectOnly }
  , { walsCode := "god", iso := "gdo", value := .directAndIndirect }
  , { walsCode := "goo", iso := "gni", value := .indirectOnly }
  , { walsCode := "grb", iso := "grj", value := .noGrammaticalEvidentials }
  , { walsCode := "grk", iso := "ell", value := .noGrammaticalEvidentials }
  , { walsCode := "gso", iso := "kal", value := .indirectOnly }
  , { walsCode := "grw", iso := "kal", value := .indirectOnly }
  , { walsCode := "gjj", iso := "gub", value := .indirectOnly }
  , { walsCode := "gua", iso := "gug", value := .indirectOnly }
  , { walsCode := "gum", iso := "kgs", value := .noGrammaticalEvidentials }
  , { walsCode := "gny", iso := "gyy", value := .indirectOnly }
  , { walsCode := "guu", iso := "kky", value := .noGrammaticalEvidentials }
  , { walsCode := "hai", iso := "hai", value := .directAndIndirect }
  , { walsCode := "hlu", iso := "hur", value := .indirectOnly }
  , { walsCode := "ham", iso := "hmt", value := .indirectOnly }
  , { walsCode := "hau", iso := "hau", value := .noGrammaticalEvidentials }
  , { walsCode := "heb", iso := "heb", value := .noGrammaticalEvidentials }
  , { walsCode := "hid", iso := "hid", value := .indirectOnly }
  , { walsCode := "hin", iso := "hin", value := .noGrammaticalEvidentials }
  , { walsCode := "hix", iso := "hix", value := .directAndIndirect }
  , { walsCode := "hmo", iso := "hnj", value := .noGrammaticalEvidentials }
  , { walsCode := "hop", iso := "hop", value := .indirectOnly }
  , { walsCode := "hlp", iso := "yuf", value := .directAndIndirect }
  , { walsCode := "hmi", iso := "hto", value := .noGrammaticalEvidentials }
  , { walsCode := "hun", iso := "hun", value := .noGrammaticalEvidentials }
  , { walsCode := "hzb", iso := "huz", value := .indirectOnly }
  , { walsCode := "hup", iso := "hup", value := .directAndIndirect }
  , { walsCode := "igb", iso := "ibo", value := .noGrammaticalEvidentials }
  , { walsCode := "ign", iso := "ign", value := .noGrammaticalEvidentials }
  , { walsCode := "ika", iso := "arh", value := .directAndIndirect }
  , { walsCode := "imo", iso := "imn", value := .noGrammaticalEvidentials }
  , { walsCode := "ind", iso := "ind", value := .noGrammaticalEvidentials }
  , { walsCode := "ing", iso := "inh", value := .directAndIndirect }
  , { walsCode := "iqu", iso := "iqu", value := .indirectOnly }
  , { walsCode := "irq", iso := "irk", value := .noGrammaticalEvidentials }
  , { walsCode := "iri", iso := "gle", value := .noGrammaticalEvidentials }
  , { walsCode := "ite", iso := "itl", value := .noGrammaticalEvidentials }
  , { walsCode := "ito", iso := "ito", value := .indirectOnly }
  , { walsCode := "itz", iso := "itz", value := .indirectOnly }
  , { walsCode := "jak", iso := "jac", value := .indirectOnly }
  , { walsCode := "jmm", iso := "jaa", value := .directAndIndirect }
  , { walsCode := "jpn", iso := "jpn", value := .indirectOnly }
  , { walsCode := "jaq", iso := "jqr", value := .directAndIndirect }
  , { walsCode := "jem", iso := "tow", value := .indirectOnly }
  , { walsCode := "juh", iso := "ktz", value := .noGrammaticalEvidentials }
  , { walsCode := "kng", iso := "kgp", value := .indirectOnly }
  , { walsCode := "klh", iso := "kls", value := .directAndIndirect }
  , { walsCode := "kls", iso := "fla", value := .noGrammaticalEvidentials }
  , { walsCode := "kmk", iso := "xal", value := .indirectOnly }
  , { walsCode := "kma", iso := "kay", value := .indirectOnly }
  , { walsCode := "knd", iso := "kan", value := .indirectOnly }
  , { walsCode := "knr", iso := "knc", value := .noGrammaticalEvidentials }
  , { walsCode := "kpm", iso := "pam", value := .noGrammaticalEvidentials }
  , { walsCode := "krk", iso := "kyh", value := .indirectOnly }
  , { walsCode := "ksh", iso := "kju", value := .directAndIndirect }
  , { walsCode := "kto", iso := "ktw", value := .directAndIndirect }
  , { walsCode := "kws", iso := "xaw", value := .indirectOnly }
  , { walsCode := "kyl", iso := "eky", value := .directAndIndirect }
  , { walsCode := "kay", iso := "gyd", value := .directAndIndirect }
  , { walsCode := "ker", iso := "ker", value := .noGrammaticalEvidentials }
  , { walsCode := "ket", iso := "ket", value := .noGrammaticalEvidentials }
  , { walsCode := "kew", iso := "kew", value := .directAndIndirect }
  , { walsCode := "khl", iso := "klj", value := .noGrammaticalEvidentials }
  , { walsCode := "kha", iso := "khk", value := .directAndIndirect }
  , { walsCode := "khs", iso := "kha", value := .noGrammaticalEvidentials }
  , { walsCode := "khm", iso := "khm", value := .noGrammaticalEvidentials }
  , { walsCode := "kmu", iso := "kjg", value := .noGrammaticalEvidentials }
  , { walsCode := "khw", iso := "khw", value := .directAndIndirect }
  , { walsCode := "kic", iso := "kic", value := .indirectOnly }
  , { walsCode := "klv", iso := "kij", value := .noGrammaticalEvidentials }
  , { walsCode := "kio", iso := "kio", value := .indirectOnly }
  , { walsCode := "krb", iso := "gil", value := .noGrammaticalEvidentials }
  , { walsCode := "koa", iso := "cku", value := .directAndIndirect }
  , { walsCode := "kob", iso := "kpw", value := .noGrammaticalEvidentials }
  , { walsCode := "kod", iso := "kfa", value := .directAndIndirect }
  , { walsCode := "kol", iso := "kfb", value := .noGrammaticalEvidentials }
  , { walsCode := "kzy", iso := "kpv", value := .directAndIndirect }
  , { walsCode := "kon", iso := "kng", value := .noGrammaticalEvidentials }
  , { walsCode := "kor", iso := "kor", value := .indirectOnly }
  , { walsCode := "kje", iso := "coe", value := .directAndIndirect }
  , { walsCode := "kfe", iso := "kfz", value := .noGrammaticalEvidentials }
  , { walsCode := "kse", iso := "ses", value := .noGrammaticalEvidentials }
  , { walsCode := "kro", iso := "kgo", value := .noGrammaticalEvidentials }
  , { walsCode := "knm", iso := "kun", value := .noGrammaticalEvidentials }
  , { walsCode := "kji", iso := "kmr", value := .directAndIndirect }
  , { walsCode := "kut", iso := "kut", value := .noGrammaticalEvidentials }
  , { walsCode := "kwk", iso := "kwk", value := .indirectOnly }
  , { walsCode := "lad", iso := "lbj", value := .directAndIndirect }
  , { walsCode := "lah", iso := "lhu", value := .indirectOnly }
  , { walsCode := "lak", iso := "lbe", value := .noGrammaticalEvidentials }
  , { walsCode := "lkt", iso := "lkt", value := .indirectOnly }
  , { walsCode := "lan", iso := "laj", value := .noGrammaticalEvidentials }
  , { walsCode := "lat", iso := "lav", value := .indirectOnly }
  , { walsCode := "lav", iso := "lvk", value := .noGrammaticalEvidentials }
  , { walsCode := "laz", iso := "lzz", value := .directAndIndirect }
  , { walsCode := "leg", iso := "lea", value := .directAndIndirect }
  , { walsCode := "lep", iso := "lep", value := .noGrammaticalEvidentials }
  , { walsCode := "lez", iso := "lez", value := .indirectOnly }
  , { walsCode := "lim", iso := "lif", value := .indirectOnly }
  , { walsCode := "lit", iso := "lit", value := .indirectOnly }
  , { walsCode := "kkv", iso := "khl", value := .noGrammaticalEvidentials }
  , { walsCode := "luv", iso := "lue", value := .noGrammaticalEvidentials }
  , { walsCode := "mab", iso := "mde", value := .noGrammaticalEvidentials }
  , { walsCode := "mch", iso := "mcb", value := .noGrammaticalEvidentials }
  , { walsCode := "mac", iso := "mbc", value := .noGrammaticalEvidentials }
  , { walsCode := "mne", iso := "nmu", value := .indirectOnly }
  , { walsCode := "mak", iso := "myh", value := .directAndIndirect }
  , { walsCode := "mal", iso := "plt", value := .noGrammaticalEvidentials }
  , { walsCode := "mam", iso := "mam", value := .indirectOnly }
  , { walsCode := "mdn", iso := "mhq", value := .indirectOnly }
  , { walsCode := "mnd", iso := "cmn", value := .noGrammaticalEvidentials }
  , { walsCode := "myi", iso := "mpc", value := .indirectOnly }
  , { walsCode := "mao", iso := "mri", value := .noGrammaticalEvidentials }
  , { walsCode := "map", iso := "arn", value := .noGrammaticalEvidentials }
  , { walsCode := "mku", iso := "zmr", value := .noGrammaticalEvidentials }
  , { walsCode := "mny", iso := "zmc", value := .noGrammaticalEvidentials }
  , { walsCode := "mar", iso := "mrc", value := .directAndIndirect }
  , { walsCode := "mrd", iso := "mrz", value := .indirectOnly }
  , { walsCode := "mrt", iso := "vma", value := .indirectOnly }
  , { walsCode := "mtl", iso := "mvb", value := .indirectOnly }
  , { walsCode := "mau", iso := "mph", value := .noGrammaticalEvidentials }
  , { walsCode := "may", iso := "ayz", value := .noGrammaticalEvidentials }
  , { walsCode := "mei", iso := "mni", value := .directAndIndirect }
  , { walsCode := "mgl", iso := "xmf", value := .directAndIndirect }
  , { walsCode := "mss", iso := "skd", value := .indirectOnly }
  , { walsCode := "mth", iso := "mxp", value := .indirectOnly }
  , { walsCode := "mxt", iso := "miy", value := .noGrammaticalEvidentials }
  , { walsCode := "mxc", iso := "mig", value := .noGrammaticalEvidentials }
  , { walsCode := "mxz", iso := "miz", value := .noGrammaticalEvidentials }
  , { walsCode := "mja", iso := "mxt", value := .indirectOnly }
  , { walsCode := "mxo", iso := "mie", value := .indirectOnly }
  , { walsCode := "mxs", iso := "mks", value := .indirectOnly }
  , { walsCode := "moh", iso := "moh", value := .indirectOnly }
  , { walsCode := "mtg", iso := "moe", value := .indirectOnly }
  , { walsCode := "mov", iso := "mzp", value := .noGrammaticalEvidentials }
  , { walsCode := "mun", iso := "unr", value := .noGrammaticalEvidentials }
  , { walsCode := "mse", iso := "umu", value := .noGrammaticalEvidentials }
  , { walsCode := "mrl", iso := "mur", value := .noGrammaticalEvidentials }
  , { walsCode := "nhh", iso := "", value := .noGrammaticalEvidentials }
  , { walsCode := "nmi", iso := "nhx", value := .indirectOnly }
  , { walsCode := "nhm", iso := "ncl", value := .indirectOnly }
  , { walsCode := "nmp", iso := "nhm", value := .noGrammaticalEvidentials }
  , { walsCode := "nhn", iso := "ncj", value := .indirectOnly }
  , { walsCode := "nht", iso := "nhg", value := .indirectOnly }
  , { walsCode := "kho", iso := "naq", value := .noGrammaticalEvidentials }
  , { walsCode := "nav", iso := "nav", value := .indirectOnly }
  , { walsCode := "ndy", iso := "djk", value := .noGrammaticalEvidentials }
  , { walsCode := "ntu", iso := "yrk", value := .directAndIndirect }
  , { walsCode := "nep", iso := "npi", value := .indirectOnly }
  , { walsCode := "nev", iso := "pia", value := .indirectOnly }
  , { walsCode := "nwd", iso := "new", value := .indirectOnly }
  , { walsCode := "nez", iso := "nez", value := .noGrammaticalEvidentials }
  , { walsCode := "nti", iso := "niy", value := .noGrammaticalEvidentials }
  , { walsCode := "ngi", iso := "wyb", value := .directAndIndirect }
  , { walsCode := "nsn", iso := "nsz", value := .indirectOnly }
  , { walsCode := "nit", iso := "dtd", value := .indirectOnly }
  , { walsCode := "niv", iso := "niv", value := .indirectOnly }
  , { walsCode := "nko", iso := "cgg", value := .noGrammaticalEvidentials }
  , { walsCode := "nbd", iso := "dgl", value := .noGrammaticalEvidentials }
  , { walsCode := "nug", iso := "nuy", value := .noGrammaticalEvidentials }
  , { walsCode := "nuu", iso := "nuk", value := .indirectOnly }
  , { walsCode := "nya", iso := "nyt", value := .noGrammaticalEvidentials }
  , { walsCode := "ood", iso := "ood", value := .indirectOnly }
  , { walsCode := "oji", iso := "", value := .noGrammaticalEvidentials }
  , { walsCode := "omh", iso := "oma", value := .indirectOnly }
  , { walsCode := "ond", iso := "one", value := .indirectOnly }
  , { walsCode := "orh", iso := "hae", value := .noGrammaticalEvidentials }
  , { walsCode := "otm", iso := "ote", value := .indirectOnly }
  , { walsCode := "pms", iso := "pma", value := .noGrammaticalEvidentials }
  , { walsCode := "pno", iso := "pao", value := .indirectOnly }
  , { walsCode := "put", iso := "ute", value := .indirectOnly }
  , { walsCode := "pai", iso := "pwn", value := .indirectOnly }
  , { walsCode := "plk", iso := "plu", value := .noGrammaticalEvidentials }
  , { walsCode := "prc", iso := "pab", value := .indirectOnly }
  , { walsCode := "psm", iso := "pqm", value := .indirectOnly }
  , { walsCode := "ptw", iso := "pwi", value := .indirectOnly }
  , { walsCode := "pau", iso := "pad", value := .indirectOnly }
  , { walsCode := "pwn", iso := "paw", value := .indirectOnly }
  , { walsCode := "pem", iso := "aoc", value := .noGrammaticalEvidentials }
  , { walsCode := "prs", iso := "pes", value := .directAndIndirect }
  , { walsCode := "pip", iso := "ppl", value := .noGrammaticalEvidentials }
  , { walsCode := "prh", iso := "myp", value := .directAndIndirect }
  , { walsCode := "pir", iso := "pib", value := .indirectOnly }
  , { walsCode := "pit", iso := "pjt", value := .indirectOnly }
  , { walsCode := "ppi", iso := "pit", value := .noGrammaticalEvidentials }
  , { walsCode := "poh", iso := "pon", value := .noGrammaticalEvidentials }
  , { walsCode := "pme", iso := "peb", value := .directAndIndirect }
  , { walsCode := "pmn", iso := "pej", value := .directAndIndirect }
  , { walsCode := "pso", iso := "pom", value := .directAndIndirect }
  , { walsCode := "pot", iso := "pot", value := .indirectOnly }
  , { walsCode := "pum", iso := "pmi", value := .directAndIndirect }
  , { walsCode := "pur", iso := "tsz", value := .indirectOnly }
  , { walsCode := "pae", iso := "pbb", value := .indirectOnly }
  , { walsCode := "qaw", iso := "alc", value := .noGrammaticalEvidentials }
  , { walsCode := "que", iso := "yum", value := .directAndIndirect }
  , { walsCode := "qhu", iso := "qub", value := .directAndIndirect }
  , { walsCode := "qim", iso := "qvi", value := .directAndIndirect }
  , { walsCode := "qui", iso := "qui", value := .indirectOnly }
  , { walsCode := "ram", iso := "rma", value := .noGrammaticalEvidentials }
  , { walsCode := "rap", iso := "rap", value := .noGrammaticalEvidentials }
  , { walsCode := "ret", iso := "tnc", value := .directAndIndirect }
  , { walsCode := "rom", iso := "ron", value := .noGrammaticalEvidentials }
  , { walsCode := "rus", iso := "rus", value := .noGrammaticalEvidentials }
  , { walsCode := "rut", iso := "rut", value := .indirectOnly }
  , { walsCode := "slr", iso := "slr", value := .directAndIndirect }
  , { walsCode := "san", iso := "sag", value := .noGrammaticalEvidentials }
  , { walsCode := "snm", iso := "xsu", value := .directAndIndirect }
  , { walsCode := "src", iso := "srs", value := .indirectOnly }
  , { walsCode := "say", iso := "pos", value := .noGrammaticalEvidentials }
  , { walsCode := "slp", iso := "spl", value := .noGrammaticalEvidentials }
  , { walsCode := "sel", iso := "ona", value := .noGrammaticalEvidentials }
  , { walsCode := "snt", iso := "set", value := .noGrammaticalEvidentials }
  , { walsCode := "srr", iso := "ser", value := .indirectOnly }
  , { walsCode := "she", iso := "xsr", value := .directAndIndirect }
  , { walsCode := "shk", iso := "shp", value := .indirectOnly }
  , { walsCode := "shu", iso := "shs", value := .indirectOnly }
  , { walsCode := "sin", iso := "snn", value := .directAndIndirect }
  , { walsCode := "srn", iso := "srq", value := .indirectOnly }
  , { walsCode := "siu", iso := "sis", value := .noGrammaticalEvidentials }
  , { walsCode := "sla", iso := "den", value := .indirectOnly }
  , { walsCode := "spa", iso := "spa", value := .noGrammaticalEvidentials }
  , { walsCode := "squ", iso := "squ", value := .directAndIndirect }
  , { walsCode := "sre", iso := "kpm", value := .noGrammaticalEvidentials }
  , { walsCode := "sue", iso := "sue", value := .indirectOnly }
  , { walsCode := "sup", iso := "spp", value := .noGrammaticalEvidentials }
  , { walsCode := "swa", iso := "swh", value := .noGrammaticalEvidentials }
  , { walsCode := "swe", iso := "swe", value := .indirectOnly }
  , { walsCode := "sba", iso := "slc", value := .noGrammaticalEvidentials }
  , { walsCode := "tab", iso := "mky", value := .noGrammaticalEvidentials }
  , { walsCode := "tac", iso := "tna", value := .indirectOnly }
  , { walsCode := "tag", iso := "tgl", value := .indirectOnly }
  , { walsCode := "tkl", iso := "tkm", value := .indirectOnly }
  , { walsCode := "tml", iso := "tam", value := .indirectOnly }
  , { walsCode := "twe", iso := "tac", value := .directAndIndirect }
  , { walsCode := "tar", iso := "tae", value := .directAndIndirect }
  , { walsCode := "tsm", iso := "", value := .noGrammaticalEvidentials }
  , { walsCode := "tau", iso := "tya", value := .noGrammaticalEvidentials }
  , { walsCode := "tpn", iso := "ntp", value := .indirectOnly }
  , { walsCode := "trn", iso := "ter", value := .indirectOnly }
  , { walsCode := "tew", iso := "tew", value := .indirectOnly }
  , { walsCode := "trg", iso := "tew", value := .noGrammaticalEvidentials }
  , { walsCode := "tha", iso := "tha", value := .noGrammaticalEvidentials }
  , { walsCode := "thk", iso := "ths", value := .noGrammaticalEvidentials }
  , { walsCode := "til", iso := "til", value := .noGrammaticalEvidentials }
  , { walsCode := "tmc", iso := "tjm", value := .noGrammaticalEvidentials }
  , { walsCode := "twn", iso := "twf", value := .indirectOnly }
  , { walsCode := "tws", iso := "tix", value := .noGrammaticalEvidentials }
  , { walsCode := "tiw", iso := "tiw", value := .noGrammaticalEvidentials }
  , { walsCode := "tlp", iso := "tcf", value := .noGrammaticalEvidentials }
  , { walsCode := "tli", iso := "tli", value := .noGrammaticalEvidentials }
  , { walsCode := "ton", iso := "tqw", value := .indirectOnly }
  , { walsCode := "toq", iso := "mlu", value := .noGrammaticalEvidentials }
  , { walsCode := "txj", iso := "too", value := .noGrammaticalEvidentials }
  , { walsCode := "tru", iso := "tpy", value := .indirectOnly }
  , { walsCode := "tsi", iso := "tsi", value := .indirectOnly }
  , { walsCode := "ttu", iso := "bbl", value := .directAndIndirect }
  , { walsCode := "tuc", iso := "tuo", value := .directAndIndirect }
  , { walsCode := "tuk", iso := "", value := .noGrammaticalEvidentials }
  , { walsCode := "tnb", iso := "tuf", value := .noGrammaticalEvidentials }
  , { walsCode := "tun", iso := "tun", value := .indirectOnly }
  , { walsCode := "tur", iso := "tur", value := .directAndIndirect }
  , { walsCode := "tus", iso := "tus", value := .noGrammaticalEvidentials }
  , { walsCode := "tuy", iso := "tue", value := .directAndIndirect }
  , { walsCode := "tzo", iso := "tzo", value := .indirectOnly }
  , { walsCode := "tzu", iso := "tzj", value := .indirectOnly }
  , { walsCode := "tsh", iso := "par", value := .indirectOnly }
  , { walsCode := "una", iso := "mtg", value := .noGrammaticalEvidentials }
  , { walsCode := "ung", iso := "ung", value := .noGrammaticalEvidentials }
  , { walsCode := "uhi", iso := "urf", value := .noGrammaticalEvidentials }
  , { walsCode := "urk", iso := "urb", value := .indirectOnly }
  , { walsCode := "usa", iso := "wnu", value := .noGrammaticalEvidentials }
  , { walsCode := "vie", iso := "vie", value := .noGrammaticalEvidentials }
  , { walsCode := "wai", iso := "waw", value := .indirectOnly }
  , { walsCode := "wam", iso := "wmb", value := .noGrammaticalEvidentials }
  , { walsCode := "wao", iso := "auc", value := .indirectOnly }
  , { walsCode := "wra", iso := "wba", value := .indirectOnly }
  , { walsCode := "wrd", iso := "wrr", value := .noGrammaticalEvidentials }
  , { walsCode := "wrk", iso := "gae", value := .noGrammaticalEvidentials }
  , { walsCode := "war", iso := "pav", value := .noGrammaticalEvidentials }
  , { walsCode := "wrg", iso := "wgy", value := .noGrammaticalEvidentials }
  , { walsCode := "wat", iso := "wbv", value := .noGrammaticalEvidentials }
  , { walsCode := "wur", iso := "wau", value := .indirectOnly }
  , { walsCode := "way", iso := "oym", value := .indirectOnly }
  , { walsCode := "wyn", iso := "way", value := .noGrammaticalEvidentials }
  , { walsCode := "wic", iso := "wic", value := .indirectOnly }
  , { walsCode := "wch", iso := "mzh", value := .noGrammaticalEvidentials }
  , { walsCode := "win", iso := "wnw", value := .directAndIndirect }
  , { walsCode := "wiy", iso := "wiy", value := .noGrammaticalEvidentials }
  , { walsCode := "wol", iso := "woe", value := .noGrammaticalEvidentials }
  , { walsCode := "yag", iso := "yad", value := .noGrammaticalEvidentials }
  , { walsCode := "ykt", iso := "sah", value := .directAndIndirect }
  , { walsCode := "yam", iso := "yaa", value := .indirectOnly }
  , { walsCode := "yaq", iso := "yaq", value := .indirectOnly }
  , { walsCode := "ywl", iso := "yok", value := .noGrammaticalEvidentials }
  , { walsCode := "yyg", iso := "xya", value := .noGrammaticalEvidentials }
  , { walsCode := "yid", iso := "yii", value := .noGrammaticalEvidentials }
  , { walsCode := "yim", iso := "yee", value := .noGrammaticalEvidentials }
  , { walsCode := "yor", iso := "yor", value := .noGrammaticalEvidentials }
  , { walsCode := "yuc", iso := "yuc", value := .noGrammaticalEvidentials }
  , { walsCode := "yko", iso := "yux", value := .indirectOnly }
  , { walsCode := "yuk", iso := "gcd", value := .noGrammaticalEvidentials }
  , { walsCode := "ypk", iso := "esu", value := .indirectOnly }
  , { walsCode := "yur", iso := "yur", value := .noGrammaticalEvidentials }
  , { walsCode := "zqc", iso := "zoc", value := .indirectOnly }
  , { walsCode := "zul", iso := "zul", value := .noGrammaticalEvidentials }
  , { walsCode := "zun", iso := "zun", value := .noGrammaticalEvidentials }
  ]

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F77A
