import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 90A: Order of Relative Clause and Noun
@cite{dryer-2013-wals}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 90A`.

Chapter 90, 824 languages.
-/

namespace Core.WALS.F90A

/-- WALS 90A values. -/
inductive RelClauseNounOrder where
  /-- Noun-Relative clause (579 languages). -/
  | nounRelativeClause
  /-- Relative clause-Noun (141 languages). -/
  | relativeClauseNoun
  /-- Internally headed (24 languages). -/
  | internallyHeaded
  /-- Correlative (7 languages). -/
  | correlative
  /-- Adjoined (8 languages). -/
  | adjoined
  /-- Doubly headed (1 languages). -/
  | doublyHeaded
  /-- Mixed (64 languages). -/
  | mixed
  deriving DecidableEq, BEq, Repr

private def allData_0 : List (Datapoint RelClauseNounOrder) :=
  [ { walsCode := "xoo", iso := "nmn", value := .nounRelativeClause }
  , { walsCode := "huc", iso := "huc", value := .nounRelativeClause }
  , { walsCode := "aar", iso := "aiw", value := .nounRelativeClause }
  , { walsCode := "abi", iso := "axb", value := .nounRelativeClause }
  , { walsCode := "abk", iso := "abk", value := .relativeClauseNoun }
  , { walsCode := "abv", iso := "abz", value := .nounRelativeClause }
  , { walsCode := "abu", iso := "kgr", value := .nounRelativeClause }
  , { walsCode := "ace", iso := "ace", value := .nounRelativeClause }
  , { walsCode := "acg", iso := "aca", value := .nounRelativeClause }
  , { walsCode := "acn", iso := "acn", value := .relativeClauseNoun }
  , { walsCode := "acl", iso := "ach", value := .nounRelativeClause }
  , { walsCode := "adi", iso := "adj", value := .nounRelativeClause }
  , { walsCode := "adz", iso := "adz", value := .nounRelativeClause }
  , { walsCode := "ain", iso := "ain", value := .relativeClauseNoun }
  , { walsCode := "ajg", iso := "ajg", value := .nounRelativeClause }
  , { walsCode := "akh", iso := "ahk", value := .relativeClauseNoun }
  , { walsCode := "all", iso := "nrz", value := .nounRelativeClause }
  , { walsCode := "ala", iso := "amp", value := .relativeClauseNoun }
  , { walsCode := "alb", iso := "sqi", value := .nounRelativeClause }
  , { walsCode := "aly", iso := "aly", value := .nounRelativeClause }
  , { walsCode := "aml", iso := "omb", value := .nounRelativeClause }
  , { walsCode := "amq", iso := "amk", value := .nounRelativeClause }
  , { walsCode := "amb", iso := "abt", value := .relativeClauseNoun }
  , { walsCode := "amt", iso := "adx", value := .mixed }
  , { walsCode := "ame", iso := "aey", value := .nounRelativeClause }
  , { walsCode := "amh", iso := "amh", value := .relativeClauseNoun }
  , { walsCode := "ami", iso := "ami", value := .relativeClauseNoun }
  , { walsCode := "amo", iso := "amo", value := .nounRelativeClause }
  , { walsCode := "anj", iso := "aty", value := .nounRelativeClause }
  , { walsCode := "agm", iso := "njm", value := .nounRelativeClause }
  , { walsCode := "anc", iso := "anc", value := .nounRelativeClause }
  , { walsCode := "ang", iso := "agg", value := .nounRelativeClause }
  , { walsCode := "anu", iso := "cko", value := .nounRelativeClause }
  , { walsCode := "any", iso := "anu", value := .nounRelativeClause }
  , { walsCode := "ao", iso := "njo", value := .mixed }
  , { walsCode := "apw", iso := "apw", value := .nounRelativeClause }
  , { walsCode := "apt", iso := "apt", value := .relativeClauseNoun }
  , { walsCode := "apu", iso := "apu", value := .nounRelativeClause }
  , { walsCode := "aeg", iso := "arz", value := .nounRelativeClause }
  , { walsCode := "arg", iso := "afb", value := .nounRelativeClause }
  , { walsCode := "arq", iso := "acm", value := .nounRelativeClause }
  , { walsCode := "arj", iso := "afb", value := .nounRelativeClause }
  , { walsCode := "amr", iso := "ary", value := .nounRelativeClause }
  , { walsCode := "asy", iso := "apc", value := .nounRelativeClause }
  , { walsCode := "ana", iso := "aro", value := .nounRelativeClause }
  , { walsCode := "abo", iso := "arv", value := .nounRelativeClause }
  , { walsCode := "arm", iso := "hye", value := .mixed }
  , { walsCode := "arw", iso := "hyw", value := .nounRelativeClause }
  , { walsCode := "alk", iso := "apr", value := .nounRelativeClause }
  , { walsCode := "aro", iso := "aia", value := .nounRelativeClause }
  , { walsCode := "amp", iso := "aer", value := .nounRelativeClause }
  , { walsCode := "awe", iso := "are", value := .nounRelativeClause }
  , { walsCode := "asm", iso := "cns", value := .relativeClauseNoun }
  , { walsCode := "ath", iso := "aph", value := .relativeClauseNoun }
  , { walsCode := "awa", iso := "awb", value := .relativeClauseNoun }
  , { walsCode := "awt", iso := "kmn", value := .relativeClauseNoun }
  , { walsCode := "azi", iso := "azb", value := .mixed }
  , { walsCode := "bbl", iso := "bvx", value := .nounRelativeClause }
  , { walsCode := "bab", iso := "bav", value := .nounRelativeClause }
  , { walsCode := "bfi", iso := "ksf", value := .nounRelativeClause }
  , { walsCode := "bag", iso := "bmi", value := .nounRelativeClause }
  , { walsCode := "bgr", iso := "fuu", value := .nounRelativeClause }
  , { walsCode := "bai", iso := "bca", value := .relativeClauseNoun }
  , { walsCode := "baj", iso := "bdl", value := .nounRelativeClause }
  , { walsCode := "bwc", iso := "bdr", value := .nounRelativeClause }
  , { walsCode := "bka", iso := "bdh", value := .nounRelativeClause }
  , { walsCode := "bku", iso := "bri", value := .nounRelativeClause }
  , { walsCode := "bvi", iso := "", value := .nounRelativeClause }
  , { walsCode := "blt", iso := "bft", value := .relativeClauseNoun }
  , { walsCode := "bam", iso := "bam", value := .correlative }
  , { walsCode := "brl", iso := "loy", value := .relativeClauseNoun }
  , { walsCode := "baa", iso := "bbb", value := .nounRelativeClause }
  , { walsCode := "bbu", iso := "brm", value := .nounRelativeClause }
  , { walsCode := "brs", iso := "bsn", value := .nounRelativeClause }
  , { walsCode := "bar", iso := "bfa", value := .nounRelativeClause }
  , { walsCode := "brp", iso := "bpe", value := .nounRelativeClause }
  , { walsCode := "bsr", iso := "bsc", value := .nounRelativeClause }
  , { walsCode := "bsk", iso := "bak", value := .relativeClauseNoun }
  , { walsCode := "bsq", iso := "eus", value := .relativeClauseNoun }
  , { walsCode := "bkr", iso := "btx", value := .nounRelativeClause }
  , { walsCode := "bto", iso := "bbc", value := .nounRelativeClause }
  , { walsCode := "baq", iso := "brg", value := .nounRelativeClause }
  , { walsCode := "baw", iso := "bgr", value := .mixed }
  , { walsCode := "bej", iso := "bej", value := .nounRelativeClause }
  , { walsCode := "bel", iso := "byw", value := .relativeClauseNoun }
  , { walsCode := "bco", iso := "blc", value := .nounRelativeClause }
  , { walsCode := "blr", iso := "bel", value := .nounRelativeClause }
  , { walsCode := "bfg", iso := "grr", value := .nounRelativeClause }
  , { walsCode := "bma", iso := "tzm", value := .nounRelativeClause }
  , { walsCode := "brf", iso := "rif", value := .nounRelativeClause }
  , { walsCode := "zag", iso := "zag", value := .nounRelativeClause }
  , { walsCode := "ber", iso := "wti", value := .nounRelativeClause }
  , { walsCode := "bik", iso := "bhw", value := .nounRelativeClause }
  , { walsCode := "bid", iso := "bid", value := .nounRelativeClause }
  , { walsCode := "bil", iso := "blb", value := .mixed }
  , { walsCode := "bmb", iso := "bim", value := .nounRelativeClause }
  , { walsCode := "bni", iso := "bin", value := .nounRelativeClause }
  , { walsCode := "bii", iso := "bzr", value := .nounRelativeClause }
  , { walsCode := "bir", iso := "bom", value := .nounRelativeClause }
  , { walsCode := "bla", iso := "bla", value := .mixed }
  , { walsCode := "bob", iso := "bni", value := .nounRelativeClause }
  , { walsCode := "bod", iso := "brx", value := .relativeClauseNoun }
  , { walsCode := "bok", iso := "bqc", value := .nounRelativeClause }
  , { walsCode := "btk", iso := "lbk", value := .nounRelativeClause }
  , { walsCode := "brh", iso := "brh", value := .nounRelativeClause }
  , { walsCode := "bre", iso := "bre", value := .nounRelativeClause }
  , { walsCode := "bud", iso := "bdm", value := .nounRelativeClause }
  , { walsCode := "bug", iso := "bug", value := .nounRelativeClause }
  , { walsCode := "bul", iso := "bul", value := .nounRelativeClause }
  , { walsCode := "bum", iso := "tkw", value := .nounRelativeClause }
  , { walsCode := "brm", iso := "mya", value := .relativeClauseNoun }
  , { walsCode := "buu", iso := "mhs", value := .nounRelativeClause }
  , { walsCode := "brn", iso := "bds", value := .nounRelativeClause }
  , { walsCode := "bur", iso := "bsk", value := .relativeClauseNoun }
  , { walsCode := "bus", iso := "bqp", value := .nounRelativeClause }
  , { walsCode := "bsh", iso := "buf", value := .nounRelativeClause }
  , { walsCode := "bya", iso := "bee", value := .mixed }
  , { walsCode := "cah", iso := "chl", value := .nounRelativeClause }
  , { walsCode := "cak", iso := "cak", value := .nounRelativeClause }
  , { walsCode := "cml", iso := "rab", value := .relativeClauseNoun }
  , { walsCode := "cax", iso := "", value := .nounRelativeClause }
  , { walsCode := "cnm", iso := "knm", value := .nounRelativeClause }
  , { walsCode := "cnl", iso := "ram", value := .mixed }
  , { walsCode := "cnt", iso := "yue", value := .relativeClauseNoun }
  , { walsCode := "cde", iso := "mch", value := .nounRelativeClause }
  , { walsCode := "ctl", iso := "cat", value := .nounRelativeClause }
  , { walsCode := "cav", iso := "cav", value := .nounRelativeClause }
  , { walsCode := "ceb", iso := "ceb", value := .nounRelativeClause }
  , { walsCode := "chh", iso := "sgw", value := .relativeClauseNoun }
  , { walsCode := "cld", iso := "cld", value := .nounRelativeClause }
  , { walsCode := "chw", iso := "cja", value := .nounRelativeClause }
  , { walsCode := "cha", iso := "cha", value := .nounRelativeClause }
  , { walsCode := "chg", iso := "nbc", value := .mixed }
  , { walsCode := "chn", iso := "chx", value := .relativeClauseNoun }
  , { walsCode := "cso", iso := "ctp", value := .nounRelativeClause }
  , { walsCode := "cya", iso := "ctp", value := .nounRelativeClause }
  , { walsCode := "chc", iso := "che", value := .relativeClauseNoun }
  , { walsCode := "cmh", iso := "ute", value := .nounRelativeClause }
  , { walsCode := "cpn", iso := "cdm", value := .relativeClauseNoun }
  , { walsCode := "che", iso := "chr", value := .relativeClauseNoun }
  , { walsCode := "cic", iso := "nya", value := .nounRelativeClause }
  , { walsCode := "chi", iso := "cid", value := .internallyHeaded }
  , { walsCode := "cmr", iso := "mrh", value := .internallyHeaded }
  , { walsCode := "chs", iso := "csy", value := .relativeClauseNoun }
  , { walsCode := "ccm", iso := "cco", value := .nounRelativeClause }
  , { walsCode := "cle", iso := "cle", value := .nounRelativeClause }
  , { walsCode := "cpl", iso := "cpa", value := .nounRelativeClause }
  , { walsCode := "chq", iso := "chq", value := .nounRelativeClause }
  , { walsCode := "cpy", iso := "cap", value := .relativeClauseNoun }
  , { walsCode := "chp", iso := "chp", value := .nounRelativeClause }
  , { walsCode := "ctm", iso := "ctm", value := .nounRelativeClause }
  , { walsCode := "cct", iso := "cho", value := .internallyHeaded }
  , { walsCode := "cmy", iso := "chf", value := .nounRelativeClause }
  , { walsCode := "chr", iso := "crw", value := .nounRelativeClause }
  , { walsCode := "chj", iso := "cac", value := .nounRelativeClause }
  , { walsCode := "chk", iso := "ckt", value := .mixed }
  , { walsCode := "chv", iso := "chv", value := .relativeClauseNoun }
  , { walsCode := "cmn", iso := "com", value := .nounRelativeClause }
  , { walsCode := "coo", iso := "csz", value := .nounRelativeClause }
  , { walsCode := "cop", iso := "cop", value := .nounRelativeClause }
  , { walsCode := "cor", iso := "crn", value := .nounRelativeClause }
  , { walsCode := "crn", iso := "cor", value := .nounRelativeClause }
  , { walsCode := "cub", iso := "cub", value := .nounRelativeClause }
  , { walsCode := "cze", iso := "ces", value := .nounRelativeClause }
  , { walsCode := "cem", iso := "cam", value := .nounRelativeClause }
  , { walsCode := "ddj", iso := "god", value := .nounRelativeClause }
  , { walsCode := "dag", iso := "dgz", value := .nounRelativeClause }
  , { walsCode := "dgr", iso := "dta", value := .relativeClauseNoun }
  , { walsCode := "dan", iso := "dnj", value := .nounRelativeClause }
  , { walsCode := "dni", iso := "dni", value := .nounRelativeClause }
  , { walsCode := "dsh", iso := "dan", value := .nounRelativeClause }
  , { walsCode := "drg", iso := "dar", value := .relativeClauseNoun }
  , { walsCode := "drm", iso := "drd", value := .mixed }
  , { walsCode := "day", iso := "dai", value := .nounRelativeClause }
  , { walsCode := "deg", iso := "deg", value := .nounRelativeClause }
  , { walsCode := "des", iso := "des", value := .nounRelativeClause }
  , { walsCode := "dhm", iso := "dhi", value := .relativeClauseNoun }
  , { walsCode := "dhi", iso := "div", value := .relativeClauseNoun }
  , { walsCode := "did", iso := "did", value := .nounRelativeClause }
  , { walsCode := "die", iso := "dih", value := .internallyHeaded }
  , { walsCode := "dig", iso := "mhu", value := .relativeClauseNoun }
  , { walsCode := "dms", iso := "dis", value := .relativeClauseNoun }
  , { walsCode := "din", iso := "din", value := .nounRelativeClause }
  , { walsCode := "dio", iso := "dyo", value := .nounRelativeClause }
  , { walsCode := "diy", iso := "dif", value := .adjoined }
  , { walsCode := "djm", iso := "djr", value := .nounRelativeClause }
  , { walsCode := "dlm", iso := "kbv", value := .mixed }
  , { walsCode := "dom", iso := "rmt", value := .nounRelativeClause }
  , { walsCode := "dds", iso := "dds", value := .internallyHeaded }
  , { walsCode := "doy", iso := "dow", value := .nounRelativeClause }
  , { walsCode := "dre", iso := "dhv", value := .nounRelativeClause }
  , { walsCode := "duk", iso := "dud", value := .nounRelativeClause }
  , { walsCode := "dut", iso := "nld", value := .nounRelativeClause }
  , { walsCode := "dyi", iso := "dbl", value := .nounRelativeClause }
  , { walsCode := "erk", iso := "erk", value := .nounRelativeClause }
  , { walsCode := "efi", iso := "efi", value := .nounRelativeClause }
  , { walsCode := "eip", iso := "eip", value := .relativeClauseNoun }
  , { walsCode := "emb", iso := "emp", value := .nounRelativeClause }
  , { walsCode := "egn", iso := "enn", value := .nounRelativeClause }
  , { walsCode := "eno", iso := "eno", value := .nounRelativeClause }
  , { walsCode := "eng", iso := "eng", value := .nounRelativeClause }
  , { walsCode := "epe", iso := "sja", value := .internallyHeaded }
  , { walsCode := "err", iso := "erg", value := .nounRelativeClause }
  , { walsCode := "est", iso := "ekk", value := .nounRelativeClause }
  , { walsCode := "eud", iso := "", value := .nounRelativeClause }
  , { walsCode := "evn", iso := "eve", value := .relativeClauseNoun }
  , { walsCode := "eve", iso := "evn", value := .relativeClauseNoun }
  , { walsCode := "ewe", iso := "ewe", value := .nounRelativeClause }
  , { walsCode := "ewo", iso := "ewo", value := .nounRelativeClause }
  , { walsCode := "fij", iso := "fij", value := .nounRelativeClause }
  , { walsCode := "fin", iso := "fin", value := .nounRelativeClause }
  , { walsCode := "fon", iso := "fon", value := .nounRelativeClause }
  , { walsCode := "fre", iso := "fra", value := .nounRelativeClause }
  , { walsCode := "fri", iso := "fry", value := .nounRelativeClause }
  , { walsCode := "fua", iso := "fub", value := .nounRelativeClause }
  , { walsCode := "fur", iso := "fvr", value := .nounRelativeClause }
  , { walsCode := "fut", iso := "fut", value := .nounRelativeClause }
  , { walsCode := "fye", iso := "pym", value := .nounRelativeClause }
  , { walsCode := "gnd", iso := "gqa", value := .nounRelativeClause }
  , { walsCode := "gae", iso := "gla", value := .nounRelativeClause }
  , { walsCode := "gah", iso := "gah", value := .mixed }
  , { walsCode := "gal", iso := "adl", value := .relativeClauseNoun }
  , { walsCode := "gam", iso := "gmv", value := .relativeClauseNoun }
  , { walsCode := "gap", iso := "pwg", value := .nounRelativeClause }
  , { walsCode := "gar", iso := "grt", value := .relativeClauseNoun }
  , { walsCode := "grf", iso := "cab", value := .nounRelativeClause }
  , { walsCode := "gbb", iso := "gbp", value := .nounRelativeClause }
  , { walsCode := "gel", iso := "nlg", value := .nounRelativeClause }
  , { walsCode := "geo", iso := "kat", value := .nounRelativeClause }
  , { walsCode := "ger", iso := "deu", value := .nounRelativeClause }
  , { walsCode := "gim", iso := "bcq", value := .mixed }
  , { walsCode := "god", iso := "gdo", value := .mixed }
  , { walsCode := "gok", iso := "gkn", value := .nounRelativeClause }
  , { walsCode := "grb", iso := "grj", value := .nounRelativeClause }
  , { walsCode := "grk", iso := "ell", value := .nounRelativeClause }
  , { walsCode := "grw", iso := "kal", value := .nounRelativeClause }
  , { walsCode := "ghb", iso := "guh", value := .nounRelativeClause }
  , { walsCode := "gud", iso := "gde", value := .nounRelativeClause }
  , { walsCode := "gul", iso := "kcm", value := .nounRelativeClause }
  , { walsCode := "gmw", iso := "gvs", value := .mixed }
  , { walsCode := "gum", iso := "kgs", value := .nounRelativeClause }
  , { walsCode := "gmz", iso := "guk", value := .nounRelativeClause }
  , { walsCode := "gnb", iso := "wlg", value := .nounRelativeClause }
  , { walsCode := "gur", iso := "", value := .relativeClauseNoun }
  , { walsCode := "gwa", iso := "gbr", value := .nounRelativeClause }
  , { walsCode := "gyc", iso := "jya", value := .relativeClauseNoun }
  , { walsCode := "hai", iso := "hai", value := .internallyHeaded }
  , { walsCode := "hak", iso := "hak", value := .relativeClauseNoun }
  , { walsCode := "hal", iso := "hla", value := .nounRelativeClause }
  , { walsCode := "hhu", iso := "wos", value := .relativeClauseNoun }
  , { walsCode := "han", iso := "hni", value := .relativeClauseNoun }
  , { walsCode := "har", iso := "tmd", value := .mixed }
  , { walsCode := "hat", iso := "had", value := .nounRelativeClause }
  , { walsCode := "hau", iso := "hau", value := .nounRelativeClause }
  , { walsCode := "haw", iso := "haw", value := .nounRelativeClause }
  , { walsCode := "hwr", iso := "hac", value := .nounRelativeClause }
  , { walsCode := "hya", iso := "hay", value := .nounRelativeClause }
  , { walsCode := "hay", iso := "vay", value := .relativeClauseNoun }
  , { walsCode := "hdi", iso := "xed", value := .nounRelativeClause }
  , { walsCode := "heb", iso := "heb", value := .nounRelativeClause }
  , { walsCode := "hei", iso := "hei", value := .nounRelativeClause }
  , { walsCode := "hid", iso := "hid", value := .nounRelativeClause }
  , { walsCode := "hin", iso := "hin", value := .correlative }
  , { walsCode := "hix", iso := "hix", value := .nounRelativeClause }
  , { walsCode := "hmo", iso := "hnj", value := .nounRelativeClause }
  , { walsCode := "ho", iso := "hoc", value := .relativeClauseNoun }
  , { walsCode := "hoa", iso := "hoa", value := .nounRelativeClause }
  , { walsCode := "hol", iso := "hoo", value := .nounRelativeClause }
  , { walsCode := "hua", iso := "ygr", value := .relativeClauseNoun }
  , { walsCode := "htc", iso := "hus", value := .nounRelativeClause }
  , { walsCode := "hve", iso := "huv", value := .nounRelativeClause }
  , { walsCode := "hui", iso := "hch", value := .nounRelativeClause }
  , { walsCode := "hum", iso := "huu", value := .relativeClauseNoun }
  , { walsCode := "hnd", iso := "hke", value := .nounRelativeClause }
  , { walsCode := "hun", iso := "hun", value := .mixed }
  , { walsCode := "hzb", iso := "huz", value := .relativeClauseNoun }
  , { walsCode := "hpd", iso := "jup", value := .relativeClauseNoun }
  , { walsCode := "hup", iso := "hup", value := .nounRelativeClause }
  , { walsCode := "isa", iso := "ksi", value := .nounRelativeClause }
  , { walsCode := "iaa", iso := "iai", value := .nounRelativeClause }
  , { walsCode := "iau", iso := "tmu", value := .nounRelativeClause }
  , { walsCode := "iba", iso := "iba", value := .nounRelativeClause }
  , { walsCode := "ice", iso := "isl", value := .nounRelativeClause }
  , { walsCode := "idn", iso := "viv", value := .nounRelativeClause }
  , { walsCode := "mxe", iso := "mxe", value := .nounRelativeClause }
  , { walsCode := "ifu", iso := "ifb", value := .nounRelativeClause }
  , { walsCode := "igb", iso := "ibo", value := .nounRelativeClause }
  , { walsCode := "ign", iso := "ign", value := .nounRelativeClause }
  , { walsCode := "ijo", iso := "ijc", value := .relativeClauseNoun }
  , { walsCode := "ik", iso := "ikx", value := .nounRelativeClause }
  , { walsCode := "ika", iso := "arh", value := .internallyHeaded }
  , { walsCode := "ila", iso := "ilb", value := .nounRelativeClause }
  , { walsCode := "imo", iso := "imn", value := .mixed }
  , { walsCode := "ind", iso := "ind", value := .nounRelativeClause }
  , { walsCode := "igs", iso := "tbi", value := .nounRelativeClause }
  , { walsCode := "ing", iso := "inh", value := .relativeClauseNoun }
  , { walsCode := "irq", iso := "irk", value := .nounRelativeClause }
  , { walsCode := "iri", iso := "gle", value := .nounRelativeClause }
  , { walsCode := "ita", iso := "ita", value := .nounRelativeClause }
  , { walsCode := "izi", iso := "izz", value := .nounRelativeClause }
  , { walsCode := "jab", iso := "jae", value := .nounRelativeClause }
  , { walsCode := "jak", iso := "jac", value := .nounRelativeClause }
  , { walsCode := "jms", iso := "djm", value := .mixed }
  , { walsCode := "jpn", iso := "jpn", value := .relativeClauseNoun }
  , { walsCode := "jeb", iso := "jeb", value := .nounRelativeClause }
  , { walsCode := "jng", iso := "kac", value := .relativeClauseNoun }
  , { walsCode := "juk", iso := "jbu", value := .nounRelativeClause }
  , { walsCode := "jmo", iso := "bex", value := .nounRelativeClause }
  , { walsCode := "juh", iso := "ktz", value := .nounRelativeClause }
  , { walsCode := "kab", iso := "kbd", value := .relativeClauseNoun }
  , { walsCode := "kbt", iso := "xkp", value := .nounRelativeClause }
  , { walsCode := "kbl", iso := "kab", value := .nounRelativeClause }
  , { walsCode := "kgr", iso := "kki", value := .nounRelativeClause }
  , { walsCode := "krr", iso := "kxa", value := .nounRelativeClause }
  , { walsCode := "kmk", iso := "xal", value := .relativeClauseNoun }
  , { walsCode := "kma", iso := "kay", value := .nounRelativeClause }
  , { walsCode := "kmz", iso := "kms", value := .mixed }
  , { walsCode := "kam", iso := "xbr", value := .nounRelativeClause }
  , { walsCode := "kan", iso := "ogo", value := .nounRelativeClause }
  , { walsCode := "knk", iso := "kna", value := .nounRelativeClause }
  , { walsCode := "knd", iso := "kan", value := .mixed }
  , { walsCode := "knr", iso := "knc", value := .nounRelativeClause }
  , { walsCode := "kyo", iso := "kny", value := .nounRelativeClause }
  , { walsCode := "kpm", iso := "pam", value := .nounRelativeClause }
  , { walsCode := "kar", iso := "kah", value := .nounRelativeClause }
  , { walsCode := "krc", iso := "krc", value := .relativeClauseNoun }
  , { walsCode := "kkp", iso := "kaa", value := .relativeClauseNoun }
  , { walsCode := "kbw", iso := "bwe", value := .nounRelativeClause }
  , { walsCode := "kpw", iso := "kjp", value := .nounRelativeClause }
  , { walsCode := "ksg", iso := "ksw", value := .nounRelativeClause }
  , { walsCode := "kmj", iso := "kdj", value := .nounRelativeClause }
  , { walsCode := "kas", iso := "kas", value := .mixed }
  , { walsCode := "ktc", iso := "xtc", value := .nounRelativeClause }
  , { walsCode := "ktl", iso := "kcr", value := .nounRelativeClause }
  , { walsCode := "kau", iso := "pss", value := .nounRelativeClause }
  , { walsCode := "kws", iso := "xaw", value := .nounRelativeClause }
  , { walsCode := "kyl", iso := "eky", value := .nounRelativeClause }
  , { walsCode := "kay", iso := "gyd", value := .nounRelativeClause }
  , { walsCode := "kel", iso := "sbc", value := .nounRelativeClause }
  , { walsCode := "kem", iso := "ahg", value := .relativeClauseNoun }
  , { walsCode := "ken", iso := "kyq", value := .nounRelativeClause }
  , { walsCode := "ker", iso := "ker", value := .nounRelativeClause }
  , { walsCode := "kte", iso := "kcv", value := .nounRelativeClause }
  , { walsCode := "kew", iso := "kew", value := .mixed }
  , { walsCode := "khl", iso := "klj", value := .nounRelativeClause }
  , { walsCode := "khg", iso := "klr", value := .relativeClauseNoun }
  , { walsCode := "kha", iso := "khk", value := .relativeClauseNoun }
  , { walsCode := "kmh", iso := "kjl", value := .relativeClauseNoun }
  , { walsCode := "khd", iso := "khg", value := .relativeClauseNoun }
  , { walsCode := "knz", iso := "khg", value := .nounRelativeClause }
  , { walsCode := "kty", iso := "kca", value := .relativeClauseNoun }
  , { walsCode := "khr", iso := "khr", value := .mixed }
  , { walsCode := "khs", iso := "kha", value := .nounRelativeClause }
  , { walsCode := "khm", iso := "khm", value := .nounRelativeClause }
  , { walsCode := "khw", iso := "khw", value := .relativeClauseNoun }
  , { walsCode := "kik", iso := "kik", value := .nounRelativeClause }
  , { walsCode := "klv", iso := "kij", value := .nounRelativeClause }
  , { walsCode := "klw", iso := "klb", value := .nounRelativeClause }
  , { walsCode := "kio", iso := "kio", value := .internallyHeaded }
  , { walsCode := "kri", iso := "kzw", value := .nounRelativeClause }
  , { walsCode := "krb", iso := "gil", value := .nounRelativeClause }
  , { walsCode := "kir", iso := "cme", value := .nounRelativeClause }
  , { walsCode := "kis", iso := "kss", value := .nounRelativeClause }
  , { walsCode := "klm", iso := "kla", value := .nounRelativeClause }
  , { walsCode := "koa", iso := "cku", value := .mixed }
  , { walsCode := "kob", iso := "kpw", value := .mixed }
  , { walsCode := "koe", iso := "xwg", value := .nounRelativeClause }
  , { walsCode := "kkt", iso := "kkk", value := .nounRelativeClause }
  , { walsCode := "kol", iso := "kfb", value := .relativeClauseNoun }
  , { walsCode := "klr", iso := "shm", value := .nounRelativeClause }
  , { walsCode := "kmb", iso := "", value := .doublyHeaded }
  , { walsCode := "xbi", iso := "xbi", value := .nounRelativeClause }
  , { walsCode := "kni", iso := "kma", value := .nounRelativeClause }
  , { walsCode := "krn", iso := "kqz", value := .mixed }
  , { walsCode := "kor", iso := "kor", value := .relativeClauseNoun }
  , { walsCode := "kje", iso := "coe", value := .nounRelativeClause }
  , { walsCode := "kku", iso := "kfq", value := .relativeClauseNoun }
  , { walsCode := "kfe", iso := "kfz", value := .nounRelativeClause }
  , { walsCode := "krw", iso := "khe", value := .mixed }
  , { walsCode := "kos", iso := "kos", value := .nounRelativeClause }
  , { walsCode := "koy", iso := "kff", value := .relativeClauseNoun }
  , { walsCode := "kch", iso := "khq", value := .nounRelativeClause }
  , { walsCode := "kse", iso := "ses", value := .nounRelativeClause }
  , { walsCode := "kre", iso := "krs", value := .nounRelativeClause }
  , { walsCode := "kro", iso := "kgo", value := .nounRelativeClause }
  , { walsCode := "knc", iso := "uwa", value := .nounRelativeClause }
  , { walsCode := "kkq", iso := "kui", value := .adjoined }
  , { walsCode := "kya", iso := "gvn", value := .adjoined }
  , { walsCode := "klg", iso := "kle", value := .mixed }
  , { walsCode := "knm", iso := "kun", value := .nounRelativeClause }
  , { walsCode := "kuo", iso := "kto", value := .nounRelativeClause }
  , { walsCode := "krd", iso := "ckb", value := .nounRelativeClause }
  , { walsCode := "kut", iso := "kut", value := .internallyHeaded }
  , { walsCode := "thy", iso := "thd", value := .nounRelativeClause }
  , { walsCode := "kuv", iso := "kxv", value := .relativeClauseNoun }
  , { walsCode := "kwn", iso := "kwn", value := .nounRelativeClause }
  , { walsCode := "kwz", iso := "xwa", value := .nounRelativeClause }
  , { walsCode := "kwo", iso := "kmo", value := .relativeClauseNoun }
  , { walsCode := "kwt", iso := "kwo", value := .relativeClauseNoun }
  , { walsCode := "kgy", iso := "kgy", value := .relativeClauseNoun }
  , { walsCode := "kyq", iso := "nuk", value := .nounRelativeClause }
  , { walsCode := "lab", iso := "lbu", value := .nounRelativeClause }
  , { walsCode := "lah", iso := "lhu", value := .relativeClauseNoun }
  , { walsCode := "lai", iso := "cnh", value := .mixed }
  , { walsCode := "lkt", iso := "lkt", value := .internallyHeaded }
  , { walsCode := "lal", iso := "ywt", value := .mixed }
  , { walsCode := "lmh", iso := "slp", value := .nounRelativeClause }
  , { walsCode := "lmg", iso := "hia", value := .nounRelativeClause }
  , { walsCode := "lmn", iso := "lmn", value := .relativeClauseNoun }
  , { walsCode := "lmu", iso := "lmu", value := .nounRelativeClause }
  , { walsCode := "lmp", iso := "ljp", value := .nounRelativeClause }
  , { walsCode := "lan", iso := "laj", value := .nounRelativeClause }
  , { walsCode := "lao", iso := "lao", value := .nounRelativeClause }
  , { walsCode := "lat", iso := "lav", value := .nounRelativeClause }
  , { walsCode := "lav", iso := "lvk", value := .internallyHeaded }
  , { walsCode := "leg", iso := "lea", value := .nounRelativeClause }
  , { walsCode := "lel", iso := "lln", value := .nounRelativeClause }
  , { walsCode := "len", iso := "tnl", value := .nounRelativeClause }
  , { walsCode := "ldu", iso := "led", value := .mixed }
  , { walsCode := "let", iso := "lti", value := .nounRelativeClause }
  , { walsCode := "lew", iso := "lww", value := .nounRelativeClause }
  , { walsCode := "lez", iso := "lez", value := .relativeClauseNoun }
  , { walsCode := "lim", iso := "lif", value := .relativeClauseNoun }
  , { walsCode := "lnd", iso := "liy", value := .nounRelativeClause }
  , { walsCode := "lis", iso := "lis", value := .relativeClauseNoun }
  , { walsCode := "lit", iso := "lit", value := .nounRelativeClause }
  , { walsCode := "lgt", iso := "log", value := .nounRelativeClause }
  , { walsCode := "ara", iso := "arw", value := .mixed }
  , { walsCode := "lgu", iso := "lgu", value := .nounRelativeClause }
  , { walsCode := "lon", iso := "los", value := .nounRelativeClause }
  , { walsCode := "lda", iso := "lug", value := .nounRelativeClause }
  , { walsCode := "lug", iso := "lgg", value := .nounRelativeClause }
  , { walsCode := "lui", iso := "lui", value := .nounRelativeClause }
  , { walsCode := "lbu", iso := "lun", value := .nounRelativeClause }
  , { walsCode := "luo", iso := "luo", value := .nounRelativeClause }
  , { walsCode := "luv", iso := "lue", value := .nounRelativeClause }
  , { walsCode := "myn", iso := "mhy", value := .nounRelativeClause }
  , { walsCode := "mad", iso := "mhi", value := .nounRelativeClause }
  , { walsCode := "maa", iso := "mas", value := .nounRelativeClause }
  , { walsCode := "mab", iso := "mde", value := .nounRelativeClause }
  , { walsCode := "mac", iso := "mbc", value := .mixed }
  , { walsCode := "mne", iso := "nmu", value := .relativeClauseNoun }
  , { walsCode := "mpr", iso := "", value := .nounRelativeClause }
  , { walsCode := "msn", iso := "mbq", value := .internallyHeaded }
  , { walsCode := "mai", iso := "mai", value := .mixed }
  , { walsCode := "maj", iso := "mpe", value := .nounRelativeClause }
  , { walsCode := "mak", iso := "myh", value := .mixed }
  , { walsCode := "mkj", iso := "mkz", value := .nounRelativeClause }
  , { walsCode := "mal", iso := "plt", value := .nounRelativeClause }
  , { walsCode := "mym", iso := "mal", value := .relativeClauseNoun }
  , { walsCode := "mlu", iso := "mgl", value := .nounRelativeClause }
  , { walsCode := "mlg", iso := "", value := .nounRelativeClause }
  , { walsCode := "mam", iso := "mam", value := .nounRelativeClause }
  , { walsCode := "mmn", iso := "mmn", value := .nounRelativeClause }
  , { walsCode := "mds", iso := "xmm", value := .nounRelativeClause }
  , { walsCode := "mnm", iso := "mva", value := .nounRelativeClause }
  , { walsCode := "nmm", iso := "nmm", value := .relativeClauseNoun }
  , { walsCode := "mnd", iso := "cmn", value := .relativeClauseNoun }
  , { walsCode := "mmb", iso := "mna", value := .nounRelativeClause }
  , { walsCode := "myi", iso := "mpc", value := .nounRelativeClause }
  , { walsCode := "mng", iso := "mqy", value := .nounRelativeClause }
  , { walsCode := "mgg", iso := "mjg", value := .relativeClauseNoun }
  , { walsCode := "mgq", iso := "mge", value := .nounRelativeClause }
  , { walsCode := "maw", iso := "mlq", value := .nounRelativeClause }
  , { walsCode := "mns", iso := "mns", value := .relativeClauseNoun }
  , { walsCode := "mao", iso := "mri", value := .nounRelativeClause }
  , { walsCode := "mhi", iso := "mar", value := .relativeClauseNoun }
  , { walsCode := "mrg", iso := "mrt", value := .nounRelativeClause }
  , { walsCode := "mar", iso := "mrc", value := .mixed }
  , { walsCode := "mrq", iso := "", value := .nounRelativeClause }
  , { walsCode := "mrt", iso := "vma", value := .adjoined }
  , { walsCode := "mru", iso := "mhx", value := .relativeClauseNoun }
  , { walsCode := "mas", iso := "mcn", value := .nounRelativeClause }
  , { walsCode := "msk", iso := "jle", value := .nounRelativeClause }
  , { walsCode := "msl", iso := "mls", value := .nounRelativeClause }
  , { walsCode := "mka", iso := "mxx", value := .correlative }
  , { walsCode := "mau", iso := "mph", value := .nounRelativeClause }
  , { walsCode := "may", iso := "ayz", value := .nounRelativeClause }
  , { walsCode := "myg", iso := "mdm", value := .nounRelativeClause }
  , { walsCode := "mbr", iso := "mpk", value := .nounRelativeClause }
  , { walsCode := "mby", iso := "myb", value := .nounRelativeClause }
  , { walsCode := "mdo", iso := "gmm", value := .nounRelativeClause }
  , { walsCode := "mbm", iso := "mdd", value := .nounRelativeClause }
  , { walsCode := "mee", iso := "mym", value := .nounRelativeClause }
  , { walsCode := "meh", iso := "gdq", value := .nounRelativeClause }
  , { walsCode := "mei", iso := "mni", value := .relativeClauseNoun }
  , { walsCode := "mek", iso := "skf", value := .adjoined }
  , { walsCode := "men", iso := "mez", value := .nounRelativeClause }
  , { walsCode := "mea", iso := "mej", value := .nounRelativeClause }
  , { walsCode := "mpt", iso := "mpt", value := .internallyHeaded }
  , { walsCode := "hna", iso := "hna", value := .nounRelativeClause }
  , { walsCode := "min", iso := "min", value := .nounRelativeClause }
  , { walsCode := "msg", iso := "mrg", value := .relativeClauseNoun }
  , { walsCode := "mco", iso := "mco", value := .nounRelativeClause }
  , { walsCode := "mxc", iso := "mig", value := .nounRelativeClause }
  , { walsCode := "mxo", iso := "mie", value := .nounRelativeClause }
  , { walsCode := "mxp", iso := "mil", value := .nounRelativeClause }
  , { walsCode := "mxy", iso := "mpm", value := .nounRelativeClause }
  , { walsCode := "miy", iso := "mkf", value := .nounRelativeClause }
  , { walsCode := "mcv", iso := "moc", value := .nounRelativeClause }
  ]

private def allData_1 : List (Datapoint RelClauseNounOrder) :=
  [ { walsCode := "mof", iso := "mif", value := .nounRelativeClause }
  , { walsCode := "mok", iso := "mkj", value := .nounRelativeClause }
  , { walsCode := "mga", iso := "ndt", value := .nounRelativeClause }
  , { walsCode := "mgo", iso := "lol", value := .nounRelativeClause }
  , { walsCode := "mno", iso := "mnr", value := .nounRelativeClause }
  , { walsCode := "moa", iso := "mte", value := .nounRelativeClause }
  , { walsCode := "mro", iso := "mor", value := .nounRelativeClause }
  , { walsCode := "mou", iso := "mgd", value := .nounRelativeClause }
  , { walsCode := "mos", iso := "cas", value := .nounRelativeClause }
  , { walsCode := "mot", iso := "siw", value := .nounRelativeClause }
  , { walsCode := "mpu", iso := "akc", value := .nounRelativeClause }
  , { walsCode := "aoj", iso := "aoj", value := .nounRelativeClause }
  , { walsCode := "mum", iso := "mzm", value := .nounRelativeClause }
  , { walsCode := "mna", iso := "mnb", value := .nounRelativeClause }
  , { walsCode := "mdg", iso := "mua", value := .nounRelativeClause }
  , { walsCode := "mud", iso := "mnf", value := .nounRelativeClause }
  , { walsCode := "mun", iso := "unr", value := .relativeClauseNoun }
  , { walsCode := "mup", iso := "sur", value := .nounRelativeClause }
  , { walsCode := "mrl", iso := "mur", value := .nounRelativeClause }
  , { walsCode := "mpa", iso := "mwf", value := .mixed }
  , { walsCode := "mur", iso := "muz", value := .nounRelativeClause }
  , { walsCode := "mgu", iso := "mug", value := .nounRelativeClause }
  , { walsCode := "msm", iso := "msu", value := .nounRelativeClause }
  , { walsCode := "mus", iso := "emi", value := .nounRelativeClause }
  , { walsCode := "mut", iso := "css", value := .nounRelativeClause }
  , { walsCode := "mwo", iso := "mlv", value := .nounRelativeClause }
  , { walsCode := "ndr", iso := "wyy", value := .nounRelativeClause }
  , { walsCode := "nma", iso := "nbi", value := .relativeClauseNoun }
  , { walsCode := "ngt", iso := "nmf", value := .relativeClauseNoun }
  , { walsCode := "nhh", iso := "", value := .nounRelativeClause }
  , { walsCode := "nhm", iso := "ncl", value := .nounRelativeClause }
  , { walsCode := "nhn", iso := "ncj", value := .mixed }
  , { walsCode := "nht", iso := "nhg", value := .nounRelativeClause }
  , { walsCode := "bio", iso := "bio", value := .nounRelativeClause }
  , { walsCode := "nal", iso := "nal", value := .nounRelativeClause }
  , { walsCode := "kho", iso := "naq", value := .relativeClauseNoun }
  , { walsCode := "nam", iso := "nnm", value := .mixed }
  , { walsCode := "nan", iso := "niq", value := .nounRelativeClause }
  , { walsCode := "nrg", iso := "sen", value := .nounRelativeClause }
  , { walsCode := "nph", iso := "npa", value := .relativeClauseNoun }
  , { walsCode := "nar", iso := "nrb", value := .nounRelativeClause }
  , { walsCode := "nat", iso := "ncz", value := .nounRelativeClause }
  , { walsCode := "nav", iso := "nav", value := .internallyHeaded }
  , { walsCode := "ncm", iso := "bud", value := .nounRelativeClause }
  , { walsCode := "ndo", iso := "ndo", value := .nounRelativeClause }
  , { walsCode := "ndt", iso := "ndv", value := .nounRelativeClause }
  , { walsCode := "ndy", iso := "djk", value := .nounRelativeClause }
  , { walsCode := "neh", iso := "nsn", value := .nounRelativeClause }
  , { walsCode := "naj", iso := "aij", value := .nounRelativeClause }
  , { walsCode := "nwd", iso := "new", value := .relativeClauseNoun }
  , { walsCode := "new", iso := "new", value := .relativeClauseNoun }
  , { walsCode := "ney", iso := "ney", value := .nounRelativeClause }
  , { walsCode := "nez", iso := "nez", value := .nounRelativeClause }
  , { walsCode := "ngl", iso := "nig", value := .nounRelativeClause }
  , { walsCode := "ngm", iso := "sba", value := .nounRelativeClause }
  , { walsCode := "ngk", iso := "nam", value := .adjoined }
  , { walsCode := "ngi", iso := "wyb", value := .mixed }
  , { walsCode := "ngz", iso := "ngi", value := .nounRelativeClause }
  , { walsCode := "ngo", iso := "ngo", value := .nounRelativeClause }
  , { walsCode := "nia", iso := "nia", value := .nounRelativeClause }
  , { walsCode := "nif", iso := "num", value := .nounRelativeClause }
  , { walsCode := "niu", iso := "niu", value := .nounRelativeClause }
  , { walsCode := "niv", iso := "niv", value := .relativeClauseNoun }
  , { walsCode := "nkn", iso := "nko", value := .nounRelativeClause }
  , { walsCode := "nko", iso := "cgg", value := .nounRelativeClause }
  , { walsCode := "noc", iso := "njb", value := .relativeClauseNoun }
  , { walsCode := "non", iso := "nhu", value := .nounRelativeClause }
  , { walsCode := "noo", iso := "snf", value := .nounRelativeClause }
  , { walsCode := "nor", iso := "nor", value := .nounRelativeClause }
  , { walsCode := "nua", iso := "nxl", value := .nounRelativeClause }
  , { walsCode := "nbd", iso := "dgl", value := .nounRelativeClause }
  , { walsCode := "nku", iso := "xnz", value := .nounRelativeClause }
  , { walsCode := "nue", iso := "nus", value := .nounRelativeClause }
  , { walsCode := "nun", iso := "nut", value := .nounRelativeClause }
  , { walsCode := "nug", iso := "nuy", value := .nounRelativeClause }
  , { walsCode := "nup", iso := "nup", value := .nounRelativeClause }
  , { walsCode := "nza", iso := "nzk", value := .nounRelativeClause }
  , { walsCode := "ood", iso := "ood", value := .nounRelativeClause }
  , { walsCode := "obo", iso := "ann", value := .nounRelativeClause }
  , { walsCode := "obg", iso := "ogu", value := .nounRelativeClause }
  , { walsCode := "oji", iso := "", value := .nounRelativeClause }
  , { walsCode := "olo", iso := "ong", value := .nounRelativeClause }
  , { walsCode := "ond", iso := "one", value := .internallyHeaded }
  , { walsCode := "oya", iso := "ory", value := .correlative }
  , { walsCode := "orh", iso := "hae", value := .nounRelativeClause }
  , { walsCode := "orw", iso := "ssn", value := .nounRelativeClause }
  , { walsCode := "osa", iso := "osa", value := .internallyHeaded }
  , { walsCode := "otm", iso := "ote", value := .nounRelativeClause }
  , { walsCode := "paa", iso := "pqa", value := .nounRelativeClause }
  , { walsCode := "pms", iso := "pma", value := .nounRelativeClause }
  , { walsCode := "pno", iso := "pao", value := .nounRelativeClause }
  , { walsCode := "pai", iso := "pwn", value := .nounRelativeClause }
  , { walsCode := "pal", iso := "pau", value := .nounRelativeClause }
  , { walsCode := "plg", iso := "pll", value := .nounRelativeClause }
  , { walsCode := "pnx", iso := "kre", value := .nounRelativeClause }
  , { walsCode := "pan", iso := "pan", value := .mixed }
  , { walsCode := "pre", iso := "asa", value := .nounRelativeClause }
  , { walsCode := "psh", iso := "pst", value := .nounRelativeClause }
  , { walsCode := "pat", iso := "ptp", value := .nounRelativeClause }
  , { walsCode := "ptt", iso := "lae", value := .nounRelativeClause }
  , { walsCode := "plh", iso := "plh", value := .nounRelativeClause }
  , { walsCode := "pau", iso := "pad", value := .nounRelativeClause }
  , { walsCode := "per", iso := "pip", value := .nounRelativeClause }
  , { walsCode := "prs", iso := "pes", value := .nounRelativeClause }
  , { walsCode := "pga", iso := "plg", value := .nounRelativeClause }
  , { walsCode := "pba", iso := "pia", value := .nounRelativeClause }
  , { walsCode := "pip", iso := "ppl", value := .nounRelativeClause }
  , { walsCode := "pit", iso := "pjt", value := .mixed }
  , { walsCode := "pod", iso := "pbi", value := .nounRelativeClause }
  , { walsCode := "poh", iso := "pon", value := .nounRelativeClause }
  , { walsCode := "pkt", iso := "pko", value := .nounRelativeClause }
  , { walsCode := "pol", iso := "pol", value := .nounRelativeClause }
  , { walsCode := "psw", iso := "psw", value := .nounRelativeClause }
  , { walsCode := "por", iso := "por", value := .nounRelativeClause }
  , { walsCode := "pul", iso := "puw", value := .nounRelativeClause }
  , { walsCode := "pum", iso := "pmi", value := .relativeClauseNoun }
  , { walsCode := "prk", iso := "prx", value := .relativeClauseNoun }
  , { walsCode := "pur", iso := "tsz", value := .nounRelativeClause }
  , { walsCode := "par", iso := "lkr", value := .nounRelativeClause }
  , { walsCode := "qaf", iso := "aar", value := .relativeClauseNoun }
  , { walsCode := "qia", iso := "", value := .relativeClauseNoun }
  , { walsCode := "qhu", iso := "qub", value := .relativeClauseNoun }
  , { walsCode := "qim", iso := "qvi", value := .relativeClauseNoun }
  , { walsCode := "rag", iso := "lml", value := .nounRelativeClause }
  , { walsCode := "rap", iso := "rap", value := .nounRelativeClause }
  , { walsCode := "raw", iso := "raw", value := .relativeClauseNoun }
  , { walsCode := "res", iso := "rgr", value := .mixed }
  , { walsCode := "ret", iso := "tnc", value := .internallyHeaded }
  , { walsCode := "rwe", iso := "rmw", value := .nounRelativeClause }
  , { walsCode := "rom", iso := "ron", value := .nounRelativeClause }
  , { walsCode := "rsu", iso := "roh", value := .nounRelativeClause }
  , { walsCode := "ron", iso := "cla", value := .nounRelativeClause }
  , { walsCode := "rot", iso := "rtm", value := .nounRelativeClause }
  , { walsCode := "rov", iso := "rug", value := .nounRelativeClause }
  , { walsCode := "ruk", iso := "dru", value := .mixed }
  , { walsCode := "rum", iso := "klq", value := .relativeClauseNoun }
  , { walsCode := "run", iso := "rou", value := .nounRelativeClause }
  , { walsCode := "rny", iso := "nyn", value := .nounRelativeClause }
  , { walsCode := "rus", iso := "rus", value := .nounRelativeClause }
  , { walsCode := "sah", iso := "saj", value := .nounRelativeClause }
  , { walsCode := "sak", iso := "sku", value := .nounRelativeClause }
  , { walsCode := "slb", iso := "sbe", value := .nounRelativeClause }
  , { walsCode := "sle", iso := "ndi", value := .nounRelativeClause }
  , { walsCode := "sam", iso := "smo", value := .nounRelativeClause }
  , { walsCode := "sdw", iso := "sad", value := .nounRelativeClause }
  , { walsCode := "san", iso := "sag", value := .nounRelativeClause }
  , { walsCode := "sgu", iso := "snq", value := .nounRelativeClause }
  , { walsCode := "stl", iso := "sat", value := .mixed }
  , { walsCode := "snm", iso := "xsu", value := .mixed }
  , { walsCode := "src", iso := "srs", value := .nounRelativeClause }
  , { walsCode := "srd", iso := "sro", value := .nounRelativeClause }
  , { walsCode := "sar", iso := "dju", value := .relativeClauseNoun }
  , { walsCode := "svs", iso := "svs", value := .relativeClauseNoun }
  , { walsCode := "sed", iso := "sed", value := .nounRelativeClause }
  , { walsCode := "see", iso := "trv", value := .nounRelativeClause }
  , { walsCode := "sml", iso := "sza", value := .nounRelativeClause }
  , { walsCode := "ser", iso := "sei", value := .internallyHeaded }
  , { walsCode := "ses", iso := "sot", value := .nounRelativeClause }
  , { walsCode := "shb", iso := "sbf", value := .nounRelativeClause }
  , { walsCode := "sht", iso := "shj", value := .nounRelativeClause }
  , { walsCode := "skw", iso := "swv", value := .mixed }
  , { walsCode := "shn", iso := "sna", value := .nounRelativeClause }
  , { walsCode := "sir", iso := "sjr", value := .nounRelativeClause }
  , { walsCode := "sid", iso := "sid", value := .relativeClauseNoun }
  , { walsCode := "skr", iso := "tty", value := .nounRelativeClause }
  , { walsCode := "skk", iso := "sip", value := .relativeClauseNoun }
  , { walsCode := "sng", iso := "snc", value := .relativeClauseNoun }
  , { walsCode := "snh", iso := "sin", value := .nounRelativeClause }
  , { walsCode := "sio", iso := "xsi", value := .nounRelativeClause }
  , { walsCode := "qum", iso := "qum", value := .nounRelativeClause }
  , { walsCode := "sro", iso := "ssd", value := .nounRelativeClause }
  , { walsCode := "sis", iso := "baa", value := .nounRelativeClause }
  , { walsCode := "sla", iso := "den", value := .mixed }
  , { walsCode := "so", iso := "teu", value := .nounRelativeClause }
  , { walsCode := "sob", iso := "sob", value := .nounRelativeClause }
  , { walsCode := "som", iso := "som", value := .nounRelativeClause }
  , { walsCode := "sgb", iso := "mnx", value := .nounRelativeClause }
  , { walsCode := "sea", iso := "tvk", value := .nounRelativeClause }
  , { walsCode := "tou", iso := "wib", value := .internallyHeaded }
  , { walsCode := "spa", iso := "spa", value := .nounRelativeClause }
  , { walsCode := "squ", iso := "squ", value := .mixed }
  , { walsCode := "sre", iso := "kpm", value := .nounRelativeClause }
  , { walsCode := "sud", iso := "tgo", value := .nounRelativeClause }
  , { walsCode := "sul", iso := "sua", value := .nounRelativeClause }
  , { walsCode := "sun", iso := "sun", value := .nounRelativeClause }
  , { walsCode := "sup", iso := "spp", value := .correlative }
  , { walsCode := "swa", iso := "swh", value := .nounRelativeClause }
  , { walsCode := "swt", iso := "ssw", value := .nounRelativeClause }
  , { walsCode := "swe", iso := "swe", value := .nounRelativeClause }
  , { walsCode := "tab", iso := "mky", value := .nounRelativeClause }
  , { walsCode := "tag", iso := "tgl", value := .nounRelativeClause }
  , { walsCode := "tah", iso := "tah", value := .nounRelativeClause }
  , { walsCode := "taf", iso := "sps", value := .nounRelativeClause }
  , { walsCode := "taj", iso := "tgk", value := .nounRelativeClause }
  , { walsCode := "tak", iso := "tbc", value := .nounRelativeClause }
  , { walsCode := "tls", iso := "shm", value := .nounRelativeClause }
  , { walsCode := "tmm", iso := "mla", value := .nounRelativeClause }
  , { walsCode := "tam", iso := "taj", value := .relativeClauseNoun }
  , { walsCode := "tsk", iso := "taq", value := .nounRelativeClause }
  , { walsCode := "tml", iso := "tam", value := .relativeClauseNoun }
  , { walsCode := "tpt", iso := "tpj", value := .nounRelativeClause }
  , { walsCode := "tce", iso := "tar", value := .nounRelativeClause }
  , { walsCode := "twe", iso := "tac", value := .mixed }
  , { walsCode := "tar", iso := "tae", value := .nounRelativeClause }
  , { walsCode := "tat", iso := "txx", value := .nounRelativeClause }
  , { walsCode := "tvo", iso := "tat", value := .relativeClauseNoun }
  , { walsCode := "tau", iso := "tya", value := .mixed }
  , { walsCode := "taw", iso := "tbo", value := .nounRelativeClause }
  , { walsCode := "tbo", iso := "tbl", value := .nounRelativeClause }
  , { walsCode := "tel", iso := "tel", value := .relativeClauseNoun }
  , { walsCode := "tmr", iso := "tea", value := .nounRelativeClause }
  , { walsCode := "tne", iso := "tem", value := .nounRelativeClause }
  , { walsCode := "ten", iso := "tex", value := .nounRelativeClause }
  , { walsCode := "tny", iso := "kza", value := .nounRelativeClause }
  , { walsCode := "teo", iso := "tio", value := .nounRelativeClause }
  , { walsCode := "tee", iso := "tee", value := .nounRelativeClause }
  , { walsCode := "tep", iso := "tpt", value := .nounRelativeClause }
  , { walsCode := "tpn", iso := "ntp", value := .nounRelativeClause }
  , { walsCode := "ter", iso := "ttr", value := .nounRelativeClause }
  , { walsCode := "trb", iso := "tfr", value := .nounRelativeClause }
  , { walsCode := "tes", iso := "teo", value := .nounRelativeClause }
  , { walsCode := "ttn", iso := "tet", value := .nounRelativeClause }
  , { walsCode := "ttd", iso := "tet", value := .nounRelativeClause }
  , { walsCode := "tha", iso := "tha", value := .nounRelativeClause }
  , { walsCode := "thu", iso := "tdh", value := .relativeClauseNoun }
  , { walsCode := "tdr", iso := "bod", value := .mixed }
  , { walsCode := "tmo", iso := "bod", value := .relativeClauseNoun }
  , { walsCode := "tis", iso := "bod", value := .mixed }
  , { walsCode := "tib", iso := "bod", value := .relativeClauseNoun }
  , { walsCode := "tid", iso := "tvo", value := .nounRelativeClause }
  , { walsCode := "tgk", iso := "tgc", value := .nounRelativeClause }
  , { walsCode := "tgr", iso := "tig", value := .relativeClauseNoun }
  , { walsCode := "tja", iso := "dih", value := .internallyHeaded }
  , { walsCode := "tim", iso := "tih", value := .nounRelativeClause }
  , { walsCode := "tin", iso := "cir", value := .nounRelativeClause }
  , { walsCode := "trm", iso := "suq", value := .nounRelativeClause }
  , { walsCode := "tiw", iso := "tiw", value := .nounRelativeClause }
  , { walsCode := "tlp", iso := "tcf", value := .nounRelativeClause }
  , { walsCode := "tli", iso := "tli", value := .relativeClauseNoun }
  , { walsCode := "tbt", iso := "tti", value := .nounRelativeClause }
  , { walsCode := "tke", iso := "tkl", value := .nounRelativeClause }
  , { walsCode := "tla", iso := "ksd", value := .nounRelativeClause }
  , { walsCode := "tno", iso := "tdn", value := .nounRelativeClause }
  , { walsCode := "toz", iso := "toi", value := .nounRelativeClause }
  , { walsCode := "tng", iso := "ton", value := .nounRelativeClause }
  , { walsCode := "txj", iso := "too", value := .nounRelativeClause }
  , { walsCode := "tri", iso := "trc", value := .nounRelativeClause }
  , { walsCode := "tsf", iso := "cof", value := .relativeClauseNoun }
  , { walsCode := "tgl", iso := "tsj", value := .relativeClauseNoun }
  , { walsCode := "tsi", iso := "tsi", value := .nounRelativeClause }
  , { walsCode := "ttu", iso := "bbl", value := .relativeClauseNoun }
  , { walsCode := "tai", iso := "thz", value := .nounRelativeClause }
  , { walsCode := "tbu", iso := "", value := .nounRelativeClause }
  , { walsCode := "tuc", iso := "tuo", value := .relativeClauseNoun }
  , { walsCode := "tgn", iso := "tzn", value := .nounRelativeClause }
  , { walsCode := "tuk", iso := "", value := .mixed }
  , { walsCode := "tnn", iso := "tvu", value := .nounRelativeClause }
  , { walsCode := "tnk", iso := "lcm", value := .nounRelativeClause }
  , { walsCode := "tun", iso := "tun", value := .nounRelativeClause }
  , { walsCode := "tna", iso := "tuv", value := .nounRelativeClause }
  , { walsCode := "tur", iso := "tur", value := .relativeClauseNoun }
  , { walsCode := "tkm", iso := "tuk", value := .relativeClauseNoun }
  , { walsCode := "tvl", iso := "tvl", value := .nounRelativeClause }
  , { walsCode := "tzu", iso := "tzj", value := .nounRelativeClause }
  , { walsCode := "tsh", iso := "par", value := .mixed }
  , { walsCode := "uby", iso := "uby", value := .relativeClauseNoun }
  , { walsCode := "udh", iso := "ude", value := .mixed }
  , { walsCode := "ukr", iso := "ukr", value := .nounRelativeClause }
  , { walsCode := "uld", iso := "udl", value := .nounRelativeClause }
  , { walsCode := "uli", iso := "uli", value := .nounRelativeClause }
  , { walsCode := "una", iso := "mtg", value := .relativeClauseNoun }
  , { walsCode := "ung", iso := "ung", value := .nounRelativeClause }
  , { walsCode := "url", iso := "urk", value := .nounRelativeClause }
  , { walsCode := "urn", iso := "ura", value := .relativeClauseNoun }
  , { walsCode := "urt", iso := "urt", value := .nounRelativeClause }
  , { walsCode := "urd", iso := "urd", value := .correlative }
  , { walsCode := "ute", iso := "ute", value := .nounRelativeClause }
  , { walsCode := "uyg", iso := "uig", value := .relativeClauseNoun }
  , { walsCode := "uzb", iso := "", value := .relativeClauseNoun }
  , { walsCode := "vaf", iso := "vaf", value := .nounRelativeClause }
  , { walsCode := "vai", iso := "vai", value := .correlative }
  , { walsCode := "vie", iso := "vie", value := .nounRelativeClause }
  , { walsCode := "vnm", iso := "vnm", value := .nounRelativeClause }
  , { walsCode := "wah", iso := "", value := .nounRelativeClause }
  , { walsCode := "wak", iso := "wbl", value := .nounRelativeClause }
  , { walsCode := "wal", iso := "van", value := .nounRelativeClause }
  , { walsCode := "wbn", iso := "wms", value := .mixed }
  , { walsCode := "wao", iso := "auc", value := .mixed }
  , { walsCode := "wap", iso := "wao", value := .internallyHeaded }
  , { walsCode := "war", iso := "pav", value := .nounRelativeClause }
  , { walsCode := "wrl", iso := "wbp", value := .adjoined }
  , { walsCode := "wrg", iso := "wgy", value := .mixed }
  , { walsCode := "wel", iso := "cym", value := .nounRelativeClause }
  , { walsCode := "wma", iso := "mqs", value := .nounRelativeClause }
  , { walsCode := "wic", iso := "wic", value := .nounRelativeClause }
  , { walsCode := "wch", iso := "mzh", value := .nounRelativeClause }
  , { walsCode := "wol", iso := "woe", value := .nounRelativeClause }
  , { walsCode := "wlo", iso := "wlo", value := .nounRelativeClause }
  , { walsCode := "wlf", iso := "wol", value := .nounRelativeClause }
  , { walsCode := "xas", iso := "kao", value := .mixed }
  , { walsCode := "xho", iso := "xho", value := .nounRelativeClause }
  , { walsCode := "ygr", iso := "ygr", value := .relativeClauseNoun }
  , { walsCode := "yag", iso := "yad", value := .nounRelativeClause }
  , { walsCode := "ykt", iso := "sah", value := .relativeClauseNoun }
  , { walsCode := "yal", iso := "kkl", value := .relativeClauseNoun }
  , { walsCode := "yap", iso := "yap", value := .nounRelativeClause }
  , { walsCode := "yaq", iso := "yaq", value := .nounRelativeClause }
  , { walsCode := "yar", iso := "yrb", value := .relativeClauseNoun }
  , { walsCode := "yid", iso := "yii", value := .adjoined }
  , { walsCode := "yor", iso := "yor", value := .nounRelativeClause }
  , { walsCode := "yuc", iso := "yuc", value := .nounRelativeClause }
  , { walsCode := "yko", iso := "yux", value := .relativeClauseNoun }
  , { walsCode := "yuk", iso := "gcd", value := .nounRelativeClause }
  , { walsCode := "yul", iso := "yul", value := .nounRelativeClause }
  , { walsCode := "yur", iso := "yur", value := .mixed }
  , { walsCode := "yuw", iso := "kld", value := .internallyHeaded }
  , { walsCode := "zai", iso := "zai", value := .nounRelativeClause }
  , { walsCode := "zzo", iso := "zpq", value := .nounRelativeClause }
  , { walsCode := "zay", iso := "zay", value := .relativeClauseNoun }
  , { walsCode := "zhn", iso := "zgb", value := .nounRelativeClause }
  , { walsCode := "zch", iso := "zoh", value := .nounRelativeClause }
  , { walsCode := "zul", iso := "zul", value := .nounRelativeClause }
  , { walsCode := "rgc", iso := "jya", value := .internallyHeaded }
  , { walsCode := "eme", iso := "eme", value := .nounRelativeClause }
  ]

/-- Complete WALS 90A dataset (824 languages). -/
def allData : List (Datapoint RelClauseNounOrder) := allData_0 ++ allData_1

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F90A
