import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 91A: Order of Degree Word and Adjective
@cite{wals-2013}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 91A`.

Chapter 91, 481 languages.
-/

namespace Core.WALS.F91A

/-- WALS 91A values. -/
inductive OrderOfDegreeWordAndAdjective where
  /-- Degree word-Adjective (227 languages). -/
  | degreeWordAdjective
  /-- Adjective-Degree word (192 languages). -/
  | adjectiveDegreeWord
  /-- No dominant order (62 languages). -/
  | noDominantOrder
  deriving DecidableEq, BEq, Repr

/-- Complete WALS 91A dataset (481 languages). -/
def allData : List (Datapoint OrderOfDegreeWordAndAdjective) :=
  [ { walsCode := "abi", iso := "axb", value := .degreeWordAdjective }
  , { walsCode := "abk", iso := "abk", value := .degreeWordAdjective }
  , { walsCode := "abu", iso := "kgr", value := .adjectiveDegreeWord }
  , { walsCode := "ace", iso := "ace", value := .noDominantOrder }
  , { walsCode := "adg", iso := "adn", value := .noDominantOrder }
  , { walsCode := "adi", iso := "adj", value := .adjectiveDegreeWord }
  , { walsCode := "agc", iso := "agt", value := .noDominantOrder }
  , { walsCode := "akn", iso := "aka", value := .adjectiveDegreeWord }
  , { walsCode := "akh", iso := "ahk", value := .noDominantOrder }
  , { walsCode := "ala", iso := "amp", value := .adjectiveDegreeWord }
  , { walsCode := "alb", iso := "sqi", value := .degreeWordAdjective }
  , { walsCode := "amc", iso := "amc", value := .adjectiveDegreeWord }
  , { walsCode := "amq", iso := "amk", value := .adjectiveDegreeWord }
  , { walsCode := "ame", iso := "aey", value := .adjectiveDegreeWord }
  , { walsCode := "anj", iso := "aty", value := .adjectiveDegreeWord }
  , { walsCode := "agm", iso := "njm", value := .adjectiveDegreeWord }
  , { walsCode := "ao", iso := "njo", value := .degreeWordAdjective }
  , { walsCode := "apw", iso := "apw", value := .degreeWordAdjective }
  , { walsCode := "apl", iso := "apy", value := .adjectiveDegreeWord }
  , { walsCode := "apt", iso := "apt", value := .degreeWordAdjective }
  , { walsCode := "aeg", iso := "arz", value := .adjectiveDegreeWord }
  , { walsCode := "arg", iso := "afb", value := .degreeWordAdjective }
  , { walsCode := "arq", iso := "acm", value := .noDominantOrder }
  , { walsCode := "arj", iso := "afb", value := .degreeWordAdjective }
  , { walsCode := "ams", iso := "arb", value := .adjectiveDegreeWord }
  , { walsCode := "amr", iso := "ary", value := .adjectiveDegreeWord }
  , { walsCode := "asy", iso := "apc", value := .noDominantOrder }
  , { walsCode := "arm", iso := "hye", value := .degreeWordAdjective }
  , { walsCode := "arw", iso := "hyw", value := .degreeWordAdjective }
  , { walsCode := "awe", iso := "are", value := .adjectiveDegreeWord }
  , { walsCode := "asm", iso := "cns", value := .adjectiveDegreeWord }
  , { walsCode := "au", iso := "avt", value := .adjectiveDegreeWord }
  , { walsCode := "ava", iso := "ava", value := .degreeWordAdjective }
  , { walsCode := "awa", iso := "awb", value := .degreeWordAdjective }
  , { walsCode := "awp", iso := "kwi", value := .degreeWordAdjective }
  , { walsCode := "awt", iso := "kmn", value := .adjectiveDegreeWord }
  , { walsCode := "aym", iso := "ayr", value := .degreeWordAdjective }
  , { walsCode := "bab", iso := "bav", value := .degreeWordAdjective }
  , { walsCode := "bfi", iso := "ksf", value := .adjectiveDegreeWord }
  , { walsCode := "bdw", iso := "bdw", value := .adjectiveDegreeWord }
  , { walsCode := "bwc", iso := "bdr", value := .noDominantOrder }
  , { walsCode := "blt", iso := "bft", value := .degreeWordAdjective }
  , { walsCode := "bnn", iso := "bcm", value := .adjectiveDegreeWord }
  , { walsCode := "brp", iso := "bpe", value := .adjectiveDegreeWord }
  , { walsCode := "bry", iso := "byr", value := .adjectiveDegreeWord }
  , { walsCode := "bsk", iso := "bak", value := .degreeWordAdjective }
  , { walsCode := "bsq", iso := "eus", value := .degreeWordAdjective }
  , { walsCode := "bkr", iso := "btx", value := .degreeWordAdjective }
  , { walsCode := "bto", iso := "bbc", value := .degreeWordAdjective }
  , { walsCode := "baw", iso := "bgr", value := .adjectiveDegreeWord }
  , { walsCode := "bid", iso := "bid", value := .adjectiveDegreeWord }
  , { walsCode := "bkl", iso := "bcl", value := .adjectiveDegreeWord }
  , { walsCode := "bil", iso := "blb", value := .degreeWordAdjective }
  , { walsCode := "bmb", iso := "bim", value := .adjectiveDegreeWord }
  , { walsCode := "bbw", iso := "gup", value := .adjectiveDegreeWord }
  , { walsCode := "bod", iso := "brx", value := .noDominantOrder }
  , { walsCode := "boq", iso := "", value := .adjectiveDegreeWord }
  , { walsCode := "bre", iso := "bre", value := .noDominantOrder }
  , { walsCode := "bri", iso := "bzd", value := .noDominantOrder }
  , { walsCode := "bud", iso := "bdm", value := .adjectiveDegreeWord }
  , { walsCode := "bug", iso := "bug", value := .degreeWordAdjective }
  , { walsCode := "bgn", iso := "bgg", value := .degreeWordAdjective }
  , { walsCode := "bul", iso := "bul", value := .degreeWordAdjective }
  , { walsCode := "pnu", iso := "buh", value := .adjectiveDegreeWord }
  , { walsCode := "but", iso := "bxm", value := .degreeWordAdjective }
  , { walsCode := "brm", iso := "mya", value := .degreeWordAdjective }
  , { walsCode := "brn", iso := "bds", value := .adjectiveDegreeWord }
  , { walsCode := "bur", iso := "bsk", value := .degreeWordAdjective }
  , { walsCode := "bsh", iso := "buf", value := .adjectiveDegreeWord }
  , { walsCode := "bya", iso := "bee", value := .degreeWordAdjective }
  , { walsCode := "cnm", iso := "knm", value := .adjectiveDegreeWord }
  , { walsCode := "cnt", iso := "yue", value := .degreeWordAdjective }
  , { walsCode := "car", iso := "car", value := .adjectiveDegreeWord }
  , { walsCode := "cas", iso := "cbr", value := .noDominantOrder }
  , { walsCode := "cyv", iso := "cyb", value := .degreeWordAdjective }
  , { walsCode := "cai", iso := "suq", value := .noDominantOrder }
  , { walsCode := "cld", iso := "cld", value := .adjectiveDegreeWord }
  , { walsCode := "chw", iso := "cja", value := .adjectiveDegreeWord }
  , { walsCode := "cha", iso := "cha", value := .degreeWordAdjective }
  , { walsCode := "cso", iso := "ctp", value := .adjectiveDegreeWord }
  , { walsCode := "chd", iso := "cdn", value := .degreeWordAdjective }
  , { walsCode := "che", iso := "chr", value := .degreeWordAdjective }
  , { walsCode := "cmr", iso := "mrh", value := .adjectiveDegreeWord }
  , { walsCode := "chs", iso := "csy", value := .adjectiveDegreeWord }
  , { walsCode := "ccm", iso := "cco", value := .noDominantOrder }
  , { walsCode := "cle", iso := "cle", value := .degreeWordAdjective }
  , { walsCode := "cpl", iso := "cpa", value := .degreeWordAdjective }
  , { walsCode := "chq", iso := "chq", value := .noDominantOrder }
  , { walsCode := "ctm", iso := "ctm", value := .adjectiveDegreeWord }
  , { walsCode := "cct", iso := "cho", value := .adjectiveDegreeWord }
  , { walsCode := "cln", iso := "cht", value := .degreeWordAdjective }
  , { walsCode := "cmy", iso := "chf", value := .degreeWordAdjective }
  , { walsCode := "chr", iso := "crw", value := .noDominantOrder }
  , { walsCode := "chv", iso := "chv", value := .degreeWordAdjective }
  , { walsCode := "coc", iso := "cod", value := .degreeWordAdjective }
  , { walsCode := "cmn", iso := "com", value := .degreeWordAdjective }
  , { walsCode := "coo", iso := "csz", value := .degreeWordAdjective }
  , { walsCode := "cro", iso := "cro", value := .adjectiveDegreeWord }
  , { walsCode := "cub", iso := "cub", value := .noDominantOrder }
  , { walsCode := "cup", iso := "cup", value := .degreeWordAdjective }
  , { walsCode := "dag", iso := "dgz", value := .adjectiveDegreeWord }
  , { walsCode := "dgb", iso := "dag", value := .adjectiveDegreeWord }
  , { walsCode := "dsh", iso := "dan", value := .degreeWordAdjective }
  , { walsCode := "drm", iso := "drd", value := .degreeWordAdjective }
  , { walsCode := "did", iso := "did", value := .adjectiveDegreeWord }
  , { walsCode := "die", iso := "dih", value := .adjectiveDegreeWord }
  , { walsCode := "dig", iso := "mhu", value := .noDominantOrder }
  , { walsCode := "dim", iso := "dim", value := .degreeWordAdjective }
  , { walsCode := "din", iso := "din", value := .adjectiveDegreeWord }
  , { walsCode := "djm", iso := "djr", value := .adjectiveDegreeWord }
  , { walsCode := "dre", iso := "dhv", value := .adjectiveDegreeWord }
  , { walsCode := "dul", iso := "duu", value := .degreeWordAdjective }
  , { walsCode := "dma", iso := "dma", value := .adjectiveDegreeWord }
  , { walsCode := "eng", iso := "eng", value := .degreeWordAdjective }
  , { walsCode := "ese", iso := "ese", value := .adjectiveDegreeWord }
  , { walsCode := "est", iso := "ekk", value := .degreeWordAdjective }
  , { walsCode := "eve", iso := "evn", value := .degreeWordAdjective }
  , { walsCode := "fij", iso := "fij", value := .noDominantOrder }
  , { walsCode := "fin", iso := "fin", value := .degreeWordAdjective }
  , { walsCode := "pdp", iso := "ppo", value := .degreeWordAdjective }
  , { walsCode := "fre", iso := "fra", value := .degreeWordAdjective }
  , { walsCode := "fua", iso := "fub", value := .adjectiveDegreeWord }
  , { walsCode := "fut", iso := "fut", value := .adjectiveDegreeWord }
  , { walsCode := "gae", iso := "gla", value := .degreeWordAdjective }
  , { walsCode := "ger", iso := "deu", value := .degreeWordAdjective }
  , { walsCode := "gid", iso := "gih", value := .noDominantOrder }
  , { walsCode := "goa", iso := "guc", value := .adjectiveDegreeWord }
  , { walsCode := "gok", iso := "gkn", value := .degreeWordAdjective }
  , { walsCode := "gln", iso := "gvf", value := .adjectiveDegreeWord }
  , { walsCode := "gon", iso := "gno", value := .degreeWordAdjective }
  , { walsCode := "grk", iso := "ell", value := .degreeWordAdjective }
  , { walsCode := "grw", iso := "kal", value := .degreeWordAdjective }
  , { walsCode := "gjj", iso := "gub", value := .adjectiveDegreeWord }
  , { walsCode := "guj", iso := "guj", value := .degreeWordAdjective }
  , { walsCode := "gmw", iso := "gvs", value := .adjectiveDegreeWord }
  , { walsCode := "gur", iso := "", value := .degreeWordAdjective }
  , { walsCode := "guu", iso := "kky", value := .degreeWordAdjective }
  , { walsCode := "gyc", iso := "jya", value := .degreeWordAdjective }
  , { walsCode := "hai", iso := "hai", value := .adjectiveDegreeWord }
  , { walsCode := "hak", iso := "hak", value := .noDominantOrder }
  , { walsCode := "hal", iso := "hla", value := .adjectiveDegreeWord }
  , { walsCode := "hlu", iso := "hur", value := .degreeWordAdjective }
  , { walsCode := "ham", iso := "hmt", value := .degreeWordAdjective }
  , { walsCode := "han", iso := "hni", value := .noDominantOrder }
  , { walsCode := "hau", iso := "hau", value := .adjectiveDegreeWord }
  , { walsCode := "haw", iso := "haw", value := .adjectiveDegreeWord }
  , { walsCode := "hay", iso := "vay", value := .degreeWordAdjective }
  , { walsCode := "heb", iso := "heb", value := .noDominantOrder }
  , { walsCode := "hil", iso := "hil", value := .noDominantOrder }
  , { walsCode := "hin", iso := "hin", value := .degreeWordAdjective }
  , { walsCode := "hix", iso := "hix", value := .adjectiveDegreeWord }
  , { walsCode := "hmo", iso := "hnj", value := .adjectiveDegreeWord }
  , { walsCode := "hoa", iso := "hoa", value := .adjectiveDegreeWord }
  , { walsCode := "hop", iso := "hop", value := .degreeWordAdjective }
  , { walsCode := "htc", iso := "hus", value := .degreeWordAdjective }
  , { walsCode := "hve", iso := "huv", value := .degreeWordAdjective }
  , { walsCode := "hmi", iso := "hto", value := .degreeWordAdjective }
  , { walsCode := "hum", iso := "huu", value := .degreeWordAdjective }
  , { walsCode := "hnd", iso := "hke", value := .adjectiveDegreeWord }
  , { walsCode := "hun", iso := "hun", value := .degreeWordAdjective }
  , { walsCode := "isa", iso := "ksi", value := .adjectiveDegreeWord }
  , { walsCode := "iaa", iso := "iai", value := .adjectiveDegreeWord }
  , { walsCode := "iba", iso := "iba", value := .noDominantOrder }
  , { walsCode := "ice", iso := "isl", value := .degreeWordAdjective }
  , { walsCode := "ika", iso := "arh", value := .degreeWordAdjective }
  , { walsCode := "ilo", iso := "ilo", value := .noDominantOrder }
  , { walsCode := "imo", iso := "imn", value := .noDominantOrder }
  , { walsCode := "ind", iso := "ind", value := .degreeWordAdjective }
  , { walsCode := "iqu", iso := "iqu", value := .degreeWordAdjective }
  , { walsCode := "ita", iso := "ita", value := .degreeWordAdjective }
  , { walsCode := "ite", iso := "itl", value := .degreeWordAdjective }
  , { walsCode := "jad", iso := "jda", value := .adjectiveDegreeWord }
  , { walsCode := "jak", iso := "jac", value := .degreeWordAdjective }
  , { walsCode := "jms", iso := "djm", value := .adjectiveDegreeWord }
  , { walsCode := "jpn", iso := "jpn", value := .degreeWordAdjective }
  , { walsCode := "jaq", iso := "jqr", value := .degreeWordAdjective }
  , { walsCode := "jng", iso := "kac", value := .degreeWordAdjective }
  , { walsCode := "jiv", iso := "jiv", value := .degreeWordAdjective }
  , { walsCode := "jmo", iso := "bex", value := .adjectiveDegreeWord }
  , { walsCode := "kbt", iso := "xkp", value := .degreeWordAdjective }
  , { walsCode := "kgr", iso := "kki", value := .adjectiveDegreeWord }
  , { walsCode := "kng", iso := "kgp", value := .adjectiveDegreeWord }
  , { walsCode := "krr", iso := "kxa", value := .adjectiveDegreeWord }
  , { walsCode := "kmk", iso := "xal", value := .degreeWordAdjective }
  , { walsCode := "kmz", iso := "kms", value := .adjectiveDegreeWord }
  , { walsCode := "xns", iso := "xns", value := .degreeWordAdjective }
  , { walsCode := "knd", iso := "kan", value := .degreeWordAdjective }
  , { walsCode := "knr", iso := "knc", value := .adjectiveDegreeWord }
  , { walsCode := "jva", iso := "kpj", value := .degreeWordAdjective }
  , { walsCode := "kkp", iso := "kaa", value := .degreeWordAdjective }
  , { walsCode := "kbw", iso := "bwe", value := .adjectiveDegreeWord }
  , { walsCode := "ksg", iso := "ksw", value := .adjectiveDegreeWord }
  , { walsCode := "kmj", iso := "kdj", value := .noDominantOrder }
  , { walsCode := "ktu", iso := "", value := .noDominantOrder }
  , { walsCode := "kau", iso := "pss", value := .adjectiveDegreeWord }
  , { walsCode := "kel", iso := "sbc", value := .adjectiveDegreeWord }
  , { walsCode := "ket", iso := "ket", value := .degreeWordAdjective }
  , { walsCode := "khg", iso := "klr", value := .degreeWordAdjective }
  , { walsCode := "kha", iso := "khk", value := .degreeWordAdjective }
  , { walsCode := "kmh", iso := "kjl", value := .degreeWordAdjective }
  , { walsCode := "kty", iso := "kca", value := .degreeWordAdjective }
  , { walsCode := "khs", iso := "kha", value := .adjectiveDegreeWord }
  , { walsCode := "khm", iso := "khm", value := .adjectiveDegreeWord }
  , { walsCode := "kmu", iso := "kjg", value := .noDominantOrder }
  , { walsCode := "khn", iso := "kkh", value := .adjectiveDegreeWord }
  , { walsCode := "knn", iso := "kfk", value := .degreeWordAdjective }
  , { walsCode := "kri", iso := "kzw", value := .adjectiveDegreeWord }
  , { walsCode := "krb", iso := "gil", value := .adjectiveDegreeWord }
  , { walsCode := "kis", iso := "kss", value := .noDominantOrder }
  , { walsCode := "klm", iso := "kla", value := .degreeWordAdjective }
  , { walsCode := "kob", iso := "kpw", value := .adjectiveDegreeWord }
  , { walsCode := "kta", iso := "kqi", value := .adjectiveDegreeWord }
  , { walsCode := "klr", iso := "shm", value := .degreeWordAdjective }
  , { walsCode := "kon", iso := "kng", value := .noDominantOrder }
  , { walsCode := "kor", iso := "kor", value := .degreeWordAdjective }
  , { walsCode := "kos", iso := "kos", value := .degreeWordAdjective }
  , { walsCode := "koy", iso := "kff", value := .degreeWordAdjective }
  , { walsCode := "kch", iso := "khq", value := .adjectiveDegreeWord }
  , { walsCode := "kyn", iso := "koy", value := .degreeWordAdjective }
  , { walsCode := "kre", iso := "krs", value := .adjectiveDegreeWord }
  , { walsCode := "kro", iso := "kgo", value := .noDominantOrder }
  , { walsCode := "knm", iso := "kun", value := .degreeWordAdjective }
  , { walsCode := "kuo", iso := "kto", value := .degreeWordAdjective }
  , { walsCode := "krd", iso := "ckb", value := .degreeWordAdjective }
  , { walsCode := "kut", iso := "kut", value := .degreeWordAdjective }
  , { walsCode := "thy", iso := "thd", value := .noDominantOrder }
  , { walsCode := "kwo", iso := "kmo", value := .adjectiveDegreeWord }
  , { walsCode := "kwt", iso := "kwo", value := .adjectiveDegreeWord }
  , { walsCode := "kyq", iso := "nuk", value := .noDominantOrder }
  , { walsCode := "lah", iso := "lhu", value := .adjectiveDegreeWord }
  , { walsCode := "lai", iso := "cnh", value := .adjectiveDegreeWord }
  , { walsCode := "lkt", iso := "lkt", value := .degreeWordAdjective }
  , { walsCode := "lal", iso := "ywt", value := .adjectiveDegreeWord }
  , { walsCode := "lmh", iso := "slp", value := .noDominantOrder }
  , { walsCode := "lmn", iso := "lmn", value := .degreeWordAdjective }
  , { walsCode := "lmp", iso := "ljp", value := .adjectiveDegreeWord }
  , { walsCode := "lao", iso := "lao", value := .adjectiveDegreeWord }
  , { walsCode := "lat", iso := "lav", value := .degreeWordAdjective }
  , { walsCode := "len", iso := "tnl", value := .adjectiveDegreeWord }
  , { walsCode := "let", iso := "lti", value := .adjectiveDegreeWord }
  , { walsCode := "lez", iso := "lez", value := .degreeWordAdjective }
  , { walsCode := "lim", iso := "lif", value := .degreeWordAdjective }
  , { walsCode := "lis", iso := "lis", value := .degreeWordAdjective }
  , { walsCode := "lit", iso := "lit", value := .degreeWordAdjective }
  , { walsCode := "lon", iso := "los", value := .adjectiveDegreeWord }
  , { walsCode := "lou", iso := "loj", value := .noDominantOrder }
  , { walsCode := "lug", iso := "lgg", value := .adjectiveDegreeWord }
  , { walsCode := "lun", iso := "nst", value := .degreeWordAdjective }
  , { walsCode := "kkv", iso := "khl", value := .adjectiveDegreeWord }
  , { walsCode := "myn", iso := "mhy", value := .noDominantOrder }
  , { walsCode := "mad", iso := "mhi", value := .adjectiveDegreeWord }
  , { walsCode := "maa", iso := "mas", value := .adjectiveDegreeWord }
  , { walsCode := "mab", iso := "mde", value := .degreeWordAdjective }
  , { walsCode := "mac", iso := "mbc", value := .adjectiveDegreeWord }
  , { walsCode := "mdm", iso := "dmd", value := .degreeWordAdjective }
  , { walsCode := "mgi", iso := "mgu", value := .adjectiveDegreeWord }
  , { walsCode := "mak", iso := "myh", value := .degreeWordAdjective }
  , { walsCode := "mkj", iso := "mkz", value := .degreeWordAdjective }
  , { walsCode := "mlk", iso := "mpb", value := .degreeWordAdjective }
  , { walsCode := "mlu", iso := "mgl", value := .adjectiveDegreeWord }
  , { walsCode := "mmn", iso := "mmn", value := .degreeWordAdjective }
  , { walsCode := "mds", iso := "xmm", value := .degreeWordAdjective }
  , { walsCode := "mnm", iso := "mva", value := .adjectiveDegreeWord }
  , { walsCode := "mnc", iso := "mnc", value := .degreeWordAdjective }
  , { walsCode := "mnd", iso := "cmn", value := .degreeWordAdjective }
  , { walsCode := "mng", iso := "mqy", value := .noDominantOrder }
  , { walsCode := "mns", iso := "mns", value := .degreeWordAdjective }
  , { walsCode := "mao", iso := "mri", value := .adjectiveDegreeWord }
  , { walsCode := "map", iso := "arn", value := .degreeWordAdjective }
  , { walsCode := "mku", iso := "zmr", value := .adjectiveDegreeWord }
  , { walsCode := "mhi", iso := "mar", value := .degreeWordAdjective }
  , { walsCode := "mrg", iso := "mrt", value := .adjectiveDegreeWord }
  , { walsCode := "mru", iso := "mhx", value := .degreeWordAdjective }
  , { walsCode := "msl", iso := "mls", value := .degreeWordAdjective }
  , { walsCode := "mau", iso := "mph", value := .adjectiveDegreeWord }
  , { walsCode := "may", iso := "ayz", value := .adjectiveDegreeWord }
  , { walsCode := "mbe", iso := "mdt", value := .adjectiveDegreeWord }
  , { walsCode := "mbi", iso := "baw", value := .degreeWordAdjective }
  , { walsCode := "mee", iso := "mym", value := .adjectiveDegreeWord }
  , { walsCode := "mie", iso := "ium", value := .adjectiveDegreeWord }
  , { walsCode := "min", iso := "min", value := .adjectiveDegreeWord }
  , { walsCode := "msg", iso := "mrg", value := .degreeWordAdjective }
  , { walsCode := "mis", iso := "miq", value := .degreeWordAdjective }
  , { walsCode := "mco", iso := "mco", value := .degreeWordAdjective }
  , { walsCode := "mxc", iso := "mig", value := .noDominantOrder }
  , { walsCode := "mxj", iso := "mio", value := .adjectiveDegreeWord }
  , { walsCode := "mxo", iso := "mie", value := .adjectiveDegreeWord }
  , { walsCode := "mxp", iso := "mil", value := .adjectiveDegreeWord }
  , { walsCode := "miz", iso := "lus", value := .adjectiveDegreeWord }
  , { walsCode := "mok", iso := "mkj", value := .degreeWordAdjective }
  , { walsCode := "mon", iso := "mnw", value := .adjectiveDegreeWord }
  , { walsCode := "moe", iso := "myv", value := .degreeWordAdjective }
  , { walsCode := "mna", iso := "mnb", value := .adjectiveDegreeWord }
  , { walsCode := "mun", iso := "unr", value := .noDominantOrder }
  , { walsCode := "mup", iso := "sur", value := .noDominantOrder }
  , { walsCode := "mpa", iso := "mwf", value := .adjectiveDegreeWord }
  , { walsCode := "msq", iso := "hur", value := .degreeWordAdjective }
  , { walsCode := "nab", iso := "naf", value := .adjectiveDegreeWord }
  , { walsCode := "ngt", iso := "nmf", value := .adjectiveDegreeWord }
  , { walsCode := "nhh", iso := "", value := .degreeWordAdjective }
  , { walsCode := "nhm", iso := "ncl", value := .degreeWordAdjective }
  , { walsCode := "nht", iso := "nhg", value := .degreeWordAdjective }
  , { walsCode := "nak", iso := "nak", value := .adjectiveDegreeWord }
  , { walsCode := "kho", iso := "naq", value := .degreeWordAdjective }
  , { walsCode := "nam", iso := "nnm", value := .adjectiveDegreeWord }
  , { walsCode := "nnc", iso := "ncb", value := .adjectiveDegreeWord }
  , { walsCode := "nnk", iso := "nnk", value := .adjectiveDegreeWord }
  , { walsCode := "nav", iso := "nav", value := .degreeWordAdjective }
  , { walsCode := "ndo", iso := "ndo", value := .adjectiveDegreeWord }
  , { walsCode := "ndy", iso := "djk", value := .noDominantOrder }
  , { walsCode := "nnd", iso := "anh", value := .adjectiveDegreeWord }
  , { walsCode := "nwd", iso := "new", value := .degreeWordAdjective }
  , { walsCode := "new", iso := "new", value := .degreeWordAdjective }
  , { walsCode := "nez", iso := "nez", value := .degreeWordAdjective }
  , { walsCode := "ngd", iso := "nxg", value := .adjectiveDegreeWord }
  , { walsCode := "ngl", iso := "nig", value := .noDominantOrder }
  , { walsCode := "ngm", iso := "sba", value := .adjectiveDegreeWord }
  , { walsCode := "ngz", iso := "ngi", value := .adjectiveDegreeWord }
  , { walsCode := "nbr", iso := "gym", value := .degreeWordAdjective }
  , { walsCode := "nia", iso := "nia", value := .adjectiveDegreeWord }
  , { walsCode := "nca", iso := "caq", value := .adjectiveDegreeWord }
  , { walsCode := "nsg", iso := "ncg", value := .degreeWordAdjective }
  , { walsCode := "niu", iso := "niu", value := .adjectiveDegreeWord }
  , { walsCode := "nkn", iso := "nko", value := .adjectiveDegreeWord }
  , { walsCode := "nko", iso := "cgg", value := .adjectiveDegreeWord }
  , { walsCode := "nor", iso := "nor", value := .degreeWordAdjective }
  , { walsCode := "nbd", iso := "dgl", value := .degreeWordAdjective }
  , { walsCode := "nun", iso := "nut", value := .adjectiveDegreeWord }
  , { walsCode := "nus", iso := "nuf", value := .degreeWordAdjective }
  , { walsCode := "nuu", iso := "nuk", value := .adjectiveDegreeWord }
  , { walsCode := "nyk", iso := "tpq", value := .degreeWordAdjective }
  , { walsCode := "nis", iso := "njz", value := .noDominantOrder }
  , { walsCode := "ood", iso := "ood", value := .degreeWordAdjective }
  , { walsCode := "obo", iso := "ann", value := .adjectiveDegreeWord }
  , { walsCode := "oji", iso := "", value := .degreeWordAdjective }
  , { walsCode := "olo", iso := "ong", value := .adjectiveDegreeWord }
  , { walsCode := "ond", iso := "one", value := .degreeWordAdjective }
  , { walsCode := "oro", iso := "okv", value := .adjectiveDegreeWord }
  , { walsCode := "orh", iso := "hae", value := .degreeWordAdjective }
  , { walsCode := "osa", iso := "osa", value := .degreeWordAdjective }
  , { walsCode := "otm", iso := "ote", value := .degreeWordAdjective }
  , { walsCode := "pkn", iso := "drl", value := .adjectiveDegreeWord }
  , { walsCode := "pal", iso := "pau", value := .degreeWordAdjective }
  , { walsCode := "plg", iso := "pll", value := .adjectiveDegreeWord }
  , { walsCode := "plk", iso := "plu", value := .degreeWordAdjective }
  , { walsCode := "pam", iso := "pmz", value := .degreeWordAdjective }
  , { walsCode := "pan", iso := "pan", value := .degreeWordAdjective }
  , { walsCode := "psh", iso := "pst", value := .degreeWordAdjective }
  , { walsCode := "psm", iso := "pqm", value := .degreeWordAdjective }
  , { walsCode := "ptt", iso := "lae", value := .degreeWordAdjective }
  , { walsCode := "prs", iso := "pes", value := .degreeWordAdjective }
  , { walsCode := "pit", iso := "pjt", value := .adjectiveDegreeWord }
  , { walsCode := "pog", iso := "poy", value := .adjectiveDegreeWord }
  , { walsCode := "poh", iso := "pon", value := .noDominantOrder }
  , { walsCode := "pok", iso := "rwa", value := .adjectiveDegreeWord }
  , { walsCode := "pol", iso := "pol", value := .degreeWordAdjective }
  , { walsCode := "por", iso := "por", value := .degreeWordAdjective }
  , { walsCode := "pul", iso := "puw", value := .degreeWordAdjective }
  , { walsCode := "pum", iso := "pmi", value := .degreeWordAdjective }
  , { walsCode := "pae", iso := "pbb", value := .degreeWordAdjective }
  , { walsCode := "par", iso := "lkr", value := .noDominantOrder }
  , { walsCode := "qia", iso := "", value := .degreeWordAdjective }
  , { walsCode := "qhu", iso := "qub", value := .degreeWordAdjective }
  , { walsCode := "qim", iso := "qvi", value := .degreeWordAdjective }
  , { walsCode := "rji", iso := "rji", value := .noDominantOrder }
  , { walsCode := "ram", iso := "rma", value := .adjectiveDegreeWord }
  , { walsCode := "rpa", iso := "bod", value := .degreeWordAdjective }
  , { walsCode := "raw", iso := "raw", value := .degreeWordAdjective }
  , { walsCode := "rwe", iso := "rmw", value := .noDominantOrder }
  , { walsCode := "rom", iso := "ron", value := .degreeWordAdjective }
  , { walsCode := "rot", iso := "rtm", value := .adjectiveDegreeWord }
  , { walsCode := "ruk", iso := "dru", value := .degreeWordAdjective }
  , { walsCode := "rus", iso := "rus", value := .degreeWordAdjective }
  , { walsCode := "sah", iso := "saj", value := .noDominantOrder }
  , { walsCode := "sal", iso := "sln", value := .adjectiveDegreeWord }
  , { walsCode := "syu", iso := "sll", value := .adjectiveDegreeWord }
  , { walsCode := "sam", iso := "smo", value := .noDominantOrder }
  , { walsCode := "sdw", iso := "sad", value := .degreeWordAdjective }
  , { walsCode := "san", iso := "sag", value := .adjectiveDegreeWord }
  , { walsCode := "snm", iso := "xsu", value := .adjectiveDegreeWord }
  , { walsCode := "srd", iso := "sro", value := .degreeWordAdjective }
  , { walsCode := "svs", iso := "svs", value := .noDominantOrder }
  , { walsCode := "seb", iso := "kpz", value := .adjectiveDegreeWord }
  , { walsCode := "sed", iso := "sed", value := .adjectiveDegreeWord }
  , { walsCode := "slp", iso := "spl", value := .adjectiveDegreeWord }
  , { walsCode := "sem", iso := "nsm", value := .noDominantOrder }
  , { walsCode := "snt", iso := "set", value := .adjectiveDegreeWord }
  , { walsCode := "scr", iso := "hbs", value := .degreeWordAdjective }
  , { walsCode := "sna", iso := "scl", value := .degreeWordAdjective }
  , { walsCode := "shk", iso := "shp", value := .degreeWordAdjective }
  , { walsCode := "skk", iso := "sip", value := .degreeWordAdjective }
  , { walsCode := "sim", iso := "smr", value := .adjectiveDegreeWord }
  , { walsCode := "sng", iso := "snc", value := .adjectiveDegreeWord }
  , { walsCode := "snh", iso := "sin", value := .degreeWordAdjective }
  , { walsCode := "sio", iso := "xsi", value := .noDominantOrder }
  , { walsCode := "srn", iso := "srq", value := .adjectiveDegreeWord }
  , { walsCode := "sro", iso := "ssd", value := .adjectiveDegreeWord }
  , { walsCode := "som", iso := "som", value := .degreeWordAdjective }
  , { walsCode := "son", iso := "sov", value := .adjectiveDegreeWord }
  , { walsCode := "srb", iso := "", value := .degreeWordAdjective }
  , { walsCode := "spa", iso := "spa", value := .degreeWordAdjective }
  , { walsCode := "spi", iso := "spt", value := .degreeWordAdjective }
  , { walsCode := "sre", iso := "kpm", value := .adjectiveDegreeWord }
  , { walsCode := "sul", iso := "sua", value := .adjectiveDegreeWord }
  , { walsCode := "sun", iso := "sun", value := .noDominantOrder }
  , { walsCode := "swe", iso := "swe", value := .degreeWordAdjective }
  , { walsCode := "tab", iso := "mky", value := .noDominantOrder }
  , { walsCode := "tah", iso := "tah", value := .adjectiveDegreeWord }
  , { walsCode := "tak", iso := "tbc", value := .adjectiveDegreeWord }
  , { walsCode := "tls", iso := "shm", value := .degreeWordAdjective }
  , { walsCode := "tml", iso := "tam", value := .degreeWordAdjective }
  , { walsCode := "tce", iso := "tar", value := .degreeWordAdjective }
  , { walsCode := "twe", iso := "tac", value := .degreeWordAdjective }
  , { walsCode := "tar", iso := "tae", value := .adjectiveDegreeWord }
  , { walsCode := "tvo", iso := "tat", value := .degreeWordAdjective }
  , { walsCode := "taw", iso := "tbo", value := .adjectiveDegreeWord }
  , { walsCode := "tbo", iso := "tbl", value := .degreeWordAdjective }
  , { walsCode := "tel", iso := "tel", value := .degreeWordAdjective }
  , { walsCode := "tee", iso := "tee", value := .degreeWordAdjective }
  , { walsCode := "tep", iso := "tpt", value := .degreeWordAdjective }
  , { walsCode := "tpn", iso := "ntp", value := .degreeWordAdjective }
  , { walsCode := "ttn", iso := "tet", value := .adjectiveDegreeWord }
  , { walsCode := "ttd", iso := "tet", value := .adjectiveDegreeWord }
  , { walsCode := "tha", iso := "tha", value := .adjectiveDegreeWord }
  , { walsCode := "tho", iso := "thp", value := .degreeWordAdjective }
  , { walsCode := "tib", iso := "bod", value := .adjectiveDegreeWord }
  , { walsCode := "tid", iso := "tvo", value := .adjectiveDegreeWord }
  , { walsCode := "tgk", iso := "tgc", value := .adjectiveDegreeWord }
  , { walsCode := "tja", iso := "dih", value := .adjectiveDegreeWord }
  , { walsCode := "tim", iso := "tih", value := .adjectiveDegreeWord }
  , { walsCode := "tni", iso := "lbf", value := .degreeWordAdjective }
  , { walsCode := "tin", iso := "cir", value := .degreeWordAdjective }
  , { walsCode := "tlp", iso := "tcf", value := .degreeWordAdjective }
  , { walsCode := "tli", iso := "tli", value := .degreeWordAdjective }
  , { walsCode := "tod", iso := "sbu", value := .degreeWordAdjective }
  , { walsCode := "tla", iso := "ksd", value := .noDominantOrder }
  , { walsCode := "tno", iso := "tdn", value := .degreeWordAdjective }
  , { walsCode := "tng", iso := "ton", value := .noDominantOrder }
  , { walsCode := "txj", iso := "too", value := .degreeWordAdjective }
  , { walsCode := "tgl", iso := "tsj", value := .degreeWordAdjective }
  , { walsCode := "tsi", iso := "tsi", value := .degreeWordAdjective }
  , { walsCode := "tun", iso := "tun", value := .adjectiveDegreeWord }
  , { walsCode := "tur", iso := "tur", value := .degreeWordAdjective }
  , { walsCode := "tvt", iso := "tvt", value := .degreeWordAdjective }
  , { walsCode := "tzu", iso := "tzj", value := .noDominantOrder }
  , { walsCode := "tsh", iso := "par", value := .noDominantOrder }
  , { walsCode := "udm", iso := "udm", value := .degreeWordAdjective }
  , { walsCode := "una", iso := "mtg", value := .degreeWordAdjective }
  , { walsCode := "ung", iso := "ung", value := .adjectiveDegreeWord }
  , { walsCode := "url", iso := "urk", value := .adjectiveDegreeWord }
  , { walsCode := "urd", iso := "urd", value := .degreeWordAdjective }
  , { walsCode := "urk", iso := "urb", value := .adjectiveDegreeWord }
  , { walsCode := "usa", iso := "wnu", value := .degreeWordAdjective }
  , { walsCode := "usr", iso := "usa", value := .degreeWordAdjective }
  , { walsCode := "uzb", iso := "", value := .degreeWordAdjective }
  , { walsCode := "vaf", iso := "vaf", value := .degreeWordAdjective }
  , { walsCode := "wal", iso := "van", value := .adjectiveDegreeWord }
  , { walsCode := "wbn", iso := "wms", value := .adjectiveDegreeWord }
  , { walsCode := "wme", iso := "wme", value := .degreeWordAdjective }
  , { walsCode := "wra", iso := "wba", value := .adjectiveDegreeWord }
  , { walsCode := "war", iso := "pav", value := .noDominantOrder }
  , { walsCode := "wsk", iso := "wsk", value := .adjectiveDegreeWord }
  , { walsCode := "wat", iso := "wbv", value := .degreeWordAdjective }
  , { walsCode := "wel", iso := "cym", value := .noDominantOrder }
  , { walsCode := "wem", iso := "xww", value := .degreeWordAdjective }
  , { walsCode := "wol", iso := "woe", value := .adjectiveDegreeWord }
  , { walsCode := "wlo", iso := "wlo", value := .adjectiveDegreeWord }
  , { walsCode := "wlf", iso := "wol", value := .adjectiveDegreeWord }
  , { walsCode := "wor", iso := "wro", value := .adjectiveDegreeWord }
  , { walsCode := "xav", iso := "xav", value := .adjectiveDegreeWord }
  , { walsCode := "yag", iso := "yad", value := .degreeWordAdjective }
  , { walsCode := "yap", iso := "yap", value := .degreeWordAdjective }
  , { walsCode := "yaq", iso := "yaq", value := .degreeWordAdjective }
  , { walsCode := "yar", iso := "yrb", value := .adjectiveDegreeWord }
  , { walsCode := "ycn", iso := "ycn", value := .adjectiveDegreeWord }
  , { walsCode := "ytu", iso := "ykg", value := .degreeWordAdjective }
  , { walsCode := "yur", iso := "yur", value := .degreeWordAdjective }
  , { walsCode := "zai", iso := "zai", value := .degreeWordAdjective }
  , { walsCode := "zch", iso := "zoh", value := .degreeWordAdjective }
  , { walsCode := "zqc", iso := "zoc", value := .degreeWordAdjective }
  , { walsCode := "omi", iso := "aom", value := .noDominantOrder }
  ]

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F91A
