import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 95A: Relationship between the Order of Object and Verb and the Order of Adposition and Noun Phrase
@cite{wals-2013}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 95A`.

Chapter 95, 1142 languages.
-/

namespace Core.WALS.F95A

/-- WALS 95A values. -/
inductive RelationshipBetweenTheOrderOfObjectAndVerbAndTheOrderOfAdpositionAndNounPhrase where
  /-- OV and Postpositions (472 languages). -/
  | ovAndPostpositions
  /-- OV and Prepositions (14 languages). -/
  | ovAndPrepositions
  /-- VO and Postpositions (42 languages). -/
  | voAndPostpositions
  /-- VO and Prepositions (456 languages). -/
  | voAndPrepositions
  /-- Other (158 languages). -/
  | other
  deriving DecidableEq, BEq, Repr

private def allData_0 : List (Datapoint RelationshipBetweenTheOrderOfObjectAndVerbAndTheOrderOfAdpositionAndNounPhrase) :=
  [ { walsCode := "ani", iso := "hnh", value := .other }
  , { walsCode := "huc", iso := "huc", value := .other }
  , { walsCode := "aar", iso := "aiw", value := .ovAndPostpositions }
  , { walsCode := "aba", iso := "aau", value := .ovAndPostpositions }
  , { walsCode := "abi", iso := "axb", value := .voAndPrepositions }
  , { walsCode := "abk", iso := "abk", value := .ovAndPostpositions }
  , { walsCode := "abu", iso := "kgr", value := .voAndPrepositions }
  , { walsCode := "ace", iso := "ace", value := .other }
  , { walsCode := "acg", iso := "aca", value := .voAndPostpositions }
  , { walsCode := "acn", iso := "acn", value := .ovAndPostpositions }
  , { walsCode := "acl", iso := "ach", value := .voAndPrepositions }
  , { walsCode := "acm", iso := "acv", value := .voAndPrepositions }
  , { walsCode := "aco", iso := "kjq", value := .other }
  , { walsCode := "adg", iso := "adn", value := .ovAndPostpositions }
  , { walsCode := "adi", iso := "adj", value := .voAndPostpositions }
  , { walsCode := "ady", iso := "ady", value := .ovAndPostpositions }
  , { walsCode := "adn", iso := "adt", value := .other }
  , { walsCode := "adz", iso := "adz", value := .voAndPrepositions }
  , { walsCode := "agc", iso := "agt", value := .voAndPrepositions }
  , { walsCode := "ain", iso := "ain", value := .ovAndPostpositions }
  , { walsCode := "aja", iso := "aja", value := .voAndPrepositions }
  , { walsCode := "ajg", iso := "ajg", value := .other }
  , { walsCode := "akn", iso := "aka", value := .other }
  , { walsCode := "akh", iso := "ahk", value := .ovAndPostpositions }
  , { walsCode := "all", iso := "nrz", value := .other }
  , { walsCode := "ala", iso := "amp", value := .ovAndPostpositions }
  , { walsCode := "alw", iso := "alh", value := .other }
  , { walsCode := "alb", iso := "sqi", value := .voAndPrepositions }
  , { walsCode := "als", iso := "aes", value := .voAndPrepositions }
  , { walsCode := "aln", iso := "alp", value := .voAndPrepositions }
  , { walsCode := "aly", iso := "aly", value := .ovAndPostpositions }
  , { walsCode := "amc", iso := "amc", value := .ovAndPostpositions }
  , { walsCode := "ama", iso := "aie", value := .voAndPrepositions }
  , { walsCode := "aml", iso := "omb", value := .voAndPrepositions }
  , { walsCode := "amq", iso := "amk", value := .voAndPrepositions }
  , { walsCode := "amb", iso := "abt", value := .ovAndPostpositions }
  , { walsCode := "amt", iso := "adx", value := .ovAndPostpositions }
  , { walsCode := "ame", iso := "aey", value := .ovAndPostpositions }
  , { walsCode := "amh", iso := "amh", value := .other }
  , { walsCode := "ami", iso := "ami", value := .voAndPrepositions }
  , { walsCode := "anj", iso := "aty", value := .voAndPrepositions }
  , { walsCode := "agm", iso := "njm", value := .ovAndPostpositions }
  , { walsCode := "anc", iso := "anc", value := .voAndPrepositions }
  , { walsCode := "ang", iso := "agg", value := .ovAndPostpositions }
  , { walsCode := "ann", iso := "aoi", value := .other }
  , { walsCode := "any", iso := "anu", value := .other }
  , { walsCode := "ane", iso := "anz", value := .voAndPrepositions }
  , { walsCode := "ao", iso := "njo", value := .ovAndPostpositions }
  , { walsCode := "apl", iso := "apy", value := .ovAndPostpositions }
  , { walsCode := "apt", iso := "apt", value := .ovAndPostpositions }
  , { walsCode := "api", iso := "apn", value := .ovAndPostpositions }
  , { walsCode := "apu", iso := "apu", value := .other }
  , { walsCode := "aeg", iso := "arz", value := .voAndPrepositions }
  , { walsCode := "arg", iso := "afb", value := .voAndPrepositions }
  , { walsCode := "arq", iso := "acm", value := .voAndPrepositions }
  , { walsCode := "arj", iso := "afb", value := .voAndPrepositions }
  , { walsCode := "ams", iso := "arb", value := .voAndPrepositions }
  , { walsCode := "amr", iso := "ary", value := .voAndPrepositions }
  , { walsCode := "asy", iso := "apc", value := .voAndPrepositions }
  , { walsCode := "ana", iso := "aro", value := .ovAndPostpositions }
  , { walsCode := "arp", iso := "ape", value := .voAndPrepositions }
  , { walsCode := "arc", iso := "aqc", value := .ovAndPostpositions }
  , { walsCode := "arm", iso := "hye", value := .other }
  , { walsCode := "arw", iso := "hyw", value := .ovAndPostpositions }
  , { walsCode := "alk", iso := "apr", value := .voAndPrepositions }
  , { walsCode := "aro", iso := "aia", value := .voAndPrepositions }
  , { walsCode := "amp", iso := "aer", value := .ovAndPostpositions }
  , { walsCode := "asu", iso := "asu", value := .ovAndPostpositions }
  , { walsCode := "atk", iso := "aqp", value := .ovAndPostpositions }
  , { walsCode := "ata", iso := "tay", value := .voAndPrepositions }
  , { walsCode := "au", iso := "avt", value := .voAndPrepositions }
  , { walsCode := "ava", iso := "ava", value := .ovAndPostpositions }
  , { walsCode := "avo", iso := "avu", value := .other }
  , { walsCode := "awp", iso := "kwi", value := .ovAndPostpositions }
  , { walsCode := "awt", iso := "kmn", value := .ovAndPostpositions }
  , { walsCode := "ayw", iso := "nfl", value := .voAndPrepositions }
  , { walsCode := "aym", iso := "ayr", value := .ovAndPostpositions }
  , { walsCode := "bbl", iso := "bvx", value := .voAndPrepositions }
  , { walsCode := "bab", iso := "bav", value := .voAndPrepositions }
  , { walsCode := "bac", iso := "wdj", value := .other }
  , { walsCode := "baf", iso := "bfd", value := .voAndPrepositions }
  , { walsCode := "bgs", iso := "bsp", value := .voAndPostpositions }
  , { walsCode := "bag", iso := "bmi", value := .voAndPrepositions }
  , { walsCode := "bgr", iso := "fuu", value := .other }
  , { walsCode := "bai", iso := "bca", value := .other }
  , { walsCode := "baj", iso := "bdl", value := .voAndPrepositions }
  , { walsCode := "bwc", iso := "bdr", value := .voAndPrepositions }
  , { walsCode := "bak", iso := "bkc", value := .voAndPrepositions }
  , { walsCode := "bka", iso := "bdh", value := .voAndPrepositions }
  , { walsCode := "bvi", iso := "", value := .voAndPrepositions }
  , { walsCode := "blt", iso := "bft", value := .ovAndPostpositions }
  , { walsCode := "bam", iso := "bam", value := .ovAndPostpositions }
  , { walsCode := "bnk", iso := "abb", value := .voAndPrepositions }
  , { walsCode := "bnn", iso := "bcm", value := .voAndPrepositions }
  , { walsCode := "bao", iso := "peh", value := .ovAndPostpositions }
  , { walsCode := "ble", iso := "bci", value := .voAndPostpositions }
  , { walsCode := "baa", iso := "bbb", value := .ovAndPostpositions }
  , { walsCode := "bbu", iso := "brm", value := .voAndPrepositions }
  , { walsCode := "brs", iso := "bsn", value := .ovAndPostpositions }
  , { walsCode := "bar", iso := "bfa", value := .voAndPrepositions }
  , { walsCode := "bry", iso := "byr", value := .ovAndPostpositions }
  , { walsCode := "bae", iso := "bae", value := .voAndPostpositions }
  , { walsCode := "bas", iso := "bas", value := .voAndPrepositions }
  , { walsCode := "bsk", iso := "bak", value := .ovAndPostpositions }
  , { walsCode := "bsq", iso := "eus", value := .ovAndPostpositions }
  , { walsCode := "bkr", iso := "btx", value := .voAndPrepositions }
  , { walsCode := "bto", iso := "bbc", value := .voAndPrepositions }
  , { walsCode := "bzi", iso := "bvz", value := .ovAndPostpositions }
  , { walsCode := "baw", iso := "bgr", value := .ovAndPostpositions }
  , { walsCode := "bej", iso := "bej", value := .ovAndPostpositions }
  , { walsCode := "bco", iso := "blc", value := .voAndPrepositions }
  , { walsCode := "blr", iso := "bel", value := .other }
  , { walsCode := "blu", iso := "lua", value := .voAndPrepositions }
  , { walsCode := "bse", iso := "rif", value := .voAndPrepositions }
  , { walsCode := "bfg", iso := "grr", value := .voAndPrepositions }
  , { walsCode := "bma", iso := "tzm", value := .voAndPrepositions }
  , { walsCode := "brf", iso := "rif", value := .voAndPrepositions }
  , { walsCode := "zag", iso := "zag", value := .ovAndPostpositions }
  , { walsCode := "bti", iso := "", value := .ovAndPostpositions }
  , { walsCode := "bkb", iso := "xub", value := .ovAndPostpositions }
  , { walsCode := "bho", iso := "bho", value := .ovAndPostpositions }
  , { walsCode := "bik", iso := "bhw", value := .voAndPrepositions }
  , { walsCode := "bid", iso := "bid", value := .voAndPrepositions }
  , { walsCode := "bkl", iso := "bcl", value := .voAndPrepositions }
  , { walsCode := "bia", iso := "bip", value := .voAndPrepositions }
  , { walsCode := "bln", iso := "byn", value := .ovAndPostpositions }
  , { walsCode := "blx", iso := "bll", value := .ovAndPostpositions }
  , { walsCode := "bil", iso := "blb", value := .voAndPostpositions }
  , { walsCode := "bmb", iso := "bim", value := .other }
  , { walsCode := "bin", iso := "bhg", value := .ovAndPostpositions }
  , { walsCode := "bni", iso := "bin", value := .voAndPrepositions }
  , { walsCode := "bbw", iso := "gup", value := .other }
  , { walsCode := "bir", iso := "bom", value := .voAndPrepositions }
  , { walsCode := "boa", iso := "kvg", value := .ovAndPostpositions }
  , { walsCode := "bob", iso := "bni", value := .voAndPrepositions }
  , { walsCode := "bok", iso := "bqc", value := .ovAndPostpositions }
  , { walsCode := "bol", iso := "bli", value := .voAndPrepositions }
  , { walsCode := "bgo", iso := "bot", value := .voAndPrepositions }
  , { walsCode := "bon", iso := "bpu", value := .ovAndPostpositions }
  , { walsCode := "btk", iso := "lbk", value := .voAndPrepositions }
  , { walsCode := "boj", iso := "adi", value := .ovAndPostpositions }
  , { walsCode := "bra", iso := "brb", value := .voAndPrepositions }
  , { walsCode := "bre", iso := "bre", value := .voAndPrepositions }
  , { walsCode := "bri", iso := "bzd", value := .ovAndPostpositions }
  , { walsCode := "bdu", iso := "buu", value := .voAndPrepositions }
  , { walsCode := "bud", iso := "bdm", value := .voAndPrepositions }
  , { walsCode := "bul", iso := "bul", value := .voAndPrepositions }
  , { walsCode := "bum", iso := "tkw", value := .voAndPrepositions }
  , { walsCode := "bnb", iso := "bck", value := .other }
  , { walsCode := "bua", iso := "bvr", value := .ovAndPostpositions }
  , { walsCode := "but", iso := "bxm", value := .ovAndPostpositions }
  , { walsCode := "brm", iso := "mya", value := .ovAndPostpositions }
  , { walsCode := "buu", iso := "mhs", value := .voAndPrepositions }
  , { walsCode := "brn", iso := "bds", value := .other }
  , { walsCode := "bur", iso := "bsk", value := .ovAndPostpositions }
  , { walsCode := "bus", iso := "bqp", value := .ovAndPostpositions }
  , { walsCode := "bsh", iso := "buf", value := .voAndPrepositions }
  , { walsCode := "dok", iso := "ngc", value := .voAndPrepositions }
  , { walsCode := "bya", iso := "bee", value := .ovAndPostpositions }
  , { walsCode := "cah", iso := "chl", value := .ovAndPostpositions }
  , { walsCode := "cak", iso := "cak", value := .voAndPrepositions }
  , { walsCode := "cam", iso := "kbh", value := .other }
  , { walsCode := "cnl", iso := "ram", value := .ovAndPostpositions }
  , { walsCode := "cnt", iso := "yue", value := .other }
  , { walsCode := "car", iso := "car", value := .ovAndPostpositions }
  , { walsCode := "cde", iso := "mch", value := .ovAndPostpositions }
  , { walsCode := "cas", iso := "cbr", value := .ovAndPostpositions }
  , { walsCode := "ctl", iso := "cat", value := .voAndPrepositions }
  , { walsCode := "ctw", iso := "chc", value := .ovAndPostpositions }
  , { walsCode := "cav", iso := "cav", value := .other }
  , { walsCode := "cyv", iso := "cyb", value := .voAndPrepositions }
  , { walsCode := "ceb", iso := "ceb", value := .voAndPrepositions }
  , { walsCode := "chh", iso := "sgw", value := .other }
  , { walsCode := "cai", iso := "suq", value := .other }
  , { walsCode := "cha", iso := "cha", value := .voAndPrepositions }
  , { walsCode := "chg", iso := "nbc", value := .ovAndPostpositions }
  , { walsCode := "chn", iso := "chx", value := .ovAndPostpositions }
  , { walsCode := "cso", iso := "ctp", value := .voAndPrepositions }
  , { walsCode := "cya", iso := "ctp", value := .voAndPrepositions }
  , { walsCode := "chc", iso := "che", value := .ovAndPostpositions }
  , { walsCode := "cmh", iso := "ute", value := .other }
  , { walsCode := "che", iso := "chr", value := .ovAndPostpositions }
  , { walsCode := "cic", iso := "nya", value := .voAndPrepositions }
  , { walsCode := "chi", iso := "cid", value := .ovAndPostpositions }
  , { walsCode := "cmr", iso := "mrh", value := .ovAndPostpositions }
  , { walsCode := "chs", iso := "csy", value := .ovAndPostpositions }
  , { walsCode := "cti", iso := "ctd", value := .ovAndPostpositions }
  , { walsCode := "ccm", iso := "cco", value := .voAndPrepositions }
  , { walsCode := "cle", iso := "cle", value := .voAndPrepositions }
  , { walsCode := "cpl", iso := "cpa", value := .voAndPrepositions }
  , { walsCode := "chq", iso := "chq", value := .voAndPrepositions }
  , { walsCode := "ckl", iso := "chh", value := .voAndPrepositions }
  , { walsCode := "chp", iso := "chp", value := .ovAndPostpositions }
  , { walsCode := "cqt", iso := "cax", value := .voAndPrepositions }
  , { walsCode := "ctm", iso := "ctm", value := .ovAndPostpositions }
  , { walsCode := "cct", iso := "cho", value := .ovAndPostpositions }
  , { walsCode := "cln", iso := "cht", value := .ovAndPostpositions }
  , { walsCode := "cmy", iso := "chf", value := .voAndPrepositions }
  , { walsCode := "chr", iso := "crw", value := .voAndPrepositions }
  , { walsCode := "chj", iso := "cac", value := .voAndPrepositions }
  , { walsCode := "chk", iso := "ckt", value := .ovAndPostpositions }
  , { walsCode := "cba", iso := "boi", value := .voAndPrepositions }
  , { walsCode := "chv", iso := "chv", value := .ovAndPostpositions }
  , { walsCode := "cbo", iso := "cao", value := .ovAndPostpositions }
  , { walsCode := "coc", iso := "cod", value := .voAndPostpositions }
  , { walsCode := "coe", iso := "crd", value := .voAndPrepositions }
  , { walsCode := "cmn", iso := "com", value := .ovAndPostpositions }
  , { walsCode := "cmx", iso := "coo", value := .voAndPrepositions }
  , { walsCode := "coo", iso := "csz", value := .other }
  , { walsCode := "cop", iso := "cop", value := .voAndPrepositions }
  , { walsCode := "cor", iso := "crn", value := .voAndPostpositions }
  , { walsCode := "crn", iso := "cor", value := .voAndPrepositions }
  , { walsCode := "cea", iso := "csw", value := .voAndPostpositions }
  , { walsCode := "cub", iso := "cub", value := .ovAndPostpositions }
  , { walsCode := "cuc", iso := "", value := .voAndPrepositions }
  , { walsCode := "cup", iso := "cup", value := .ovAndPostpositions }
  , { walsCode := "cze", iso := "ces", value := .voAndPrepositions }
  , { walsCode := "cem", iso := "cam", value := .voAndPrepositions }
  , { walsCode := "ddj", iso := "god", value := .other }
  , { walsCode := "dag", iso := "dgz", value := .ovAndPostpositions }
  , { walsCode := "dga", iso := "dga", value := .voAndPostpositions }
  , { walsCode := "dgb", iso := "dag", value := .voAndPostpositions }
  , { walsCode := "dgr", iso := "dta", value := .ovAndPostpositions }
  , { walsCode := "dam", iso := "mbp", value := .other }
  , { walsCode := "dan", iso := "dnj", value := .ovAndPostpositions }
  , { walsCode := "dni", iso := "dni", value := .ovAndPostpositions }
  , { walsCode := "dsh", iso := "dan", value := .voAndPrepositions }
  , { walsCode := "drg", iso := "dar", value := .ovAndPostpositions }
  , { walsCode := "drm", iso := "drd", value := .ovAndPostpositions }
  , { walsCode := "des", iso := "des", value := .ovAndPostpositions }
  , { walsCode := "dhr", iso := "dhr", value := .other }
  , { walsCode := "dhm", iso := "dhi", value := .ovAndPostpositions }
  , { walsCode := "did", iso := "did", value := .voAndPrepositions }
  , { walsCode := "die", iso := "dih", value := .ovAndPostpositions }
  , { walsCode := "dig", iso := "mhu", value := .ovAndPostpositions }
  , { walsCode := "dms", iso := "dis", value := .ovAndPostpositions }
  , { walsCode := "dim", iso := "dim", value := .ovAndPostpositions }
  , { walsCode := "din", iso := "din", value := .other }
  , { walsCode := "dio", iso := "dyo", value := .voAndPrepositions }
  , { walsCode := "djm", iso := "djr", value := .other }
  , { walsCode := "djr", iso := "ddj", value := .other }
  , { walsCode := "djn", iso := "dji", value := .other }
  , { walsCode := "dji", iso := "jig", value := .ovAndPostpositions }
  , { walsCode := "dlm", iso := "kbv", value := .ovAndPostpositions }
  , { walsCode := "der", iso := "kbv", value := .ovAndPostpositions }
  , { walsCode := "dmk", iso := "dmk", value := .ovAndPostpositions }
  , { walsCode := "dom", iso := "rmt", value := .voAndPrepositions }
  , { walsCode := "don", iso := "kmc", value := .voAndPrepositions }
  , { walsCode := "dgo", iso := "doo", value := .other }
  , { walsCode := "dds", iso := "dds", value := .ovAndPostpositions }
  , { walsCode := "doy", iso := "dow", value := .other }
  , { walsCode := "dre", iso := "dhv", value := .voAndPrepositions }
  , { walsCode := "duk", iso := "dud", value := .voAndPrepositions }
  , { walsCode := "dul", iso := "duu", value := .ovAndPostpositions }
  , { walsCode := "dmi", iso := "dus", value := .ovAndPostpositions }
  , { walsCode := "dun", iso := "duc", value := .ovAndPostpositions }
  , { walsCode := "dut", iso := "nld", value := .other }
  , { walsCode := "daw", iso := "kwa", value := .ovAndPostpositions }
  , { walsCode := "edo", iso := "etr", value := .ovAndPostpositions }
  , { walsCode := "erk", iso := "erk", value := .voAndPrepositions }
  , { walsCode := "eip", iso := "eip", value := .ovAndPostpositions }
  , { walsCode := "ora", iso := "ema", value := .voAndPrepositions }
  , { walsCode := "emb", iso := "emp", value := .ovAndPostpositions }
  , { walsCode := "emm", iso := "amy", value := .other }
  , { walsCode := "ene", iso := "", value := .ovAndPostpositions }
  , { walsCode := "egn", iso := "enn", value := .voAndPrepositions }
  , { walsCode := "eno", iso := "eno", value := .voAndPrepositions }
  , { walsCode := "eng", iso := "eng", value := .voAndPrepositions }
  , { walsCode := "epe", iso := "sja", value := .ovAndPostpositions }
  , { walsCode := "err", iso := "erg", value := .voAndPrepositions }
  , { walsCode := "ese", iso := "ese", value := .ovAndPostpositions }
  , { walsCode := "esm", iso := "", value := .voAndPrepositions }
  , { walsCode := "est", iso := "ekk", value := .voAndPostpositions }
  , { walsCode := "eud", iso := "", value := .ovAndPostpositions }
  , { walsCode := "evn", iso := "eve", value := .ovAndPostpositions }
  , { walsCode := "eve", iso := "evn", value := .ovAndPostpositions }
  , { walsCode := "ewe", iso := "ewe", value := .voAndPostpositions }
  , { walsCode := "ewo", iso := "ewo", value := .voAndPrepositions }
  , { walsCode := "fas", iso := "faa", value := .ovAndPostpositions }
  , { walsCode := "fij", iso := "fij", value := .voAndPrepositions }
  , { walsCode := "fin", iso := "fin", value := .voAndPostpositions }
  , { walsCode := "pdp", iso := "ppo", value := .ovAndPostpositions }
  , { walsCode := "fon", iso := "fon", value := .other }
  , { walsCode := "for", iso := "for", value := .ovAndPostpositions }
  , { walsCode := "fre", iso := "fra", value := .voAndPrepositions }
  , { walsCode := "fri", iso := "fry", value := .other }
  , { walsCode := "fua", iso := "fub", value := .voAndPrepositions }
  , { walsCode := "fni", iso := "fuv", value := .voAndPrepositions }
  , { walsCode := "ful", iso := "fun", value := .ovAndPostpositions }
  , { walsCode := "fur", iso := "fvr", value := .ovAndPostpositions }
  , { walsCode := "fut", iso := "fut", value := .voAndPrepositions }
  , { walsCode := "fye", iso := "pym", value := .voAndPrepositions }
  , { walsCode := "gnd", iso := "gqa", value := .voAndPrepositions }
  , { walsCode := "gae", iso := "gla", value := .voAndPrepositions }
  , { walsCode := "gam", iso := "gmv", value := .ovAndPostpositions }
  , { walsCode := "gap", iso := "pwg", value := .ovAndPostpositions }
  , { walsCode := "gar", iso := "grt", value := .ovAndPostpositions }
  , { walsCode := "grr", iso := "wrk", value := .voAndPrepositions }
  , { walsCode := "grf", iso := "cab", value := .voAndPrepositions }
  , { walsCode := "gav", iso := "gvo", value := .ovAndPostpositions }
  , { walsCode := "gbb", iso := "gbp", value := .voAndPrepositions }
  , { walsCode := "gel", iso := "nlg", value := .voAndPrepositions }
  , { walsCode := "gla", iso := "gqu", value := .voAndPrepositions }
  , { walsCode := "geo", iso := "kat", value := .ovAndPostpositions }
  , { walsCode := "ger", iso := "deu", value := .other }
  , { walsCode := "gid", iso := "gih", value := .other }
  , { walsCode := "gim", iso := "bcq", value := .ovAndPostpositions }
  , { walsCode := "git", iso := "git", value := .other }
  , { walsCode := "giz", iso := "gis", value := .voAndPrepositions }
  , { walsCode := "goa", iso := "guc", value := .voAndPrepositions }
  , { walsCode := "goe", iso := "ank", value := .voAndPrepositions }
  , { walsCode := "gok", iso := "gkn", value := .voAndPrepositions }
  , { walsCode := "gln", iso := "gvf", value := .ovAndPostpositions }
  , { walsCode := "gon", iso := "gno", value := .ovAndPostpositions }
  , { walsCode := "goo", iso := "gni", value := .other }
  , { walsCode := "gan", iso := "apq", value := .ovAndPostpositions }
  , { walsCode := "grb", iso := "grj", value := .voAndPostpositions }
  , { walsCode := "grk", iso := "ell", value := .voAndPrepositions }
  , { walsCode := "grw", iso := "kal", value := .ovAndPostpositions }
  , { walsCode := "ghb", iso := "guh", value := .ovAndPostpositions }
  , { walsCode := "gjj", iso := "gub", value := .voAndPostpositions }
  , { walsCode := "gua", iso := "gug", value := .voAndPostpositions }
  , { walsCode := "grj", iso := "var", value := .other }
  , { walsCode := "gto", iso := "gta", value := .voAndPrepositions }
  , { walsCode := "gud", iso := "gde", value := .voAndPrepositions }
  , { walsCode := "guj", iso := "guj", value := .ovAndPostpositions }
  , { walsCode := "gul", iso := "kcm", value := .other }
  , { walsCode := "gmw", iso := "gvs", value := .ovAndPostpositions }
  , { walsCode := "gum", iso := "kgs", value := .other }
  , { walsCode := "gmz", iso := "guk", value := .voAndPrepositions }
  , { walsCode := "gnb", iso := "wlg", value := .voAndPrepositions }
  , { walsCode := "guw", iso := "guw", value := .other }
  , { walsCode := "gnn", iso := "gww", value := .other }
  , { walsCode := "ggu", iso := "gnr", value := .other }
  , { walsCode := "grg", iso := "gge", value := .other }
  , { walsCode := "gur", iso := "", value := .ovAndPostpositions }
  , { walsCode := "gwa", iso := "gbr", value := .other }
  , { walsCode := "gwo", iso := "kcg", value := .voAndPrepositions }
  , { walsCode := "gyc", iso := "jya", value := .ovAndPostpositions }
  , { walsCode := "hai", iso := "hai", value := .ovAndPostpositions }
  , { walsCode := "hal", iso := "hla", value := .voAndPrepositions }
  , { walsCode := "hlu", iso := "hur", value := .voAndPrepositions }
  , { walsCode := "ham", iso := "hmt", value := .ovAndPostpositions }
  , { walsCode := "hhu", iso := "wos", value := .ovAndPostpositions }
  , { walsCode := "han", iso := "hni", value := .ovAndPostpositions }
  , { walsCode := "hat", iso := "had", value := .voAndPrepositions }
  , { walsCode := "hau", iso := "hau", value := .voAndPrepositions }
  , { walsCode := "haw", iso := "haw", value := .voAndPrepositions }
  , { walsCode := "hya", iso := "hay", value := .voAndPrepositions }
  , { walsCode := "hay", iso := "vay", value := .ovAndPostpositions }
  , { walsCode := "hdi", iso := "xed", value := .voAndPrepositions }
  , { walsCode := "heb", iso := "heb", value := .voAndPrepositions }
  , { walsCode := "heh", iso := "heh", value := .voAndPrepositions }
  , { walsCode := "hei", iso := "hei", value := .voAndPrepositions }
  , { walsCode := "hem", iso := "hem", value := .voAndPrepositions }
  , { walsCode := "hid", iso := "hid", value := .ovAndPostpositions }
  , { walsCode := "hil", iso := "hil", value := .voAndPrepositions }
  , { walsCode := "hin", iso := "hin", value := .ovAndPostpositions }
  , { walsCode := "hix", iso := "hix", value := .ovAndPostpositions }
  , { walsCode := "lic", iso := "lic", value := .voAndPrepositions }
  , { walsCode := "hma", iso := "hmr", value := .ovAndPostpositions }
  , { walsCode := "hmo", iso := "hnj", value := .voAndPrepositions }
  , { walsCode := "ho", iso := "hoc", value := .ovAndPostpositions }
  , { walsCode := "hoa", iso := "hoa", value := .voAndPrepositions }
  , { walsCode := "hop", iso := "hop", value := .ovAndPostpositions }
  , { walsCode := "hua", iso := "ygr", value := .ovAndPostpositions }
  , { walsCode := "hlp", iso := "yuf", value := .ovAndPostpositions }
  , { walsCode := "htc", iso := "hus", value := .voAndPrepositions }
  , { walsCode := "hve", iso := "huv", value := .voAndPrepositions }
  , { walsCode := "hum", iso := "huu", value := .ovAndPostpositions }
  , { walsCode := "hun", iso := "hun", value := .voAndPostpositions }
  , { walsCode := "hzb", iso := "huz", value := .ovAndPostpositions }
  , { walsCode := "hpd", iso := "jup", value := .ovAndPostpositions }
  , { walsCode := "hup", iso := "hup", value := .other }
  , { walsCode := "isa", iso := "ksi", value := .other }
  , { walsCode := "iaa", iso := "iai", value := .voAndPrepositions }
  , { walsCode := "iau", iso := "tmu", value := .ovAndPostpositions }
  , { walsCode := "iba", iso := "iba", value := .voAndPrepositions }
  , { walsCode := "ice", iso := "isl", value := .voAndPrepositions }
  , { walsCode := "ido", iso := "idu", value := .other }
  , { walsCode := "idu", iso := "clk", value := .ovAndPostpositions }
  , { walsCode := "idn", iso := "viv", value := .ovAndPostpositions }
  , { walsCode := "ifu", iso := "ifb", value := .voAndPrepositions }
  , { walsCode := "ifm", iso := "ifm", value := .voAndPrepositions }
  , { walsCode := "igb", iso := "ibo", value := .voAndPrepositions }
  , { walsCode := "ign", iso := "ign", value := .voAndPrepositions }
  , { walsCode := "ik", iso := "ikx", value := .voAndPrepositions }
  , { walsCode := "ika", iso := "arh", value := .ovAndPostpositions }
  , { walsCode := "ila", iso := "ilb", value := .voAndPrepositions }
  , { walsCode := "ilo", iso := "ilo", value := .voAndPrepositions }
  , { walsCode := "imo", iso := "imn", value := .ovAndPostpositions }
  , { walsCode := "ina", iso := "szp", value := .other }
  , { walsCode := "ind", iso := "ind", value := .voAndPrepositions }
  , { walsCode := "igs", iso := "tbi", value := .voAndPrepositions }
  , { walsCode := "inn", iso := "ynd", value := .ovAndPostpositions }
  , { walsCode := "iqu", iso := "iqu", value := .voAndPostpositions }
  , { walsCode := "irq", iso := "irk", value := .ovAndPrepositions }
  , { walsCode := "irr", iso := "irh", value := .voAndPrepositions }
  , { walsCode := "iri", iso := "gle", value := .voAndPrepositions }
  , { walsCode := "ita", iso := "ita", value := .voAndPrepositions }
  , { walsCode := "iwa", iso := "ibd", value := .other }
  , { walsCode := "kwy", iso := "yom", value := .voAndPrepositions }
  , { walsCode := "ixi", iso := "ixl", value := .voAndPrepositions }
  , { walsCode := "jar", iso := "izr", value := .voAndPrepositions }
  , { walsCode := "izi", iso := "izz", value := .voAndPrepositions }
  , { walsCode := "jbt", iso := "jbt", value := .ovAndPostpositions }
  , { walsCode := "jab", iso := "jae", value := .other }
  , { walsCode := "jak", iso := "jac", value := .voAndPrepositions }
  , { walsCode := "jam", iso := "djd", value := .other }
  , { walsCode := "jms", iso := "djm", value := .ovAndPostpositions }
  , { walsCode := "jpn", iso := "jpn", value := .ovAndPostpositions }
  , { walsCode := "jeb", iso := "jeb", value := .other }
  , { walsCode := "jng", iso := "kac", value := .ovAndPostpositions }
  , { walsCode := "jin", iso := "jiu", value := .ovAndPostpositions }
  , { walsCode := "joh", iso := "rgk", value := .ovAndPostpositions }
  , { walsCode := "jug", iso := "nst", value := .ovAndPostpositions }
  , { walsCode := "juk", iso := "jbu", value := .voAndPrepositions }
  , { walsCode := "jmo", iso := "bex", value := .voAndPrepositions }
  , { walsCode := "juh", iso := "ktz", value := .voAndPostpositions }
  , { walsCode := "kab", iso := "kbd", value := .ovAndPostpositions }
  , { walsCode := "kbt", iso := "xkp", value := .ovAndPostpositions }
  , { walsCode := "kby", iso := "kbp", value := .voAndPrepositions }
  , { walsCode := "kbl", iso := "kab", value := .voAndPrepositions }
  , { walsCode := "kac", iso := "xac", value := .ovAndPostpositions }
  , { walsCode := "kdz", iso := "kzj", value := .voAndPrepositions }
  , { walsCode := "kgr", iso := "kki", value := .voAndPrepositions }
  , { walsCode := "kng", iso := "kgp", value := .ovAndPostpositions }
  , { walsCode := "krr", iso := "kxa", value := .other }
  , { walsCode := "klq", iso := "kmh", value := .ovAndPostpositions }
  , { walsCode := "kmk", iso := "xal", value := .ovAndPostpositions }
  , { walsCode := "kll", iso := "bco", value := .ovAndPostpositions }
  , { walsCode := "kma", iso := "kay", value := .ovAndPostpositions }
  , { walsCode := "kmz", iso := "kms", value := .ovAndPostpositions }
  , { walsCode := "kms", iso := "xas", value := .ovAndPostpositions }
  , { walsCode := "kam", iso := "xbr", value := .voAndPrepositions }
  , { walsCode := "kbo", iso := "kbx", value := .ovAndPostpositions }
  , { walsCode := "kmw", iso := "xmu", value := .other }
  , { walsCode := "kan", iso := "ogo", value := .voAndPrepositions }
  , { walsCode := "knk", iso := "kna", value := .voAndPrepositions }
  , { walsCode := "xns", iso := "xns", value := .ovAndPostpositions }
  , { walsCode := "knd", iso := "kan", value := .ovAndPostpositions }
  , { walsCode := "knb", iso := "khd", value := .ovAndPostpositions }
  , { walsCode := "knr", iso := "knc", value := .ovAndPostpositions }
  , { walsCode := "kpm", iso := "pam", value := .voAndPrepositions }
  , { walsCode := "kar", iso := "kah", value := .voAndPrepositions }
  , { walsCode := "krc", iso := "krc", value := .ovAndPostpositions }
  , { walsCode := "jva", iso := "kpj", value := .ovAndPostpositions }
  , { walsCode := "kkp", iso := "kaa", value := .ovAndPostpositions }
  , { walsCode := "kkw", iso := "zkk", value := .other }
  , { walsCode := "kbw", iso := "bwe", value := .voAndPrepositions }
  , { walsCode := "kpw", iso := "kjp", value := .voAndPrepositions }
  , { walsCode := "ksg", iso := "ksw", value := .voAndPrepositions }
  , { walsCode := "kmj", iso := "kdj", value := .voAndPrepositions }
  , { walsCode := "kyr", iso := "yuj", value := .ovAndPostpositions }
  , { walsCode := "krk", iso := "kyh", value := .other }
  , { walsCode := "kaa", iso := "arr", value := .ovAndPostpositions }
  , { walsCode := "kas", iso := "kas", value := .voAndPostpositions }
  , { walsCode := "kti", iso := "kts", value := .ovAndPostpositions }
  , { walsCode := "kau", iso := "pss", value := .voAndPrepositions }
  , { walsCode := "kws", iso := "xaw", value := .other }
  , { walsCode := "kyz", iso := "kyz", value := .ovAndPostpositions }
  , { walsCode := "kyl", iso := "eky", value := .other }
  , { walsCode := "kay", iso := "gyd", value := .other }
  , { walsCode := "kel", iso := "sbc", value := .voAndPrepositions }
  , { walsCode := "kem", iso := "ahg", value := .ovAndPostpositions }
  , { walsCode := "ken", iso := "kyq", value := .other }
  , { walsCode := "ker", iso := "ker", value := .voAndPrepositions }
  , { walsCode := "ksa", iso := "kee", value := .ovAndPostpositions }
  , { walsCode := "ket", iso := "ket", value := .ovAndPostpositions }
  , { walsCode := "kte", iso := "kcv", value := .voAndPrepositions }
  , { walsCode := "kew", iso := "kew", value := .ovAndPostpositions }
  , { walsCode := "khl", iso := "klj", value := .ovAndPostpositions }
  , { walsCode := "kha", iso := "khk", value := .ovAndPostpositions }
  , { walsCode := "kmh", iso := "kjl", value := .ovAndPostpositions }
  , { walsCode := "khd", iso := "khg", value := .ovAndPostpositions }
  , { walsCode := "knz", iso := "khg", value := .ovAndPostpositions }
  , { walsCode := "kty", iso := "kca", value := .ovAndPostpositions }
  , { walsCode := "khr", iso := "khr", value := .ovAndPostpositions }
  , { walsCode := "khs", iso := "kha", value := .voAndPrepositions }
  , { walsCode := "khm", iso := "khm", value := .voAndPrepositions }
  , { walsCode := "kmu", iso := "kjg", value := .voAndPrepositions }
  , { walsCode := "khw", iso := "khw", value := .ovAndPostpositions }
  , { walsCode := "kik", iso := "kik", value := .voAndPrepositions }
  , { walsCode := "klv", iso := "kij", value := .voAndPrepositions }
  , { walsCode := "kil", iso := "lub", value := .voAndPrepositions }
  , { walsCode := "kim", iso := "kig", value := .ovAndPostpositions }
  , { walsCode := "kga", iso := "zga", value := .voAndPrepositions }
  , { walsCode := "knn", iso := "kfk", value := .ovAndPostpositions }
  , { walsCode := "kin", iso := "kin", value := .voAndPrepositions }
  , { walsCode := "kri", iso := "kzw", value := .voAndPrepositions }
  , { walsCode := "kie", iso := "geb", value := .ovAndPostpositions }
  , { walsCode := "krb", iso := "gil", value := .voAndPrepositions }
  , { walsCode := "kir", iso := "cme", value := .voAndPostpositions }
  , { walsCode := "kis", iso := "kss", value := .other }
  , { walsCode := "kiw", iso := "kjd", value := .ovAndPostpositions }
  , { walsCode := "klm", iso := "kla", value := .other }
  , { walsCode := "koa", iso := "cku", value := .ovAndPostpositions }
  , { walsCode := "kob", iso := "kpw", value := .ovAndPostpositions }
  , { walsCode := "koe", iso := "xwg", value := .voAndPrepositions }
  , { walsCode := "kmo", iso := "kpx", value := .ovAndPostpositions }
  ]

private def allData_1 : List (Datapoint RelationshipBetweenTheOrderOfObjectAndVerbAndTheOrderOfAdpositionAndNounPhrase) :=
  [ { walsCode := "kok", iso := "trp", value := .ovAndPostpositions }
  , { walsCode := "kkt", iso := "kkk", value := .voAndPrepositions }
  , { walsCode := "kol", iso := "kfb", value := .ovAndPostpositions }
  , { walsCode := "klr", iso := "shm", value := .ovAndPostpositions }
  , { walsCode := "kmb", iso := "", value := .ovAndPostpositions }
  , { walsCode := "xbi", iso := "xbi", value := .voAndPrepositions }
  , { walsCode := "kop", iso := "koi", value := .ovAndPostpositions }
  , { walsCode := "kzy", iso := "kpv", value := .voAndPostpositions }
  , { walsCode := "kon", iso := "kng", value := .voAndPrepositions }
  , { walsCode := "kni", iso := "kma", value := .other }
  , { walsCode := "krn", iso := "kqz", value := .ovAndPostpositions }
  , { walsCode := "kor", iso := "kor", value := .ovAndPostpositions }
  , { walsCode := "kje", iso := "coe", value := .voAndPostpositions }
  , { walsCode := "kku", iso := "kfq", value := .ovAndPostpositions }
  , { walsCode := "kfe", iso := "kfz", value := .other }
  , { walsCode := "kry", iso := "kpy", value := .ovAndPostpositions }
  , { walsCode := "kos", iso := "kos", value := .voAndPrepositions }
  , { walsCode := "kch", iso := "khq", value := .voAndPostpositions }
  , { walsCode := "kse", iso := "ses", value := .ovAndPostpositions }
  , { walsCode := "kyn", iso := "koy", value := .ovAndPostpositions }
  , { walsCode := "krh", iso := "xra", value := .ovAndPostpositions }
  , { walsCode := "kre", iso := "krs", value := .voAndPrepositions }
  , { walsCode := "knc", iso := "uwa", value := .ovAndPostpositions }
  , { walsCode := "kkq", iso := "kui", value := .ovAndPostpositions }
  , { walsCode := "kya", iso := "gvn", value := .ovAndPrepositions }
  , { walsCode := "kmn", iso := "kue", value := .ovAndPostpositions }
  , { walsCode := "kum", iso := "kfy", value := .ovAndPostpositions }
  , { walsCode := "kun", iso := "kvn", value := .ovAndPostpositions }
  , { walsCode := "knm", iso := "kun", value := .ovAndPostpositions }
  , { walsCode := "kuo", iso := "kto", value := .voAndPrepositions }
  , { walsCode := "krd", iso := "ckb", value := .ovAndPrepositions }
  , { walsCode := "kus", iso := "kgg", value := .ovAndPostpositions }
  , { walsCode := "thy", iso := "thd", value := .other }
  , { walsCode := "kuv", iso := "kxv", value := .ovAndPostpositions }
  , { walsCode := "kwa", iso := "kwd", value := .voAndPrepositions }
  , { walsCode := "kwk", iso := "kwk", value := .voAndPrepositions }
  , { walsCode := "kwn", iso := "kwn", value := .voAndPrepositions }
  , { walsCode := "kwb", iso := "kwe", value := .ovAndPostpositions }
  , { walsCode := "kwo", iso := "kmo", value := .ovAndPostpositions }
  , { walsCode := "kwt", iso := "kwo", value := .ovAndPostpositions }
  , { walsCode := "kxo", iso := "xuu", value := .ovAndPostpositions }
  , { walsCode := "kyk", iso := "kyc", value := .ovAndPostpositions }
  , { walsCode := "kgy", iso := "kgy", value := .ovAndPostpositions }
  , { walsCode := "kyq", iso := "nuk", value := .voAndPrepositions }
  , { walsCode := "laa", iso := "gdm", value := .voAndPrepositions }
  , { walsCode := "lab", iso := "lbu", value := .voAndPrepositions }
  , { walsCode := "lac", iso := "lac", value := .voAndPrepositions }
  , { walsCode := "lad", iso := "lbj", value := .ovAndPostpositions }
  , { walsCode := "lag", iso := "kot", value := .voAndPrepositions }
  , { walsCode := "lah", iso := "lhu", value := .ovAndPostpositions }
  , { walsCode := "lai", iso := "cnh", value := .ovAndPostpositions }
  , { walsCode := "lak", iso := "lbe", value := .ovAndPostpositions }
  , { walsCode := "lkt", iso := "lkt", value := .ovAndPostpositions }
  , { walsCode := "lal", iso := "ywt", value := .ovAndPostpositions }
  , { walsCode := "lmh", iso := "slp", value := .other }
  , { walsCode := "lmg", iso := "hia", value := .voAndPrepositions }
  , { walsCode := "lmn", iso := "lmn", value := .ovAndPostpositions }
  , { walsCode := "lmp", iso := "ljp", value := .voAndPrepositions }
  , { walsCode := "lgi", iso := "lag", value := .voAndPrepositions }
  , { walsCode := "lan", iso := "laj", value := .voAndPrepositions }
  , { walsCode := "lao", iso := "lao", value := .voAndPrepositions }
  , { walsCode := "lar", iso := "lrg", value := .ovAndPostpositions }
  , { walsCode := "lat", iso := "lav", value := .voAndPrepositions }
  , { walsCode := "lav", iso := "lvk", value := .ovAndPostpositions }
  , { walsCode := "leb", iso := "agh", value := .voAndPrepositions }
  , { walsCode := "lec", iso := "lec", value := .other }
  , { walsCode := "lel", iso := "lln", value := .voAndPrepositions }
  , { walsCode := "llm", iso := "lef", value := .voAndPostpositions }
  , { walsCode := "len", iso := "tnl", value := .voAndPrepositions }
  , { walsCode := "ldu", iso := "led", value := .other }
  , { walsCode := "lep", iso := "lep", value := .ovAndPostpositions }
  , { walsCode := "les", iso := "les", value := .other }
  , { walsCode := "let", iso := "lti", value := .voAndPrepositions }
  , { walsCode := "lew", iso := "lww", value := .voAndPrepositions }
  , { walsCode := "lez", iso := "lez", value := .ovAndPostpositions }
  , { walsCode := "lho", iso := "lhm", value := .ovAndPostpositions }
  , { walsCode := "lil", iso := "lil", value := .voAndPrepositions }
  , { walsCode := "lml", iso := "lmc", value := .other }
  , { walsCode := "lnd", iso := "liy", value := .voAndPrepositions }
  , { walsCode := "lis", iso := "lis", value := .ovAndPostpositions }
  , { walsCode := "lit", iso := "lit", value := .voAndPrepositions }
  , { walsCode := "lgt", iso := "log", value := .other }
  , { walsCode := "ara", iso := "arw", value := .voAndPostpositions }
  , { walsCode := "ldo", iso := "bdu", value := .voAndPrepositions }
  , { walsCode := "lgu", iso := "lgu", value := .voAndPrepositions }
  , { walsCode := "lon", iso := "los", value := .voAndPrepositions }
  , { walsCode := "lot", iso := "njh", value := .ovAndPostpositions }
  , { walsCode := "lou", iso := "loj", value := .voAndPrepositions }
  , { walsCode := "lug", iso := "lgg", value := .other }
  , { walsCode := "lui", iso := "lui", value := .other }
  , { walsCode := "lbu", iso := "lun", value := .voAndPrepositions }
  , { walsCode := "lun", iso := "nst", value := .ovAndPostpositions }
  , { walsCode := "luo", iso := "luo", value := .voAndPrepositions }
  , { walsCode := "kkv", iso := "khl", value := .voAndPrepositions }
  , { walsCode := "luv", iso := "lue", value := .voAndPrepositions }
  , { walsCode := "mad", iso := "mhi", value := .other }
  , { walsCode := "maa", iso := "mas", value := .voAndPrepositions }
  , { walsCode := "mab", iso := "mde", value := .ovAndPostpositions }
  , { walsCode := "mcd", iso := "mkd", value := .voAndPrepositions }
  , { walsCode := "mac", iso := "mbc", value := .ovAndPostpositions }
  , { walsCode := "mdm", iso := "dmd", value := .voAndPrepositions }
  , { walsCode := "mae", iso := "mmw", value := .voAndPrepositions }
  , { walsCode := "mgh", iso := "mag", value := .ovAndPostpositions }
  , { walsCode := "mag", iso := "mgp", value := .ovAndPostpositions }
  , { walsCode := "mgi", iso := "mgu", value := .ovAndPostpositions }
  , { walsCode := "mpr", iso := "", value := .voAndPostpositions }
  , { walsCode := "msn", iso := "mbq", value := .ovAndPostpositions }
  , { walsCode := "mai", iso := "mai", value := .ovAndPostpositions }
  , { walsCode := "maj", iso := "mpe", value := .voAndPostpositions }
  , { walsCode := "mak", iso := "myh", value := .other }
  , { walsCode := "mkj", iso := "mkz", value := .ovAndPostpositions }
  , { walsCode := "mkl", iso := "mgf", value := .ovAndPostpositions }
  , { walsCode := "mua", iso := "mgh", value := .voAndPrepositions }
  , { walsCode := "mal", iso := "plt", value := .voAndPrepositions }
  , { walsCode := "mlu", iso := "mgl", value := .voAndPrepositions }
  , { walsCode := "mlg", iso := "", value := .voAndPrepositions }
  , { walsCode := "mam", iso := "mam", value := .voAndPrepositions }
  , { walsCode := "mmn", iso := "mmn", value := .voAndPrepositions }
  , { walsCode := "mds", iso := "xmm", value := .voAndPrepositions }
  , { walsCode := "mnm", iso := "mva", value := .ovAndPostpositions }
  , { walsCode := "mnc", iso := "mnc", value := .ovAndPostpositions }
  , { walsCode := "mdn", iso := "mhq", value := .ovAndPostpositions }
  , { walsCode := "mnd", iso := "cmn", value := .other }
  , { walsCode := "mkg", iso := "mnk", value := .ovAndPostpositions }
  , { walsCode := "mmb", iso := "mna", value := .voAndPrepositions }
  , { walsCode := "myi", iso := "mpc", value := .ovAndPrepositions }
  , { walsCode := "mng", iso := "mqy", value := .voAndPrepositions }
  , { walsCode := "mgg", iso := "mjg", value := .ovAndPostpositions }
  , { walsCode := "maw", iso := "mlq", value := .ovAndPostpositions }
  , { walsCode := "man", iso := "mev", value := .ovAndPostpositions }
  , { walsCode := "mwb", iso := "mbb", value := .voAndPrepositions }
  , { walsCode := "mns", iso := "mns", value := .ovAndPostpositions }
  , { walsCode := "mao", iso := "mri", value := .voAndPrepositions }
  , { walsCode := "map", iso := "arn", value := .other }
  , { walsCode := "mra", iso := "mec", value := .other }
  , { walsCode := "mku", iso := "zmr", value := .ovAndPostpositions }
  , { walsCode := "mhi", iso := "mar", value := .ovAndPostpositions }
  , { walsCode := "mrg", iso := "mrt", value := .voAndPrepositions }
  , { walsCode := "mme", iso := "mhr", value := .ovAndPostpositions }
  , { walsCode := "mar", iso := "mrc", value := .ovAndPostpositions }
  , { walsCode := "mrd", iso := "mrz", value := .ovAndPostpositions }
  , { walsCode := "mrq", iso := "", value := .voAndPrepositions }
  , { walsCode := "mrh", iso := "mfr", value := .ovAndPostpositions }
  , { walsCode := "mru", iso := "mhx", value := .ovAndPostpositions }
  , { walsCode := "mas", iso := "mcn", value := .voAndPrepositions }
  , { walsCode := "mtt", iso := "wam", value := .other }
  , { walsCode := "mdl", iso := "zml", value := .ovAndPostpositions }
  , { walsCode := "myr", iso := "mcf", value := .ovAndPostpositions }
  , { walsCode := "mka", iso := "mxx", value := .ovAndPostpositions }
  , { walsCode := "mau", iso := "mph", value := .voAndPrepositions }
  , { walsCode := "max", iso := "mbl", value := .ovAndPostpositions }
  , { walsCode := "may", iso := "ayz", value := .voAndPrepositions }
  , { walsCode := "myg", iso := "mdm", value := .voAndPrepositions }
  , { walsCode := "mzh", iso := "mau", value := .other }
  , { walsCode := "mbr", iso := "mpk", value := .other }
  , { walsCode := "mby", iso := "myb", value := .other }
  , { walsCode := "mbe", iso := "mdt", value := .voAndPrepositions }
  , { walsCode := "mdo", iso := "gmm", value := .voAndPrepositions }
  , { walsCode := "mbm", iso := "mdd", value := .voAndPrepositions }
  , { walsCode := "meh", iso := "gdq", value := .voAndPrepositions }
  , { walsCode := "mei", iso := "mni", value := .ovAndPostpositions }
  , { walsCode := "mek", iso := "skf", value := .ovAndPostpositions }
  , { walsCode := "mke", iso := "mek", value := .ovAndPostpositions }
  , { walsCode := "mde", iso := "men", value := .ovAndPostpositions }
  , { walsCode := "men", iso := "mez", value := .other }
  , { walsCode := "mey", iso := "mcr", value := .ovAndPostpositions }
  , { walsCode := "mea", iso := "mej", value := .voAndPrepositions }
  , { walsCode := "mpt", iso := "mpt", value := .ovAndPostpositions }
  , { walsCode := "mik", iso := "mjw", value := .ovAndPostpositions }
  , { walsCode := "hna", iso := "hna", value := .voAndPrepositions }
  , { walsCode := "min", iso := "min", value := .other }
  , { walsCode := "mnv", iso := "mvn", value := .ovAndPostpositions }
  , { walsCode := "msg", iso := "mrg", value := .ovAndPostpositions }
  , { walsCode := "mis", iso := "miq", value := .ovAndPostpositions }
  , { walsCode := "mss", iso := "skd", value := .other }
  , { walsCode := "mxx", iso := "mxp", value := .other }
  , { walsCode := "mxc", iso := "mig", value := .voAndPrepositions }
  , { walsCode := "mxj", iso := "mio", value := .voAndPrepositions }
  , { walsCode := "mxo", iso := "mie", value := .voAndPrepositions }
  , { walsCode := "mxp", iso := "mil", value := .voAndPrepositions }
  , { walsCode := "mxy", iso := "mpm", value := .voAndPrepositions }
  , { walsCode := "miy", iso := "mkf", value := .voAndPrepositions }
  , { walsCode := "miz", iso := "lus", value := .ovAndPostpositions }
  , { walsCode := "mlm", iso := "mra", value := .voAndPrepositions }
  , { walsCode := "mof", iso := "mif", value := .voAndPrepositions }
  , { walsCode := "moh", iso := "moh", value := .other }
  , { walsCode := "mok", iso := "mkj", value := .voAndPrepositions }
  , { walsCode := "mom", iso := "mso", value := .ovAndPostpositions }
  , { walsCode := "fqs", iso := "fqs", value := .ovAndPostpositions }
  , { walsCode := "mqf", iso := "mqf", value := .ovAndPostpositions }
  , { walsCode := "mon", iso := "mnw", value := .voAndPrepositions }
  , { walsCode := "mga", iso := "ndt", value := .voAndPrepositions }
  , { walsCode := "mgo", iso := "lol", value := .voAndPrepositions }
  , { walsCode := "mno", iso := "mnr", value := .ovAndPostpositions }
  , { walsCode := "moa", iso := "mte", value := .other }
  , { walsCode := "mbo", iso := "mxk", value := .ovAndPostpositions }
  , { walsCode := "moo", iso := "mos", value := .other }
  , { walsCode := "mor", iso := "mhz", value := .voAndPrepositions }
  , { walsCode := "mri", iso := "mok", value := .ovAndPostpositions }
  , { walsCode := "moe", iso := "myv", value := .voAndPostpositions }
  , { walsCode := "mro", iso := "mor", value := .other }
  , { walsCode := "mou", iso := "mgd", value := .other }
  , { walsCode := "mtu", iso := "meu", value := .ovAndPostpositions }
  , { walsCode := "mov", iso := "mzp", value := .voAndPrepositions }
  , { walsCode := "mpu", iso := "akc", value := .voAndPrepositions }
  , { walsCode := "mum", iso := "mzm", value := .voAndPrepositions }
  , { walsCode := "mna", iso := "mnb", value := .voAndPrepositions }
  , { walsCode := "mdg", iso := "mua", value := .voAndPrepositions }
  , { walsCode := "mun", iso := "unr", value := .ovAndPostpositions }
  , { walsCode := "muu", iso := "myu", value := .ovAndPostpositions }
  , { walsCode := "mup", iso := "sur", value := .voAndPrepositions }
  , { walsCode := "mrl", iso := "mur", value := .other }
  , { walsCode := "mpa", iso := "mwf", value := .other }
  , { walsCode := "mrw", iso := "zmu", value := .other }
  , { walsCode := "mgu", iso := "mug", value := .voAndPrepositions }
  , { walsCode := "msm", iso := "msu", value := .voAndPrepositions }
  , { walsCode := "msq", iso := "hur", value := .voAndPrepositions }
  , { walsCode := "mus", iso := "emi", value := .voAndPrepositions }
  , { walsCode := "nab", iso := "naf", value := .ovAndPostpositions }
  , { walsCode := "nad", iso := "mbj", value := .ovAndPostpositions }
  , { walsCode := "nze", iso := "nzm", value := .ovAndPostpositions }
  , { walsCode := "nag", iso := "nce", value := .ovAndPostpositions }
  , { walsCode := "nhh", iso := "", value := .voAndPrepositions }
  , { walsCode := "nhm", iso := "ncl", value := .voAndPrepositions }
  , { walsCode := "nht", iso := "nhg", value := .voAndPrepositions }
  , { walsCode := "nak", iso := "nak", value := .voAndPrepositions }
  , { walsCode := "nal", iso := "nal", value := .voAndPrepositions }
  , { walsCode := "kho", iso := "naq", value := .ovAndPostpositions }
  , { walsCode := "nam", iso := "nnm", value := .ovAndPostpositions }
  , { walsCode := "nnc", iso := "ncb", value := .voAndPrepositions }
  , { walsCode := "nan", iso := "niq", value := .voAndPrepositions }
  , { walsCode := "nnk", iso := "nnk", value := .ovAndPostpositions }
  , { walsCode := "nph", iso := "npa", value := .ovAndPostpositions }
  , { walsCode := "nar", iso := "nrb", value := .ovAndPostpositions }
  , { walsCode := "nas", iso := "nas", value := .ovAndPostpositions }
  , { walsCode := "nat", iso := "ncz", value := .ovAndPostpositions }
  , { walsCode := "nav", iso := "nav", value := .ovAndPostpositions }
  , { walsCode := "ncm", iso := "bud", value := .other }
  , { walsCode := "ndj", iso := "djj", value := .ovAndPostpositions }
  , { walsCode := "ndo", iso := "ndo", value := .voAndPrepositions }
  , { walsCode := "ndu", iso := "nmd", value := .voAndPrepositions }
  , { walsCode := "ndt", iso := "ndv", value := .voAndPrepositions }
  , { walsCode := "ndy", iso := "djk", value := .voAndPrepositions }
  , { walsCode := "neh", iso := "nsn", value := .voAndPrepositions }
  , { walsCode := "nnd", iso := "anh", value := .ovAndPostpositions }
  , { walsCode := "ntu", iso := "yrk", value := .ovAndPostpositions }
  , { walsCode := "naj", iso := "aij", value := .ovAndPrepositions }
  , { walsCode := "nep", iso := "npi", value := .ovAndPostpositions }
  , { walsCode := "nev", iso := "pia", value := .ovAndPostpositions }
  , { walsCode := "nwd", iso := "new", value := .ovAndPostpositions }
  , { walsCode := "new", iso := "new", value := .ovAndPostpositions }
  , { walsCode := "ney", iso := "ney", value := .other }
  , { walsCode := "nez", iso := "nez", value := .other }
  , { walsCode := "ntj", iso := "ntj", value := .ovAndPostpositions }
  , { walsCode := "ngd", iso := "nxg", value := .voAndPrepositions }
  , { walsCode := "ngl", iso := "nig", value := .other }
  , { walsCode := "ngm", iso := "sba", value := .voAndPrepositions }
  , { walsCode := "ngg", iso := "nam", value := .ovAndPostpositions }
  , { walsCode := "ngk", iso := "nam", value := .other }
  , { walsCode := "ngb", iso := "nga", value := .voAndPrepositions }
  , { walsCode := "ndi", iso := "ngb", value := .voAndPrepositions }
  , { walsCode := "nti", iso := "niy", value := .other }
  , { walsCode := "ngz", iso := "ngi", value := .voAndPrepositions }
  , { walsCode := "ngo", iso := "ngo", value := .voAndPrepositions }
  , { walsCode := "ngu", iso := "llp", value := .voAndPrepositions }
  , { walsCode := "nbr", iso := "gym", value := .ovAndPostpositions }
  , { walsCode := "nha", iso := "nha", value := .other }
  , { walsCode := "nia", iso := "nia", value := .voAndPrepositions }
  , { walsCode := "nca", iso := "caq", value := .voAndPrepositions }
  , { walsCode := "nsg", iso := "ncg", value := .voAndPrepositions }
  , { walsCode := "nif", iso := "num", value := .voAndPrepositions }
  , { walsCode := "niu", iso := "niu", value := .voAndPrepositions }
  , { walsCode := "niv", iso := "niv", value := .ovAndPostpositions }
  , { walsCode := "nkn", iso := "nko", value := .voAndPostpositions }
  , { walsCode := "nko", iso := "cgg", value := .voAndPrepositions }
  , { walsCode := "noc", iso := "njb", value := .ovAndPostpositions }
  , { walsCode := "non", iso := "nhu", value := .other }
  , { walsCode := "noo", iso := "snf", value := .voAndPrepositions }
  , { walsCode := "nor", iso := "nor", value := .voAndPrepositions }
  , { walsCode := "nse", iso := "nse", value := .voAndPrepositions }
  , { walsCode := "nua", iso := "nxl", value := .voAndPrepositions }
  , { walsCode := "nbd", iso := "dgl", value := .ovAndPostpositions }
  , { walsCode := "nue", iso := "nus", value := .other }
  , { walsCode := "nun", iso := "nut", value := .voAndPrepositions }
  , { walsCode := "nug", iso := "nuy", value := .other }
  , { walsCode := "yi", iso := "iii", value := .ovAndPostpositions }
  , { walsCode := "nup", iso := "nup", value := .voAndPrepositions }
  , { walsCode := "nyr", iso := "nna", value := .other }
  , { walsCode := "nyi", iso := "nyi", value := .ovAndPostpositions }
  , { walsCode := "nis", iso := "njz", value := .ovAndPostpositions }
  , { walsCode := "nyu", iso := "nyv", value := .other }
  , { walsCode := "nza", iso := "nzk", value := .voAndPrepositions }
  , { walsCode := "ood", iso := "ood", value := .other }
  , { walsCode := "obo", iso := "ann", value := .voAndPrepositions }
  , { walsCode := "ocu", iso := "ocu", value := .voAndPrepositions }
  , { walsCode := "obg", iso := "ogu", value := .voAndPrepositions }
  , { walsCode := "oks", iso := "opm", value := .ovAndPostpositions }
  , { walsCode := "olo", iso := "ong", value := .voAndPrepositions }
  , { walsCode := "ork", iso := "oaa", value := .ovAndPostpositions }
  , { walsCode := "oro", iso := "okv", value := .ovAndPostpositions }
  , { walsCode := "orh", iso := "hae", value := .ovAndPostpositions }
  , { walsCode := "orw", iso := "ssn", value := .ovAndPostpositions }
  , { walsCode := "ory", iso := "ury", value := .ovAndPostpositions }
  , { walsCode := "osa", iso := "osa", value := .ovAndPostpositions }
  , { walsCode := "oss", iso := "oss", value := .ovAndPostpositions }
  , { walsCode := "otm", iso := "ote", value := .voAndPrepositions }
  , { walsCode := "owi", iso := "owi", value := .ovAndPostpositions }
  , { walsCode := "paa", iso := "pqa", value := .voAndPrepositions }
  , { walsCode := "pms", iso := "pma", value := .voAndPrepositions }
  , { walsCode := "pno", iso := "pao", value := .other }
  , { walsCode := "pai", iso := "pwn", value := .voAndPrepositions }
  , { walsCode := "pal", iso := "pau", value := .voAndPrepositions }
  , { walsCode := "plg", iso := "pll", value := .voAndPrepositions }
  , { walsCode := "plk", iso := "plu", value := .voAndPrepositions }
  , { walsCode := "pnx", iso := "kre", value := .other }
  , { walsCode := "pnn", iso := "pag", value := .voAndPrepositions }
  , { walsCode := "png", iso := "pbr", value := .voAndPrepositions }
  , { walsCode := "pan", iso := "pan", value := .ovAndPostpositions }
  , { walsCode := "pny", iso := "pnw", value := .other }
  , { walsCode := "pre", iso := "asa", value := .voAndPrepositions }
  , { walsCode := "psh", iso := "pst", value := .ovAndPostpositions }
  , { walsCode := "psm", iso := "pqm", value := .voAndPrepositions }
  , { walsCode := "pat", iso := "ptp", value := .voAndPrepositions }
  , { walsCode := "ptt", iso := "lae", value := .ovAndPostpositions }
  , { walsCode := "ptw", iso := "pwi", value := .ovAndPostpositions }
  , { walsCode := "plh", iso := "plh", value := .voAndPrepositions }
  , { walsCode := "pau", iso := "pad", value := .other }
  , { walsCode := "paw", iso := "pwa", value := .ovAndPostpositions }
  , { walsCode := "per", iso := "pip", value := .voAndPrepositions }
  , { walsCode := "prs", iso := "pes", value := .ovAndPrepositions }
  , { walsCode := "pip", iso := "ppl", value := .voAndPrepositions }
  , { walsCode := "prh", iso := "myp", value := .ovAndPostpositions }
  , { walsCode := "pis", iso := "psa", value := .ovAndPostpositions }
  , { walsCode := "pit", iso := "pjt", value := .ovAndPostpositions }
  , { walsCode := "ppi", iso := "pit", value := .other }
  , { walsCode := "pod", iso := "pbi", value := .voAndPrepositions }
  , { walsCode := "pog", iso := "poy", value := .voAndPrepositions }
  , { walsCode := "poh", iso := "pon", value := .voAndPrepositions }
  , { walsCode := "pok", iso := "rwa", value := .other }
  , { walsCode := "pkt", iso := "pko", value := .voAndPrepositions }
  , { walsCode := "pol", iso := "pol", value := .voAndPrepositions }
  , { walsCode := "pmn", iso := "pej", value := .ovAndPostpositions }
  , { walsCode := "pso", iso := "pom", value := .ovAndPostpositions }
  , { walsCode := "zqs", iso := "poi", value := .voAndPrepositions }
  , { walsCode := "psw", iso := "psw", value := .voAndPrepositions }
  , { walsCode := "por", iso := "por", value := .voAndPrepositions }
  , { walsCode := "pra", iso := "prn", value := .ovAndPostpositions }
  , { walsCode := "pul", iso := "puw", value := .voAndPrepositions }
  , { walsCode := "pun", iso := "wdj", value := .ovAndPostpositions }
  , { walsCode := "prk", iso := "prx", value := .ovAndPostpositions }
  , { walsCode := "pur", iso := "tsz", value := .other }
  , { walsCode := "pae", iso := "pbb", value := .ovAndPostpositions }
  , { walsCode := "par", iso := "lkr", value := .ovAndPrepositions }
  , { walsCode := "qaf", iso := "aar", value := .ovAndPostpositions }
  , { walsCode := "qaw", iso := "alc", value := .ovAndPostpositions }
  , { walsCode := "qhu", iso := "qub", value := .ovAndPostpositions }
  , { walsCode := "qim", iso := "qvi", value := .ovAndPostpositions }
  , { walsCode := "rag", iso := "lml", value := .voAndPrepositions }
  , { walsCode := "ram", iso := "rma", value := .ovAndPostpositions }
  , { walsCode := "rap", iso := "rap", value := .voAndPrepositions }
  , { walsCode := "raw", iso := "raw", value := .ovAndPostpositions }
  , { walsCode := "rem", iso := "bfw", value := .ovAndPostpositions }
  , { walsCode := "res", iso := "rgr", value := .ovAndPostpositions }
  , { walsCode := "ret", iso := "tnc", value := .ovAndPostpositions }
  , { walsCode := "rik", iso := "rkb", value := .ovAndPostpositions }
  , { walsCode := "rit", iso := "rit", value := .other }
  , { walsCode := "rwe", iso := "rmw", value := .voAndPrepositions }
  , { walsCode := "rom", iso := "ron", value := .voAndPrepositions }
  , { walsCode := "rga", iso := "rng", value := .voAndPrepositions }
  , { walsCode := "rot", iso := "rtm", value := .voAndPrepositions }
  , { walsCode := "ruk", iso := "dru", value := .voAndPrepositions }
  , { walsCode := "rum", iso := "klq", value := .ovAndPostpositions }
  , { walsCode := "run", iso := "rou", value := .ovAndPostpositions }
  , { walsCode := "rny", iso := "nyn", value := .voAndPrepositions }
  , { walsCode := "rus", iso := "rus", value := .voAndPrepositions }
  , { walsCode := "rut", iso := "rut", value := .ovAndPostpositions }
  , { walsCode := "sno", iso := "sme", value := .voAndPostpositions }
  , { walsCode := "sah", iso := "saj", value := .voAndPrepositions }
  , { walsCode := "sak", iso := "sku", value := .voAndPrepositions }
  , { walsCode := "slb", iso := "sbe", value := .ovAndPostpositions }
  , { walsCode := "sal", iso := "sln", value := .voAndPrepositions }
  , { walsCode := "syu", iso := "sll", value := .ovAndPostpositions }
  , { walsCode := "sle", iso := "ndi", value := .voAndPostpositions }
  , { walsCode := "sam", iso := "smo", value := .voAndPrepositions }
  , { walsCode := "sdw", iso := "sad", value := .ovAndPostpositions }
  , { walsCode := "san", iso := "sag", value := .voAndPrepositions }
  , { walsCode := "sta", iso := "sce", value := .ovAndPostpositions }
  , { walsCode := "stl", iso := "sat", value := .ovAndPostpositions }
  , { walsCode := "snm", iso := "xsu", value := .ovAndPostpositions }
  , { walsCode := "src", iso := "srs", value := .ovAndPostpositions }
  , { walsCode := "sar", iso := "dju", value := .ovAndPostpositions }
  , { walsCode := "sav", iso := "sdg", value := .ovAndPostpositions }
  , { walsCode := "svs", iso := "svs", value := .ovAndPostpositions }
  , { walsCode := "seb", iso := "kpz", value := .voAndPrepositions }
  , { walsCode := "sed", iso := "sed", value := .voAndPrepositions }
  , { walsCode := "sel", iso := "ona", value := .ovAndPostpositions }
  , { walsCode := "sem", iso := "nsm", value := .ovAndPostpositions }
  , { walsCode := "sme", iso := "sif", value := .ovAndPostpositions }
  , { walsCode := "sml", iso := "sza", value := .voAndPrepositions }
  , { walsCode := "smn", iso := "mus", value := .ovAndPostpositions }
  , { walsCode := "snc", iso := "see", value := .other }
  , { walsCode := "sgl", iso := "szg", value := .voAndPrepositions }
  , { walsCode := "snt", iso := "set", value := .ovAndPostpositions }
  , { walsCode := "scr", iso := "hbs", value := .voAndPrepositions }
  , { walsCode := "ser", iso := "sei", value := .ovAndPostpositions }
  , { walsCode := "ses", iso := "sot", value := .voAndPrepositions }
  , { walsCode := "shb", iso := "sbf", value := .ovAndPostpositions }
  , { walsCode := "shh", iso := "mcd", value := .ovAndPostpositions }
  , { walsCode := "skw", iso := "swv", value := .ovAndPostpositions }
  , { walsCode := "she", iso := "xsr", value := .ovAndPostpositions }
  , { walsCode := "shl", iso := "shk", value := .voAndPrepositions }
  , { walsCode := "sna", iso := "scl", value := .ovAndPostpositions }
  , { walsCode := "shk", iso := "shp", value := .ovAndPostpositions }
  , { walsCode := "shi", iso := "shb", value := .ovAndPostpositions }
  , { walsCode := "shn", iso := "sna", value := .voAndPrepositions }
  , { walsCode := "ryu", iso := "ryu", value := .ovAndPostpositions }
  , { walsCode := "shu", iso := "shs", value := .voAndPrepositions }
  , { walsCode := "sir", iso := "sjr", value := .voAndPrepositions }
  , { walsCode := "sid", iso := "sid", value := .ovAndPostpositions }
  , { walsCode := "skk", iso := "sip", value := .ovAndPostpositions }
  , { walsCode := "sim", iso := "smr", value := .voAndPrepositions }
  , { walsCode := "sng", iso := "snc", value := .ovAndPostpositions }
  , { walsCode := "snh", iso := "sin", value := .ovAndPostpositions }
  , { walsCode := "sio", iso := "xsi", value := .voAndPrepositions }
  , { walsCode := "qum", iso := "qum", value := .voAndPrepositions }
  , { walsCode := "srn", iso := "srq", value := .ovAndPostpositions }
  , { walsCode := "sro", iso := "ssd", value := .ovAndPostpositions }
  , { walsCode := "sis", iso := "baa", value := .voAndPrepositions }
  , { walsCode := "sko", iso := "skv", value := .ovAndPostpositions }
  , { walsCode := "sla", iso := "den", value := .ovAndPostpositions }
  , { walsCode := "slo", iso := "slv", value := .voAndPrepositions }
  , { walsCode := "so", iso := "teu", value := .voAndPrepositions }
  , { walsCode := "sob", iso := "sob", value := .voAndPrepositions }
  , { walsCode := "sod", iso := "gru", value := .other }
  , { walsCode := "som", iso := "som", value := .other }
  , { walsCode := "son", iso := "sov", value := .voAndPrepositions }
  , { walsCode := "srb", iso := "", value := .ovAndPrepositions }
  , { walsCode := "sgb", iso := "mnx", value := .voAndPrepositions }
  , { walsCode := "tou", iso := "wib", value := .ovAndPostpositions }
  , { walsCode := "spa", iso := "spa", value := .voAndPrepositions }
  , { walsCode := "squ", iso := "squ", value := .voAndPrepositions }
  , { walsCode := "sre", iso := "kpm", value := .voAndPrepositions }
  , { walsCode := "sti", iso := "", value := .voAndPrepositions }
  , { walsCode := "sue", iso := "sue", value := .ovAndPostpositions }
  , { walsCode := "sul", iso := "sua", value := .voAndPrepositions }
  , { walsCode := "sun", iso := "sun", value := .voAndPrepositions }
  , { walsCode := "sup", iso := "spp", value := .ovAndPostpositions }
  , { walsCode := "sus", iso := "sus", value := .ovAndPostpositions }
  , { walsCode := "swa", iso := "swh", value := .voAndPrepositions }
  , { walsCode := "swe", iso := "swe", value := .voAndPrepositions }
  , { walsCode := "tab", iso := "mky", value := .voAndPrepositions }
  , { walsCode := "tbl", iso := "tnm", value := .ovAndPostpositions }
  , { walsCode := "tbw", iso := "tap", value := .voAndPrepositions }
  , { walsCode := "tac", iso := "tna", value := .ovAndPostpositions }
  , { walsCode := "tah", iso := "tah", value := .voAndPrepositions }
  , { walsCode := "taj", iso := "tgk", value := .ovAndPrepositions }
  , { walsCode := "tkl", iso := "tkm", value := .ovAndPostpositions }
  , { walsCode := "tak", iso := "tbc", value := .ovAndPostpositions }
  , { walsCode := "tal", iso := "tlj", value := .voAndPrepositions }
  , { walsCode := "tls", iso := "shm", value := .ovAndPostpositions }
  , { walsCode := "tam", iso := "taj", value := .ovAndPostpositions }
  , { walsCode := "tsk", iso := "taq", value := .voAndPrepositions }
  , { walsCode := "tml", iso := "tam", value := .ovAndPostpositions }
  , { walsCode := "tnc", iso := "tcb", value := .ovAndPostpositions }
  , { walsCode := "tpt", iso := "tpj", value := .ovAndPrepositions }
  , { walsCode := "tce", iso := "tar", value := .ovAndPostpositions }
  , { walsCode := "twe", iso := "tac", value := .other }
  , { walsCode := "tar", iso := "tae", value := .ovAndPostpositions }
  , { walsCode := "tvo", iso := "tat", value := .ovAndPostpositions }
  , { walsCode := "tsr", iso := "trr", value := .voAndPostpositions }
  , { walsCode := "tsg", iso := "tsg", value := .voAndPrepositions }
  , { walsCode := "tau", iso := "tya", value := .ovAndPostpositions }
  , { walsCode := "taw", iso := "tbo", value := .other }
  , { walsCode := "tbo", iso := "tbl", value := .voAndPrepositions }
  , { walsCode := "tlf", iso := "tlf", value := .ovAndPostpositions }
  , { walsCode := "tel", iso := "tel", value := .ovAndPostpositions }
  , { walsCode := "tmr", iso := "tea", value := .voAndPrepositions }
  , { walsCode := "tne", iso := "tem", value := .voAndPrepositions }
  , { walsCode := "ten", iso := "tex", value := .other }
  , { walsCode := "tny", iso := "kza", value := .ovAndPostpositions }
  , { walsCode := "teo", iso := "tio", value := .voAndPrepositions }
  , { walsCode := "tee", iso := "tee", value := .voAndPrepositions }
  , { walsCode := "tep", iso := "tpt", value := .voAndPrepositions }
  , { walsCode := "tpn", iso := "ntp", value := .voAndPostpositions }
  , { walsCode := "tps", iso := "stp", value := .voAndPostpositions }
  , { walsCode := "ter", iso := "ttr", value := .voAndPrepositions }
  , { walsCode := "trb", iso := "tfr", value := .ovAndPostpositions }
  , { walsCode := "tes", iso := "teo", value := .voAndPrepositions }
  , { walsCode := "tet", iso := "tll", value := .voAndPrepositions }
  , { walsCode := "ttn", iso := "tet", value := .voAndPrepositions }
  , { walsCode := "ttd", iso := "tet", value := .voAndPrepositions }
  , { walsCode := "tha", iso := "tha", value := .voAndPrepositions }
  , { walsCode := "thn", iso := "thf", value := .ovAndPostpositions }
  , { walsCode := "tho", iso := "thp", value := .voAndPrepositions }
  , { walsCode := "thu", iso := "tdh", value := .ovAndPostpositions }
  , { walsCode := "tmo", iso := "bod", value := .ovAndPostpositions }
  , { walsCode := "tic", iso := "tca", value := .other }
  , { walsCode := "tid", iso := "tvo", value := .voAndPrepositions }
  , { walsCode := "tgk", iso := "tgc", value := .voAndPrepositions }
  , { walsCode := "tig", iso := "tir", value := .ovAndPrepositions }
  ]

private def allData_2 : List (Datapoint RelationshipBetweenTheOrderOfObjectAndVerbAndTheOrderOfAdpositionAndNounPhrase) :=
  [ { walsCode := "tgr", iso := "tig", value := .ovAndPrepositions }
  , { walsCode := "tja", iso := "dih", value := .ovAndPostpositions }
  , { walsCode := "tik", iso := "tik", value := .other }
  , { walsCode := "tim", iso := "tih", value := .voAndPrepositions }
  , { walsCode := "tin", iso := "cir", value := .voAndPrepositions }
  , { walsCode := "tir", iso := "tri", value := .ovAndPostpositions }
  , { walsCode := "trm", iso := "suq", value := .voAndPostpositions }
  , { walsCode := "tiv", iso := "tiv", value := .voAndPrepositions }
  , { walsCode := "twn", iso := "twf", value := .other }
  , { walsCode := "tiw", iso := "tiw", value := .voAndPrepositions }
  , { walsCode := "tlp", iso := "tcf", value := .voAndPrepositions }
  , { walsCode := "tli", iso := "tli", value := .ovAndPostpositions }
  , { walsCode := "tbt", iso := "tti", value := .ovAndPostpositions }
  , { walsCode := "tlo", iso := "tlb", value := .ovAndPrepositions }
  , { walsCode := "tke", iso := "tkl", value := .voAndPrepositions }
  , { walsCode := "tla", iso := "ksd", value := .voAndPrepositions }
  , { walsCode := "tno", iso := "tdn", value := .voAndPrepositions }
  , { walsCode := "tng", iso := "ton", value := .voAndPrepositions }
  , { walsCode := "ton", iso := "tqw", value := .ovAndPostpositions }
  , { walsCode := "trw", iso := "trw", value := .ovAndPostpositions }
  , { walsCode := "txj", iso := "too", value := .voAndPrepositions }
  , { walsCode := "tri", iso := "trc", value := .voAndPrepositions }
  , { walsCode := "tru", iso := "tpy", value := .other }
  , { walsCode := "tsf", iso := "cof", value := .ovAndPostpositions }
  , { walsCode := "tsz", iso := "ddo", value := .ovAndPostpositions }
  , { walsCode := "tgl", iso := "tsj", value := .ovAndPostpositions }
  , { walsCode := "tsi", iso := "tsi", value := .voAndPrepositions }
  , { walsCode := "ttu", iso := "bbl", value := .ovAndPostpositions }
  , { walsCode := "tai", iso := "thz", value := .voAndPrepositions }
  , { walsCode := "tgh", iso := "thv", value := .voAndPrepositions }
  , { walsCode := "tbu", iso := "", value := .ovAndPostpositions }
  , { walsCode := "tuc", iso := "tuo", value := .ovAndPostpositions }
  , { walsCode := "tuk", iso := "", value := .voAndPrepositions }
  , { walsCode := "tul", iso := "tcy", value := .ovAndPostpositions }
  , { walsCode := "tnn", iso := "tvu", value := .other }
  , { walsCode := "tnk", iso := "lcm", value := .voAndPrepositions }
  , { walsCode := "tun", iso := "tun", value := .ovAndPostpositions }
  , { walsCode := "tpr", iso := "tui", value := .voAndPrepositions }
  , { walsCode := "tna", iso := "tuv", value := .voAndPrepositions }
  , { walsCode := "tur", iso := "tur", value := .ovAndPostpositions }
  , { walsCode := "tkm", iso := "tuk", value := .ovAndPostpositions }
  , { walsCode := "tus", iso := "tus", value := .other }
  , { walsCode := "tte", iso := "tta", value := .ovAndPostpositions }
  , { walsCode := "tvt", iso := "tvt", value := .ovAndPostpositions }
  , { walsCode := "tvl", iso := "tvl", value := .ovAndPrepositions }
  , { walsCode := "tuv", iso := "tyv", value := .ovAndPostpositions }
  , { walsCode := "tuy", iso := "tue", value := .ovAndPostpositions }
  , { walsCode := "tzo", iso := "tzo", value := .voAndPrepositions }
  , { walsCode := "tzu", iso := "tzj", value := .voAndPrepositions }
  , { walsCode := "tsh", iso := "par", value := .other }
  , { walsCode := "uby", iso := "uby", value := .ovAndPostpositions }
  , { walsCode := "udh", iso := "ude", value := .ovAndPostpositions }
  , { walsCode := "udm", iso := "udm", value := .ovAndPostpositions }
  , { walsCode := "ukr", iso := "ukr", value := .voAndPrepositions }
  , { walsCode := "uld", iso := "udl", value := .voAndPrepositions }
  , { walsCode := "uli", iso := "uli", value := .voAndPrepositions }
  , { walsCode := "una", iso := "mtg", value := .ovAndPostpositions }
  , { walsCode := "ung", iso := "ung", value := .ovAndPostpositions }
  , { walsCode := "url", iso := "urk", value := .voAndPrepositions }
  , { walsCode := "urn", iso := "ura", value := .ovAndPostpositions }
  , { walsCode := "urd", iso := "urd", value := .ovAndPostpositions }
  , { walsCode := "urk", iso := "urb", value := .ovAndPostpositions }
  , { walsCode := "usa", iso := "wnu", value := .ovAndPostpositions }
  , { walsCode := "ute", iso := "ute", value := .ovAndPostpositions }
  , { walsCode := "vaf", iso := "vaf", value := .other }
  , { walsCode := "vai", iso := "vai", value := .ovAndPostpositions }
  , { walsCode := "vie", iso := "vie", value := .voAndPrepositions }
  , { walsCode := "vnm", iso := "vnm", value := .voAndPrepositions }
  , { walsCode := "vot", iso := "vot", value := .other }
  , { walsCode := "wah", iso := "", value := .ovAndPostpositions }
  , { walsCode := "wai", iso := "waw", value := .ovAndPostpositions }
  , { walsCode := "wak", iso := "wbl", value := .other }
  , { walsCode := "wal", iso := "van", value := .voAndPostpositions }
  , { walsCode := "wbn", iso := "wms", value := .ovAndPostpositions }
  , { walsCode := "wme", iso := "wme", value := .ovAndPostpositions }
  , { walsCode := "wna", iso := "wan", value := .ovAndPostpositions }
  , { walsCode := "wan", iso := "xwk", value := .other }
  , { walsCode := "wao", iso := "auc", value := .ovAndPostpositions }
  , { walsCode := "wra", iso := "wba", value := .ovAndPostpositions }
  , { walsCode := "wry", iso := "wrz", value := .voAndPostpositions }
  , { walsCode := "wrd", iso := "wrr", value := .other }
  , { walsCode := "wrk", iso := "gae", value := .voAndPrepositions }
  , { walsCode := "wrm", iso := "wsa", value := .voAndPrepositions }
  , { walsCode := "war", iso := "pav", value := .voAndPrepositions }
  , { walsCode := "wrl", iso := "wbp", value := .other }
  , { walsCode := "wrg", iso := "wgy", value := .other }
  , { walsCode := "wrw", iso := "wwr", value := .other }
  , { walsCode := "was", iso := "was", value := .ovAndPostpositions }
  , { walsCode := "wsk", iso := "wsk", value := .ovAndPostpositions }
  , { walsCode := "wtm", iso := "wax", value := .ovAndPostpositions }
  , { walsCode := "way", iso := "oym", value := .ovAndPostpositions }
  , { walsCode := "wed", iso := "wed", value := .other }
  , { walsCode := "wel", iso := "cym", value := .voAndPrepositions }
  , { walsCode := "wem", iso := "xww", value := .other }
  , { walsCode := "wma", iso := "mqs", value := .voAndPrepositions }
  , { walsCode := "wch", iso := "mzh", value := .voAndPrepositions }
  , { walsCode := "wik", iso := "yok", value := .other }
  , { walsCode := "win", iso := "wnw", value := .other }
  , { walsCode := "wiy", iso := "wiy", value := .other }
  , { walsCode := "woi", iso := "woi", value := .other }
  , { walsCode := "wol", iso := "woe", value := .voAndPrepositions }
  , { walsCode := "wlo", iso := "wlo", value := .voAndPrepositions }
  , { walsCode := "wlf", iso := "wol", value := .voAndPrepositions }
  , { walsCode := "xas", iso := "kao", value := .ovAndPostpositions }
  , { walsCode := "xho", iso := "xho", value := .voAndPrepositions }
  , { walsCode := "xar", iso := "ane", value := .voAndPrepositions }
  , { walsCode := "ygr", iso := "ygr", value := .ovAndPostpositions }
  , { walsCode := "yag", iso := "yad", value := .voAndPostpositions }
  , { walsCode := "yah", iso := "yag", value := .ovAndPostpositions }
  , { walsCode := "ykt", iso := "sah", value := .ovAndPostpositions }
  , { walsCode := "yal", iso := "kkl", value := .ovAndPostpositions }
  , { walsCode := "yap", iso := "yap", value := .voAndPrepositions }
  , { walsCode := "yqy", iso := "jaq", value := .ovAndPostpositions }
  , { walsCode := "yaq", iso := "yaq", value := .ovAndPostpositions }
  , { walsCode := "yar", iso := "yrb", value := .ovAndPostpositions }
  , { walsCode := "ywr", iso := "ywr", value := .other }
  , { walsCode := "yei", iso := "jei", value := .ovAndPostpositions }
  , { walsCode := "ylm", iso := "jel", value := .ovAndPostpositions }
  , { walsCode := "yel", iso := "yle", value := .ovAndPostpositions }
  , { walsCode := "yim", iso := "yee", value := .ovAndPostpositions }
  , { walsCode := "yin", iso := "yij", value := .other }
  , { walsCode := "yok", iso := "yok", value := .voAndPrepositions }
  , { walsCode := "yor", iso := "yor", value := .voAndPrepositions }
  , { walsCode := "yuc", iso := "yuc", value := .ovAndPostpositions }
  , { walsCode := "ycn", iso := "ycn", value := .voAndPostpositions }
  , { walsCode := "yko", iso := "yux", value := .ovAndPostpositions }
  , { walsCode := "ytu", iso := "ykg", value := .ovAndPostpositions }
  , { walsCode := "yul", iso := "yul", value := .voAndPrepositions }
  , { walsCode := "ypk", iso := "esu", value := .other }
  , { walsCode := "yur", iso := "yur", value := .other }
  , { walsCode := "zan", iso := "zne", value := .voAndPrepositions }
  , { walsCode := "zai", iso := "zai", value := .voAndPrepositions }
  , { walsCode := "zap", iso := "zaw", value := .voAndPrepositions }
  , { walsCode := "zya", iso := "zav", value := .voAndPrepositions }
  , { walsCode := "zar", iso := "dje", value := .other }
  , { walsCode := "zaz", iso := "diq", value := .ovAndPostpositions }
  , { walsCode := "zhn", iso := "zgb", value := .voAndPrepositions }
  , { walsCode := "zch", iso := "zoh", value := .voAndPostpositions }
  , { walsCode := "zul", iso := "zul", value := .voAndPrepositions }
  , { walsCode := "zun", iso := "zun", value := .ovAndPostpositions }
  , { walsCode := "eme", iso := "eme", value := .ovAndPostpositions }
  , { walsCode := "omi", iso := "aom", value := .ovAndPostpositions }
  ]

/-- Complete WALS 95A dataset (1142 languages). -/
def allData : List (Datapoint RelationshipBetweenTheOrderOfObjectAndVerbAndTheOrderOfAdpositionAndNounPhrase) := allData_0 ++ allData_1 ++ allData_2

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F95A
