import Linglib.Core.WALS.Datapoint

/-!
# WALS Feature 97A: Relationship between the Order of Object and Verb and the Order of Adjective and Noun
@cite{wals-2013}

Auto-generated from WALS v2020.4 CLDF data.
**Do not edit by hand** — regenerate with `python3 scripts/gen_wals.py 97A`.

Chapter 97, 1316 languages.
-/

namespace Core.WALS.F97A

/-- WALS 97A values. -/
inductive RelationshipBetweenTheOrderOfObjectAndVerbAndTheOrderOfAdjectiveAndNoun where
  /-- OV and AdjN (216 languages). -/
  | ovAndAdjn
  /-- OV and NAdj (332 languages). -/
  | ovAndNadj
  /-- VO and AdjN (114 languages). -/
  | voAndAdjn
  /-- VO and NAdj (456 languages). -/
  | voAndNadj
  /-- Other (198 languages). -/
  | other
  deriving DecidableEq, BEq, Repr

private def allData_0 : List (Datapoint RelationshipBetweenTheOrderOfObjectAndVerbAndTheOrderOfAdjectiveAndNoun) :=
  [ { walsCode := "xoo", iso := "nmn", value := .voAndNadj }
  , { walsCode := "ani", iso := "hnh", value := .other }
  , { walsCode := "xam", iso := "xam", value := .voAndNadj }
  , { walsCode := "huc", iso := "huc", value := .voAndNadj }
  , { walsCode := "aar", iso := "aiw", value := .ovAndNadj }
  , { walsCode := "abi", iso := "axb", value := .other }
  , { walsCode := "abk", iso := "abk", value := .ovAndNadj }
  , { walsCode := "abv", iso := "abz", value := .ovAndNadj }
  , { walsCode := "abu", iso := "kgr", value := .voAndNadj }
  , { walsCode := "ace", iso := "ace", value := .other }
  , { walsCode := "acg", iso := "aca", value := .voAndNadj }
  , { walsCode := "acn", iso := "acn", value := .other }
  , { walsCode := "acl", iso := "ach", value := .voAndNadj }
  , { walsCode := "aco", iso := "kjq", value := .other }
  , { walsCode := "adg", iso := "adn", value := .ovAndNadj }
  , { walsCode := "adi", iso := "adj", value := .voAndNadj }
  , { walsCode := "ady", iso := "ady", value := .ovAndNadj }
  , { walsCode := "adn", iso := "adt", value := .other }
  , { walsCode := "adz", iso := "adz", value := .voAndNadj }
  , { walsCode := "awi", iso := "awi", value := .ovAndNadj }
  , { walsCode := "aga", iso := "agd", value := .ovAndAdjn }
  , { walsCode := "agh", iso := "agq", value := .voAndNadj }
  , { walsCode := "agc", iso := "agt", value := .voAndAdjn }
  , { walsCode := "agd", iso := "duo", value := .voAndAdjn }
  , { walsCode := "ain", iso := "ain", value := .ovAndAdjn }
  , { walsCode := "aja", iso := "aja", value := .voAndAdjn }
  , { walsCode := "ajg", iso := "ajg", value := .other }
  , { walsCode := "akn", iso := "aka", value := .voAndNadj }
  , { walsCode := "akh", iso := "ahk", value := .ovAndNadj }
  , { walsCode := "ala", iso := "amp", value := .ovAndAdjn }
  , { walsCode := "alw", iso := "alh", value := .other }
  , { walsCode := "alb", iso := "sqi", value := .voAndNadj }
  , { walsCode := "als", iso := "aes", value := .voAndAdjn }
  , { walsCode := "aln", iso := "alp", value := .voAndNadj }
  , { walsCode := "aly", iso := "aly", value := .ovAndNadj }
  , { walsCode := "amm", iso := "amm", value := .other }
  , { walsCode := "amc", iso := "amc", value := .ovAndNadj }
  , { walsCode := "amn", iso := "amn", value := .ovAndNadj }
  , { walsCode := "ama", iso := "aie", value := .voAndNadj }
  , { walsCode := "aml", iso := "omb", value := .voAndNadj }
  , { walsCode := "amq", iso := "amk", value := .voAndNadj }
  , { walsCode := "amb", iso := "abt", value := .ovAndAdjn }
  , { walsCode := "amt", iso := "adx", value := .other }
  , { walsCode := "ame", iso := "aey", value := .ovAndNadj }
  , { walsCode := "amh", iso := "amh", value := .ovAndAdjn }
  , { walsCode := "ami", iso := "ami", value := .voAndAdjn }
  , { walsCode := "amo", iso := "amo", value := .voAndNadj }
  , { walsCode := "amx", iso := "imi", value := .ovAndNadj }
  , { walsCode := "anj", iso := "aty", value := .voAndNadj }
  , { walsCode := "agm", iso := "njm", value := .ovAndNadj }
  , { walsCode := "anc", iso := "anc", value := .voAndNadj }
  , { walsCode := "ang", iso := "agg", value := .ovAndNadj }
  , { walsCode := "agt", iso := "awg", value := .ovAndNadj }
  , { walsCode := "ano", iso := "nun", value := .ovAndNadj }
  , { walsCode := "anu", iso := "cko", value := .voAndNadj }
  , { walsCode := "ayi", iso := "any", value := .voAndNadj }
  , { walsCode := "any", iso := "anu", value := .other }
  , { walsCode := "ane", iso := "anz", value := .voAndNadj }
  , { walsCode := "ao", iso := "njo", value := .ovAndNadj }
  , { walsCode := "apl", iso := "apy", value := .ovAndNadj }
  , { walsCode := "apt", iso := "apt", value := .ovAndNadj }
  , { walsCode := "api", iso := "apn", value := .ovAndNadj }
  , { walsCode := "apu", iso := "apu", value := .other }
  , { walsCode := "abn", iso := "ard", value := .ovAndNadj }
  , { walsCode := "aeg", iso := "arz", value := .voAndNadj }
  , { walsCode := "arg", iso := "afb", value := .voAndNadj }
  , { walsCode := "arq", iso := "acm", value := .voAndNadj }
  , { walsCode := "arj", iso := "afb", value := .voAndNadj }
  , { walsCode := "ams", iso := "arb", value := .voAndNadj }
  , { walsCode := "amr", iso := "ary", value := .voAndNadj }
  , { walsCode := "asy", iso := "apc", value := .voAndNadj }
  , { walsCode := "ana", iso := "aro", value := .ovAndNadj }
  , { walsCode := "aab", iso := "aah", value := .voAndNadj }
  , { walsCode := "arp", iso := "ape", value := .voAndAdjn }
  , { walsCode := "abo", iso := "arv", value := .ovAndNadj }
  , { walsCode := "arc", iso := "aqc", value := .ovAndAdjn }
  , { walsCode := "arm", iso := "hye", value := .other }
  , { walsCode := "arw", iso := "hyw", value := .ovAndAdjn }
  , { walsCode := "alk", iso := "apr", value := .voAndNadj }
  , { walsCode := "aro", iso := "aia", value := .voAndNadj }
  , { walsCode := "amp", iso := "aer", value := .ovAndNadj }
  , { walsCode := "asm", iso := "cns", value := .ovAndNadj }
  , { walsCode := "ass", iso := "asm", value := .ovAndAdjn }
  , { walsCode := "atm", iso := "kuz", value := .ovAndNadj }
  , { walsCode := "ata", iso := "tay", value := .other }
  , { walsCode := "ath", iso := "aph", value := .ovAndAdjn }
  , { walsCode := "au", iso := "avt", value := .voAndNadj }
  , { walsCode := "ava", iso := "ava", value := .ovAndAdjn }
  , { walsCode := "avo", iso := "avu", value := .other }
  , { walsCode := "awa", iso := "awb", value := .ovAndAdjn }
  , { walsCode := "awp", iso := "kwi", value := .ovAndAdjn }
  , { walsCode := "awt", iso := "kmn", value := .ovAndNadj }
  , { walsCode := "awy", iso := "auw", value := .ovAndNadj }
  , { walsCode := "ayw", iso := "nfl", value := .voAndNadj }
  , { walsCode := "aym", iso := "ayr", value := .ovAndAdjn }
  , { walsCode := "ayo", iso := "", value := .voAndNadj }
  , { walsCode := "aze", iso := "", value := .ovAndAdjn }
  , { walsCode := "bbl", iso := "bvx", value := .voAndNadj }
  , { walsCode := "bab", iso := "bav", value := .voAndNadj }
  , { walsCode := "bac", iso := "wdj", value := .other }
  , { walsCode := "bdm", iso := "bia", value := .ovAndNadj }
  , { walsCode := "baf", iso := "bfd", value := .voAndNadj }
  , { walsCode := "bag", iso := "bmi", value := .voAndNadj }
  , { walsCode := "bdw", iso := "bdw", value := .ovAndNadj }
  , { walsCode := "bai", iso := "bca", value := .voAndAdjn }
  , { walsCode := "baj", iso := "bdl", value := .voAndNadj }
  , { walsCode := "bwc", iso := "bdr", value := .voAndNadj }
  , { walsCode := "bak", iso := "bkc", value := .voAndAdjn }
  , { walsCode := "bka", iso := "bdh", value := .voAndAdjn }
  , { walsCode := "bku", iso := "bri", value := .voAndNadj }
  , { walsCode := "blz", iso := "", value := .voAndNadj }
  , { walsCode := "bvi", iso := "", value := .voAndNadj }
  , { walsCode := "blt", iso := "bft", value := .ovAndAdjn }
  , { walsCode := "bam", iso := "bam", value := .ovAndNadj }
  , { walsCode := "bnj", iso := "bdy", value := .ovAndAdjn }
  , { walsCode := "bgm", iso := "dba", value := .ovAndNadj }
  , { walsCode := "bnk", iso := "abb", value := .voAndNadj }
  , { walsCode := "bnn", iso := "bcm", value := .voAndNadj }
  , { walsCode := "ble", iso := "bci", value := .voAndNadj }
  , { walsCode := "brl", iso := "loy", value := .ovAndNadj }
  , { walsCode := "baa", iso := "bbb", value := .ovAndNadj }
  , { walsCode := "bbu", iso := "brm", value := .voAndAdjn }
  , { walsCode := "brs", iso := "bsn", value := .other }
  , { walsCode := "bar", iso := "bfa", value := .voAndNadj }
  , { walsCode := "brp", iso := "bpe", value := .ovAndNadj }
  , { walsCode := "bry", iso := "byr", value := .ovAndNadj }
  , { walsCode := "bae", iso := "bae", value := .voAndNadj }
  , { walsCode := "bsr", iso := "bsc", value := .ovAndNadj }
  , { walsCode := "bas", iso := "bas", value := .voAndNadj }
  , { walsCode := "bsk", iso := "bak", value := .ovAndAdjn }
  , { walsCode := "bsq", iso := "eus", value := .ovAndNadj }
  , { walsCode := "bkr", iso := "btx", value := .voAndNadj }
  , { walsCode := "bto", iso := "bbc", value := .voAndNadj }
  , { walsCode := "baq", iso := "brg", value := .voAndNadj }
  , { walsCode := "baw", iso := "bgr", value := .ovAndNadj }
  , { walsCode := "bej", iso := "bej", value := .other }
  , { walsCode := "bel", iso := "byw", value := .ovAndAdjn }
  , { walsCode := "bco", iso := "blc", value := .voAndAdjn }
  , { walsCode := "blr", iso := "bel", value := .other }
  , { walsCode := "blu", iso := "lua", value := .voAndNadj }
  , { walsCode := "bch", iso := "shy", value := .voAndNadj }
  , { walsCode := "bfg", iso := "grr", value := .voAndNadj }
  , { walsCode := "bma", iso := "tzm", value := .voAndNadj }
  , { walsCode := "brf", iso := "rif", value := .voAndNadj }
  , { walsCode := "zag", iso := "zag", value := .ovAndNadj }
  , { walsCode := "ber", iso := "wti", value := .voAndNadj }
  , { walsCode := "bho", iso := "bho", value := .ovAndAdjn }
  , { walsCode := "bhu", iso := "unr", value := .ovAndAdjn }
  , { walsCode := "bik", iso := "bhw", value := .voAndNadj }
  , { walsCode := "bid", iso := "bid", value := .voAndNadj }
  , { walsCode := "bkl", iso := "bcl", value := .other }
  , { walsCode := "bia", iso := "bip", value := .voAndNadj }
  , { walsCode := "bln", iso := "byn", value := .ovAndNadj }
  , { walsCode := "blx", iso := "bll", value := .ovAndNadj }
  , { walsCode := "bil", iso := "blb", value := .voAndAdjn }
  , { walsCode := "bin", iso := "bhg", value := .ovAndNadj }
  , { walsCode := "bni", iso := "bin", value := .voAndNadj }
  , { walsCode := "bbw", iso := "gup", value := .other }
  , { walsCode := "bii", iso := "bzr", value := .voAndAdjn }
  , { walsCode := "bir", iso := "bom", value := .voAndNadj }
  , { walsCode := "biu", iso := "", value := .ovAndNadj }
  , { walsCode := "bla", iso := "bla", value := .voAndAdjn }
  , { walsCode := "bod", iso := "brx", value := .ovAndAdjn }
  , { walsCode := "bok", iso := "bqc", value := .ovAndNadj }
  , { walsCode := "bgo", iso := "bot", value := .other }
  , { walsCode := "bon", iso := "bpu", value := .ovAndNadj }
  , { walsCode := "btk", iso := "lbk", value := .other }
  , { walsCode := "boj", iso := "adi", value := .other }
  , { walsCode := "bra", iso := "brb", value := .voAndNadj }
  , { walsCode := "bre", iso := "bre", value := .voAndNadj }
  , { walsCode := "bri", iso := "bzd", value := .ovAndNadj }
  , { walsCode := "bkt", iso := "bkk", value := .ovAndAdjn }
  , { walsCode := "bub", iso := "bvb", value := .voAndNadj }
  , { walsCode := "bdu", iso := "buu", value := .voAndNadj }
  , { walsCode := "bud", iso := "bdm", value := .voAndNadj }
  , { walsCode := "bgn", iso := "bgg", value := .other }
  , { walsCode := "bun", iso := "buo", value := .ovAndNadj }
  , { walsCode := "bul", iso := "bul", value := .voAndAdjn }
  , { walsCode := "bum", iso := "tkw", value := .voAndNadj }
  , { walsCode := "ghr", iso := "bfu", value := .ovAndNadj }
  , { walsCode := "pnu", iso := "buh", value := .voAndNadj }
  , { walsCode := "bnb", iso := "bck", value := .other }
  , { walsCode := "bua", iso := "bvr", value := .other }
  , { walsCode := "but", iso := "bxm", value := .ovAndAdjn }
  , { walsCode := "brm", iso := "mya", value := .ovAndNadj }
  , { walsCode := "buu", iso := "mhs", value := .voAndNadj }
  , { walsCode := "brn", iso := "bds", value := .voAndNadj }
  , { walsCode := "bur", iso := "bsk", value := .ovAndAdjn }
  , { walsCode := "bus", iso := "bqp", value := .ovAndNadj }
  , { walsCode := "bsh", iso := "buf", value := .voAndNadj }
  , { walsCode := "bya", iso := "bee", value := .ovAndAdjn }
  , { walsCode := "cah", iso := "chl", value := .ovAndAdjn }
  , { walsCode := "cak", iso := "cak", value := .voAndAdjn }
  , { walsCode := "cax", iso := "", value := .voAndNadj }
  , { walsCode := "cam", iso := "kbh", value := .other }
  , { walsCode := "cnl", iso := "ram", value := .ovAndNadj }
  , { walsCode := "cnt", iso := "yue", value := .voAndAdjn }
  , { walsCode := "car", iso := "car", value := .ovAndAdjn }
  , { walsCode := "cde", iso := "mch", value := .ovAndNadj }
  , { walsCode := "cas", iso := "cbr", value := .ovAndNadj }
  , { walsCode := "ctl", iso := "cat", value := .voAndNadj }
  , { walsCode := "ctw", iso := "chc", value := .ovAndNadj }
  , { walsCode := "cav", iso := "cav", value := .other }
  , { walsCode := "cay", iso := "cbi", value := .ovAndAdjn }
  , { walsCode := "cyv", iso := "cyb", value := .voAndAdjn }
  , { walsCode := "cga", iso := "old", value := .voAndNadj }
  , { walsCode := "chh", iso := "sgw", value := .ovAndAdjn }
  , { walsCode := "cai", iso := "suq", value := .other }
  , { walsCode := "cme", iso := "cjm", value := .voAndNadj }
  , { walsCode := "chw", iso := "cja", value := .voAndNadj }
  , { walsCode := "chb", iso := "can", value := .ovAndNadj }
  , { walsCode := "cha", iso := "cha", value := .voAndAdjn }
  , { walsCode := "chg", iso := "nbc", value := .other }
  , { walsCode := "chn", iso := "chx", value := .ovAndAdjn }
  , { walsCode := "cso", iso := "ctp", value := .voAndNadj }
  , { walsCode := "cya", iso := "ctp", value := .voAndNadj }
  , { walsCode := "chd", iso := "cdn", value := .ovAndAdjn }
  , { walsCode := "chc", iso := "che", value := .ovAndAdjn }
  , { walsCode := "cmh", iso := "ute", value := .other }
  , { walsCode := "cpn", iso := "cdm", value := .ovAndAdjn }
  , { walsCode := "che", iso := "chr", value := .ovAndAdjn }
  , { walsCode := "cic", iso := "nya", value := .voAndNadj }
  , { walsCode := "chi", iso := "cid", value := .ovAndNadj }
  , { walsCode := "cmr", iso := "mrh", value := .ovAndNadj }
  , { walsCode := "chs", iso := "csy", value := .other }
  , { walsCode := "cti", iso := "ctd", value := .ovAndNadj }
  , { walsCode := "ccm", iso := "cco", value := .voAndNadj }
  , { walsCode := "cle", iso := "cle", value := .voAndNadj }
  , { walsCode := "cpl", iso := "cpa", value := .voAndNadj }
  , { walsCode := "chq", iso := "chq", value := .voAndNadj }
  , { walsCode := "ckl", iso := "chh", value := .voAndAdjn }
  , { walsCode := "cpy", iso := "cap", value := .ovAndAdjn }
  , { walsCode := "ctm", iso := "ctm", value := .ovAndNadj }
  , { walsCode := "cct", iso := "cho", value := .other }
  , { walsCode := "cln", iso := "cht", value := .ovAndAdjn }
  , { walsCode := "chx", iso := "clo", value := .voAndAdjn }
  , { walsCode := "cmy", iso := "chf", value := .voAndAdjn }
  , { walsCode := "chr", iso := "crw", value := .voAndNadj }
  , { walsCode := "chk", iso := "ckt", value := .ovAndAdjn }
  , { walsCode := "chv", iso := "chv", value := .ovAndAdjn }
  , { walsCode := "cbo", iso := "cao", value := .ovAndNadj }
  , { walsCode := "coc", iso := "cod", value := .voAndNadj }
  , { walsCode := "cmn", iso := "com", value := .ovAndAdjn }
  , { walsCode := "coo", iso := "csz", value := .other }
  , { walsCode := "cop", iso := "cop", value := .voAndNadj }
  , { walsCode := "cor", iso := "crn", value := .voAndNadj }
  , { walsCode := "crn", iso := "cor", value := .voAndNadj }
  , { walsCode := "cro", iso := "cro", value := .ovAndNadj }
  , { walsCode := "cub", iso := "cub", value := .ovAndAdjn }
  , { walsCode := "cui", iso := "cui", value := .ovAndNadj }
  , { walsCode := "cuc", iso := "", value := .other }
  , { walsCode := "cup", iso := "cup", value := .ovAndNadj }
  , { walsCode := "cze", iso := "ces", value := .voAndAdjn }
  , { walsCode := "cem", iso := "cam", value := .voAndNadj }
  , { walsCode := "ddj", iso := "god", value := .other }
  , { walsCode := "dag", iso := "dgz", value := .ovAndNadj }
  , { walsCode := "dga", iso := "dga", value := .voAndNadj }
  , { walsCode := "dgb", iso := "dag", value := .voAndNadj }
  , { walsCode := "dgr", iso := "dta", value := .ovAndAdjn }
  , { walsCode := "dam", iso := "mbp", value := .other }
  , { walsCode := "dan", iso := "dnj", value := .ovAndNadj }
  , { walsCode := "dsh", iso := "dan", value := .voAndAdjn }
  , { walsCode := "drg", iso := "dar", value := .ovAndAdjn }
  , { walsCode := "drm", iso := "drd", value := .ovAndAdjn }
  , { walsCode := "day", iso := "dai", value := .voAndNadj }
  , { walsCode := "deg", iso := "deg", value := .other }
  , { walsCode := "des", iso := "des", value := .ovAndAdjn }
  , { walsCode := "deu", iso := "der", value := .ovAndAdjn }
  , { walsCode := "dha", iso := "dsh", value := .ovAndNadj }
  , { walsCode := "dhr", iso := "dhr", value := .other }
  , { walsCode := "dhm", iso := "dhi", value := .ovAndAdjn }
  , { walsCode := "did", iso := "did", value := .voAndNadj }
  , { walsCode := "die", iso := "dih", value := .other }
  , { walsCode := "dig", iso := "mhu", value := .ovAndNadj }
  , { walsCode := "dms", iso := "dis", value := .ovAndNadj }
  , { walsCode := "dim", iso := "dim", value := .ovAndNadj }
  , { walsCode := "din", iso := "din", value := .other }
  , { walsCode := "dio", iso := "dyo", value := .voAndNadj }
  , { walsCode := "diy", iso := "dif", value := .ovAndNadj }
  , { walsCode := "djm", iso := "djr", value := .other }
  , { walsCode := "djr", iso := "ddj", value := .other }
  , { walsCode := "djn", iso := "dji", value := .other }
  , { walsCode := "dji", iso := "jig", value := .ovAndNadj }
  , { walsCode := "dlm", iso := "kbv", value := .other }
  , { walsCode := "der", iso := "kbv", value := .other }
  , { walsCode := "dmk", iso := "dmk", value := .ovAndAdjn }
  , { walsCode := "dom", iso := "rmt", value := .voAndAdjn }
  , { walsCode := "don", iso := "kmc", value := .voAndNadj }
  , { walsCode := "dgo", iso := "doo", value := .other }
  , { walsCode := "dds", iso := "dds", value := .ovAndNadj }
  , { walsCode := "doy", iso := "dow", value := .voAndNadj }
  , { walsCode := "dre", iso := "dhv", value := .voAndNadj }
  , { walsCode := "dua", iso := "dua", value := .voAndNadj }
  , { walsCode := "duk", iso := "dud", value := .voAndNadj }
  , { walsCode := "dul", iso := "duu", value := .other }
  , { walsCode := "dma", iso := "dma", value := .voAndNadj }
  , { walsCode := "dmi", iso := "dus", value := .ovAndAdjn }
  , { walsCode := "dum", iso := "vam", value := .ovAndNadj }
  , { walsCode := "dun", iso := "duc", value := .ovAndNadj }
  , { walsCode := "dut", iso := "nld", value := .other }
  , { walsCode := "dyi", iso := "dbl", value := .ovAndNadj }
  , { walsCode := "daw", iso := "kwa", value := .ovAndNadj }
  , { walsCode := "edo", iso := "etr", value := .ovAndNadj }
  , { walsCode := "erk", iso := "erk", value := .voAndNadj }
  , { walsCode := "ega", iso := "ega", value := .voAndNadj }
  , { walsCode := "eip", iso := "eip", value := .ovAndAdjn }
  , { walsCode := "emb", iso := "emp", value := .ovAndNadj }
  , { walsCode := "emm", iso := "amy", value := .other }
  , { walsCode := "ene", iso := "", value := .ovAndAdjn }
  , { walsCode := "egn", iso := "enn", value := .voAndNadj }
  , { walsCode := "eno", iso := "eno", value := .voAndNadj }
  , { walsCode := "eng", iso := "eng", value := .voAndAdjn }
  , { walsCode := "epe", iso := "sja", value := .ovAndNadj }
  , { walsCode := "err", iso := "erg", value := .voAndNadj }
  , { walsCode := "ese", iso := "ese", value := .ovAndNadj }
  , { walsCode := "esm", iso := "", value := .other }
  , { walsCode := "est", iso := "ekk", value := .voAndAdjn }
  , { walsCode := "evn", iso := "eve", value := .ovAndAdjn }
  , { walsCode := "eve", iso := "evn", value := .ovAndAdjn }
  , { walsCode := "ewe", iso := "ewe", value := .voAndNadj }
  , { walsCode := "ewo", iso := "ewo", value := .voAndNadj }
  , { walsCode := "fas", iso := "faa", value := .ovAndNadj }
  , { walsCode := "fij", iso := "fij", value := .voAndNadj }
  , { walsCode := "fin", iso := "fin", value := .voAndAdjn }
  , { walsCode := "foe", iso := "foi", value := .ovAndNadj }
  , { walsCode := "pdp", iso := "ppo", value := .other }
  , { walsCode := "fon", iso := "fon", value := .voAndNadj }
  , { walsCode := "for", iso := "for", value := .ovAndAdjn }
  , { walsCode := "fre", iso := "fra", value := .voAndNadj }
  , { walsCode := "fri", iso := "fry", value := .other }
  , { walsCode := "fua", iso := "fub", value := .voAndNadj }
  , { walsCode := "fni", iso := "fuv", value := .voAndNadj }
  , { walsCode := "ful", iso := "fun", value := .ovAndNadj }
  , { walsCode := "fur", iso := "fvr", value := .ovAndNadj }
  , { walsCode := "fut", iso := "fut", value := .voAndNadj }
  , { walsCode := "fye", iso := "pym", value := .voAndNadj }
  , { walsCode := "gnd", iso := "gqa", value := .voAndNadj }
  , { walsCode := "gds", iso := "gaj", value := .ovAndAdjn }
  , { walsCode := "gae", iso := "gla", value := .voAndNadj }
  , { walsCode := "gah", iso := "gah", value := .other }
  , { walsCode := "gal", iso := "adl", value := .ovAndAdjn }
  , { walsCode := "gam", iso := "gmv", value := .ovAndAdjn }
  , { walsCode := "gar", iso := "grt", value := .ovAndNadj }
  , { walsCode := "grr", iso := "wrk", value := .voAndNadj }
  , { walsCode := "grf", iso := "cab", value := .voAndNadj }
  , { walsCode := "gav", iso := "gvo", value := .ovAndNadj }
  , { walsCode := "gbk", iso := "gya", value := .voAndAdjn }
  , { walsCode := "gbb", iso := "gbp", value := .voAndAdjn }
  , { walsCode := "gel", iso := "nlg", value := .voAndNadj }
  , { walsCode := "gla", iso := "gqu", value := .voAndNadj }
  , { walsCode := "geo", iso := "kat", value := .ovAndAdjn }
  , { walsCode := "ger", iso := "deu", value := .other }
  , { walsCode := "gid", iso := "gih", value := .other }
  , { walsCode := "gim", iso := "bcq", value := .other }
  , { walsCode := "git", iso := "git", value := .other }
  , { walsCode := "goa", iso := "guc", value := .voAndNadj }
  , { walsCode := "god", iso := "gdo", value := .ovAndAdjn }
  , { walsCode := "goe", iso := "ank", value := .voAndNadj }
  , { walsCode := "gok", iso := "gkn", value := .voAndAdjn }
  , { walsCode := "gln", iso := "gvf", value := .ovAndNadj }
  , { walsCode := "gon", iso := "gno", value := .ovAndAdjn }
  , { walsCode := "goo", iso := "gni", value := .ovAndNadj }
  , { walsCode := "gan", iso := "apq", value := .ovAndNadj }
  , { walsCode := "grb", iso := "grj", value := .voAndNadj }
  , { walsCode := "grk", iso := "ell", value := .voAndAdjn }
  , { walsCode := "grw", iso := "kal", value := .ovAndNadj }
  , { walsCode := "gjj", iso := "gub", value := .voAndNadj }
  , { walsCode := "gua", iso := "gug", value := .voAndNadj }
  , { walsCode := "grj", iso := "var", value := .other }
  , { walsCode := "gto", iso := "gta", value := .voAndNadj }
  , { walsCode := "gud", iso := "gde", value := .voAndAdjn }
  , { walsCode := "gug", iso := "ktd", value := .ovAndNadj }
  , { walsCode := "guh", iso := "ghs", value := .ovAndNadj }
  , { walsCode := "guj", iso := "guj", value := .ovAndAdjn }
  , { walsCode := "gul", iso := "kcm", value := .voAndNadj }
  , { walsCode := "gmw", iso := "gvs", value := .ovAndNadj }
  , { walsCode := "gum", iso := "kgs", value := .other }
  , { walsCode := "gmz", iso := "guk", value := .other }
  , { walsCode := "gnb", iso := "wlg", value := .voAndAdjn }
  , { walsCode := "guw", iso := "guw", value := .voAndNadj }
  , { walsCode := "gnn", iso := "gww", value := .other }
  , { walsCode := "ggu", iso := "gnr", value := .other }
  , { walsCode := "grg", iso := "gge", value := .other }
  , { walsCode := "gur", iso := "", value := .ovAndAdjn }
  , { walsCode := "guu", iso := "kky", value := .ovAndNadj }
  , { walsCode := "gwa", iso := "gbr", value := .other }
  , { walsCode := "gyc", iso := "jya", value := .ovAndNadj }
  , { walsCode := "ga", iso := "gaa", value := .voAndNadj }
  , { walsCode := "hai", iso := "hai", value := .ovAndNadj }
  , { walsCode := "hal", iso := "hla", value := .voAndNadj }
  , { walsCode := "hlu", iso := "hur", value := .voAndAdjn }
  , { walsCode := "ham", iso := "hmt", value := .ovAndNadj }
  , { walsCode := "hhu", iso := "wos", value := .ovAndAdjn }
  , { walsCode := "han", iso := "hni", value := .other }
  , { walsCode := "har", iso := "tmd", value := .ovAndNadj }
  , { walsCode := "hat", iso := "had", value := .voAndNadj }
  , { walsCode := "hau", iso := "hau", value := .voAndAdjn }
  , { walsCode := "haw", iso := "haw", value := .voAndNadj }
  , { walsCode := "hya", iso := "hay", value := .voAndNadj }
  , { walsCode := "hay", iso := "vay", value := .ovAndAdjn }
  , { walsCode := "hdi", iso := "xed", value := .voAndNadj }
  , { walsCode := "heb", iso := "heb", value := .voAndNadj }
  , { walsCode := "heh", iso := "heh", value := .voAndNadj }
  , { walsCode := "hei", iso := "hei", value := .voAndAdjn }
  , { walsCode := "hem", iso := "hem", value := .voAndNadj }
  , { walsCode := "hid", iso := "hid", value := .ovAndNadj }
  , { walsCode := "hil", iso := "hil", value := .other }
  , { walsCode := "hin", iso := "hin", value := .ovAndAdjn }
  , { walsCode := "hix", iso := "hix", value := .ovAndNadj }
  , { walsCode := "lic", iso := "lic", value := .voAndNadj }
  , { walsCode := "hma", iso := "hmr", value := .ovAndNadj }
  , { walsCode := "hmo", iso := "hnj", value := .voAndNadj }
  , { walsCode := "ho", iso := "hoc", value := .ovAndAdjn }
  , { walsCode := "hoa", iso := "hoa", value := .voAndNadj }
  , { walsCode := "hol", iso := "hoo", value := .voAndNadj }
  , { walsCode := "hop", iso := "hop", value := .ovAndAdjn }
  , { walsCode := "hua", iso := "ygr", value := .ovAndAdjn }
  , { walsCode := "hlp", iso := "yuf", value := .ovAndNadj }
  , { walsCode := "htc", iso := "hus", value := .voAndAdjn }
  , { walsCode := "hve", iso := "huv", value := .voAndAdjn }
  , { walsCode := "hmi", iso := "hto", value := .ovAndAdjn }
  , { walsCode := "hum", iso := "huu", value := .ovAndAdjn }
  , { walsCode := "hnd", iso := "hke", value := .voAndNadj }
  , { walsCode := "hun", iso := "hun", value := .voAndAdjn }
  , { walsCode := "hzb", iso := "huz", value := .ovAndAdjn }
  , { walsCode := "hpd", iso := "jup", value := .ovAndNadj }
  , { walsCode := "hup", iso := "hup", value := .other }
  , { walsCode := "isa", iso := "ksi", value := .ovAndNadj }
  , { walsCode := "iaa", iso := "iai", value := .voAndAdjn }
  , { walsCode := "iba", iso := "iba", value := .voAndNadj }
  , { walsCode := "ice", iso := "isl", value := .voAndAdjn }
  , { walsCode := "ido", iso := "idu", value := .other }
  , { walsCode := "idu", iso := "clk", value := .ovAndAdjn }
  , { walsCode := "idn", iso := "viv", value := .ovAndNadj }
  , { walsCode := "mxe", iso := "mxe", value := .voAndNadj }
  , { walsCode := "ifu", iso := "ifb", value := .voAndAdjn }
  , { walsCode := "ifm", iso := "ifm", value := .voAndNadj }
  , { walsCode := "igb", iso := "ibo", value := .voAndNadj }
  , { walsCode := "ige", iso := "ige", value := .voAndNadj }
  , { walsCode := "ijo", iso := "ijc", value := .ovAndAdjn }
  , { walsCode := "ik", iso := "ikx", value := .voAndNadj }
  , { walsCode := "ika", iso := "arh", value := .ovAndNadj }
  , { walsCode := "ila", iso := "ilb", value := .voAndNadj }
  , { walsCode := "ilo", iso := "ilo", value := .voAndAdjn }
  , { walsCode := "imo", iso := "imn", value := .ovAndNadj }
  , { walsCode := "ina", iso := "szp", value := .other }
  , { walsCode := "ind", iso := "ind", value := .voAndNadj }
  , { walsCode := "igs", iso := "tbi", value := .voAndNadj }
  , { walsCode := "inn", iso := "ynd", value := .ovAndNadj }
  , { walsCode := "iqu", iso := "iqu", value := .voAndNadj }
  , { walsCode := "irx", iso := "irn", value := .ovAndNadj }
  , { walsCode := "irq", iso := "irk", value := .ovAndNadj }
  , { walsCode := "irr", iso := "irh", value := .voAndNadj }
  , { walsCode := "iri", iso := "gle", value := .voAndNadj }
  , { walsCode := "ita", iso := "ita", value := .voAndNadj }
  , { walsCode := "ite", iso := "itl", value := .other }
  , { walsCode := "ito", iso := "ito", value := .other }
  , { walsCode := "iwa", iso := "ibd", value := .voAndAdjn }
  , { walsCode := "kwy", iso := "yom", value := .voAndNadj }
  , { walsCode := "jar", iso := "izr", value := .voAndNadj }
  , { walsCode := "izi", iso := "izz", value := .other }
  , { walsCode := "jbt", iso := "jbt", value := .ovAndNadj }
  , { walsCode := "jab", iso := "jae", value := .voAndNadj }
  , { walsCode := "jad", iso := "jda", value := .ovAndNadj }
  , { walsCode := "jak", iso := "jac", value := .voAndAdjn }
  , { walsCode := "jam", iso := "djd", value := .other }
  , { walsCode := "jms", iso := "djm", value := .ovAndNadj }
  , { walsCode := "jpn", iso := "jpn", value := .ovAndAdjn }
  , { walsCode := "jrw", iso := "anq", value := .ovAndNadj }
  , { walsCode := "jeb", iso := "jeb", value := .other }
  , { walsCode := "jng", iso := "kac", value := .ovAndNadj }
  , { walsCode := "jin", iso := "jiu", value := .ovAndNadj }
  , { walsCode := "jiv", iso := "jiv", value := .ovAndAdjn }
  , { walsCode := "joh", iso := "rgk", value := .ovAndAdjn }
  , { walsCode := "jug", iso := "nst", value := .other }
  , { walsCode := "juk", iso := "jbu", value := .voAndNadj }
  , { walsCode := "jmo", iso := "bex", value := .voAndNadj }
  , { walsCode := "juh", iso := "ktz", value := .voAndNadj }
  , { walsCode := "kbt", iso := "xkp", value := .ovAndAdjn }
  , { walsCode := "kby", iso := "kbp", value := .voAndNadj }
  , { walsCode := "kbl", iso := "kab", value := .voAndNadj }
  , { walsCode := "kac", iso := "xac", value := .other }
  , { walsCode := "kdz", iso := "kzj", value := .voAndNadj }
  , { walsCode := "kgr", iso := "kki", value := .voAndNadj }
  , { walsCode := "kng", iso := "kgp", value := .ovAndNadj }
  , { walsCode := "krr", iso := "kxa", value := .ovAndNadj }
  , { walsCode := "kae", iso := "tbd", value := .ovAndNadj }
  , { walsCode := "klq", iso := "kmh", value := .ovAndNadj }
  , { walsCode := "kgu", iso := "ktg", value := .ovAndNadj }
  , { walsCode := "kmk", iso := "xal", value := .ovAndAdjn }
  , { walsCode := "kll", iso := "bco", value := .ovAndNadj }
  , { walsCode := "kma", iso := "kay", value := .ovAndNadj }
  , { walsCode := "kmz", iso := "kms", value := .ovAndNadj }
  , { walsCode := "kms", iso := "xas", value := .ovAndAdjn }
  , { walsCode := "kba", iso := "kam", value := .voAndNadj }
  , { walsCode := "kam", iso := "xbr", value := .voAndNadj }
  , { walsCode := "kbo", iso := "kbx", value := .ovAndNadj }
  , { walsCode := "kmw", iso := "xmu", value := .other }
  , { walsCode := "kan", iso := "ogo", value := .other }
  , { walsCode := "knk", iso := "kna", value := .other }
  ]

private def allData_1 : List (Datapoint RelationshipBetweenTheOrderOfObjectAndVerbAndTheOrderOfAdjectiveAndNoun) :=
  [ { walsCode := "knd", iso := "kan", value := .ovAndAdjn }
  , { walsCode := "kno", iso := "kxo", value := .ovAndNadj }
  , { walsCode := "knr", iso := "knc", value := .ovAndNadj }
  , { walsCode := "kpm", iso := "pam", value := .other }
  , { walsCode := "kar", iso := "kah", value := .voAndNadj }
  , { walsCode := "krc", iso := "krc", value := .ovAndAdjn }
  , { walsCode := "krj", iso := "gbd", value := .other }
  , { walsCode := "jva", iso := "kpj", value := .ovAndNadj }
  , { walsCode := "kkp", iso := "kaa", value := .ovAndAdjn }
  , { walsCode := "kkw", iso := "zkk", value := .other }
  , { walsCode := "kbw", iso := "bwe", value := .voAndNadj }
  , { walsCode := "kpw", iso := "kjp", value := .voAndNadj }
  , { walsCode := "ksg", iso := "ksw", value := .voAndNadj }
  , { walsCode := "kmj", iso := "kdj", value := .voAndNadj }
  , { walsCode := "kyr", iso := "yuj", value := .other }
  , { walsCode := "krk", iso := "kyh", value := .other }
  , { walsCode := "kaa", iso := "arr", value := .ovAndNadj }
  , { walsCode := "kas", iso := "kas", value := .voAndAdjn }
  , { walsCode := "ksn", iso := "cog", value := .voAndNadj }
  , { walsCode := "ktc", iso := "xtc", value := .voAndNadj }
  , { walsCode := "ktl", iso := "kcr", value := .voAndNadj }
  , { walsCode := "kau", iso := "pss", value := .voAndNadj }
  , { walsCode := "kws", iso := "xaw", value := .other }
  , { walsCode := "kyz", iso := "kyz", value := .ovAndNadj }
  , { walsCode := "kyl", iso := "eky", value := .voAndNadj }
  , { walsCode := "kay", iso := "gyd", value := .other }
  , { walsCode := "kel", iso := "sbc", value := .voAndNadj }
  , { walsCode := "kem", iso := "ahg", value := .ovAndAdjn }
  , { walsCode := "ker", iso := "ker", value := .voAndNadj }
  , { walsCode := "ket", iso := "ket", value := .ovAndAdjn }
  , { walsCode := "kte", iso := "kcv", value := .voAndNadj }
  , { walsCode := "kew", iso := "kew", value := .ovAndAdjn }
  , { walsCode := "khl", iso := "klj", value := .ovAndAdjn }
  , { walsCode := "khg", iso := "klr", value := .ovAndAdjn }
  , { walsCode := "kha", iso := "khk", value := .ovAndAdjn }
  , { walsCode := "kmh", iso := "kjl", value := .ovAndAdjn }
  , { walsCode := "khd", iso := "khg", value := .ovAndNadj }
  , { walsCode := "knz", iso := "khg", value := .ovAndNadj }
  , { walsCode := "kty", iso := "kca", value := .ovAndAdjn }
  , { walsCode := "khs", iso := "kha", value := .voAndNadj }
  , { walsCode := "khm", iso := "khm", value := .voAndNadj }
  , { walsCode := "kmu", iso := "kjg", value := .voAndNadj }
  , { walsCode := "khw", iso := "khw", value := .ovAndAdjn }
  , { walsCode := "kik", iso := "kik", value := .voAndNadj }
  , { walsCode := "klv", iso := "kij", value := .voAndNadj }
  , { walsCode := "klw", iso := "klb", value := .ovAndNadj }
  , { walsCode := "kga", iso := "zga", value := .voAndNadj }
  , { walsCode := "knn", iso := "kfk", value := .ovAndAdjn }
  , { walsCode := "kin", iso := "kin", value := .voAndNadj }
  , { walsCode := "kri", iso := "kzw", value := .voAndNadj }
  , { walsCode := "kie", iso := "geb", value := .ovAndNadj }
  , { walsCode := "krb", iso := "gil", value := .voAndNadj }
  , { walsCode := "kir", iso := "cme", value := .voAndNadj }
  , { walsCode := "kis", iso := "kss", value := .other }
  , { walsCode := "kiw", iso := "kjd", value := .ovAndAdjn }
  , { walsCode := "klm", iso := "kla", value := .other }
  , { walsCode := "kla", iso := "klu", value := .other }
  , { walsCode := "shp", iso := "yak", value := .voAndAdjn }
  , { walsCode := "koa", iso := "cku", value := .ovAndNadj }
  , { walsCode := "kob", iso := "kpw", value := .ovAndNadj }
  , { walsCode := "koe", iso := "xwg", value := .voAndNadj }
  , { walsCode := "kmo", iso := "kpx", value := .ovAndNadj }
  , { walsCode := "kta", iso := "kqi", value := .ovAndNadj }
  , { walsCode := "kok", iso := "trp", value := .ovAndNadj }
  , { walsCode := "kkt", iso := "kkk", value := .voAndNadj }
  , { walsCode := "kol", iso := "kfb", value := .ovAndAdjn }
  , { walsCode := "klr", iso := "shm", value := .ovAndAdjn }
  , { walsCode := "kmb", iso := "", value := .ovAndNadj }
  , { walsCode := "xbi", iso := "xbi", value := .voAndNadj }
  , { walsCode := "kop", iso := "koi", value := .ovAndAdjn }
  , { walsCode := "kzy", iso := "kpv", value := .voAndAdjn }
  , { walsCode := "kom", iso := "xom", value := .voAndNadj }
  , { walsCode := "kon", iso := "kng", value := .voAndNadj }
  , { walsCode := "krn", iso := "kqz", value := .ovAndAdjn }
  , { walsCode := "kor", iso := "kor", value := .ovAndAdjn }
  , { walsCode := "kje", iso := "coe", value := .voAndNadj }
  , { walsCode := "kku", iso := "kfq", value := .ovAndAdjn }
  , { walsCode := "kfe", iso := "kfz", value := .voAndNadj }
  , { walsCode := "krw", iso := "khe", value := .ovAndAdjn }
  , { walsCode := "kry", iso := "kpy", value := .ovAndAdjn }
  , { walsCode := "kos", iso := "kos", value := .voAndNadj }
  , { walsCode := "koy", iso := "kff", value := .ovAndAdjn }
  , { walsCode := "kch", iso := "khq", value := .voAndNadj }
  , { walsCode := "kse", iso := "ses", value := .ovAndNadj }
  , { walsCode := "kyn", iso := "koy", value := .ovAndNadj }
  , { walsCode := "krh", iso := "xra", value := .ovAndNadj }
  , { walsCode := "kqq", iso := "kqq", value := .ovAndNadj }
  , { walsCode := "kre", iso := "krs", value := .voAndAdjn }
  , { walsCode := "kro", iso := "kgo", value := .voAndNadj }
  , { walsCode := "krz", iso := "kry", value := .ovAndAdjn }
  , { walsCode := "knc", iso := "uwa", value := .ovAndNadj }
  , { walsCode := "kya", iso := "gvn", value := .ovAndNadj }
  , { walsCode := "klg", iso := "kle", value := .ovAndAdjn }
  , { walsCode := "kmn", iso := "kue", value := .ovAndNadj }
  , { walsCode := "kum", iso := "kfy", value := .ovAndAdjn }
  , { walsCode := "knm", iso := "kun", value := .ovAndNadj }
  , { walsCode := "kmp", iso := "kup", value := .ovAndNadj }
  , { walsCode := "kuo", iso := "kto", value := .voAndNadj }
  , { walsCode := "krd", iso := "ckb", value := .ovAndNadj }
  , { walsCode := "kut", iso := "kut", value := .other }
  , { walsCode := "thy", iso := "thd", value := .ovAndNadj }
  , { walsCode := "kuu", iso := "kuy", value := .ovAndNadj }
  , { walsCode := "kuv", iso := "kxv", value := .ovAndAdjn }
  , { walsCode := "kwa", iso := "kwd", value := .voAndNadj }
  , { walsCode := "kwk", iso := "kwk", value := .voAndAdjn }
  , { walsCode := "kwn", iso := "kwn", value := .voAndNadj }
  , { walsCode := "kwz", iso := "xwa", value := .ovAndNadj }
  , { walsCode := "kwb", iso := "kwe", value := .ovAndNadj }
  , { walsCode := "kwo", iso := "kmo", value := .ovAndAdjn }
  , { walsCode := "kwt", iso := "kwo", value := .other }
  , { walsCode := "kxo", iso := "xuu", value := .ovAndAdjn }
  , { walsCode := "kyk", iso := "kyc", value := .ovAndNadj }
  , { walsCode := "kgy", iso := "kgy", value := .ovAndNadj }
  , { walsCode := "laa", iso := "gdm", value := .voAndNadj }
  , { walsCode := "lab", iso := "lbu", value := .voAndNadj }
  , { walsCode := "lac", iso := "lac", value := .voAndAdjn }
  , { walsCode := "lad", iso := "lbj", value := .ovAndNadj }
  , { walsCode := "laf", iso := "laf", value := .other }
  , { walsCode := "lag", iso := "kot", value := .voAndNadj }
  , { walsCode := "lah", iso := "lhu", value := .other }
  , { walsCode := "lai", iso := "cnh", value := .other }
  , { walsCode := "lak", iso := "lbe", value := .ovAndAdjn }
  , { walsCode := "lkt", iso := "lkt", value := .ovAndNadj }
  , { walsCode := "lal", iso := "ywt", value := .ovAndNadj }
  , { walsCode := "lmh", iso := "slp", value := .voAndNadj }
  , { walsCode := "lmg", iso := "hia", value := .voAndNadj }
  , { walsCode := "lmn", iso := "lmn", value := .ovAndAdjn }
  , { walsCode := "lmu", iso := "lmu", value := .other }
  , { walsCode := "lmp", iso := "ljp", value := .voAndNadj }
  , { walsCode := "lgi", iso := "lag", value := .voAndNadj }
  , { walsCode := "lan", iso := "laj", value := .voAndNadj }
  , { walsCode := "lao", iso := "lao", value := .voAndNadj }
  , { walsCode := "lar", iso := "lrg", value := .ovAndNadj }
  , { walsCode := "lat", iso := "lav", value := .voAndAdjn }
  , { walsCode := "lav", iso := "lvk", value := .ovAndNadj }
  , { walsCode := "leb", iso := "agh", value := .voAndNadj }
  , { walsCode := "agb", iso := "agb", value := .voAndNadj }
  , { walsCode := "lec", iso := "lec", value := .other }
  , { walsCode := "lel", iso := "lln", value := .voAndNadj }
  , { walsCode := "llm", iso := "lef", value := .voAndNadj }
  , { walsCode := "len", iso := "tnl", value := .voAndNadj }
  , { walsCode := "ldu", iso := "led", value := .other }
  , { walsCode := "lep", iso := "lep", value := .ovAndNadj }
  , { walsCode := "les", iso := "les", value := .other }
  , { walsCode := "let", iso := "lti", value := .voAndNadj }
  , { walsCode := "lew", iso := "lww", value := .voAndNadj }
  , { walsCode := "lez", iso := "lez", value := .ovAndAdjn }
  , { walsCode := "lil", iso := "lil", value := .voAndAdjn }
  , { walsCode := "lim", iso := "lif", value := .ovAndAdjn }
  , { walsCode := "lml", iso := "lmc", value := .other }
  , { walsCode := "lnd", iso := "liy", value := .voAndAdjn }
  , { walsCode := "lin", iso := "lin", value := .voAndNadj }
  , { walsCode := "lis", iso := "lis", value := .ovAndNadj }
  , { walsCode := "lit", iso := "lit", value := .voAndAdjn }
  , { walsCode := "lgt", iso := "log", value := .other }
  , { walsCode := "ara", iso := "arw", value := .voAndAdjn }
  , { walsCode := "ldo", iso := "bdu", value := .voAndNadj }
  , { walsCode := "lgu", iso := "lgu", value := .voAndNadj }
  , { walsCode := "lon", iso := "los", value := .voAndNadj }
  , { walsCode := "lot", iso := "njh", value := .ovAndNadj }
  , { walsCode := "lou", iso := "loj", value := .voAndNadj }
  , { walsCode := "luc", iso := "lch", value := .voAndNadj }
  , { walsCode := "lug", iso := "lgg", value := .other }
  , { walsCode := "lui", iso := "lui", value := .other }
  , { walsCode := "lbu", iso := "lun", value := .voAndNadj }
  , { walsCode := "lun", iso := "nst", value := .other }
  , { walsCode := "luo", iso := "luo", value := .voAndNadj }
  , { walsCode := "kkv", iso := "khl", value := .voAndNadj }
  , { walsCode := "luv", iso := "lue", value := .voAndNadj }
  , { walsCode := "ma", iso := "msj", value := .voAndAdjn }
  , { walsCode := "myn", iso := "mhy", value := .voAndNadj }
  , { walsCode := "mad", iso := "mhi", value := .other }
  , { walsCode := "maa", iso := "mas", value := .voAndNadj }
  , { walsCode := "mab", iso := "mde", value := .ovAndNadj }
  , { walsCode := "mcd", iso := "mkd", value := .voAndAdjn }
  , { walsCode := "mch", iso := "mcb", value := .other }
  , { walsCode := "mac", iso := "mbc", value := .ovAndNadj }
  , { walsCode := "mda", iso := "mxu", value := .voAndNadj }
  , { walsCode := "mdm", iso := "dmd", value := .voAndAdjn }
  , { walsCode := "mae", iso := "mmw", value := .voAndNadj }
  , { walsCode := "mne", iso := "nmu", value := .ovAndAdjn }
  , { walsCode := "mpr", iso := "", value := .voAndNadj }
  , { walsCode := "msn", iso := "mbq", value := .ovAndNadj }
  , { walsCode := "mai", iso := "mai", value := .ovAndAdjn }
  , { walsCode := "maj", iso := "mpe", value := .voAndAdjn }
  , { walsCode := "mkz", iso := "mcp", value := .voAndNadj }
  , { walsCode := "mak", iso := "myh", value := .other }
  , { walsCode := "mkj", iso := "mkz", value := .ovAndNadj }
  , { walsCode := "mkd", iso := "kde", value := .voAndNadj }
  , { walsCode := "mua", iso := "mgh", value := .voAndNadj }
  , { walsCode := "mal", iso := "plt", value := .voAndNadj }
  , { walsCode := "mlk", iso := "mpb", value := .ovAndNadj }
  , { walsCode := "mym", iso := "mal", value := .ovAndAdjn }
  , { walsCode := "mlu", iso := "mgl", value := .voAndNadj }
  , { walsCode := "mlg", iso := "", value := .voAndNadj }
  , { walsCode := "mto", iso := "kmj", value := .ovAndAdjn }
  , { walsCode := "mam", iso := "mam", value := .other }
  , { walsCode := "mmn", iso := "mmn", value := .other }
  , { walsCode := "mla", iso := "", value := .voAndNadj }
  , { walsCode := "mmv", iso := "mdi", value := .voAndNadj }
  , { walsCode := "mds", iso := "xmm", value := .voAndNadj }
  , { walsCode := "mnm", iso := "mva", value := .ovAndNadj }
  , { walsCode := "nmm", iso := "nmm", value := .other }
  , { walsCode := "mnc", iso := "mnc", value := .ovAndAdjn }
  , { walsCode := "mdn", iso := "mhq", value := .ovAndNadj }
  , { walsCode := "mnd", iso := "cmn", value := .voAndAdjn }
  , { walsCode := "mkg", iso := "mnk", value := .ovAndNadj }
  , { walsCode := "mmb", iso := "mna", value := .voAndNadj }
  , { walsCode := "myi", iso := "mpc", value := .ovAndNadj }
  , { walsCode := "mbt", iso := "mdj", value := .voAndNadj }
  , { walsCode := "mng", iso := "mqy", value := .voAndNadj }
  , { walsCode := "mgg", iso := "mjg", value := .ovAndAdjn }
  , { walsCode := "maw", iso := "mlq", value := .ovAndNadj }
  , { walsCode := "man", iso := "mev", value := .ovAndNadj }
  , { walsCode := "mwb", iso := "mbb", value := .voAndAdjn }
  , { walsCode := "mns", iso := "mns", value := .ovAndAdjn }
  , { walsCode := "mao", iso := "mri", value := .voAndNadj }
  , { walsCode := "map", iso := "arn", value := .voAndAdjn }
  , { walsCode := "mra", iso := "mec", value := .other }
  , { walsCode := "mku", iso := "zmr", value := .ovAndNadj }
  , { walsCode := "mhi", iso := "mar", value := .ovAndAdjn }
  , { walsCode := "mrc", iso := "rnp", value := .ovAndAdjn }
  , { walsCode := "mrg", iso := "mrt", value := .voAndNadj }
  , { walsCode := "mme", iso := "mhr", value := .ovAndAdjn }
  , { walsCode := "mar", iso := "mrc", value := .ovAndNadj }
  , { walsCode := "mrr", iso := "zmt", value := .ovAndNadj }
  , { walsCode := "mrq", iso := "", value := .voAndNadj }
  , { walsCode := "mrh", iso := "mfr", value := .ovAndNadj }
  , { walsCode := "mrt", iso := "vma", value := .voAndNadj }
  , { walsCode := "mru", iso := "mhx", value := .ovAndNadj }
  , { walsCode := "mas", iso := "mcn", value := .voAndNadj }
  , { walsCode := "msk", iso := "jle", value := .voAndNadj }
  , { walsCode := "msl", iso := "mls", value := .ovAndNadj }
  , { walsCode := "mtt", iso := "wam", value := .other }
  , { walsCode := "mts", iso := "mpq", value := .ovAndNadj }
  , { walsCode := "mdl", iso := "zml", value := .ovAndNadj }
  , { walsCode := "myr", iso := "mcf", value := .ovAndNadj }
  , { walsCode := "mtb", iso := "mgw", value := .voAndNadj }
  , { walsCode := "mka", iso := "mxx", value := .ovAndNadj }
  , { walsCode := "mau", iso := "mph", value := .voAndAdjn }
  , { walsCode := "may", iso := "ayz", value := .voAndNadj }
  , { walsCode := "myg", iso := "mdm", value := .voAndAdjn }
  , { walsCode := "mzc", iso := "maq", value := .voAndNadj }
  , { walsCode := "mzh", iso := "mau", value := .other }
  , { walsCode := "mba", iso := "mfc", value := .voAndNadj }
  , { walsCode := "mbr", iso := "mpk", value := .voAndNadj }
  , { walsCode := "mby", iso := "myb", value := .voAndNadj }
  , { walsCode := "mbe", iso := "mdt", value := .voAndNadj }
  , { walsCode := "mbi", iso := "baw", value := .voAndNadj }
  , { walsCode := "mdo", iso := "gmm", value := .voAndAdjn }
  , { walsCode := "mbl", iso := "mdq", value := .voAndNadj }
  , { walsCode := "mdw", iso := "mdw", value := .voAndNadj }
  , { walsCode := "mbm", iso := "mdd", value := .voAndNadj }
  , { walsCode := "mee", iso := "mym", value := .voAndNadj }
  , { walsCode := "meh", iso := "gdq", value := .voAndNadj }
  , { walsCode := "mei", iso := "mni", value := .other }
  , { walsCode := "mek", iso := "skf", value := .ovAndNadj }
  , { walsCode := "mke", iso := "mek", value := .ovAndNadj }
  , { walsCode := "mde", iso := "men", value := .ovAndNadj }
  , { walsCode := "men", iso := "mez", value := .other }
  , { walsCode := "mey", iso := "mcr", value := .ovAndNadj }
  , { walsCode := "mer", iso := "ulk", value := .ovAndAdjn }
  , { walsCode := "mea", iso := "mej", value := .voAndNadj }
  , { walsCode := "mpt", iso := "mpt", value := .ovAndNadj }
  , { walsCode := "mie", iso := "ium", value := .voAndNadj }
  , { walsCode := "mii", iso := "", value := .ovAndNadj }
  , { walsCode := "mij", iso := "mxj", value := .ovAndNadj }
  , { walsCode := "mik", iso := "mjw", value := .other }
  , { walsCode := "mil", iso := "", value := .ovAndAdjn }
  , { walsCode := "hna", iso := "hna", value := .voAndNadj }
  , { walsCode := "min", iso := "min", value := .other }
  , { walsCode := "mnv", iso := "mvn", value := .ovAndNadj }
  , { walsCode := "mir", iso := "mep", value := .other }
  , { walsCode := "msg", iso := "mrg", value := .ovAndAdjn }
  , { walsCode := "mis", iso := "miq", value := .ovAndNadj }
  , { walsCode := "mss", iso := "skd", value := .other }
  , { walsCode := "mxx", iso := "mxp", value := .other }
  , { walsCode := "mxc", iso := "mig", value := .voAndNadj }
  , { walsCode := "mxj", iso := "mio", value := .voAndNadj }
  , { walsCode := "mxo", iso := "mie", value := .voAndNadj }
  , { walsCode := "mxp", iso := "mil", value := .voAndNadj }
  , { walsCode := "mxy", iso := "mpm", value := .voAndNadj }
  , { walsCode := "miy", iso := "mkf", value := .voAndNadj }
  , { walsCode := "miz", iso := "lus", value := .ovAndNadj }
  , { walsCode := "mlm", iso := "mra", value := .voAndNadj }
  , { walsCode := "mcv", iso := "moc", value := .other }
  , { walsCode := "mof", iso := "mif", value := .voAndNadj }
  , { walsCode := "moh", iso := "moh", value := .other }
  , { walsCode := "mok", iso := "mkj", value := .voAndNadj }
  , { walsCode := "mon", iso := "mnw", value := .voAndNadj }
  , { walsCode := "mga", iso := "ndt", value := .voAndNadj }
  , { walsCode := "mgo", iso := "lol", value := .voAndNadj }
  , { walsCode := "moa", iso := "mte", value := .other }
  , { walsCode := "mbo", iso := "mxk", value := .ovAndNadj }
  , { walsCode := "moo", iso := "mos", value := .voAndNadj }
  , { walsCode := "mor", iso := "mhz", value := .voAndNadj }
  , { walsCode := "moe", iso := "myv", value := .voAndAdjn }
  , { walsCode := "mro", iso := "mor", value := .voAndNadj }
  , { walsCode := "mou", iso := "mgd", value := .other }
  , { walsCode := "mos", iso := "cas", value := .other }
  , { walsCode := "mtu", iso := "meu", value := .ovAndNadj }
  , { walsCode := "mot", iso := "siw", value := .ovAndNadj }
  , { walsCode := "mpo", iso := "mye", value := .voAndNadj }
  , { walsCode := "mpu", iso := "akc", value := .voAndNadj }
  , { walsCode := "aoj", iso := "aoj", value := .voAndNadj }
  , { walsCode := "msc", iso := "chb", value := .ovAndNadj }
  , { walsCode := "mum", iso := "mzm", value := .voAndNadj }
  , { walsCode := "mna", iso := "mnb", value := .voAndNadj }
  , { walsCode := "mdg", iso := "mua", value := .voAndNadj }
  , { walsCode := "mun", iso := "unr", value := .ovAndAdjn }
  , { walsCode := "mgk", iso := "mhk", value := .voAndNadj }
  , { walsCode := "mup", iso := "sur", value := .voAndNadj }
  , { walsCode := "mrl", iso := "mur", value := .voAndNadj }
  , { walsCode := "mpa", iso := "mwf", value := .ovAndNadj }
  , { walsCode := "mur", iso := "muz", value := .voAndNadj }
  , { walsCode := "mrw", iso := "zmu", value := .other }
  , { walsCode := "mgu", iso := "mug", value := .voAndNadj }
  , { walsCode := "msm", iso := "msu", value := .voAndNadj }
  , { walsCode := "msq", iso := "hur", value := .voAndAdjn }
  , { walsCode := "mus", iso := "emi", value := .voAndAdjn }
  , { walsCode := "mwe", iso := "mwe", value := .voAndNadj }
  , { walsCode := "mwo", iso := "mlv", value := .voAndNadj }
  , { walsCode := "nab", iso := "naf", value := .ovAndNadj }
  , { walsCode := "ndr", iso := "wyy", value := .voAndNadj }
  , { walsCode := "nma", iso := "nbi", value := .ovAndNadj }
  , { walsCode := "ngt", iso := "nmf", value := .ovAndNadj }
  , { walsCode := "nze", iso := "nzm", value := .ovAndNadj }
  , { walsCode := "nag", iso := "nce", value := .other }
  , { walsCode := "nhh", iso := "", value := .voAndNadj }
  , { walsCode := "nhm", iso := "ncl", value := .voAndNadj }
  , { walsCode := "nhn", iso := "ncj", value := .other }
  , { walsCode := "nht", iso := "nhg", value := .voAndNadj }
  , { walsCode := "bio", iso := "bio", value := .other }
  , { walsCode := "nak", iso := "nak", value := .voAndNadj }
  , { walsCode := "nal", iso := "nal", value := .voAndNadj }
  , { walsCode := "kho", iso := "naq", value := .ovAndAdjn }
  , { walsCode := "nam", iso := "nnm", value := .ovAndNadj }
  , { walsCode := "nnc", iso := "ncb", value := .voAndNadj }
  , { walsCode := "nan", iso := "niq", value := .voAndNadj }
  , { walsCode := "nnk", iso := "nnk", value := .ovAndNadj }
  , { walsCode := "nph", iso := "npa", value := .ovAndNadj }
  , { walsCode := "nar", iso := "nrb", value := .ovAndNadj }
  , { walsCode := "nas", iso := "nas", value := .other }
  , { walsCode := "nat", iso := "ncz", value := .ovAndNadj }
  , { walsCode := "nau", iso := "nau", value := .voAndNadj }
  , { walsCode := "nav", iso := "nav", value := .ovAndNadj }
  , { walsCode := "ncm", iso := "bud", value := .voAndNadj }
  , { walsCode := "ndb", iso := "nde", value := .voAndNadj }
  , { walsCode := "ndj", iso := "djj", value := .ovAndNadj }
  , { walsCode := "ndo", iso := "ndo", value := .voAndNadj }
  , { walsCode := "ndu", iso := "nmd", value := .voAndNadj }
  , { walsCode := "ndt", iso := "ndv", value := .voAndNadj }
  , { walsCode := "ndy", iso := "djk", value := .voAndAdjn }
  , { walsCode := "neh", iso := "nsn", value := .voAndNadj }
  , { walsCode := "nnd", iso := "anh", value := .ovAndNadj }
  , { walsCode := "ntu", iso := "yrk", value := .ovAndAdjn }
  , { walsCode := "naj", iso := "aij", value := .ovAndNadj }
  , { walsCode := "nep", iso := "npi", value := .ovAndAdjn }
  , { walsCode := "nev", iso := "pia", value := .ovAndAdjn }
  , { walsCode := "nwd", iso := "new", value := .ovAndAdjn }
  , { walsCode := "new", iso := "new", value := .ovAndAdjn }
  , { walsCode := "ney", iso := "ney", value := .other }
  , { walsCode := "nez", iso := "nez", value := .other }
  , { walsCode := "ntj", iso := "ntj", value := .ovAndNadj }
  , { walsCode := "ngd", iso := "nxg", value := .voAndNadj }
  , { walsCode := "ngj", iso := "nju", value := .ovAndNadj }
  , { walsCode := "ngl", iso := "nig", value := .other }
  , { walsCode := "nkb", iso := "ngk", value := .ovAndNadj }
  , { walsCode := "ngm", iso := "sba", value := .voAndNadj }
  , { walsCode := "ngg", iso := "nam", value := .ovAndNadj }
  , { walsCode := "nga", iso := "nio", value := .ovAndAdjn }
  , { walsCode := "ngn", iso := "nid", value := .ovAndNadj }
  , { walsCode := "ngk", iso := "nam", value := .other }
  , { walsCode := "ngw", iso := "nxn", value := .other }
  , { walsCode := "ndi", iso := "ngb", value := .voAndNadj }
  , { walsCode := "nti", iso := "niy", value := .other }
  , { walsCode := "ngi", iso := "wyb", value := .other }
  , { walsCode := "ngz", iso := "ngi", value := .voAndNadj }
  , { walsCode := "ngo", iso := "ngo", value := .voAndNadj }
  , { walsCode := "ngu", iso := "llp", value := .voAndNadj }
  , { walsCode := "nbr", iso := "gym", value := .ovAndNadj }
  , { walsCode := "nha", iso := "nha", value := .other }
  , { walsCode := "nia", iso := "nia", value := .voAndNadj }
  , { walsCode := "nca", iso := "caq", value := .voAndAdjn }
  , { walsCode := "nsn", iso := "nsz", value := .ovAndAdjn }
  , { walsCode := "nsg", iso := "ncg", value := .voAndAdjn }
  , { walsCode := "nif", iso := "num", value := .voAndNadj }
  , { walsCode := "niu", iso := "niu", value := .voAndNadj }
  , { walsCode := "niv", iso := "niv", value := .ovAndAdjn }
  , { walsCode := "nke", iso := "isi", value := .other }
  , { walsCode := "nkn", iso := "nko", value := .voAndNadj }
  , { walsCode := "nko", iso := "cgg", value := .voAndNadj }
  , { walsCode := "noc", iso := "njb", value := .ovAndNadj }
  , { walsCode := "nog", iso := "nog", value := .ovAndAdjn }
  , { walsCode := "non", iso := "nhu", value := .voAndNadj }
  , { walsCode := "noo", iso := "snf", value := .voAndNadj }
  , { walsCode := "nor", iso := "nor", value := .voAndAdjn }
  , { walsCode := "nse", iso := "nse", value := .voAndNadj }
  , { walsCode := "nto", iso := "nto", value := .voAndNadj }
  , { walsCode := "nua", iso := "nxl", value := .voAndNadj }
  , { walsCode := "nbd", iso := "dgl", value := .ovAndNadj }
  , { walsCode := "nku", iso := "xnz", value := .ovAndNadj }
  , { walsCode := "nue", iso := "nus", value := .other }
  , { walsCode := "nun", iso := "nut", value := .voAndNadj }
  , { walsCode := "nug", iso := "nuy", value := .other }
  , { walsCode := "yi", iso := "iii", value := .ovAndNadj }
  , { walsCode := "nup", iso := "nup", value := .voAndNadj }
  , { walsCode := "nus", iso := "nuf", value := .ovAndNadj }
  , { walsCode := "nuu", iso := "nuk", value := .other }
  , { walsCode := "nyk", iso := "tpq", value := .ovAndNadj }
  , { walsCode := "nym", iso := "nym", value := .voAndNadj }
  , { walsCode := "nyr", iso := "nna", value := .other }
  , { walsCode := "nyi", iso := "nyi", value := .ovAndNadj }
  , { walsCode := "nis", iso := "njz", value := .ovAndAdjn }
  , { walsCode := "nza", iso := "nzk", value := .voAndAdjn }
  , { walsCode := "ood", iso := "ood", value := .voAndAdjn }
  , { walsCode := "obo", iso := "ann", value := .other }
  , { walsCode := "ocu", iso := "ocu", value := .voAndAdjn }
  , { walsCode := "obg", iso := "ogu", value := .voAndAdjn }
  , { walsCode := "oks", iso := "opm", value := .other }
  , { walsCode := "olo", iso := "ong", value := .voAndNadj }
  , { walsCode := "omh", iso := "oma", value := .ovAndNadj }
  , { walsCode := "ord", iso := "mvf", value := .ovAndAdjn }
  , { walsCode := "ori", iso := "tag", value := .ovAndNadj }
  , { walsCode := "ork", iso := "oaa", value := .ovAndNadj }
  , { walsCode := "oro", iso := "okv", value := .ovAndNadj }
  , { walsCode := "orh", iso := "hae", value := .ovAndNadj }
  , { walsCode := "orw", iso := "ssn", value := .ovAndNadj }
  , { walsCode := "ory", iso := "ury", value := .ovAndNadj }
  , { walsCode := "osa", iso := "osa", value := .ovAndNadj }
  , { walsCode := "oss", iso := "oss", value := .ovAndAdjn }
  , { walsCode := "otm", iso := "ote", value := .voAndAdjn }
  , { walsCode := "otr", iso := "otr", value := .voAndNadj }
  , { walsCode := "paa", iso := "pqa", value := .voAndAdjn }
  , { walsCode := "pkn", iso := "drl", value := .voAndAdjn }
  , { walsCode := "pms", iso := "pma", value := .voAndNadj }
  , { walsCode := "pno", iso := "pao", value := .ovAndAdjn }
  , { walsCode := "pai", iso := "pwn", value := .voAndNadj }
  , { walsCode := "pal", iso := "pau", value := .voAndAdjn }
  , { walsCode := "plg", iso := "pll", value := .voAndNadj }
  , { walsCode := "plk", iso := "plu", value := .voAndNadj }
  , { walsCode := "pam", iso := "pmz", value := .voAndNadj }
  , { walsCode := "pnx", iso := "kre", value := .other }
  , { walsCode := "pnn", iso := "pag", value := .other }
  , { walsCode := "png", iso := "pbr", value := .voAndNadj }
  , { walsCode := "pan", iso := "pan", value := .ovAndAdjn }
  , { walsCode := "pny", iso := "pnw", value := .other }
  , { walsCode := "pre", iso := "asa", value := .voAndNadj }
  , { walsCode := "psh", iso := "pst", value := .ovAndAdjn }
  , { walsCode := "pat", iso := "ptp", value := .voAndNadj }
  , { walsCode := "ptt", iso := "lae", value := .ovAndAdjn }
  , { walsCode := "plh", iso := "plh", value := .voAndNadj }
  , { walsCode := "pau", iso := "pad", value := .other }
  , { walsCode := "paw", iso := "pwa", value := .ovAndAdjn }
  , { walsCode := "per", iso := "pip", value := .voAndNadj }
  , { walsCode := "prs", iso := "pes", value := .ovAndNadj }
  , { walsCode := "pia", iso := "pid", value := .ovAndNadj }
  , { walsCode := "pga", iso := "plg", value := .voAndNadj }
  , { walsCode := "pba", iso := "pia", value := .ovAndAdjn }
  , { walsCode := "pip", iso := "ppl", value := .voAndAdjn }
  , { walsCode := "prh", iso := "myp", value := .ovAndNadj }
  , { walsCode := "pir", iso := "pib", value := .ovAndNadj }
  , { walsCode := "pit", iso := "pjt", value := .ovAndNadj }
  , { walsCode := "ppi", iso := "pit", value := .other }
  , { walsCode := "pod", iso := "pbi", value := .other }
  , { walsCode := "poh", iso := "pon", value := .voAndNadj }
  , { walsCode := "pok", iso := "rwa", value := .other }
  , { walsCode := "pkt", iso := "pko", value := .voAndNadj }
  , { walsCode := "pol", iso := "pol", value := .voAndAdjn }
  , { walsCode := "psw", iso := "psw", value := .voAndNadj }
  , { walsCode := "por", iso := "por", value := .voAndNadj }
  , { walsCode := "pra", iso := "prn", value := .ovAndAdjn }
  , { walsCode := "pul", iso := "puw", value := .voAndNadj }
  , { walsCode := "pun", iso := "wdj", value := .ovAndNadj }
  , { walsCode := "prk", iso := "prx", value := .ovAndAdjn }
  , { walsCode := "pur", iso := "tsz", value := .voAndNadj }
  , { walsCode := "pae", iso := "pbb", value := .ovAndNadj }
  , { walsCode := "par", iso := "lkr", value := .ovAndNadj }
  , { walsCode := "qaf", iso := "aar", value := .ovAndAdjn }
  , { walsCode := "qhu", iso := "qub", value := .ovAndAdjn }
  , { walsCode := "qim", iso := "qvi", value := .ovAndAdjn }
  , { walsCode := "qui", iso := "qui", value := .voAndAdjn }
  , { walsCode := "rag", iso := "lml", value := .voAndNadj }
  , { walsCode := "rji", iso := "rji", value := .other }
  , { walsCode := "ral", iso := "ral", value := .ovAndNadj }
  , { walsCode := "ram", iso := "rma", value := .ovAndNadj }
  , { walsCode := "rpa", iso := "bod", value := .ovAndAdjn }
  , { walsCode := "rao", iso := "rao", value := .ovAndNadj }
  , { walsCode := "rap", iso := "rap", value := .voAndNadj }
  , { walsCode := "ras", iso := "ras", value := .ovAndNadj }
  , { walsCode := "rwa", iso := "rwo", value := .ovAndNadj }
  , { walsCode := "raw", iso := "raw", value := .ovAndNadj }
  , { walsCode := "rem", iso := "bfw", value := .ovAndAdjn }
  , { walsCode := "res", iso := "rgr", value := .ovAndAdjn }
  , { walsCode := "ret", iso := "tnc", value := .ovAndAdjn }
  , { walsCode := "rit", iso := "rit", value := .other }
  , { walsCode := "rwe", iso := "rmw", value := .voAndAdjn }
  , { walsCode := "rom", iso := "ron", value := .voAndNadj }
  , { walsCode := "rsu", iso := "roh", value := .voAndNadj }
  , { walsCode := "rga", iso := "rng", value := .voAndNadj }
  ]

private def allData_2 : List (Datapoint RelationshipBetweenTheOrderOfObjectAndVerbAndTheOrderOfAdjectiveAndNoun) :=
  [ { walsCode := "rot", iso := "rtm", value := .voAndNadj }
  , { walsCode := "rov", iso := "rug", value := .voAndNadj }
  , { walsCode := "ruk", iso := "dru", value := .other }
  , { walsCode := "rum", iso := "klq", value := .ovAndNadj }
  , { walsCode := "run", iso := "rou", value := .ovAndNadj }
  , { walsCode := "rny", iso := "nyn", value := .voAndNadj }
  , { walsCode := "rru", iso := "nyo", value := .voAndNadj }
  , { walsCode := "rus", iso := "rus", value := .voAndAdjn }
  , { walsCode := "rut", iso := "rut", value := .ovAndAdjn }
  , { walsCode := "sno", iso := "sme", value := .voAndAdjn }
  , { walsCode := "sah", iso := "saj", value := .voAndNadj }
  , { walsCode := "sak", iso := "sku", value := .voAndNadj }
  , { walsCode := "slb", iso := "sbe", value := .ovAndNadj }
  , { walsCode := "sal", iso := "sln", value := .other }
  , { walsCode := "syu", iso := "sll", value := .ovAndNadj }
  , { walsCode := "sle", iso := "ndi", value := .voAndNadj }
  , { walsCode := "sam", iso := "smo", value := .voAndNadj }
  , { walsCode := "sdw", iso := "sad", value := .ovAndNadj }
  , { walsCode := "san", iso := "sag", value := .voAndAdjn }
  , { walsCode := "sgu", iso := "snq", value := .voAndNadj }
  , { walsCode := "sta", iso := "sce", value := .ovAndAdjn }
  , { walsCode := "stl", iso := "sat", value := .ovAndAdjn }
  , { walsCode := "snm", iso := "xsu", value := .ovAndNadj }
  , { walsCode := "sap", iso := "spu", value := .voAndNadj }
  , { walsCode := "src", iso := "srs", value := .ovAndNadj }
  , { walsCode := "srd", iso := "sro", value := .voAndNadj }
  , { walsCode := "sar", iso := "dju", value := .ovAndAdjn }
  , { walsCode := "sav", iso := "sdg", value := .ovAndAdjn }
  , { walsCode := "svs", iso := "svs", value := .ovAndAdjn }
  , { walsCode := "seb", iso := "kpz", value := .voAndNadj }
  , { walsCode := "sed", iso := "sed", value := .voAndNadj }
  , { walsCode := "see", iso := "trv", value := .other }
  , { walsCode := "sel", iso := "ona", value := .ovAndAdjn }
  , { walsCode := "skp", iso := "sel", value := .ovAndAdjn }
  , { walsCode := "sem", iso := "nsm", value := .ovAndNadj }
  , { walsCode := "sme", iso := "sif", value := .ovAndNadj }
  , { walsCode := "sml", iso := "sza", value := .voAndNadj }
  , { walsCode := "smn", iso := "mus", value := .ovAndNadj }
  , { walsCode := "snc", iso := "see", value := .other }
  , { walsCode := "snt", iso := "set", value := .ovAndNadj }
  , { walsCode := "scr", iso := "hbs", value := .voAndAdjn }
  , { walsCode := "ser", iso := "sei", value := .other }
  , { walsCode := "ses", iso := "sot", value := .voAndNadj }
  , { walsCode := "shb", iso := "sbf", value := .ovAndAdjn }
  , { walsCode := "shm", iso := "ksb", value := .voAndNadj }
  , { walsCode := "sht", iso := "shj", value := .voAndNadj }
  , { walsCode := "she", iso := "xsr", value := .ovAndNadj }
  , { walsCode := "shl", iso := "shk", value := .voAndNadj }
  , { walsCode := "sna", iso := "scl", value := .ovAndAdjn }
  , { walsCode := "shk", iso := "shp", value := .other }
  , { walsCode := "shi", iso := "shb", value := .ovAndNadj }
  , { walsCode := "smp", iso := "sii", value := .voAndAdjn }
  , { walsCode := "shn", iso := "sna", value := .voAndNadj }
  , { walsCode := "sho", iso := "shh", value := .ovAndAdjn }
  , { walsCode := "sia", iso := "snp", value := .ovAndNadj }
  , { walsCode := "sir", iso := "sjr", value := .voAndAdjn }
  , { walsCode := "sid", iso := "sid", value := .ovAndAdjn }
  , { walsCode := "skk", iso := "sip", value := .ovAndNadj }
  , { walsCode := "sil", iso := "dau", value := .ovAndNadj }
  , { walsCode := "sim", iso := "smr", value := .voAndNadj }
  , { walsCode := "sng", iso := "snc", value := .ovAndNadj }
  , { walsCode := "snh", iso := "sin", value := .ovAndAdjn }
  , { walsCode := "sio", iso := "xsi", value := .voAndNadj }
  , { walsCode := "sin", iso := "snn", value := .ovAndAdjn }
  , { walsCode := "qum", iso := "qum", value := .voAndAdjn }
  , { walsCode := "srn", iso := "srq", value := .ovAndNadj }
  , { walsCode := "sro", iso := "ssd", value := .ovAndNadj }
  , { walsCode := "sis", iso := "baa", value := .voAndNadj }
  , { walsCode := "siu", iso := "sis", value := .voAndAdjn }
  , { walsCode := "sko", iso := "skv", value := .ovAndNadj }
  , { walsCode := "sla", iso := "den", value := .ovAndNadj }
  , { walsCode := "slo", iso := "slv", value := .voAndAdjn }
  , { walsCode := "so", iso := "teu", value := .voAndNadj }
  , { walsCode := "sob", iso := "sob", value := .voAndNadj }
  , { walsCode := "sod", iso := "gru", value := .ovAndAdjn }
  , { walsCode := "som", iso := "som", value := .ovAndNadj }
  , { walsCode := "snn", iso := "snk", value := .ovAndNadj }
  , { walsCode := "son", iso := "sov", value := .other }
  , { walsCode := "srb", iso := "", value := .ovAndAdjn }
  , { walsCode := "sgb", iso := "mnx", value := .voAndNadj }
  , { walsCode := "sea", iso := "tvk", value := .voAndNadj }
  , { walsCode := "spa", iso := "spa", value := .voAndNadj }
  , { walsCode := "spi", iso := "spt", value := .ovAndNadj }
  , { walsCode := "squ", iso := "squ", value := .voAndAdjn }
  , { walsCode := "sre", iso := "kpm", value := .voAndNadj }
  , { walsCode := "sti", iso := "", value := .voAndNadj }
  , { walsCode := "sud", iso := "tgo", value := .voAndNadj }
  , { walsCode := "sue", iso := "sue", value := .ovAndNadj }
  , { walsCode := "suk", iso := "sui", value := .ovAndAdjn }
  , { walsCode := "sku", iso := "sub", value := .voAndNadj }
  , { walsCode := "sul", iso := "sua", value := .voAndNadj }
  , { walsCode := "sun", iso := "sun", value := .voAndNadj }
  , { walsCode := "sup", iso := "spp", value := .ovAndNadj }
  , { walsCode := "swa", iso := "swh", value := .voAndNadj }
  , { walsCode := "swt", iso := "ssw", value := .other }
  , { walsCode := "swe", iso := "swe", value := .voAndAdjn }
  , { walsCode := "tab", iso := "mky", value := .voAndNadj }
  , { walsCode := "tba", iso := "sst", value := .ovAndNadj }
  , { walsCode := "tbl", iso := "tnm", value := .ovAndNadj }
  , { walsCode := "tbw", iso := "tap", value := .voAndNadj }
  , { walsCode := "tac", iso := "tna", value := .other }
  , { walsCode := "tag", iso := "tgl", value := .other }
  , { walsCode := "tah", iso := "tah", value := .voAndNadj }
  , { walsCode := "taf", iso := "sps", value := .voAndNadj }
  , { walsCode := "trr", iso := "tbg", value := .other }
  , { walsCode := "taj", iso := "tgk", value := .ovAndNadj }
  , { walsCode := "tkl", iso := "tkm", value := .ovAndNadj }
  , { walsCode := "tak", iso := "tbc", value := .ovAndNadj }
  , { walsCode := "tls", iso := "shm", value := .ovAndAdjn }
  , { walsCode := "tma", iso := "tma", value := .ovAndNadj }
  , { walsCode := "tmm", iso := "mla", value := .voAndNadj }
  , { walsCode := "tam", iso := "taj", value := .ovAndAdjn }
  , { walsCode := "tsk", iso := "taq", value := .voAndNadj }
  , { walsCode := "tml", iso := "tam", value := .ovAndAdjn }
  , { walsCode := "tnc", iso := "tcb", value := .ovAndNadj }
  , { walsCode := "tce", iso := "tar", value := .ovAndAdjn }
  , { walsCode := "twe", iso := "tac", value := .ovAndAdjn }
  , { walsCode := "tao", iso := "tro", value := .ovAndNadj }
  , { walsCode := "tar", iso := "tae", value := .other }
  , { walsCode := "tat", iso := "txx", value := .voAndNadj }
  , { walsCode := "tvo", iso := "tat", value := .ovAndAdjn }
  , { walsCode := "tsg", iso := "tsg", value := .voAndNadj }
  , { walsCode := "tau", iso := "tya", value := .ovAndNadj }
  , { walsCode := "taw", iso := "tbo", value := .ovAndNadj }
  , { walsCode := "tbo", iso := "tbl", value := .voAndNadj }
  , { walsCode := "tlf", iso := "tlf", value := .ovAndNadj }
  , { walsCode := "tel", iso := "tel", value := .ovAndAdjn }
  , { walsCode := "tmn", iso := "teq", value := .voAndNadj }
  , { walsCode := "tmr", iso := "tea", value := .voAndNadj }
  , { walsCode := "tne", iso := "tem", value := .voAndNadj }
  , { walsCode := "ten", iso := "tex", value := .voAndNadj }
  , { walsCode := "tny", iso := "kza", value := .ovAndNadj }
  , { walsCode := "teo", iso := "tio", value := .voAndNadj }
  , { walsCode := "tee", iso := "tee", value := .voAndAdjn }
  , { walsCode := "tep", iso := "tpt", value := .voAndAdjn }
  , { walsCode := "tpn", iso := "ntp", value := .other }
  , { walsCode := "tps", iso := "stp", value := .voAndNadj }
  , { walsCode := "ter", iso := "ttr", value := .voAndNadj }
  , { walsCode := "trb", iso := "tfr", value := .ovAndNadj }
  , { walsCode := "tes", iso := "teo", value := .voAndNadj }
  , { walsCode := "ttn", iso := "tet", value := .voAndNadj }
  , { walsCode := "ttd", iso := "tet", value := .voAndNadj }
  , { walsCode := "tha", iso := "tha", value := .voAndNadj }
  , { walsCode := "thk", iso := "ths", value := .ovAndAdjn }
  , { walsCode := "thn", iso := "thf", value := .ovAndAdjn }
  , { walsCode := "tho", iso := "thp", value := .voAndAdjn }
  , { walsCode := "thu", iso := "tdh", value := .ovAndAdjn }
  , { walsCode := "tdi", iso := "bod", value := .ovAndNadj }
  , { walsCode := "tdr", iso := "bod", value := .ovAndNadj }
  , { walsCode := "tmo", iso := "bod", value := .ovAndNadj }
  , { walsCode := "tis", iso := "bod", value := .other }
  , { walsCode := "tib", iso := "bod", value := .ovAndNadj }
  , { walsCode := "tic", iso := "tca", value := .other }
  , { walsCode := "tid", iso := "tvo", value := .voAndNadj }
  , { walsCode := "tgk", iso := "tgc", value := .voAndNadj }
  , { walsCode := "tig", iso := "tir", value := .ovAndAdjn }
  , { walsCode := "tgr", iso := "tig", value := .ovAndAdjn }
  , { walsCode := "tja", iso := "dih", value := .other }
  , { walsCode := "tik", iso := "tik", value := .other }
  , { walsCode := "tia", iso := "tms", value := .voAndNadj }
  , { walsCode := "tim", iso := "tih", value := .voAndNadj }
  , { walsCode := "tni", iso := "lbf", value := .ovAndAdjn }
  , { walsCode := "tin", iso := "cir", value := .voAndAdjn }
  , { walsCode := "tiv", iso := "tiv", value := .other }
  , { walsCode := "twn", iso := "twf", value := .other }
  , { walsCode := "tiw", iso := "tiw", value := .voAndAdjn }
  , { walsCode := "tlp", iso := "tcf", value := .voAndNadj }
  , { walsCode := "tli", iso := "tli", value := .other }
  , { walsCode := "tob", iso := "tob", value := .voAndAdjn }
  , { walsCode := "tbt", iso := "tti", value := .ovAndNadj }
  , { walsCode := "tla", iso := "ksd", value := .other }
  , { walsCode := "tno", iso := "tdn", value := .voAndNadj }
  , { walsCode := "toz", iso := "toi", value := .voAndNadj }
  , { walsCode := "tng", iso := "ton", value := .voAndNadj }
  , { walsCode := "ton", iso := "tqw", value := .ovAndNadj }
  , { walsCode := "trw", iso := "trw", value := .ovAndAdjn }
  , { walsCode := "tot", iso := "tlc", value := .other }
  , { walsCode := "txj", iso := "too", value := .voAndAdjn }
  , { walsCode := "tri", iso := "trc", value := .voAndNadj }
  , { walsCode := "tru", iso := "tpy", value := .other }
  , { walsCode := "tsf", iso := "cof", value := .ovAndAdjn }
  , { walsCode := "tsz", iso := "ddo", value := .ovAndAdjn }
  , { walsCode := "tgl", iso := "tsj", value := .ovAndAdjn }
  , { walsCode := "tsi", iso := "tsi", value := .voAndAdjn }
  , { walsCode := "ttu", iso := "bbl", value := .ovAndAdjn }
  , { walsCode := "tbu", iso := "", value := .ovAndNadj }
  , { walsCode := "tuc", iso := "tuo", value := .other }
  , { walsCode := "tgn", iso := "tzn", value := .voAndNadj }
  , { walsCode := "tuk", iso := "", value := .voAndNadj }
  , { walsCode := "tul", iso := "tcy", value := .ovAndAdjn }
  , { walsCode := "tum", iso := "tmq", value := .voAndNadj }
  , { walsCode := "tnn", iso := "tvu", value := .ovAndNadj }
  , { walsCode := "tnk", iso := "lcm", value := .voAndNadj }
  , { walsCode := "tun", iso := "tun", value := .ovAndNadj }
  , { walsCode := "tpr", iso := "tui", value := .voAndNadj }
  , { walsCode := "tna", iso := "tuv", value := .voAndNadj }
  , { walsCode := "tur", iso := "tur", value := .ovAndAdjn }
  , { walsCode := "tkm", iso := "tuk", value := .ovAndAdjn }
  , { walsCode := "tus", iso := "tus", value := .other }
  , { walsCode := "tvt", iso := "tvt", value := .other }
  , { walsCode := "tvl", iso := "tvl", value := .ovAndNadj }
  , { walsCode := "tuv", iso := "tyv", value := .ovAndAdjn }
  , { walsCode := "tzu", iso := "tzj", value := .other }
  , { walsCode := "tsh", iso := "par", value := .ovAndAdjn }
  , { walsCode := "uby", iso := "uby", value := .ovAndAdjn }
  , { walsCode := "udi", iso := "udi", value := .ovAndAdjn }
  , { walsCode := "udh", iso := "ude", value := .ovAndAdjn }
  , { walsCode := "udm", iso := "udm", value := .ovAndAdjn }
  , { walsCode := "ukr", iso := "ukr", value := .voAndAdjn }
  , { walsCode := "uld", iso := "udl", value := .voAndNadj }
  , { walsCode := "uli", iso := "uli", value := .voAndNadj }
  , { walsCode := "una", iso := "mtg", value := .ovAndNadj }
  , { walsCode := "ung", iso := "ung", value := .ovAndNadj }
  , { walsCode := "ura", iso := "uur", value := .voAndNadj }
  , { walsCode := "uhi", iso := "urf", value := .ovAndNadj }
  , { walsCode := "url", iso := "urk", value := .voAndNadj }
  , { walsCode := "urn", iso := "ura", value := .ovAndNadj }
  , { walsCode := "urt", iso := "urt", value := .voAndNadj }
  , { walsCode := "urd", iso := "urd", value := .ovAndAdjn }
  , { walsCode := "uru", iso := "ure", value := .other }
  , { walsCode := "urk", iso := "urb", value := .ovAndNadj }
  , { walsCode := "usa", iso := "wnu", value := .ovAndNadj }
  , { walsCode := "usr", iso := "usa", value := .ovAndAdjn }
  , { walsCode := "ute", iso := "ute", value := .ovAndNadj }
  , { walsCode := "uyg", iso := "uig", value := .ovAndAdjn }
  , { walsCode := "uzb", iso := "", value := .ovAndAdjn }
  , { walsCode := "vaf", iso := "vaf", value := .ovAndNadj }
  , { walsCode := "vai", iso := "vai", value := .ovAndNadj }
  , { walsCode := "ven", iso := "ven", value := .voAndNadj }
  , { walsCode := "vie", iso := "vie", value := .voAndNadj }
  , { walsCode := "vnm", iso := "vnm", value := .voAndNadj }
  , { walsCode := "wag", iso := "waq", value := .ovAndNadj }
  , { walsCode := "wah", iso := "", value := .ovAndNadj }
  , { walsCode := "wak", iso := "wbl", value := .ovAndAdjn }
  , { walsCode := "wal", iso := "van", value := .voAndNadj }
  , { walsCode := "wbn", iso := "wms", value := .ovAndNadj }
  , { walsCode := "wme", iso := "wme", value := .ovAndAdjn }
  , { walsCode := "wna", iso := "wan", value := .ovAndNadj }
  , { walsCode := "wan", iso := "xwk", value := .other }
  , { walsCode := "wao", iso := "auc", value := .other }
  , { walsCode := "wap", iso := "wao", value := .ovAndNadj }
  , { walsCode := "wra", iso := "wba", value := .ovAndNadj }
  , { walsCode := "wrd", iso := "wrr", value := .other }
  , { walsCode := "wrk", iso := "gae", value := .voAndNadj }
  , { walsCode := "wrm", iso := "wsa", value := .voAndNadj }
  , { walsCode := "wrl", iso := "wbp", value := .other }
  , { walsCode := "wrg", iso := "wgy", value := .other }
  , { walsCode := "wrw", iso := "wwr", value := .other }
  , { walsCode := "was", iso := "was", value := .ovAndAdjn }
  , { walsCode := "wsk", iso := "wsk", value := .ovAndNadj }
  , { walsCode := "wth", iso := "wth", value := .voAndNadj }
  , { walsCode := "wed", iso := "wed", value := .ovAndNadj }
  , { walsCode := "wel", iso := "cym", value := .voAndNadj }
  , { walsCode := "wem", iso := "xww", value := .voAndAdjn }
  , { walsCode := "wma", iso := "mqs", value := .voAndNadj }
  , { walsCode := "wic", iso := "wic", value := .ovAndNadj }
  , { walsCode := "wch", iso := "mzh", value := .voAndNadj }
  , { walsCode := "wmu", iso := "wim", value := .ovAndNadj }
  , { walsCode := "wn", iso := "wig", value := .ovAndNadj }
  , { walsCode := "wik", iso := "yok", value := .other }
  , { walsCode := "win", iso := "wnw", value := .other }
  , { walsCode := "wiy", iso := "wiy", value := .other }
  , { walsCode := "woi", iso := "woi", value := .ovAndNadj }
  , { walsCode := "wly", iso := "wal", value := .ovAndAdjn }
  , { walsCode := "wol", iso := "woe", value := .voAndNadj }
  , { walsCode := "wlo", iso := "wlo", value := .voAndNadj }
  , { walsCode := "wlf", iso := "wol", value := .voAndNadj }
  , { walsCode := "wom", iso := "wmx", value := .ovAndNadj }
  , { walsCode := "xas", iso := "kao", value := .ovAndNadj }
  , { walsCode := "xer", iso := "xer", value := .ovAndNadj }
  , { walsCode := "xho", iso := "xho", value := .voAndNadj }
  , { walsCode := "xar", iso := "ane", value := .voAndAdjn }
  , { walsCode := "ygr", iso := "ygr", value := .ovAndAdjn }
  , { walsCode := "yag", iso := "yad", value := .voAndNadj }
  , { walsCode := "yah", iso := "yag", value := .ovAndAdjn }
  , { walsCode := "ykt", iso := "sah", value := .ovAndAdjn }
  , { walsCode := "yal", iso := "kkl", value := .ovAndNadj }
  , { walsCode := "yam", iso := "yaa", value := .ovAndNadj }
  , { walsCode := "ybi", iso := "ybi", value := .ovAndAdjn }
  , { walsCode := "yao", iso := "yao", value := .voAndNadj }
  , { walsCode := "yap", iso := "yap", value := .voAndNadj }
  , { walsCode := "yaq", iso := "yaq", value := .ovAndAdjn }
  , { walsCode := "yar", iso := "yrb", value := .ovAndAdjn }
  , { walsCode := "ywr", iso := "ywr", value := .other }
  , { walsCode := "yay", iso := "pcc", value := .voAndNadj }
  , { walsCode := "yel", iso := "yle", value := .ovAndNadj }
  , { walsCode := "yid", iso := "yii", value := .ovAndNadj }
  , { walsCode := "yim", iso := "yee", value := .other }
  , { walsCode := "yin", iso := "yij", value := .other }
  , { walsCode := "yng", iso := "yia", value := .voAndAdjn }
  , { walsCode := "yok", iso := "yok", value := .voAndAdjn }
  , { walsCode := "yor", iso := "yor", value := .voAndNadj }
  , { walsCode := "yuc", iso := "yuc", value := .ovAndNadj }
  , { walsCode := "ycn", iso := "ycn", value := .voAndAdjn }
  , { walsCode := "yko", iso := "yux", value := .ovAndAdjn }
  , { walsCode := "ytu", iso := "ykg", value := .ovAndAdjn }
  , { walsCode := "yuk", iso := "gcd", value := .ovAndAdjn }
  , { walsCode := "yul", iso := "yul", value := .voAndNadj }
  , { walsCode := "ypk", iso := "esu", value := .other }
  , { walsCode := "yur", iso := "yur", value := .other }
  , { walsCode := "yuw", iso := "kld", value := .ovAndAdjn }
  , { walsCode := "zan", iso := "zne", value := .voAndAdjn }
  , { walsCode := "zai", iso := "zai", value := .voAndNadj }
  , { walsCode := "zap", iso := "zaw", value := .voAndNadj }
  , { walsCode := "zya", iso := "zav", value := .voAndNadj }
  , { walsCode := "zzo", iso := "zpq", value := .voAndNadj }
  , { walsCode := "zar", iso := "dje", value := .other }
  , { walsCode := "zay", iso := "zay", value := .ovAndAdjn }
  , { walsCode := "zaz", iso := "diq", value := .ovAndNadj }
  , { walsCode := "zch", iso := "zoh", value := .voAndAdjn }
  , { walsCode := "zqc", iso := "zoc", value := .voAndAdjn }
  , { walsCode := "zul", iso := "zul", value := .voAndNadj }
  , { walsCode := "zun", iso := "zun", value := .ovAndNadj }
  , { walsCode := "rgc", iso := "jya", value := .ovAndNadj }
  , { walsCode := "eme", iso := "eme", value := .ovAndNadj }
  , { walsCode := "omi", iso := "aom", value := .ovAndNadj }
  ]

/-- Complete WALS 97A dataset (1316 languages). -/
def allData : List (Datapoint RelationshipBetweenTheOrderOfObjectAndVerbAndTheOrderOfAdjectiveAndNoun) := allData_0 ++ allData_1 ++ allData_2

/-- Look up a language by WALS code. -/
def lookup (code : String) := Datapoint.lookup allData code

/-- Look up a language by ISO 639-3 code. -/
def lookupISO (iso : String) := Datapoint.lookupISO allData iso

end Core.WALS.F97A
