module

public import Linglib.Data.UD.UPOS

/-!
# X-bar categories

A syntactic category is the projection of a head at a bar level, or the clause `S`, which projects
from no head. The bar levels are those of X-bar theory: a head `X⁰`, an intermediate projection
`X′`, and a maximal projection `XP`. Heads are named by their Universal Dependencies part of
speech, so the noun phrase `NP` is the maximal projection of a `NOUN`. Barker and Pullum's
MAX-command is generated by the nodes whose labels are maximal projections, here the categories
of level `max`. `Syntax.Cat` is the default category type of `Syntax.Tree`.

## Main declarations

* `Syntax.BarLevel`: the bar levels.
* `Syntax.Cat`: the categories, with `Cat.level` and the pattern-matchable traditional names
  `N`, `NP`, `CP`, and so on.

## Implementation notes

The bar level is part of the label, as in X-bar theory and Barker and Pullum's `Xᵏ`. Bare phrase
structure instead reads minimal and maximal projections off the tree, which needs a tree that marks
its heads; `Syntax.Tree` does not. The complementizer `C` is `SCONJ`, the tag UD gives
complementizers, and `Neg` is `PART`, the tag of English *not* and of other particles.

## References

* [barker-pullum-1990]
* [de-marneffe-zeman-2021]
-/

@[expose] public section

namespace Syntax

/-- The bar level of a category is that of a head, an intermediate projection, or a maximal
projection. -/
inductive BarLevel where
  /-- `zero` is the level of a head, `X⁰`. -/
  | zero
  /-- `bar` is the level of an intermediate projection, `X′`. -/
  | bar
  /-- `max` is the level of a maximal projection, `XP`. -/
  | max
  deriving DecidableEq, Repr

/-- A syntactic category is the projection of a head of some part of speech at some bar level, or
the clause. -/
inductive Cat where
  /-- `proj pos n` is the projection at bar level `n` of a head of part of speech `pos`. -/
  | proj : UD.UPOS → BarLevel → Cat
  /-- `S` is the clause, which projects from no head. -/
  | S
  deriving DecidableEq, Repr

namespace Cat

instance : Inhabited Cat := ⟨S⟩

/-- `c.level` is the bar level of a projection `c`; the clause has none. -/
def level : Cat → Option BarLevel
  | proj _ n => some n
  | S => none

@[simp] theorem level_proj (pos : UD.UPOS) (n : BarLevel) : (proj pos n).level = some n := rfl

@[simp] theorem level_S : S.level = none := rfl

/-! ### Traditional names

Each name is a `match_pattern`, so it can be used in pattern position. -/

@[match_pattern] abbrev N     : Cat := proj .NOUN .zero
@[match_pattern] abbrev V     : Cat := proj .VERB .zero
@[match_pattern] abbrev Det   : Cat := proj .DET .zero
@[match_pattern] abbrev Adj   : Cat := proj .ADJ .zero
@[match_pattern] abbrev Adv   : Cat := proj .ADV .zero
@[match_pattern] abbrev P     : Cat := proj .ADP .zero
@[match_pattern] abbrev Conj  : Cat := proj .CCONJ .zero
@[match_pattern] abbrev Neg   : Cat := proj .PART .zero
@[match_pattern] abbrev C     : Cat := proj .SCONJ .zero
@[match_pattern] abbrev Num   : Cat := proj .NUM .zero
@[match_pattern] abbrev Pron  : Cat := proj .PRON .zero
@[match_pattern] abbrev Aux   : Cat := proj .AUX .zero

@[match_pattern] abbrev NP    : Cat := proj .NOUN .max
@[match_pattern] abbrev VP    : Cat := proj .VERB .max
@[match_pattern] abbrev DP    : Cat := proj .DET .max
@[match_pattern] abbrev PP    : Cat := proj .ADP .max
@[match_pattern] abbrev AdjP  : Cat := proj .ADJ .max
@[match_pattern] abbrev AdvP  : Cat := proj .ADV .max
@[match_pattern] abbrev ConjP : Cat := proj .CCONJ .max
@[match_pattern] abbrev NegP  : Cat := proj .PART .max
@[match_pattern] abbrev CP    : Cat := proj .SCONJ .max
@[match_pattern] abbrev NumP  : Cat := proj .NUM .max

end Cat

end Syntax
