/-
Copyright (c) 2026 Robert Hawkins. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Robert Hawkins
-/
import Linglib.Core.Computability.Subregular.Language.TierStrictlyLocal
import Linglib.Core.Computability.Subregular.Language.StrictlyPiecewise
import Linglib.Core.Computability.Subregular.Language.PiecewiseTestable
import Linglib.Core.Computability.Subregular.Language.Definite
import Mathlib.Computability.Language
import Mathlib.Order.BooleanSubalgebra
import Linglib.Core.Data.List.Factors

/-!
# Multitier extensions of subregular classes

The Boolean closure of tier-projected language families. For a class
`𝒞 : Language α → Prop`, the multitier closure `IsBTC 𝒞` closes under finite
`⊓`/`⊔`/`ᶜ` the languages that are preimages of a `𝒞`-language under some Boolean
tier projection.

## Main definitions

* `IsTierBased 𝒞` — preimages of `𝒞`-languages under a Boolean tier projection.
* `IsBTC 𝒞` — the multitier closure: the `BooleanSubalgebra.closure` of the
  tier-projected family, with injections `IsBTC.base`/`of_class` and closure
  operations `IsBTC.inter`/`union`/`compl`.
* `IsBTSL`/`IsBTSP`/`IsBTD`/`IsBTK`/`IsBTLI`/`IsBTN` — its six specializations
  (strictly local, strictly piecewise, definite, reverse definite, generalized
  definite, finite-or-cofinite).
* `IsBTC.Indist` — tier-indistinguishability, the congruence behind membership refutation.

## Main results

* `IsBTC.mono` — monotonicity in the base class.
* `IsBTC.mem_iff_of_indist` and `not_isBTC_of_indist` — membership respects
  tier-indistinguishability, yielding the standard non-membership argument.

## Implementation notes

`IsTierBased`/`IsBTC.Indist` quantify over `Bool` tiers `T : α → Bool`, avoiding an
`∃ T, ∃ _ : DecidablePred T, …` witness; the `Prop`-with-`[DecidablePred]` form used by
`tierProject`/`TSLGrammar` converts via `T x ↔ tier x = true`.
-/

namespace Language

open Subregular

variable {α : Type*} {𝒞 𝒟 : Language α → Prop} {L L₁ L₂ : Language α} {k : ℕ}
  {w₁ w₂ : List α}

/-! ## Tier-based language families -/

/-- A language `L` is **tier-based for class `𝒞`** iff there is some
Boolean tier predicate `T : α → Bool` and some `L' : Language α` with
`L'` in `𝒞` such that `L` is the preimage of `L'` under projection by
`T`: `w ∈ L ↔ w.filter T ∈ L'`.

The Bool tier shape is the existence-friendly form (no instance
quantifier issues). For the Prop+DecidablePred form used by
`tierProject` and `TSLGrammar`, convert via `T x ↔ tier x = true`. -/
def IsTierBased (𝒞 : Language α → Prop) (L : Language α) : Prop :=
  ∃ T : α → Bool, ∃ L' : Language α,
    L = { w | w.filter T ∈ L' } ∧ 𝒞 L'

namespace IsTierBased

/-- **Class injection**: every `𝒞`-language is tier-based for `𝒞` via the
universal-true tier (no symbols erased). The witness is `T = fun _ => true`
and `L' = L`. -/
theorem of_class (h : 𝒞 L) : IsTierBased 𝒞 L := by
  refine ⟨fun _ => true, L, ?_, h⟩
  ext w
  show w ∈ L ↔ List.filter (fun _ => true) w ∈ L
  rw [List.filter_true]

/-- Monotonicity in the base class. -/
theorem mono (h : ∀ L, 𝒞 L → 𝒟 L) (hL : IsTierBased 𝒞 L) : IsTierBased 𝒟 L := by
  obtain ⟨T, L', hL_eq, hL'⟩ := hL
  exact ⟨T, L', hL_eq, h _ hL'⟩

end IsTierBased

/-! ## Multitier (Boolean tier-projected) closure -/

/-- The **multitier closure** of a class `𝒞`: the Boolean subalgebra of
`Language α` generated by the tier-projected family `IsTierBased 𝒞`. -/
def IsBTC (𝒞 : Language α → Prop) (L : Language α) : Prop :=
  L ∈ BooleanSubalgebra.closure {L' | IsTierBased 𝒞 L'}

/-- Base-class injection: a tier-based language lies in the closure. -/
theorem IsBTC.base (h : IsTierBased 𝒞 L) : IsBTC 𝒞 L :=
  BooleanSubalgebra.subset_closure h

/-- Closure under intersection. -/
theorem IsBTC.inter (h₁ : IsBTC 𝒞 L₁) (h₂ : IsBTC 𝒞 L₂) : IsBTC 𝒞 (L₁ ⊓ L₂) :=
  BooleanSubalgebra.inf_mem h₁ h₂

/-- Closure under union. -/
theorem IsBTC.union (h₁ : IsBTC 𝒞 L₁) (h₂ : IsBTC 𝒞 L₂) : IsBTC 𝒞 (L₁ ⊔ L₂) :=
  BooleanSubalgebra.sup_mem h₁ h₂

/-- Closure under complement. -/
theorem IsBTC.compl (h : IsBTC 𝒞 L) : IsBTC 𝒞 Lᶜ :=
  BooleanSubalgebra.compl_mem h

/-- **Class injection** into the multitier closure: every `𝒞`-language is in
`IsBTC 𝒞`, via the universal tier. -/
theorem IsBTC.of_class (h : 𝒞 L) : IsBTC 𝒞 L :=
  .base (IsTierBased.of_class h)

/-- **Tier-based injection** into the multitier closure: every
tier-based-for-`𝒞` language is in `IsBTC 𝒞`. -/
theorem IsBTC.of_tierBased (h : IsTierBased 𝒞 L) : IsBTC 𝒞 L :=
  .base h

/-- Monotonicity of multitier closure in the base class. -/
theorem IsBTC.mono (h : ∀ L, 𝒞 L → 𝒟 L) (hL : IsBTC 𝒞 L) : IsBTC 𝒟 L :=
  BooleanSubalgebra.closure_mono (fun _ hL' => IsTierBased.mono h hL') hL

/-! ## Specializations

One line each. Closure under intersection, union, and complement comes
from `IsBTC.inter`/`union`/`compl`; class injection from `IsBTC.of_class`. -/

/-- **Multitier strictly local** (BTSL): Boolean closure of tier-projected
SL_k languages. -/
def IsBTSL (k : ℕ) : Language α → Prop := IsBTC (Language.IsStrictlyLocal · k)

/-- **Multitier strictly piecewise** (BTSP): Boolean closure of
tier-projected SP_k languages. -/
def IsBTSP (k : ℕ) : Language α → Prop := IsBTC (Language.IsStrictlyPiecewise · k)

/-- **Multitier definite** (BTD): Boolean closure of tier-projected D_k
languages. -/
def IsBTD (k : ℕ) : Language α → Prop := IsBTC (Language.IsDefinite · k)

/-- **Multitier reverse definite** (BTK): Boolean closure of tier-projected
RD_k languages. -/
def IsBTK (k : ℕ) : Language α → Prop := IsBTC (Language.IsReverseDefinite · k)

/-- **Multitier generalized definite** (BTLI): Boolean closure of
tier-projected ℒℐ_k languages. -/
def IsBTLI (k : ℕ) : Language α → Prop := IsBTC (Language.IsGeneralizedDefinite · k)

/-- **Multitier finite-or-cofinite** (BTN): Boolean closure of
tier-projected co/finite languages. -/
def IsBTN : Language α → Prop := IsBTC Language.IsFiniteOrCofinite

/-! ## Cross-class inclusions

Class containment lifts through the multitier construction: if `𝒞 ⊆ 𝒟`
pointwise, then `IsBTC 𝒞 ⊆ IsBTC 𝒟`. Specializing the `D_k ⊆ ℒℐ_k` and
`RD_k ⊆ ℒℐ_k` inclusions yields BTD ⊆ BTLI and BTK ⊆ BTLI. -/

/-- **D_k ⊆ ℒℐ_k** lifts to **BTD_k ⊆ BTLI_k**. -/
theorem IsBTD.toIsBTLI (h : IsBTD k L) : IsBTLI k L :=
  IsBTC.mono (fun _ => Language.IsDefinite.toIsGeneralizedDefinite) h

/-- **RD_k ⊆ ℒℐ_k** lifts to **BTK_k ⊆ BTLI_k**. -/
theorem IsBTK.toIsBTLI (h : IsBTK k L) : IsBTLI k L :=
  IsBTC.mono (fun _ => Language.IsReverseDefinite.toIsGeneralizedDefinite) h

/-! ## TSL ⊆ multitier SL -/

/-- **TSL_k → BTSL_k**: every tier-based strictly local language is in the
multitier closure of strictly local languages. A `TSLGrammar` witness presents
its language as the preimage of an SL language under the tier projection, hence
`IsTierBased (Language.IsStrictlyLocal · k)`, hence in the closure via
`IsBTC.base`. -/
theorem IsTierStrictlyLocal.toIsBTSL (h : IsTierStrictlyLocal k L) : IsBTSL k L := by
  apply IsBTC.base
  obtain ⟨G, rfl⟩ := h
  refine ⟨fun x => decide (G.tier x), SLGrammar.language k G.permitted, ?_, ⟨_, rfl⟩⟩
  ext w
  show (∀ f ∈ List.kFactors k (boundary k (tierProject G.tier w)), f ∈ G.permitted) ↔
       ∀ f ∈ List.kFactors k (boundary k (List.filter _ w)), f ∈ G.permitted
  rw [tierProject_eq_filter]

/-! ## Indistinguishability framework for refuting `IsBTC` membership

Standard technique for `L ∉ IsBTC 𝒞`: exhibit two words `w₁`, `w₂` that are
𝒞-tier-indistinguishable (every `𝒞`-language under every Bool tier projection
assigns them the same membership) but differ in `L`-membership. The
`IsGeneralizedDefinite k` specialization — sharing length-`k` prefix-and-suffix
on every tier projection (`indist_isGenDef_of_tierAffixes`) — is the common case. -/

/-- Two words are **𝒞-tier-indistinguishable** iff under every Bool tier
projection, every `𝒞`-language assigns them the same membership. -/
def IsBTC.Indist (𝒞 : Language α → Prop) (w₁ w₂ : List α) : Prop :=
  ∀ T : α → Bool, ∀ L' : Language α, 𝒞 L' →
    (w₁.filter T ∈ L' ↔ w₂.filter T ∈ L')

namespace IsBTC.Indist

@[refl] protected theorem refl (𝒞 : Language α → Prop) (w : List α) :
    IsBTC.Indist 𝒞 w w := fun _ _ _ => Iff.rfl

@[symm] protected theorem symm (h : IsBTC.Indist 𝒞 w₁ w₂) : IsBTC.Indist 𝒞 w₂ w₁ :=
  fun T L' hL' => (h T L' hL').symm

@[trans] protected theorem trans {w₃ : List α}
    (h₁ : IsBTC.Indist 𝒞 w₁ w₂) (h₂ : IsBTC.Indist 𝒞 w₂ w₃) :
    IsBTC.Indist 𝒞 w₁ w₃ :=
  fun T L' hL' => (h₁ T L' hL').trans (h₂ T L' hL')

end IsBTC.Indist

/-- Tier-indistinguishability transports through the Boolean closure:
`w₁` and `w₂` 𝒞-tier-indistinguishable implies same membership in every
`IsBTC 𝒞`-language. Induction on the closure: `mem` is the defining property
of `Indist`; `bot`/`sup`/`compl` lift via `Iff.rfl`/`or_congr`/`not_congr`. -/
theorem IsBTC.mem_iff_of_indist (hL : IsBTC 𝒞 L) (hindist : IsBTC.Indist 𝒞 w₁ w₂) :
    w₁ ∈ L ↔ w₂ ∈ L := by
  induction hL using BooleanSubalgebra.closure_bot_sup_induction with
  | mem L' hL' =>
    obtain ⟨T, L'', hL_eq, hL''⟩ := hL'
    rw [hL_eq]; exact hindist T L'' hL''
  | bot => exact Iff.rfl
  | sup _ _ _ _ ih₁ ih₂ => exact or_congr ih₁ ih₂
  | compl _ _ ih => exact not_congr ih

/-- **Refutation lemma**: if `w₁ ∈ L` and `w₂ ∉ L` but `w₁` and `w₂` are
𝒞-tier-indistinguishable, then `L ∉ IsBTC 𝒞`. -/
theorem not_isBTC_of_indist (h_indist : IsBTC.Indist 𝒞 w₁ w₂)
    (h_w₁ : w₁ ∈ L) (h_w₂ : w₂ ∉ L) :
    ¬ IsBTC 𝒞 L :=
  fun hL => h_w₂ ((IsBTC.mem_iff_of_indist hL h_indist).mp h_w₁)

/-- Shared length-`k` prefix-and-suffix on every Bool-tier projection implies
`IsBTC.Indist (Language.IsGeneralizedDefinite · k)` — the standard specialization
for refuting `IsBTLI k` membership, reducing it to a `Bool`-tier-parameterised
pair of affix equalities. -/
theorem IsBTC.indist_isGenDef_of_tierAffixes
    (h : ∀ T : α → Bool,
      Edge.left.takeAt k (w₁.filter T) = Edge.left.takeAt k (w₂.filter T) ∧
      Edge.right.takeAt k (w₁.filter T) = Edge.right.takeAt k (w₂.filter T)) :
    IsBTC.Indist (Language.IsGeneralizedDefinite · k) w₁ w₂ := by
  intro T L' hL'
  obtain ⟨h_pre, h_suf⟩ := h T
  exact Language.isGeneralizedDefinite_iff_edges.mp hL' h_pre h_suf

end Language
