module

public import Mathlib.Data.Finset.Card
public import Mathlib.Data.Finset.Max
public import Linglib.Syntax.Minimalist.Defs
public import Linglib.Syntax.Tree.Command
public import Linglib.Syntax.Binding.Basic
public import Linglib.Syntax.Case.Dependent

/-!
# Newman (2024): *When Arguments Merge*

This file formalizes Newman's theory of feature-driven Merge and its consequences for the verb
phrase. A head bears Merge features, and an element merging with it checks every unchecked feature
it can. Features may go unchecked, and they belong to categories rather than to lexical items: V
bears `[·D·]`, checked by a DP, and `[·X·]`, checked by anything, and v in addition `[·V·]` and
`[·wh·]`. Since a DP checks everything a non-DP checks and a wh-DP everything a DP checks, a phrase
checking a subset of another's features must merge first. Among the operations possible at a
step, Weak Economy prefers one checking more features unless one would bleed the other. Newman
derives from this where arguments go in the verb phrase, the binding pattern of the dative
alternation, agent focus in Mayan subject questions, and the subjects of passive ditransitives.

## Main definitions

* `Licensed`: a sequence of merges with one head, each checking a feature still unchecked.
* `Phrase.checks`, `bundleV`, `bundlev`: the features a phrase checks and those V and v bear.
* `configuration`: the binding theory, m-command without reverse c-command.
* `AgentFocus`: Voice and T cross-reference one argument, so Voice is spelled out as agent focus.
* `System.Derivation`: a derivation at v in which every step respects Weak Economy.

## Main results

* `Licensed.not_sublist`: an element checking only features another checks cannot follow it.
* `nonDP_first`, `not_dp_after_dp`: non-DP arguments are complements, one DP per head.
* `wordOrder_binding`: the direct object can bind the indirect object only when it precedes it.
* `transitive_derivations`, `agentFocus_iff`: agent focus arises exactly when the object checks
  `[·D·]` before the wh-subject merges.
* `npObject_no_agentFocus`, `multipleFronting`: the environments that obviate agent focus.
* `doma`, `lowPassive_subject`, `om_iobj_subject`: the subjects of passive ditransitives.
* `greek_passive`, `greek_whPassive`, `greek_active`: when Greek clitic doubling is obligatory.
* `literal_greek_whPassive`: Weak Economy read as worded makes clitic doubling obligatory in wh
  passives, against the data.
* `System.exists_derivation`: Weak Economy never blocks every operation.
* `whSubject_complement`, `overlap_subjectQuestions`, `overlap_passives`: Weak Economy makes a
  wh-subject v's complement unless operations checking a common feature are exempt.

## Implementation notes

A phrase's checkable features are read off its category and the features it bears. The first
specifier merged is outermost, by Paillé's generalization of Richards's tucking in; m-command is
Barker and Pullum's command relation generated by the maximal projections, and case is Marantz's
dependent case. An operation is possible when it checks a Merge feature of an accessible phrase,
and a derivation ends only when nothing possible remains, as Preminger's obligatory operations
require.

## TODO

The person-hierarchy effects on agent focus and the weak-crossover account of anaphoric objects
in chapter 3, and chapters 6 and 7, are not formalized.

## References

* [newman-2024]
* [preminger-2014]
* [richards-1997]
* [paille-2020]
* [marantz-1991]
* [barker-pullum-1990]
-/

@[expose] public section

namespace Newman2024

open scoped List
open Minimalist (Cat)
open Core.Order (TreePath)

/-! ### Feature-driven Merge -/

section Merge

variable {F α : Type*} [DecidableEq F] (κ : α → Finset F) (P : Finset F)

/-- `Licensed κ P s es` holds when the elements `es` can merge in order with a head whose unchecked
Merge features are `s`, where `κ e` is the set of features `e` can check and the features in `P`
stay active once checked. Each element checks every unchecked feature it can, and at least one;
features left over at the end are allowed. -/
def Licensed : Finset F → List α → Prop
  | _, [] => True
  | s, e :: es => (s ∩ κ e).Nonempty ∧ Licensed (s \ (κ e \ P)) es

instance decLicensed : (s : Finset F) → (es : List α) → Decidable (Licensed κ P s es)
  | _, [] => isTrue trivial
  | s, e :: es =>
    haveI := decLicensed (s \ (κ e \ P)) es
    inferInstanceAs (Decidable (_ ∧ _))

variable {κ P} {s : Finset F} {es : List α}

@[simp] theorem licensed_nil : Licensed κ P s [] := trivial

@[simp] theorem licensed_cons {e : α} :
    Licensed κ P s (e :: es) ↔ (s ∩ κ e).Nonempty ∧ Licensed κ P (s \ (κ e \ P)) es := Iff.rfl

/-- Every element of a licensed sequence can check one of the head's features. -/
theorem Licensed.nonempty_of_mem (h : Licensed κ P s es) {b : α} (hb : b ∈ es) :
    (s ∩ κ b).Nonempty := by
  induction es generalizing s with
  | nil => simp at hb
  | cons e es ih =>
    obtain ⟨h₁, h₂⟩ := licensed_cons.1 h
    rcases List.mem_cons.1 hb with rfl | hb
    · exact h₁
    · exact (ih h₂ hb).mono (Finset.inter_subset_inter Finset.sdiff_subset subset_rfl)

/-- If `b` can check only features of the head that `a` checks and uses up, `b` cannot merge
after `a`. -/
theorem Licensed.not_sublist (h : Licensed κ P s es) {a b : α} (hab : s ∩ κ b ⊆ κ a \ P) :
    ¬ [a, b] <+ es := by
  induction es generalizing s with
  | nil => simp
  | cons e es ih =>
    obtain ⟨_, h₂⟩ := licensed_cons.1 h
    intro hs
    rcases List.sublist_cons_iff.1 hs with hs | ⟨r, hr, hs⟩
    · exact ih h₂ ((Finset.inter_subset_inter Finset.sdiff_subset subset_rfl).trans hab) hs
    · obtain ⟨rfl, rfl⟩ := List.cons_eq_cons.1 hr
      obtain ⟨x, hx⟩ := h₂.nonempty_of_mem (List.singleton_sublist.1 hs)
      rw [Finset.mem_inter, Finset.mem_sdiff] at hx
      exact hx.1.2 (hab (Finset.mem_inter.2 ⟨hx.1.1, hx.2⟩))

/-- If every element can check and use up whatever `b` can check among the head's features, `b`
merges first. -/
theorem Licensed.head?_eq (h : Licensed κ P s es) {b : α} (hb : b ∈ es)
    (hsub : ∀ a ∈ es, s ∩ κ b ⊆ κ a \ P) : es.head? = some b := by
  cases es with
  | nil => simp at hb
  | cons e es =>
    rcases List.mem_cons.1 hb with rfl | hb
    · rfl
    · exact absurd (List.cons_sublist_cons.2 (List.singleton_sublist.2 hb))
        (h.not_sublist (hsub e List.mem_cons_self))

/-- When no feature stays active, no element merges twice. -/
theorem Licensed.nodup (h : Licensed κ ∅ s es) : es.Nodup :=
  List.nodup_iff_sublist.2 fun _ ↦ h.not_sublist (by simp)

/-- When no feature stays active, a head licenses at most as many merges as it has features. -/
theorem Licensed.length_le (h : Licensed κ ∅ s es) : es.length ≤ s.card := by
  induction es generalizing s with
  | nil => simp
  | cons e es ih =>
    obtain ⟨h₁, h₂⟩ := licensed_cons.1 h
    rw [Finset.sdiff_empty] at h₂
    have := Finset.card_sdiff_add_card_inter s (κ e)
    have := h₁.card_pos
    have := ih h₂
    simp only [List.length_cons]
    omega

end Merge

/-- If no two elements satisfying `p` occur in order in `l`, at most one does. -/
private theorem length_filter_le_one {α : Type*} {l : List α} {p : α → Bool}
    (h : ∀ a b, p a → p b → ¬ [a, b] <+ l) : (l.filter p).length ≤ 1 := by
  match hl : l.filter p with
  | [] | [_] => simp
  | a :: b :: t =>
    have hs : [a, b] <+ l := (List.cons_sublist_cons.2 (List.cons_sublist_cons.2
      (List.nil_sublist t))).trans (hl ▸ List.filter_sublist)
    have ha : a ∈ l.filter p := by simp [hl]
    have hb : b ∈ l.filter p := by simp [hl]
    exact absurd hs (h a b (List.mem_filter.1 ha).2 (List.mem_filter.1 hb).2)

/-- `arrangements l n` collects the duplicate-free lists of length at most `n` drawn from `l`. -/
private def arrangements {α : Type*} [DecidableEq α] (l : List α) : ℕ → List (List α)
  | 0 => [[]]
  | n + 1 => [] :: l.flatMap fun a ↦ (arrangements (l.erase a) n).map (a :: ·)

private theorem mem_arrangements {α : Type*} [DecidableEq α] :
    ∀ {n : ℕ} {l es : List α}, es.Nodup → es ⊆ l → es.length ≤ n → es ∈ arrangements l n
  | 0, _, [], _, _, _ => List.mem_singleton_self _
  | 0, _, _ :: _, _, _, h => absurd h (by simp)
  | _ + 1, _, [], _, _, _ => List.mem_cons_self
  | _ + 1, _, a :: es, hnd, hsub, hlen => by
    obtain ⟨hna, hnd⟩ := List.nodup_cons.1 hnd
    refine List.mem_cons_of_mem _ (List.mem_flatMap.2
      ⟨a, hsub List.mem_cons_self, List.mem_map.2 ⟨es, mem_arrangements hnd ?_ ?_, rfl⟩⟩)
    · exact fun x hx ↦ (List.mem_erase_of_ne (by rintro rfl; exact hna hx)).2
        (hsub (List.mem_cons_of_mem _ hx))
    · simpa using hlen

private theorem mem_arrangements_length {α : Type*} [DecidableEq α] {l es : List α}
    (hnd : es.Nodup) (hsub : es ⊆ l) : es ∈ arrangements l l.length :=
  mem_arrangements hnd hsub (hnd.subperm hsub).length_le

/-! ### The Categorial Merge Hypothesis -/

/-- The features that drive Merge and Agree at a head are `[·D·]`, checked by a full DP,
`[·Dweak·]`, checked by anything bearing D including a clitic, the category-unspecified `[·X·]`,
checked by anything, `[·V·]`, checked by a VP, `[·wh·]`, checked by a wh-phrase, the
object-marking feature, checked by a phrase with the discourse status object marking tracks, and
the φ-probe `[uφ]`, valued by Agree. -/
inductive Feature where
  | D
  | Dweak
  | X
  | V
  | wh
  | om
  | phi
  deriving DecidableEq, Repr

/-- Every feature but the φ-probe is a Merge feature. -/
def Feature.IsMerge (f : Feature) : Prop := f ≠ .phi

instance : DecidablePred Feature.IsMerge := fun f ↦ inferInstanceAs (Decidable (f ≠ .phi))

/-- A phrase, as Merge features see it, is its category and the further features it bears, such
as `[wh]`. -/
structure Phrase where
  cat : Cat
  bears : Finset Feature := ∅
  deriving DecidableEq

namespace Phrase

/-- A phrase checks `[·X·]`, `[·D·]` and `[·Dweak·]` when it is a DP, `[·V·]` when it is a VP, and
the features it bears. -/
def checks (p : Phrase) : Finset Feature :=
  {.X} ∪ (if p.cat = .D then {.D, .Dweak} else ∅) ∪ (if p.cat = .V then {.V} else ∅) ∪ p.bears

@[simp] theorem mem_checks {p : Phrase} {f : Feature} :
    f ∈ p.checks ↔
      f = .X ∨ (f = .D ∨ f = .Dweak) ∧ p.cat = .D ∨ f = .V ∧ p.cat = .V ∨ f ∈ p.bears := by
  unfold checks
  split_ifs <;> simp_all; tauto

/-- `dp` is a DP bearing nothing further. -/
def dp : Phrase := ⟨.D, ∅⟩

/-- `whDP` is a wh-DP. -/
def whDP : Phrase := ⟨.D, {.wh}⟩

/-- `vp` is a VP. -/
def vp : Phrase := ⟨.V, ∅⟩

/-- A phrase that is neither a DP nor a VP and bears nothing checks only `[·X·]`. -/
theorem checks_eq_X {p : Phrase} (hD : p.cat ≠ .D) (hV : p.cat ≠ .V) (hb : p.bears = ∅) :
    p.checks = {.X} := by
  ext f; simp [hD, hV, hb]

/-- A wh-DP checks everything a DP checks. -/
theorem checks_dp_subset_whDP : dp.checks ⊆ whDP.checks := by
  intro f; simp [dp, whDP]; tauto

/-- A DP checks everything a phrase that is not a VP and bears nothing checks. -/
theorem checks_subset_dp {p : Phrase} (hV : p.cat ≠ .V) (hb : p.bears = ∅) :
    p.checks ⊆ dp.checks := by
  intro f; simp [dp, hV, hb]; tauto

end Phrase

/-- V bears `[·D·]` and `[·X·]`, whatever the verb. -/
def bundleV : Finset Feature := {.D, .X}

/-- v bears V's features, `[·V·]` for merging VP, and `[·wh·]` for successive-cyclic movement. -/
def bundlev : Finset Feature := {.D, .X, .V, .wh}

/-! ### The distribution of DPs and non-DPs -/

section Distribution

variable {α : Type*} {f : α → Phrase} {s : Finset Feature} {es : List α}

/-- **The non-DP first theorem.** A phrase that checks nothing but `[·X·]` merges first with any
head it merges with, so it is that head's complement. -/
theorem nonDP_first (h : Licensed (Phrase.checks ∘ f) ∅ s es) {b : α} (hb : b ∈ es)
    (hD : (f b).cat ≠ .D) (hV : (f b).cat ≠ .V) (hbears : (f b).bears = ∅) :
    es.head? = some b :=
  h.head?_eq hb fun a _ ↦ Finset.inter_subset_right.trans <| by
    simp [Function.comp_apply, Phrase.checks_eq_X hD hV hbears]

/-- A non-DP argument of v makes VP a specifier rather than v's complement. -/
theorem vp_specifier (h : Licensed (Phrase.checks ∘ f) ∅ bundlev es) {b vp : α} (hb : b ∈ es)
    (hD : (f b).cat ≠ .D) (hV : (f b).cat ≠ .V) (hbears : (f b).bears = ∅) (hne : vp ≠ b) :
    es.head? ≠ some vp := by
  rw [nonDP_first h hb hD hV hbears]
  simpa using hne.symm

/-- **One DP per head.** A DP cannot merge after another DP bearing everything it bears. -/
theorem not_dp_after_dp (h : Licensed (Phrase.checks ∘ f) ∅ s es) {a b : α}
    (ha : (f a).cat = .D) (hb : (f b).cat = .D) (hbears : (f b).bears ⊆ (f a).bears) :
    ¬ [a, b] <+ es :=
  h.not_sublist <| Finset.inter_subset_right.trans fun x hx ↦ by
    simp only [Function.comp_apply, Finset.sdiff_empty, Phrase.mem_checks, ha, hb] at hx ⊢
    rcases hx with hx | hx | hx | hx
    · exact Or.inl hx
    · exact Or.inr (Or.inl hx)
    · exact Or.inr (Or.inr (Or.inl hx))
    · exact Or.inr (Or.inr (Or.inr (hbears hx)))

/-- A head introduces at most one DP bearing nothing further. -/
theorem length_filter_dp_le_one (h : Licensed (Phrase.checks ∘ f) ∅ s es) :
    (es.filter fun a ↦ (f a).cat = .D ∧ (f a).bears = ∅).length ≤ 1 :=
  length_filter_le_one fun _ _ ha hb ↦ by
    simp only [decide_eq_true_eq] at ha hb
    exact not_dp_after_dp h ha.1 hb.1 (hb.2 ▸ Finset.empty_subset _)

/-- A head introduces at most one argument that is neither a DP nor a VP and bears nothing. -/
theorem length_filter_nonDP_le_one (h : Licensed (Phrase.checks ∘ f) ∅ s es) :
    (es.filter fun a ↦ (f a).cat ≠ .D ∧ (f a).cat ≠ .V ∧ (f a).bears = ∅).length ≤ 1 :=
  length_filter_le_one fun a _ _ hb ↦ by
    simp only [decide_eq_true_eq] at hb
    exact h.not_sublist <| Finset.inter_subset_right.trans <| by
      simp [Function.comp_apply, Phrase.checks_eq_X hb.1 hb.2.1 hb.2.2]

/-- V takes a non-DP complement and then a DP, but not a DP and then a non-DP. -/
example : Licensed Phrase.checks ∅ bundleV [⟨.P, ∅⟩, .dp] ∧
    ¬ Licensed Phrase.checks ∅ bundleV [.dp, ⟨.P, ∅⟩] := by decide

/-- *Bet* uses every argument feature. V takes the clause and then the wager, and v takes the
applied dative, then VP as a specifier, then the bettor. -/
example : Licensed Phrase.checks ∅ bundleV [⟨.C, ∅⟩, .dp] ∧
    Licensed Phrase.checks ∅ bundlev [⟨.Appl, ∅⟩, .vp, .dp] := by decide

end Distribution

/-! ### The dative alternation -/

/-- A node of a tree is a head, an intermediate projection, or a maximal projection. -/
inductive Level where
  | head
  | bar
  | max
  deriving DecidableEq, Repr

/-- A leaf of a ditransitive vP is the external argument, v, V, the direct object, or the phrase
containing the indirect object. -/
inductive Leaf where
  | subj
  | v
  | V
  | dobj
  | iobj
  deriving DecidableEq, Repr

/-- An `XTree` is a tree whose nodes carry a category and a projection level. -/
abbrev XTree := Syntax.Tree (Cat × Level) Leaf

/-- A tree counts for Merge features as a phrase of its root's category. -/
def XTree.checks (t : XTree) : Finset Feature := Phrase.checks ⟨t.cat.1, ∅⟩

/-- `bar c h comp specs` is the stack of intermediate projections of the phrase headed by `h`,
with complement `comp` and specifiers `specs`. -/
def bar (c : Cat) (h comp : XTree) : List XTree → XTree
  | [] => .node (c, .bar) [h, comp]
  | s :: ss => .node (c, .bar) [s, bar c h comp ss]

/-- `project c h es` is the phrase the head `h` of category `c` projects when `es` merge with it.
The first is the complement, and each later one tucks in below the specifiers already merged, so
the first specifier is outermost. -/
def project (c : Cat) (h : XTree) : List XTree → XTree
  | [] => .node (c, .max) [h]
  | [comp] => .node (c, .max) [h, comp]
  | comp :: s :: ss => .node (c, .max) [s, bar c h comp ss]

/-- `subjP` is the external argument, a DP. -/
def subjP : XTree := .terminal (.D, .max) .subj

/-- `dobjP` is the direct object, a DP. -/
def dobjP : XTree := .terminal (.D, .max) .dobj

/-- `iobjP` is the phrase containing the indirect object, a PP or an applicative phrase. -/
def iobjP : XTree := .terminal (.P, .max) .iobj

/-- `vHead` is the head v. -/
def vHead : XTree := .terminal (.v, .head) .v

/-- `VHead` is the head V. -/
def VHead : XTree := .terminal (.V, .head) .V

/-- `lowXP` is the ditransitive with the indirect object in V's complement. -/
def lowXP : XTree := project .v vHead [project .V VHead [iobjP, dobjP], subjP]

/-- `highXP` is the ditransitive with the indirect object in v's complement and VP a specifier
linearized on the left. -/
def highXP : XTree := project .v vHead [iobjP, subjP, project .V VHead [dobjP]]

/-- `highXPRight` is `highXP` with the VP specifier linearized on the right. -/
def highXPRight : XTree :=
  .node (.v, .max) [subjP, .node (.v, .bar) [.node (.v, .bar) [vHead, iobjP],
    project .V VHead [dobjP]]]

/-- `ditransitives` lists the three ditransitive vPs. -/
def ditransitives : List XTree := [lowXP, highXP, highXPRight]

/-- Both structures come from licensed derivations, and VP cannot be v's complement when the
phrase containing the indirect object merges with v. -/
theorem ditransitives_licensed :
    Licensed XTree.checks ∅ bundleV [iobjP, dobjP] ∧
      Licensed XTree.checks ∅ bundlev [project .V VHead [iobjP, dobjP], subjP] ∧
      Licensed XTree.checks ∅ bundleV [dobjP] ∧
      Licensed XTree.checks ∅ bundlev [iobjP, subjP, project .V VHead [dobjP]] ∧
      ¬ Licensed XTree.checks ∅ bundlev [project .V VHead [dobjP], iobjP, subjP] := by
  decide

/-- In the binding configuration of a tree, `a` commands `b` when every maximal projection
properly dominating `a` dominates `b` and `b` does not c-command `a`. Binding is not restricted to
a domain. -/
def configuration (t : XTree) : Binding.Configuration TreePath where
  commands a b := (a, b) ∈ Syntax.Tree.maxCommand t {n | n.2 = .max} ∧
    ¬ Syntax.CCommands t b a
  domain _ := Set.univ

instance (t : XTree) : DecidableRel (configuration t).commands := fun a b ↦
  inferInstanceAs (Decidable ((a, b) ∈ Syntax.Tree.maxCommand t _ ∧ _))

/-- `leafPaths t` pairs each leaf of `t` with its position. -/
def leafPaths (t : XTree) : List (Leaf × TreePath) :=
  t.fold (fun _ w ↦ [(w, ⊥)])
    (fun _ bs ↦ bs.zipIdx.flatMap fun (ps, i) ↦ ps.map fun (w, p) ↦ (w, ⟨i :: p.toList⟩))
    (fun _ _ ↦ []) (fun _ _ ps ↦ ps.map fun (w, p) ↦ (w, ⟨0 :: p.toList⟩))

/-- The leaf `x` can bind the leaf `y` in `t`. -/
def CanBind (t : XTree) (x y : Leaf) : Prop :=
  ∃ a ∈ (leafPaths t).lookup x, ∃ b ∈ (leafPaths t).lookup y, (configuration t).commands a b

instance (t : XTree) (x y : Leaf) : Decidable (CanBind t x y) :=
  inferInstanceAs (Decidable (∃ a ∈ _, _))

/-- The leaf `x` precedes the leaf `y` in `t`. -/
def Precedes (t : XTree) (x y : Leaf) : Prop := t.yield.idxOf x < t.yield.idxOf y

instance (t : XTree) (x y : Leaf) : Decidable (Precedes t x y) :=
  inferInstanceAs (Decidable (_ < _))

/-- With the indirect object in V's complement, the direct object binds it and not conversely;
with it in v's complement, the converse holds, however VP is linearized. -/
theorem canBind_dobj_iobj :
    CanBind lowXP .dobj .iobj ∧ ¬ CanBind lowXP .iobj .dobj ∧
      ∀ t ∈ [highXP, highXPRight], CanBind t .iobj .dobj ∧ ¬ CanBind t .dobj .iobj := by
  decide

/-- With the indirect object in v's complement neither object c-commands the other. -/
theorem highXP_not_cCommands :
    ∃ a ∈ (leafPaths highXP).lookup .dobj, ∃ b ∈ (leafPaths highXP).lookup .iobj,
      ¬ Syntax.CCommands highXP a b ∧ ¬ Syntax.CCommands highXP b a := by
  decide

/-- **Word order and binding.** When the indirect object precedes the direct object, the direct
object cannot bind it; when it follows, either can bind the other. -/
theorem wordOrder_binding :
    (∀ t ∈ ditransitives, Precedes t .iobj .dobj → ¬ CanBind t .dobj .iobj) ∧
      (∃ t ∈ ditransitives, Precedes t .dobj .iobj ∧ CanBind t .dobj .iobj) ∧
      (∃ t ∈ ditransitives, Precedes t .dobj .iobj ∧ CanBind t .iobj .dobj) := by
  decide

/-! ### Subject questions and agent focus -/

/-- The phrases merging with v in a transitive clause are VP, the internal argument moving out
of it, and the external argument. -/
inductive Transitive where
  | vp
  | obj
  | subj
  deriving DecidableEq, Repr

/-- `Transitive.phrase obj whs a` is the phrase `a` is, with an object of category `obj` and the
phrases in `whs` bearing `[wh]`. -/
def Transitive.phrase (obj : Cat) (whs : List Transitive) : Transitive → Phrase
  | .vp => .vp
  | .obj => ⟨obj, if .obj ∈ whs then {.wh} else ∅⟩
  | .subj => ⟨.D, if .subj ∈ whs then {.wh} else ∅⟩

/-- `TransitiveDerivation P obj whs es` says that VP merges with v as its complement and then the
specifiers `es` merge, with the features in `P` staying active. -/
abbrev TransitiveDerivation (P : Finset Feature) (obj : Cat) (whs es : List Transitive) : Prop :=
  Licensed (Phrase.checks ∘ Transitive.phrase obj whs) P bundlev (.vp :: es)

private theorem Transitive.mem_arrangements {es : List Transitive} (hes : es.Nodup) :
    es ∈ arrangements [Transitive.vp, .obj, .subj] 3 :=
  Newman2024.mem_arrangements hes (fun x _ ↦ by cases x <;> simp)
    (hes.subperm (l₂ := [.vp, .obj, .subj]) fun x _ ↦ by cases x <;> simp).length_le

private theorem TransitiveDerivation.nodup {obj : Cat} {whs es : List Transitive}
    (h : TransitiveDerivation ∅ obj whs es) : es.Nodup :=
  (List.nodup_cons.1 (Licensed.nodup h)).2

/-- **Subject and object questions.** With an external argument and the wh-phrase passing
through the edge of vP, a subject question has two derivations, the subject checking `[·D·]` and
`[·wh·]` at once or the object checking `[·D·]` first; an object question has one, the subject
merging before the wh-object. -/
theorem transitive_derivations {es : List Transitive} :
    (TransitiveDerivation ∅ .D [.subj] es ∧ .subj ∈ es ↔ es = [.subj] ∨ es = [.obj, .subj]) ∧
      (TransitiveDerivation ∅ .D [.obj] es ∧ .subj ∈ es ∧ .obj ∈ es ↔ es = [.subj, .obj]) := by
  refine ⟨⟨?_, by rintro (rfl | rfl) <;> decide⟩, ⟨?_, by rintro rfl; decide⟩⟩
  · rintro ⟨h, hs⟩
    have hm := Transitive.mem_arrangements h.nodup
    revert h hs; revert hm; revert es
    decide
  · rintro ⟨h, hs, ho⟩
    have hm := Transitive.mem_arrangements h.nodup
    revert h hs ho; revert hm; revert es
    decide

/-- `heightOrder es` lists the arguments from the highest down once the specifiers `es` have
merged, the specifiers first with the first merged outermost, then the object in situ unless it
has moved. -/
def heightOrder (es : List Transitive) : List Transitive :=
  es.filter (· ≠ .vp) ++ if .obj ∈ es then [] else [.obj]

/-- When the first specifier merges, the dependent rules of an ergative grammar assign case to
the arguments then in vP, highest first and without the moved object's lower copy. A specifier
merged later is unmarked. -/
def caseOf (es : List Transitive) (a : Transitive) : Option Case :=
  let r := DependentCase.Rules.ofAlignment .ergative
  let dom := match es with
    | s :: _ => if s = .obj then [Transitive.obj] else [s, .obj]
    | [] => [.obj]
  match ((r.unmarkedPass (fun _ ↦ true) <| r.dependentPass (fun _ ↦ true) <|
      Case.lexicalValuation (fun _ ↦ none) dom).lookup a) with
  | some v => v.map (·.1)
  | none => r.unmarked

/-- Voice's φ-probe, spelled out as Set A, agrees with the closest argument. -/
def setA (es : List Transitive) : Option Transitive := (heightOrder es).head?

/-- T's φ-probe, spelled out as Set B, agrees with the closest absolutive argument. -/
def setB (es : List Transitive) : Option Transitive :=
  (heightOrder es).find? fun a ↦ caseOf es a = some .abs

/-- When the adjacent probes on Voice and T cross-reference the same argument, anti-redundancy
deletes Voice's copy, and Voice is spelled out as the agent-focus morpheme. -/
def AgentFocus (es : List Transitive) : Prop := setA es = setB es

instance (es : List Transitive) : Decidable (AgentFocus es) :=
  inferInstanceAs (Decidable (_ = _))

/-- The subject is ergative when it merges first, absolutive when the object has moved before it;
in both cases the object is absolutive. -/
example :
    caseOf [.subj] .subj = some .erg ∧ caseOf [.subj] .obj = some .abs ∧
      caseOf [.obj, .subj] .subj = some .abs ∧ caseOf [.obj, .subj] .obj = some .abs := by
  decide

/-- **Agent focus.** Whichever phrases are wh-phrases, in a transitive derivation with an external
argument Voice and T cross-reference the same argument exactly when the object checks `[·D·]`
before the subject merges. -/
theorem agentFocus_iff {whs : List Transitive}
    (hw : whs ∈ ([[], [.subj], [.obj], [.subj, .obj]] : List (List Transitive)))
    {es : List Transitive} (h : TransitiveDerivation ∅ .D whs es) (hs : .subj ∈ es) :
    AgentFocus es ↔ es = [.obj, .subj] := by
  have hm := Transitive.mem_arrangements h.nodup
  revert h hs; revert hm; revert es; revert whs
  decide

/-- **NP objects obviate agent focus.** An NP object cannot check `[·D·]`, so a subject question
has only the derivation in which the subject checks `[·D·]` and `[·wh·]` at once; Set A
cross-references the subject and Set B the object, as in a transitive clause. -/
theorem npObject_no_agentFocus {es : List Transitive}
    (h : TransitiveDerivation ∅ .N [.subj] es) (hs : .subj ∈ es) :
    es = [.subj] ∧ setA es = some .subj ∧ setB es = some .obj ∧ ¬ AgentFocus es := by
  have hm := Transitive.mem_arrangements h.nodup
  revert h hs; revert hm; revert es
  decide

/-- The subject question with an NP object is licensed. -/
example : TransitiveDerivation ∅ .N [.subj] [.subj] := by decide

/-- When `[·wh·]` is checked once, a wh-subject and a wh-object cannot both become specifiers of
v, whichever merges first. -/
theorem multipleFronting_blocked {es : List Transitive}
    (h : TransitiveDerivation ∅ .D [.subj, .obj] es) : ¬ (.subj ∈ es ∧ .obj ∈ es) := by
  have hm := Transitive.mem_arrangements h.nodup
  revert h; revert hm; revert es
  decide

/-- **Multiple fronting.** When `[·wh·]` stays active, a wh-subject and a plain object merge
object first, a wh-object and a plain subject subject first, and two wh-phrases in either order;
agent focus arises exactly when the object is the outer specifier. -/
theorem multipleFronting {es : List Transitive} (hnd : es.Nodup) (hs : .subj ∈ es)
    (ho : .obj ∈ es) :
    (TransitiveDerivation {.wh} .D [.subj] es ↔ es = [.obj, .subj]) ∧
      (TransitiveDerivation {.wh} .D [.obj] es ↔ es = [.subj, .obj]) ∧
      (TransitiveDerivation {.wh} .D [.subj, .obj] es ↔
        es = [.subj, .obj] ∨ es = [.obj, .subj]) ∧
      ∀ whs ∈ ([[.subj], [.obj], [.subj, .obj]] : List (List Transitive)),
        TransitiveDerivation {.wh} .D whs es → (AgentFocus es ↔ es = [.obj, .subj]) := by
  have hm := Transitive.mem_arrangements hnd
  revert hnd hs ho; revert hm; revert es
  decide

/-! ### Weak Economy -/

/-- A system of operations at v fixes the features each operation checks, the operations, and
when an operation is available given the ones already applied. -/
structure System (ι : Type*) where
  /-- `checks a` is the set of features operation `a` checks. -/
  checks : ι → Finset Feature
  /-- `ops` lists the operations. -/
  ops : List ι
  /-- `Available done a` holds when `a` is available after the operations `done`. -/
  Available : List ι → ι → Prop
  /-- Availability is decidable. -/
  decAvailable : ∀ done a, Decidable (Available done a)

attribute [instance] System.decAvailable

namespace System

variable {ι : Type*} [DecidableEq ι] (S : System ι)

/-- An operation is possible when it has not applied, is available, and would check an unchecked
Merge feature. -/
def Possible (s : Finset Feature) (done : List ι) (a : ι) : Prop :=
  a ∉ done ∧ S.Available done a ∧ ∃ f ∈ s ∩ S.checks a, f.IsMerge

instance (s : Finset Feature) (done : List ι) (a : ι) : Decidable (S.Possible s done a) :=
  inferInstanceAs (Decidable (_ ∧ _ ∧ _))

/-- Doing `a` bleeds `b` when `b` is possible now but not once `a` has applied. -/
def Bleeds (s : Finset Feature) (done : List ι) (a b : ι) : Prop :=
  S.Possible s done b ∧ ¬ S.Possible (s \ S.checks a) (done ++ [a]) b

instance (s : Finset Feature) (done : List ι) (a b : ι) : Decidable (S.Bleeds s done a b) :=
  inferInstanceAs (Decidable (_ ∧ _))

/-- Weak Economy does not compare two operations when either would bleed the other. -/
def Exempt (s : Finset Feature) (done : List ι) (a b : ι) : Prop :=
  S.Bleeds s done a b ∨ S.Bleeds s done b a

instance (s : Finset Feature) (done : List ι) (a b : ι) : Decidable (S.Exempt s done a b) :=
  inferInstanceAs (Decidable (_ ∨ _))

/-- Weak Economy as Newman words it exempts `a` from comparison with an operation `b` checking
more features only when doing `b` would bleed `a`. -/
def ExemptLiteral (s : Finset Feature) (done : List ι) (a b : ι) : Prop := S.Bleeds s done b a

instance (s : Finset Feature) (done : List ι) (a b : ι) :
    Decidable (S.ExemptLiteral s done a b) :=
  inferInstanceAs (Decidable (S.Bleeds s done b a))

/-- Newman's conjecture further exempts two operations that would check a common feature. -/
def ExemptOverlap (s : Finset Feature) (done : List ι) (a b : ι) : Prop :=
  S.Exempt s done a b ∨ (s ∩ S.checks a ∩ S.checks b).Nonempty

instance (s : Finset Feature) (done : List ι) (a b : ι) :
    Decidable (S.ExemptOverlap s done a b) :=
  inferInstanceAs (Decidable (_ ∨ _))

/-- **Weak Economy** permits `a` unless some possible operation would check more features and
is not exempt from comparison with it under `E`. -/
def WeakEconomy (E : Finset Feature → List ι → ι → ι → Prop) (s : Finset Feature)
    (done : List ι) (a : ι) : Prop :=
  ∀ b ∈ S.ops, S.Possible s done b →
    (s ∩ S.checks a).card < (s ∩ S.checks b).card → E s done a b

instance (E : Finset Feature → List ι → ι → ι → Prop) [∀ s d a b, Decidable (E s d a b)]
    (s : Finset Feature) (done : List ι) (a : ι) : Decidable (S.WeakEconomy E s done a) :=
  inferInstanceAs (Decidable (∀ b ∈ S.ops, _))

/-- `S.Derivation E s done es` holds when, after the operations `done` and with `s` unchecked,
the operations `es` apply in order, each possible and permitted by Weak Economy, until no
operation is possible. -/
def Derivation (E : Finset Feature → List ι → ι → ι → Prop) :
    Finset Feature → List ι → List ι → Prop
  | s, done, [] => ∀ b ∈ S.ops, ¬ S.Possible s done b
  | s, done, e :: es => e ∈ S.ops ∧ S.Possible s done e ∧ S.WeakEconomy E s done e ∧
      Derivation E (s \ S.checks e) (done ++ [e]) es

instance decDerivation (E : Finset Feature → List ι → ι → ι → Prop)
    [∀ s d a b, Decidable (E s d a b)] :
    (s : Finset Feature) → (done es : List ι) → Decidable (S.Derivation E s done es)
  | _, _, [] => inferInstanceAs (Decidable (∀ b ∈ S.ops, _))
  | s, done, e :: es =>
    haveI := decDerivation E (s \ S.checks e) (done ++ [e]) es
    inferInstanceAs (Decidable (_ ∧ _ ∧ _ ∧ _))

/-- An economical derivation is one under Weak Economy as Newman applies it, from scratch. -/
abbrev Economical (s : Finset Feature) (es : List ι) : Prop := S.Derivation S.Exempt s [] es

/-- An overlap-economical derivation is one under Newman's conjecture, from scratch. -/
abbrev OverlapEconomical (s : Finset Feature) (es : List ι) : Prop :=
  S.Derivation S.ExemptOverlap s [] es

/-- The subject of a derivation is the first operation that can check v's `[·D·]`. -/
def subject (es : List ι) : Option ι := es.find? fun a ↦ Feature.D ∈ S.checks a

variable {S}

omit [DecidableEq ι] in
theorem derivation_cons {E : Finset Feature → List ι → ι → ι → Prop} {s : Finset Feature}
    {done es : List ι} {e : ι} :
    S.Derivation E s done (e :: es) ↔ e ∈ S.ops ∧ S.Possible s done e ∧
      S.WeakEconomy E s done e ∧ S.Derivation E (s \ S.checks e) (done ++ [e]) es :=
  Iff.rfl

omit [DecidableEq ι] in
/-- The operations of a derivation are distinct, drawn from the system, and new. -/
theorem Derivation.nodup {E : Finset Feature → List ι → ι → ι → Prop} {s : Finset Feature}
    {done es : List ι} (h : S.Derivation E s done es) :
    es.Nodup ∧ es ⊆ S.ops ∧ ∀ e ∈ es, e ∉ done := by
  induction es generalizing s done with
  | nil => simp
  | cons e es ih =>
    obtain ⟨he, ⟨hd, _⟩, _, h⟩ := derivation_cons.1 h
    obtain ⟨hnd, hsub, hnot⟩ := ih h
    refine ⟨List.nodup_cons.2 ⟨fun hes ↦ hnot e hes (by simp), hnd⟩,
      List.cons_subset.2 ⟨he, hsub⟩, fun x hx ↦ ?_⟩
    rcases List.mem_cons.1 hx with rfl | hx
    · exact hd
    · exact fun hxd ↦ hnot x hx (List.mem_append_left _ hxd)

/-- Weak Economy never blocks every operation. The possible operation checking the most features
is always permitted, so from any state some derivation runs to completion, whatever the
exemptions. -/
theorem exists_derivation (E : Finset Feature → List ι → ι → ι → Prop) (s : Finset Feature)
    (done : List ι) : ∃ es, S.Derivation E s done es := by
  induction s using Finset.strongInduction generalizing done with
  | H s ih =>
    by_cases hpos : ∃ b ∈ S.ops, S.Possible s done b
    · obtain ⟨b, hb, hmax⟩ := Finset.exists_max_image
        ((S.ops.filter fun b ↦ S.Possible s done b).toFinset) (fun b ↦ (s ∩ S.checks b).card)
        (by obtain ⟨b, hb, hp⟩ := hpos; exact ⟨b, by simp [hb, hp]⟩)
      simp only [List.mem_toFinset, List.mem_filter, decide_eq_true_eq] at hb hmax
      obtain ⟨f, hf, -⟩ := hb.2.2.2
      have hsub : s \ S.checks b ⊂ s := (Finset.ssubset_iff_of_subset Finset.sdiff_subset).2
        ⟨f, (Finset.mem_inter.1 hf).1, fun h ↦ (Finset.mem_sdiff.1 h).2 (Finset.mem_inter.1 hf).2⟩
      obtain ⟨es, hes⟩ := ih _ hsub (done ++ [b])
      exact ⟨b :: es, hb.1, hb.2, fun c hc hcp hlt ↦ absurd (hmax c ⟨hc, hcp⟩) (not_le.2 hlt),
        hes⟩
    · push Not at hpos
      exact ⟨[], hpos⟩

omit [DecidableEq ι] in
/-- Every derivation is licensed, since Weak Economy only restricts the order of operations. -/
theorem Derivation.licensed {E : Finset Feature → List ι → ι → ι → Prop} {s : Finset Feature}
    {done es : List ι} (h : S.Derivation E s done es) : Licensed S.checks ∅ s es := by
  induction es generalizing s done with
  | nil => trivial
  | cons e es ih =>
    obtain ⟨_, ⟨_, _, f, hf, _⟩, _, h⟩ := derivation_cons.1 h
    exact licensed_cons.2 ⟨⟨f, hf⟩, by rw [Finset.sdiff_empty]; exact ih h⟩

/-- A derivation is one of the arrangements of the operations. -/
private theorem Derivation.mem_arrangements {E : Finset Feature → List ι → ι → ι → Prop}
    {s : Finset Feature} {es : List ι} (h : S.Derivation E s [] es) :
    es ∈ arrangements S.ops S.ops.length :=
  mem_arrangements_length h.nodup.1 h.nodup.2.1

end System

/-! ### Passives of ditransitives -/

/-- The operations at v in a passive ditransitive are raising the indirect object, merging VP,
and raising the direct object. -/
inductive Passive where
  | iobj
  | vp
  | dobj
  deriving DecidableEq, Repr

/-- `Passive.phrase io dobj a` is the phrase operation `a` merges, given the indirect object `io`
and the direct object `dobj`. -/
def Passive.phrase (io dobj : Phrase) : Passive → Phrase
  | .iobj => io
  | .vp => .vp
  | .dobj => dobj

/-- In a double object passive the indirect object sits in v's complement, accessible from the
start, and the direct object is accessible once VP has merged. -/
def highPassive (io dobj : Phrase) : System Passive where
  checks := Phrase.checks ∘ Passive.phrase io dobj
  ops := [.iobj, .vp, .dobj]
  Available done a := a = .dobj → .vp ∈ done
  decAvailable _ _ := inferInstanceAs (Decidable (_ → _))

/-- In a prepositional passive VP is v's complement and the direct object c-commands the
indirect object, so the indirect object is accessible only once the direct object has moved. -/
def lowPassive (io dobj : Phrase) : System Passive where
  checks := Phrase.checks ∘ Passive.phrase io dobj
  ops := [.vp, .dobj, .iobj]
  Available done a := (a ≠ .vp → .vp ∈ done) ∧ (a = .iobj → .dobj ∈ done)
  decAvailable _ _ := inferInstanceAs (Decidable (_ ∧ _))

/-- `afterXP` is the set of v's features left once the phrase containing the indirect object has
checked `[·X·]`. -/
def afterXP : Finset Feature := bundlev \ Phrase.checks ⟨.P, ∅⟩

/-- **Symmetric passives.** With plain objects either one can become the subject of a double
object passive. -/
theorem symmetric_passive :
    (∃ es, (highPassive .dp .dp).Economical afterXP es ∧
      (highPassive .dp .dp).subject es = some .iobj) ∧
    ∃ es, (highPassive .dp .dp).Economical afterXP es ∧
      (highPassive .dp .dp).subject es = some .dobj :=
  ⟨⟨[.iobj, .vp], by decide⟩, ⟨[.vp, .dobj], by decide⟩⟩

/-- **The double object movement asymmetry.** A wh indirect object checks `[·D·]` and `[·wh·]`
at once, so Weak Economy raises it before VP merges, and it is the subject of every passive. -/
theorem doma {es : List Passive} (h : (highPassive .whDP .dp).Economical afterXP es) :
    (highPassive .whDP .dp).subject es = some .iobj := by
  have hm := System.Derivation.mem_arrangements h
  revert h; revert hm; revert es
  decide

/-- The wh indirect object raises first; raising the direct object is licensed but not
economical. -/
example : (highPassive .whDP .dp).Economical afterXP [.iobj, .vp] ∧
    Licensed (highPassive .whDP .dp).checks ∅ afterXP [.vp, .dobj] ∧
    ¬ (highPassive .whDP .dp).Economical afterXP [.vp, .dobj] := by decide

/-- A wh direct object becomes accessible only after VP merges, too late to force the order, so
either object can still become the subject. -/
theorem whDobj_symmetric :
    (∃ es, (highPassive .dp .whDP).Economical afterXP es ∧
      (highPassive .dp .whDP).subject es = some .iobj) ∧
    ∃ es, (highPassive .dp .whDP).Economical afterXP es ∧
      (highPassive .dp .whDP).subject es = some .dobj :=
  ⟨⟨[.iobj, .vp, .dobj], by decide⟩, ⟨[.vp, .dobj], by decide⟩⟩

/-- In a prepositional passive only the direct object can become the subject, even when the
indirect object is a wh-phrase. -/
theorem lowPassive_subject {io : Phrase} (hio : io ∈ [Phrase.dp, .whDP]) {es : List Passive}
    (h : (lowPassive io .dp).Economical bundlev es) :
    (lowPassive io .dp).subject es = some .dobj := by
  have hm := System.Derivation.mem_arrangements h
  revert h; revert hm; revert es; revert io
  decide

/-- A prepositional passive raises the direct object, and a wh indirect object then checks
`[·wh·]`. -/
example : (lowPassive .dp .dp).Economical bundlev [.vp, .dobj] ∧
    (lowPassive .whDP .dp).Economical bundlev [.vp, .dobj, .iobj] := by decide

/-- **No indirect object passives with inherent case.** An indirect object with an inherent-case
shell cannot check `[·D·]`, so it is never the passive subject. -/
theorem iobj_kp_not_subject {bears : Finset Feature} (hD : Feature.D ∉ bears) (dobj : Phrase)
    (es : List Passive) : (highPassive ⟨.K, bears⟩ dobj).subject es ≠ some .iobj := by
  intro h
  have := List.find?_some h
  simp [highPassive, Passive.phrase, hD] at this

/-! ### Object marking -/

/-- v in a language with object marking also bears the object-marking feature. -/
def bundlevOM : Finset Feature := insert .om bundlev

/-- `afterXPOM` is the set of such a v's features left once the phrase containing the indirect
object has checked `[·X·]`. -/
def afterXPOM : Finset Feature := bundlevOM \ Phrase.checks ⟨.P, ∅⟩

/-- `omDP` is a DP controlling object marking. -/
def omDP : Phrase := ⟨.D, {.om}⟩

/-- An indirect object controlling object marking checks `[·D·]` and the object-marking feature
at once, so it is the subject of every passive. -/
theorem om_iobj_subject {es : List Passive}
    (h : (highPassive omDP .dp).Economical afterXPOM es) :
    (highPassive omDP .dp).subject es = some .iobj := by
  have hm := System.Derivation.mem_arrangements h
  revert h; revert hm; revert es
  decide

/-- The object-marked indirect object raises before VP merges. -/
example : (highPassive omDP .dp).Economical afterXPOM [.iobj, .vp] ∧
    ¬ (highPassive omDP .dp).Economical afterXPOM [.vp, .dobj] := by decide

/-- A direct object can control object marking in a passive whose subject is the indirect
object. -/
theorem om_dobj_recipientPassive :
    ∃ es, (highPassive .dp omDP).Economical afterXPOM es ∧
      (highPassive .dp omDP).subject es = some .iobj ∧ .dobj ∈ es :=
  ⟨[.iobj, .vp, .dobj], by decide⟩

/-! ### Greek clitic doubling -/

/-- The operations at Greek v after the phrase containing the indirect object has merged are
clitic doubling the indirect object, wh-moving its KP, merging VP, raising the direct object, and
merging the external argument. -/
inductive Greek where
  | clitic
  | kp
  | vp
  | dobj
  | subj
  deriving DecidableEq, Repr

/-- Greek v bears `[·Dweak·]` and a φ-probe besides v's features. -/
def bundlevGreek : Finset Feature := {.D, .Dweak, .X, .V, .wh, .phi}

/-- `afterXPGreek` is the set of Greek v's features left once the phrase containing the indirect
object has checked `[·X·]`. -/
def afterXPGreek : Finset Feature := bundlevGreek \ Phrase.checks ⟨.P, ∅⟩

/-- Clitic doubling Agrees with the DP inside the indirect object's KP and moves a clitic, a weak
D-element, so it checks `[uφ]` and `[·Dweak·]`; the other operations check what their phrases
check. -/
def Greek.checks (kp : Phrase) : Greek → Finset Feature
  | .clitic => {.Dweak, .phi}
  | .kp => kp.checks
  | .vp => Phrase.vp.checks
  | .dobj | .subj => Phrase.dp.checks

/-- `greek kp ops` is Greek v with the indirect object's KP `kp` and the operations `ops`. The
clitic is accessible while the KP is in v's complement, the direct object once VP has merged. -/
def greek (kp : Phrase) (ops : List Greek) : System Greek where
  checks := Greek.checks kp
  ops := ops
  Available done a := (a = .clitic → .kp ∉ done) ∧ (a = .dobj → .vp ∈ done)
  decAvailable _ _ := inferInstanceAs (Decidable (_ ∧ _))

/-- `greekPassive` lists the operations of a Greek passive. -/
def greekPassive : List Greek := [.clitic, .kp, .vp, .dobj]

/-- `greekActive` lists the operations of a Greek active. -/
def greekActive : List Greek := [.clitic, .kp, .vp, .dobj, .subj]

/-- **Dative intervention.** In a Greek passive, clitic doubling checks two features and merging
VP one, so the indirect object is clitic doubled before the direct object can raise. -/
theorem greek_passive {es : List Greek}
    (h : (greek ⟨.K, ∅⟩ greekPassive).Economical afterXPGreek es) :
    es.head? = some .clitic ∧ (greek ⟨.K, ∅⟩ greekPassive).subject es = some .dobj := by
  have hm := System.Derivation.mem_arrangements h
  revert h; revert hm; revert es
  decide

/-- The plain passive clitic doubles, merges VP, and raises the direct object; merging VP first is
licensed but not economical. -/
example : (greek ⟨.K, ∅⟩ greekPassive).Economical afterXPGreek [.clitic, .vp, .dobj] ∧
    ¬ (greek ⟨.K, ∅⟩ greekPassive).Economical afterXPGreek [.vp, .clitic, .dobj] := by decide

/-- A wh indirect object makes clitic doubling optional. Wh-moving the KP out of v's complement
bleeds clitic doubling, so Weak Economy does not compare the two, and the direct object is the
subject either way. -/
theorem greek_whPassive :
    (∀ es, (greek ⟨.K, {.wh}⟩ greekPassive).Economical afterXPGreek es →
      (greek ⟨.K, {.wh}⟩ greekPassive).subject es = some .dobj) ∧
    (∃ es, (greek ⟨.K, {.wh}⟩ greekPassive).Economical afterXPGreek es ∧ .clitic ∉ es) ∧
    ∃ es, (greek ⟨.K, {.wh}⟩ greekPassive).Economical afterXPGreek es ∧ .clitic ∈ es :=
  ⟨fun es h ↦ by
    have hm := System.Derivation.mem_arrangements h
    revert h; revert hm; revert es
    decide,
    ⟨[.kp, .vp, .dobj], by decide⟩, ⟨[.clitic, .kp, .vp, .dobj], by decide⟩⟩

/-- In a Greek active clitic doubling is optional. The external argument checks `[·D·]` and
`[·Dweak·]`, as many features as clitic doubling, and bleeds it by checking `[·Dweak·]`. -/
theorem greek_active :
    (∃ es, (greek ⟨.K, ∅⟩ greekActive).Economical afterXPGreek es ∧ .subj ∈ es ∧
      .clitic ∈ es) ∧
    ∃ es, (greek ⟨.K, ∅⟩ greekActive).Economical afterXPGreek es ∧ .subj ∈ es ∧
      .clitic ∉ es :=
  ⟨⟨[.clitic, .subj, .vp], by decide⟩, ⟨[.subj, .vp], by decide⟩⟩

/-- Once the external argument has checked `[·Dweak·]`, clitic doubling is no longer possible. -/
example : ¬ (greek ⟨.K, ∅⟩ greekActive).Economical afterXPGreek [.subj, .clitic, .vp] := by
  decide

/-- `greekFlat kp ops` is Greek v in a system where wh-movement of the KP would leave the clitic
accessible. -/
def greekFlat (kp : Phrase) (ops : List Greek) : System Greek where
  checks := Greek.checks kp
  ops := ops
  Available done a := a = .dobj → .vp ∈ done
  decAvailable _ _ := inferInstanceAs (Decidable (_ → _))

/-- Without the structural bleeding, Weak Economy would force clitic doubling in wh passives, so
the optionality of Greek clitic doubling depends on wh-movement removing the KP from v's
complement. -/
theorem greekFlat_whPassive {es : List Greek}
    (h : (greekFlat ⟨.K, {.wh}⟩ greekPassive).Economical afterXPGreek es) : .clitic ∈ es := by
  have hm := System.Derivation.mem_arrangements h
  revert h; revert hm; revert es
  decide

/-- In that system the wh passive still has a derivation, with clitic doubling first. -/
example : (greekFlat ⟨.K, {.wh}⟩ greekPassive).Economical afterXPGreek [.clitic, .kp, .vp, .dobj] :=
  by decide

/-- **The wording of Weak Economy.** Read as worded, Weak Economy exempts an operation only when
the operation checking more features would bleed it. Clitic doubling checks more features than
wh-movement of the KP and does not bleed it, so under that reading clitic doubling would be
obligatory in Greek wh passives, contrary to the passives without a clitic that Newman cites; her
analysis needs the bleeding of either operation by the other to exempt them. -/
theorem literal_greek_whPassive {es : List Greek}
    (h : (greek ⟨.K, {.wh}⟩ greekPassive).Derivation
      (greek ⟨.K, {.wh}⟩ greekPassive).ExemptLiteral afterXPGreek [] es) : .clitic ∈ es := by
  have hm := System.Derivation.mem_arrangements h
  revert h; revert hm; revert es
  decide

/-- Under the literal reading the wh passive still has a derivation, with clitic doubling
first. -/
example : (greek ⟨.K, {.wh}⟩ greekPassive).Derivation
    (greek ⟨.K, {.wh}⟩ greekPassive).ExemptLiteral afterXPGreek [] [.clitic, .kp, .vp, .dobj] := by
  decide

/-! ### Weak Economy in subject questions -/

/-- `transitiveSystem whs` has the operations at v in a transitive clause with the phrases in
`whs` bearing `[wh]`: merging VP, moving the object once VP has merged, and merging the external
argument. -/
def transitiveSystem (whs : List Transitive) : System Transitive where
  checks := Phrase.checks ∘ Transitive.phrase .D whs
  ops := [.vp, .obj, .subj]
  Available done a := a = .obj → .vp ∈ done
  decAvailable _ _ := inferInstanceAs (Decidable (_ → _))

/-- **Weak Economy makes a wh-subject v's complement.** The wh-subject checks `[·D·]`, `[·X·]` and
`[·wh·]`, VP only `[·X·]` and `[·V·]`, and neither bleeds the other, so Weak Economy merges the
subject first, ruling out both subject-question derivations with VP as v's complement. -/
theorem whSubject_complement {es : List Transitive}
    (h : (transitiveSystem [.subj]).Economical bundlev es) : es.head? = some .subj := by
  have hm := System.Derivation.mem_arrangements h
  revert h; revert hm; revert es
  decide

/-- The wh-subject question has the derivation with the subject as v's complement, but not the
licensed one with VP as the complement. -/
example : (transitiveSystem [.subj]).Economical bundlev [.subj, .vp] ∧
    TransitiveDerivation ∅ .D [.subj] [.subj] ∧
    ¬ (transitiveSystem [.subj]).Economical bundlev [.vp, .subj] := by decide

/-- With a plain subject, VP and the subject check two features each, so either can be v's
complement. -/
theorem plainSubject_either :
    (∃ es, (transitiveSystem []).Economical bundlev es ∧ es.head? = some .vp) ∧
    ∃ es, (transitiveSystem []).Economical bundlev es ∧ es.head? = some .subj :=
  ⟨⟨[.vp, .subj], by decide⟩, ⟨[.subj, .vp], by decide⟩⟩

/-- **Newman's conjecture restores the subject-question derivations.** When operations checking a
common feature are exempt, VP and a wh-subject, which share `[·X·]`, are not compared, and both
subject-question derivations and the object-question derivation are economical. -/
theorem overlap_subjectQuestions :
    (transitiveSystem [.subj]).OverlapEconomical bundlev [.vp, .subj] ∧
      (transitiveSystem [.subj]).OverlapEconomical bundlev [.vp, .obj, .subj] ∧
      (transitiveSystem [.obj]).OverlapEconomical bundlev [.vp, .subj, .obj] := by
  decide

/-- The conjecture leaves the passive results intact. The wh indirect object is still the
subject of every double object passive, and Greek clitic doubling is still obligatory in plain
passives and optional in wh passives and actives. -/
theorem overlap_passives :
    (∀ es, (highPassive .whDP .dp).OverlapEconomical afterXP es →
      (highPassive .whDP .dp).subject es = some .iobj) ∧
    (∀ es, (greek ⟨.K, ∅⟩ greekPassive).OverlapEconomical afterXPGreek es →
      es.head? = some .clitic) ∧
    (∃ es, (greek ⟨.K, {.wh}⟩ greekPassive).OverlapEconomical afterXPGreek es ∧
      .clitic ∉ es) ∧
    (∃ es, (greek ⟨.K, ∅⟩ greekActive).OverlapEconomical afterXPGreek es ∧ .subj ∈ es ∧
      .clitic ∉ es) :=
  ⟨fun es h ↦ by
    have hm := System.Derivation.mem_arrangements h
    revert h; revert hm; revert es
    decide,
    fun es h ↦ by
    have hm := System.Derivation.mem_arrangements h
    revert h; revert hm; revert es
    decide,
    ⟨[.kp, .vp, .dobj], by decide⟩, ⟨[.subj, .vp], by decide⟩⟩

end Newman2024
