module

public import Mathlib.Tactic.DeriveFintype
public import Linglib.Syntax.Minimalist.Phi.Lattice
public import Linglib.Data.Examples.Toosarvandani2023

/-!
# Toosarvandani (2023): The Interpretation and Grammatical Representation of Animacy

This file formalizes the plurality-based semantics of animacy of [toosarvandani-2023] and its
consequence for the person-case constraint. The third-person plural pronouns of Southeastern
Sierra Zapotec, which distinguish elders, other humans, animals and inanimates, show the
associativity of local-person plurals, (14): they refer to heterogeneous groups, a mixed group
takes the most marked pronoun, and the members must be associates in the context. The
account composes animacy features as [harbour-2016] and [kratzer-2009] compose person
features. A feature denotes the lattice generated by its atoms, (48) and (58), the atoms of
*speaker*, *participant*, *elder*, *human* and *animate* forming entailment chains, and
features combine by the pointwise join `⊕`, (50), so a specification such as *elder* over
*human* over *animate* over π denotes every group containing an elder, (53) and (62),
`specification_eq_containing`: heterogeneity. Lexical complementarity, (52), restricts a
pronoun to what no more specified pronoun denotes, so a mixed group takes the most marked
pronoun, `mixed_group_marked`, and the local persons take the speaker and addressee away
from the elder pronoun, `mem_elder_lexComp_iff`: marked reference. Number composes by
intersection after person and animacy, (57), `singular_containing`, and cannot precede them,
since `⊕` would restore the pluralities that *singular* removed, (63),
`exists_plural_oplus_singular`. Social gender cannot compose the same way: disjoint feature
denotations give pronouns neither of which is the more specified, (71), `gender_incomparable`.
Because person and animacy features share one head, the condition on Agree behind the
person-case constraint, (86), that a head Agrees with two pronouns iff the higher has all the
features of the lower, compares them together. The Zapotec specifications (60)–(61) form a
chain, so Agree holds iff the subject is at least as high on the hierarchy, `agrees_iff`,
(77)–(81), and a probe relativized to fewer animacy features, as in the Laxopa and Zoogocho
varieties, collapses the distinctions it does not see, `AgreesUnder.mono`.

## Implementation notes

Individuals are a finite type and a group a nonempty finite set of atoms, the join being
union, as in `Syntax/Minimalist/Phi/Lattice.lean`, where the composition and complementarity
lemmas live; a feature's atoms are a `Finset`, with the speaker and addressee among the
elders, (58a). Context-dependence, (54), is not modelled: the associate relation is left to
the context. The person-based constraint is absolute in Zapotec while (86) derives a relative
one, a difference the paper attributes to the probe's relativization, and the same-category
pairings that (86) licenses are not in the data. The Agree-based theory generalizes
[deal-2024]'s, with the probe's features sequenced after [coon-keine-2021] so that only the
features of the highest head, person and animacy, enter the comparison. The Yalálag clitic
data of (77)–(81) and the English context-dependence examples of (16)–(18) are the rows of
`Data.Examples.Toosarvandani2023`.

## References

* [toosarvandani-2023]
* [harbour-2016]
* [kratzer-2009]
* [link-1983]
* [deal-2024]
* [coon-keine-2021]
-/

@[expose] public section

namespace Toosarvandani2023

open Minimalist.Phi.Lattice Finset

/-! ### Features and their composition (section 3) -/

variable {Ind : Type*} [DecidableEq Ind] [Fintype Ind]

/-- ⟦π⟧, (48c): every singular or plural individual. -/
def piDen : Finset (Finset Ind) := nePowerset univ

/-- A feature specification: the features' lattices added by `⊕` over π, the last listed
innermost, (51) and (61). -/
def specification (fs : List (Finset Ind)) : Finset (Finset Ind) :=
  fs.foldr (λ X acc => oplus (nePowerset X) acc) piDen

@[simp] theorem specification_nil : specification ([] : List (Finset Ind)) = piDen := rfl

@[simp] theorem specification_cons (X : Finset Ind) (fs : List (Finset Ind)) :
    specification (X :: fs) = oplus (nePowerset X) (specification fs) := rfl

/-- (53) and (62): along an entailment chain of features, a specification denotes the groups
containing an atom of its most specific feature. -/
theorem specification_eq_containing : ∀ {fs : List (Finset Ind)} {X : Finset Ind},
    (X :: fs).Pairwise (· ⊆ ·) → specification (X :: fs) = containing X univ
  | [], X, _ => oplus_nePowerset_nePowerset (subset_univ X)
  | Y :: fs, X, h => by
    have h' := List.pairwise_cons.1 h
    rw [specification_cons, specification_eq_containing h'.2,
      oplus_nePowerset_containing (h'.1 Y (by simp)) (subset_univ _)]

/-- Marked reference, (62): a group of an elder and a nonelder human lies in the elder and
the human specifications, and lexical complementarity removes it from the human pronoun. -/
theorem mixed_group_marked {E H : Finset Ind} {e h : Ind} (he : e ∈ E) (hh : h ∈ H) :
    {e, h} ∈ containing E univ ∧ {e, h} ∈ containing H univ ∧
      {e, h} ∉ lexComp (containing H univ) (containing E univ) :=
  ⟨mem_containing_iff.2 ⟨subset_univ _, e, by simp [he]⟩,
    mem_containing_iff.2 ⟨subset_univ _, h, by simp [hh]⟩,
    λ hm => (mem_lexComp_containing_iff.1 hm).2.2 ⟨e, by simp [he]⟩⟩

/-- (62a): against the local persons, whose most specific features have the speaker and the
addressee as atoms, the elder pronoun refers to the groups with an elder and no
conversational participant. -/
theorem mem_elder_lexComp_iff {E : Finset Ind} {i u : Ind} {s : Finset Ind} :
    s ∈ lexComp (containing E univ) (containing {i, u} univ) ↔
      (s ∩ E).Nonempty ∧ i ∉ s ∧ u ∉ s := by
  rw [mem_lexComp_containing_iff, not_nonempty_iff_eq_empty, eq_empty_iff_forall_notMem]
  simp only [subset_univ, true_and, mem_inter, mem_insert, mem_singleton, not_and, not_or]
  constructor
  · rintro ⟨hE, h⟩
    exact ⟨hE, λ hi => (h i hi).1 rfl, λ hu => (h u hu).2 rfl⟩
  · rintro ⟨hE, hi, hu⟩
    exact ⟨hE, λ x hx => ⟨λ h => hi (h ▸ hx), λ h => hu (h ▸ hx)⟩⟩

/-! ### Number (section 3.2) -/

/-- (56a): *singular* keeps the atomic individuals, composing by intersection. -/
def singular (L : Finset (Finset Ind)) : Finset (Finset Ind) := L.filter λ s => s.card = 1

/-- (57): composed after person and animacy, *singular* leaves a specification's atoms. -/
theorem singular_containing (X : Finset Ind) : singular (containing X univ) = X.image ({·}) := by
  ext s
  simp only [singular, mem_filter, mem_containing_iff, subset_univ, true_and, card_eq_one,
    mem_image]
  constructor
  · rintro ⟨hX, a, rfl⟩
    obtain ⟨b, hb⟩ := hX
    rw [mem_inter, mem_singleton] at hb
    exact ⟨a, hb.1 ▸ hb.2, rfl⟩
  · rintro ⟨a, ha, rfl⟩
    exact ⟨⟨a, by simp [ha]⟩, a, rfl⟩

/-- (63): a feature composed by `⊕` after *singular* restores pluralities. -/
theorem pair_mem_oplus_singular {X : Finset Ind} {x : Ind} (hx : x ∈ X) (y : Ind) :
    ({x, y} : Finset Ind) ∈ oplus (nePowerset X) (singular piDen) := by
  rw [insert_eq]
  exact mem_oplus_of_mem
    (mem_nePowerset_iff.2 ⟨singleton_nonempty x, singleton_subset_iff.2 hx⟩)
    (mem_filter.2
      ⟨mem_nePowerset_iff.2 ⟨singleton_nonempty y, subset_univ _⟩, card_singleton y⟩)

/-- So person and animacy must compose before number. -/
theorem exists_plural_oplus_singular {X : Finset Ind} {x y : Ind} (hx : x ∈ X) (hxy : x ≠ y) :
    ∃ s ∈ oplus (nePowerset X) (singular piDen), s.card ≠ 1 :=
  ⟨{x, y}, pair_mem_oplus_singular hx y, by rw [card_pair hxy]; decide⟩

/-! ### Social gender (section 3.5) -/

/-- (71): feminine and masculine atoms are disjoint, so the pronouns their features would
compose by `⊕` are incomparable and lexical complementarity cannot restrict either. -/
theorem gender_incomparable {F M : Finset Ind} (hd : Disjoint F M) (hF : F.Nonempty)
    (hM : M.Nonempty) :
    ¬ containing F univ ⊆ containing M univ ∧ ¬ containing M univ ⊆ containing F univ :=
  ⟨containing_not_subset_of_disjoint hd hF (subset_univ _),
    containing_not_subset_of_disjoint hd.symm hM (subset_univ _)⟩

/-! ### The person-case constraint (section 4) -/

/-- The features of the highest nominal head in Zapotec, (60): a chain, each entailing the
next. -/
inductive Feature where
  | speaker
  | participant
  | elder
  | human
  | animate
  | pi
  deriving DecidableEq, Fintype, Repr

/-- Position in the chain, from the most specific. -/
def Feature.rank : Feature → ℕ
  | .speaker => 0
  | .participant => 1
  | .elder => 2
  | .human => 3
  | .animate => 4
  | .pi => 5

instance : LinearOrder Feature := LinearOrder.lift' Feature.rank (by decide)

/-- The pronoun categories of Table 1, clusivity set aside. -/
inductive Pronoun where
  | first
  | second
  | thirdElder
  | thirdHuman
  | thirdAnimal
  | thirdInanimate
  deriving DecidableEq, Fintype, Repr

/-- The most specific feature of a category's specification, (60)–(61). -/
def Pronoun.top : Pronoun → Feature
  | .first => .speaker
  | .second => .participant
  | .thirdElder => .elder
  | .thirdHuman => .human
  | .thirdAnimal => .animate
  | .thirdInanimate => .pi

/-- A category's feature specification: its most specific feature and all it entails. -/
def Pronoun.features (p : Pronoun) : Finset Feature := univ.filter (p.top ≤ ·)

/-- Specifications are nested as the hierarchy orders the categories. -/
theorem features_subset_iff {p q : Pronoun} : p.features ⊆ q.features ↔ q.top ≤ p.top :=
  ⟨λ h => (mem_filter.1 (h (mem_filter.2 ⟨mem_univ _, le_refl _⟩))).2,
    λ h _ hf => mem_filter.2 ⟨mem_univ _, h.trans (mem_filter.1 hf).2⟩⟩

/-- (86): a head Agrees with a subject and an object pronoun, and both cliticize, iff the
subject has all of the object's features. -/
def Agrees (subj obj : Pronoun) : Prop := obj.features ⊆ subj.features

instance (subj obj : Pronoun) : Decidable (Agrees subj obj) :=
  inferInstanceAs (Decidable (obj.features ⊆ subj.features))

/-- The specifications form a chain, so Agree holds iff the subject is at least as high on the
hierarchy: the object clitic is blocked exactly when the object outranks the subject,
(77)–(81). -/
theorem agrees_iff {subj obj : Pronoun} : Agrees subj obj ↔ subj.top ≤ obj.top :=
  features_subset_iff

/-- A probe relativized to the features `R` compares only those. -/
def AgreesUnder (R : Finset Feature) (subj obj : Pronoun) : Prop :=
  obj.features ∩ R ⊆ subj.features ∩ R

instance (R : Finset Feature) (subj obj : Pronoun) : Decidable (AgreesUnder R subj obj) :=
  inferInstanceAs (Decidable (obj.features ∩ R ⊆ subj.features ∩ R))

theorem agreesUnder_univ {subj obj : Pronoun} : AgreesUnder univ subj obj ↔ Agrees subj obj := by
  simp [AgreesUnder, Agrees]

/-- The fewer features a probe sees, the weaker the constraint. -/
theorem AgreesUnder.mono {R R' : Finset Feature} {subj obj : Pronoun} (h : R ⊆ R')
    (ha : AgreesUnder R' subj obj) : AgreesUnder R subj obj := λ _ hf =>
  mem_inter.2 ⟨(mem_inter.1 (ha (mem_inter.2 ⟨(mem_inter.1 hf).1, h (mem_inter.1 hf).2⟩))).1,
    (mem_inter.1 hf).2⟩

/-- The Laxopa probe does not see *elder*, so elder and nonelder human clitics combine
freely, where Yalálag's full relativization blocks (79b). -/
theorem laxopa_human_elder :
    AgreesUnder {.speaker, .participant, .human, .animate, .pi} .thirdHuman .thirdElder ∧
      ¬ Agrees .thirdHuman .thirdElder := by
  decide

/-- The Zoogocho probe sees only *animate* among the animacy features, so any animate
clitics combine. -/
theorem zoogocho_animal_elder :
    AgreesUnder {.speaker, .participant, .animate, .pi} .thirdAnimal .thirdElder := by
  decide

end Toosarvandani2023
