import Mathlib.Algebra.BigOperators.Field
import Linglib.Pragmatics.InformationTheory.Channel
import Linglib.Pragmatics.Efficiency

/-!
# Zaslavsky, Kemp, Regier and Tishby (2018): Efficient Compression in Color Naming

This file formalizes the communication model of [zaslavsky-kemp-regier-tishby-2018], in which
a color naming system is an encoder that compresses meanings, distributions over the colors of
the environment, into words, and languages are hypothesized to trade off the complexity of the
lexicon against the accuracy of communication as the Information Bottleneck principle of
[tishby-pereira-bialek-1999] prescribes. A `Model` bundles the meanings, the cognitive source
over them, and the encoder. The listener is an optimal Bayesian decoder, interpreting a word as
the posterior mixture of meanings (`decoder`). Complexity is the information the words carry
about the meanings (`complexity`), accuracy the information they carry about the environment
(`accuracy`), and the expected Kullback–Leibler distortion between the speaker's meaning and
the listener's interpretation is the information about the environment that the lexicon loses
(`distortion_eq`), so that minimizing distortion is maximizing accuracy. The Information
Bottleneck objective `F_β = I(M;W) − β I(W;U)` (`objective`) is, up to a constant, the
β-scalarized cost of `Pragmatics.Efficiency` on the pair of distortion and complexity
(`objective_eq_weightedCost`), and a language's deviation from optimality at `β` is the
substrate's `efficiencyLossAt` (`deviation_eq_efficiencyLossAt`). The optimal encoders satisfy
the self-consistent Boltzmann form in which a word's probability decays exponentially in its
divergence from the meaning (`IsIBOptimum`).

## Implementation notes

* Every distribution in a model is strictly positive, which keeps the logarithms of the
  information quantities finite; the empirical encoders of the World Color Survey are not in
  the library.
* The information quantities are the channel mutual informations of
  `Pragmatics.InformationTheory`; the paper's forms with the word marginal in the denominator
  are recovered by Bayes' rule (`complexity_eq`).
* The efficiency loss `ε_l` divides the minimal deviation by the fitted `β_l`; the fit itself
  is a numerical optimization outside the formalization.

## References

* [zaslavsky-kemp-regier-tishby-2018]
* [tishby-pereira-bialek-1999]
* [shannon-1948]
-/

namespace ZaslavskyKempRegierTishby2018

open Pragmatics.InformationTheory Pragmatics.Efficiency Finset Real

variable {U M W : Type} [Fintype U] [Fintype M] [Fintype W]

/-- The color communication model: meanings are distributions over the environment `U`,
generated by a cognitive source over `M`, and compressed into words `W` by an encoder. All
three distributions are strictly positive. -/
structure Model (U M W : Type) [Fintype U] [Fintype M] [Fintype W] where
  /-- Each meaning `m` is a distribution `m(u)` over the environment. -/
  meanings : CommChannel M U
  /-- The cognitive source `p(m)`. -/
  source : M → ℝ
  /-- The naming policy `q(w | m)`. -/
  encoder : CommChannel M W
  meanings_pos : ∀ m u, 0 < meanings.encode m u
  source_pos : ∀ m, 0 < source m
  source_sum : ∑ m, source m = 1
  encoder_pos : ∀ m w, 0 < encoder.encode m w

namespace Model

variable (𝓜 : Model U M W)

/-- A source that sums to one has a meaning. -/
theorem nonempty (𝓜 : Model U M W) : Nonempty M := by
  by_contra h
  rw [not_nonempty_iff] at h
  have := 𝓜.source_sum
  simp at this

/-! ### The Bayesian listener -/

/-- The word marginal `q(w)`. -/
noncomputable def wordMarginal (w : W) : ℝ := marginalWord 𝓜.encoder 𝓜.source w

theorem wordMarginal_pos (w : W) : 0 < 𝓜.wordMarginal w :=
  let ⟨m⟩ := 𝓜.nonempty
  marginalWord_pos_of _ _ (λ m => (𝓜.source_pos m).le) (𝓜.source_pos m) (𝓜.encoder_pos _ w)

/-- The environment marginal `p(u)`. -/
noncomputable def envMarginal (u : U) : ℝ := marginalWord 𝓜.meanings 𝓜.source u

theorem envMarginal_pos (u : U) : 0 < 𝓜.envMarginal u :=
  let ⟨m⟩ := 𝓜.nonempty
  marginalWord_pos_of _ _ (λ m => (𝓜.source_pos m).le) (𝓜.source_pos m) (𝓜.meanings_pos _ u)

/-- The joint probability of a word and a state of the environment. -/
noncomputable def joint (w : W) (u : U) : ℝ :=
  ∑ m, 𝓜.source m * 𝓜.encoder.encode m w * 𝓜.meanings.encode m u

theorem joint_pos (w : W) (u : U) : 0 < 𝓜.joint w u :=
  have := 𝓜.nonempty
  sum_pos (λ m _ => mul_pos (mul_pos (𝓜.source_pos m) (𝓜.encoder_pos m w))
    (𝓜.meanings_pos m u)) univ_nonempty

theorem sum_joint_env (w : W) : ∑ u, 𝓜.joint w u = 𝓜.wordMarginal w := by
  unfold joint wordMarginal marginalWord
  rw [sum_comm]
  simp_rw [← mul_sum, 𝓜.meanings.encode_sum_one, mul_one]

theorem sum_joint_word (u : U) : ∑ w, 𝓜.joint w u = 𝓜.envMarginal u := by
  unfold joint envMarginal marginalWord
  rw [sum_comm]
  refine sum_congr rfl λ m _ => ?_
  have : ∀ w, 𝓜.source m * 𝓜.encoder.encode m w * 𝓜.meanings.encode m u
      = 𝓜.source m * 𝓜.meanings.encode m u * 𝓜.encoder.encode m w := λ w => by ring
  simp_rw [this, ← mul_sum, 𝓜.encoder.encode_sum_one, mul_one]

/-- The listener's interpretation of `w`, the posterior mixture of meanings `m̂_w(u)`. -/
noncomputable def interpretation (w : W) (u : U) : ℝ := 𝓜.joint w u / 𝓜.wordMarginal w

theorem interpretation_pos (w : W) (u : U) : 0 < 𝓜.interpretation w u :=
  div_pos (𝓜.joint_pos w u) (𝓜.wordMarginal_pos w)

theorem wordMarginal_mul_interpretation (w : W) (u : U) :
    𝓜.wordMarginal w * 𝓜.interpretation w u = 𝓜.joint w u :=
  mul_div_cancel₀ _ (𝓜.wordMarginal_pos w).ne'

/-- The optimal Bayesian listener as a channel from words to the environment. -/
noncomputable def decoder : CommChannel W U where
  encode := 𝓜.interpretation
  encode_nonneg w u := (𝓜.interpretation_pos w u).le
  encode_sum_one w := by
    unfold interpretation
    rw [← sum_div, sum_joint_env, div_self (𝓜.wordMarginal_pos w).ne']

theorem marginalWord_decoder (u : U) :
    marginalWord 𝓜.decoder 𝓜.wordMarginal u = 𝓜.envMarginal u := by
  unfold marginalWord
  simp_rw [decoder, wordMarginal_mul_interpretation, sum_joint_word]

/-! ### Complexity, accuracy and distortion -/

/-- The complexity of the lexicon, `I_q(M;W)`. -/
noncomputable def complexity : ℝ := mutualInfo 𝓜.encoder 𝓜.source

/-- The accuracy of the lexicon, `I_q(W;U)`. -/
noncomputable def accuracy : ℝ := mutualInfo 𝓜.decoder 𝓜.wordMarginal

/-- The information the meanings carry about the environment, `I(M;U)`, independent of the
encoder. -/
noncomputable def sourceInfo : ℝ := mutualInfo 𝓜.meanings 𝓜.source

/-- The Kullback–Leibler divergence between two positive distributions on `U`. -/
noncomputable def kl (a b : U → ℝ) : ℝ := ∑ u, a u * log (a u / b u)

/-- The expected distortion between the speaker's meaning and the listener's
interpretation. -/
noncomputable def distortion : ℝ :=
  ∑ m, ∑ w, 𝓜.source m * 𝓜.encoder.encode m w * kl (𝓜.meanings.encode m) (𝓜.interpretation w)

/-- Complexity in the paper's form, with the word marginal in the denominator. -/
theorem complexity_eq :
    𝓜.complexity = ∑ m, ∑ w, 𝓜.source m * 𝓜.encoder.encode m w
      * log (𝓜.encoder.encode m w / 𝓜.wordMarginal w) := by
  unfold complexity mutualInfo
  refine sum_congr rfl λ m _ => sum_congr rfl λ w _ => ?_
  congr 2
  unfold posterior
  rw [div_div, mul_comm (marginalWord _ _ w), ← div_div, mul_div_assoc,
    div_self (𝓜.source_pos m).ne', mul_one]
  rfl

private theorem sourceInfo_eq :
    𝓜.sourceInfo = ∑ m, ∑ u, 𝓜.source m * 𝓜.meanings.encode m u
      * (log (𝓜.meanings.encode m u) - log (𝓜.envMarginal u)) := by
  unfold sourceInfo mutualInfo
  refine sum_congr rfl λ m _ => sum_congr rfl λ u _ => ?_
  congr 1
  rw [← log_div (𝓜.meanings_pos m u).ne' (𝓜.envMarginal_pos u).ne']
  congr 1
  unfold posterior envMarginal
  rw [div_div, mul_comm (marginalWord _ _ u), ← div_div, mul_div_assoc,
    div_self (𝓜.source_pos m).ne', mul_one]

private theorem accuracy_eq :
    𝓜.accuracy = ∑ w, ∑ u, 𝓜.joint w u
      * (log (𝓜.interpretation w u) - log (𝓜.envMarginal u)) := by
  unfold accuracy mutualInfo
  refine sum_congr rfl λ w _ => sum_congr rfl λ u _ => ?_
  rw [← wordMarginal_mul_interpretation]
  congr 1
  rw [← log_div (𝓜.interpretation_pos w u).ne' (𝓜.envMarginal_pos u).ne']
  congr 1
  unfold posterior
  rw [marginalWord_decoder]
  show 𝓜.interpretation w u * 𝓜.wordMarginal w / 𝓜.envMarginal u / 𝓜.wordMarginal w = _
  rw [div_div, mul_comm (𝓜.envMarginal u), ← div_div, mul_div_assoc,
    div_self (𝓜.wordMarginal_pos w).ne', mul_one]

/-- The expected distortion is the information about the environment that the lexicon loses:
`E_q[D[M ‖ M̂]] = I(M;U) − I_q(W;U)`. -/
theorem distortion_eq : 𝓜.distortion = 𝓜.sourceInfo - 𝓜.accuracy := by
  have hlog : ∀ m w u, log (𝓜.meanings.encode m u / 𝓜.interpretation w u)
      = log (𝓜.meanings.encode m u) - log (𝓜.interpretation w u) :=
    λ m w u => log_div (𝓜.meanings_pos m u).ne' (𝓜.interpretation_pos w u).ne'
  -- the three quantities, expanded
  have hA : 𝓜.sourceInfo = (∑ m, ∑ u, 𝓜.source m * 𝓜.meanings.encode m u
      * log (𝓜.meanings.encode m u)) - ∑ u, 𝓜.envMarginal u * log (𝓜.envMarginal u) := by
    rw [sourceInfo_eq]
    simp_rw [mul_sub, sum_sub_distrib]
    congr 1
    rw [sum_comm]
    simp_rw [← sum_mul]
    rfl
  have hB : 𝓜.accuracy = (∑ w, ∑ u, 𝓜.joint w u * log (𝓜.interpretation w u))
      - ∑ u, 𝓜.envMarginal u * log (𝓜.envMarginal u) := by
    rw [accuracy_eq]
    simp_rw [mul_sub, sum_sub_distrib]
    congr 1
    rw [sum_comm]
    simp_rw [← sum_mul, sum_joint_word]
  have hD : 𝓜.distortion = (∑ m, ∑ u, 𝓜.source m * 𝓜.meanings.encode m u
      * log (𝓜.meanings.encode m u)) - ∑ w, ∑ u, 𝓜.joint w u * log (𝓜.interpretation w u) := by
    unfold distortion kl
    simp_rw [hlog, mul_sub, sum_sub_distrib, mul_sub, sum_sub_distrib]
    congr 1
    · refine sum_congr rfl λ m _ => ?_
      have : ∀ w, 𝓜.source m * 𝓜.encoder.encode m w
            * ∑ u, 𝓜.meanings.encode m u * log (𝓜.meanings.encode m u)
          = 𝓜.encoder.encode m w
            * (𝓜.source m * ∑ u, 𝓜.meanings.encode m u * log (𝓜.meanings.encode m u)) :=
        λ w => by ring
      simp_rw [this, ← sum_mul, 𝓜.encoder.encode_sum_one, one_mul, mul_sum]
      exact sum_congr rfl λ u _ => by ring
    · rw [sum_comm]
      refine sum_congr rfl λ w _ => ?_
      simp_rw [mul_sum]
      rw [sum_comm]
      refine sum_congr rfl λ u _ => ?_
      unfold joint
      rw [sum_mul]
      exact sum_congr rfl λ m _ => by ring
  rw [hA, hB, hD]
  ring

/-! ### The Information Bottleneck objective -/

/-- The Information Bottleneck objective `F_β = I_q(M;W) − β I_q(W;U)`. -/
noncomputable def objective (β : ℝ) : ℝ := 𝓜.complexity - β * 𝓜.accuracy

/-- The distortion–complexity cost pair of the lexicon. -/
noncomputable def costPair : CostPair := ⟨𝓜.distortion, 𝓜.complexity⟩

/-- Up to the encoder-independent constant `β I(M;U)`, the objective is the β-scalarized cost
of distortion and complexity. -/
theorem objective_eq_weightedCost (β : ℝ) :
    𝓜.objective β = weightedCost 𝓜.costPair β - β * 𝓜.sourceInfo := by
  unfold objective weightedCost costPair
  rw [distortion_eq]
  ring

/-- The deviation `ΔF_β` of the lexicon from a reference encoder at `β`. -/
noncomputable def deviation (𝓜' : Model U M W) (β : ℝ) : ℝ := 𝓜.objective β - 𝓜'.objective β

/-- For two lexicons over the same meanings and source, the deviation is the substrate's
efficiency loss at `β`. -/
theorem deviation_eq_efficiencyLossAt (𝓜' : Model U M W) (h : 𝓜'.sourceInfo = 𝓜.sourceInfo)
    (β : ℝ) : 𝓜.deviation 𝓜' β = efficiencyLossAt 𝓜.costPair 𝓜'.costPair β := by
  unfold deviation efficiencyLossAt
  rw [objective_eq_weightedCost, objective_eq_weightedCost, h]
  ring

/-- The efficiency loss `ε_l = ΔF_{β_l} / β_l` at the fitted trade-off. -/
noncomputable def efficiencyLoss (𝓜' : Model U M W) (β : ℝ) : ℝ := 𝓜.deviation 𝓜' β / β

/-- The self-consistent form of the Information Bottleneck optima: each word's probability
decays exponentially, at rate `β`, in the divergence between the meaning and the word's
interpretation. -/
def IsIBOptimum (β : ℝ) : Prop :=
  ∀ m w, 𝓜.encoder.encode m w =
    𝓜.wordMarginal w * exp (-β * kl (𝓜.meanings.encode m) (𝓜.interpretation w))
      / ∑ w', 𝓜.wordMarginal w' * exp (-β * kl (𝓜.meanings.encode m) (𝓜.interpretation w'))

end Model

end ZaslavskyKempRegierTishby2018
