import Linglib.Core.Computability.Subregular.Basic

/-!
# Definite and Reverse-Definite Languages (D_k, RD_k)

A language `L` is **`k`-definite** when membership is determined by the last
`k` symbols of the input @cite{rogers-pullum-2011} @cite{lambert-2022}: any
two strings agreeing on their length-`k` suffix are L-equivalent. The dual
notion, **reverse `k`-definite** (RD_k), checks the length-`k` *prefix*
instead.

These are weaker than SL_k in expressive power — they look at one fixed
position (the edge) rather than every contiguous window — but they are
foundational for the right- and left-context-only fragments of finite-state
computation. Concrete linguistic uses include word-final neutralization
(D_1 / D_2: a constraint on the last few segments) and word-initial
prosodic templates (RD_k).

## Strictly definite vs definite

The classical definite/strictly-definite distinction collapses for the
generative formulation used here: a language is definite iff it is
strictly definite (the permitted-suffix set is just the suffixes of
L-members), so we use a single `DefiniteGrammar` type and elide the
"strictly" qualifier.

## No boundary augmentation

Unlike SL/LT, D and RD do not use boundary symbols: the suffix/prefix
already privileges the edge structurally, and adding `none` markers would
just shift indexing by `k - 1`. The grammar's `permitted` set is over the
raw alphabet `α`, not `Augmented α`.
-/

namespace Core.Computability.Subregular

universe u

variable {α : Type u}

-- ============================================================================
-- § 1: Definite grammars (suffix-based)
-- ============================================================================

/-- A **`k`-definite grammar** over `α`: a set of permitted length-(≤`k`)
    suffixes. A string is accepted iff its length-`k` suffix
    (`List.takeRight k`) is in the permitted set; for strings shorter than
    `k`, the whole string is its own suffix. -/
structure DefiniteGrammar (k : ℕ) (α : Type u) where
  /-- The set of permitted length-(≤`k`) suffixes. -/
  permitted : Set (List α)

namespace DefiniteGrammar

variable {k : ℕ}

/-- The length-`k` suffix of a list (the whole list if shorter than `k`).
    Computed as `xs.drop (xs.length - k)`; `Nat` truncating subtraction
    handles the short-list case correctly. -/
def lastK (k : ℕ) (xs : List α) : List α := xs.drop (xs.length - k)

/-- The language generated by a definite grammar: strings whose length-`k`
    suffix is permitted. -/
def lang (G : DefiniteGrammar k α) : Language α := fun w =>
  lastK k w ∈ G.permitted

@[simp] theorem mem_lang (G : DefiniteGrammar k α) (w : List α) :
    w ∈ G.lang ↔ lastK k w ∈ G.permitted := Iff.rfl

/-- The definite grammar permitting *all* suffixes — accepts every string. -/
def univ (k : ℕ) (α : Type u) : DefiniteGrammar k α := ⟨Set.univ⟩

@[simp] theorem lang_univ (k : ℕ) :
    (univ k α).lang = (Set.univ : Language α) := by
  funext w
  exact propext ⟨fun _ => trivial, fun _ => trivial⟩

end DefiniteGrammar

/-- A language `L` is **`k`-definite** iff some `DefiniteGrammar k α`
    generates exactly `L`. -/
def IsDefiniteK (k : ℕ) (L : Language α) : Prop :=
  ∃ G : DefiniteGrammar k α, G.lang = L

/-- Every definite grammar witnesses D_k for its language. -/
theorem DefiniteGrammar.isDefiniteK_lang {k : ℕ} (G : DefiniteGrammar k α) :
    IsDefiniteK k G.lang :=
  ⟨G, rfl⟩

-- ============================================================================
-- § 2: Reverse-definite grammars (prefix-based)
-- ============================================================================

/-- A **reverse `k`-definite grammar** over `α`: a set of permitted
    length-(≤`k`) prefixes. A string is accepted iff its length-`k` prefix
    (`List.take k`) is in the permitted set. -/
structure ReverseDefiniteGrammar (k : ℕ) (α : Type u) where
  /-- The set of permitted length-(≤`k`) prefixes. -/
  permitted : Set (List α)

namespace ReverseDefiniteGrammar

variable {k : ℕ}

/-- The language generated by a reverse-definite grammar: strings whose
    length-`k` prefix is permitted. -/
def lang (G : ReverseDefiniteGrammar k α) : Language α := fun w =>
  w.take k ∈ G.permitted

@[simp] theorem mem_lang (G : ReverseDefiniteGrammar k α) (w : List α) :
    w ∈ G.lang ↔ w.take k ∈ G.permitted := Iff.rfl

/-- The reverse-definite grammar permitting *all* prefixes — accepts every
    string. -/
def univ (k : ℕ) (α : Type u) : ReverseDefiniteGrammar k α := ⟨Set.univ⟩

@[simp] theorem lang_univ (k : ℕ) :
    (univ k α).lang = (Set.univ : Language α) := by
  funext w
  exact propext ⟨fun _ => trivial, fun _ => trivial⟩

end ReverseDefiniteGrammar

/-- A language `L` is **reverse `k`-definite** iff some
    `ReverseDefiniteGrammar k α` generates exactly `L`. -/
def IsReverseDefiniteK (k : ℕ) (L : Language α) : Prop :=
  ∃ G : ReverseDefiniteGrammar k α, G.lang = L

/-- Every reverse-definite grammar witnesses RD_k for its language. -/
theorem ReverseDefiniteGrammar.isReverseDefiniteK_lang {k : ℕ}
    (G : ReverseDefiniteGrammar k α) : IsReverseDefiniteK k G.lang :=
  ⟨G, rfl⟩

end Core.Computability.Subregular
