import Linglib.Core.Order.Branching
import Linglib.Syntax.Tree.Cat

/-!
# Command relations generated by categories

The command relations of the syntactic literature, reconstructed as generators on a
category-labelled tree: a node S-commands whatever the lowest S above it dominates
(Langacker's command), and likewise NP-command, K-command from the cyclic nodes S and NP,
MAX-command from the maximal projections, and c-command from the branching nodes. Each is
`commandRelation` on `Branching.toTreeOrder` generated by the positions carrying the
relevant categories, so the Intersection Theorem identifies K-command with
S-command ∩ NP-command, and Rouveret and Vergnaud's relation, which takes the lower of the
first branching node and the first maximal projection, with c-command ∩ MAX-command.

## References

* [barker-pullum-1990]
* [langacker-1969]
* [lasnik-1976]
* [rouveret-vergnaud-1980]
-/

namespace Syntax.Tree

open Core.Order Core.Order.Branching

variable {W : Type*} (t : Tree Cat W)

/-- The positions of `t` whose category lies in `L`. -/
def labeled (L : Set Cat) : Set TreePath :=
  {p | ∃ s, subtreeAt t p.toList = some s ∧ s.cat ∈ L}

instance (L : Set Cat) [DecidablePred (· ∈ L)] (p : TreePath) : Decidable (p ∈ labeled t L) :=
  match h : subtreeAt t p.toList with
  | none => isFalse (by rintro ⟨s, hs, _⟩; rw [h] at hs; simp at hs)
  | some s => decidable_of_iff (s.cat ∈ L)
      ⟨λ hL => ⟨s, h, hL⟩, λ ⟨_, hs, hL⟩ => by rw [h] at hs; cases hs; exact hL⟩

theorem labeled_union (L₁ L₂ : Set Cat) : labeled t (L₁ ∪ L₂) = labeled t L₁ ∪ labeled t L₂ := by
  ext p; simp only [labeled, Set.mem_union, Set.mem_ofPred_eq, and_or_left, exists_or]

/-- Langacker's command: generated by the S nodes. -/
abbrev sCommand : Set (TreePath × TreePath) := commandRelation (toTreeOrder t) (labeled t {.S})

/-- Generated by the NP nodes. -/
abbrev npCommand : Set (TreePath × TreePath) := commandRelation (toTreeOrder t) (labeled t {.NP})

/-- Lasnik's kommand: generated by the cyclic nodes, S and NP. -/
abbrev kCommand : Set (TreePath × TreePath) := commandRelation (toTreeOrder t) (labeled t {.S, .NP})

/-- Generated by the maximal projections `max`. -/
abbrev maxCommand (max : Set Cat) : Set (TreePath × TreePath) :=
  commandRelation (toTreeOrder t) (labeled t max)

/-- Rouveret and Vergnaud's c-command, generated by the branching nodes together with the
maximal projections. -/
abbrev rvCommand (max : Set Cat) : Set (TreePath × TreePath) :=
  commandRelation (toTreeOrder t) ({p | isBranchingAt t p} ∪ labeled t max)

/-- K-command is S-command ∩ NP-command. -/
theorem kCommand_eq : kCommand t = sCommand t ∩ npCommand t := by
  rw [kCommand, sCommand, npCommand, intersection_theorem, ← labeled_union, Set.singleton_union]

/-- Rouveret and Vergnaud's relation is c-command ∩ MAX-command. -/
theorem rvCommand_eq (max : Set Cat) : rvCommand t max = cCommandAt t ∩ maxCommand t max :=
  (intersection_theorem _ _ _).symm

end Syntax.Tree
