module

public import Linglib.Syntax.Command
public import Linglib.Syntax.Tree.Cat

/-!
# Command relations generated by categories

The command relations of the syntactic literature, reconstructed as generators on a
labelled tree: a node S-commands whatever the lowest S above it dominates
(Langacker's command), and likewise NP-command, K-command from the cyclic nodes S and NP,
MAX-command from the maximal projections, and c-command from the branching nodes. Each is
`commandRelation` generated by the positions carrying the
relevant categories, so the Intersection Theorem identifies K-command with
S-command ∩ NP-command, and Rouveret and Vergnaud's relation, which takes the lower of the
first branching node and the first maximal projection, with c-command ∩ MAX-command.
Reinhart's c-command, `CCommands`, is the c-command relation restricted to nodes neither of
which dominates the other.

## References

* [barker-pullum-1990]
* [langacker-1969]
* [lasnik-1976]
* [rouveret-vergnaud-1980]
* [reinhart-1976]
-/

@[expose] public section

namespace Syntax.Tree

open Core.Order Core.Order.Branching

section Labeled

variable {C W : Type*} (t : Tree C W)

/-- `labeled t L` is the set of positions of `t` whose category lies in `L`. -/
def labeled (L : Set C) : Set TreePath :=
  {p | ∃ s, subtreeAt t p.toList = some s ∧ s.cat ∈ L}

instance (L : Set C) [DecidablePred (· ∈ L)] (p : TreePath) : Decidable (p ∈ labeled t L) :=
  match h : subtreeAt t p.toList with
  | none => isFalse (by rintro ⟨s, hs, _⟩; rw [h] at hs; simp at hs)
  | some s => decidable_of_iff (s.cat ∈ L)
      ⟨fun hL ↦ ⟨s, h, hL⟩, fun ⟨_, hs, hL⟩ ↦ by rw [h] at hs; cases hs; exact hL⟩

theorem labeled_union (L₁ L₂ : Set C) : labeled t (L₁ ∪ L₂) = labeled t L₁ ∪ labeled t L₂ := by
  ext p; simp only [labeled, Set.mem_union, Set.mem_ofPred_eq, and_or_left, exists_or]

/-- MAX-command is generated by the maximal projections `max`. -/
abbrev maxCommand (max : Set C) : Set (TreePath × TreePath) :=
  commandRelation (labeled t max)

/-- Rouveret and Vergnaud's c-command is generated by the branching nodes together with the
maximal projections. -/
abbrev rvCommand (max : Set C) : Set (TreePath × TreePath) :=
  commandRelation ({p | isBranchingAt t p} ∪ labeled t max)

/-- Rouveret and Vergnaud's relation is c-command ∩ MAX-command. -/
theorem rvCommand_eq (max : Set C) : rvCommand t max = cCommandAt t ∩ maxCommand t max :=
  commandRelation_union _ _

end Labeled

section Cat

variable {W : Type*} (t : Tree Cat W)

/-- Langacker's command is generated by the S nodes. -/
abbrev sCommand : Set (TreePath × TreePath) := commandRelation (labeled t {.S})

/-- NP-command is generated by the NP nodes. -/
abbrev npCommand : Set (TreePath × TreePath) := commandRelation (labeled t {.NP})

/-- Lasnik's kommand is generated by the cyclic nodes, S and NP. -/
abbrev kCommand : Set (TreePath × TreePath) := commandRelation (labeled t {.S, .NP})

/-- K-command is S-command ∩ NP-command. -/
theorem kCommand_eq : kCommand t = sCommand t ∩ npCommand t := by
  rw [kCommand, sCommand, npCommand, ← commandRelation_union, ← labeled_union, Set.singleton_union]

end Cat

section CCommands

variable {C W : Type*} (t : Tree C W)

/-- `a` c-commands `b` in `t` when neither dominates the other and every branching node properly
dominating `a` dominates `b`. -/
def CCommands (a b : TreePath) : Prop := (a, b) ∈ cCommandAt t ∧ ¬ a ≤ b ∧ ¬ b ≤ a

instance : DecidableRel (CCommands t) := fun _ _ ↦ inferInstanceAs (Decidable (_ ∧ _ ∧ _))

end CCommands

section RoseTree

variable {C W : Type*}

/-- The c-command relation of a constituency tree is that of its rose tree. -/
theorem cCommandAt_toRoseTree (t : Tree C W) : cCommandAt t.toRoseTree = cCommandAt t :=
  cCommandAt_map_of_children_map children_toRoseTree t

end RoseTree

end Syntax.Tree
