/-
Copyright (c) 2026 Robert Hawkins. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Robert Hawkins
-/
import Linglib.Phonology.Subregular.StrictlyLocal
import Linglib.Phonology.Subregular.Aperiodicity
import Linglib.Phonology.Subregular.TierProjection
import Mathlib.Data.List.Basic
import Mathlib.Computability.Language
import Linglib.Core.Data.List.Factors

/-!
# Tier-based strictly local languages (TSL_k)

A language is **tier-based strictly `k`-local** when its membership is determined by
`SL_k` membership of its projection onto a *tier* — a decidable subalphabet `T`.
Off-tier symbols are erased before the `SL_k` test, so the constraint applies to
tier-adjacent factors while arbitrary off-tier material may intervene.

## Main definitions

* `tierProject T`: keep the symbols satisfying `T`, erase the rest. The `byClass`
  specialization of the keystone `TierProjection.apply` (`Subregular.TierProjection`).
* `TSLGrammar k α`: a decidable tier together with an `SL_k` grammar read on the
  projection.
* `IsTierStrictlyLocal k L`: `L` is generated by some `TSLGrammar k α`.

## Main results

* `Language.IsStrictlyLocal.toIsTierStrictlyLocal`: `SL_k ⊆ TSL_k`, via the
  universal tier (projection is the identity).
-/

variable {α : Type*}

namespace Subregular

variable (T : α → Prop) [DecidablePred T]

/-- **Tier projection**: keep the symbols satisfying the tier predicate `T`,
erase the rest. The single-alphabet `byClass` specialization of the keystone
erasing string homomorphism `TierProjection.apply`
(`Subregular.TierProjection`), so the autosegmental and subregular
tiers are one definition rather than two joined by a bridge. -/
def tierProject (xs : List α) : List α :=
  TierProjection.apply (TierProjection.byClass T) xs

/-- `tierProject` reduces to `List.filter` (via `TierProjection.apply_byClass`). -/
lemma tierProject_eq_filter (xs : List α) :
    tierProject T xs = xs.filter (fun x => decide (T x)) :=
  TierProjection.apply_byClass T xs

@[simp] lemma tierProject_nil : tierProject T ([] : List α) = [] := rfl

lemma tierProject_cons (x : α) (xs : List α) :
    tierProject T (x :: xs) =
      if T x then x :: tierProject T xs else tierProject T xs := by
  simp [tierProject_eq_filter, List.filter_cons]

/-- Projection by the universal tier is the identity. -/
@[simp] lemma tierProject_univ (w : List α) :
    tierProject (fun _ : α => True) w = w := by
  simp [tierProject_eq_filter]

/-- A **tier-based strictly `k`-local grammar**: a decidable tier (subset
of `α`) plus an SL grammar interpreted on the projected string. The tier
predicate is carried as an instance field via `[DecidablePred tier]` so
projection at use sites picks up the decidability automatically. -/
structure TSLGrammar (k : ℕ) (α : Type*) where
  /-- The membership predicate selecting which symbols stay on the tier.
  Symbols failing `tier` are erased before the SL test. -/
  tier : α → Prop
  /-- Decidability of `tier`, needed to define projection. -/
  [decTier : DecidablePred tier]
  /-- The `SL` grammar read on the *projected* string: its permitted factors. -/
  permitted : SLGrammar α

namespace TSLGrammar

variable {k : ℕ}

attribute [instance] TSLGrammar.decTier

/-- The language generated by a TSL grammar: the preimage, under tier
projection, of the `SL_k` language of `permitted`. -/
def lang (G : TSLGrammar k α) : Language α := tierProject G.tier ⁻¹' G.permitted.language k

@[simp] lemma mem_lang (G : TSLGrammar k α) (w : List α) :
    w ∈ G.lang ↔
      ∀ f ∈ List.kFactors k (boundary k (tierProject G.tier w)), f ∈ G.permitted := Iff.rfl

end TSLGrammar

end Subregular

namespace Language

/-- A language is **tier-based strictly `k`-local** iff some
`TSLGrammar k α` generates it. -/
def IsTierStrictlyLocal (k : ℕ) (L : Language α) : Prop :=
  ∃ G : Subregular.TSLGrammar k α, G.lang = L

/-! ## Inclusions -/

/-- **SL_k ⊆ TSL_k**: take the universal tier (every symbol on tier), so
projection is the identity and the TSL grammar's `lang` reduces to the
underlying SL grammar's `lang`. -/
theorem IsStrictlyLocal.toIsTierStrictlyLocal {k : ℕ} {L : Language α}
    (h : L.IsStrictlyLocal k) : IsTierStrictlyLocal k L := by
  obtain ⟨G, rfl⟩ := h
  exact ⟨{ tier := fun _ => True, permitted := G }, by ext w; simp⟩

/-! ### Tier erasure as a monoid hom, and star-freeness -/

end Language

namespace Subregular

variable (T : α → Prop) [DecidablePred T]

/-- **Tier erasure as a monoid hom** `FreeMonoid α →* FreeMonoid α`: the `byClass T`
specialization of the keystone bundled hom `TierProjection.applyHom`. The monoid-hom laws
are inherited from `applyHom` rather than re-proved, since `tierProject T` is by definition
`TierProjection.apply (TierProjection.byClass T)`. -/
def tierProjectHom : FreeMonoid α →* FreeMonoid α :=
  TierProjection.applyHom (TierProjection.byClass T)

@[simp] lemma tierProjectHom_apply (w : FreeMonoid α) :
    tierProjectHom T w = tierProject T w := rfl

end Subregular

namespace Language

open Subregular

variable [Finite α]

/-- **Tier-based strictly local languages are star-free** ([heinz-rawal-tanner-2011]). Over a
finite alphabet, a TSL language is the inverse image of an `SL_k` language under the
tier-erasure homomorphism, and star-freeness is closed under inverse homomorphism
(`IsStarFree.comap`), so `TSL_k ⊆ SF`. -/
theorem IsTierStrictlyLocal.isStarFree {k : ℕ} {L : Language α} (h : IsTierStrictlyLocal k L) :
    L.IsStarFree := by
  obtain ⟨G, rfl⟩ := h
  have hsf : (G.permitted.language k).IsStarFree :=
    IsStrictlyLocal.isStarFree ⟨G.permitted, rfl⟩
  have := hsf.comap (tierProjectHom G.tier)
  rwa [show {w : List α | tierProjectHom G.tier (FreeMonoid.ofList w)
      ∈ G.permitted.language k} = G.lang from rfl] at this

end Language
