import Linglib.Core.CoreConcept
import Linglib.Features.Number
import Linglib.Core.Tree
import Linglib.Theories.Semantics.Quantification.Lexicon
import Linglib.Theories.Semantics.Alternatives.Source
import Linglib.Theories.Semantics.Alternatives.Pronounceable
import Linglib.Theories.Semantics.Alternatives.Indirect
import Linglib.Theories.Semantics.Alternatives.Structural
import Linglib.Theories.Pragmatics.AvoidAmbiguity
import Linglib.Fragments.French.Determiners
import Linglib.Fragments.English.Determiners

/-!
# Jeretič et al. 2025 — Anti-duality of *tous*
@cite{jeretic-bassi-gonzalez-yatsushiro-meyer-sauerland-2025}

Cross-linguistic anti-duality of universal and other quantifiers:

> The English universal quantifiers *all* and *every* are 'anti-dual',
> i.e. cannot be used if their domain is known to contain only two
> individuals. Instead, the dual universal quantifier *both* can be
> used in those contexts […] French *tous* is also anti-dual. But
> French does not have a lexical item for 'both'.

The paper's resolution distinguishes three theoretical entities (paper
§4.3, Fig. 1):

1. The **lexicalized dual item** (English *both*, German *beide*) —
   competes with universal *all*/*alle* via standard MP
   (@cite{percus-2006}, @cite{sauerland-2008}).
2. The **unpronounceable dual structure** (*tous les NP.dual*) —
   generated by the grammar via the dual core concept and *blocked from
   pronunciation* by Avoid Ambiguity (paper eq 37).
3. The **indirect alternative** (French *les deux NP*) — a
   pronounceable surrogate equivalent in meaning to (2) and at most as
   complex (Katzir node count); its existence *licenses* (2) to count
   as MP competitor.

The `Competitor` type below faithfully tracks all three, rather than
collapsing (2) and (3) into one bin.

## Cross-linguistic predictions (paper §5)

We reproduce only the (language, quantifier) cells the paper actually
discusses. Per-cell paper-section citations are attached to each datum.
The prediction is computed via:
- `Lexicalizes lex realizes Id.dual` for `Competitor.lexicalDual`
  (paper §3, English *all* via *both*; §5.2 *no* via *neither*)
- A pronounceable expression at-most-as-complex equivalent to the
  unpronounceable dual structure for `Competitor.indirectAlternative`
  (paper §4.1 French *tous* via *les deux*; §5.4 English *always* via
  *both times*)
- `Competitor.none` if neither obtains (paper §5.2 French *aucun*,
  German *keine*; §5.4 French *toujours*)

## Connection to linglib infrastructure

- `Features.Number.dualPredOnLattice` is the predicate-modification
  denotation of DUAL (paper eq 39 / §8 eq 98b), grounded in the
  existing Harbour `dualF = ⟨−atomic, +minimal⟩` and bridged via
  `Features.Number.dualPredOnLattice_eq_via_features`.
- `Alternatives.Indirect.indirectFrom` lifts an indirect alternative
  into an `AlternativeSource`, plugging into the
  `Alternatives.Structural.violatesMP` competition operator.
- `Pragmatics.AvoidAmbiguity.Blocked` formalizes paper eq 37 as the
  blocking principle that renders `tous les NP.dual` unpronounceable.
- The paper's MP-via-indirect-alts is a refinement of the
  MP-via-direct-alts machinery already in linglib via
  `Phenomena/Plurals/Studies/Sauerland2003.lean` (sg/pl/dual phi-MP);
  Sauerland's account works for English *both* but not French *tous*,
  which is exactly the gap this paper fills.

## Theoretical alternatives the paper rejects

§6.1 considers `BOTH` as the universal core concept (rather than just
`DUAL`) and rejects it; we do not formalize this counter-proposal but
note that the choice between MP-based accounts of anti-duality
(@cite{percus-2006}, @cite{sauerland-2008}) and obligatory-implicature
accounts (@cite{magri-2009}) is real. This file commits to MP.
-/

set_option autoImplicit false

namespace Phenomena.Presupposition.Studies.JereticEtAl2025

open Core.CoreConcept
open Theories.Semantics.Quantification.Lexicon (QuantifierEntry)

-- ============================================================================
-- §1  Languages and quantifier slots
-- ============================================================================

/-- Languages discussed in the paper, plus Slovenian as the
discriminating prediction (paper §4.2.1, §5: dual morphologically
realized → no anti-duality of universal). -/
inductive Language where
  | english | french | german | japanese | icelandic | slovenian
  deriving DecidableEq, Repr

/-- Quantifier slots discussed in the paper. -/
inductive QSlot where
  /-- Universal: English *all*, French *tous*, German *alle*. -/
  | universal
  /-- Negative: English *no*, French *aucun*, German *keine*. -/
  | negative
  /-- Interrogative: English *which*, French *quel*, Japanese *dono*. -/
  | which
  /-- Distributive: English *each*, French *chaque*, Japanese *each*. -/
  | each
  /-- Existential: English *one*, French *un*, Japanese *one*. -/
  | one
  /-- Temporal universal: English *always*, French *toujours*. -/
  | always
  deriving DecidableEq, Repr

/-- Three-way classification (paper §4.3, Fig. 1):

- `lexicalDual`: a single lexical item realizes the dual core
  concept, e.g. English *both*, German *beide*, Japanese *dotti*.
  Competes via standard MP.
- `unpronounceableWithIndirectAlt`: the dual structure exists in the
  grammar but is silent (blocked by Avoid Ambiguity). A pronounceable
  surrogate at no greater complexity (the *indirect alternative*) makes
  the silent structure count as MP competitor. E.g. French *les deux*
  surrogates *tous les NP.dual*; English *both times* surrogates
  *all+ways DUAL times*; German *beide Male* surrogates *immer + DUAL*.
- `noCompetitor`: the dual structure exists but no pronounceable
  surrogate at sufficient simplicity exists, so MP does not fire.
  E.g. French *aucun* (would-be surrogates *aucun des deux* / *ni l'un
  ni l'autre* are too complex); German *keine*; French *toujours*. -/
inductive Competitor where
  | lexicalDual
  | unpronounceableWithIndirectAlt
  | noCompetitor
  deriving DecidableEq, Repr

/-- Acceptability strength reported in the paper. The Boolean
distinction "anti-dual yes/no" loses the marginality contrast between
Japanese *dono* (categorical `#`) and Icelandic *hvaða* (marginal `?`).
We track three values to preserve the paper's gradient judgment data. -/
inductive Acceptability where
  /-- `#` — categorically infelicitous in dual contexts (anti-dual). -/
  | hash
  /-- `?` — marginal/degraded in dual contexts. -/
  | question
  /-- `✓` — felicitous in dual contexts (NOT anti-dual). -/
  | ok
  deriving DecidableEq, Repr

/-- An empirical datum: a (language, quantifier-slot) cell the paper
explicitly discusses, with the paper-reported acceptability and a
human-readable section reference. -/
structure Datum where
  language : Language
  slot : QSlot
  /-- Paper-reported acceptability of the universal/negative/etc. with
  a 2-element domain. `.hash` and `.question` are anti-dual; `.ok` is
  not. -/
  observed : Acceptability
  /-- Paper section/example reference, for audit. -/
  paperRef : String
  deriving Repr

-- ============================================================================
-- §2  The paper's data table (only paper-licensed cells)
-- ============================================================================

/-- The paper's empirical claims. Every entry corresponds to an
explicit paragraph or example in Jeretič et al. 2025. Cells the paper
does not discuss are *omitted* rather than extrapolated.

Coverage: English (all 6 slots), French (all 6 slots), German
(universal/negative/always — §5.2 fn 2 and §5.4 only), Japanese
(which/each/one/always — §5.1.1, §5.1.2, §5.4 only), Icelandic
(which only — §5.1.1), Slovenian (universal — §4.2.1 ex. 36).

Total: 21 paper-licensed data points. -/
def paperData : List Datum := [
  -- English (paper §1, §3, §5.1.1, §5.1.2, §5.4)
  ⟨.english, .universal, .hash, "§1 ex. 1, §3"⟩,
  ⟨.english, .negative, .hash, "§5.2"⟩,
  ⟨.english, .which, .ok, "§5.1.1 ex. 11/64"⟩,
  ⟨.english, .each, .ok, "§5.1.2 ex. 74"⟩,
  ⟨.english, .one, .ok, "§5.1.2"⟩,
  ⟨.english, .always, .hash, "§5.4 ex. 80"⟩,
  -- French (paper §1, §4, §5.1, §5.2, §5.4)
  ⟨.french, .universal, .hash, "§1 ex. 2, §4"⟩,
  ⟨.french, .negative, .ok, "§5.2 ex. 6/76"⟩,
  ⟨.french, .which, .ok, "§5.1.1 ex. 12"⟩,
  ⟨.french, .each, .ok, "§5.1"⟩,
  ⟨.french, .one, .ok, "§5.1"⟩,
  ⟨.french, .always, .ok, "§5.4 ex. 81"⟩,
  -- German (paper §5.2, §5.4)
  ⟨.german, .universal, .hash, "§5.2 fn 2 (paralleling English)"⟩,
  ⟨.german, .negative, .ok, "§5.2 ex. 6c, ex. 77"⟩,
  ⟨.german, .always, .hash, "§5.4 ex. 83 (immer)"⟩,
  -- Japanese (paper §5.1.1, §5.1.2, §5.4)
  ⟨.japanese, .which, .hash, "§5.1.1 ex. 8 (dotti vs dono)"⟩,
  ⟨.japanese, .each, .hash, "§5.1.2 ex. 9 (dotti-mo)"⟩,
  ⟨.japanese, .one, .hash, "§5.1.2 ex. 10 (dotti-ka)"⟩,
  ⟨.japanese, .always, .question, "§5.4 fn 22 (itu-mo, weak)"⟩,
  -- Icelandic (paper §5.1.1)
  ⟨.icelandic, .which, .question, "§5.1.1 ex. 7 (hvor vs hvaða, marginal)"⟩,
  -- Slovenian (paper §4.2.1 ex. 36): morphological dual is pronounceable;
  -- prediction is *no* anti-duality of the universal because the dual
  -- structure has no Avoid-Ambiguity blocking issue.
  ⟨.slovenian, .universal, .ok, "§4.2.1 ex. 36 (predicted: dual is overt)"⟩
]

/-- Whether the paper-reported acceptability counts as anti-dual. -/
def Acceptability.isAntiDual : Acceptability → Bool
  | .hash | .question => true
  | .ok => false

-- ============================================================================
-- §3  Per-language lexicon shape (the inputs the prediction reads)
-- ============================================================================

/-- For each (language, quantifier-slot) cell, what does the language
provide for the dual reading? This is the *typological input* the
theory consumes — derived from per-language Fragment data where it
exists, hand-encoded for languages whose Fragment is not yet in
linglib. Where Fragment data is available (English, French), the
encoding here is consistent with it.

Justification per cell:
- English *all* → `.lexicalDual` because `Fragments.English.Determiners.both`
  has `numberRestriction := some .du` (see `both_neither_dual_marked`).
- English *no* → `.lexicalDual` via *neither*.
- French *tous* → `.unpronounceableWithIndirectAlt` because
  `Fragments.French.Determiners.les_deux` has `numberRestriction :=
  some .du` and is no more complex than *tous les NP*.
- French *aucun* → `.noCompetitor` because no Fragment entry has both
  `qforce = .negative` and `numberRestriction = some .du` and no
  surrogate at sufficient simplicity exists (paper §5.2).
- German *alle* → `.lexicalDual` via *beide* (Fragment not yet built).
- German *keine* → `.noCompetitor` per paper §5.2 (no German *neither*).
- German *immer* → `.unpronounceableWithIndirectAlt` per paper §5.4:
  *immer* decomposes as the suppleted *all+ways DUAL*, with *beide
  Male* as the indirect alternative (NOT a lexical dual).
- Japanese *dono* etc. → `.lexicalDual` via the *dotti* indeterminate;
  paper §5.1.1, §5.1.2 (one morpheme realizes the dual core concept
  across which/each/one slots).
- Japanese *itu-mo* → `.unpronounceableWithIndirectAlt` per paper §5.4
  fn 22: *ni-kai-tomo* ('two-times-with-foc') as the surrogate, weakly.
- Icelandic *hvaða* → `.lexicalDual` via *hvor* (paper §5.1.1).
- Slovenian *vsi* → `.noCompetitor`: dual is morphologically OVERT
  (paper §4.2.1 ex. 36 *računalnika sta pokvarjena*), so AA doesn't
  block the dual structure → it remains pronounceable as a *direct*
  alternative, not as an indirect one. The "indirect alternative"
  machinery doesn't fire because there is no unpronounceable witness.
-/
def lexiconCompetitor : Language → QSlot → Competitor
  | .english,   .universal => .lexicalDual
  | .english,   .negative  => .lexicalDual
  | .english,   .which     => .noCompetitor
  | .english,   .each      => .noCompetitor
  | .english,   .one       => .noCompetitor
  | .english,   .always    => .unpronounceableWithIndirectAlt
  | .french,    .universal => .unpronounceableWithIndirectAlt
  | .french,    .negative  => .noCompetitor
  | .french,    .which     => .noCompetitor
  | .french,    .each      => .noCompetitor
  | .french,    .one       => .noCompetitor
  | .french,    .always    => .noCompetitor
  | .german,    .universal => .lexicalDual
  | .german,    .negative  => .noCompetitor
  | .german,    .always    => .unpronounceableWithIndirectAlt
  | .japanese,  .which     => .lexicalDual
  | .japanese,  .each      => .lexicalDual
  | .japanese,  .one       => .lexicalDual
  | .japanese,  .always    => .unpronounceableWithIndirectAlt
  | .icelandic, .which     => .lexicalDual
  | .slovenian, .universal => .noCompetitor   -- dual overt; see docstring
  -- Cells the paper does not discuss return `.noCompetitor` as a
  -- safe default; they should not appear in `paperData`.
  | _, _ => .noCompetitor

/-- The theoretical prediction (paper §4–5): a quantifier is anti-dual
iff the language provides EITHER a lexical dual competitor OR an
indirect alternative for the (silent) dual structure. -/
def predictedAntiDual (lang : Language) (q : QSlot) : Bool :=
  match lexiconCompetitor lang q with
  | .lexicalDual                    => true
  | .unpronounceableWithIndirectAlt => true
  | .noCompetitor                   => false

-- ============================================================================
-- §4  Fragment-grounded derivations (English & French)
-- ============================================================================

/-! Connect `lexiconCompetitor` to the actual per-language Fragment
data where it exists. These are not stipulations about the typology
but checks: if `Fragments.English.Determiners.both` were not
`.du`-marked, the theorem would fail and the typological encoding
would be exposed as out of sync with the lexicon. -/

/-- English realizes the dual core concept iff some entry in the
lexicon carries `numberRestriction = some .du`. For English this is
witnessed by `both` and `neither`. -/
def englishRealizesDual : Prop :=
  ∃ q ∈ Fragments.English.Determiners.allQuantifiers, q.numberRestriction = some .du

theorem english_realizes_dual : englishRealizesDual :=
  ⟨Fragments.English.Determiners.both, by
    simp only [Fragments.English.Determiners.allQuantifiers, List.mem_cons]
    tauto, rfl⟩

/-- French does NOT lexicalize a *universal* dual quantifier (no
French *both*); it does have `les_deux` realizing the dual core
concept on the definite slot. This is the paper's central observation:
French has the dual concept but lacks its universal lexicalization. -/
def frenchHasDualOnDefinite : Prop :=
  Fragments.French.Determiners.les_deux.numberRestriction = some .du

theorem french_dual_on_definite : frenchHasDualOnDefinite := rfl

/-- French *tous* is plural-restricted, NOT dual — the gap the paper
explains via Indirect Alternatives. -/
theorem french_tous_not_lexical_dual :
    Fragments.French.Determiners.tous.numberRestriction ≠ some .du := by
  decide

/-- The grounding bridge: `lexiconCompetitor .english .universal =
.lexicalDual` is consistent with English having a `.du`-marked
quantifier with `qforce = .universal` (which is *both*). -/
theorem english_universal_competitor_grounded :
    lexiconCompetitor .english .universal = .lexicalDual ∧
    ∃ q ∈ Fragments.English.Determiners.allQuantifiers,
      q.qforce = .universal ∧ q.numberRestriction = some .du :=
  ⟨rfl, Fragments.English.Determiners.both, by
    simp only [Fragments.English.Determiners.allQuantifiers, List.mem_cons]
    tauto, rfl, rfl⟩

/-- The grounding bridge for French: `lexiconCompetitor .french
.universal = .unpronounceableWithIndirectAlt` is consistent with
French lacking a `.du`-marked universal AND having *les deux*
realizing dual on the definite slot (the indirect alternative). -/
theorem french_universal_competitor_grounded :
    lexiconCompetitor .french .universal = .unpronounceableWithIndirectAlt ∧
    Fragments.French.Determiners.tous.qforce = .universal ∧
    Fragments.French.Determiners.tous.numberRestriction ≠ some .du ∧
    Fragments.French.Determiners.les_deux.numberRestriction = some .du := by
  refine ⟨rfl, rfl, ?_, rfl⟩
  decide

-- ============================================================================
-- §5  Theory matches data (the central empirical claim)
-- ============================================================================

/-- For each cell the paper discusses, the prediction matches the
reported acceptability.

This is the headline result. Unlike a `data = data` theorem over two
parallel stipulated tables, here `predictedAntiDual` is computed from
`lexiconCompetitor` (typological input) and `Acceptability.isAntiDual`
extracts a Boolean from the paper's gradient judgment. The prediction
shape (lexical dual OR indirect alternative → anti-dual) is the
theory; the per-cell `lexiconCompetitor` value reads the language; the
agreement with `paperData.observed.isAntiDual` is the substantive
empirical claim. -/
theorem theory_matches_data :
    paperData.all (fun d =>
      predictedAntiDual d.language d.slot == d.observed.isAntiDual) = true := by
  decide

/-- The English/French headline contrast (paper §1, §4): both languages
predict anti-duality of the universal, by different routes. -/
example :
    predictedAntiDual .english .universal = true ∧
    predictedAntiDual .french .universal = true := by
  refine ⟨rfl, rfl⟩

/-- The German *keine* / French *aucun* asymmetry (paper §5.2):
neither language has anti-duality on negatives despite German having
lexical *beide*. -/
example :
    predictedAntiDual .french .negative = false ∧
    predictedAntiDual .german .negative = false := by
  refine ⟨rfl, rfl⟩

/-- The *always*/*toujours* contrast (paper §5.4): English anti-dual,
French not. -/
example :
    predictedAntiDual .english .always = true ∧
    predictedAntiDual .french .always = false := by
  refine ⟨rfl, rfl⟩

/-- **Discriminating prediction** for Slovenian (paper §4.2.1 ex. 36):
because Slovenian morphologically realizes the dual, the
unpronounceable structure of the analysis becomes pronounceable, no
indirect-alternative competition is needed, and the universal is NOT
anti-dual. This is the empirical leverage of the Indirect Alternative
account: it explains why dual-marking languages do not show
anti-duality of the universal in the way French/English do. -/
theorem slovenian_universal_not_anti_dual :
    predictedAntiDual .slovenian .universal = false := rfl

-- ============================================================================
-- §6  Connection to MP-via-direct-alts (Sauerland 2003)
-- ============================================================================

/-! ### Bridge to `Phenomena/Plurals/Studies/Sauerland2003.lean`

@cite{sauerland-2003} formalizes MP competition over phi-features
(sg/pl/dual) via direct alternatives — the standard
@cite{percus-2006}, @cite{sauerland-2008} mechanism. That account
correctly predicts:
- English *all* anti-dual via direct competition with *both*
  (lexicalized phi-feature alternative).

It cannot predict:
- French *tous* anti-dual (no direct alternative — no French *both*).
- English *always* anti-dual (no direct alternative — *both times* is
  not a phi-feature alternative to *always* but a phrasal one).

This paper extends the account by introducing *indirect* alternatives:
when the direct phi-feature alternative is unpronounceable, a
phrasal surrogate at no greater complexity counts as competitor. The
two accounts agree on `lexicalDual` cases and diverge on
`unpronounceableWithIndirectAlt` cases — Sauerland 2003 predicts no
anti-duality where Jeretič et al. 2025 predict anti-duality. The
empirical evidence (French *tous*, English *always*) favors the
extended account.
-/

/-- Cells where Sauerland 2003's direct-alts MP and Jeretič et al.
2025's indirect-alts MP make the same prediction (lexical dual). -/
def directAltAgrees : Language → QSlot → Bool
  | lang, q =>
    match lexiconCompetitor lang q with
    | .lexicalDual => true
    | _ => false

/-- The cells where the two accounts diverge — exactly the
`unpronounceableWithIndirectAlt` cells. -/
def directAltDiverges : Language → QSlot → Bool
  | lang, q =>
    match lexiconCompetitor lang q with
    | .unpronounceableWithIndirectAlt => true
    | _ => false

/-- Divergence is non-empty: there are paper-cited cells where the
two accounts make different predictions. This is the empirical content
of the paper's contribution over Sauerland 2003. -/
theorem accounts_diverge :
    directAltDiverges .french .universal = true ∧
    directAltDiverges .english .always = true := by
  refine ⟨rfl, rfl⟩

-- ============================================================================
-- §7  Worked end-to-end example
-- ============================================================================

/-! ### A worked end-to-end example: French *tous les verres*

The typological table above asserts that French *tous* is anti-dual via
an indirect alternative. This section *exercises* the typeclass
infrastructure end-to-end on a minimal sentence pair, demonstrating
that `AlternativeSource` / `Pronounceability` / `indirectFrom` /
`Alternatives.Structural.violatesMP` compose correctly: each component
plugs into the next and the final `violatesMP` predicate fires on real
parse trees.

We use a deliberately shallow tree structure — a single NP with two
Det-substitutable terminals — so the proofs go through by `decide` and
a single Katzir substitution step. The sentence pair is paper §4.1
ex. 25 (*tous les verres sont pleins* / *les deux verres sont pleins*),
collapsed to its essential head structure: *tous V* / *les_deux V*,
with the silent witness *tous_DUAL V*.
-/

section WorkedExample

open Core.Tree
open Alternatives Alternatives.Structural

/-- Two domains: a 2-cup world (`w2`) and a 3-cup world (`w3`).
The dual presupposition is satisfied only in `w2`. -/
inductive WorldEx | w2 | w3
  deriving DecidableEq, Repr

/-- Lexicon entry: the universal *tous*. -/
private def tousLex     : Tree Cat String := .terminal .Det "tous"
/-- Lexicon entry: the silent realization of `tous` carrying the dual
core concept (paper §4.2.1). Same syntactic category (Det) so it is
Katzir-substitutable for `tousLex`. -/
private def tousDualLex : Tree Cat String := .terminal .Det "tous_DUAL"
/-- Lexicon entry: the indirect alternative *les deux*, treated here
as a portmanteau Det for minimality. -/
private def lesDeuxLex  : Tree Cat String := .terminal .Det "les_deux"
/-- Lexicon entry: the common noun *verres*. -/
private def verresLex   : Tree Cat String := .terminal .N "verres"

/-- The French lexicon for the worked example. -/
private def frenchLex : List (Tree Cat String) :=
  [tousLex, tousDualLex, lesDeuxLex, verresLex]

/-- *tous V*: the surface universal. Three nodes (NP + two terminals). -/
private def tousVerres     : Tree Cat String := .node .NP [tousLex, verresLex]
/-- *tous_DUAL V*: the silent witness — same structure as `tousVerres`
but with the dual-bearing Det. Identical size; differs by a single
Katzir substitution at the Det position. -/
private def tousDualVerres : Tree Cat String := .node .NP [tousDualLex, verresLex]
/-- *les deux V*: the indirect alternative. Same size as `tousVerres`. -/
private def lesDeuxVerres  : Tree Cat String := .node .NP [lesDeuxLex, verresLex]

/-- Whether a tree contains the silent dual marker as a terminal. -/
private def hasDualMarker (t : Tree Cat String) : Bool :=
  t.subtrees.any fun s => match s with
    | .terminal _ "tous_DUAL" => true
    | _ => false

/-- Whether a tree contains *les_deux* as a terminal. -/
private def hasLesDeux (t : Tree Cat String) : Bool :=
  t.subtrees.any fun s => match s with
    | .terminal _ "les_deux" => true
    | _ => false

/-- French pronounceability: trees containing `tous_DUAL` are silent. -/
private def frenchPron : Pronounceability (Tree Cat String) :=
  ⟨fun t => hasDualMarker t = false⟩

/-- Toy semantics. *tous V* asserts "all cups full" with trivial
presupposition. The dual variants (silent or *les deux*) additionally
presuppose exactly two cups, so they are defined only in `w2`. The
asserted content is uniformly `true` in our model — what differs is
the strength of the presupposition. -/
private def meaning (t : Tree Cat String) (w : WorldEx) : Bool :=
  if hasDualMarker t || hasLesDeux t then
    match w with | .w2 => true | .w3 => false
  else
    true

/-- Presupposition function: same as `meaning` in this toy model
(the "definedness" of the sentence). -/
private def presupFn : Tree Cat String → WorldEx → Bool := meaning

/-- At-issue assertion: "all cups are full". Uniform across the three
sentences in this toy model — they share at-issue content and differ
only in presupposition (the precondition for MP to apply). -/
private def assertionFn : Tree Cat String → WorldEx → Bool :=
  fun _ _ => true

/-- The French indirect-alternative source: Katzir alternatives
filtered by pronounceability and meaning equivalence. This is the
cross-application of all the new infrastructure: `katzirSource frenchLex`
provides the base structural alternatives, `frenchPron` flags silent
witnesses, `meaning` checks semantic equivalence to the witness,
`Tree.size` measures complexity. -/
private def frenchIndirectSrc : AlternativeSource (Tree Cat String) :=
  Indirect.indirectFrom (katzirSource frenchLex) frenchPron meaning Tree.size

/-- *tous_DUAL V* is a Katzir alternative of *tous V* via the
substitution Det → Det (replacing `tousLex` with `tousDualLex`). -/
private theorem tousDual_katzir_alt :
    tousDualVerres ∈ katzirSource frenchLex tousVerres := by
  apply Relation.ReflTransGen.single
  refine StructOp.inChild (cs := [tousLex, verresLex]) ⟨0, by decide⟩
    (StructOp.subst (φ := tousLex) (ψ := tousDualLex) rfl ?_)
  -- tousDualLex ∈ substitutionSource frenchLex tousVerres
  show tousDualLex ∈ frenchLex ++ tousVerres.subtrees
  refine List.mem_append_left _ (List.mem_cons_of_mem _ ?_)
  exact List.mem_cons_self

/-- *les deux V* is in the French indirect-alternative source for
*tous V*, witnessed by the silent *tous_DUAL V*. -/
private theorem lesDeux_indirectAlt_tous :
    lesDeuxVerres ∈ frenchIndirectSrc tousVerres := by
  refine ⟨?_, tousDualVerres, tousDual_katzir_alt, ?_, ?_⟩
  · -- size lesDeuxVerres ≤ size tousVerres (both are 3)
    decide
  · -- frenchPron.unpron tousDualVerres
    show ¬ (hasDualMarker tousDualVerres = false)
    decide
  · -- meaning lesDeuxVerres = meaning tousDualVerres
    funext w
    cases w <;> rfl

/-- **Headline theorem of §7**: *tous V* violates Maximize Presupposition
via competition with the indirect alternative *les deux V*, which is
licensed by the silent witness *tous_DUAL V*.

This is the end-to-end demonstration that the
`AlternativeSource` / `Pronounceability` / `indirectFrom` /
`Alternatives.Structural.violatesMP` infrastructure is wired
correctly: the abstract pragmatic-competition operator fires on a
real tree-based example with a real silent witness via a real indirect
alternative, deriving the paper's anti-duality of *tous* (paper §4.1
ex. 25, paper Fig. 1). -/
theorem tous_violatesMP_via_indirect :
    violatesMP frenchIndirectSrc presupFn assertionFn
               tousVerres (fun _ => true) := by
  refine ⟨lesDeuxVerres, lesDeux_indirectAlt_tous, ?_, ?_, ?_, rfl⟩
  · -- ∀ w, assertionFn lesDeuxVerres w = assertionFn tousVerres w
    intro _; rfl
  · -- ∀ w, presupFn lesDeuxVerres w → presupFn tousVerres w
    intro w _
    cases w <;> rfl
  · -- ∃ w, presupFn tousVerres w ∧ presupFn lesDeuxVerres w = false
    exact ⟨WorldEx.w3, rfl, rfl⟩

end WorkedExample

end Phenomena.Presupposition.Studies.JereticEtAl2025
