import Linglib.Core.Data.RoseTree.Basic
import Linglib.Core.Data.Multiset.Rel
import Mathlib.Data.List.Perm.Basic
import Mathlib.Data.List.Forall2
import Mathlib.Logic.Relation
import Mathlib.Algebra.BigOperators.Group.Multiset.Defs
import Mathlib.Algebra.Group.Nat.Defs
import Mathlib.Data.Multiset.Basic
import Mathlib.Data.Multiset.MapFold

set_option autoImplicit false

/-!
# Nonplanar n-ary rooted trees as a quotient of `RoseTree α`
[marcolli-chomsky-berwick-2025] [foissy-introduction-hopf-algebras-trees]

A **nonplanar rooted tree** is a `RoseTree α` modulo the equivalence
relation generated by:
- swapping two adjacent children of any vertex
- replacing a child with a nonplanar-equivalent tree (recursive step)

The quotient `Nonplanar α := Quotient RoseTree.instSetoid` gives the carrier MCB §1.1.2 +
§1.10 actually wants for syntactic objects: trees with unordered
children at each node.

## Strategy

Define a primitive `PermStep` relation that captures a single elementary
move (a swap or a recursive substitution), then take the equivalence
closure via `Relation.EqvGen`. This way:

- The equivalence relation IS automatically an equivalence (via the
  reflexive/symmetric/transitive constructors of `EqvGen`).
- Proving things about it reduces to handling the elementary `PermStep`
  cases plus the equivalence-closure constructors.

## Foissy connection

With `Nonplanar α` as carrier, `B+_a : Multiset (Nonplanar α) → Nonplanar α`
becomes well-defined: graft the multiset of children under a new root
labeled `a`. (For `RoseTree α` with multiset forests, B+ wasn't well-defined
because the resulting tree's child-list ordering depended on choice of
multiset representative.) This unblocks Foissy's clean cocycle proof of
Δ^p coassoc on the nonplanar Hopf algebra (Phase A.7).

## MCB anchor

[marcolli-chomsky-berwick-2025] §1.1.3 (book p. 20) — explicit
caveat: `{α, {β, γ}} = α △ β γ = α △ γ β = γ β △ α`. This file's
`Nonplanar α` realizes that unordered-children semantics for general
arity.

## Status

`[UPSTREAM]` candidate. No sorries.
-/

namespace RoseTree

variable {α : Type*}

/-! ### PermStep — elementary moves

A `PermStep t s` says: `s` is obtained from `t` by either:
- swapping two adjacent children of some vertex, or
- replacing a single child with a tree related by `PermStep` (recursion). -/

/-- A single-step child-permutation move on a rooted tree. -/
inductive PermStep : RoseTree α → RoseTree α → Prop where
  /-- Swap two adjacent children at the root vertex. -/
  | swapAtRoot {a : α} {l r : RoseTree α} {pre post : List (RoseTree α)} :
      PermStep (.node a (pre ++ l :: r :: post)) (.node a (pre ++ r :: l :: post))
  /-- Apply a step inside a child subtree, leaving siblings unchanged. -/
  | recurse {a : α} {pre : List (RoseTree α)} {old new : RoseTree α}
            {post : List (RoseTree α)} (h : PermStep old new) :
      PermStep (.node a (pre ++ old :: post)) (.node a (pre ++ new :: post))

/-! ### PermEquiv — equivalence closure

The nonplanar-equivalence relation on trees: the equivalence
closure of `PermStep`. Built using `Relation.EqvGen`, so it's
automatically reflexive / symmetric / transitive. -/

/-- Nonplanar equivalence on trees: equivalence closure of `PermStep`. -/
def PermEquiv : RoseTree α → RoseTree α → Prop := Relation.EqvGen PermStep

namespace PermEquiv

@[refl] theorem refl (t : RoseTree α) : PermEquiv t t :=
  Relation.EqvGen.refl t

@[symm] theorem symm {t s : RoseTree α} (h : PermEquiv t s) : PermEquiv s t :=
  Relation.EqvGen.symm _ _ h

theorem trans {t s u : RoseTree α} (h₁ : PermEquiv t s) (h₂ : PermEquiv s u) :
    PermEquiv t u :=
  Relation.EqvGen.trans _ _ _ h₁ h₂

theorem of_step {t s : RoseTree α} (h : PermStep t s) : PermEquiv t s :=
  Relation.EqvGen.rel _ _ h

theorem isEquivalence : Equivalence (PermEquiv : RoseTree α → RoseTree α → Prop) :=
  Relation.EqvGen.is_equivalence _

/-- Extend an `Eq`-valued invariant from single steps to the equivalence closure:
    a function unchanged by every `PermStep` is unchanged by `PermEquiv`. -/
theorem lift_eq {β : Sort*} {f : RoseTree α → β}
    (hf : ∀ t s : RoseTree α, PermStep t s → f t = f s)
    {t s : RoseTree α} (h : PermEquiv t s) : f t = f s :=
  congrArg (Quot.lift f hf) (Quot.eqvGen_sound h)

end PermEquiv

/-! ### Lifting structural invariants from `RoseTree` to `Nonplanar`

Functions `RoseTree α → β` that are invariant under `PermStep` lift
through the equivalence closure to functions `Nonplanar α → β`. Below
we lift `numNodes` (vertex count) and the other counts as worked examples.

The pattern: prove invariance under the elementary `PermStep`, then
extend to `PermEquiv` with `PermEquiv.lift_eq`. On `RoseTree` the
counts sum/`foldr`-max directly over `cs.map …`, so permutation
invariance is just `List.Perm.sum_eq` / `List.Perm.foldr_eq` on the
child list. -/

/-! #### Node count invariance -/

/-- `numNodes` is invariant under `PermStep`: a root swap permutes the
    children list (`List.Perm.sum_eq`); a recursive step rewrites one
    child by an equal-count subtree. -/
private theorem numNodes_permStep {t s : RoseTree α} (h : PermStep t s) :
    t.numNodes = s.numNodes := by
  induction h with
  | @swapAtRoot a l r pre post =>
    simp only [numNodes_node]
    congr 1
    exact (((List.Perm.swap r l post).append_left pre).map numNodes).sum_eq
  | @recurse a pre old new post _ ih =>
    simp only [numNodes_node, List.map_append, List.map_cons, List.sum_append,
      List.sum_cons, ih]

/-- `numNodes` is invariant under `PermEquiv`. -/
theorem numNodes_permEquiv {t s : RoseTree α} (h : PermEquiv t s) :
    t.numNodes = s.numNodes :=
  PermEquiv.lift_eq (fun _ _ h' => numNodes_permStep h') h

/-! #### Leaf-count invariance -/

/-- `numLeaves` is invariant under `PermStep`. -/
private theorem numLeaves_permStep {t s : RoseTree α} (h : PermStep t s) :
    t.numLeaves = s.numLeaves := by
  induction h with
  | @swapAtRoot a l r pre post =>
    simp only [numLeaves_node]
    congr 1
    exact (((List.Perm.swap r l post).append_left pre).map numLeaves).sum_eq
  | @recurse a pre old new post _ ih =>
    simp only [numLeaves_node, List.map_append, List.map_cons, List.sum_append,
      List.sum_cons, ih]

/-- `numLeaves` is invariant under `PermEquiv`. -/
theorem numLeaves_permEquiv {t s : RoseTree α} (h : PermEquiv t s) :
    t.numLeaves = s.numLeaves :=
  PermEquiv.lift_eq (fun _ _ h' => numLeaves_permStep h') h

/-! #### Value invariance -/

/-- The root value is preserved by every `PermStep`. -/
private theorem permStep_value_eq {t s : RoseTree α} (h : PermStep t s) :
    t.value = s.value := by
  cases h with
  | swapAtRoot => rfl
  | recurse _ => rfl

/-- The root value is preserved by `PermEquiv`. -/
theorem value_permEquiv {t s : RoseTree α} (h : PermEquiv t s) :
    t.value = s.value :=
  PermEquiv.lift_eq (fun _ _ h' => permStep_value_eq h') h

/-! #### Lifting child-list operations to `PermEquiv`

The smart constructor `Nonplanar.node` needs to know that the
parent-node equivalence respects the natural list-of-children
operations: cons (sibling-prepend), permutation, and componentwise
equivalence. -/

/-- Lift a `PermEquiv` from a child to the parent that has identical
    pre- and post-siblings (a chain of `recurse` moves). -/
theorem permEquiv_recurse_lift {a : α} (pre post : List (RoseTree α))
    {old new : RoseTree α} (h : PermEquiv old new) :
    PermEquiv (.node a (pre ++ old :: post))
              (.node a (pre ++ new :: post)) := by
  induction h with
  | rel _ _ hstep => exact PermEquiv.of_step (.recurse hstep)
  | refl _ => exact PermEquiv.refl _
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih1 ih2 => exact ih1.trans ih2

/-- Lift a single root-children `PermStep` under a sibling-cons head. -/
private theorem permStep_cons_lift (x : RoseTree α) {a : α}
    {cs ds : List (RoseTree α)}
    (h : PermStep (.node a cs) (.node a ds)) :
    PermStep (.node a (x :: cs)) (.node a (x :: ds)) := by
  cases h with
  | @swapAtRoot _ l r pre post =>
    show PermStep (.node a ((x :: pre) ++ l :: r :: post))
                  (.node a ((x :: pre) ++ r :: l :: post))
    exact .swapAtRoot
  | @recurse _ pre old new post hstep =>
    show PermStep (.node a ((x :: pre) ++ old :: post))
                  (.node a ((x :: pre) ++ new :: post))
    exact .recurse hstep

/-- Auxiliary form of `permEquiv_cons_lift` over arbitrary `t s`. The
    `trans` case needs `EqvGen` intermediates to be characterized as
    `.node a _`, which we obtain via `value_permEquiv` on the
    sub-chains. -/
private theorem permEquiv_cons_lift_aux
    {t s : RoseTree α} (h : PermEquiv t s) :
    ∀ {a : α} {cs ds : List (RoseTree α)} (x : RoseTree α),
      t = .node a cs → s = .node a ds →
      PermEquiv (.node a (x :: cs)) (.node a (x :: ds)) := by
  induction h with
  | rel u v hstep =>
    intro a cs ds x hu hv
    subst hu; subst hv
    exact PermEquiv.of_step (permStep_cons_lift x hstep)
  | refl u =>
    intro a cs ds x hu hv
    subst hu
    cases hv
    exact PermEquiv.refl _
  | symm u v _ ih =>
    intro a cs ds x hu hv
    exact (ih x hv hu).symm
  | trans u v w h1 _ ih1 ih2 =>
    intro a cs ds x hu hw
    subst hu; subst hw
    have hvval : v.value = a := by
      have hval := value_permEquiv h1
      simp at hval
      exact hval.symm
    have hvform : v = .node a v.children := by
      cases v with
      | node b vs =>
        simp only [RoseTree.value_node] at hvval
        rw [hvval]
        rfl
    exact (ih1 x rfl hvform).trans (ih2 x hvform rfl)

/-- A `PermEquiv` between root nodes lifts under a sibling-cons. -/
theorem permEquiv_cons_lift (x : RoseTree α) {a : α}
    {cs ds : List (RoseTree α)}
    (h : PermEquiv (.node a cs) (.node a ds)) :
    PermEquiv (.node a (x :: cs)) (.node a (x :: ds)) :=
  permEquiv_cons_lift_aux h x rfl rfl

/-- A `List.Perm` at root level lifts to `PermEquiv` on the node. -/
theorem permEquiv_root_perm {a : α} {cs ds : List (RoseTree α)}
    (h : cs.Perm ds) :
    PermEquiv (.node a cs) (.node a ds) := by
  induction h with
  | nil => exact PermEquiv.refl _
  | cons x _ ih => exact permEquiv_cons_lift x ih
  | swap x y l =>
    apply PermEquiv.of_step
    show PermStep (.node a ([] ++ y :: x :: l))
                  (.node a ([] ++ x :: y :: l))
    exact .swapAtRoot
  | trans _ _ ih1 ih2 => exact ih1.trans ih2

/-- A componentwise `PermEquiv` on root children lifts to `PermEquiv`
    on the node. -/
theorem permEquiv_node_componentwise {a : α} {cs ds : List (RoseTree α)}
    (h : List.Forall₂ PermEquiv cs ds) :
    PermEquiv (.node a cs) (.node a ds) := by
  induction h with
  | nil => exact PermEquiv.refl _
  | @cons c d cs' ds' hcd _ ih =>
    have step1 : PermEquiv (.node a (c :: cs')) (.node a (d :: cs')) :=
      permEquiv_recurse_lift [] cs' hcd
    have step2 : PermEquiv (.node a (d :: cs')) (.node a (d :: ds')) :=
      permEquiv_cons_lift d ih
    exact step1.trans step2

/-! #### Arity / depth / isLeaf invariance

Three more invariants of tree structure that are preserved by
`PermEquiv`. The pattern follows `numNodes`: prove `*_permStep`
by case on the step constructor, then lift to `*_permEquiv` via
`PermEquiv.lift_eq`. -/

/-- Arity (root child count) is invariant under `PermStep`: both
    `swapAtRoot` and `recurse` keep the children list's length fixed. -/
private theorem arity_permStep {t s : RoseTree α} (h : PermStep t s) :
    t.arity = s.arity := by
  cases h <;> simp [arity]

/-- Arity is invariant under `PermEquiv`. -/
theorem arity_permEquiv {t s : RoseTree α} (h : PermEquiv t s) :
    t.arity = s.arity :=
  PermEquiv.lift_eq (fun _ _ h' => arity_permStep h') h

/-- Depth is invariant under `PermStep`. The `swapAtRoot` case uses
    `List.Perm.foldr_eq` (`max` is left-commutative); the `recurse` case
    rewrites one child by an equal-depth subtree. -/
private theorem depth_permStep {t s : RoseTree α} (h : PermStep t s) :
    t.depth = s.depth := by
  induction h with
  | @swapAtRoot a l r pre post =>
    simp only [depth_node]
    congr 1
    exact (((List.Perm.swap r l post).append_left pre).map depth).foldr_eq 0
  | @recurse a pre old new post _ ih =>
    simp only [depth_node, List.map_append, List.map_cons, ih]

/-- Depth is invariant under `PermEquiv`. -/
theorem depth_permEquiv {t s : RoseTree α} (h : PermEquiv t s) :
    t.depth = s.depth :=
  PermEquiv.lift_eq (fun _ _ h' => depth_permStep h') h

/-- Leaf-ness is invariant under `PermStep`. Both `swapAtRoot` and
    `recurse` keep a non-empty children list on both sides, so both are
    non-leaves. -/
private theorem isLeaf_permStep {t s : RoseTree α} (h : PermStep t s) :
    t.isLeaf = s.isLeaf := by
  cases h with
  | @swapAtRoot a l r pre post => cases pre <;> rfl
  | @recurse a pre old new post _ => cases pre <;> rfl

/-- Leaf-ness is invariant under `PermEquiv`. -/
theorem isLeaf_permEquiv {t s : RoseTree α} (h : PermEquiv t s) :
    t.isLeaf = s.isLeaf :=
  PermEquiv.lift_eq (fun _ _ h' => isLeaf_permStep h') h

/-! ### Setoid instance -/

/-- The setoid on `RoseTree α` whose quotient is `Nonplanar α`. -/
instance instSetoid : Setoid (RoseTree α) where
  r := PermEquiv
  iseqv := PermEquiv.isEquivalence

end RoseTree

/-! ## Nonplanar — the quotient type -/

namespace RootedTree

/-- A nonplanar n-ary rooted tree with α-labeled vertices: the quotient
    of `RoseTree α` by `PermEquiv`. -/
def Nonplanar (α : Type*) : Type _ := Quotient (RoseTree.instSetoid : Setoid (RoseTree α))

namespace Nonplanar

variable {α : Type*}

/-- The canonical projection from ordered to nonplanar trees. -/
def mk (t : RoseTree α) : Nonplanar α := Quotient.mk _ t

/-- Two trees give the same nonplanar tree iff they're `PermEquiv`. -/
theorem mk_eq_mk_iff {t s : RoseTree α} : mk t = mk s ↔ RoseTree.PermEquiv t s :=
  Quotient.eq

@[simp] theorem mk_step {t s : RoseTree α} (h : RoseTree.PermStep t s) : mk t = mk s :=
  mk_eq_mk_iff.mpr (RoseTree.PermEquiv.of_step h)

/-- Lift a function `RoseTree α → β` that's invariant under `PermEquiv`
    to `Nonplanar α → β`. -/
def lift {β : Sort*} (f : RoseTree α → β)
    (h : ∀ t s, RoseTree.PermEquiv t s → f t = f s) : Nonplanar α → β :=
  Quotient.lift f h

@[simp] theorem lift_mk {β : Sort*} (f : RoseTree α → β)
    (h : ∀ t s, RoseTree.PermEquiv t s → f t = f s) (t : RoseTree α) :
    lift f h (mk t) = f t := rfl

/-! ### Smart leaf constructor + lifted counts

A leaf in `Nonplanar α` is `mk (RoseTree.leaf a)`. `numNodes` is the
canonical first lifted invariant. -/

/-- A nonplanar leaf labeled `a`. -/
def leaf (a : α) : Nonplanar α := mk (RoseTree.leaf a)

@[simp] theorem leaf_def (a : α) : (leaf a : Nonplanar α) = mk (RoseTree.leaf a) := rfl

/-- The **node count** (number of vertices) of a nonplanar tree, lifted
    from `RoseTree.numNodes` via `PermEquiv`-invariance. -/
def numNodes : Nonplanar α → Nat :=
  Nonplanar.lift RoseTree.numNodes (fun _ _ h => RoseTree.numNodes_permEquiv h)

@[simp] theorem numNodes_mk (t : RoseTree α) : (mk t).numNodes = t.numNodes := rfl

@[simp] theorem numNodes_leaf (a : α) : (leaf a : Nonplanar α).numNodes = 1 := by
  simp [RoseTree.leaf]

/-- The **leaf count** (number of childless vertices) of a nonplanar tree,
    lifted from `RoseTree.numLeaves` via `PermEquiv`-invariance. MCB's
    complexity grading `#L` (Def. 1.6.2) is built on this. -/
def numLeaves : Nonplanar α → Nat :=
  Nonplanar.lift RoseTree.numLeaves (fun _ _ h => RoseTree.numLeaves_permEquiv h)

@[simp] theorem numLeaves_mk (t : RoseTree α) : (mk t).numLeaves = t.numLeaves := rfl

@[simp] theorem numLeaves_leaf (a : α) : (leaf a : Nonplanar α).numLeaves = 1 := by
  simp

/-- The **arity** (root child count) of a nonplanar tree. -/
def arity : Nonplanar α → Nat :=
  Nonplanar.lift RoseTree.arity (fun _ _ h => RoseTree.arity_permEquiv h)

@[simp] theorem arity_mk (t : RoseTree α) : (mk t).arity = t.arity := rfl

@[simp] theorem arity_leaf (a : α) : (leaf a : Nonplanar α).arity = 0 := rfl

/-- The **depth** (longest root-to-leaf path in vertices) of a nonplanar tree. -/
def depth : Nonplanar α → Nat :=
  Nonplanar.lift RoseTree.depth (fun _ _ h => RoseTree.depth_permEquiv h)

@[simp] theorem depth_mk (t : RoseTree α) : (mk t).depth = t.depth := rfl

@[simp] theorem depth_leaf (a : α) : (leaf a : Nonplanar α).depth = 1 := by
  simp [RoseTree.leaf]

/-- A nonplanar tree is a **leaf** if its root has no children. (Audit
    item: queue migrate to `Prop` + `[DecidablePred]` once the matching
    `RoseTree.isLeaf` is migrated.) -/
def isLeaf : Nonplanar α → Bool :=
  Nonplanar.lift RoseTree.isLeaf (fun _ _ h => RoseTree.isLeaf_permEquiv h)

@[simp] theorem isLeaf_mk (t : RoseTree α) : (mk t).isLeaf = t.isLeaf := rfl

@[simp] theorem isLeaf_leaf (a : α) : (leaf a : Nonplanar α).isLeaf = true := rfl

/-! ### Destructors and node injectivity

The root value and the children (as a multiset of nonplanar trees) are
`PermEquiv`-invariant, so they descend to `Nonplanar`. `congrArg` on these destructors
inverts `mk`-equality at a node with no induction, giving the injectivity
characterization `mk_node_eq_mk_node_iff`. -/

/-- The root value of a nonplanar tree. -/
def value : Nonplanar α → α :=
  Nonplanar.lift RoseTree.value (fun _ _ h => RoseTree.value_permEquiv h)

@[simp] theorem value_mk (t : RoseTree α) : (mk t).value = t.value := rfl

private theorem childrenMk_permStep {t s : RoseTree α} (h : RoseTree.PermStep t s) :
    (↑(t.children.map mk) : Multiset (Nonplanar α)) = ↑(s.children.map mk) := by
  cases h with
  | @swapAtRoot a l r pre post =>
    exact Multiset.coe_eq_coe.mpr (((List.Perm.swap r l post).append_left pre).map mk)
  | @recurse a pre old new post h =>
    simp [RoseTree.children, mk_step h]

private theorem childrenMk_permEquiv {t s : RoseTree α} (h : RoseTree.PermEquiv t s) :
    (↑(t.children.map mk) : Multiset (Nonplanar α)) = ↑(s.children.map mk) :=
  RoseTree.PermEquiv.lift_eq (fun _ _ h' => childrenMk_permStep h') h

/-- The children of a nonplanar tree, as a multiset of nonplanar trees. -/
def children : Nonplanar α → Multiset (Nonplanar α) :=
  Nonplanar.lift (fun t => ↑(t.children.map mk)) (fun _ _ h => childrenMk_permEquiv h)

@[simp] theorem children_mk (t : RoseTree α) :
    (mk t).children = ↑(t.children.map mk) := rfl

/-- Injectivity of the node constructor on the quotient: `mk`-images of two nodes are
    equal iff the root values agree and the children agree as multisets of nonplanar
    trees. The forward direction is `congrArg` on the `value` and `children`
    destructors; the backward direction assembles a `PermEquiv` componentwise. -/
theorem mk_node_eq_mk_node_iff {a b : α} {cs ds : List (RoseTree α)} :
    mk (.node a cs) = mk (.node b ds) ↔
      a = b ∧ (↑(cs.map mk) : Multiset (Nonplanar α)) = ↑(ds.map mk) := by
  constructor
  · intro h
    exact ⟨by simpa [RoseTree.value] using congrArg value h,
           by simpa [RoseTree.children] using congrArg children h⟩
  · rintro ⟨rfl, hc⟩
    rw [← Multiset.map_coe, ← Multiset.map_coe, ← Multiset.rel_eq, Multiset.rel_map] at hc
    obtain ⟨ds', hf, hperm⟩ := Multiset.rel_coe_iff_exists.mp
      (hc.mono fun x _ y _ h => mk_eq_mk_iff.mp h)
    exact mk_eq_mk_iff.mpr ((RoseTree.permEquiv_node_componentwise hf).trans
      (RoseTree.permEquiv_root_perm hperm))

/-! ### Smart node constructor

The B+ operator (Phase A.7) and the Δ^c trace coproduct (Phase D) both
require building a `Nonplanar α` from a label and an *unordered*
collection of children. The smart constructor `node a cs` does this on
`Multiset (Nonplanar α)`; well-definedness follows from
`RoseTree.permEquiv_root_perm` (children-list permutation invariance).
The characterization `node_mk_tree_list` then bridges back to the
underlying `RoseTree` `node` via `Quotient.mk_out` componentwise. -/

/-- Build a `Nonplanar α` from a label and an unordered multiset of
    children. Implementation: pick a list representative of the
    multiset (`Quotient.liftOn`), then per-child tree representatives
    via `Quotient.out`, and quotient back. -/
noncomputable def node (a : α) (cs : Multiset (Nonplanar α)) : Nonplanar α :=
  Quotient.liftOn cs
    (fun (lst : List (Nonplanar α)) =>
      mk (.node a (lst.map Quotient.out)))
    (fun l1 l2 hperm => by
      apply mk_eq_mk_iff.mpr
      apply RoseTree.permEquiv_root_perm
      exact hperm.map _)

/-- Characterization: building a `Nonplanar α` from a list of tree
    children (lifted to nonplanar via `mk`) agrees with directly lifting
    the tree `node a ps`. -/
theorem node_mk_tree_list (a : α) (ps : List (RoseTree α)) :
    node a (Multiset.ofList (ps.map mk)) = mk (.node a ps) := by
  show mk (.node a ((ps.map mk).map Quotient.out)) = mk (.node a ps)
  apply mk_eq_mk_iff.mpr
  apply RoseTree.permEquiv_node_componentwise
  induction ps with
  | nil => exact List.Forall₂.nil
  | cons p ps ih =>
    refine List.Forall₂.cons ?_ ih
    exact Quotient.exact (Quotient.out_eq (mk p))

/-! #### Sanity tests -/

/-- Sibling order doesn't matter at the root: this is built into the
    `Multiset` carrier. -/
example {α : Type*} (a b c : α) :
    node a (Multiset.ofList [leaf b, leaf c]) =
      node a (Multiset.ofList [leaf c, leaf b]) := by
  congr 1
  exact (Multiset.coe_eq_coe.mpr (List.Perm.swap _ _ _))

/-- A nonplanar binary node built via `node` agrees with the canonical
    tree binary node lifted via `mk`. -/
example {α : Type*} (a b c : α) :
    node a (Multiset.ofList [leaf b, leaf c]) =
      mk (RoseTree.node a [RoseTree.leaf b, RoseTree.leaf c]) := by
  have := node_mk_tree_list a [RoseTree.leaf b, RoseTree.leaf c]
  simpa [leaf] using this

/-! ### Root value and children

Root-level projections, lifted through the quotient: `RoseTree.value` is
`PermEquiv`-invariant on the nose (`value_permEquiv`), and the
mk-image of `RoseTree.children` is invariant as a *multiset* (root swaps
permute the list; recursive steps rewrite a child within its `mk`-class). -/

/-- The mk-image of the root children, as a multiset, is preserved by a
    single `PermStep`. -/
private theorem permStep_children_multiset_eq {t s : RoseTree α}
    (h : RoseTree.PermStep t s) :
    Multiset.ofList (t.children.map mk) = Multiset.ofList (s.children.map mk) := by
  cases h with
  | @swapAtRoot a l r pre post =>
    simp only [RoseTree.children_node]
    exact Multiset.coe_eq_coe.mpr
      (((List.Perm.swap r l post).append_left pre).map mk)
  | @recurse a pre old new post hstep =>
    simp only [RoseTree.children_node, List.map_append, List.map_cons]
    rw [mk_step hstep]

/-- The mk-image of the root children, as a multiset, is preserved by
    `PermEquiv`. -/
theorem permEquiv_children_multiset_eq {t s : RoseTree α}
    (h : RoseTree.PermEquiv t s) :
    Multiset.ofList (t.children.map mk) = Multiset.ofList (s.children.map mk) := by
  induction h with
  | rel _ _ hstep => exact permStep_children_multiset_eq hstep
  | refl _ => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih1 ih2 => exact ih1.trans ih2

/-- The root value of a nonplanar tree. -/
def rootValue : Nonplanar α → α :=
  Nonplanar.lift RoseTree.value (fun _ _ h => RoseTree.value_permEquiv h)

/-- The multiset of root children of a nonplanar tree. -/
def rootChildren : Nonplanar α → Multiset (Nonplanar α) :=
  Nonplanar.lift (fun t => Multiset.ofList (t.children.map mk))
    (fun _ _ h => permEquiv_children_multiset_eq h)

@[simp] theorem rootValue_mk (t : RoseTree α) : rootValue (mk t) = t.value := rfl

@[simp] theorem rootChildren_mk (t : RoseTree α) :
    rootChildren (mk t) = Multiset.ofList (t.children.map mk) := rfl

@[simp] theorem rootValue_node (a : α) (F : Multiset (Nonplanar α)) :
    rootValue (node a F) = a := by
  induction F using Quotient.inductionOn with
  | h lst => rfl

@[simp] theorem rootChildren_node (a : α) (F : Multiset (Nonplanar α)) :
    rootChildren (node a F) = F := by
  induction F using Quotient.inductionOn with
  | h lst =>
    show Multiset.ofList (((lst.map Quotient.out).map mk)) = Multiset.ofList lst
    rw [List.map_map]
    congr 1
    exact (List.map_congr_left (fun x _ => Quotient.out_eq x)).trans (List.map_id lst)

/-- Eta law: every tree is the `node` of its root value and root children. -/
theorem node_eta (t : Nonplanar α) : node (rootValue t) (rootChildren t) = t := by
  induction t using Quotient.inductionOn with
  | h p =>
    cases p with
    | node a cs => exact node_mk_tree_list a cs

/-! ### Node count of a `node` -/

/-- Every tree has at least one vertex (the root). -/
theorem numNodes_pos (t : Nonplanar α) : 0 < t.numNodes := by
  induction t using Quotient.inductionOn with
  | h p => exact RoseTree.numNodes_pos p

/-- Node count of a smart-constructor `node`: one (the root) plus the
    total node count of the children multiset. -/
@[simp] theorem numNodes_node (a : α) (F : Multiset (Nonplanar α)) :
    (node a F).numNodes = 1 + (F.map numNodes).sum := by
  refine Quotient.inductionOn F fun lst => ?_
  show (mk (.node a (lst.map Quotient.out))).numNodes = _
  rw [numNodes_mk, RoseTree.numNodes_node, List.map_map]
  simp only [Multiset.quot_mk_to_coe, Multiset.map_coe, Multiset.sum_coe]
  congr 1
  refine congrArg List.sum (List.map_congr_left fun t _ => ?_)
  show (mk (Quotient.out t)).numNodes = numNodes t
  exact congrArg numNodes (Quotient.out_eq t)

end Nonplanar

end RootedTree

/-! ## Functoriality of `map` under `PermEquiv`

Setup for `Nonplanar.map`: lift `RoseTree.map` through the quotient by
showing it preserves the equivalence relation. Done in two steps:
elementary `PermStep` preservation, then closure under `EqvGen`. -/

namespace RoseTree

variable {α β γ : Type*}

/-- `RoseTree.map` preserves `PermStep`. -/
private theorem permStep_map (f : α → β) {t s : RoseTree α} (h : PermStep t s) :
    PermStep (map f t) (map f s) := by
  induction h with
  | @swapAtRoot a l r pre post =>
    simp only [map_node, List.map_append, List.map_cons]
    exact PermStep.swapAtRoot
  | @recurse a pre old new post _hstep ih =>
    simp only [map_node, List.map_append, List.map_cons]
    exact PermStep.recurse ih

/-- `RoseTree.map` preserves `PermEquiv` (the equivalence closure of
    `PermStep`). Substrate for `Nonplanar.map`. -/
theorem permEquiv_map (f : α → β) {t s : RoseTree α} (h : PermEquiv t s) :
    PermEquiv (map f t) (map f s) := by
  induction h with
  | rel _ _ hstep => exact .of_step (permStep_map f hstep)
  | refl _ => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih1 ih2 => exact ih1.trans ih2

end RoseTree

namespace RootedTree.Nonplanar

variable {α β γ : Type*}

/-! ## Functoriality

Lift `RoseTree.map` through the quotient. Counterpart of `List.map` for
lists: a function `f : α → β` lifts to `Nonplanar α → Nonplanar β` by
relabeling every vertex. -/

/-- Map a function over the vertex labels of a nonplanar rooted tree.
    Lifted from `RoseTree.map` via `Quotient.map`. -/
def map (f : α → β) : Nonplanar α → Nonplanar β :=
  Quotient.map (RoseTree.map f)
    (fun _ _ h => RoseTree.permEquiv_map f h)

/-- Quotient-unfolding for `Nonplanar.map`. Plain lemma (not `@[simp]`)
    since mathlib's generic `Quotient.map_mk` covers the same ground. -/
theorem map_mk (f : α → β) (t : RoseTree α) :
    map f (mk t) = mk (RoseTree.map f t) := rfl

theorem map_leaf (f : α → β) (a : α) :
    map f (leaf a) = leaf (f a) := by
  show map f (mk (RoseTree.leaf a)) = mk (RoseTree.leaf (f a))
  rw [map_mk, RoseTree.map_leaf]

@[simp] theorem map_id (t : Nonplanar α) : map id t = t := by
  refine Quotient.inductionOn t ?_
  intro p
  show map id (mk p) = mk p
  rw [map_mk, RoseTree.id_map]

theorem map_map (f : α → β) (g : β → γ) (t : Nonplanar α) :
    map g (map f t) = map (g ∘ f) t := by
  refine Quotient.inductionOn t ?_
  intro p
  show map g (map f (mk p)) = map (g ∘ f) (mk p)
  rw [map_mk, map_mk, map_mk, RoseTree.comp_map]

/-! ### Counting interactions -/

@[simp] theorem numNodes_map (f : α → β) (t : Nonplanar α) :
    (map f t).numNodes = t.numNodes := by
  refine Quotient.inductionOn t ?_
  intro p
  show (map f (mk p)).numNodes = (mk p).numNodes
  rw [map_mk, numNodes_mk, numNodes_mk, RoseTree.numNodes_map]

@[simp] theorem depth_map (f : α → β) (t : Nonplanar α) :
    (map f t).depth = t.depth := by
  refine Quotient.inductionOn t ?_
  intro p
  show (map f (mk p)).depth = (mk p).depth
  rw [map_mk, depth_mk, depth_mk, RoseTree.depth_map]

@[simp] theorem arity_map (f : α → β) (t : Nonplanar α) :
    (map f t).arity = t.arity := by
  refine Quotient.inductionOn t ?_
  intro p
  show (map f (mk p)).arity = (mk p).arity
  rw [map_mk, arity_mk, arity_mk, RoseTree.arity_map]

@[simp] theorem isLeaf_map (f : α → β) (t : Nonplanar α) :
    (map f t).isLeaf = t.isLeaf := by
  refine Quotient.inductionOn t ?_
  intro p
  show (map f (mk p)).isLeaf = (mk p).isLeaf
  rw [map_mk, isLeaf_mk, isLeaf_mk, RoseTree.isLeaf_map]

@[simp] theorem numLeaves_map (f : α → β) (t : Nonplanar α) :
    (map f t).numLeaves = t.numLeaves := by
  refine Quotient.inductionOn t ?_
  intro p
  show (map f (mk p)).numLeaves = (mk p).numLeaves
  rw [map_mk, numLeaves_mk, numLeaves_mk, RoseTree.numLeaves_map]

end RootedTree.Nonplanar
